"use client";
import { UnitCircleLab } from "./unit-circle-lab";
import { Phs232HarmonicLab } from "./phs-232-harmonic-lab";
import { Phs232EnergyLab } from "./phs-232-energy-lab";
import { Phs232DampingLab } from "./phs-232-damping-lab";
import { RefresherProgrammingLab } from "./refresher-programming-lab";
import { RefresherComplexLab } from "./refresher-complex-lab";
import { RefresherCalculusLab } from "./refresher-calculus-lab";
import { RefresherVectorLab } from "./refresher-vector-lab";
import { ExponentialLab } from "./exponential-lab";
import { LogarithmLab } from "./logarithm-lab";
import { RefresherTrigLab } from "./refresher-trig-lab";
import { RefresherMeasurementLab } from "./refresher-measurement-lab";
import { RefresherExplogLab } from "./refresher-explog-lab";
import { Phs231GravityLab } from "./phs-231-gravity-lab";
import { Phs231WorkLab } from "./phs-231-work-lab";
import { Phs231EnergyLab } from "./phs-231-energy-lab";
import { Phs231ImpulseLab } from "./phs-231-impulse-lab";
import { Phs231ValidationLab } from "./phs-231-validation-lab";
import { Phs231NumericalLab } from "./phs-231-numerical-lab";
import { Phs231MaterialsLab } from "./phs-231-materials-lab";
import { Phs231ElasticLab } from "./phs-231-elasticity-lab";
import { Phs231StaticsLab } from "./phs-231-statics-lab";
import { Phs231RollingLab } from "./phs-231-rolling-lab";
import { Phs231AngularLab } from "./phs-231-angular-lab";
import { Phs231RotationLab } from "./phs-231-rotation-lab";
import { Phs231CollisionLab } from "./phs-231-collision-lab";
import { Phs231CircularLab } from "./phs-231-circular-lab";
import { Phs231DragLab } from "./phs-231-drag-lab";
import { Phs231FrictionLab } from "./phs-231-friction-lab";
import { Phs231ForceLab } from "./phs-231-force-lab";
import { Phs231ProjectileLab } from "./phs-231-projectile-lab";
import { Phs231FrameLab } from "./phs-231-frame-lab";
import { Phs231MotionLab } from "./phs-231-motion-lab";
import { Phs231VectorLab } from "./phs-231-vector-lab";

import Link from "next/link";
import { useState, type FormEvent } from "react";
import type { Lesson, LearningPack } from "@/lib/learning/contracts";
import { saveProgress, useStudy } from "@/lib/study-store";
import { Phs231MeasurementLab } from "./phs-231-measurement-lab";
import { LessonPreparation } from "./lesson-preparation";
import { useStudyDraft } from "@/lib/use-study-draft";
import { AttemptRunner } from "./attempt-runner";
import { Equation, MathText } from "./math-text";
import { EquationBalance } from "./equation-balance";
import { IntervalBuilder } from "./interval-builder";
import { ParabolaExplorer } from "./parabola-explorer";
import { CandidateAudit } from "./candidate-audit";
import { ArithmeticLab } from "./arithmetic-lab";
import { PolynomialLab } from "./polynomial-lab";
import { SimplificationLab } from "./simplification-lab";
import { LineLab } from "./line-lab";
import { TriangleCalculator } from "./triangle-calculator";
import { PiecewiseLab } from "./piecewise-lab";
import { TransformationLab } from "./transformation-lab";
import { CompositionLab } from "./composition-lab";
import { CalibrationLab } from "./calibration-lab";
import { PolynomialEndsLab } from "./polynomial-ends-lab";
import { RootMultiplicityLab } from "./root-multiplicity-lab";
import { DivisionLab } from "./division-lab";
import { RootSearchLab } from "./root-search-lab";
import { RationalFunctionLab } from "./rational-function-lab";
import { SignChartLab } from "./sign-chart-lab";
import { VariationLab } from "./variation-lab";
import { RadicalLab } from "./radical-lab";
import { LogRewriteLab } from "./log-rewrite-lab";
import { ModelLab } from "./model-lab";
import { RotationLab } from "./rotation-lab";
import { RightTriangleLab } from "./right-triangle-lab";
import { courseById } from "@/lib/catalog";
import { GuidedQuestion } from "./question-fields";
import { PageHeading } from "../ui";
import "./learning.css";

export function LessonReader({lesson,previous,next,releaseStatus="building"}:{lesson:Lesson;previous?:{id:string;title:string};next?:{id:string;title:string};releaseStatus?:LearningPack["status"]}) {
  const {data,ready,locked}=useStudy();
  const [message,setMessage]=useState("");
  const [saving,setSaving]=useState(false);
  const draft=useStudyDraft(data.learning.notes[lesson.courseId]?.[lesson.id]??"",`${lesson.courseId}/${lesson.id}`);
  const [removeId,setRemoveId]=useState<string|null>(null);
  const evidence=data.learning.evidence.find(item=>item.courseId===lesson.courseId&&item.lessonId===lesson.id&&item.lessonVersion===lesson.version);
  const attempts=data.learning.attempts.filter(item=>item.courseId===lesson.courseId&&item.lessonId===lesson.id);
  const saveNotes=async(event:FormEvent<HTMLFormElement>)=>{
    event.preventDefault();const note=String(new FormData(event.currentTarget).get("lessonNotes")??"");
    setSaving(true);
    const saved=await saveProgress(current=>({...current,learning:{...current.learning,notes:{...current.learning.notes,[lesson.courseId]:{...current.learning.notes[lesson.courseId],[lesson.id]:note}}}}));
    setSaving(false);
    setMessage(saved?"Lesson notes saved.":"Notes could not be saved. Check the storage notice.");
  };
  const removeAttempt=async()=>{
    const saved=await saveProgress(current=>({...current,learning:{...current.learning,attempts:current.learning.attempts.filter(item=>item.id!==removeId)}}));
    if(saved){setRemoveId(null);setMessage("Attempt details removed. Demonstrated-objective evidence has been kept.");}
  };
  return <><Link className="back-link" href={`/courses/${lesson.courseId}`}>Back to the course</Link><PageHeading eyebrow={`${courseById(lesson.courseId)?.code} · ${lesson.moduleId.toUpperCase()} · Lesson ${lesson.id.slice(-2)}`} title={lesson.title}>{lesson.objective}</PageHeading><div className="lesson-kicker"><span className="pill">{lesson.estimatedMinutes} minutes, at your pace</span><span className="pill neutral">{evidence?"Objective demonstrated":"Ready to study"}</span><span className="pill neutral">{releaseStatus==="building"?"Course under construction":releaseStatus==="preview"?"Technical preview":"Subject reviewed"}</span></div><div className="lesson-layout"><div className="lesson-main"><section className="panel lesson-reading" id="read"><h2>Why this matters</h2><p>{lesson.why}</p><LessonPreparation lesson={lesson}/>{lesson.sections.map(section=><section key={section.heading}><h2>{section.heading}</h2>{section.paragraphs.map((paragraph,index)=><p key={index}><MathText>{paragraph}</MathText></p>)}</section>)}</section><section className="panel" id="examples"><span className="eyebrow">Follow the reasoning</span><h2>Worked examples</h2>{lesson.examples.map(example=><article className="worked-example" key={example.title}><h3>{example.title}</h3><p><MathText>{example.prompt}</MathText></p><ol>{example.steps.map((step,index)=><li key={index}><Equation display>{step.math}</Equation><p>{step.reason}</p></li>)}</ol><p className="notice"><MathText>{example.conclusion}</MathText></p></article>)}</section><section className="panel" id="guided"><span className="eyebrow">Finish a worked example</span><h2>{lesson.guided.title}</h2><p><MathText>{lesson.guided.setup}</MathText></p><ol>{lesson.guided.before.map((text,index)=><li key={index}><MathText>{text}</MathText></li>)}</ol><fieldset disabled={!ready} aria-label="Guided practice controls" style={{border:0,padding:0,margin:0,minWidth:0}}><GuidedQuestion question={lesson.guided.question}/></fieldset><p className="muted">{lesson.guided.after}</p></section><section className="panel" id="investigate"><span className="eyebrow">Predict, change, explain</span><h2>Investigate the relationship</h2><fieldset disabled={!ready} aria-label="Investigation controls" style={{border:0,padding:0,margin:0,minWidth:0}}>{lesson.interaction.kind==="model-lab"?<ModelLab key={lesson.id} activity={lesson.interaction}/> :lesson.interaction.kind==="log-rewrite-lab"?<LogRewriteLab activity={lesson.interaction}/>:lesson.interaction.kind==="logarithm-lab"?<LogarithmLab activity={lesson.interaction}/>:lesson.interaction.kind==="exponential-lab"?<ExponentialLab activity={lesson.interaction}/>:lesson.interaction.kind==="refresher-programming-lab"?<RefresherProgrammingLab activity={lesson.interaction}/>:lesson.interaction.kind==="refresher-complex-lab"?<RefresherComplexLab activity={lesson.interaction}/>:lesson.interaction.kind==="refresher-calculus-lab"?<RefresherCalculusLab activity={lesson.interaction}/>:lesson.interaction.kind==="refresher-vector-lab"?<RefresherVectorLab activity={lesson.interaction}/>:lesson.interaction.kind==="refresher-measurement-lab"?<RefresherMeasurementLab activity={lesson.interaction}/>:lesson.interaction.kind==="refresher-explog-lab"?<RefresherExplogLab activity={lesson.interaction}/>:lesson.interaction.kind==="refresher-trig-lab"?<RefresherTrigLab activity={lesson.interaction}/>:lesson.interaction.kind==="phs231-validation"?<Phs231ValidationLab activity={lesson.interaction}/>:lesson.interaction.kind==="unit-circle-lab"?<UnitCircleLab activity={lesson.interaction}/>:lesson.interaction.kind==="right-triangle-lab"?<RightTriangleLab key={lesson.id} activity={lesson.interaction}/>:lesson.interaction.kind==="rotation-lab"?<RotationLab activity={lesson.interaction}/>:lesson.interaction.kind==="phs232-damping"?<Phs232DampingLab activity={lesson.interaction}/>:lesson.interaction.kind==="phs232-oscillator-energy"?<Phs232EnergyLab activity={lesson.interaction}/>: lesson.interaction.kind==="phs232-harmonic"?<Phs232HarmonicLab activity={lesson.interaction}/>:lesson.interaction.kind==="phs231-numerical"?<Phs231NumericalLab activity={lesson.interaction}/>:lesson.interaction.kind==="phs231-materials"?<Phs231MaterialsLab activity={lesson.interaction}/>:lesson.interaction.kind==="phs231-elasticity"?<Phs231ElasticLab activity={lesson.interaction}/>:lesson.interaction.kind==="phs231-statics"?<Phs231StaticsLab activity={lesson.interaction}/>:lesson.interaction.kind==="phs231-rolling"?<Phs231RollingLab activity={lesson.interaction}/>:lesson.interaction.kind==="phs231-angular"?<Phs231AngularLab activity={lesson.interaction}/>:lesson.interaction.kind==="phs231-rotation"?<Phs231RotationLab activity={lesson.interaction}/>:lesson.interaction.kind==="phs231-collision"?<Phs231CollisionLab activity={lesson.interaction}/>:lesson.interaction.kind==="phs231-impulse"?<Phs231ImpulseLab activity={lesson.interaction}/>:lesson.interaction.kind==="phs231-energy"?<Phs231EnergyLab activity={lesson.interaction}/>:lesson.interaction.kind==="phs231-work"?<Phs231WorkLab activity={lesson.interaction}/>:lesson.interaction.kind==="phs231-gravity"?<Phs231GravityLab activity={lesson.interaction}/>:lesson.interaction.kind==="phs231-circular"?<Phs231CircularLab activity={lesson.interaction}/>:lesson.interaction.kind==="phs231-drag"?<Phs231DragLab activity={lesson.interaction}/>:lesson.interaction.kind==="phs231-friction"?<Phs231FrictionLab activity={lesson.interaction}/>:lesson.interaction.kind==="phs231-forces"?<Phs231ForceLab activity={lesson.interaction}/>:lesson.interaction.kind==="phs231-projectiles"?<Phs231ProjectileLab activity={lesson.interaction}/>:lesson.interaction.kind==="phs231-frames"?<Phs231FrameLab activity={lesson.interaction}/>:lesson.interaction.kind==="phs231-motion"?<Phs231MotionLab activity={lesson.interaction}/>:lesson.interaction.kind==="phs231-vectors"?<Phs231VectorLab activity={lesson.interaction}/>:lesson.interaction.kind==="phs231-measurement"?<Phs231MeasurementLab activity={lesson.interaction}/>:lesson.interaction.kind==="equation-balance"?<EquationBalance activity={lesson.interaction}/>:lesson.interaction.kind==="interval-builder"?<IntervalBuilder activity={lesson.interaction}/>:lesson.interaction.kind==="parabola-explorer"?<ParabolaExplorer activity={lesson.interaction}/>:lesson.interaction.kind==="candidate-audit"?<CandidateAudit activity={lesson.interaction}/>:lesson.interaction.kind==="polynomial-lab"?<PolynomialLab activity={lesson.interaction}/>:lesson.interaction.kind==="simplification-lab"?<SimplificationLab activity={lesson.interaction}/>:lesson.interaction.kind==="line-lab"?<LineLab activity={lesson.interaction}/>:lesson.interaction.kind==="triangle-calculator"?<TriangleCalculator activity={lesson.interaction}/>:lesson.interaction.kind==="piecewise-lab"?<PiecewiseLab activity={lesson.interaction}/>:lesson.interaction.kind==="transformation-lab"?<TransformationLab activity={lesson.interaction}/>:lesson.interaction.kind==="composition-lab"?<CompositionLab activity={lesson.interaction}/>:lesson.interaction.kind==="radical-lab"?<RadicalLab activity={lesson.interaction}/>:lesson.interaction.kind==="variation-lab"?<VariationLab activity={lesson.interaction}/>:lesson.interaction.kind==="sign-chart-lab"?<SignChartLab activity={lesson.interaction}/>:lesson.interaction.kind==="rational-function-lab"?<RationalFunctionLab activity={lesson.interaction}/>:lesson.interaction.kind==="root-search-lab"?<RootSearchLab activity={lesson.interaction}/>:lesson.interaction.kind==="division-lab"?<DivisionLab activity={lesson.interaction}/>:lesson.interaction.kind==="root-multiplicity-lab"?<RootMultiplicityLab activity={lesson.interaction}/>:lesson.interaction.kind==="polynomial-ends-lab"?<PolynomialEndsLab activity={lesson.interaction}/>:lesson.interaction.kind==="calibration-lab"?<CalibrationLab activity={lesson.interaction}/>:<ArithmeticLab activity={lesson.interaction}/>}</fieldset></section><section className="panel" id="practice"><span className="eyebrow">Apply your understanding</span><h2>Practice and checkpoint</h2><AttemptRunner lesson={lesson}/></section><section className="panel" id="review"><h2>Carry these ideas forward</h2><ul>{lesson.summary.map((item,index)=><li key={index}><MathText>{item}</MathText></li>)}</ul><div className="notice"><strong>Recall it later</strong><p>{lesson.retrieval}</p>{evidence&&<p>Next review: {new Date(evidence.nextReviewAt).toLocaleDateString()}. Completing the lesson and retaining it over time are separate checks.</p>}</div><h3 className="section-space">Read further</h3>{lesson.readings.map(reading=><p key={reading.url}><a className="text-link" href={reading.url} target="_blank" rel="noreferrer">{reading.title}</a><br/><span className="muted">{reading.purpose}</span></p>)}</section><section className="panel" id="notes"><h2>Your lesson notes</h2><form onSubmit={saveNotes}><div className="field"><label htmlFor="lesson-notes">Reasoning, questions, or a worked solution to revisit</label><textarea id="lesson-notes" name="lessonNotes" value={draft.value} onChange={event=>draft.setValue(event.target.value)} maxLength={5000} disabled={!ready||locked}/></div><button className="button secondary" disabled={!ready||locked||saving}>{saving?"Saving notes...":"Save lesson notes"}</button></form><p role="status" className="form-status">{message}</p>{draft.changed&&<div className="notice warning" role="status"><p>Saved lesson notes changed while you were editing. Your draft has been kept.</p><button className="button secondary" onClick={draft.loadSaved}>Load saved lesson notes</button></div>}{attempts.length>0&&<details className="section-space"><summary>Saved attempt history ({attempts.length})</summary><p className="muted">Export a backup in Settings before removing work you want to keep.</p><ul className="lesson-history">{attempts.map(attempt=><li key={attempt.id}><span>{attempt.mode=== "checkpoint"?"Checkpoint":"Practice"} · {attempt.status}<small>{new Date(attempt.startedAt).toLocaleString()}</small></span><button className="button secondary" onClick={()=>setRemoveId(attempt.id)} disabled={locked}>Remove attempt details</button></li>)}</ul>{removeId&&<div className="notice warning"><p>Remove this attempt&apos;s questions and answers? Any previously demonstrated-objective evidence will remain.</p><div className="form-actions"><button className="button danger" onClick={removeAttempt}>Confirm removal</button><button className="button secondary" onClick={()=>setRemoveId(null)}>Keep attempt</button></div></div>}</details>}</section><nav className="attempt-navigation" aria-label="Adjacent lessons">{previous?<Link className="button secondary" href={`/courses/${lesson.courseId}/lessons/${previous.id}`}>Previous: {previous.title}</Link>:<Link className="button secondary" href={`/courses/${lesson.courseId}`}>Course overview</Link>}{next&&<Link className="button" href={`/courses/${lesson.courseId}/lessons/${next.id}`}>Next: {next.title}</Link>}</nav></div><aside className="lesson-nav"><span className="eyebrow">In this lesson</span><nav aria-label="Lesson sections">{[["read","Read and understand"],["examples","Worked examples"],["guided","Guided practice"],["investigate","Interactive investigation"],["practice","Practice and checkpoint"],["review","Summary and recall"],["notes","Your notes and history"]].map(([id,label])=><a key={id} href={`#${id}`}>{label}</a>)}</nav></aside></div></>;
}
