"use client";
import Link from "next/link";
import { useState } from "react";
import { useStudy } from "@/lib/study-store";
import { angleInputs,calculatorCheck,entryCases,checkPrediction,toolNumber,createPracticeFile,comparePracticeFile,type AngleMode,type CalculatorOperation,type PracticeFile } from "@/lib/learning/refreshers/orientation-tools";
export function CalculatorCheckLab(){
 const {ready}=useStudy(),[mode,setMode]=useState<AngleMode>("degrees"),[operation,setOperation]=useState<CalculatorOperation>("sin"),[input,setInput]=useState("thirty"),[prediction,setPrediction]=useState(""),[message,setMessage]=useState(""),[result,setResult]=useState<ReturnType<typeof calculatorCheck>|null>(null),[entry,setEntry]=useState(0),[entryPrediction,setEntryPrediction]=useState(""),[entryMessage,setEntryMessage]=useState(""),[entryShown,setEntryShown]=useState(false);
 const clear=()=>{setMessage("");setResult(null);};
 function check(){try{const model=calculatorCheck(operation,mode,angleInputs.find(i=>i.id===input)!.value),feedback=checkPrediction(prediction,model.result);setMessage(feedback);setResult(feedback.startsWith("Enter")?null:model);}catch(error){setResult(null);setMessage(error instanceof Error?error.message:"Check the input.");}}
 return <section className="panel" id="tool-lab"><span className="eyebrow">Predict, compare, explain</span><h2>Calculator check</h2><p>Use known values to inspect angle mode and expression grouping. These local practice comparisons do not create a completion record. The supplied operations have explicit conventions; a different calculator may use different keys.</p>
 <fieldset disabled={!ready} style={{border:0,padding:0,minWidth:0}}><legend>Angle and inverse-function check</legend><div className="field"><label htmlFor="orientation-operation">Operation</label><select id="orientation-operation" value={operation} onChange={e=>{setOperation(e.target.value as CalculatorOperation);clear();}}><option value="sin">Sine</option><option value="cos">Cosine</option><option value="asin">Inverse sine (principal angle)</option></select></div><div className="field"><label htmlFor="orientation-mode">Angle mode</label><select id="orientation-mode" value={mode} onChange={e=>{setMode(e.target.value as AngleMode);clear();}}><option value="degrees">Degrees</option><option value="radians">Radians</option></select></div><div className="field"><label htmlFor="orientation-input">Numeric input</label><select id="orientation-input" value={input} onChange={e=>{setInput(e.target.value);clear();}}>{angleInputs.map(i=><option value={i.id} key={i.id}>{i.label}</option>)}</select><small>For sine/cosine, mode supplies the angle unit. For inverse sine, input is dimensionless and mode specifies the output angle unit.</small></div><div className="field"><label htmlFor="orientation-prediction">Predicted angle-check result</label><input id="orientation-prediction" value={prediction} maxLength={100} onChange={e=>{setPrediction(e.target.value);clear();}}/><small>Enter a decimal or scientific notation, such as 0.5 or 5e-1. Approximate π/6 as 0.523599 when predicting a radian result.</small></div><button className="button secondary" onClick={check}>Compare angle prediction</button></fieldset><p role="status" data-testid="angle-feedback">{message}</p>{result&&<div className="notice"><p><strong>Computed result: {toolNumber(result.result)} ({result.unit})</strong></p><p>{result.explanation}</p><p>Displayed decimals are approximations. Explain the result using a known angle before relying on the tool.</p></div>}
 <fieldset disabled={!ready} style={{border:0,padding:0,minWidth:0}} className="section-space"><legend>Grouping and scientific notation</legend><div className="field"><label htmlFor="orientation-entry">Expression to inspect</label><select id="orientation-entry" value={entry} onChange={e=>{setEntry(Number(e.target.value));setEntryMessage("");setEntryShown(false);}}>{entryCases.map((c,i)=><option value={i} key={c.id}>{c.label}</option>)}</select></div><div className="field"><label htmlFor="orientation-entry-prediction">Predicted expression result</label><input id="orientation-entry-prediction" value={entryPrediction} maxLength={100} onChange={e=>{setEntryPrediction(e.target.value);setEntryMessage("");setEntryShown(false);}}/></div><button className="button secondary" onClick={()=>{const feedback=checkPrediction(entryPrediction,entryCases[entry].result);setEntryMessage(feedback);setEntryShown(!feedback.startsWith("Enter"));}}>Compare expression prediction</button></fieldset><p role="status" data-testid="entry-feedback">{entryMessage}</p>{entryShown&&<p className="notice">Result: {toolNumber(entryCases[entry].result)}. {entryCases[entry].explanation} Angle mode has no effect on this arithmetic expression.</p>}</section>;
}
export function FileRoundTripLab(){
 const {ready}=useStudy(),[note,setNote]=useState("My practice copy contains this marker note."),[revision,setRevision]=useState(1),[expected,setExpected]=useState<PracticeFile|null>(null),[message,setMessage]=useState(""),[checking,setChecking]=useState(false);
 function download(){
  if(note.trim().length<10){setMessage("Write a specific practice note of at least 10 characters.");return;}
  const record=createPracticeFile(note,revision,"orientation-"+crypto.randomUUID()),url=URL.createObjectURL(new Blob([JSON.stringify(record,null,2)],{type:"application/json"})),anchor=document.createElement("a");
  anchor.href=url;anchor.download=`f12-practice-r${String(revision).padStart(2,"0")}.json`;anchor.click();window.setTimeout(()=>URL.revokeObjectURL(url),1000);setExpected(record);setMessage("Practice file prepared for download. Locate it, reopen it below, and compare the marker and note.");
 }
 async function reopen(input:HTMLInputElement){
  const file=input.files?.[0];if(!file||!expected)return;setChecking(true);setMessage("");
  try{if(file.size>20_000)throw Error("Choose the small practice JSON file (20 KB maximum).");const record=comparePracticeFile(await file.text(),expected);setMessage(`Reopen check passed: revision ${record.revision}, marker and note match. Record the filename and what you verified in your practical work. This is a practice artifact, not a progress backup.`);}catch(error){setMessage(error instanceof Error?error.message:"The file could not be read.");}finally{setChecking(false);input.value="";}
 }
 return <section className="panel" id="tool-lab"><span className="eyebrow">A harmless file rehearsal</span><h2>Save and reopen a practice file</h2><p>This exercise downloads a small JSON document containing only your practice note, revision and marker. The selected file is read in this browser. It does not replace your progress or record completion.</p><fieldset disabled={!ready||checking} style={{border:0,padding:0,minWidth:0}}><legend>Create a practice copy</legend><div className="field"><label htmlFor="practice-file-note">Practice file note</label><textarea id="practice-file-note" value={note} maxLength={200} onChange={e=>{setNote(e.target.value);setMessage("");}}/><small>Use 10–200 characters. Use fictional study content for this exercise.</small></div><div className="field"><label htmlFor="practice-file-revision">Practice file revision</label><select id="practice-file-revision" value={revision} onChange={e=>{setRevision(Number(e.target.value));setMessage("");}}>{[1,2,3].map(r=><option value={r} key={r}>{r}</option>)}</select></div><button className="button secondary" onClick={download}>Download practice file</button></fieldset>
 {expected&&<div className="notice section-space" style={{overflowWrap:"anywhere"}}><h3>Expected downloaded contents</h3><p>Revision: {expected.revision}. Marker: <code>{expected.marker}</code>.</p><p>Note: {expected.note}</p><p>Editing the fields above does not change a file already downloaded. Download again to make a new copy with a new marker.</p><div className="field"><label htmlFor="practice-file-reopen">Reopen the downloaded practice file</label><input id="practice-file-reopen" type="file" accept=".json,application/json" disabled={checking} onChange={e=>void reopen(e.currentTarget)}/><small style={{color:"var(--ink)"}}>Choose the file from this round, at most 20 KB. A mismatch leaves your progress unchanged.</small></div></div>}
 <p role="status">{checking?"Reading the selected file...":message}</p><p>For real progress, use <Link className="text-link" href="/settings">Settings: export and review a progress backup</Link>. Save your practical draft before leaving this lesson. Review a real import before choosing replacement; this practice file is not compatible with that import.</p></section>;
}
