"use client";

import { useId, useState } from "react";
import { travelingWaveInputSchema, travelingWavePatternPosition, travelingWavePoint, travelingWaveRecording, travelingWaveRun, type TravelingWaveActivity, type TravelingWavePoint, type TravelingWaveRun } from "@/lib/learning/phs-232-traveling-wave";
import { approximateExact, parseExact, realExact } from "@/lib/learning/exact-number";
import { MathText } from "./math-text";
import styles from "./phs-232-traveling-wave-lab.module.css";
import "./phs-232.css";

const display = (n: number) => n !== 0 && (Math.abs(n) < .001 || Math.abs(n) > 1e6) ? n.toExponential(6) : String(Number(n.toPrecision(8)));
const tick = (n: number) => n !== 0 && (Math.abs(n) < .01 || Math.abs(n) >= 10000) ? n.toExponential(1).replace(".0e", "e") : String(Number(n.toPrecision(3)));
const controls = [
  ["tension", "Wave tension (N)", .1, 100, .1], ["density", "Wave linear density (kg/m)", .001, 2, .001],
  ["amplitude", "Wave displacement amplitude (m)", 0, .1, .001], ["frequency", "Source frequency (Hz; harmonic only)", .1, 20, .1],
  ["phase", "Initial phase (rad; harmonic only)", -2 * Math.PI, 2 * Math.PI, .01], ["width", "Gaussian width (m; pulse only)", .1, 5, .1],
  ["regionWidth", "Control-region width (characteristic lengths)", .25, 3, .05], ["duration", "Record duration (characteristic times)", .25, 8, .25],
] as const;
const pointHeadings = ["Row", "x (m)", "t (s)", "y (m)", "y_t (m/s)", "y_tt (m/s²)", "y_x", "y_xx (1/m)", "K/length (J/m)", "U/length (J/m)", "u (J/m)", "P toward +x (W)"];
const pointRow = (s: TravelingWavePoint, i: number) => [i, s.position, s.time, s.displacement, s.velocity, s.acceleration, s.slope, s.curvature, s.kinetic, s.potential, s.energyDensity, s.power];

function WaveTable({ label, headings, rows }: { label: string; headings: string[]; rows: number[][] }) {
  const id = useId(), [page, setPage] = useState(0), pages = Math.ceil(rows.length / 64);
  return <div>{pages > 1 && <><div className="field"><label htmlFor={id}>{label} page</label><select id={id} value={page} onChange={e => setPage(Number(e.target.value))}>{Array.from({ length: pages }, (_, i) => <option key={i} value={i}>{i + 1} of {pages}: rows {64 * i}–{Math.min(rows.length - 1, 64 * i + 63)}</option>)}</select></div><div className="form-actions"><button className="button secondary" disabled={page === 0} onClick={() => setPage(page - 1)}>Previous {label.toLowerCase()} page</button><button className="button secondary" disabled={page === pages - 1} onClick={() => setPage(page + 1)}>Next {label.toLowerCase()} page</button></div></>}
    <div className={styles.table} role="region" aria-label={label + "; scroll horizontally if needed"} tabIndex={0}><table><caption>{label}: {rows.length} rows; page {page + 1} of {pages}</caption><thead><tr>{headings.map(h => <th key={h} scope="col">{h}</th>)}</tr></thead><tbody>{rows.slice(page * 64, page * 64 + 64).map((row, i) => <tr key={i}><th scope="row">{display(row[0])}</th>{row.slice(1).map((n, j) => <td key={j}>{display(n)}</td>)}</tr>)}</tbody></table></div>
  </div>;
}

type Trace = { points: [number, number][]; color: string; dash?: string };
function WavePlot({ title, xLabel, yLabel, domain, extent, traces, caption, verticals = [], markers = [] }: {
  title: string; xLabel: string; yLabel: string; domain: [number, number]; extent: [number, number]; traces: Trace[]; caption: string;
  verticals?: number[]; markers?: { x: number; y: number; pattern?: boolean }[];
}) {
  const id = useId(), x = (v: number) => 90 + 285 * (v - domain[0]) / (domain[1] - domain[0]), y = (v: number) => 180 - 140 * (v - extent[0]) / (extent[1] - extent[0]);
  return <figure><svg viewBox="0 0 400 265" role="img" aria-labelledby={id}><title id={id}>{title}</title>
    <path d="M90 35V180H385" fill="none" stroke="#a1aba7"/>{extent[0] < 0 && extent[1] > 0 && <line x1="90" x2="385" y1={y(0)} y2={y(0)} stroke="#a1aba7"/>}
    <text x="90" y="25">{yLabel}</text><text x="8" y="46">{tick(extent[1])}</text><text x="8" y="186">{tick(extent[0])}</text>
    <text x="90" y="215">{tick(domain[0])}</text><text x="375" y="215" textAnchor="end">{tick(domain[1])}</text><text x="232" y="248" textAnchor="middle">{xLabel}</text>
    {verticals.filter(v => v >= domain[0] && v <= domain[1]).map((v, i) => <line key={i} x1={x(v)} x2={x(v)} y1="35" y2="180" stroke="#293f36" strokeDasharray="2 3"/>)}
    {traces.map((trace, i) => <polyline key={i} points={trace.points.map(([a, b]) => x(a) + "," + y(b)).join(" ")} fill="none" stroke={trace.color} strokeWidth="2.5" strokeDasharray={trace.dash}/>)}
    {markers.filter(m => m.x >= domain[0] && m.x <= domain[1]).map((m, i) => m.pattern ? <path key={i} d={"M" + x(m.x) + " " + (y(m.y) - 7) + "l-6 10h12Z"} fill="#8c411e"/> : <circle key={i} cx={x(m.x)} cy={y(m.y)} r="5" fill="#176582"/>)}
  </svg><figcaption>{caption}</figcaption></figure>;
}

function WaveResults({ run }: { run: TravelingWaveRun }) {
  const id = useId(), [positionIndex, setPositionIndex] = useState(128), [timeIndex, setTimeIndex] = useState(0), [resolution, setResolution] = useState("fine"), [timeStep, setTimeStep] = useState(.125), [spaceStep, setSpaceStep] = useState(.125);
  const p = run.model, time = run.fine[timeIndex].time, position = -p.viewHalfWidth + 2 * p.viewHalfWidth * positionIndex / 256;
  const snapshot = Array.from({ length: 257 }, (_, i) => travelingWavePoint(p, -p.viewHalfWidth + 2 * p.viewHalfWidth * i / 256, time));
  const history = run.fine.map(row => travelingWavePoint(p, position, row.time)), probe = history[timeIndex], pattern = travelingWavePatternPosition(p, time);
  const chosen = resolution === "fine" ? run.fine : run.coarse, amplitudeScale = 1.1 * p.amplitude || .01;
  const energyMin = Math.min(0, ...run.fine.flatMap(r => [r.change, r.netWork])), energyMax = Math.max(0, ...run.fine.flatMap(r => [r.change, r.netWork])), margin = (energyMax - energyMin) * .07 || .001;
  const recording = p.profile === "harmonic" ? travelingWaveRecording(p, timeStep, spaceStep, position) : null;
  const unit = p.profile === "harmonic" ? "wavelength" : "pulse width", timeName = p.profile === "harmonic" ? "period" : "width-transit time";
  return <div className={styles.results}><h3>Wave evidence</h3>
    <p>Positive medium speed c={display(p.speed)} m/s; maximum slope={display(p.maximumSlope)}. One characteristic length is {display(p.scale)} m ({unit}), and one characteristic time is {display(p.timeUnit)} s ({timeName}). The fixed control region is [{display(run.left)}, {display(run.right)}] m; plot edges are not physical boundaries.</p>
    {p.profile === "harmonic" ? <p>k={display(p.waveNumber!)} rad/m; omega={display(p.omega!)} rad/s; mean u={display(p.meanDensity!)} J/m; signed mean P={display(p.meanPower!)} W. These means apply to the single harmonic wave over a full period or wavelength.</p> : <p>The Gaussian pulse has no wavelength, harmonic frequency or oscillation period. Its full-line energy is {display(p.totalPulseEnergy!)} J. The displayed finite region can contain only part of it.</p>}
    <div className="phs232-controls"><div className="field"><label htmlFor={id + "-position"}>Tagged material-point position index: {positionIndex}</label><input id={id + "-position"} type="range" min="0" max="256" step="1" value={positionIndex} onChange={e => setPositionIndex(Number(e.target.value))}/><div className="form-actions"><button className="button secondary" onClick={() => setPositionIndex(Math.max(0, positionIndex - 1))} disabled={positionIndex === 0}>Previous wave position</button><button className="button secondary" onClick={() => setPositionIndex(Math.min(256, positionIndex + 1))} disabled={positionIndex === 256}>Next wave position</button></div></div>
      <div className="field"><label htmlFor={id + "-time"}>Wave time index: {timeIndex}</label><input id={id + "-time"} type="range" min="0" max={run.fine.length - 1} step="1" value={timeIndex} onChange={e => setTimeIndex(Number(e.target.value))}/><div className="form-actions"><button className="button secondary" onClick={() => setTimeIndex(Math.max(0, timeIndex - 1))} disabled={timeIndex === 0}>Previous wave time</button><button className="button secondary" onClick={() => setTimeIndex(Math.min(run.fine.length - 1, timeIndex + 1))} disabled={timeIndex === run.fine.length - 1}>Next wave time</button></div></div></div>
    <p>Use Arrow, Home and End keys on either slider. Changing time keeps the tagged material point&apos;s x fixed. No animation is needed.</p>
    <p data-testid="wave-probe">Probe: x={display(position)} m; t={display(time)} s; y={display(probe.displacement)} m; y_t={display(probe.velocity)} m/s; y_tt={display(probe.acceleration)} m/s²; y_x={display(probe.slope)}; y_xx={display(probe.curvature)} 1/m; u={display(probe.energyDensity)} J/m; signed P={display(probe.power)} W.</p>
    <p data-testid="wave-pattern">{pattern === null ? "Zero amplitude: there is no identifiable crest, pulse or observed direction." : (p.profile === "harmonic" ? "Tracked n=0 positive crest" : "Tracked pulse center") + ": x=" + display(pattern) + " m, moving at " + display(p.direction * p.speed) + " m/s. " + (Math.abs(pattern) > p.viewHalfWidth ? "It is outside this view; it has not been wrapped to a different crest." : "The brown triangle marks this pattern location.")}</p>
    <div className="phs232-plots">
      <WavePlot title="Spatial wave profile at the selected time. Blue circle is a tagged material point; brown triangle is the tracked crest or pulse center. Dotted lines bound the energy control region. All derivatives and energy values appear in the snapshot table." xLabel="Position x (m)" yLabel="Displacement (m)" domain={[-p.viewHalfWidth, p.viewHalfWidth]} extent={[-amplitudeScale, amplitudeScale]} traces={[{ points: snapshot.map(s => [s.position, s.displacement]), color: "#176582" }]} verticals={[run.left, run.right]} markers={[{ x: position, y: probe.displacement }, ...(pattern === null ? [] : [{ x: pattern, y: p.amplitude, pattern: true }])]} caption="A material point moves transversely at fixed x; a crest or pulse center translates along x. Blue circle = tagged point, brown triangle = tracked pattern, dotted lines = fixed control-region boundaries. Shape and vertical scale are exaggerated relative to physical aspect ratio."/>
      <WavePlot title="Displacement of the tagged material point versus time. The probe point and dotted time line match the spatial snapshot. The time-history table supplies velocity, acceleration and energy as well." xLabel="Time (s)" yLabel="Local y (m)" domain={[0, run.end]} extent={[-amplitudeScale, amplitudeScale]} traces={[{ points: history.map(s => [s.time, s.displacement]), color: "#176582" }]} verticals={[time]} markers={[{ x: time, y: probe.displacement }]} caption="Follow one material coordinate through time. Harmonic motion repeats; passage of a pulse generally does not. Time and position probes can move independently, and the full time-history table remains available."/>
      <WavePlot title="Energy change in the fixed region and independently integrated net boundary work. Solid blue is E minus E0; dashed brown is left-boundary work minus right-boundary work. Both can be signed." xLabel="Time (s)" yLabel="Change / work (J)" domain={[0, run.end]} extent={[energyMin - margin, energyMax + margin]} traces={[{ points: run.fine.map(r => [r.time, r.change]), color: "#176582" }, { points: run.fine.map(r => [r.time, r.netWork]), color: "#8c411e", dash: "6 4" }]} verticals={[time]} caption="Solid blue = E−E0 from spatial energy integration. Dashed brown = W_left−W_right from separate time integration of boundary power. Agreement is tested through their residual and refinement; net work is not defined from the energy difference."/>
    </div>
    <h4>Independent energy account</h4><p>Both boundary powers are signed toward +x. Stored energy obeys ΔE=W_left−W_right, including for leftward travel. Separate Simpson quadratures integrate energy in space and boundary power in time; midpoint evaluations supplement each time interval. Refining both grids compares numerical approximations, not physical measurement uncertainty.</p>
    <WaveTable label="Wave convergence" headings={["Resolution", "Spatial panels", "Time intervals", "dt (s)", "Final E (J)", "Final net work (J)", "Largest balance residual (J)"]} rows={[[1, run.input.intervals, run.input.intervals, run.end / run.input.intervals, run.coarse.at(-1)!.energy, run.coarse.at(-1)!.netWork, run.coarseResidual], [2, 2 * run.input.intervals, 2 * run.input.intervals, run.end / (2 * run.input.intervals), run.fine.at(-1)!.energy, run.fine.at(-1)!.netWork, run.fineResidual]]}/>
    <p>Resolution 1 is coarse; resolution 2 is refined. Largest aligned energy difference={display(run.energyDifference)} J; net-work difference={display(run.workDifference)} J. They are comparison evidence, not guaranteed error bounds. At the selected time, E={display(run.fine[timeIndex].energy)} J and balance residual={display(run.fine[timeIndex].residual)} J.</p>
    <details><summary>All spatial derivatives and energy values</summary><p>Every one of the 257 plotted positions at the selected time, including both endpoints.</p><WaveTable label="Wave snapshot" headings={pointHeadings} rows={snapshot.map(pointRow)}/></details>
    <details><summary>All tagged-point time states</summary><p>Every refined time at the selected material position.</p><WaveTable label="Wave time history" headings={pointHeadings} rows={history.map(pointRow)}/></details>
    <details><summary>All boundary work and stored-energy records</summary><div className="field"><label htmlFor={id + "-resolution"}>Wave energy record resolution</label><select id={id + "-resolution"} value={resolution} onChange={e => setResolution(e.target.value)}><option value="coarse">Coarse</option><option value="fine">Refined</option></select></div>
      <WaveTable key={resolution} label="Wave energy ledger" headings={["Row", "t (s)", "E (J)", "E−E0 (J)", "P_left (W)", "P_right (W)", "W_left (J)", "W_right (J)", "Net work (J)", "Residual (J)"]} rows={chosen.map(r => [r.index, r.time, r.energy, r.change, r.leftPower, r.rightPower, r.leftWork, r.rightWork, r.netWork, r.residual])}/>
    </details>
    {recording && <details><summary>Periodic snapshots and sampling ambiguity</summary><p>This panel records a separate pair of snapshots at t=0 and t=delta_t, plus nine stroboscopic samples of the currently tagged material coordinate. These times are distinct from the main probe. The equation supplies the true direction; sparse recordings need additional assumptions.</p>
      <div className="phs232-controls"><div className="field"><label htmlFor={id + "-dt"}>Recording time step (periods)</label><select id={id + "-dt"} value={timeStep} onChange={e => setTimeStep(Number(e.target.value))}>{[.125, .5, .75, 1, 1.25].map(v => <option key={v} value={v}>{v}</option>)}</select></div><div className="field"><label htmlFor={id + "-dx"}>Recording position step (wavelengths)</label><select id={id + "-dx"} value={spaceStep} onChange={e => setSpaceStep(Number(e.target.value))}>{[.125, .5, .75, 1].map(v => <option key={v} value={v}>{v}</option>)}</select></div></div>
      <p data-testid="wave-alias">delta_t={display(recording.deltaTime)} s; delta_x={display(recording.deltaPosition)} m. Model translation={display(recording.trueShift)} m. {p.amplitude === 0 ? "Zero amplitude makes every shift indistinguishable." : recording.halfAmbiguity ? "Half-wavelength tie: both +lambda/2 and -lambda/2 give the same periodic profile. No unique principal signed shift exists." : "Principal signed shift=" + display(recording.principalShift!) + " m; apparent principal velocity=" + display(recording.apparentVelocity!) + " m/s."}</p>
      <p>Adding any integer wavelength gives the same complete periodic snapshot. A justified strict bound |shift|&lt;lambda/2 selects a unique principal shift; a bound smaller than one wavelength alone does not. Coarse spatial samples can introduce further ambiguity. At one sample per period, a moving wave can appear frozen. Half-period samples cannot by themselves establish travel direction.</p>
      <WaveTable label="Wave recorded snapshots" headings={["x (m)", "y at t=0 (m)", "y at delta_t (m)"]} rows={recording.spatial.map(r => [r.position, r.first, r.second])}/>
      <WaveTable label="Wave stroboscopic record" headings={["Sample", "t (s)", "x (m)", "Recorded y (m)"]} rows={recording.temporal.map((r, i) => [i, r.time, r.position, r.displacement])}/>
    </details>}
    <h4>Build a reproducible investigation record</h4><ol><li>Record the parameters, units, slope restriction and predictions. Compare the tagged point with the tracked pattern at a crest and a steep slope.</li><li>Reverse direction with the same harmonic phase, then double amplitude within the slope guard. Compare signed power, nonnegative energy and the amplitude-squared prediction.</li><li>Change tension at fixed density, source frequency and amplitude. Record the resulting speed and wavelength; explain which controls stayed fixed.</li><li>Switch to a Gaussian pulse and follow energy entering and leaving the fixed region. Account for both signed boundary works and compare the two quadrature resolutions.</li><li>In harmonic mode compare a resolved record with three-quarter-period and full-period samples. Explain an apparent reversal or frozen record using actual table entries.</li></ol>
    <details><summary>Traveling-wave investigation self-check rubric</summary><p>Score each item 0 for missing or incorrect, 1 for partial and 2 for complete evidence. Revise every score below 2. This proposed self-check is not an official grade and does not award objective evidence.</p><ol><li><strong>Conditions:</strong> all parameters, units, direction, model assumptions and slope restriction are reproducible.</li><li><strong>Motion:</strong> derivatives and recorded states distinguish material-point motion from tracked-pattern translation.</li><li><strong>Energy:</strong> both signed boundaries, stored energy and numerical refinement support the account.</li><li><strong>Comparison:</strong> one controlled change has a quantitative prediction and observed numerical evidence.</li><li><strong>Limits:</strong> the record explains sampling ambiguity and the difference between an ideal simulation, approximation error and physical experimental evidence.</li></ol></details>
  </div>;
}

export function Phs232TravelingWaveLab({ activity }: { activity: TravelingWaveActivity }) {
  const id = useId(), [values, setValues] = useState(controls.map(([key]) => String(activity.initial[key]))), [profile, setProfile] = useState(activity.initial.profile), [direction, setDirection] = useState(String(activity.initial.direction)), [intervals, setIntervals] = useState(String(activity.initial.intervals));
  const [speed, setSpeed] = useState(""), [velocity, setVelocity] = useState(""), [power, setPower] = useState(""), [message, setMessage] = useState(""), [run, setRun] = useState<TravelingWaveRun | null>(null), [generation, setGeneration] = useState(0);
  const clear = () => { setRun(null); setMessage(""); setSpeed(""); setVelocity(""); setPower(""); };
  const reveal = () => {
    try {
      if (values.some(value => !value.trim())) throw Error("Complete every model input; an empty value is not zero.");
      const parsed = travelingWaveInputSchema.safeParse({ ...Object.fromEntries(controls.map(([key], i) => [key, Number(values[i])])), profile, direction: Number(direction), intervals: Number(intervals) });
      if (!parsed.success) throw Error("Use the labeled ranges, at most four harmonic periods, and maximum slope at most 0.2. Reduce amplitude or frequency, or adjust the medium or pulse width.");
      if (!speed.trim() || !velocity.trim() || !power) throw Error("Predict the wave speed, initial tagged-point velocity and power direction before revealing.");
      const numerical = (text: string) => { const exact = parseExact(text); if (!realExact(exact)) throw Error("Predictions must be finite real numbers in the labeled units."); const value = approximateExact(exact).real; if (!Number.isFinite(value)) throw Error("Use finite real predictions."); return value; };
      const predictedSpeed = numerical(speed), predictedVelocity = numerical(velocity), result = travelingWaveRun(parsed.data), point = travelingWavePoint(result.model, 0, 0);
      const close = (a: number, b: number) => Math.abs(a - b) <= Math.max(1e-6, Math.abs(b) * 1e-6), expectedPower = result.model.amplitude === 0 ? "zero" : result.model.direction === 1 ? "positive" : "negative";
      const missed = [close(predictedSpeed, result.model.speed) ? "" : "medium speed", close(predictedVelocity, point.velocity) ? "" : "local transverse velocity", power === expectedPower ? "" : "power direction"].filter(Boolean);
      setRun(result); setGeneration(generation + 1);
      setMessage(missed.length ? "Revisit " + missed.join(", ") + ". Use c=sqrt(F_T/mu), differentiate the stated profile at fixed x=0,t=0, and keep signed energy transport distinct from nonnegative stored energy. The records below let you revise your prediction." : "Your predictions agree with the model. Compare the material point, translated pattern and independently integrated boundary work.");
    } catch (error) { setRun(null); setMessage(error instanceof Error ? error.message : "Check the inputs."); }
  };
  return <div className="phs232-investigation"><p><MathText>{activity.prompt}</MathText></p><p className="muted">Simulation of a uniform ideal string with constant tension and small slope, without damping, bending stiffness or reflection. No physical experiment or official equipment is assigned. Controls reset on reload; save parameters and representative records in lesson notes.</p>
    <div className="phs232-controls"><div className="field"><label htmlFor={id + "-profile"}>Traveling profile</label><select id={id + "-profile"} value={profile} onChange={e => { setProfile(e.target.value as "harmonic" | "gaussian"); clear(); }}><option value="harmonic">Harmonic wavetrain</option><option value="gaussian">Gaussian pulse</option></select></div><div className="field"><label htmlFor={id + "-direction"}>Wave direction</label><select id={id + "-direction"} value={direction} onChange={e => { setDirection(e.target.value); clear(); }}><option value="1">Rightward (+x)</option><option value="-1">Leftward (-x)</option></select></div>
      {controls.map(([key, label, min, max, step], i) => <div className="field" key={key}><label htmlFor={id + "-" + key}>{label}</label><input id={id + "-" + key} type="number" min={min} max={key === "duration" && profile === "harmonic" ? 4 : max} step={step} value={values[i]} onChange={e => { setValues(current => current.map((v, j) => i === j ? e.target.value : v)); clear(); }}/><small>Allowed: {display(min)} to {display(key === "duration" && profile === "harmonic" ? 4 : max)}.</small></div>)}
      <div className="field"><label htmlFor={id + "-intervals"}>Wave base integration intervals</label><select id={id + "-intervals"} value={intervals} onChange={e => { setIntervals(e.target.value); clear(); }}>{[64, 128, 256].map(v => <option key={v} value={v}>{v} and refined {2 * v}</option>)}</select></div>
    </div><p>Harmonic mode uses y=A cos(kx−sigma*omega*t+phi), omega=2*pi*f and k=omega/c; width is unused. Pulse mode uses y=A exp(−[(x−sigma*c*t−x0)/w]²/2), with x0=−2.5*sigma*w; frequency and phase are unused. Characteristic length/time are wavelength/period for a harmonic wave and width/width-transit time for a pulse.</p>
    <p>The maximum-slope guard 0.2 is a teaching choice, not a universal physical validity threshold. At that slope, the quadratic stretch-energy term differs from fixed-tension geometric stretch by less than 1%. This does not bound every error in a real string. Keep units in SI; a density in g/m must first be divided by 1000.</p>
    <fieldset className="phs232-predictions"><legend>Predict before revealing</legend><div className="phs232-controls"><div className="field"><label htmlFor={id + "-speed"}>Predicted positive wave speed (m/s)</label><input id={id + "-speed"} value={speed} onChange={e => setSpeed(e.target.value)}/></div><div className="field"><label htmlFor={id + "-velocity"}>Predicted transverse velocity at x=0,t=0 (m/s)</label><input id={id + "-velocity"} value={velocity} onChange={e => setVelocity(e.target.value)}/></div><div className="field"><label htmlFor={id + "-power"}>Sign of transported power away from zero-slope points</label><select id={id + "-power"} value={power} onChange={e => setPower(e.target.value)}><option value="">Choose a prediction</option><option value="positive">Positive toward +x</option><option value="negative">Negative toward +x</option><option value="zero">No transported power: zero amplitude</option></select></div></div><p>Use decimal values or exact arithmetic/radicals. Numerical tolerance is the larger of 0.000001 in the labeled unit and one part per million of the expected value. Power can be zero at an isolated crest even when the wave transports energy elsewhere.</p><button className="button secondary" onClick={reveal}>Check wave predictions</button></fieldset>
    <p role="status" className="form-status">{message}</p>{run && <WaveResults key={generation} run={run}/>}
  </div>;
}
