"use client";

import { useId, useState } from "react";
import { reflectionCyclePowers, reflectionInputSchema, reflectionModel, reflectionPoint, type ReflectionInput, type ReflectionModel } from "@/lib/learning/phs-232-superposition";
import { ModeNumbers, ModePlot, ModeProbe, ModeTable, modeClose, modeDisplay as display, modeNumbers, modePrediction, modePredictionHelp } from "./phs-232-mode-evidence";
import styles from "./phs-232-mode-evidence.module.css";

const controls = [
  ["tension", "Boundary tension (N)", .1, 100, .1], ["density", "Incident-string density (kg/m)", .001, 2, .001],
  ["secondDensity", "Second-string density (kg/m; junction only)", .001, 2, .001], ["frequency", "Boundary source frequency (Hz)", .1, 20, .1],
  ["amplitude", "Incident displacement amplitude (m)", 0, .1, .001],
] as const;
function ReflectionResults({ p }: { p: ReflectionModel }) {
  const id = useId(), [side, setSide] = useState<"left" | "right">("left"), [positionIndex, setPositionIndex] = useState(256), [timeIndex, setTimeIndex] = useState(0);
  const time = p.period * timeIndex / 256, position = side === "left" ? p.wavelength * (positionIndex / 128 - 2) : p.secondWavelength! * positionIndex / 128;
  const left = Array.from({ length: 257 }, (_, i) => reflectionPoint(p, "left", p.wavelength * (i / 128 - 2), time));
  const right = p.boundary === "junction" ? Array.from({ length: 257 }, (_, i) => reflectionPoint(p, "right", p.secondWavelength! * i / 128, time)) : [];
  const probe = reflectionPoint(p, side, position, time), cutLeft = reflectionPoint(p, "left", 0, time), cutRight = p.boundary === "junction" ? reflectionPoint(p, "right", 0, time) : null;
  const history = Array.from({ length: 257 }, (_, i) => ({ left: reflectionPoint(p, "left", 0, p.period * i / 256), right: p.boundary === "junction" ? reflectionPoint(p, "right", 0, p.period * i / 256) : null }));
  const coarse = reflectionCyclePowers(p, 128), fine = reflectionCyclePowers(p, 256), scale = 1.1 * p.amplitude * (1 + Math.abs(p.reflection)) || .01;
  const snapshotRows = [...left.map((r, i) => [i, "left", r.position, r.time, r.first.displacement, r.second.displacement, r.displacement, r.velocity, r.slope, r.kinetic, r.potential, r.power]),
    ...right.map((r, i) => [257 + i, "right", r.position, r.time, r.first.displacement, r.second.displacement, r.displacement, r.velocity, r.slope, r.kinetic, r.potential, r.power])];
  return <div className={styles.results}><h4>Reflection evidence</h4>
    <p data-testid="reflection-summary">r={display(p.reflection)}; R={display(p.reflectionFraction)}; transmitted power fraction={display(p.transmissionFraction)}. {p.transmission === null ? "This ideal endpoint has no transmitted physical string." : "t_a=" + display(p.transmission) + "; R + transmitted fraction=" + display(p.reflectionFraction + p.transmissionFraction) + "."} Boundary displacement amplitude={display(p.boundaryAmplitude)} m.</p>
    <p>Incident c={display(p.speed)} m/s, wavelength={display(p.wavelength)} m and Z1={display(p.impedance)} kg/s. {p.secondSpeed === null ? "Second-string density is unused for this ideal endpoint." : "Transmitted c=" + display(p.secondSpeed) + " m/s, wavelength=" + display(p.secondWavelength!) + " m and Z2=" + display(p.secondImpedance!) + " kg/s."} Common source frequency={display(p.frequency)} Hz; maximum combined slope={display(p.maximumSlope)}.</p>
    {p.amplitude === 0 && <p>Zero incident amplitude: there is no observed reflected or transmitted motion or phase. The listed coefficients describe the boundary model; measured power ratios would be 0/0 and are not inferred from this zero signal.</p>}
    <div className="phs232-controls">{p.boundary === "junction" && <div className="field"><label htmlFor={id + "-side"}>Boundary probe string</label><select id={id + "-side"} value={side} onChange={e => { const next = e.target.value as "left" | "right"; setSide(next); setPositionIndex(next === "left" ? 256 : 0); }}><option value="left">Left: incident plus reflected</option><option value="right">Right: transmitted</option></select></div>}
      <ModeProbe label="Boundary position index" value={positionIndex} max={256} change={setPositionIndex}/><ModeProbe label="Boundary time index" value={timeIndex} max={256} change={setTimeIndex}/></div>
    <p>Arrow, Home and End keys move each probe. The left position range ends at x=0; the right range begins there. Each plot spans two wavelengths in its own medium, so its labeled spatial range can differ.</p>
    <p data-testid="reflection-probe">Selected {side} string: x={display(position)} m, t={display(time)} s; y={display(probe.displacement)} m; y_t={display(probe.velocity)} m/s; slope={display(probe.slope)}; K/length={display(probe.kinetic)} J/m; U/length={display(probe.potential)} J/m; signed P={display(probe.power)} W.</p>
    <div className={styles.plots}>
      <ModePlot title="Incident, reflected and total displacement on the left string at the selected time. The complete snapshot table separates the three values." xLabel="Left x (m)" yLabel="Displacement (m)" domain={[-2 * p.wavelength, 0]} extent={[-scale, scale]} traces={[
        { points: left.map(r => [r.position, r.first.displacement]), color: "#176582" }, { points: left.map(r => [r.position, r.second.displacement]), color: "#8c411e", dash: "7 4" }, { points: left.map(r => [r.position, r.displacement]), color: "#23574d", dash: "8 3 2 3" },
      ]} markers={side === "left" ? [[position, probe.displacement]] : []} caption="Solid blue = incident; dashed brown = reflected; dot-dash green = total. x=0 is the physical boundary. A negative reflected coefficient means displacement inversion, while reflected power points left for either phase sign. Vertical scale is exaggerated."/>
      {right.length ? <ModePlot title="Transmitted displacement on the right string at the same time. There is no incoming wave from the right." xLabel="Right x (m)" yLabel="Displacement (m)" domain={[0, 2 * p.secondWavelength!]} extent={[-scale, scale]} traces={[{ points: right.map(r => [r.position, r.displacement]), color: "#176582" }]} markers={side === "right" ? [[position, probe.displacement]] : []} caption="The transmitted wave has the same source frequency and the second string's wavelength. Compare the matching values at x=0 using the boundary table; these two plots use different spatial ranges when the densities differ."/> :
        <ModePlot title="Ideal endpoint displacement over one period. The boundary-history table also lists its velocity, force and power." xLabel="Time (s)" yLabel="Endpoint y (m)" domain={[0, p.period]} extent={[-scale, scale]} traces={[{ points: history.map(r => [r.left.time, r.left.displacement]), color: "#176582" }]} verticals={[time]} caption="The fixed endpoint remains at y=0. A free endpoint has displacement amplitude 2A but zero transverse force. Neither ideal endpoint transmits energy; zero power does not always mean zero displacement."/>}
    </div>
    <ModeTable label="Boundary matching" headings={["Side at x=0", "t (s)", "y (m)", "y_t (m/s)", "y_x", "F_T*y_x (N)", "P toward +x (W)"]} rows={[["left", time, cutLeft.displacement, cutLeft.velocity, cutLeft.slope, p.tension * cutLeft.slope, cutLeft.power], ...(cutRight ? [["right", time, cutRight.displacement, cutRight.velocity, cutRight.slope, p.tension * cutRight.slope, cutRight.power]] : [])]}/>
    <p data-testid="boundary-residual">{cutRight ? "Junction residuals, left minus right: displacement=" + display(cutLeft.displacement - cutRight.displacement) + " m; transverse-force quantity=" + display(p.tension * (cutLeft.slope - cutRight.slope)) + " N; signed flux=" + display(cutLeft.power - cutRight.power) + " W." : p.boundary === "fixed" ? "Fixed-end constraint: y(0,t)=" + display(cutLeft.displacement) + " m and endpoint velocity=" + display(cutLeft.velocity) + " m/s." : "Free-end constraint: y_x(0,t)=" + display(cutLeft.slope) + " and transverse-force quantity=" + display(p.tension * cutLeft.slope) + " N."} The matching force quantities use the same +x cut convention; the two physical forces exerted on the massless junction oppose one another.</p>
    <ModeTable label="Reflection cycle powers" headings={["Contribution", "Analytic mean (W)", "128-interval mean (W)", "256-interval mean (W)"]} rows={[["incident", p.incidentMeanPower, coarse.incident, fine.incident], ["reflected", p.reflectedMeanPower, coarse.reflected, fine.reflected], ["transmitted", p.transmittedMeanPower, coarse.transmitted, fine.transmitted]]}/>
    <p>Separate cycle integrals of −F_T*y_x*y_t give the listed numerical powers. Signed conservation is P_incident+P_reflected=P_transmitted. Refined residual={display(fine.residual)} W; coarse residual={display(coarse.residual)} W. R is nonnegative, whereas the reflected signed power is negative when it is nonzero. A transmission amplitude above one is compatible with conserved power because the impedance changes.</p>
    <details><summary>All reflection spatial states</summary><ModeTable label="Reflection snapshot" headings={["Row", "String", "x (m)", "t (s)", "Incident or transmitted y (m)", "Reflected y (m)", "Total y (m)", "y_t (m/s)", "y_x", "K/length (J/m)", "U/length (J/m)", "P toward +x (W)"]} rows={snapshotRows}/></details>
    <details><summary>All boundary time states</summary><ModeTable label="Boundary time history" headings={["Row", "t (s)", "Left y (m)", "Left y_t (m/s)", "Left F_T*y_x (N)", "Left P (W)", "Right y (m)", "Right F_T*y_x (N)", "Right P (W)"]} rows={history.map((r, i) => [i, r.left.time, r.left.displacement, r.left.velocity, p.tension * r.left.slope, r.left.power, r.right?.displacement ?? "absent", r.right ? p.tension * r.right.slope : "absent", r.right?.power ?? "absent"])}/></details>
    <ol><li>Compare a fixed endpoint with a free endpoint at several times. Record the applicable constraint and explain why boundary power is zero in both cases.</li><li>Choose a junction with the second density four times the first. Record r, t_a, both wavelengths and both instantaneous matching conditions.</li><li>Reverse the density ratio, then match the two densities. Explain a transmitted amplitude above one, and the absence of a reflected phase when r=0.</li><li>Use the signed power ledger to check conservation. Do not replace the transmitted power fraction with t_a squared unless the impedances match.</li></ol>
  </div>;
}

export function Phs232ReflectionPanel({ initial }: { initial: ReflectionInput }) {
  const id = useId(), [values, setValues] = useState(controls.map(([key]) => String(initial[key]))), [boundary, setBoundary] = useState(initial.boundary);
  const [reflection, setReflection] = useState(""), [transmission, setTransmission] = useState(""), [condition, setCondition] = useState(""), [message, setMessage] = useState(""), [model, setModel] = useState<ReflectionModel | null>(null), [generation, setGeneration] = useState(0);
  const clear = () => { setModel(null); setMessage(""); setReflection(""); setTransmission(""); setCondition(""); };
  const reveal = () => {
    try {
      const parsed = reflectionInputSchema.safeParse({ ...modeNumbers(controls, values), boundary });
      if (!parsed.success) throw Error("Use the labeled ranges and maximum combined slope at most 0.2 in each active string.");
      if (!condition) throw Error("Predict the boundary condition before revealing.");
      const r = modePrediction(reflection), fraction = modePrediction(transmission), result = reflectionModel(parsed.data);
      const missed = [modeClose(r, result.reflection) ? "" : "signed reflection coefficient", modeClose(fraction, result.transmissionFraction) ? "" : "transmitted power fraction", condition === boundary ? "" : "boundary condition"].filter(Boolean);
      setModel(result); setGeneration(generation + 1);
      setMessage(missed.length ? "Revisit " + missed.join(", ") + ". Use displacement and transverse-force conditions together. Distinguish signed displacement coefficients from nonnegative power fractions; the transmitted fraction includes Z2/Z1." : "Your predictions agree. Test the boundary at several phases and check the signed power account.");
    } catch (error) { setModel(null); setMessage(error instanceof Error ? error.message : "Check the inputs."); }
  };
  return <section className={styles.panel}><h3>Test a boundary or junction</h3><p>The incident wave is A cos(k1*x−omega*t). On the left, its reflection is r*A cos(k1*x+omega*t). A finite junction has a massless connection, common tension and no incoming wave from the right.</p>
    <div className="phs232-controls"><div className="field"><label htmlFor={id + "-boundary"}>String boundary model</label><select id={id + "-boundary"} value={boundary} onChange={e => { setBoundary(e.target.value as ReflectionInput["boundary"]); clear(); }}><option value="fixed">Ideal fixed endpoint</option><option value="free">Ideal massless free endpoint</option><option value="junction">Two-string massless junction</option></select></div><ModeNumbers controls={controls} values={values} change={(i, value) => { setValues(v => v.map((item, j) => i === j ? value : item)); clear(); }}/></div>
    <p>For a finite junction both densities stay positive and finite. Fixed and free endpoints are separate ideal models, not zero-density or infinite-density numerical inputs. A finite endpoint mass would require a different force equation.</p>
    <fieldset className="phs232-predictions"><legend>Predict the boundary response</legend><div className="phs232-controls"><div className="field"><label htmlFor={id + "-r"}>Predicted signed displacement coefficient r</label><input id={id + "-r"} value={reflection} onChange={e => setReflection(e.target.value)}/></div><div className="field"><label htmlFor={id + "-t"}>Predicted transmitted power fraction</label><input id={id + "-t"} value={transmission} onChange={e => setTransmission(e.target.value)}/></div><div className="field"><label htmlFor={id + "-condition"}>Predicted boundary condition</label><select id={id + "-condition"} value={condition} onChange={e => setCondition(e.target.value)}><option value="">Choose a prediction</option><option value="fixed">Zero endpoint displacement</option><option value="free">Zero endpoint transverse slope</option><option value="junction">Continuous displacement and transverse force</option></select></div></div><p>{modePredictionHelp} An ideal endpoint has zero transmitted power fraction.</p><button className="button secondary" onClick={reveal}>Check reflection predictions</button></fieldset>
    <p role="status" className="form-status">{message}</p>{model && <ReflectionResults key={generation} p={model}/>}
  </section>;
}
