"use client";

import { useId, useState } from "react";
import { elasticInputSchema, elasticRun, type ElasticActivity, type ElasticInput } from "@/lib/learning/phs-231-elasticity";
import { approximateExact, parseExact, realExact } from "@/lib/learning/exact-number";
import { MathText } from "./math-text";
import "./phs-231.css";

const display=(n:number)=>n===0?"0":Math.abs(n)>=100000||Math.abs(n)<.00001?n.toExponential(4):String(Number(n.toFixed(6)));
const tick=(n:number)=>n!==0&&(Math.abs(n)>=10000||Math.abs(n)<.01)?n.toExponential(1):String(Number(n.toPrecision(3)));
const defaults={
  axial:{mode:"axial",lengthM:2,areaMm2:4,modulusGPa:100,loadN:200,stressLimitMPa:100,strainLimit:.002},
  shear:{mode:"shear",lengthM:.02,areaMm2:60,modulusGPa:.8,loadN:120,stressLimitMPa:5,strainLimit:.01},
  bulk:{mode:"bulk",volumeCm3:500,modulusGPa:2,pressureMPa:4,stressLimitMPa:10,strainLimit:.005},
} satisfies Record<ElasticInput["mode"],ElasticInput>;
type Result={input:ElasticInput;state:ReturnType<typeof elasticRun>};
type Sample=Result["state"]["peak"];
type Control=[string,string,number,number,number];
const labelsFor=(mode:ElasticInput["mode"])=>mode==="bulk"?{stress:"Hydrostatic pressure increase",strain:"Volumetric strain",change:"Volume change",unit:"cm³",factor:1e6,load:"Pressure increase",loadUnit:"MPa"}:mode==="shear"?{stress:"Signed shear stress",strain:"Engineering shear strain",change:"Signed face shift",unit:"μm",factor:1e6,load:"Signed tangential force",loadUnit:"N"}:{stress:"Signed normal stress",strain:"Engineering axial strain",change:"Signed extension",unit:"mm",factor:1000,load:"Signed axial force",loadUnit:"N"};
const status=(s:Sample)=>s.status==="outside"?"Outside the supplied linear range":s.status==="history"?"Load is back in range; response remains unestablished":s.status==="limit"?"Admitted at a supplied limit":"Admitted by the supplied model";
function controlsFor(mode:ElasticInput["mode"]):Control[]{
  const material:Control[]=[["modulusGPa",mode==="bulk"?"Bulk modulus K (GPa)":mode==="shear"?"Shear modulus G (GPa)":"Young modulus E (GPa)",.001,300,.1],["stressLimitMPa",mode==="bulk"?"Pressure-increment limit (MPa)":"Stress-magnitude limit (MPa)",.01,1000,.1],["strainLimit","Strain-magnitude limit",.00001,.05,.0001]];
  return mode==="bulk"?[["volumeCm3","Reference volume (cm³)",.1,5000,.1],["pressureMPa","Peak pressure increase (MPa)",0,1000,.1],...material]:[["lengthM",mode==="shear"?"Distance between sheared faces (m)":"Original gauge length (m)",.01,5,.01],["areaMm2",mode==="shear"?"Loaded face area (mm²)":"Original cross-sectional area (mm²)",.1,1000,.1],["loadN",mode==="shear"?"Peak signed tangential force (N)":"Peak signed axial force (N)",-5000,5000,1],...material];
}
function ElasticShape({result,index}:{result:Result;index:number}){
  const id=useId(),s=result.state.samples[index],mode=result.input.mode,labels=labelsFor(mode);
  if(s.strain===null||s.deformation===null)return <figure><div className="notice"><strong>Deformation is not established at this stage.</strong><p>The applied load is known, but the supplied law does not determine the shape, strain, or stored energy after this unsupported excursion. A zero final load does not prove zero permanent set.</p></div><figcaption>No deformed shape is drawn for an unknown material response.</figcaption></figure>;
  const mag=s.strain===0?100:Math.min(100,.25/Math.abs(s.strain)),stretch=1+mag*s.strain,shift=75*mag*s.strain,size=90*Math.cbrt(stretch);
  return <figure><svg viewBox="0 0 360 245" role="img" aria-labelledby={id}><title id={id}>{`${mode} deformation schematic at loading stage ${display(s.stage)}. Strain is exaggerated by a factor of ${display(mag)} for visibility. Dashed outline is the reference geometry; the filled shape represents the established response. Actual ${labels.change.toLowerCase()} is ${display(s.deformation*labels.factor)} ${labels.unit}. Equivalent values are in the table.`}</title>
    <text x="180" y="24" textAnchor="middle" fontSize="19" fill="#243b38">{mode==="bulk"?"Isotropic volume response":mode==="shear"?"Shear shape change":"Axial length change"}</text>
    {mode==="axial"?<><rect x="65" y="90" width={150*stretch} height="65" fill="#dcece5" stroke="#145f84" strokeWidth="3"/><rect x="65" y="90" width="150" height="65" fill="none" stroke="#933d20" strokeWidth="2" strokeDasharray="6 4"/></>:mode==="shear"?<><polygon points={`75,170 245,170 ${245+shift},95 ${75+shift},95`} fill="#dcece5" stroke="#145f84" strokeWidth="3"/><rect x="75" y="95" width="170" height="75" fill="none" stroke="#933d20" strokeWidth="2" strokeDasharray="6 4"/></>:<>
      <path d={`M${170-size/2},${140-size/2} l${size/4},${-size/4} h${size} v${size} l${-size/4},${size/4}`} fill="#edf3ef" stroke="#145f84" strokeWidth="2"/>
      <rect x={170-size/2} y={140-size/2} width={size} height={size} fill="#dcece5" stroke="#145f84" strokeWidth="3"/>
      <rect x="125" y="95" width="90" height="90" fill="none" stroke="#933d20" strokeWidth="2" strokeDasharray="6 4"/>
    </>}
    <text x="180" y="214" textAnchor="middle" fontSize="18" fill="#243b38">{`${labels.change}: ${display(s.deformation*labels.factor)} ${labels.unit}`}</text>
    <text x="180" y="238" textAnchor="middle" fontSize="18" fill="#243b38">{`Strain shown at ${display(mag)}× scale`}</text>
  </svg><figcaption>Reference geometry is dashed brown; established deformation is filled blue-green. {mode==="axial"?"Only axial length change is drawn; lateral Poisson deformation is omitted.":mode==="shear"?"Layer height is fixed in this ideal simple-shear kinematics; a full static element also needs complementary boundary tractions.":"The cube represents isotropic contraction. Its displayed volume strain is magnified; actual volume change is in the table."} The magnification adapts to keep the shape legible. This schematic is not physical measurement or a strain-gauge reading.</figcaption></figure>;
}
function LoadHistory({result,index}:{result:Result;index:number}){
  const id=useId(),rows=result.state.samples,labels=labelsFor(result.input.mode),rawLow=Math.min(0,result.state.peakLoad),rawHigh=Math.max(0,result.state.peakLoad),lo=rawLow===rawHigh?-1:rawLow,hi=rawLow===rawHigh?1:rawHigh;
  const x=(t:number)=>85+125*t,y=(v:number)=>210-158*(v-lo)/(hi-lo);
  return <figure><svg viewBox="0 0 360 267" role="img" aria-labelledby={id}><title id={id}>Prescribed load path from zero to peak and back to zero. Stage is a sequence parameter, not elapsed time. Gray shading after an exceeded range boundary marks where deformation and energy are no longer established, even when the applied load returns to zero. Complete stage values are in the table.</title>
    <text x="180" y="23" textAnchor="middle" fontSize="19" fill="#243b38">{`Applied load (${labels.loadUnit})`}</text>
    {result.state.overloaded&&result.state.limitStage!==null&&<rect x={x(result.state.limitStage)} y="45" width={335-x(result.state.limitStage)} height="168" fill="#e2e0dc"/>}
    {[0,.5,1].map(f=><g key={f}><line x1="85" x2="335" y1={y(lo+f*(hi-lo))} y2={y(lo+f*(hi-lo))} stroke="#c7d3ce"/><text x="78" y={y(lo+f*(hi-lo))+5} textAnchor="end" fontSize="18" fill="#243b38">{tick(lo+f*(hi-lo))}</text><text x={x(2*f)} y="236" textAnchor="middle" fontSize="18" fill="#243b38">{2*f}</text></g>)}
    <polyline points={rows.map(r=>`${x(r.stage)},${y(r.load)}`).join(" ")} fill="none" stroke="#145f84" strokeWidth="2.5"/>
    <line x1={x(rows[index].stage)} x2={x(rows[index].stage)} y1="45" y2="213" stroke="#933d20" strokeDasharray="5 4"/>
    <text x="210" y="260" textAnchor="middle" fontSize="18" fill="#243b38">Loading stage</text>
  </svg><figcaption>0→1 increases the load from zero to the requested peak; 1→2 removes it. Blue is the prescribed load, including any part beyond the material law. Gray means the subsequent response is unestablished; it does not mean force stops being applied. The dashed line marks the selected stage. No physical time or loading rate is inferred.</figcaption></figure>;
}
function ResponsePlot({result,index}:{result:Result;index:number}){
  const id=useId(),labels=labelsFor(result.input.mode),known=result.state.samples.filter(r=>r.deformation!==null),allX=known.map(r=>r.deformation!*labels.factor),allY=known.map(r=>r.load);
  if(result.state.peakLoad===0)return <figure><svg viewBox="0 0 360 190" role="img" aria-labelledby={id}><title id={id}>Zero-load trial: every prescribed stage is the origin, with zero deformation and zero applied load.</title><text x="180" y="28" textAnchor="middle" fontSize="19" fill="#243b38">Zero-load trial</text><line x1="140" x2="220" y1="95" y2="95" stroke="#526a63"/><line x1="180" x2="180" y1="55" y2="125" stroke="#526a63"/><circle cx="180" cy="95" r="5" fill="#145f84"/><text x="180" y="158" textAnchor="middle" fontSize="18" fill="#243b38">Only the origin is sampled</text></svg><figcaption>No deformation or load excursion occurs. A single zero–zero state cannot identify stiffness or modulus; those remain supplied model inputs.</figcaption></figure>;
  const xlo=Math.min(0,...allX),xhi=Math.max(0,...allX),ylo=Math.min(0,...allY),yhi=Math.max(0,...allY),xspan=xhi-xlo||1,yspan=yhi-ylo||1;
  const x=(v:number)=>85+250*(v-xlo)/xspan,y=(v:number)=>210-158*(v-ylo)/yspan,selected=result.state.samples[index];
  return <figure><svg viewBox="0 0 360 270" role="img" aria-labelledby={id}><title id={id}>{`Established applied load versus ${labels.change.toLowerCase()}. Only states covered by the supplied constitutive law and loading history are drawn. Reversible unloading retraces loading when the peak stays admitted. Unknown deformation is omitted instead of extending the line. The table gives every state.`}</title>
    <text x="180" y="23" textAnchor="middle" fontSize="19" fill="#243b38">{`Established load (${labels.loadUnit})`}</text>
    {[0,.5,1].map(f=><g key={f}><line x1="85" x2="335" y1={y(ylo+f*(yhi-ylo))} y2={y(ylo+f*(yhi-ylo))} stroke="#c7d3ce"/><text x="78" y={y(ylo+f*(yhi-ylo))+5} textAnchor="end" fontSize="18" fill="#243b38">{tick(ylo+f*(yhi-ylo))}</text><text x={85+250*f} y="236" textAnchor="middle" fontSize="18" fill="#243b38">{tick(xlo+f*(xhi-xlo))}</text></g>)}
    <polyline points={known.map(r=>`${x(r.deformation!*labels.factor)},${y(r.load)}`).join(" ")} fill="none" stroke="#145f84" strokeWidth="3"/>
    {selected.deformation!==null&&<circle cx={x(selected.deformation*labels.factor)} cy={y(selected.load)} r="5" fill="#933d20"/>}
    <text x="210" y="262" textAnchor="middle" fontSize="18" fill="#243b38">{`${labels.change} (${labels.unit})`}</text>
  </svg><figcaption>The line ends where knowledge of the response ends. A known selected state is an orange dot; an unknown state has no invented point. {result.input.mode==="bulk"?"Increasing pressure accompanies negative volume change. Incremental work uses −∫Δp dV, so stored energy is positive.":"Signed force and signed displacement have matching signs under this law; quasistatic work uses ∫F dδ."} Zero-load trials contain only the origin. Geometry changes the slope of this specimen response even when the material modulus stays fixed.</figcaption></figure>;
}
export function Phs231ElasticLab({activity}:{activity:ElasticActivity}){
  const valuesFor=(p:ElasticInput)=>Object.fromEntries(Object.entries(p).filter(([key])=>key!=="mode").map(([key,value])=>[key,String(value)]));
  const [mode,setMode]=useState(activity.initial.mode),[values,setValues]=useState(valuesFor(activity.initial)),[predictions,setPredictions]=useState(["","","",""]),[predictedDecision,setPredictedDecision]=useState<""|"admitted"|"outside">(""),[result,setResult]=useState<Result|null>(null),[message,setMessage]=useState(""),[index,setIndex]=useState(0);
  const labels=labelsFor(mode),controls=controlsFor(mode);
  const clear=()=>{setResult(null);setMessage("");};
  const apply=(p:ElasticInput)=>{setMode(p.mode);setValues(valuesFor(p));setPredictions(["","","",""]);setPredictedDecision("");setIndex(0);clear();};
  const check=()=>{
    try{
      if(controls.some(([key])=>!values[key]?.trim()))throw Error("Complete every model input; an empty input is not zero.");
      const parsed=elasticInputSchema.safeParse({mode,...Object.fromEntries(controls.map(([key])=>[key,Number(values[key])]))});
      if(!parsed.success)throw Error("Use finite model inputs inside every printed range. Areas, lengths, volumes, moduli, and limits must be positive; the bulk pressure increase cannot be negative.");
      if(!predictedDecision||!predictions[0].trim()||(predictedDecision==="admitted"&&predictions.slice(1).some(v=>!v.trim())))throw Error("Predict the peak stress and range decision first. An admitted prediction also needs strain, deformation, and stored energy.");
      const answer=(raw:string)=>{
        const text=raw.trim();
        if(/^[+-]?(?:\d+(?:\.\d*)?|\.\d+)(?:e[+-]?\d+)?$/i.test(text)){const n=Number(text);if(!Number.isFinite(n))throw Error("Predictions must be finite real numbers.");return n;}
        const n=parseExact(text);if(!realExact(n))throw Error("Predictions must be real numbers.");return approximateExact(n).real;
      };
      const state=elasticRun(parsed.data),peak=state.peak,expected=[peak.stress,peak.strain,peak.deformation===null?null:peak.deformation*labels.factor,peak.energy],names=["peak stress","peak strain","peak deformation","peak energy"],tolerances=[1e-6,1e-10,1e-6,1e-9],missed:string[]=[];
      const submitted=predictions.map((raw,i)=>i===0||predictedDecision==="admitted"?answer(raw):null);
      submitted.forEach((value,i)=>{if(value!==null&&(expected[i]===null||Math.abs(value-expected[i]!)>Math.max(tolerances[i],Math.abs(expected[i]!)*1e-8)))missed.push(names[i]);});
      if(predictedDecision!==(state.overloaded?"outside":"admitted"))missed.push("range decision");
      setResult({input:parsed.data,state});setIndex(state.samples.findIndex(s=>s.stage===1));
      setMessage(missed.length?`Revisit ${missed.join(", ")}. Compare stress with both supplied bounds before claiming a deformation or energy. Use the original geometry and the modulus for this mode; a linear extrapolation beyond a limit is not an established material response.`:state.overloaded?"Both predictions agree: the peak demand exceeds the supplied model, so peak deformation and stored energy are not established.":"All five predictions agree with the supplied linear law, geometry, and both range bounds.");
    }catch(error){setResult(null);setMessage(error instanceof Error?error.message:"Check the inputs.");}
  };
  const presets:[string,ElasticInput][]=[
    ["Axial baseline",defaults.axial],["Double area at fixed force",{...defaults.axial,areaMm2:8}],["Double area at fixed extension",{...defaults.axial,areaMm2:8,loadN:400}],["Double gauge length",{...defaults.axial,lengthM:4}],["Signed compression",{...defaults.axial,loadN:-200}],["Exact stress limit",{...defaults.axial,loadN:400}],["Beyond stress limit",{...defaults.axial,loadN:500}],["Strain limit first",{...defaults.axial,strainLimit:.0004}],["Zero axial load",{...defaults.axial,loadN:0}],["Shear example",defaults.shear],["Bulk example",defaults.bulk],["Beyond bulk limit",{...defaults.bulk,pressureMPa:12}],
  ];
  const s=result?.state.samples[index],nullable=(n:number|null,factor=1)=>n===null?"Not established":display(n*factor);
  return <div className="phs231-investigation"><p><MathText>{activity.prompt}</MathText></p>
    <p className="muted">This is a simulation with hypothetical material properties and supplied validity bounds. It is not a physical wire-tension, breaking, or pressurized-vessel experiment. Controls reset on reload; save your predictions, evidence, and explanations in lesson notes.</p>
    <div className="field"><label htmlFor="phs231-elastic-mode">Deformation mode</label><select id="phs231-elastic-mode" value={mode} onChange={event=>apply(defaults[event.target.value as ElasticInput["mode"]])}><option value="axial">Axial specimen</option><option value="shear">Shear element</option><option value="bulk">Bulk compression</option></select></div>
    <p>{mode==="axial"?"A uniform, initially unstressed specimen carries a signed axial force. Tension and extension are positive. Compression assumes a short, laterally supported ideal specimen; no buckling prediction follows.":mode==="shear"?"Opposing tangential forces shear a homogeneous element. Positive force produces positive face shift. The static element also needs complementary face tractions to balance moments; these are implicit in the ideal shear state.":"A hydrostatic pressure increment is positive in compression and causes negative volume change. The reference volume is at the baseline pressure. Stored energy is incremental about that reference; baseline-pressure work is not included."}</p>
    <fieldset className="phs231-predictions"><legend>Geometry, material, and loading</legend><div className="phs231-controls">{controls.map(([key,label,min,max,step])=><div className="field" key={key}><label htmlFor={`phs231-elastic-${key}`}>{label}</label><input id={`phs231-elastic-${key}`} type="number" min={min} max={max} step={step} value={values[key]??""} aria-describedby={`phs231-elastic-${key}-range`} onChange={event=>{setValues(current=>({...current,[key]:event.target.value}));clear();}}/><small id={`phs231-elastic-${key}-range`}>Allowed range: {min} to {max}.</small></div>)}</div></fieldset>
    <p>The smaller of the supplied stress bound and modulus × strain bound limits this model. Equality is admitted at a limit. These bounds are assumptions for this trial, not strength ratings or permission to load real equipment. The load path rises from zero to peak and returns to zero quasistatically.</p>
    <details><summary>Load prepared elastic comparisons</summary><div className="form-actions">{presets.map(([label,p])=><button className="button secondary" key={label} onClick={()=>apply(p)}>{label}</button>)}</div></details>
    <fieldset className="phs231-predictions"><legend>Predict the peak response</legend><p>Enter fractions, sqrt(...), or finite decimals in the labeled units. Check the range before predicting deformation. Accepted errors are 0.000001 MPa, 0.0000000001 strain, 0.000001 {labels.unit}, and 0.000000001 J, or one part in 100 million of the expected value, whichever is larger.</p>
      <div className="field"><label htmlFor="phs231-elastic-decision">Predicted peak range decision</label><select id="phs231-elastic-decision" value={predictedDecision} onChange={event=>{setPredictedDecision(event.target.value as typeof predictedDecision);clear();}}><option value="">Choose a decision</option><option value="admitted">Peak is inside or at both supplied bounds</option><option value="outside">Peak exceeds at least one supplied bound</option></select></div>
      <div className="phs231-controls">{[`Predicted peak ${labels.stress.toLowerCase()} (MPa)`,`Predicted peak ${labels.strain.toLowerCase()}`,`Predicted peak ${labels.change.toLowerCase()} (${labels.unit})`,"Predicted peak stored energy (J)"].map((label,i)=><div className="field" key={label}><label htmlFor={`phs231-elastic-prediction-${i}`}>{label}</label><input id={`phs231-elastic-prediction-${i}`} maxLength={200} disabled={i>0&&predictedDecision==="outside"} value={predictions[i]} onChange={event=>{setPredictions(current=>current.map((v,j)=>i===j?event.target.value:v));clear();}}/>{i>0&&predictedDecision==="outside"&&<small>Not established by the supplied model when the peak exceeds a bound.</small>}</div>)}</div>
    </fieldset>
    <div className="form-actions"><button className="button" onClick={check}>Check elastic account</button><button className="button secondary" onClick={()=>apply(activity.initial)}>Reset elasticity investigation</button></div><p role="status" className="form-status">{message}</p>
    {result&&s&&<div className="notice">
      <p><strong>Effective stress-magnitude bound: {display(result.state.stressLimit)} MPa.</strong> {result.state.limitBy==="both"?"Both supplied bounds become active together.":result.state.limitBy==="strain"?"The strain bound becomes active first.":"The stress bound becomes active first."} {mode==="bulk"?"Admitted peak pressure increase":"Admitted force magnitude"} is at most {display(result.state.limitLoad)} {labels.loadUnit}.</p>
      <p>{mode==="bulk"?`Pressure-per-volume stiffness: ${display(result.state.stiffness*1e-12)} MPa/cm³; compliance: ${display(result.state.compliance*1e12)} cm³/MPa.`:`Specimen stiffness: ${display(result.state.stiffness/1000)} kN/m; compliance: ${display(result.state.compliance*1000)} mm/N.`} These depend on reference geometry. The material modulus is {display(result.input.modulusGPa)} GPa.</p>
      <div className="field"><label htmlFor="phs231-elastic-sample">Loading-stage sample</label><input id="phs231-elastic-sample" type="range" min={0} max={result.state.samples.length-1} step={1} value={index} aria-valuetext={`Stage ${display(s.stage)}; load ${display(s.load)} ${labels.loadUnit}; ${status(s)}`} onChange={event=>setIndex(Number(event.target.value))}/><p>Selected stage: <strong>{display(s.stage)}</strong>. Use arrow keys, Home, and End. Stage 1 is peak load; stage 2 is final zero load. Exact limits have buttons and may sit between regular samples. No physical time scale or automatic motion is supplied.</p></div>
      <div className="form-actions">{result.state.events.map(event=><button className="button secondary" key={event.kind} onClick={()=>setIndex(result.state.samples.findIndex(row=>row.stage===event.stage))}>{event.label}</button>)}</div>
      <p><strong>{status(s)}.</strong> {s.status==="history"?"Returning the applied load to its admitted range does not recover a known constitutive history. Plasticity, permanent set, damage, and dissipation require additional evidence.":s.status==="outside"?"The load demand is known, but strain, deformation, stored energy, and work after the boundary are not determined by the supplied law.":"Strain, displacement, and energy follow the supplied reversible linear law at this stage."}</p>
      <ElasticShape result={result} index={index}/><LoadHistory result={result} index={index}/><ResponsePlot result={result} index={index}/>
      <div className="phs231-table" role="region" tabIndex={0} aria-label="Selected elastic account"><table><caption>Elastic account at loading stage {display(s.stage)}</caption><thead><tr><th scope="col">Quantity</th><th scope="col">Value</th><th scope="col">Unit</th></tr></thead><tbody>
        {([[labels.load,s.load,labels.loadUnit,1],[labels.stress,s.stress,"MPa",1],[labels.strain,s.strain,"1",1],[labels.change,s.deformation,labels.unit,labels.factor],["Stored energy density",s.energyDensity,"J/m³",1],["Stored energy",s.energy,"J",1],["Net incremental work from stage 0",s.work,"J",1],["Energy minus work residual",s.energyResidual,"J",1]] as [string,number|null,string,number][]).map(([label,value,unit,factor])=><tr key={label}><th scope="row">{label}</th><td>{nullable(value,factor)}</td><td>{unit}</td></tr>)}
      </tbody></table></div>
      <p><MathText>{mode==="bulk"?"Within the admitted path, $U=\\tfrac12K(\\Delta V/V_0)^2V_0=-\\tfrac12\\Delta p\\Delta V$.":"Within the admitted path, $U=\\tfrac12 F\\delta$; signed compression still stores nonnegative energy."}</MathText> Net work is work delivered since the reference, including energy returned during admitted unloading. An exceeded bound stops this accounting; a zero final load does not establish a zero final energy or deformation.</p>
      <details><summary>Complete loading and unloading table</summary><div className="phs231-table" role="region" tabIndex={0} aria-label="Complete elastic path table" style={{maxHeight:"24rem",overflowY:"auto"}}><table style={{minWidth:"42rem"}}><caption>All plotted samples and exact range events; unknown responses stay explicit</caption><thead style={{position:"sticky",top:0,background:"#f6f8f3"}}><tr>{["Stage",`Load (${labels.loadUnit})`,"Stress (MPa)","Strain",`Deformation (${labels.unit})`,"Energy (J)","Net work (J)","Status"].map(label=><th scope="col" key={label}>{label}</th>)}</tr></thead><tbody>{result.state.samples.map(row=><tr key={row.stage}><th scope="row">{display(row.stage)}</th><td>{display(row.load)}</td><td>{display(row.stress)}</td><td>{nullable(row.strain)}</td><td>{nullable(row.deformation,labels.factor)}</td><td>{nullable(row.energy)}</td><td>{nullable(row.work)}</td><td>{status(row)}</td></tr>)}</tbody></table></div></details>
    </div>}
    <h3 className="section-space">Build an evidence record</h3>
    <ol><li>Record the axial baseline, a doubled area at fixed force, and a doubled area at fixed extension. Predict which stress, strain, stiffness, and energy change before checking.</li><li>Inspect one compression, shear, and bulk trial. Explain each sign and unit. Integrate the displayed linear load–deformation relation and compare its work with stored energy.</li><li>Compare the exact stress limit, beyond-limit, and strain-limit-first trials. Inspect the loading limit, peak, return to range, and final zero load. Separate known loading from unknown response.</li><li>Save an input table, at least six predicted and checked states, one independent unit calculation, one energy calculation, and an explanation of the unknown unloading history in lesson notes. Add a measurement-resolution or fixture-compliance limitation that the ideal simulation omits.</li></ol>
    <p>Self-assess four criteria from 0 to 2: traceable inputs and units; correct predictions and independent calculations; causal comparison with the held condition named; and a justified model-limit or measurement discussion. Use 0 for missing evidence, 1 for partial evidence or a material error, and 2 for a complete justified account. Revisit any zero. A proposed target is at least 6 of 8 with no zero; this is practice evidence, not an official laboratory grade.</p>
  </div>;
}

