"use client";

import { useId, useState } from "react";
import { coupledModeInputSchema, coupledModeRun, type CoupledModeInput } from "@/lib/learning/phs-232-coupled-modes";
import { ModeNumbers, ModePlot, ModeProbe, ModeTable, modeClose, modeDisplay as display, modeNumbers, modePrediction, modePredictionHelp } from "./phs-232-mode-evidence";
import styles from "./phs-232-mode-evidence.module.css";

const controls = [
  ["mass", "Each coupled mass m (kg)", .1, 5, .1], ["stiffness", "Each wall-spring stiffness k (N/m)", .1, 100, .1],
  ["couplingRatio", "Coupling stiffness ratio k_c / k", 0, 4, .025], ["firstPosition", "Initial mass 1 displacement (m)", -.1, .1, .01],
  ["secondPosition", "Initial mass 2 displacement (m)", -.1, .1, .01], ["firstVelocity", "Initial mass 1 velocity (m/s)", -1, 1, .01],
  ["secondVelocity", "Initial mass 2 velocity (m/s)", -1, 1, .01], ["cycles", "Record duration (lower-mode periods)", 1, 24, 1],
] as const;
type Run = ReturnType<typeof coupledModeRun>;
function CoupledResults({ run }: { run: Run }) {
  const id = useId(), [timeIndex, setTimeIndex] = useState(0), [resolution, setResolution] = useState("fine");
  const p = run.model, point = run.fine[timeIndex], scale = 1.1 * (p.plusAmplitude + p.minusAmplitude) || .01, energyScale = 1.1 * p.totalEnergy || .001;
  const selected = resolution === "fine" ? run.fine : run.coarse, distinct = p.deltaOmega > 0 && p.hasTwoModes;
  return <div className={styles.results}><h4>Coupled-mass evidence</h4>
    <p data-testid="coupled-summary">k_c={display(p.couplingStiffness)} N/m; omega_plus={display(p.omegaPlus)} rad/s; omega_minus={display(p.omegaMinus)} rad/s; frequency separation={display(p.beatFrequency)} Hz. {p.beatPeriod === null ? "The frequencies coincide: no beat cycle and no coupling-spring transfer." : "Magnitude repeat period associated with this frequency separation=" + display(p.beatPeriod) + " s; signed cosine-modulation period for an equal-amplitude pair=" + display(p.signedModulationPeriod!) + " s."}</p>
    <p data-testid="coupled-interpretation">{p.atRest ? "Both modal amplitudes are zero: the system is at rest." : !p.hasTwoModes ? "Only one normal component is excited. The system's two possible frequencies do not create a beat in this single-mode motion." : !distinct ? "Both chosen coordinates can be nonzero, but their equal frequencies reconstruct independent uncoupled masses without a changing beat magnitude." : "Both distinct normal components are excited. The plotted magnitude bounds describe their interference; unequal modal amplitudes need not cancel."} {distinct && "The recorded window spans " + display(run.beatCyclesInView!) + " magnitude repeat cycles."}</p>
    <ModeTable label="Initial normal components" headings={["Component", "omega (rad/s)", "q(0) (m)", "q_t(0) (m/s)", "Amplitude (m)", "Phase (rad)", "Conserved modal E (J)"]} rows={[["symmetric (+)", p.omegaPlus, p.plusPosition, p.plusVelocity, p.plusAmplitude, p.plusPhase ?? "undefined", p.plusEnergy], ["antisymmetric (-)", p.omegaMinus, p.minusPosition, p.minusVelocity, p.minusAmplitude, p.minusPhase ?? "undefined", p.minusEnergy]]}/>
    <ModeProbe label="Coupled time index" value={timeIndex} max={run.fine.length - 1} change={setTimeIndex}/>
    <p>Use Arrow, Home and End keys or step buttons. The record contains every refined state. Exact modal solutions produce motion; separate time quadrature integrates the two coupling powers. Coarse sampling uses at least 32 intervals per fastest-mode period, with twice as many in the refined record.</p>
    <p data-testid="coupled-probe">At t={display(point.time)} s: x1={display(point.firstPosition)} m, v1={display(point.firstVelocity)} m/s; x2={display(point.secondPosition)} m, v2={display(point.secondVelocity)} m/s. E1={display(point.firstEnergy)} J; E2={display(point.secondEnergy)} J; coupling U_c={display(point.couplingEnergy)} J; total={display(point.totalEnergy)} J. Coupling powers into the mass/wall-spring accounts: P1={display(point.firstPower)} W, P2={display(point.secondPower)} W.</p>
    <div className={styles.plots}>
      <ModePlot title="Mass 1 displacement and positive and negative magnitude bounds throughout the selected record. Full physical states are in the table." xLabel="Time (s)" yLabel="Mass 1 x (m)" domain={[0, p.end]} extent={[-scale, scale]} traces={[
        { points: run.fine.map(r => [r.time, r.firstPosition]), color: "#176582" }, { points: run.fine.map(r => [r.time, r.firstEnvelope]), color: "#8c411e", dash: "5 4" }, { points: run.fine.map(r => [r.time, -r.firstEnvelope]), color: "#8c411e", dash: "5 4" },
      ]} verticals={[point.time]} markers={[[point.time, point.firstPosition]]} caption="Solid blue = mass 1 displacement; dashed brown = magnitude bounds from the rotating modal coefficients. They are not guaranteed turning-point curves. A slowly varying envelope interpretation requires nearby frequencies."/>
      <ModePlot title="Mass 2 displacement and its magnitude bounds on the same time and displacement scales as mass 1." xLabel="Time (s)" yLabel="Mass 2 x (m)" domain={[0, p.end]} extent={[-scale, scale]} traces={[
        { points: run.fine.map(r => [r.time, r.secondPosition]), color: "#176582" }, { points: run.fine.map(r => [r.time, r.secondEnvelope]), color: "#8c411e", dash: "5 4" }, { points: run.fine.map(r => [r.time, -r.secondEnvelope]), color: "#8c411e", dash: "5 4" },
      ]} verticals={[point.time]} markers={[[point.time, point.secondPosition]]} caption="The opposite sign of the antisymmetric component changes the interference at mass 2. An apparent handoff of displacement magnitude does not by itself establish complete transfer of physical energy."/>
      <ModePlot title="Symmetric and antisymmetric coordinates that reconstruct the two mass displacements. The modal-state table includes their velocities and conserved energies." xLabel="Time (s)" yLabel="Normal q (m)" domain={[0, p.end]} extent={[-scale, scale]} traces={[
        { points: run.fine.map(r => [r.time, r.plusPosition]), color: "#176582" }, { points: run.fine.map(r => [r.time, r.minusPosition]), color: "#8c411e", dash: "7 4" },
      ]} verticals={[point.time]} caption="Solid blue = q_plus=(x1+x2)/2; dashed brown = q_minus=(x1−x2)/2. Each coordinate oscillates independently at its own frequency. Reconstruct x1=q_plus+q_minus and x2=q_plus−q_minus."/>
      <ModePlot title="Physical energy accounts for mass 1, mass 2, the coupling spring and their total. Complete work and residual records are available at both resolutions." xLabel="Time (s)" yLabel="Energy (J)" domain={[0, p.end]} extent={[0, energyScale]} traces={[
        { points: run.fine.map(r => [r.time, r.firstEnergy]), color: "#176582" }, { points: run.fine.map(r => [r.time, r.secondEnergy]), color: "#8c411e", dash: "7 4" }, { points: run.fine.map(r => [r.time, r.couplingEnergy]), color: "#23574d", dash: "2 4" }, { points: run.fine.map(r => [r.time, r.totalEnergy]), color: "#27332e", dash: "8 3 2 3" },
      ]} verticals={[point.time]} caption="Solid blue = E1; dashed brown = E2; dotted green = coupling-spring energy; dot-dash dark line = total. Each Ei includes that mass's kinetic and wall-spring energy, with coupling energy retained separately."/>
    </div>
    <p>With this coordinate normalization, modal energies are m*q_plus_t²+k*q_plus² and m*q_minus_t²+(k+2*k_c)*q_minus². They are constant even as the physical mass accounts exchange energy. The whole system&apos;s energy is {display(p.totalEnergy)} J.</p>
    <ModeTable label="Coupled work refinement" headings={["Resolution", "Intervals", "dt (s)", "Final W1 (J)", "Final W2 (J)", "Largest account residual (J)"]} rows={[[1, run.intervals, p.end / run.intervals, run.coarse.at(-1)!.firstWork, run.coarse.at(-1)!.secondWork, run.coarseResidual], [2, 2 * run.intervals, p.end / (2 * run.intervals), run.fine.at(-1)!.firstWork, run.fine.at(-1)!.secondWork, run.fineResidual]]}/>
    <p data-testid="coupled-energy">Largest aligned work refinement difference={display(run.workDifference)} J. At the selected time: E1−E1(0)−W1={display(point.firstResidual)} J; E2−E2(0)−W2={display(point.secondResidual)} J; U_c−U_c(0)+W1+W2={display(point.couplingResidual)} J; total-energy change={display(point.totalResidual)} J.</p>
    <p>P1=k_c*(x2−x1)*v1 and P2=−k_c*(x2−x1)*v2. Their sum is minus the coupling-energy rate. Separate Simpson time sums integrate both powers using midpoint states; work is not defined from an energy difference. Refinement compares numerical approximations and does not measure real experimental uncertainty. A very weak coupling may need a longer record than this panel allows.</p>
    <details><summary>All coupled physical states</summary><ModeTable label="Coupled physical states" headings={["Row", "t (s)", "x1 (m)", "v1 (m/s)", "a1 (m/s²)", "x2 (m)", "v2 (m/s)", "a2 (m/s²)", "Envelope 1 (m)", "Envelope 2 (m)"]} rows={run.fine.map(r => [r.index, r.time, r.firstPosition, r.firstVelocity, r.firstAcceleration, r.secondPosition, r.secondVelocity, r.secondAcceleration, r.firstEnvelope, r.secondEnvelope])}/></details>
    <details><summary>All normal-coordinate states</summary><ModeTable label="Coupled modal states" headings={["Row", "t (s)", "q_plus (m)", "q_plus_t (m/s)", "q_minus (m)", "q_minus_t (m/s)", "E_plus (J)", "E_minus (J)"]} rows={run.fine.map(r => [r.index, r.time, r.plusPosition, r.plusVelocity, r.minusPosition, r.minusVelocity, r.plusEnergy, r.minusEnergy])}/></details>
    <details><summary>All coupled energy and work records</summary><div className="field"><label htmlFor={id + "-resolution"}>Coupled work record resolution</label><select id={id + "-resolution"} value={resolution} onChange={e => setResolution(e.target.value)}><option value="coarse">Coarse</option><option value="fine">Refined</option></select></div><ModeTable label="Coupled energy ledger" headings={["Row", "t (s)", "E1 (J)", "E2 (J)", "U_c (J)", "Total E (J)", "P1 (W)", "P2 (W)", "U_c rate (W)", "W1 (J)", "W2 (J)", "E1 residual (J)", "E2 residual (J)", "U_c residual (J)"]} rows={selected.map(r => [r.index, r.time, r.firstEnergy, r.secondEnergy, r.couplingEnergy, r.totalEnergy, r.firstPower, r.secondPower, r.couplingPower, r.firstWork, r.secondWork, r.firstResidual, r.secondResidual, r.couplingResidual])}/></details>
    <ol><li>Compare the symmetric and antisymmetric presets at the same mass and springs. Explain the unchanged versus doubled relative spring deformation.</li><li>Release one mass and compare both normal coordinates with the two physical displacements. Record at least one time when the coupling spring retains energy.</li><li>Change coupling while keeping the other conditions fixed. Record the frequency separation and how much of a magnitude cycle fits the window; avoid inferring a full beat from an incomplete record.</li><li>Set coupling to zero, then try general initial velocities. Check each mass&apos;s constant energy and explain why equal frequencies do not create a beat cycle.</li><li>Compare coarse/refined spring-work accounts and retain both work signs, coupling energy and residuals in your notes.</li></ol>
  </div>;
}

export function Phs232CoupledPanel({ initial }: { initial: CoupledModeInput }) {
  const id = useId(), [values, setValues] = useState(controls.map(([key]) => String(initial[key])));
  const [plus, setPlus] = useState(""), [minus, setMinus] = useState(""), [distinct, setDistinct] = useState(""), [message, setMessage] = useState(""), [run, setRun] = useState<Run | null>(null), [generation, setGeneration] = useState(0);
  const clear = () => { setRun(null); setMessage(""); setPlus(""); setMinus(""); setDistinct(""); };
  const preset = (second: number) => { const reset: Record<string, number> = { firstPosition: .04, secondPosition: second, firstVelocity: 0, secondVelocity: 0 }; setValues(v => controls.map(([key], i) => key in reset ? String(reset[key]) : v[i])); clear(); };
  const reveal = () => {
    try {
      const parsed = coupledModeInputSchema.safeParse(modeNumbers(controls, values));
      if (!parsed.success) throw Error("Use the labeled finite ranges, positive mass and wall stiffness, nonnegative coupling, and a record from 1 through 24 lower-mode periods.");
      if (!distinct) throw Error("Predict whether both distinct normal components are excited.");
      const first = modePrediction(plus), second = modePrediction(minus), result = coupledModeRun(parsed.data), p = result.model;
      const expected = p.deltaOmega > 0 && p.hasTwoModes ? "yes" : "no";
      const missed = [modeClose(first, p.omegaPlus) ? "" : "symmetric frequency", modeClose(second, p.omegaMinus) ? "" : "antisymmetric frequency", distinct === expected ? "" : "excited-mode classification"].filter(Boolean);
      setRun(result); setGeneration(generation + 1);
      setMessage(missed.length ? "Revisit " + missed.join(", ") + ". Add and subtract both force equations, keeping the factor 2 in k+2*k_c. Initial half-sums and half-differences determine which modes are excited; equal frequencies do not create beats." : "Your predictions agree. Reconstruct the mass motions and compare physical energy transfer with the conserved modal accounts.");
    } catch (error) { setRun(null); setMessage(error instanceof Error ? error.message : "Check the inputs."); }
  };
  return <section className={styles.panel}><h3>Reconstruct two coupled masses</h3><p>Two equal masses lie between fixed walls. Each outer spring has stiffness k and the spring between the masses has stiffness k_c. Displacements are measured from equilibrium. The ideal model assumes linear springs without damping or driving; no physical apparatus or equipment is assigned.</p>
    <div className="phs232-controls"><ModeNumbers controls={controls} values={values} change={(i, value) => { setValues(v => v.map((item, j) => i === j ? value : item)); clear(); }}/></div>
    <div className="form-actions"><button className="button secondary" onClick={() => preset(.04)}>Symmetric release preset</button><button className="button secondary" onClick={() => preset(-.04)}>Antisymmetric release preset</button><button className="button secondary" onClick={() => preset(0)}>One-mass release preset</button></div><p>Presets set only the two initial displacements and velocities; mass, stiffness, coupling and duration keep their displayed values. You can then edit all four initial values.</p>
    <fieldset className="phs232-predictions"><legend>Predict the normal components</legend><div className="phs232-controls"><div className="field"><label htmlFor={id + "-plus"}>Predicted omega_plus (rad/s)</label><input id={id + "-plus"} value={plus} onChange={e => setPlus(e.target.value)}/></div><div className="field"><label htmlFor={id + "-minus"}>Predicted omega_minus (rad/s)</label><input id={id + "-minus"} value={minus} onChange={e => setMinus(e.target.value)}/></div><div className="field"><label htmlFor={id + "-distinct"}>Are both distinct normal components excited?</label><select id={id + "-distinct"} value={distinct} onChange={e => setDistinct(e.target.value)}><option value="">Choose a prediction</option><option value="yes">Yes: both amplitudes are nonzero and frequencies differ</option><option value="no">No: a component is absent or frequencies coincide</option></select></div></div><p>{modePredictionHelp}</p><button className="button secondary" onClick={reveal}>Check coupled-mode predictions</button></fieldset>
    <p role="status" className="form-status">{message}</p>{run && <CoupledResults key={generation} run={run}/>}
  </section>;
}
