"use client";

import { useId,useState } from "react";
import { numericalCsv,numericalInputSchema,numericalRun,type NumericalActivity,type NumericalInput } from "@/lib/learning/phs-231-numerical";
import { approximateExact,parseExact,realExact } from "@/lib/learning/exact-number";
import { MathText } from "./math-text";
import "./phs-231.css";

const display=(n:number)=>n===0?"0":Math.abs(n)>=100000||Math.abs(n)<.00001?n.toExponential(8).replace(/\.?0+e/,"e"):String(Number(n.toPrecision(9)));
const tick=(n:number)=>n!==0&&(Math.abs(n)>=10000||Math.abs(n)<.01)?n.toExponential(1):String(Number(n.toPrecision(3)));
type Result=ReturnType<typeof numericalRun>;
type Run=Result["runs"][number];
type Sample=Run["samples"][number];
const names={explicit:"Simultaneous explicit Euler",semi:"Velocity-first semi-implicit Euler",midpoint:"Explicit midpoint"};
const baseline:NumericalInput={method:"semi",massKg:.5,springNPerM:8,dragKgPerS:0,positionM:.08,velocityMPerS:0,durationS:4,stepS:.1};
const controls:[keyof Omit<NumericalInput,"method">,string,number,number,number][]=[
  ["massKg","Mass (kg)",.1,20,.1],["springNPerM","Spring constant (N/m)",.1,200,.1],["dragKgPerS","Viscous coefficient (kg/s)",0,20,.1],["positionM","Initial position (m)",-1,1,.01],["velocityMPerS","Initial velocity (m/s)",-10,10,.1],["durationS","Requested final time (s)",.001,20,.1],["stepS","Requested base step (s)",.0001,2,.01],
];
const valuesFor=(p:NumericalInput)=>Object.fromEntries(controls.map(([key])=>[key,String(p[key])]));
const sign=(E0:number,E1:number)=>{const delta=E1-E0;return Math.abs(delta)<=32*Number.EPSILON*Math.max(E0,E1,Number.MIN_VALUE)?"zero":delta>0?"positive":"negative";};
function HistoryPlot({run,duration,index,kind}:{run:Run;duration:number;index:number;kind:"position"|"energy"|"balance"}){
  const id=useId(),s=run.samples[index];
  const configuration={
    position:{title:"Position (m)",actual:(r:Sample)=>r.position,reference:(r:Sample)=>r.exactPosition},
    energy:{title:"Mechanical energy (J)",actual:(r:Sample)=>r.energy,reference:(r:Sample)=>r.exactEnergy},
    balance:{title:"Energy balance residual (J)",actual:(r:Sample)=>r.balanceResidual,reference:()=>0},
  }[kind];
  const all=run.samples.flatMap(r=>[configuration.actual(r),configuration.reference(r)]),lo=Math.min(0,...all),hi=Math.max(0,...all),flat=hi===lo,min=flat?-.5:lo,max=flat?.5:hi,span=max-min;
  const x=(time:number)=>85+250*time/duration,y=(value:number)=>210-158*(value-min)/span;
  const line=(read:(s:Sample)=>number)=>run.samples.map(row=>`${x(row.time)},${y(read(row))}`).join(" ");
  return <figure><svg viewBox="0 0 360 270" role="img" aria-labelledby={id}><title id={id}>{`${configuration.title} versus time in seconds. Solid blue is the computed path. Dashed brown is ${kind==="balance"?"zero for an exact energy account":"the analytic reference for the same model"}. A dark dot marks the selected numerical sample. Gray after a stopped run means no numerical path was computed there. The selected-state and complete path tables give equivalent values.`}</title>
    <text x="180" y="23" textAnchor="middle" fontSize="19" fill="#243b38">{configuration.title}</text>
    {!run.completed&&<rect x={x(run.final.time)} y="45" width={335-x(run.final.time)} height="168" fill="#e2e0dc"/>}
    {[0,.5,1].map(f=><g key={f}><line x1="85" x2="335" y1={y(min+f*span)} y2={y(min+f*span)} stroke="#c7d3ce"/><text x="78" y={y(min+f*span)+5} textAnchor="end" fontSize="18" fill="#243b38">{tick(min+f*span)}</text><text x={x(f*duration)} y="236" textAnchor="middle" fontSize="18" fill="#243b38">{tick(f*duration)}</text></g>)}
    <polyline points={line(configuration.reference)} fill="none" stroke="#933d20" strokeWidth="3" strokeDasharray="8 4"/>
    <polyline points={line(configuration.actual)} fill="none" stroke="#145f84" strokeWidth="3"/>
    <circle cx={x(s.time)} cy={y(configuration.actual(s))} r="5" fill="#243b38"/>
    <text x="210" y="262" textAnchor="middle" fontSize="18" fill="#243b38">Time (s)</text>
  </svg><figcaption>Blue solid: {kind==="balance"?"E + D_trap − E0 on the numerical path":"numerical "+(kind==="position"?"position":"energy")}. Brown dashed: {kind==="balance"?"zero, the exact-model account":"analytic "+(kind==="position"?"position":"energy")+" at the same sampled times"}. The dark dot is selected by the keyboard time control. Lines join computed samples; they do not supply new observations. {flat&&"The zero trace uses a centered one-unit display range."} {!run.completed&&"Gray marks the uncomputed remainder of the requested interval."}</figcaption></figure>;
}
export function Phs231NumericalLab({activity}:{activity:NumericalActivity}){
  const [method,setMethod]=useState(activity.initial.method),[values,setValues]=useState(valuesFor(activity.initial)),[predictions,setPredictions]=useState(["","",""]),[energySign,setEnergySign]=useState(""),[result,setResult]=useState<Result|null>(null),[message,setMessage]=useState(""),[refinement,setRefinement]=useState<0|1|2>(0),[index,setIndex]=useState(0),[page,setPage]=useState(0);
  const clear=()=>{setResult(null);setMessage("");};
  const apply=(p:NumericalInput)=>{setMethod(p.method);setValues(valuesFor(p));setPredictions(["","",""]);setEnergySign("");setRefinement(0);setIndex(0);setPage(0);clear();};
  const check=()=>{
    try{
      if(controls.some(([key])=>!values[key]?.trim()))throw Error("Complete every model input. An empty value is not zero.");
      const parsed=numericalInputSchema.safeParse({method,...Object.fromEntries(controls.map(([key])=>[key,Number(values[key])]))});
      if(!parsed.success)throw Error("Use finite inputs within the printed ranges and at most 2000 base steps: ceil(final time / base step) ≤ 2000. The two refinements use at most 8000 steps.");
      if(predictions.some(s=>!s.trim())||!energySign)throw Error("Predict the initial acceleration, first-step position and velocity, and first-step energy change before running.");
      const answer=(raw:string)=>{
        const s=raw.trim();
        if(/^[+-]?(?:\d+(?:\.\d*)?|\.\d+)(?:e[+-]?\d+)?$/i.test(s)){const n=Number(s);if(!Number.isFinite(n))throw Error("Predictions must be finite real values.");return n;}
        const n=parseExact(s);if(!realExact(n))throw Error("Predictions must be real numbers.");return approximateExact(n).real;
      };
      const r=numericalRun(parsed.data),first=r.runs[0].first!,expected=[r.initialAcceleration,first.position,first.velocity],labels=["initial acceleration","first-step position","first-step velocity"],tolerances=[1e-9,1e-10,1e-10],missed:string[]=[];
      predictions.forEach((raw,i)=>{const n=answer(raw);if(!Number.isFinite(n)||Math.abs(n-expected[i])>Math.max(tolerances[i],Math.abs(expected[i])*1e-8))missed.push(labels[i]);});
      if(energySign!==sign(r.runs[0].initialEnergy,first.energy))missed.push("first-step energy change");
      setResult(r);setRefinement(0);setIndex(1);setPage(0);
      setMessage(missed.length?`Revisit ${missed.join(", ")}. Use the actual first width, evaluate -(k*x+b*v)/m at the specified state, and keep old, midpoint, and updated values separate. Recompute both endpoint energies from their own x and v. The tables show the calculation for comparison.`:"All four predictions agree with the specified update. Now compare h, h/2, and h/4 at the same requested final time; agreement with this model does not validate a physical experiment.");
    }catch(error){setResult(null);setMessage(error instanceof Error?error.message:"Check the inputs.");}
  };
  const presets:[string,NumericalInput][]=[
    ["Undamped baseline",baseline],["Explicit energy growth",{...baseline,method:"explicit"}],["Midpoint comparison",{...baseline,method:"midpoint"}],["Shortened final step",{...baseline,durationS:1,stepS:.3}],["Zero equilibrium",{...baseline,positionM:0}],["Critical damping",{...baseline,dragKgPerS:4}],["Overdamped comparison",{...baseline,dragKgPerS:8}],["Semi stability boundary",{...baseline,stepS:.5}],["Beyond stable interval",{...baseline,stepS:.6}],["Early computational stop",{...baseline,method:"explicit",massKg:.1,springNPerM:200,positionM:1,stepS:1,durationS:20}],["Step longer than record",{...baseline,durationS:.04}],
  ];
  const run=result?.runs[refinement],s=run?.samples[index],pages=run?Math.ceil(run.samples.length/100):0;
  const download=()=>{
    if(!result)return;
    const blob=new Blob([numericalCsv(result.input,refinement)],{type:"text/csv;charset=utf-8"}),url=URL.createObjectURL(blob),link=document.createElement("a");
    link.href=url;link.download=`phs231-${result.input.method}-${["base","half","quarter"][refinement]}.csv`;link.click();setTimeout(()=>URL.revokeObjectURL(url),1000);
  };
  return <div className="phs231-investigation"><p><MathText>{activity.prompt}</MathText></p>
    <p className="muted">This is a simulation with synthetic, exact model inputs. It is not a spring or motion-sensor experiment. Controls and outputs reset on reload; save the inputs, predictions, evidence, and revisions in lesson notes. Downloaded tables preserve every computed state.</p>
    <p><MathText>{"The supplied model is $x'=v$, $mv'=-kx-bv$, with fixed mass, linear spring constant, and nonnegative viscous coefficient. Position is signed from equilibrium. The analytic reference solves this same law with the same initial state; it does not establish whether a real spring, support, or damper follows the law."}</MathText></p>
    <div className="field"><label htmlFor="phs231-numerical-method">Time-step method</label><select id="phs231-numerical-method" value={method} onChange={event=>{setMethod(event.target.value as NumericalInput["method"]);clear();}}>{Object.entries(names).map(([id,name])=><option key={id} value={id}>{name}</option>)}</select></div>
    <fieldset className="phs231-predictions"><legend>Model and requested interval</legend><div className="phs231-controls">{controls.map(([key,label,min,max,step])=><div className="field" key={key}><label htmlFor={`phs231-numerical-${key}`}>{label}</label><input id={`phs231-numerical-${key}`} type="number" min={min} max={max} step={step} value={values[key]??""} aria-describedby={`phs231-numerical-${key}-range`} onChange={event=>{setValues(current=>({...current,[key]:event.target.value}));clear();}}/><small id={`phs231-numerical-${key}-range`}>Allowed range: {min} to {max}.</small></div>)}</div>
      <p>At most 2000 requested base steps. Each run clips only its last step to the requested final time; a step longer than the record uses the whole record as one step. Refinement means h/2 and h/4 with unchanged physical inputs.</p>
    </fieldset>
    <p><MathText>{method==="explicit"?"Explicit Euler: $x_{n+1}=x_n+h v_n$, $v_{n+1}=v_n+h a(x_n,v_n)$. Compute both increments from the old state.":method==="semi"?"Velocity-first Euler: $v_{n+1}=v_n+h a(x_n,v_n)$, then $x_{n+1}=x_n+h v_{n+1}$. The drag force here uses old velocity; this is not a fully implicit damping solve.":"Explicit midpoint: $x_m=x_n+h v_n/2$, $v_m=v_n+h a(x_n,v_n)/2$; then $x_{n+1}=x_n+h v_m$, $v_{n+1}=v_n+h a(x_m,v_m)$. Both midpoint values are provisional, not new initial data."}</MathText></p>
    <details><summary>Load prepared numerical comparisons</summary><div className="form-actions">{presets.map(([label,p])=><button className="button secondary" key={label} onClick={()=>apply(p)}>{label}</button>)}</div></details>
    <fieldset className="phs231-predictions"><legend>Predict one step before comparing full paths</legend>
      <p>Use the smaller of the requested step and final time for this first update. Enter fractions, sqrt(...), or finite decimals, including scientific notation. Accepted error is 0.000000001 m/s² for acceleration and 0.0000000001 m or m/s for state, or one part in 100 million of the expected magnitude, whichever is larger.</p>
      <div className="phs231-controls">{["Predicted initial acceleration (m/s²)","Predicted first-step position (m)","Predicted first-step velocity (m/s)"].map((label,i)=><div className="field" key={label}><label htmlFor={`phs231-numerical-prediction-${i}`}>{label}</label><input id={`phs231-numerical-prediction-${i}`} maxLength={200} value={predictions[i]} onChange={event=>{setPredictions(current=>current.map((v,j)=>j===i?event.target.value:v));clear();}}/></div>)}</div>
      <div className="field"><label htmlFor="phs231-numerical-sign">Predicted first-step mechanical energy change</label><select id="phs231-numerical-sign" value={energySign} onChange={event=>{setEnergySign(event.target.value);clear();}}><option value="">Choose a sign</option><option value="positive">Positive</option><option value="negative">Negative</option><option value="zero">Zero to numerical precision</option></select></div>
      <p>The sign compares E1 − E0 using E = (mv² + kx²)/2. A difference within 32 floating-point epsilon units of the larger energy is grouped as zero to numerical precision; that is not a proof of exact conservation.</p>
    </fieldset>
    <div className="form-actions"><button className="button" onClick={check}>Check and compare steps</button><button className="button secondary" onClick={()=>apply(activity.initial)}>Reset numerical investigation</button></div><p role="status" className="form-status">{message}</p>
    {result&&run&&s&&<div className="notice">
      <p><strong>{names[result.input.method]}.</strong> ω = {display(result.omega)} s⁻¹, b/(2m) = {display(result.alpha)} s⁻¹. The analytic reference is {result.regime==="critical"?"critically damped":result.regime}. Maximum base-step ωh = {display(result.stepRatio)}.</p>
      <p>{result.stability==="explicit-energy-growth"?"For this undamped model, simultaneous explicit Euler multiplies nonzero-state energy by 1 + (ωh)² per actual step. Shrinking h reduces finite-time error; a fixed positive step still has energy growth.":result.stability==="midpoint-energy-growth"?"For this undamped model, explicit midpoint multiplies nonzero-state energy by 1 + (ωh)⁴/4 per actual step. Second-order accuracy does not imply exact energy conservation.":result.stability==="semi-bounded"?"The base step lies inside 0 < ωh < 2 for the stated undamped velocity-first method. A uniform-step trajectory is bounded but physical energy can oscillate; a shortened final step is still checked at its actual width.":result.stability==="semi-boundary"?"The base step reaches ωh = 2. This boundary is not generally stable: its repeated eigenvalue can give growing amplitudes. A zero equilibrium or special initial state is not a general stability test.":result.stability==="semi-growth"?"The base step exceeds ωh = 2. The stated undamped velocity-first method generally grows numerically in this range. Check each refined run separately.":"Damping changes the update matrix. The undamped velocity-first threshold alone does not validate this run. Use analytic agreement, refinement, actual widths, and the energy account together."}</p>
      <div className="phs231-table" role="region" tabIndex={0} aria-label="Numerical refinement comparison"><table style={{minWidth:"62rem"}}><caption>Same requested endpoint, same initial conditions, three requested step sizes</caption><thead><tr>{["Run","Requested step (s)","Completed steps","Last computed time (s)","Reached requested T?","Endpoint position error (m)","Endpoint velocity error (m/s)","Largest sampled position error (m)","Largest sampled |E + D − E0| (J)"].map(label=><th scope="col" key={label}>{label}</th>)}</tr></thead><tbody>{result.runs.map((r,i)=><tr key={i}><th scope="row">{["Base h","Half h/2","Quarter h/4"][i]}</th><td>{display(r.stepS)}</td><td>{r.steps}</td><td>{display(r.final.time)}</td><td>{r.completed?"Yes":"No"}</td><td>{r.finalPositionError===null?"Not reached":display(r.finalPositionError)}</td><td>{r.finalVelocityError===null?"Not reached":display(r.finalVelocityError)}</td><td>{display(r.maxSampledPositionError)}</td><td>{display(r.maxSampledBalanceResidual)}</td></tr>)}</tbody></table></div>
      <p>Errors use numerical minus analytic state at the same time. Sampled maxima are not bounds between nodes. One unusually small endpoint error can come from cancellation; inspect the path and velocity too. Three refinements do not certify a physical model or a rigorous error bound.</p>
      <div className="field"><label htmlFor="phs231-numerical-run">Path to inspect</label><select id="phs231-numerical-run" value={refinement} onChange={event=>{setRefinement(Number(event.target.value) as 0|1|2);setIndex(0);setPage(0);}}><option value="0">Base step h</option><option value="1">Half step h/2</option><option value="2">Quarter step h/4</option></select></div>
      {run.stopped&&<p role="alert"><strong>Numerical run stopped at {display(run.final.time)} s.</strong> {run.stopped.reason} The first rejected attempt targeted {display(run.stopped.attemptedTime)} s. Bounds are |x| ≤ 1,000,000 m and |v| ≤ 100,000,000 m/s. Its requested-endpoint errors are unavailable; do not compare its last state as though it reached T.</p>}
      <div className="field"><label htmlFor="phs231-numerical-sample">Numerical time sample</label><input id="phs231-numerical-sample" type="range" min={0} max={run.samples.length-1} step={1} value={index} aria-valuetext={`Sample ${index}, time ${display(s.time)} seconds, position ${display(s.position)} meters`} onChange={event=>setIndex(Number(event.target.value))}/><p>Selected sample {index} of {run.steps}; time <strong>{display(s.time)} s</strong>. Use arrow keys, Home, and End. The actual preceding width is {display(s.stepWidth)} s.</p></div>
      <div className="form-actions"><button className="button secondary" onClick={()=>setIndex(Math.min(1,run.steps))}>Inspect first step</button><button className="button secondary" onClick={()=>setIndex(run.steps)}>Inspect last computed step</button><button className="button secondary" onClick={()=>setPage(Math.floor(index/100))}>Show selected table page</button><button className="button secondary" onClick={download}>Download complete numerical CSV</button></div>
      <HistoryPlot run={run} duration={result.input.durationS} index={index} kind="position"/><HistoryPlot run={run} duration={result.input.durationS} index={index} kind="energy"/><HistoryPlot run={run} duration={result.input.durationS} index={index} kind="balance"/>
      <div className="phs231-table" role="region" tabIndex={0} aria-label="Selected numerical state"><table><caption>Computed state and reference at {display(s.time)} s</caption><thead><tr><th scope="col">Quantity</th><th scope="col">Value</th><th scope="col">Unit</th></tr></thead><tbody>{([
        ["Actual preceding step width",s.stepWidth,"s"],["Numerical position",s.position,"m"],["Analytic position",s.exactPosition,"m"],["Signed position error",s.positionError,"m"],["Numerical velocity",s.velocity,"m/s"],["Analytic velocity",s.exactVelocity,"m/s"],["Signed velocity error",s.velocityError,"m/s"],["Acceleration at this numerical state",s.acceleration,"m/s²"],["Numerical mechanical energy",s.energy,"J"],["Analytic mechanical energy",s.exactEnergy,"J"],["Mechanical energy change",s.energyChange,"J"],["Trapezoid dissipation estimate",s.dissipation,"J"],["Energy balance residual",s.balanceResidual,"J"],["Absolute position error divided by reference magnitude",s.relativePositionError,"1"],
      ] as [string,number|null,string][]).map(([label,value,unit])=><tr key={label}><th scope="row">{label}</th><td>{value===null?"Unavailable: "+(s.relativePositionErrorReason==="zero-reference"?"zero reference":"ratio exceeds numerical range"):display(value)}</td><td>{unit}</td></tr>)}</tbody></table></div>
      <p><MathText>{"The analytic model obeys $dE/dt=-bv^2$. Here $D_{trap}=\\sum b(v_n^2+v_{n+1}^2)h_n/2$ uses the actual numerical velocities and widths. Its residual $E+D_{trap}-E_0$ combines state-integration and dissipation-quadrature error. It is not measured heat or an observed physical energy source."}</MathText></p>
      <details><summary>Complete numerical path table</summary>
        <div className="field"><label htmlFor="phs231-numerical-page">State table page</label><select id="phs231-numerical-page" value={page} onChange={event=>setPage(Number(event.target.value))}>{Array.from({length:pages},(_,i)=><option key={i} value={i}>{`Page ${i+1}: rows ${i*100+1}–${Math.min((i+1)*100,run.samples.length)}`}</option>)}</select></div>
        <p>Showing rows {page*100+1}–{Math.min((page+1)*100,run.samples.length)} of {run.samples.length}. Every computed state is accessible through these pages and the complete CSV. Values display nine significant digits; the CSV retains floating-point precision, input provenance, and any stop reason.</p>
        <div className="form-actions"><button className="button secondary" disabled={page===0} onClick={()=>setPage(page-1)}>Previous state page</button><button className="button secondary" disabled={page===pages-1} onClick={()=>setPage(page+1)}>Next state page</button></div>
        <div className="phs231-table" role="region" tabIndex={0} aria-label="Complete numerical path table" style={{maxHeight:"24rem",overflowY:"auto"}}><table style={{minWidth:"90rem"}}><caption>All computed states, page {page+1}; selected row highlighted</caption><thead style={{position:"sticky",top:0,background:"#f6f8f3"}}><tr>{["Time (s)","Actual step (s)","Position (m)","Reference position (m)","Position error (m)","Velocity (m/s)","Reference velocity (m/s)","Velocity error (m/s)","Acceleration (m/s²)","Energy (J)","Reference energy (J)","Energy change (J)","Dissipation (J)","Balance residual (J)"].map(label=><th scope="col" key={label}>{label}</th>)}</tr></thead><tbody>{run.samples.slice(page*100,(page+1)*100).map((r,i)=><tr key={r.time} aria-current={i+page*100===index?"true":undefined} style={i+page*100===index?{background:"#dcece5"}:undefined}><th scope="row">{display(r.time)}</th>{[r.stepWidth,r.position,r.exactPosition,r.positionError,r.velocity,r.exactVelocity,r.velocityError,r.acceleration,r.energy,r.exactEnergy,r.energyChange,r.dissipation,r.balanceResidual].map((value,j)=><td key={j}>{display(value)}</td>)}</tr>)}</tbody></table></div>
      </details>
    </div>}
    <h3 className="section-space">Build a convergence record</h3>
    <ol><li>Start with the undamped baseline. Derive its exact x(t) and v(t) from the supplied initial state and independently calculate each method’s first update. Predict the sign of its first energy change before revealing the run.</li><li>Record explicit Euler and velocity-first Euler at h = 0.1, 0.05, and 0.025 s, always to T = 4 s. Include final position and velocity errors, largest sampled position error, and energy residual. Explain why an endpoint alone can hide phase error. Add midpoint as a second-order comparison.</li><li>Use the shortened-last-step case. Record the actual final widths and confirm every completed path ends at T = 1 s. Then inspect the semi-implicit boundary and early-stop cases. Distinguish a numerical computation bound from a physical stop, and exclude incomplete runs from endpoint convergence claims.</li><li>Compare zero, critically damped, and overdamped trials. Audit E + D_trap − E0 with units. Save a CSV and a concise evidence table in lesson notes, including one corrected prediction, a step-size recommendation for this model, and the extra measurement needed to validate a real force law.</li></ol>
    <p>Score four criteria from 0 to 2: reproducible inputs and update order; independent analytic and first-step checks; controlled refinement and energy evidence; and limitations with a justified revision. Use 0 for missing, 1 for partial or materially incorrect, and 2 for complete justified evidence. The proposed practice target is at least 6 of 8 with no zero. This is a learning rubric, not an official NU laboratory grade.</p>
  </div>;
}
