"use client";

import { useId, useState } from "react";
import { drivenInputSchema, drivenRun, type DrivenActivity } from "@/lib/learning/phs-232-driven";
import { approximateExact, parseExact, realExact } from "@/lib/learning/exact-number";
import { MathText } from "./math-text";
import styles from "./phs-232-driven-lab.module.css";
import "./phs-232.css";

type Run = ReturnType<typeof drivenRun>;
type Output = "amplitude" | "velocityAmplitude" | "meanPower";
const outputs: Record<Output, [string, string]> = { amplitude: ["Displacement amplitude", "m"], velocityAmplitude: ["Velocity amplitude", "m/s"], meanPower: ["Mean periodic power", "W"] };
const display = (n: number | null) => n === null ? "undefined" : n !== 0 && (Math.abs(n) < .001 || Math.abs(n) > 1e6) ? n.toExponential(6) : String(Number(n.toPrecision(8)));
const tick = (n: number) => n !== 0 && (Math.abs(n) < .01 || Math.abs(n) >= 10000) ? n.toExponential(1).replace(".0e", "e") : String(Number(n.toPrecision(3)));
const controls = [["mass", "Driven mass (kg)", .05, 10, .05], ["stiffness", "Driven spring stiffness (N/m)", .05, 200, .05], ["dampingRatio", "Driven damping ratio zeta", 0, 3, .01], ["force", "Force amplitude F0 (N)", 0, 20, .01], ["frequencyRatio", "Selected forcing ratio Omega / omega0", 0, 4, .01], ["position", "Driven initial position (m)", -.5, .5, .01], ["velocity", "Driven initial velocity (m/s)", -5, 5, .01], ["cycles", "Driven window (natural periods T0)", .25, 12, .25]] as const;
const peaks = { interior: "Positive interior peak", endpoint: "Static endpoint maximum", unbounded: "Unbounded resonant amplitude", undefined: "Periodic power undefined at undamped resonance", flat: "Zero response: no unique peak" };
const phases = { zero: "Zero lag", below: "Between zero and pi/2", quarter: "Exactly pi/2", above: "Between pi/2 and pi", pi: "Exactly pi", undefined: "Undefined: zero force or singular response" };

function ResponseTable({ responses, label }: { responses: Run["sweep"]; label: string }) {
  return <div className={styles.table} role="region" aria-label={`${label}; scroll horizontally if needed`} tabIndex={0}><table><caption>{label}</caption><thead><tr>{["Omega / omega0", "Omega (rad/s)", "A (m)", "V amplitude (m/s)", "Lag (rad)", "Mean power (W)"].map(text => <th key={text} scope="col">{text}</th>)}</tr></thead><tbody>{responses.map((r, i) => <tr key={i}><th scope="row">{display(r.ratio)}</th>{[r.omega, r.amplitude, r.velocityAmplitude, r.lag, r.meanPower].map((n, j) => <td key={j}>{display(n)}</td>)}</tr>)}</tbody></table></div>;
}

function StateTable({ run }: { run: Run }) {
  const id = useId(), [record, setRecord] = useState("fine"), [page, setPage] = useState(0);
  const selected = record === "coarse" ? run.coarse : record === "cycle-coarse" ? run.cycle!.coarse : record === "cycle-fine" ? run.cycle!.fine : run.fine;
  const pages = Math.ceil(selected.states.length / 64), names: Record<string, string> = { coarse: "Window: coarse", fine: "Window: refined", "cycle-coarse": "Last full cycle: coarse", "cycle-fine": "Last full cycle: refined" };
  return <details><summary>All time states and independent work integrals</summary><p>Both resolutions expose every endpoint. Cycle-record work and loss start at zero at that cycle&apos;s printed start time; window-record integrals start at t=0. Simpson quadrature also evaluates the midpoint of each interval. It does not define work or loss from an energy difference.</p>
    <div className="phs232-controls"><div className="field"><label htmlFor={`${id}-record`}>Driven state record</label><select id={`${id}-record`} value={record} onChange={e => { setRecord(e.target.value); setPage(0); }}>{Object.entries(names).filter(([key]) => !key.startsWith("cycle") || run.cycle).map(([key, name]) => <option key={key} value={key}>{name}</option>)}</select></div><div className="field"><label htmlFor={`${id}-page`}>Driven state table page</label><select id={`${id}-page`} value={page} onChange={e => setPage(Number(e.target.value))}>{Array.from({ length: pages }, (_, i) => <option key={i} value={i}>{i + 1} of {pages}: states {64 * i}–{Math.min(selected.states.length - 1, 64 * i + 63)}</option>)}</select></div></div>
    <div className="form-actions"><button className="button secondary" disabled={page === 0} onClick={() => setPage(page - 1)}>Previous driven table page</button><button className="button secondary" disabled={page === pages - 1} onClick={() => setPage(page + 1)}>Next driven table page</button></div>
    <div className={styles.table} role="region" aria-label="Driven state table; scroll horizontally if needed" tabIndex={0}><table><caption>{names[record]}: {selected.states.length} states; page {page + 1} of {pages}</caption><thead><tr>{["State", "Time (s)", "Total x (m)", "Total v (m/s)", "Total a (m/s²)", "Particular x (m)", "Particular v (m/s)", "Force (N)", "Input power (W)", "Viscous power (W)", "K (J)", "U (J)", "E (J)", "Input work (J)", "Dissipated (J)", "Balance residual (J)"].map(text => <th key={text} scope="col">{text}</th>)}</tr></thead><tbody>{selected.states.slice(page * 64, page * 64 + 64).map((s, i) => <tr key={i}><th scope="row">{page * 64 + i}</th>{[s.time, s.position, s.velocity, s.acceleration, s.particularPosition, s.particularVelocity, s.force, s.inputPower, s.dissipativePower, s.kinetic, s.potential, s.energy, s.inputWork, s.dissipated, s.balanceResidual].map((n, j) => <td key={j}>{display(n)}</td>)}</tr>)}</tbody></table></div>
  </details>;
}

function DrivenPlots({ run, output, stateIndex, sweepIndex, trajectory }: { run: Run; output: Output; stateIndex: number; sweepIndex: number; trajectory: string }) {
  const id = useId(), states = run.fine.states, probe = states[stateIndex], events = run.events.filter(event => event.response.ratio <= 4);
  const sweepMax = Math.max(...run.sweep.map(r => r[output] ?? 0), ...events.map(e => e.response[output] ?? 0)) * 1.05 || 1;
  const sx = (ratio: number) => 90 + 285 * ratio / 4, sy = (value: number) => 180 - 140 * value / sweepMax;
  const segments: string[][] = [[]]; for (const r of run.sweep) { const value = r[output]; if (value === null) segments.push([]); else segments.at(-1)!.push(`${sx(r.ratio)},${sy(value)}`); }
  const extent = 1.05 * Math.max(...states.map(s => Math.max(trajectory === "particular" ? 0 : Math.abs(s.position), trajectory === "full" ? 0 : Math.abs(s.particularPosition ?? 0)))) || 1;
  const tx = (time: number) => 90 + 285 * time / run.duration, ty = (value: number) => 108 - 68 * value / extent;
  const energyMin = Math.min(0, ...states.map(s => s.inputWork)), energyMax = Math.max(0, ...states.flatMap(s => [s.energy, s.inputWork, s.dissipated]));
  const span = energyMax - energyMin || 1, ey = (value: number) => 180 - 140 * (value - energyMin) / span;
  return <div className="phs232-plots">
    <figure><svg viewBox="0 0 400 265" role="img" aria-labelledby={`${id}-sweep`}><title id={`${id}-sweep`}>{outputs[output][0]} against forcing frequency ratio at fixed force amplitude. Blue lines join uniform samples; brown circles mark exact special frequencies within the sweep. Every value is in the response and event tables. Singular points are left open.</title>
      <path d="M90 35V180H385" fill="none" stroke="#a1aba7"/><text x="90" y="25">Response ({outputs[output][1]})</text><text x="8" y="46">{tick(sweepMax)}</text><text x="8" y="186">0</text><text x="87" y="215">0</text><text x="375" y="215" textAnchor="end">4</text><text x="232" y="248" textAnchor="middle">Ω / ω0</text>
      {segments.filter(s => s.length > 1).map((points, i) => <polyline key={i} points={points.join(" ")} fill="none" stroke="#176582" strokeWidth="2.5"/>)}
      {events.map((event, i) => event.response[output] !== null && <circle key={i} cx={sx(event.response.ratio)} cy={sy(event.response[output]!)} r="4" fill="#8c411e"><title>{event.label}: {display(event.response[output])} {outputs[output][1]}</title></circle>)}
      <line x1={sx(run.sweep[sweepIndex].ratio)} x2={sx(run.sweep[sweepIndex].ratio)} y1="35" y2="180" stroke="#293f36" strokeDasharray="2 3"/>
    </svg><figcaption>{outputs[output][0]} at fixed F0. Straight segments join 129 uniform samples; circles independently locate analytic events. A sparse curve cannot resolve a narrow peak&apos;s width. Read its half-power frequencies in the event table. Undefined response points are not joined; an undamped singular peak is unbounded.</figcaption></figure>
    <figure><svg viewBox="0 0 400 265" role="img" aria-labelledby={`${id}-state`}><title id={`${id}-state`}>Displacement versus time. Solid blue is the full initial-value response and dashed brown is the bounded particular response when selected and defined. The state table supplies both.</title><path d="M90 35V180H385 M90 108H385" fill="none" stroke="#a1aba7"/><text x="90" y="25">Position (m)</text><text x="8" y="46">{tick(extent)}</text><text x="8" y="114">0</text><text x="8" y="181">{tick(-extent)}</text><text x="87" y="215">0</text><text x="375" y="215" textAnchor="end">{tick(run.duration)}</text><text x="232" y="248" textAnchor="middle">Time (s)</text>
      {trajectory !== "full" && run.response.amplitude !== null && <polyline points={states.map(s => `${tx(s.time)},${ty(s.particularPosition!)}`).join(" ")} fill="none" stroke="#8c411e" strokeWidth="2.5" strokeDasharray="6 4"/>}
      {trajectory !== "particular" && <polyline points={states.map(s => `${tx(s.time)},${ty(s.position)}`).join(" ")} fill="none" stroke="#176582" strokeWidth="2.5"/>}<line x1={tx(probe.time)} x2={tx(probe.time)} y1="35" y2="180" stroke="#293f36" strokeDasharray="2 3"/>
    </svg><figcaption>Solid blue = total state; dashed brown = bounded particular state. Display: {trajectory === "both" ? "both" : trajectory === "full" ? "full state only" : "particular state only"}. The scale follows the selected traces. Near weakly damped resonance a large particular amplitude can hide a small startup response; choose full state only to inspect it. At undamped exact resonance no bounded particular trace exists.</figcaption></figure>
    <figure><svg viewBox="0 0 400 265" role="img" aria-labelledby={`${id}-energy`}><title id={`${id}-energy`}>Mechanical energy, signed input work and nonnegative viscous transfer versus time. Solid blue is E, dashed brown is input work, dotted green is dissipated energy. Independent quadrature residuals are in the evidence table.</title><path d="M90 35V180H385" fill="none" stroke="#a1aba7"/><text x="90" y="25">Energy / work (J)</text><text x="8" y="46">{tick(energyMax || 1)}</text><text x="8" y="186">{tick(energyMin)}</text><text x="87" y="215">0</text><text x="375" y="215" textAnchor="end">{tick(run.duration)}</text><text x="232" y="248" textAnchor="middle">Time (s)</text>
      <polyline points={states.map(s => `${tx(s.time)},${ey(s.energy)}`).join(" ")} fill="none" stroke="#176582" strokeWidth="2.5"/><polyline points={states.map(s => `${tx(s.time)},${ey(s.inputWork)}`).join(" ")} fill="none" stroke="#8c411e" strokeWidth="2.5" strokeDasharray="6 4"/><polyline points={states.map(s => `${tx(s.time)},${ey(s.dissipated)}`).join(" ")} fill="none" stroke="#293f36" strokeWidth="2.5" strokeDasharray="2 3"/><line x1={tx(probe.time)} x2={tx(probe.time)} y1="35" y2="180" stroke="#293f36" strokeDasharray="2 3"/>
    </svg><figcaption>Solid blue = E; dashed brown = signed W_in; dotted green = D≥0. Check E−E0−W_in+D. Negative instantaneous driver power can make W_in decrease. Neither W_in nor D is calculated from the energy difference.</figcaption></figure>
  </div>;
}

export function Phs232DrivenLab({ activity }: { activity: DrivenActivity }) {
  const id = useId(), initial = controls.map(([key]) => String(activity.initial[key]));
  const [values, setValues] = useState(initial), [intervals, setIntervals] = useState(String(activity.initial.intervals)), [output, setOutput] = useState<Output>("amplitude");
  const [amplitude, setAmplitude] = useState(""), [peak, setPeak] = useState(""), [phase, setPhase] = useState("");
  const [run, setRun] = useState<Run | null>(null), [message, setMessage] = useState(""), [stateIndex, setStateIndex] = useState(0), [sweepIndex, setSweepIndex] = useState(0), [sweepPage, setSweepPage] = useState(0), [trajectory, setTrajectory] = useState("both");
  const clear = () => { setRun(null); setMessage(""); setStateIndex(0); setSweepIndex(0); setSweepPage(0); };
  const check = () => {
    try {
      if (values.some(value => !value.trim())) throw Error("Complete every model input; an empty input is not zero.");
      const parsed = drivenInputSchema.safeParse({ ...Object.fromEntries(controls.map(([key], i) => [key, Number(values[i])])), intervals: Number(intervals) });
      if (!parsed.success) throw Error("Use the labeled ranges. Positive zeta, force amplitude and frequency ratio must be at least 0.000001; exact zero is supported.");
      if (!amplitude.trim() || !peak || !phase) throw Error("Predict the bounded particular amplitude, selected output's peak behavior and phase lag before revealing.");
      const result = drivenRun(parsed.data), expectedAmplitude = result.response.amplitude;
      let amplitudeCorrect = amplitude.trim().toLowerCase() === "none" && expectedAmplitude === null;
      if (amplitude.trim().toLowerCase() !== "none") { const value = parseExact(amplitude); if (!realExact(value)) throw Error("Use a finite real amplitude, or none for a singular bounded response."); const n = approximateExact(value).real; if (!Number.isFinite(n)) throw Error("Use a finite real amplitude."); amplitudeCorrect = expectedAmplitude !== null && Math.abs(n - expectedAmplitude) <= Math.max(1e-6, 1e-6 * expectedAmplitude); }
      const expectedPeak = result.peaks.kind === "zero-force" ? "flat" : result.peaks.kind === "undamped" ? output === "meanPower" ? "undefined" : "unbounded" : output === "amplitude" && result.peaks.displacementRatio === 0 ? "endpoint" : "interior";
      const expectedPhase = result.response.lag === null ? "undefined" : result.response.lag === 0 ? "zero" : result.response.lag === Math.PI ? "pi" : result.model.frequencyRatio === 1 ? "quarter" : result.model.frequencyRatio < 1 ? "below" : "above";
      const missed = [amplitudeCorrect ? "" : "particular amplitude", peak === expectedPeak ? "" : "output-specific peak", phase === expectedPhase ? "" : "phase lag"].filter(Boolean);
      setRun(result); setStateIndex(0); setSweepIndex(0); setSweepPage(0);
      setMessage(missed.length ? `Revisit ${missed.join(", ")}. Use the full dynamic-stiffness magnitude, name the measured output, and retain the phase quadrant. The tables below provide evidence for revising your prediction.` : "Your predictions agree with the model. Compare startup states, periodic response and independently integrated work before drawing a conclusion.");
    } catch (error) { setRun(null); setMessage(error instanceof Error ? error.message : "Check the inputs."); }
  };
  const probe = run?.fine.states[stateIndex], selected = run?.sweep[sweepIndex];
  return <div className="phs232-investigation"><p><MathText>{activity.prompt}</MathText></p><p className="muted">Simulation: a linear spring and viscous damper driven by a prescribed force F0 cos(Ωt), with fixed force amplitude during each sweep. It is not base-displacement excitation. Controls reset on reload; save all inputs, predictions and evidence in lesson notes. No physical equipment is assigned. These software ranges do not establish a real spring&apos;s linear range or apparatus ratings.</p>
    <div className="phs232-controls">{controls.map(([key, label, min, max, step], i) => <div className="field" key={key}><label htmlFor={`${id}-${key}`}>{label}</label><input id={`${id}-${key}`} type="number" min={min} max={max} step={step} value={values[i]} onChange={e => { setValues(current => current.map((value, j) => i === j ? e.target.value : value)); clear(); }}/><small>Allowed: {min} to {max}.{["dampingRatio", "force", "frequencyRatio"].includes(key) ? " Use zero or at least 0.000001." : ""}</small></div>)}
      <div className="field"><label htmlFor={`${id}-intervals`}>Driven coarse intervals</label><select id={`${id}-intervals`} value={intervals} onChange={e => { setIntervals(e.target.value); clear(); }}>{[64, 128, 256, 512].map(n => <option key={n} value={n}>{n}</option>)}</select><small>Refined records use twice as many intervals.</small></div><div className="field"><label htmlFor={`${id}-output`}>Measured sweep output</label><select id={`${id}-output`} value={output} onChange={e => { setOutput(e.target.value as Output); clear(); }}>{Object.entries(outputs).map(([key, [name]]) => <option key={key} value={key}>{name}</option>)}</select></div>
    </div>
    <fieldset className="phs232-predictions"><legend>Predict the response before revealing</legend><p>Predict the bounded particular displacement amplitude at the selected frequency, even when studying another sweep output. Use decimals, fractions or supported radicals; the tolerance is 0.000001 m or one part per million, whichever is larger. Enter none at undamped exact resonance with nonzero force. Peak behavior refers to all Ω≥0, not just the displayed sweep.</p><div className="phs232-controls">
      <div className="field"><label htmlFor={`${id}-amplitude`}>Predicted particular amplitude (m), or none</label><input id={`${id}-amplitude`} maxLength={200} value={amplitude} onChange={e => { setAmplitude(e.target.value); clear(); }}/></div><div className="field"><label htmlFor={`${id}-peak`}>Predicted peak behavior for the selected output</label><select id={`${id}-peak`} value={peak} onChange={e => { setPeak(e.target.value); clear(); }}><option value="">Choose a prediction</option>{Object.entries(peaks).map(([key, text]) => <option key={key} value={key}>{text}</option>)}</select></div><div className="field"><label htmlFor={`${id}-phase`}>Predicted displacement lag at the selected frequency</label><select id={`${id}-phase`} value={phase} onChange={e => { setPhase(e.target.value); clear(); }}><option value="">Choose a prediction</option>{Object.entries(phases).map(([key, text]) => <option key={key} value={key}>{text}</option>)}</select></div>
    </div></fieldset>
    <div className="form-actions"><button className="button" onClick={check}>Check driven predictions</button><button className="button secondary" onClick={() => { setValues(initial); setIntervals(String(activity.initial.intervals)); setOutput("amplitude"); setAmplitude(""); setPeak(""); setPhase(""); setTrajectory("both"); clear(); }}>Reset driven model</button></div><p className="form-status" role="status">{message}</p>
    {run && probe && selected && <div className={`notice ${styles.results}`}>
      <p>omega0={display(run.model.omega0)} rad/s; beta={display(run.model.beta)} 1/s; b={display(run.model.b)} kg/s; selected Ω={display(run.model.omega)} rad/s. Window={display(run.duration)} s ({values[7]} natural periods). E0={display(run.model.initialEnergy)} J. Q={display(run.peaks.quality)}; at b=0 the finite viscous Q and half-power bandwidth are not defined.</p>
      <p>Bounded particular response: A={display(run.response.amplitude)} m; lag={display(run.response.lag)} rad; mean periodic power={display(run.response.meanPower)} W; periodic input work per forcing cycle={display(run.response.cycleWork)} J.</p>
      {run.response.kind === "resonant" ? <p>Undamped exact resonance: no bounded sinusoidal particular response exists. Its phase and periodic mean power are undefined. The full finite-time initial-value response remains available below and grows in the ideal model.</p> : run.response.kind === "zero-force" ? <p>Zero force: the particular response is zero, its phase is undefined, and there is no unique forced-response peak or forcing period. Any nonzero full trajectory is a free response from the initial state.</p> : run.response.kind === "constant" ? <p>Constant force: the particular state is F0/k with zero velocity. There is no finite forcing cycle. The full trajectory may still move while approaching this state.</p> : run.model.b === 0 ? <p>Zero damping away from resonance: a bounded particular response exists, but a nonzero homogeneous correction does not decay. The full trajectory is not necessarily this particular response at late times.</p> : <p>Positive damping: the initial-state correction decays. The bounded particular response is approached with time, but a finite startup window need not already be periodic.</p>}
      <div className="field"><label htmlFor={`${id}-sweep-probe`}>Driven sweep probe (uniform sample index): {sweepIndex}</label><input id={`${id}-sweep-probe`} type="range" min="0" max="128" step="1" value={sweepIndex} aria-valuetext={`Frequency ratio ${display(selected.ratio)}`} onChange={e => setSweepIndex(Number(e.target.value))}/></div><div className="form-actions"><button className="button secondary" disabled={sweepIndex === 0} onClick={() => setSweepIndex(sweepIndex - 1)}>Previous sweep frequency</button><button className="button secondary" disabled={sweepIndex === 128} onClick={() => setSweepIndex(sweepIndex + 1)}>Next sweep frequency</button></div><p className="phs232-sweep-probe" aria-live="polite">Sweep probe: Ω/ω0={display(selected.ratio)}; Ω={display(selected.omega)} rad/s; A={display(selected.amplitude)} m; V={display(selected.velocityAmplitude)} m/s; lag={display(selected.lag)} rad; mean power={display(selected.meanPower)} W. This probe does not change the selected time-trace frequency.</p>
      <div className="field"><label htmlFor={`${id}-time-probe`}>Driven time probe (refined state index): {stateIndex}</label><input id={`${id}-time-probe`} type="range" min="0" max={run.fine.states.length - 1} step="1" value={stateIndex} aria-valuetext={`State ${stateIndex}; ${display(probe.time)} seconds`} onChange={e => setStateIndex(Number(e.target.value))}/></div><div className="form-actions"><button className="button secondary" disabled={stateIndex === 0} onClick={() => setStateIndex(stateIndex - 1)}>Previous driven state</button><button className="button secondary" disabled={stateIndex === run.fine.states.length - 1} onClick={() => setStateIndex(stateIndex + 1)}>Next driven state</button></div><p>Use each slider&apos;s arrows, Home and End, or its buttons. Both probes have complete table alternatives.</p>
      <p className="phs232-driven-probe" aria-live="polite">Time probe: t={display(probe.time)} s; x={display(probe.position)} m; v={display(probe.velocity)} m/s; a={display(probe.acceleration)} m/s²; particular x={display(probe.particularPosition)} m; particular v={display(probe.particularVelocity)} m/s; F={display(probe.force)} N; Fv={display(probe.inputPower)} W; bv²={display(probe.dissipativePower)} W; E={display(probe.energy)} J; W_in={display(probe.inputWork)} J; D={display(probe.dissipated)} J; residual={display(probe.balanceResidual)} J.</p>
      <div className="field"><label htmlFor={`${id}-trajectory`}>Trajectory display</label><select id={`${id}-trajectory`} value={trajectory} onChange={e => setTrajectory(e.target.value)}><option value="both">Full and particular responses</option><option value="full">Full initial-value response only</option><option value="particular">Bounded particular response only</option></select></div>
      <DrivenPlots run={run} output={output} stateIndex={stateIndex} sweepIndex={sweepIndex} trajectory={trajectory}/>
      <details><summary>Exact response peaks and half-power frequencies</summary><p>Events are derived from the continuous response function, independently of the 129 sweep samples. Half power refers to mean power at fixed F0. Frequency events outside Ω/ω0=0..4 are listed but not plotted.</p>{run.events.length === 0 && <p>Zero force gives no unique response peak.</p>}{run.events.map((event, i) => <div key={i}><p><strong>{event.label}</strong>{event.response.ratio > 4 ? " (outside displayed sweep)" : ""}</p><ResponseTable responses={[event.response]} label={`Response event ${i + 1}`}/></div>)}{run.peaks.halfPower && <p>Exact half-power width={display(run.peaks.halfPower.width * run.model.omega0)} rad/s=b/m. This does not measure a half-displacement-amplitude width.</p>}</details>
      <details><summary>All uniform frequency-response samples</summary><p>129 frequencies, including both endpoints. Undefined entries at undamped resonance represent a singular bounded response, not zero.</p><div className="field"><label htmlFor={`${id}-sweep-page`}>Driven sweep table page</label><select id={`${id}-sweep-page`} value={sweepPage} onChange={e => setSweepPage(Number(e.target.value))}>{[0, 1, 2].map(i => <option key={i} value={i}>{i + 1} of 3: frequencies {i * 64}–{Math.min(128, i * 64 + 63)}</option>)}</select></div><ResponseTable responses={run.sweep.slice(sweepPage * 64, sweepPage * 64 + 64)} label={`Uniform sweep page ${sweepPage + 1}`}/></details>
      <div className={styles.table} role="region" aria-label="Driven work evidence; scroll horizontally if needed" tabIndex={0}><table><caption>Independent work integrals and refinement over the full window</caption><thead><tr><th scope="col">Measure</th><th scope="col">Coarse</th><th scope="col">Refined</th></tr></thead><tbody>
        <tr><th scope="row">Time step (s)</th><td>{display(run.coarse.step)}</td><td>{display(run.fine.step)}</td></tr><tr><th scope="row">Input work at window end (J)</th><td>{display(run.coarse.states.at(-1)!.inputWork)}</td><td>{display(run.fine.states.at(-1)!.inputWork)}</td></tr><tr><th scope="row">Viscous transfer at window end (J)</th><td>{display(run.coarse.states.at(-1)!.dissipated)}</td><td>{display(run.fine.states.at(-1)!.dissipated)}</td></tr><tr><th scope="row">Maximum |E−E0−W_in+D| (J)</th><td>{display(run.coarse.maxBalanceResidual)}</td><td>{display(run.fine.maxBalanceResidual)}</td></tr>
      </tbody></table></div><p>Largest aligned work difference={display(run.maxWorkDifference)} J; loss difference={display(run.maxLossDifference)} J. Refine the intervals and compare the digits used in your conclusion. These numerical comparisons are not guaranteed error bounds or instrument uncertainty. The full state is evaluated through a stable matrix exponential, including singular steady-response limits; work and loss use separate power quadrature.</p>
      {run.cycle ? <><p>Last complete forcing cycle in the window: {display(run.cycle.start)} to {display(run.cycle.end)} s. This is a finite interval of the full response, not an assertion that transients have ended.</p><div className={styles.table} role="region" aria-label="Driven last-cycle evidence; scroll horizontally if needed" tabIndex={0}><table><caption>Full-response last-cycle account</caption><thead><tr><th scope="col">Measure</th><th scope="col">Coarse (128 intervals)</th><th scope="col">Refined (256 intervals)</th></tr></thead><tbody>{["input", "loss", "energy", "residual"].map(key => <tr key={key}><th scope="row">{{ input: "Mean input power (W)", loss: "Mean viscous power (W)", energy: "Stored energy change (J)", residual: "Maximum balance residual (J)" }[key]}</th>{[run.cycle!.coarse, run.cycle!.fine].map((record, j) => <td key={j}>{display(key === "input" ? record.states.at(-1)!.inputWork / (run.cycle!.end - run.cycle!.start) : key === "loss" ? record.states.at(-1)!.dissipated / (run.cycle!.end - run.cycle!.start) : key === "energy" ? record.states.at(-1)!.energy - record.states[0].energy : record.maxBalanceResidual)}</td>)}</tr>)}</tbody></table></div><p>Compare these means with the particular-response mean power above. In the full response, unequal mean input and loss correspond to a stored energy change divided by this interval&apos;s duration.</p></> : <p>No complete forcing cycle is available: the selected window is too short, or the input is constant or zero. A natural reference period does not replace a missing forcing cycle.</p>}
      <StateTable run={run}/><p>Displayed values are rounded floating-point calculations; 1e-6 means 0.000001 in the labeled unit. A finite recording cannot by itself establish a steady state, a peak location, or a physical apparatus limit.</p>
      <ol><li>Keep m=1 kg, k=25 N/m, F0=1 N, zeta=0.2 and the initial zero state. Compare forcing ratios 0.5, 1 and 1.5. Record amplitude, lag, signed input power and the last-cycle means; increase the window to examine the remaining transient.</li><li>Compare displacement, velocity and mean-power sweeps at the same fixed force. Locate exact peaks and both half-power frequencies, and explain why the displacement maximum is below omega0.</li><li>Compare zeta=0.6, 1/√2 (enter its decimal value), 0.8 and 2. Explain the loss of a positive displacement peak while the velocity/power maximum remains. At the threshold, classify the endpoint carefully using the intended value and displayed precision.</li><li>Set zeta=0 and forcing ratio=1. Predict none for the bounded particular amplitude, then inspect the full response. Compare ratios 0.9999 and 1.0001 and zeta=0.000001. Use full state only when a huge particular response would hide startup.</li><li>Compare 64, 128 and 256 coarse intervals for one run. Report work/loss differences and residuals, not just visual overlap. Include a window without a full drive cycle, a constant-force run and a zero-force run.</li></ol>
      <p>Save reproducible below/near/above-frequency runs, both sides of the displacement-peak threshold, a startup/periodic comparison, an undamped resonant case and a refinement comparison in lesson notes.</p>
      <details><summary>Driven investigation self-check rubric</summary><p>Score each criterion 0 for missing or incorrect, 1 for partial and 2 for complete evidence. Revise every score below 2. This proposed self-check is not an official grade and does not award objective evidence.</p><ol><li><strong>Conditions:</strong> record all inputs and units, the cosine force convention, fixed force amplitude, selected output and both initial coordinates.</li><li><strong>Resonance:</strong> distinguish displacement, velocity and power peaks; use exact events and half-power definitions instead of reading a narrow peak from a coarse curve.</li><li><strong>Phase and startup:</strong> recover the correct quadrant, compare the full and particular states, and explain the zero-damping and constant-force exceptions.</li><li><strong>Energy evidence:</strong> compare independently integrated input work and loss with stored energy change at two resolutions, and distinguish finite-cycle means from periodic predictions.</li><li><strong>Limits and revision:</strong> support or revise a prediction with reproducible evidence and explain numerical, finite-window and linear-model limits without claiming physical experimental validation.</li></ol></details>
    </div>}
  </div>;
}
