"use client";

import { useId, useState } from "react";
import { rollingInputSchema, rollingRun, type RollingActivity, type RollingInput } from "@/lib/learning/phs-231-rolling";
import { approximateExact, parseExact, realExact } from "@/lib/learning/exact-number";
import { MathText } from "./math-text";
import "./phs-231.css";

const display=(n:number)=>n===0?"0":Math.abs(n)>=100000||Math.abs(n)<.00001?n.toExponential(4):String(Number(n.toFixed(6)));
const tick=(n:number)=>n!==0&&(Math.abs(n)>=10000||Math.abs(n)<.01)?n.toExponential(1):String(Number(n.toPrecision(3)));
const vector=(v:number[])=>`(${v.map(display).join(", ")})`;
const baseline:RollingInput={mass:2,radius:.5,beta:.5,slope:.75,gravity:10,muStatic:.3,muKinetic:.2,force:0,couple:0,v0:0,omega0:0,duration:2};
const controls:[keyof RollingInput,string,number,number,number][]=[
  ["mass","Body mass (kg)",.1,20,.1],["radius","Contact radius (m)",.05,2,.05],["beta","Inertia ratio beta",.1,1,.1],
  ["slope","Incline rise divided by run",0,2,.05],["gravity","Model gravity (m/s²)",1,20,.1],["duration","Trial duration (s)",.1,10,.1],
  ["muStatic","Static friction coefficient",0,1.5,.05],["muKinetic","Kinetic friction coefficient",0,1.5,.05],
  ["force","Signed hub force (N)",-50,50,.1],["couple","Applied clockwise couple (N m)",-20,20,.1],
  ["v0","Initial center velocity (m/s)",-10,10,.1],["omega0","Initial clockwise angular velocity (rad/s)",-40,40,.1],
];
type Result={input:RollingInput;state:ReturnType<typeof rollingRun>};
type Sample=Result["state"]["final"];
type NumericKey={ [K in keyof Sample]:Sample[K] extends number?K:never }[keyof Sample];
const motionColumns:[NumericKey,string,string][]=[["x","Center displacement","m"],["v","Center velocity","m/s"],["angle","Unwrapped clockwise angle","rad"],["omega","Clockwise angular velocity","rad/s"],["acceleration","Center acceleration","m/s²"],["alpha","Clockwise angular acceleration","rad/s²"],["slip","Contact slip velocity","m/s"],["friction","Signed contact friction","N"],["normal","Normal force","N"],["topVelocity","Instantaneous top-point velocity","m/s"],["contactNormalAcceleration","Bottom-point outward normal acceleration","m/s²"]];
const energyColumns:[NumericKey,string,string][]=[["translationKinetic","Translational kinetic energy","J"],["rotationKinetic","Rotational kinetic energy","J"],["totalKinetic","Total kinetic energy","J"],["gravityWork","Gravity work","J"],["hubWork","Hub force work","J"],["coupleWork","Applied couple work","J"],["frictionWork","Contact friction work on body","J"],["heat","Thermal conversion","J"],["frictionPower","Contact friction power on body","W"],["hubPower","Hub force power","W"],["couplePower","Applied couple power","W"],["gravityPower","Gravity power","W"],["frictionImpulse","Tangential friction impulse","N s"],["energyResidual","Energy balance residual","J"],["linearResidual","Linear impulse residual","N s"],["angularResidual","Angular impulse residual","N m s"]];

function WheelView({result,index}:{result:Result;index:number}){
  const id=useId(),s=result.state.samples[index],R=result.input.radius,scale=100/R,px=180+(s.pointPosition[0]-s.x)*scale,py=145-(s.pointPosition[1]-R)*scale;
  return <figure><svg viewBox="0 0 360 325" role="img" aria-labelledby={id}><title id={id}>{`Ramp-aligned snapshot centered on the moving body at t=${display(s.time)} s. The marked material point is an orange circle; the current bottom location is a blue square. The point began at the bottom but need not remain there. Equivalent position, velocity, and acceleration are in the marked-point table.`}</title>
    <text x="180" y="23" textAnchor="middle" fontSize="18" fill="#243b38">Wheel in ramp-aligned coordinates</text>
    <circle cx="180" cy="145" r="100" fill="#e4efee" stroke="#526a63" strokeWidth="2"/>
    <line x1="25" x2="335" y1="245" y2="245" stroke="#526a63" strokeWidth="3"/><text x="335" y="270" textAnchor="end" fontSize="18" fill="#243b38">+x downhill</text>
    <line x1="180" x2="180" y1="145" y2="58" stroke="#718f87" strokeDasharray="4 3"/><text x="187" y="65" fontSize="18" fill="#243b38">+y</text>
    <line x1="180" y1="145" x2={px} y2={py} stroke="#933d20" strokeDasharray="6 3"/>
    <rect x="171" y="236" width="18" height="18" fill="#fff" stroke="#145f84" strokeWidth="3"/>
    <circle cx={px} cy={py} r="6" fill="#933d20"/><circle cx="180" cy="145" r="4" fill="#243b38"/>
    <text x="180" y="297" textAnchor="middle" fontSize="18" fill="#243b38">{`Center x = ${display(s.x)} m`}</text>
    <text x="180" y="319" textAnchor="middle" fontSize="18" fill="#243b38">{`Current contact slip = ${display(s.slip)} m/s`}</text>
  </svg><figcaption>The view follows the center; its displacement is stated below the drawing. The plane is horizontal in these ramp-aligned axes, not necessarily in the laboratory. Orange follows one material point from its initial bottom location. Blue marks the current bottom location, usually a different material point. The outline shows radius; it does not encode the mass distribution or β.</figcaption></figure>;
}
function VelocityPlot({result,index}:{result:Result;index:number}){
  const id=useId(),R=result.input.radius,rows=result.state.samples,all=rows.flatMap(s=>[s.v,R*s.omega,s.slip]),rawLow=Math.min(0,...all),rawHigh=Math.max(0,...all),low=rawLow===rawHigh?-1:rawLow,high=rawLow===rawHigh?1:rawHigh,span=Math.max(1,high-low),bottom=low-.05*span,top=high+.05*span;
  const x=(t:number)=>85+250*t/result.input.duration,y=(v:number)=>210-158*(v-bottom)/(top-bottom);
  const series:[string,(s:Sample)=>number,string,string|undefined][]=[["center",s=>s.v,"#145f84",undefined],["rim",s=>R*s.omega,"#933d20","7 3"],["slip",s=>s.slip,"#243b38","2 3"]];
  return <figure><svg viewBox="0 0 360 260" role="img" aria-labelledby={id}><title id={id}>Signed velocities versus time. Center velocity is solid blue, R omega is long brown dashes, and contact slip is short dark dots. Rolling requires equality of the first two and zero slip. All values and exact transition times are in the tables.</title>
    <text x="180" y="23" textAnchor="middle" fontSize="20" fill="#243b38">Signed velocity (m/s)</text>
    {[0,.5,1].map(f=><g key={f}><line x1="85" x2="335" y1={y(low+f*(high-low))} y2={y(low+f*(high-low))} stroke="#c7d3ce"/><text x="78" y={y(low+f*(high-low))+5} textAnchor="end" fontSize="18" fill="#243b38">{tick(low+f*(high-low))}</text><text x={x(f*result.input.duration)} y="233" textAnchor="middle" fontSize="18" fill="#243b38">{tick(f*result.input.duration)}</text></g>)}
    {series.map(([name,get,color,dash])=><polyline key={name} points={rows.map(s=>`${x(s.time)},${y(get(s))}`).join(" ")} fill="none" stroke={color} strokeWidth="2.5" strokeDasharray={dash}/>)}
    <line x1={x(rows[index].time)} x2={x(rows[index].time)} y1="45" y2="213" stroke="#71613d" strokeDasharray="4 4"/>
    <text x="210" y="256" textAnchor="middle" fontSize="18" fill="#243b38">Time (s)</text>
  </svg><figcaption>Center velocity v: solid blue. Signed rim rate Rω: long brown dashes. Contact slip v−Rω: short dark dots. Lines connect analytic samples, including any exact contact transition. Matching center and rim rates mark no slip; a zero center velocity alone does not. Use the snapshot slider or transition button to inspect the table.</figcaption></figure>;
}
export function Phs231RollingLab({activity}:{activity:RollingActivity}){
  const valuesFor=(p:RollingInput)=>controls.map(([key])=>String(p[key]));
  const [values,setValues]=useState(valuesFor(activity.initial)),[predictions,setPredictions]=useState(["","","",""]),[result,setResult]=useState<Result|null>(null),[message,setMessage]=useState(""),[index,setIndex]=useState(0);
  const clear=()=>{setResult(null);setMessage("");};
  const apply=(p:RollingInput)=>{setValues(valuesFor(p));setIndex(0);clear();};
  const check=()=>{
    try{
      if(values.some(v=>!v.trim()))throw Error("Complete every model input; an empty input is not zero.");
      const parsed=rollingInputSchema.safeParse(Object.fromEntries(controls.map(([key],i)=>[key,Number(values[i])])));
      if(!parsed.success)throw Error("Use finite values in the printed ranges, positive mass/radius/inertia ratio, and a kinetic coefficient no greater than the static coefficient.");
      if(predictions.some(v=>!v.trim()))throw Error("Predict required static friction, static capacity, actual initial center acceleration, and actual initial angular acceleration first.");
      const state=rollingRun(parsed.data),expected=[state.requiredFriction,state.staticLimit,state.initial.acceleration,state.initial.alpha],names=["required static friction","static capacity","actual initial center acceleration","actual initial angular acceleration"];
      const missed=predictions.flatMap((raw,i)=>{
        const text=raw.trim();let answer:number;
        if(/^[+-]?(?:\d+(?:\.\d*)?|\.\d+)(?:e[+-]?\d+)?$/i.test(text)){answer=Number(text);if(!Number.isFinite(answer))throw Error("Predictions must be finite real numbers.");}
        else{const exact=parseExact(text);if(!realExact(exact))throw Error("Predictions must be real numbers.");answer=approximateExact(exact).real;}
        return Math.abs(answer-expected[i])<=Math.max(.00001,Math.abs(expected[i])*1e-8)?[]:[names[i]];
      });
      setResult({input:parsed.data,state});setIndex(0);
      setMessage(missed.length?`Revisit ${missed.join(", ")}. Solve the force and torque equations for the candidate static demand, then check its bound and the initial contact slip. During sliding use kinetic friction and solve a and α separately.`:"All four predictions agree with the force, torque, and contact account.");
    }catch(error){setResult(null);setMessage(error instanceof Error?error.message:"Check the inputs.");}
  };
  const presets:[string,Partial<RollingInput>][]=[["Passive rolling ramp",{}],["Insufficient traction",{muStatic:.2,muKinetic:.1}],["Slide into rolling",{slope:0,v0:3}],["Overspin into rolling",{slope:0,omega0:12}],["Rolling uphill",{v0:-3,omega0:-6}],["Hub force on level",{slope:0,force:6}],["Drive couple on level",{slope:0,couple:3}],["Slip reverses",{slope:0,force:-9,muStatic:.1,muKinetic:.05,v0:1,duration:1}],["Frictionless incline",{muStatic:0,muKinetic:0}],["Frictionless compatible rolling",{slope:0,muStatic:0,muKinetic:0,v0:2,omega0:4}]];
  const s=result?.state.samples[index];
  return <div className="phs231-investigation"><p><MathText>{activity.prompt}</MathText></p>
    <p className="muted">This is an analytic simulation, not a physical release or powered-wheel experiment. It uses a symmetric rigid body on an infinite stationary straight plane with ideal point contact. No rolling resistance, deformation, drag, or actuator limit is modeled. Controls reset on reload; save findings in lesson notes.</p>
    <p>Positive x points downhill along the plane and positive scalar ω is clockwise in the ramp-aligned view. The hub force is parallel to the plane; the applied couple is a separate load. Both stay constant. The normal force is mg cosθ. Kinetic friction opposes the contact velocity v−Rω, which may have a different sign from the center velocity.</p>
    {["Geometry, slope, and time","Contact, loading, and initial motion"].map((heading,group)=><fieldset className="phs231-predictions" key={heading}><legend>{heading}</legend><div className="phs231-controls">{controls.slice(group*6,group*6+6).map(([key,label,min,max,step],j)=>{const i=group*6+j;return <div className="field" key={key}><label htmlFor={`phs231-rolling-${key}`}>{label}</label><input id={`phs231-rolling-${key}`} type="number" min={min} max={max} step={step} value={values[i]} aria-describedby={`phs231-rolling-${key}-range`} onChange={event=>{setValues(current=>current.map((v,k)=>i===k?event.target.value:v));clear();}}/><small id={`phs231-rolling-${key}-range`}>Allowed range: {min} to {max}.</small></div>;})}</div></fieldset>)}
    <p><MathText>{"The inertia ratio is $\\beta=I_{\\rm cm}/(mR^2)$: an ideal uniform solid sphere has 2/5, disk or cylinder 1/2, and thin hoop 1. Rise/run equals $\\tan\\theta$; for example 3/4 gives $\\sin\\theta=3/5$ and $\\cos\\theta=4/5$. A coefficient is dimensionless, and this model requires $0\\le\\mu_k\\le\\mu_s$."}</MathText></p>
    <div className="form-actions">{presets.map(([label,patch])=><button className="button secondary" key={label} onClick={()=>apply({...baseline,...patch})}>{label}</button>)}</div>
    <fieldset className="phs231-predictions"><legend>Predict demand and actual motion</legend><p>Required static friction is a candidate force even when rolling is infeasible or initial motion is slipping. For the last two answers, use the actual initial contact regime. Enter exact fractions, sqrt(...), or decimals; accepted error is 0.00001 in the labeled unit or one part in 100 million of the result, whichever is larger.</p><div className="phs231-controls">{["Predicted required static friction (N)","Predicted static capacity (N)","Predicted actual initial center acceleration (m/s²)","Predicted actual initial angular acceleration (rad/s²)"].map((label,i)=><div className="field" key={label}><label htmlFor={`phs231-rolling-prediction-${i}`}>{label}</label><input id={`phs231-rolling-prediction-${i}`} maxLength={200} value={predictions[i]} onChange={event=>{setPredictions(current=>current.map((v,j)=>i===j?event.target.value:v));clear();}}/></div>)}</div></fieldset>
    <div className="form-actions"><button className="button" onClick={check}>Check rolling account</button><button className="button secondary" onClick={()=>{apply(activity.initial);setPredictions(["","","",""]);}}>Reset rolling investigation</button></div><p role="status" className="form-status">{message}</p>
    {result&&s&&<div className="notice">
      <p>Candidate static friction: <strong>{display(result.state.requiredFriction)} N</strong>; available magnitude: <strong>{display(result.state.staticLimit)} N</strong>. <strong>{result.state.feasible?"The static demand is within capacity.":"The static demand exceeds capacity."}</strong></p>
      <p>Actual initial contact: <strong>{result.state.initial.kind==="rolling"?"no slip":"sliding"}</strong>, with slip {display(result.state.initialSlip)} m/s and friction {display(result.state.initial.friction)} N. {result.state.initial.kind==="sliding"&&result.state.feasible?"Initial velocity mismatch still requires a sliding phase before the feasible rolling state can be reached.":result.state.initial.kind==="sliding"?"The candidate rolling constraint cannot be imposed with this capacity.":"The contact force is the required value, which can be below the maximum or zero."}</p>
      <p>At the end: <strong>v={display(result.state.final.v)} m/s</strong>, <strong>ω={display(result.state.final.omega)} rad/s</strong>, and contact slip <strong>{display(result.state.final.slip)} m/s</strong>. Thermal conversion: <strong>{display(result.state.final.heat)} J</strong>.</p>
      {result.state.events.length?result.state.events.map((event,i)=><p key={event.time}>{event.kind==="rolling-starts"?"Rolling starts":"Slip reverses without sustained rolling"} at <strong>t={display(event.time)} s</strong>. Velocity and spin remain continuous; the force law changes. {event.time===result.input.duration?"This event is at the trial endpoint; the following phase has zero duration in the displayed record.":""} <button className="button secondary" onClick={()=>setIndex(result.state.samples.findIndex(row=>row.time===event.time))}>{`Inspect transition ${i+1}`}</button></p>):<p>No change of contact regime occurs within this trial. A center-velocity reversal alone need not change the friction direction.</p>}
      <div className="phs231-table" role="region" tabIndex={0} aria-label="Rolling contact phases"><table><caption>Exact piecewise contact history</caption><thead><tr><th scope="col">Start (s)</th><th scope="col">End (s)</th><th scope="col">Regime</th><th scope="col">Friction (N)</th><th scope="col">a (m/s²)</th><th scope="col">α (rad/s²)</th></tr></thead><tbody>{result.state.phases.map((phase,i)=><tr key={i}><th scope="row">{display(phase.start)}</th><td>{display(phase.end)}</td><td>{phase.kind==="rolling"?"No slip":"Sliding"}</td><td>{display(phase.friction)}</td><td>{display(phase.acceleration)}</td><td>{display(phase.alpha)}</td></tr>)}</tbody></table></div>
      <div className="field"><label htmlFor="phs231-rolling-sample">Rolling snapshot sample</label><input id="phs231-rolling-sample" type="range" min={0} max={result.state.samples.length-1} step={1} value={index} onChange={event=>setIndex(Number(event.target.value))}/><p>Sample {index} of {result.state.samples.length-1}; selected time <strong>{display(s.time)} s</strong>. Use arrow keys, Home, and End. There is no automatic animation.</p></div>
      <WheelView result={result} index={index}/><VelocityPlot result={result} index={index}/>
      <div className="phs231-table" role="region" tabIndex={0} aria-label="Selected rolling motion"><table><caption>Motion and contact at t={display(s.time)} s: {s.kind==="rolling"?"no slip":"sliding"}</caption><thead><tr><th scope="col">Quantity</th><th scope="col">Value</th><th scope="col">Unit</th></tr></thead><tbody>{motionColumns.map(([key,label,unit])=><tr key={key}><th scope="row">{label}</th><td>{display(s[key])}</td><td>{unit}</td></tr>)}</tbody></table></div>
      <div className="phs231-table" role="region" tabIndex={0} aria-label="Marked rolling point"><table><caption>One material point initially at the bottom; vectors use the fixed ramp-aligned axes</caption><thead><tr><th scope="col">Position (m)</th><th scope="col">Velocity (m/s)</th><th scope="col">Acceleration (m/s²)</th></tr></thead><tbody><tr><td>{vector(s.pointPosition)}</td><td>{vector(s.pointVelocity)}</td><td>{vector(s.pointAcceleration)}</td></tr></tbody></table></div>
      <div className="phs231-table" role="region" tabIndex={0} aria-label="Selected rolling energy"><table><caption>Energy, power, and accumulated work from t=0 to {display(s.time)} s</caption><thead><tr><th scope="col">Quantity</th><th scope="col">Value</th><th scope="col">Unit</th></tr></thead><tbody>{energyColumns.map(([key,label,unit])=><tr key={key}><th scope="row">{label}</th><td>{display(s[key])}</td><td>{unit}</td></tr>)}</tbody></table></div>
      <p><MathText>{"Friction's total power on this body is $f(v-R\\omega)$. Thermal conversion is $-W_f$ for the stationary plane. The energy residual is $K-K_0-W_g-W_F-W_M-W_f$. The linear impulse residual uses all along-plane forces; the angular impulse residual uses the applied couple and contact moment about CM. Small residuals can reflect floating-point rounding, not physical measurement accuracy."}</MathText></p>
      <details><summary>Compare three inertia ratios</summary><p>These are separate trials with every input except β held fixed. Static feasibility describes the required force if a no-slip state is reached. The actual initial acceleration also depends on whether the initial velocities already satisfy that constraint.</p><div className="phs231-table" role="region" tabIndex={0} aria-label="Rolling inertia comparison"><table><caption>Uniform solid sphere, disk, and thin hoop inertia models</caption><thead><tr><th scope="col">Model</th><th scope="col">β</th><th scope="col">Required f (N)</th><th scope="col">Capacity admits rolling</th><th scope="col">Actual initial a (m/s²)</th><th scope="col">Initial regime</th></tr></thead><tbody>{([["Solid sphere",.4],["Disk or cylinder",.5],["Thin hoop",1]] as const).map(([label,beta])=>{const r=rollingRun({...result.input,beta});return <tr key={label}><th scope="row">{label}</th><td>{beta}</td><td>{display(r.requiredFriction)}</td><td>{r.feasible?"Yes":"No"}</td><td>{display(r.initial.acceleration)}</td><td>{r.initial.kind==="rolling"?"No slip":"Sliding"}</td></tr>;})}</tbody></table></div></details>
      {([["Complete rolling motion table",motionColumns],["Complete rolling energy table",energyColumns]] as const).map(([title,columns])=><details key={title}><summary>{title}</summary><div className="phs231-table" role="region" tabIndex={0} aria-label={title}><table><caption>{title}: regular samples plus exact contact transitions</caption><thead><tr><th scope="col">Time (s)</th><th scope="col">Regime</th>{columns.map(([key,label,unit])=><th scope="col" key={key}>{label} ({unit})</th>)}</tr></thead><tbody>{result.state.samples.map(row=><tr key={row.time}><th scope="row">{display(row.time)}</th><td>{row.kind==="rolling"?"No slip":"Sliding"}</td>{columns.map(([key])=><td key={key}>{display(row[key])}</td>)}</tr>)}</tbody></table></div></details>)}
      <p>Investigation record: compare the passive ramp with insufficient traction and explain why a=Rα fails in the latter. Next compare hub-force and couple-driven trials and explain the opposite friction directions. For a slide-to-roll trial, record the exact transition and verify thermal conversion using relative slip distance. Finally inspect the marked material point and explain why instantaneous contact rest does not mean zero acceleration. Save inputs, predictions, numerical evidence, and explanations in lesson notes.</p>
    </div>}
  </div>;
}
