"use client";
import Link from "next/link";
import { useStudy,saveProgress,toggleCourse } from "@/lib/study-store";
import { confidenceOptions,type Confidence } from "@/lib/progress";
import { courseById,type Course } from "@/lib/catalog";
import type { LearningPack } from "@/lib/learning/contracts";
import type { PracticalLesson,PracticalPath } from "@/lib/learning/refreshers/practical-contracts";
import { practicalKey,readPractical,practicalLabel } from "@/lib/learning/refreshers/practical-records";
import { readPracticalDiagnostic,practicalReviewTargets } from "@/lib/learning/refreshers/practical-diagnostic";
import { PageHeading } from "../ui";
import { PracticalDiagnostic } from "./practical-diagnostic";
import { PracticalNotes } from "./practical-notes";
import "./learning.css";
import "./refreshers.css";
export function PracticalWorkspace({course,pack,path,lessons}:{course:Course;pack:LearningPack;path:PracticalPath;lessons:PracticalLesson[]}){
 const {data,ready,locked}=useStudy(),records=lessons.map(l=>readPractical(data.learning.notes[course.id]?.[practicalKey(l.id)],l)),diagnostic=readPracticalDiagnostic(data.learning.notes[course.id]?.["practical-diagnostic"],path.diagnostic,path.version),review=practicalReviewTargets(diagnostic,path.diagnostic,path.targets),next=lessons.find(l=>review.includes(l.id))??lessons.find((_,i)=>!records[i]?.completed||records[i]?.completed?.assisted)??lessons[0],active=lessons.find((_,i)=>records[i]&&!records[i]?.active.completedAt),all=records.every(r=>r?.completed),independent=all&&records.every(r=>!r?.completed?.assisted);
 return <><Link className="back-link" href="/curriculum">Back to curriculum</Link><PageHeading eyebrow={course.code+" · Optional practical refresher"} title={course.title} action={<button className="button secondary" disabled={!ready||locked} onClick={()=>toggleCourse(course.id)}>{data.plan.includes(course.id)?"Added to my plan":"Add to my plan"}</button>}>{pack.introduction}</PageHeading>
 <div className="lesson-kicker"><span className="pill">Free, self-paced study</span><span className="pill neutral">{pack.status==="preview"?"Available preview":"In development"}</span><span className="pill neutral">Independent human review pending</span></div><p className="notice">This optional refresher awards no university credit and establishes no enrollment eligibility. Practical records describe work you produced and self-checked; they are separate from course completion and numerical mastery.</p>
 <div className="refresher-layout section-space"><div className="stack"><section className="panel"><span className="eyebrow">Choose your starting point</span><h2>Quick recall or a full explanation</h2><h3>Quick recall</h3><p>{path.quickRoute}</p><a className="button secondary" href="#diagnostic">Find gaps with the diagnostic</a><h3 className="section-space">Full explanation route</h3><p>{path.fullRoute}</p><Link className="button secondary" href={"/courses/"+course.id+"/lessons/"+lessons[0].id}>Begin the first lesson</Link>{active&&<p><Link className="button" href={"/courses/"+course.id+"/lessons/"+active.id+"#practical-task"}>Resume {active.title}</Link></p>}</section>
 <section className="panel course-lessons" id="recommendations"><span className="eyebrow">Based on saved work</span><h2>Your next useful lesson</h2><p>Diagnostic choices identify specific review topics. A completed record requires your written work and self-check; opening a lesson or selecting confidence records neither.</p><Link className="button" href={"/courses/"+course.id+"/lessons/"+next.id}>{review.includes(next.id)?"Review":"Open"}: {next.title}</Link><ol>{lessons.map((l,i)=><li key={l.id}><Link href={"/courses/"+course.id+"/lessons/"+l.id}>{l.title}</Link><p>{l.objective}</p><small>{ready?practicalLabel(records[i]):"Loading saved work..."}</small>{review.includes(l.id)&&<p>Diagnostic follow-up: revisit this lesson&apos;s reasoning, then try its practical task.</p>}<div className="form-actions"><Link className="text-link" href={"/courses/"+course.id+"/lessons/"+l.id+"#read"}>Recall and explanation</Link><Link className="text-link" href={"/courses/"+course.id+"/lessons/"+l.id+"#practical-task"}>{records[i]?"Resume practical work":"Open practical task"}</Link></div></li>)}</ol><p className="notice" data-testid="practical-portfolio">{independent?"Independent practical portfolio recorded (self-checked).":all?"Practical portfolio recorded with assisted work. Use fresh tasks for independent practice.":"Your portfolio will show drafts and completed practical records here."} The app checks required entries, not the correctness of open-ended reasoning. Independent human review is pending.</p></section>
 <PracticalDiagnostic path={path}/><PracticalNotes courseId={course.id}/>
 </div><aside className="stack"><section className="panel"><h2>What the evidence means</h2><p>Familiarity is your estimate. Guided comparison and revealed reviews are assistance. Independent records are fresh tasks completed without revealing that task&apos;s review, then checked by you against the rubric. They are not automatic certification.</p><div className="field"><label htmlFor="practical-confidence">How familiar does this feel?</label><select id="practical-confidence" value={data.confidence[course.id]??"new"} disabled={!ready||locked} onChange={e=>{const value=e.target.value as Confidence;void saveProgress(current=>({...current,confidence:{...current.confidence,[course.id]:value}}));}}>{Object.entries(confidenceOptions).map(([value,label])=><option key={value} value={value}>{label}</option>)}</select></div><p>Changing confidence does not create or change a practical record.</p></section><section className="panel"><h2>Use these habits next</h2>{path.support.map(s=><p key={s.courseId}><Link className="text-link" href={"/courses/"+s.courseId}>{courseById(s.courseId)?.code}: {courseById(s.courseId)?.title}</Link><br/>{s.reason}</p>)}</section><section className="panel"><h2>When you need more instruction</h2><p>{path.escalation.text}</p><Link className="text-link" href={"/courses/"+path.escalation.courseId}>Open {courseById(path.escalation.courseId)?.code}</Link></section></aside></div></>;
}
