"use client";
import { useId,useState } from "react";
import type { Response } from "@/lib/learning/contracts";
import { gradeQuestion } from "@/lib/learning/grading";
import { additionInvestigation,componentInvestigation,coordinateInvestigation,crossInvestigation,dotInvestigation,type VectorMode,type VectorModel,type VectorArrow } from "@/lib/learning/refreshers/vector-lab";
import { QuestionFields,QuestionFeedback } from "./question-fields";
type Activity={kind:"refresher-vector-lab";mode:VectorMode;prompt:string};
function Select({label,value,options,onChange}:{label:string;value:string;options:(number|string)[];onChange:(v:string)=>void}){const id=useId();return <div className="field"><label htmlFor={id}>{label}</label><select id={id} value={value} onChange={e=>onChange(e.target.value)}>{options.map(v=><option key={v} value={v}>{v}</option>)}</select></div>;}
function Plot({arrows}:{arrows:VectorArrow[]}){
 const id=useId().replaceAll(":",""),extent=Math.max(1,...arrows.flatMap(a=>[...a.from,...a.to]).map(Math.abs))+1,scale=95/extent,x=(v:number)=>165+v*scale,y=(v:number)=>130-v*scale,colors=["#23664f","#8c4a25","#285974","#625274"],patterns=[undefined,"9 3","3 3","10 3 2 3"];
 return <svg viewBox="0 0 330 330" role="img" aria-label="Planar vectors with equal x and y scales. The line-style legend identifies each vector; zero vectors are points. Ordered coordinates and results are in the following table." style={{width:"100%",maxWidth:550}}><defs>{colors.map((color,i)=><marker id={id+i} key={i} markerWidth="6" markerHeight="6" refX="5" refY="3" orient="auto"><path d="M0 0L6 3L0 6Z" fill={color}/></marker>)}</defs><path d="M45 130H285M165 25V240" stroke="currentColor" opacity=".35"/><text x="290" y="135">x</text><text x="173" y="28">y</text><text x="151" y="148">0</text><text x="260" y="148">{Number(extent.toFixed(3))}</text><text x="170" y="40">{Number(extent.toFixed(3))}</text>{arrows.map((a,i)=>{
  const zero=a.from[0]===a.to[0]&&a.from[1]===a.to[1],color=colors[i%4],legendY=260+i*18;
  return <g key={i}>{zero?<circle cx={x(a.from[0])} cy={y(a.from[1])} r="4" fill={color}/>:<path d={`M${x(a.from[0])} ${y(a.from[1])}L${x(a.to[0])} ${y(a.to[1])}`} stroke={color} strokeWidth="2.5" strokeDasharray={patterns[i%4]} markerEnd={`url(#${id}${i%4})`}/>}<path d={`M35 ${legendY-4}H70`} stroke={color} strokeWidth="2.5" strokeDasharray={patterns[i%4]}/><text x="80" y={legendY} fontSize="12">{a.label||"Closing edge "+(i-1)}{zero?" (zero vector)":""}</text></g>;
 })}</svg>;
}
function Prediction({model}:{model:VectorModel}){
 const [response,setResponse]=useState<Response>({}),[checked,setChecked]=useState(false),valid=checked&&gradeQuestion(model.question,response).valid;
 return <><p>{model.question.prompt}</p><QuestionFields question={model.question} response={response} onChange={r=>{setResponse(r);setChecked(false);}}/><div className="form-actions"><button className="button" onClick={()=>setChecked(true)}>Check prediction</button><button className="button secondary" onClick={()=>{setResponse({});setChecked(false);}}>Retry prediction</button></div>{checked&&<div role="status" className="section-space"><QuestionFeedback question={model.question} response={response}/></div>}{valid&&<div className="section-space"><Plot arrows={model.arrows}/><table className="coefficient-table"><caption>{model.caption}</caption><thead><tr><th scope="col">Quantity</th><th scope="col">Value</th></tr></thead><tbody>{model.rows.map((r,i)=><tr key={i}><th scope="row">{r[0]}</th><td>{r[1]}</td></tr>)}</tbody></table><p>Change one control and predict again. Explain a preserved quantity and a changed quantity in your lesson notes. Components and scale labels give the same information without relying on the diagram.</p></div>}</>;
}
export function RefresherVectorLab({activity}:{activity:Activity}){
 const [ax,setAx]=useState(activity.mode==="components"?"1":"3"),[ay,setAy]=useState(activity.mode==="components"?"-1":"4"),[bx,setBx]=useState(activity.mode==="components"?"3":"1"),[by,setBy]=useState(activity.mode==="components"?"4":"0"),[k,setK]=useState("1"),[order,setOrder]=useState("u cross v"),[radius,setRadius]=useState("2"),[angle,setAngle]=useState("30"),[height,setHeight]=useState("1");
 let model:VectorModel|undefined,error="";const a=[Number(ax),Number(ay)],b=[Number(bx),Number(by)],values=[-4,-3,-2,-1,0,1,2,3,4];
 try{model=activity.mode==="components"?componentInvestigation(a,b):activity.mode==="addition"?additionInvestigation(a,b,Number(k)):activity.mode==="dot"?dotInvestigation(a,b):activity.mode==="cross"?crossInvestigation(a,b,order==="v cross u"):coordinateInvestigation(Number(radius),Number(angle),Number(height));}catch(e){error=e instanceof Error?e.message:"Check the vector inputs.";}
 return <><p>{activity.prompt}</p><p className="muted">These predictions are assisted exploration. Independent checkpoints provide objective evidence. Changing a control clears the prediction.</p>{activity.mode==="coordinates"?<><Select label="Cylindrical radius in metres" value={radius} options={[0,1,2,4]} onChange={setRadius}/><Select label="Azimuth in degrees" value={angle} options={[0,30,90,150,225,270,360]} onChange={setAngle}/><Select label="Height in metres" value={height} options={values} onChange={setHeight}/></>:<><Select label={activity.mode==="components"?"Initial x":"Vector u x"} value={ax} options={values} onChange={setAx}/><Select label={activity.mode==="components"?"Initial y":"Vector u y"} value={ay} options={values} onChange={setAy}/><Select label={activity.mode==="components"?"Terminal x":"Vector v x"} value={bx} options={values} onChange={setBx}/><Select label={activity.mode==="components"?"Terminal y":"Vector v y"} value={by} options={values} onChange={setBy}/></>}{activity.mode==="addition"&&<Select label="Scalar multiplying u" value={k} options={[-2,-1,0,1,2]} onChange={setK}/>} {activity.mode==="cross"&&<Select label="Cross-product order" value={order} options={["u cross v","v cross u"]} onChange={setOrder}/>}
 {error?<p role="alert" className="notice warning">{error}</p>:model&&<Prediction key={[activity.mode,ax,ay,bx,by,k,order,radius,angle,height].join(":")} model={model}/>}</>;
}
