"use client";
import { useId,useState } from "react";
import type { Response } from "@/lib/learning/contracts";
import { gradeQuestion } from "@/lib/learning/grading";
import { rectangularInvestigation,conjugateInvestigation,polarInvestigation,rootsInvestigation,type ComplexMode,type ComplexModel } from "@/lib/learning/refreshers/complex-lab";
import { QuestionFields,QuestionFeedback } from "./question-fields";
type Activity={kind:"refresher-complex-lab";mode:ComplexMode;prompt:string};
function Select({label,value,options,onChange}:{label:string;value:string;options:(number|string)[];onChange:(v:string)=>void}){const id=useId();return <div className="field"><label htmlFor={id}>{label}</label><select id={id} value={value} onChange={e=>onChange(e.target.value)}>{options.map(v=><option key={v} value={v}>{v}</option>)}</select></div>;}
function Plot({model}:{model:ComplexModel}){
 const id=useId().replaceAll(":",""),extent=Math.max(1,model.radius??0,...model.arrows.flatMap(a=>[...a.from,...a.to]).map(Math.abs))+1,scale=95/extent,x=(v:number)=>165+scale*v,y=(v:number)=>125-scale*v,colors=["#23664f","#8c4a25","#285974","#625274"],patterns=[undefined,"9 3","3 3","10 3 2 3"];
 return <svg viewBox="0 0 330 345" role="img" aria-label="Complex plane with equally scaled real and imaginary axes. The line-style legend identifies each operation or root. Zero values appear as points. Exact values and checks are in the following table." style={{width:"100%",maxWidth:550}}><defs>{colors.map((color,i)=><marker id={id+i} key={i} markerWidth="6" markerHeight="6" refX="5" refY="3" orient="auto"><path d="M0 0L6 3L0 6Z" fill={color}/></marker>)}</defs>
 <path d="M40 125H285M165 20V230" stroke="currentColor" opacity=".35"/><text x="286" y="140" fontSize="12">Re</text><text x="173" y="23" fontSize="12">Im</text><text x="151" y="143" fontSize="11">0</text><text x="260" y="143" textAnchor="middle" fontSize="11">{Number(extent.toFixed(3))}</text><text x="172" y="35" fontSize="11">{Number(extent.toFixed(3))}</text>
 {model.radius!==undefined&&model.radius>0&&<circle cx="165" cy="125" r={model.radius*scale} fill="none" stroke="currentColor" strokeDasharray="2 4" opacity=".3"/>}
 {model.arrows.map((a,i)=>{const zero=a.from[0]===a.to[0]&&a.from[1]===a.to[1],legendY=259+i*20;return <g key={i}>{zero?<circle cx={x(a.to[0])} cy={y(a.to[1])} r="4" fill={colors[i%4]}/>:<><path d={`M${x(a.from[0])} ${y(a.from[1])}L${x(a.to[0])} ${y(a.to[1])}`} stroke={colors[i%4]} strokeWidth="2.4" strokeDasharray={patterns[i%4]} markerEnd={`url(#${id}${i%4})`}/><circle cx={x(a.to[0])} cy={y(a.to[1])} r="3" fill={colors[i%4]}/></>}<path d={`M30 ${legendY-4}H62`} stroke={colors[i%4]} strokeWidth="2.4" strokeDasharray={patterns[i%4]}/><text x="72" y={legendY} fontSize="12">{a.label}{zero?" (zero)":""}</text></g>;})}</svg>;
}
function Prediction({model}:{model:ComplexModel}){
 const [response,setResponse]=useState<Response>({}),[checked,setChecked]=useState(false),valid=checked&&gradeQuestion(model.question,response).valid;
 return <><p>{model.question.prompt}</p><QuestionFields question={model.question} response={response} onChange={r=>{setResponse(r);setChecked(false);}}/><div className="form-actions"><button className="button" onClick={()=>setChecked(true)}>Check prediction</button><button className="button secondary" onClick={()=>{setResponse({});setChecked(false);}}>Retry prediction</button></div>{checked&&<div role="status" className="section-space"><QuestionFeedback question={model.question} response={response}/></div>}{valid&&<div className="section-space"><Plot model={model}/><table className="coefficient-table"><caption>{model.caption}</caption><thead><tr><th scope="col">Quantity</th><th scope="col">Value</th></tr></thead><tbody>{model.rows.map((r,i)=><tr key={i}><th scope="row">{r[0]}</th><td>{r[1]}</td></tr>)}</tbody></table><p>Change one control and predict again. Explain the result in your notes using both the algebra and the diagram. The exact table supplies the same values without requiring visual interpretation.</p></div>}</>;
}
export function RefresherComplexLab({activity}:{activity:Activity}){
 const [a,setA]=useState(activity.mode==="conjugate"?"3":"2"),[b,setB]=useState(activity.mode==="conjugate"?"2":"1"),[c,setC]=useState("1"),[d,setD]=useState(activity.mode==="conjugate"?"-1":"-2"),[operation,setOperation]=useState("add"),[radius,setRadius]=useState("2"),[angle,setAngle]=useState("150"),[order,setOrder]=useState("3"),[sign,setSign]=useState("positive");
 const values=[-4,-3,-2,-1,0,1,2,3,4];let model:ComplexModel|undefined,error="";
 try{model=activity.mode==="arithmetic"?rectangularInvestigation(Number(a),Number(b),Number(c),Number(d),operation as "add"|"subtract"|"multiply"):activity.mode==="conjugate"?conjugateInvestigation(Number(a),Number(b),Number(c),Number(d)):activity.mode==="polar"?polarInvestigation(Number(radius),Number(angle)):rootsInvestigation(Number(radius),Number(order),sign==="negative");}catch(e){error=e instanceof Error?e.message:"Check the complex-number inputs.";}
 return <><p>{activity.prompt}</p><p className="muted">These predictions are assisted exploration. Independent checkpoints provide objective evidence. Changing a control clears the prediction. Use i in exact answer fields.</p>
 {activity.mode==="arithmetic"||activity.mode==="conjugate"?<><Select label={activity.mode==="conjugate"?"Numerator real part":"First real part"} value={a} onChange={setA} options={values}/><Select label={activity.mode==="conjugate"?"Numerator imaginary part":"First imaginary part"} value={b} onChange={setB} options={values}/><Select label={activity.mode==="conjugate"?"Denominator real part":"Second real part"} value={c} onChange={setC} options={values}/><Select label={activity.mode==="conjugate"?"Denominator imaginary part":"Second imaginary part"} value={d} onChange={setD} options={values}/>{activity.mode==="arithmetic"&&<Select label="Complex operation" value={operation} onChange={setOperation} options={["add","subtract","multiply"]}/>}</>:<><Select label={activity.mode==="polar"?"Polar radius":"Root radius"} value={radius} onChange={setRadius} options={[0,1,2,3,4]}/>{activity.mode==="polar"?<Select label="Displayed angle in degrees" value={angle} onChange={setAngle} options={[-540,-180,-90,0,30,45,60,90,150,180,270,360,540]}/>:<><Select label="Root order" value={order} onChange={setOrder} options={[2,3,4]}/><Select label="Real target sign" value={sign} onChange={setSign} options={["positive","negative"]}/></>}</>}
 {error?<p role="alert" className="notice warning">{error}</p>:model&&<Prediction key={[activity.mode,a,b,c,d,operation,radius,angle,order,sign].join(":")} model={model}/>}</>;
}
