"use client";
import { useId,useState } from "react";
import type { Response } from "@/lib/learning/contracts";
import { gradeQuestion } from "@/lib/learning/grading";
import { limitInvestigation,secantInvestigation,chainInvestigation,accumulationInvestigation,initialInvestigation,type CalculusMode,type CalculusModel } from "@/lib/learning/refreshers/calculus-lab";
import { QuestionFields,QuestionFeedback } from "./question-fields";
type Activity={kind:"refresher-calculus-lab";mode:CalculusMode;prompt:string};
function Select({label,value,options,onChange}:{label:string;value:string;options:number[];onChange:(v:string)=>void}){const id=useId();return <div className="field"><label htmlFor={id}>{label}</label><select id={id} value={value} onChange={e=>onChange(e.target.value)}>{options.map(v=><option key={v} value={v}>{v}</option>)}</select></div>;}
function Plot({model}:{model:CalculusModel}){
 const points=[...model.curves.flatMap(c=>c.points),...model.points??[],[0,0]],xs=points.map(p=>p[0]),ys=points.map(p=>p[1]),xmin=Math.min(...xs),xmax=Math.max(xmin+1,...xs),ymin=Math.min(...ys),ymax=Math.max(ymin+1,...ys),dx=xmax-xmin,dy=ymax-ymin,x=(n:number)=>55+250*(n-xmin)/dx,y=(n:number)=>225-180*(n-ymin)/dy,colors=["#23664f","#8c4a25","#285974"],patterns=[undefined,"8 4","3 3"];
 return <svg viewBox="0 0 360 345" role="img" aria-label="Calculus comparison plot. Solid and dashed lines are identified in the legend. Open circles exclude branch endpoints; filled dots give included point values. The table provides the numerical results." style={{width:"100%",maxWidth:600}}>
 <path d={`M45 ${y(0)}H320M${x(0)} 30V235`} stroke="currentColor" opacity=".35"/><text x="180" y="260" textAnchor="middle" fontSize="12">{model.xLabel}</text><text x="12" y="17" fontSize="12">{model.yLabel}</text><text x="55" y="244" textAnchor="middle" fontSize="11">{Number(xmin.toFixed(2))}</text><text x="305" y="244" textAnchor="middle" fontSize="11">{Number(xmax.toFixed(2))}</text><text x="48" y="228" textAnchor="end" fontSize="11">{Number(ymin.toFixed(2))}</text><text x="48" y="48" textAnchor="end" fontSize="11">{Number(ymax.toFixed(2))}</text>
 {model.curves.map((c,i)=>{const path=c.points.map((p,j)=>`${j?"L":"M"}${x(p[0])} ${y(p[1])}`).join(" "),first=c.points[0],last=c.points.at(-1)!;return <g key={c.label}>{c.area&&<path d={`${path}L${x(last[0])} ${y(0)}L${x(first[0])} ${y(0)}Z`} fill={colors[i%3]} opacity=".16"/>}<path d={path} fill="none" stroke={colors[i%3]} strokeWidth="2.4" strokeDasharray={patterns[i%3]}/>{c.openStart&&<circle cx={x(first[0])} cy={y(first[1])} r="5" fill="white" stroke={colors[i%3]} strokeWidth="2"/>}{c.openEnd&&<circle cx={x(last[0])} cy={y(last[1])} r="5" fill="white" stroke={colors[i%3]} strokeWidth="2"/>}<path d={`M40 ${280+i*20}H75`} stroke={colors[i%3]} strokeWidth="2.4" strokeDasharray={patterns[i%3]}/><text x="85" y={284+i*20} fontSize="12">{c.label}</text></g>;})}
 {model.points?.map((p,i)=><circle key={i} cx={x(p[0])} cy={y(p[1])} r="4" fill="currentColor"/>)}</svg>;
}
function Prediction({model}:{model:CalculusModel}){
 const [response,setResponse]=useState<Response>({}),[checked,setChecked]=useState(false),valid=checked&&gradeQuestion(model.question,response).valid;
 return <><p>{model.question.prompt}</p><QuestionFields question={model.question} response={response} onChange={r=>{setResponse(r);setChecked(false);}}/><div className="form-actions"><button className="button" onClick={()=>setChecked(true)}>Check prediction</button><button className="button secondary" onClick={()=>{setResponse({});setChecked(false);}}>Retry prediction</button></div>{checked&&<div role="status" className="section-space"><QuestionFeedback question={model.question} response={response}/></div>}{valid&&<div className="section-space"><Plot model={model}/><table className="coefficient-table"><caption>{model.caption}</caption><thead><tr><th scope="col">Quantity</th><th scope="col">Value</th></tr></thead><tbody>{model.rows.map((r,i)=><tr key={i}><th scope="row">{r[0]}</th><td>{r[1]}</td></tr>)}</tbody></table><p>Change one control, predict again, and explain the result in your notes. The table gives the values independently of the diagram. The two axes may use different numerical scales.</p></div>}</>;
}
export function RefresherCalculusLab({activity}:{activity:Activity}){
 const [a,setA]=useState(activity.mode==="chain"||activity.mode==="initial"?"2":activity.mode==="accumulation"?"3":"1"),[b,setB]=useState(activity.mode==="limit"?"2":activity.mode==="accumulation"?"-2":activity.mode==="secant"?"0":"1"),[c,setC]=useState(activity.mode==="limit"?"2":"2"),[d,setD]=useState(activity.mode==="limit"?"4":"3"),[x,setX]=useState(activity.mode==="limit"?"0":"1"),[h,setH]=useState("0.5"),[n,setN]=useState("2");
 let model:CalculusModel|undefined,error="";const small=[-3,-2,-1,0,1,2,3,4],select=(label:string,value:string,onChange:(s:string)=>void,options=small)=><Select label={label} value={value} onChange={onChange} options={options}/>;
 try{model=activity.mode==="limit"?limitInvestigation(Number(x),Number(b),Number(c),Number(d)):activity.mode==="secant"?secantInvestigation(Number(a),Number(b),Number(x),Number(h)):activity.mode==="chain"?chainInvestigation(Number(a),Number(b),Number(n),Number(x)):activity.mode==="accumulation"?accumulationInvestigation(Number(a),Number(b),Number(c),Number(d)):initialInvestigation(Number(a),Number(b),Number(x),Number(d));}catch(e){error=e instanceof Error?e.message:"Check the activity inputs.";}
 return <><p>{activity.prompt}</p><p className="muted">These predictions are assisted exploration. Independent checkpoints provide objective evidence. Changing a control clears the prediction.</p>
 {activity.mode==="limit"?<>{select("Junction input",x,setX)}{select("Left approach value",b,setB)}{select("Right approach value",c,setC)}{select("Assigned point value",d,setD)}</>:activity.mode==="accumulation"?<>{select("First velocity in metres per second",a,setA)}{select("Second velocity in metres per second",b,setB)}{select("First duration in seconds",c,setC,[1,2,3,4])}{select("Second duration in seconds",d,setD,[1,2,3,4])}</>:<>{select(activity.mode==="chain"?"Inner slope":activity.mode==="initial"?"Derivative slope":"Quadratic coefficient",a,setA)}{select(activity.mode==="chain"?"Inner intercept":activity.mode==="initial"?"Derivative intercept":"Linear coefficient",b,setB)}{select(activity.mode==="initial"?"Initial input":"Evaluation input",x,setX)}{activity.mode==="secant"&&select("Increment h",h,setH,[-1,-.5,-.1,0,.1,.5,1])}{activity.mode==="chain"&&select("Outer power",n,setN,[2,3,4])}{activity.mode==="initial"&&select("Initial function value",d,setD)}</>}
 {error?<p role="alert" className="notice warning">{error}</p>:model&&<Prediction key={[activity.mode,a,b,c,d,x,h,n].join(":")} model={model}/>}</>;
}
