"use client";
import { useId, useState } from "react";
import type { Response } from "@/lib/learning/contracts";
import { gradeQuestion } from "@/lib/learning/grading";
import { prefixes } from "@/lib/learning/refreshers/measurement";
import { prefixInvestigation, conversionInvestigation, dimensionInvestigation, roundingInvestigation, measurementInvestigation, type MeasurementMode, type MeasurementModel } from "@/lib/learning/refreshers/measurement-lab";
import { QuestionFields, QuestionFeedback } from "./question-fields";
type Activity={kind:"refresher-measurement-lab";mode:MeasurementMode;prompt:string};
function Select({label,value,options,onChange}:{label:string;value:string;options:(string|number|{value:number;label:string})[];onChange:(v:string)=>void}){
 const id=useId();return <div className="field"><label htmlFor={id}>{label}</label><select id={id} value={value} onChange={e=>onChange(e.target.value)}>{options.map(o=>typeof o==="object"?<option key={o.value} value={o.value}>{o.label}</option>:<option key={o} value={o}>{o}</option>)}</select></div>;
}
function Input({label,value,onChange}:{label:string;value:string;onChange:(v:string)=>void}){const id=useId();return <div className="field"><label htmlFor={id}>{label}</label><input id={id} value={value} onChange={e=>onChange(e.target.value)} inputMode="decimal"/></div>;}
function Prediction({model}:{model:MeasurementModel}){
 const [response,setResponse]=useState<Response>({}),[checked,setChecked]=useState(false),valid=checked&&gradeQuestion(model.question,response).valid,s=model.scale;
 const low=s?Math.min(s.lower,s.reference):0,high=s?Math.max(s.upper,s.reference):1,pad=Math.max((high-low)*.15,.001),x=(n:number)=>35+260*(n-low+pad)/(high-low+2*pad);
 return <><p>{model.question.prompt}</p><QuestionFields question={model.question} response={response} onChange={r=>{setResponse(r);setChecked(false);}}/><div className="form-actions"><button className="button" onClick={()=>setChecked(true)}>Check prediction</button><button className="button secondary" onClick={()=>{setResponse({});setChecked(false);}}>Retry prediction</button></div>{checked&&<div role="status" className="section-space"><QuestionFeedback question={model.question} response={response}/></div>}{valid&&<div className="section-space">{s&&<svg viewBox="0 0 330 140" role="img" aria-label="Stated bound interval with closed circular endpoints and a triangular reference marker; exact values are in the table" style={{width:"100%",maxWidth:550}}><path d="M30 70H300" stroke="currentColor" opacity=".4"/><path d={`M${x(s.lower)} 70H${x(s.upper)}`} stroke="#23664f" strokeWidth="5"/>{[s.lower,s.upper].map((v,i)=><circle key={i} cx={x(v)} cy={70} r="5" fill="#23664f"/>)}<path d={`M${x(s.reference)} 80l-6 12h12Z`} fill="#8c4a25"/><text x="30" y="35">Closed bounds (V)</text><text x="30" y="120">Triangle: stated reference</text></svg>}<table className="coefficient-table"><caption>{model.caption}</caption><thead><tr><th scope="col">Quantity</th><th scope="col">Value</th></tr></thead><tbody>{model.rows.map((row,i)=><tr key={i}><th scope="row">{row[0]}</th><td>{row[1]}</td></tr>)}</tbody></table><p>Change one control. Explain which value changes, which physical quantity or rule stays the same, and why. Record the explanation in your lesson notes.</p></div>}</>;
}
export function RefresherMeasurementLab({activity}:{activity:Activity}){
 const [value,setValue]=useState(activity.mode==="rounding"?"9.9995":activity.mode==="measurement"?"1.20":"2.5"),[from,setFrom]=useState("-3"),[to,setTo]=useState("0"),[power,setPower]=useState("2"),[p,setP]=useState("1"),[t,setT]=useState("1"),[c,setC]=useState("2"),[roundMode,setRoundMode]=useState("figures"),[digits,setDigits]=useState("4"),[resolution,setResolution]=useState("0.01"),[extra,setExtra]=useState("0.02"),[reference,setReference]=useState("1.225");
 let model:MeasurementModel|undefined,error="";
 try{model=activity.mode==="prefix"?prefixInvestigation(value,Number(from),Number(to)):activity.mode==="conversion"?conversionInvestigation(value,Number(from),Number(to),Number(power)):activity.mode==="dimensions"?dimensionInvestigation(Number(p),Number(t),Number(c)):activity.mode==="rounding"?roundingInvestigation(value,roundMode as "places"|"figures",Number(digits)):measurementInvestigation(value,resolution,extra,reference);}catch(e){error=e instanceof Error?e.message:"Enter a valid value.";}
 const prefixOptions=prefixes.map(p=>({value:p.exponent,label:`${p.name} (${p.symbol||"unit"}), 10^${p.exponent}`})),lengthOptions=prefixOptions.filter(p=>[-3,-2,0].includes(p.value));
 return <><p>{activity.prompt}</p><p className="muted">This is assisted exploration. Use the independent checkpoint for objective evidence. Changing a control clears the prediction.</p>{activity.mode!=="dimensions"&&<Input label={activity.mode==="measurement"?"Displayed voltage":activity.mode==="rounding"?"Original decimal report":"Original numerical value"} value={value} onChange={setValue}/>}
 {(activity.mode==="prefix"||activity.mode==="conversion")&&<><Select label="Source prefix" value={from} options={activity.mode==="prefix"?prefixOptions:lengthOptions} onChange={setFrom}/><Select label="Target prefix" value={to} options={activity.mode==="prefix"?prefixOptions:lengthOptions} onChange={setTo}/>{activity.mode==="conversion"&&<Select label="Power of the length unit" value={power} options={[-1,1,2,3]} onChange={setPower}/>}</>}
 {activity.mode==="dimensions"&&<><Select label="Power of velocity" value={p} options={[-1,0,1,2]} onChange={setP}/><Select label="Power of time" value={t} options={[-1,0,1,2]} onChange={setT}/><Select label="Dimensionless coefficient" value={c} options={[1,2,5]} onChange={setC}/></>}
 {activity.mode==="rounding"&&<><Select label="Rounding rule" value={roundMode} options={["figures","places"]} onChange={setRoundMode}/><Select label="Number of figures or places" value={digits} options={[1,2,3,4]} onChange={setDigits}/><p className="muted">Use a finite decimal report. The stated tie rule is nearest, with exact ties away from zero.</p></>}
 {activity.mode==="measurement"&&<><Select label="Display resolution in volts" value={resolution} options={["0.01","0.1","1"]} onChange={setResolution}/><Select label="Additional stated bound in volts" value={extra} options={["0","0.02","0.1"]} onChange={setExtra}/><Input label="Reference voltage" value={reference} onChange={setReference}/></>}
 {error?<p role="alert" className="notice warning">{error}</p>:model&&<Prediction key={[activity.mode,value,from,to,power,p,t,c,roundMode,digits,resolution,extra,reference].join(":")} model={model}/>}</>;
}
