"use client";
import { useId,useState } from "react";
import type { Response } from "@/lib/learning/contracts";
import { gradeQuestion } from "@/lib/learning/grading";
import { stateTrace,loopTrace,functionTrace,debugTrace,type ProgrammingMode,type ProgrammingModel,type SumBug,type SumRepair } from "@/lib/learning/refreshers/programming-lab";
import { QuestionFields,QuestionFeedback } from "./question-fields";
import { MathText } from "./math-text";
type Activity={kind:"refresher-programming-lab";mode:ProgrammingMode;prompt:string};
function Select({label,value,options,onChange}:{label:string;value:string;options:(number|string)[];onChange:(v:string)=>void}){const id=useId();return <div className="field"><label htmlFor={id}>{label}</label><select id={id} value={value} onChange={e=>onChange(e.target.value)}>{options.map(v=><option key={v} value={v}>{v}</option>)}</select></div>;}
function Prediction({model}:{model:ProgrammingModel}){
 const [response,setResponse]=useState<Response>({}),[checked,setChecked]=useState(false),[step,setStep]=useState(0),valid=checked&&gradeQuestion(model.question,response).valid;
 return <><p><MathText>{model.question.prompt}</MathText></p>{model.tests&&<p>Boundary cases and expected sums: {model.tests.map(t=>t.input+" → "+t.expected).join("; ")}.</p>}<QuestionFields question={model.question} response={response} onChange={r=>{setResponse(r);setChecked(false);setStep(0);}}/><div className="form-actions"><button className="button" onClick={()=>setChecked(true)}>Check prediction</button><button className="button secondary" onClick={()=>{setResponse({});setChecked(false);setStep(0);}}>Retry prediction</button></div>{checked&&<div role="status" className="section-space"><QuestionFeedback question={model.question} response={response}/></div>}{valid&&<div className="section-space"><h3>Trace one step at a time</h3><p aria-live="polite">Step {step+1} of {model.steps.length}: {model.steps[step].statement}. State: {model.steps[step].state}. {model.steps[step].reason}</p><div className="form-actions"><button className="button" disabled={step===model.steps.length-1} onClick={()=>setStep(s=>s+1)}>Next trace step</button><button className="button secondary" onClick={()=>setStep(0)}>Restart trace</button></div><div className="calibration-table-wrap" role="region" aria-label="Program trace table" tabIndex={0}><table className="coefficient-table"><caption>Executed statements and state</caption><thead><tr><th scope="col">Step</th><th scope="col">Statement</th><th scope="col">State and reason</th></tr></thead><tbody>{model.steps.slice(0,step+1).map((s,i)=><tr key={i}><th scope="row">{i+1}</th><td><code>{s.statement}</code></td><td>{s.state}<br/>{s.reason}</td></tr>)}</tbody></table></div>{step===model.steps.length-1&&model.tests&&<div className="calibration-table-wrap" role="region" aria-label="Boundary test results" tabIndex={0}><table className="coefficient-table"><caption>Regression results for the selected repair</caption><thead><tr><th scope="col">Input</th><th scope="col">Expected</th><th scope="col">Actual</th><th scope="col">Result</th></tr></thead><tbody>{model.tests.map(t=><tr key={t.input}><th scope="row"><code>{t.input}</code></th><td>{t.expected}</td><td>{t.actual}</td><td>{t.passed?"Pass":"Fail"}</td></tr>)}</tbody></table><p>Passing these cases is evidence, not proof for every possible input.</p></div>}<p>Explain the first state that changed your prediction in your lesson notes. Change a control and predict before tracing again.</p></div>}</>;
}
export function RefresherProgrammingLab({activity}:{activity:Activity}){
 const [input,setInput]=useState("2"),[threshold,setThreshold]=useState("2"),[list,setList]=useState("mixed"),[copy,setCopy]=useState("alias"),[increment,setIncrement]=useState("3"),[bug,setBug]=useState<SumBug>("offbyone"),[repair,setRepair]=useState<SumRepair>("unchanged");
 const lists:Record<string,number[]>={mixed:[-2,2,4],empty:[],singleton:[2],repeated:[1,-1,3,3]},values=[-2,-1,0,1,2,3,4,5];
 const model=activity.mode==="state"?stateTrace(+input,+threshold):activity.mode==="loop"?loopTrace(lists[list],+threshold):activity.mode==="function"?functionTrace(+input,+increment,copy==="copy"):debugTrace(bug,repair);
 return <><p>{activity.prompt}</p><p className="muted">These are bounded Python 3 traces of the displayed programs. Predictions and revealed steps are assisted exploration. Independent checkpoints provide objective evidence. Changing a control clears the prediction.</p>
 {activity.mode==="state"?<><Select label="Initial x" value={input} onChange={setInput} options={values}/><Select label="Decision threshold" value={threshold} onChange={setThreshold} options={values}/></>:activity.mode==="loop"?<><Select label="List case" value={list} onChange={setList} options={Object.keys(lists)}/><p>Selected list: [{lists[list].join(", ")}]</p><Select label="Inclusive threshold" value={threshold} onChange={setThreshold} options={values}/></>:activity.mode==="function"?<><Select label="Original first element" value={input} onChange={setInput} options={values}/><Select label="Increment" value={increment} onChange={setIncrement} options={values}/><Select label="List handling" value={copy} onChange={setCopy} options={["alias","copy"]}/></>:<><Select label="Fault" value={bug} onChange={v=>setBug(v as SumBug)} options={["offbyone","reset","early"]}/><Select label="Proposed repair" value={repair} onChange={v=>setRepair(v as SumRepair)} options={["unchanged","visit-all","keep-total","return-after"]}/><p>visit-all includes every index; keep-total removes repeated initialization; return-after moves the return beyond traversal.</p></>}
 <Prediction key={[activity.mode,input,threshold,list,copy,increment,bug,repair].join(":")} model={model}/></>;
}
