import { questionSchema, type Question } from "../contracts";
import { randomFrom } from "../random";
import { canonical, combineBounds, decimalNumber, fixedDecimal, percentBound, scaleDecimal, symmetricBounds, withinBounds, type Bounds } from "../refreshers/measurement";
import { composeRefresherQuestion } from "../refreshers/compose-question";
import { f06Identity, measurementField as field } from "./f06-fields";
export const f06UncertaintyFamilyIds=["f06-measurement-read","f06-measurement-quality","f06-measurement-uncertainty","f06-measurement-propagation"];
export const boundsField=(id:string,label:string,bounds:Bounds,unit:string)=>({id,kind:"intervals" as const,label,unit,expected:[{...bounds,lowerClosed:true,upperClosed:true}],help:"Give the complete closed interval. These are stated bounds, with endpoints included."});
export function f06UncertaintyQuestion(familyId:string,variant:string,seed:string,id:string):Question{
  const rng=randomFrom(seed),identity=f06Identity(familyId,id,"m01-l05");
  const choice=(id:string,label:string,correct:string,options:[string,string,string][])=>({id,kind:"choice",label,correct,options:rng.shuffle(options.map(([id,label,feedback])=>({id,label,feedback})))});
  const interpretation=()=>choice("meaning","What does the supplied bound establish?","bound",[
    ["bound","It supplies an interval model; no statistical confidence level has been given","A probability or coverage factor requires additional stated information."],
    ["confidence","It automatically establishes 95% statistical confidence","A plus/minus statement does not specify a probability model or confidence level by itself."],
    ["exact","It proves that the nominal value is the exact true value","A bound describes a range, not exact knowledge of the central value."],
  ]);
  if(familyId==="f06-measurement-read"){
    if(variant==="audit")return composeRefresherQuestion(["analog","digital"].map((v,i)=>f06UncertaintyQuestion(familyId,v,`${seed}:part-${i}`,id)),identity);
    if(!["analog","digital"].includes(variant))throw new Error("Unknown measurement display");
    const origin=rng.integer(0,5),step=rng.shuffle(["1/10","1/5","1/2"])[0],tick=rng.integer(1,7),reading=canonical(`${origin}+(${tick}+1/2)*(${step})`),resolution=variant==="analog"?step:rng.integer(0,1)?"1/100":"1/10",bound=canonical(`(${resolution})/2`),count=rng.integer(10,99),digital=canonical(`${count}*(${resolution})`);
    return questionSchema.parse({...identity,category:"application",parameters:{origin,step:decimalNumber(step),tick,resolution:decimalNumber(resolution),count},
      prompt:variant==="analog"?`A simulated linear scale starts at ${origin} mm and each small division is ${step} mm. The pointer is exactly halfway between the ${tick}th and ${tick+1}th small tick after that origin. Read the nominal position. For this exercise alone use one half of a small division as a conservative reading bound; also state the small-division size.`:`A simulated digital display reads ${fixedDecimal(digital,resolution==="1/100"?2:1)} V and changes in steps of ${fixedDecimal(resolution,resolution==="1/100"?2:1)} V. Under an ideal nearest-step model, give its resolution and the conservative half-step rounding bound. This is only a rounding contribution, not a total instrument uncertainty.`,
      fields:variant==="analog"?[field("reading","Nominal pointer reading",reading,"mm"),field("division","Small-division size",step,"mm"),field("bound","Stated half-division reading bound",bound,"mm")]:[field("resolution","Digital resolution",resolution,"V"),field("bound","Conservative rounding-only bound",bound,"V"),interpretation()],
      hints:["Separate the nominal reading from the scale's smallest indicated step.","A halfway pointer lies at origin plus (tick count + 1/2) times the small-division size.","Use one half of the supplied step only under the stated bound convention; it does not establish bias, calibration, or total uncertainty."],
      explanation:[variant==="analog"?`The nominal reading is ${reading} mm. The small division is ${step} mm, giving the specified half-division bound ${bound} mm.`:`The resolution is ${resolution} V and the half-step rounding bound is ${bound} V.`,"A finer display or smaller scale division alone does not prove a more accurate result.","No statistical confidence level follows from this bound statement."],
      answerSummary:variant==="analog"?`Reading ${reading} mm; division ${step} mm; bound ${bound} mm.`:`Resolution ${resolution} V; rounding-only bound ${bound} V; no confidence level supplied.`});
  }
  if(familyId==="f06-measurement-quality"){
    if(!["repeatability","bias","compare"].includes(variant))throw new Error("Unknown measurement-quality comparison");
    const reference=rng.integer(2,20)*100,offset=rng.integer(10,80)*(rng.integer(0,1)?1:-1),small=rng.integer(1,3),large=rng.integer(5,15),swap=rng.integer(0,1)===1;
    const first={center:reference+(variant==="repeatability"?0:offset),spread:small},second={center:reference,spread:variant==="bias"?small:large},a=swap?second:first,b=swap?first:second;
    const values=(series:typeof a)=>[series.center-series.spread,series.center,series.center+series.spread].map(n=>fixedDecimal(`${n}/100`,2)).join(", ");
    const repeat=choice("repeat","Which series has tighter repeatability in these observations?",a.spread<b.spread?"a":"b",[
      ["a","Series A","Compare the observed ranges rather than the number of digits on the display."],
      ["b","Series B","Compare the observed ranges rather than the distance from the reference."],
    ]);
    const closer=choice("closer","Which sample mean is closer to the stated reference?",a.center===reference?"a":"b",[
      ["a","Series A","Compare each mean's absolute discrepancy from the supplied reference."],
      ["b","Series B","Tight clustering alone does not determine agreement with a reference."],
    ]);
    return questionSchema.parse({...identity,category:"application",parameters:{reference,aCenter:a.center,bCenter:b.center,aSpread:a.spread,bSpread:b.spread},
      prompt:`Three readings in volts are A: ${values(a)}; B: ${values(b)}. The stated reference is ${fixedDecimal(`${reference}/100`,2)} V. ${variant==="repeatability"?"Find each observed range and decide which series is more repeatable.":variant==="bias"?"Find each mean minus the reference and decide which mean is closer.":"Find both means and ranges, then compare repeatability separately from agreement with the reference."} These three readings alone do not establish a complete uncertainty budget.`,
      fields:variant==="repeatability"?[field("range-a","Observed range of A",`${2*a.spread}/100`,"V"),field("range-b","Observed range of B",`${2*b.spread}/100`,"V"),repeat]:variant==="bias"?[field("error-a","Mean A minus reference",`${a.center-reference}/100`,"V"),field("error-b","Mean B minus reference",`${b.center-reference}/100`,"V"),closer]:[field("mean-a","Mean of A",`${a.center}/100`,"V"),field("mean-b","Mean of B",`${b.center}/100`,"V"),field("range-a","Observed range of A",`${2*a.spread}/100`,"V"),field("range-b","Observed range of B",`${2*b.spread}/100`,"V"),repeat,closer],
      hints:["The mean is the sum divided by three; the observed range is maximum minus minimum.","Reference discrepancy is mean minus reference. It is different from the spread of repeated readings.","A tightly clustered series can be offset from the reference. Do not equate repeatability with proof of accuracy."],
      explanation:[`The means are ${a.center/100} V and ${b.center/100} V; the ranges are ${2*a.spread/100} V and ${2*b.spread/100} V.`,`Their signed discrepancies from the reference are ${(a.center-reference)/100} V and ${(b.center-reference)/100} V.`,"These comparisons describe the supplied samples. Resolution, calibration, environmental effects, and other information may contribute to uncertainty beyond their observed scatter."],
      answerSummary:`Means A=${a.center/100} V, B=${b.center/100} V; ranges ${2*a.spread/100}, ${2*b.spread/100} V; mean-reference discrepancies ${(a.center-reference)/100}, ${(b.center-reference)/100} V.`});
  }
  if(familyId==="f06-measurement-uncertainty"){
    if(!["interval","relative","convert","compatible","zero","audit"].includes(variant))throw new Error("Unknown measurement bound structure");
    const n=variant==="zero"?0:rng.integer(5,50)*(rng.integer(0,1)?1:-1),u=rng.integer(1,9),multiple=rng.integer(-2,2),value=canonical(`${n}/2`),uncertainty=canonical(`${u}/100`),bounds=symmetricBounds(value,uncertainty),reference=canonical(`(${value})+${multiple}*(${uncertainty})`),percent=percentBound(value,uncertainty),contains=withinBounds(reference,bounds);
    const relativeZero=()=>choice("zero-relative","Relative percent uncertainty for a separate zero nominal value with a nonzero absolute bound","undefined",[
      ["undefined","Undefined because the nominal magnitude in the denominator is zero","The absolute bound remains meaningful; this particular relative measure cannot divide by zero."],
      ["zero","0%","A nonzero absolute bound has not disappeared because the nominal value is zero."],
      ["hundred","100%","No finite percentage follows from dividing by zero."],
    ]);
    const compatibility=()=>choice("compatible","Is the stated reference within the supplied closed bounds?",contains?"yes":"no",[
      ["yes","Yes, including a possible boundary equality","The model's endpoints are included; compatibility is not proof of an exact central value."],
      ["no","No","Compare the reference with both endpoints of the stated interval."],
    ]);
    return questionSchema.parse({...identity,category:"application",parameters:{n,u,multiple},
      prompt:`A signed nominal voltage offset is ${fixedDecimal(value,2)} V with a stated symmetric bound ±${fixedDecimal(uncertainty,2)} V. Treat this as the closed interval of allowed values in this model, not as a stated confidence interval. ${variant==="relative"?"Find 100 times the bound divided by the absolute nominal value.":variant==="convert"?"Convert both nominal value and bound to mV, then find the percent bound.":variant==="compatible"?`Find the interval and check reference ${fixedDecimal(reference,2)} V.`:variant==="zero"?"Find the absolute interval, then explain the relative percentage for this zero nominal value.":variant==="audit"?`Find the original interval, convert value and bound to mV, find the percent bound, and check reference ${fixedDecimal(reference,2)} V. Also classify the separate zero-nominal case.`:"Find the complete interval and interpret what has been stated."} Keep these model bounds exact.`,
      fields:variant==="relative"?[field("percent","Relative bound as a percentage",percent!,"%")]:variant==="convert"?[field("value","Converted nominal value",scaleDecimal(value,3),"mV"),field("bound","Converted absolute bound",scaleDecimal(uncertainty,3),"mV"),field("percent","Relative bound as a percentage",percent!,"%")]:variant==="compatible"?[boundsField("interval","Allowed voltage interval",bounds,"V"),compatibility()]:variant==="zero"?[boundsField("interval","Allowed voltage interval",bounds,"V"),relativeZero()]:variant==="audit"?[boundsField("interval","Allowed voltage interval",bounds,"V"),field("value","Converted nominal value",scaleDecimal(value,3),"mV"),field("bound","Converted absolute bound",scaleDecimal(uncertainty,3),"mV"),field("percent","Relative bound as a percentage",percent!,"%"),compatibility(),relativeZero(),interpretation()]:[boundsField("interval","Allowed voltage interval",bounds,"V"),interpretation()],
      hints:["Subtract and add the nonnegative bound to obtain the closed endpoints.","Convert both the nominal value and its absolute bound by the same exact scale factor. For a nonzero nominal value, use 100*bound/absolute(nominal).","A zero nominal value has a meaningful absolute interval but no value for this relative percentage. Inclusive endpoint agreement does not prove the measurement exact."],
      explanation:[`The closed interval is [${bounds.lower}, ${bounds.upper}] V.`,...(variant==="convert"||variant==="audit"?[`The converted report has nominal value ${scaleDecimal(value,3)} mV and bound ${scaleDecimal(uncertainty,3)} mV.`]:[]),percent===null?"The requested relative percentage is undefined because its denominator is zero.":`The relative bound is ${percent}%, unchanged by consistent conversion of both quantities.`,...(variant==="compatible"||variant==="audit"?[`The reference ${reference} V is ${contains?"inside":"outside"} the stated closed interval.`]:[]),"The supplied bounds carry no unstated statistical confidence level."],
      answerSummary:`Interval [${bounds.lower}, ${bounds.upper}] V; ${percent===null?"relative percentage undefined":`relative bound ${percent}%`}.${variant==="compatible"||variant==="audit"?` Reference compatibility: ${contains?"yes":"no"}.`:""}`});
  }
  if(familyId==="f06-measurement-propagation"){
    if(variant==="audit")return composeRefresherQuestion(["difference","product","quotient"].map((v,i)=>f06UncertaintyQuestion(familyId,v,`${seed}:part-${i}`,id)),identity);
    if(!["sum","difference","scale","product","quotient"].includes(variant))throw new Error("Unknown propagated bound structure");
    const a=rng.integer(2,15),b=rng.integer(1,9),u=rng.integer(1,5),v=rng.integer(1,4),scale=rng.integer(2,5)*(rng.integer(0,1)?1:-1),first=symmetricBounds(String(a),`${u}/10`),second=variant==="scale"?{lower:String(scale),upper:String(scale)}:symmetricBounds(String(b),`${v}/10`);
    const bounds=combineBounds(first,second,variant==="scale"?"product":variant as "sum"|"difference"|"product"|"quotient"),operation=variant==="sum"?"+":variant==="difference"?"-":variant==="quotient"?"/":"*",nominal=canonical(`${a}${operation}${variant==="scale"?scale:b}`),unit=variant==="product"?"m^2":variant==="quotient"?"m/s":"V";
    return questionSchema.parse({...identity,category:"application",parameters:{a,b,u,v,scale},
      prompt:variant==="scale"?`A voltage is nominally ${a}.0 V with stated bound ±${u/10} V. Multiply it by the exact signed factor ${scale}. Give the nominal result and the full closed interval of possible outputs. Keep the stated model bounds exact.`:`Two positive inputs have nominal values ${a}.0 and ${b}.0, with stated bounds ±${u/10} and ±${v/10}. ${variant==="product"?"Both are lengths in metres; find their product's nominal area and bounds.":variant==="quotient"?"The first is length in metres and the second time in seconds; find their quotient's nominal speed and bounds.":`Both are voltages; find the ${variant==="sum"?"sum":"first minus second"} and its bounds.`} Each input may vary independently anywhere within its supplied closed interval. Keep exact endpoints; no statistical probability model is assumed.`,
      fields:[field("nominal","Nominal result",nominal,unit),boundsField("interval","Complete output bounds",bounds,unit)],
      hints:["Use the nominal input values for the nominal result, and endpoints for the extreme outputs.",variant==="sum"?"Add lower endpoints for the minimum and upper endpoints for the maximum.":variant==="difference"?"The smallest difference subtracts the largest second input; the largest subtracts the smallest.":variant==="quotient"?"Both denominator endpoints are positive. The minimum divides the smallest numerator by the largest denominator.":variant==="scale"?"A negative exact factor reverses endpoint order. The bound's width cannot become negative.":"For positive independent inputs, multiply the two lower endpoints for the minimum and the two upper endpoints for the maximum.",`The output interval is [${bounds.lower}, ${bounds.upper}] ${unit}.`],
      explanation:[`The nominal result is ${nominal} ${unit}.`,`Endpoint evaluation gives the complete bound interval [${bounds.lower}, ${bounds.upper}] ${unit}.`,"Products and quotients need not have equal deviations above and below the nominal value. These exact interval bounds are different from a standard-uncertainty propagation calculation."],
      answerSummary:`Nominal ${nominal} ${unit}; bounds [${bounds.lower}, ${bounds.upper}] ${unit}.`});
  }
  throw new Error("Unknown F06 uncertainty family");
}
