import { randomFrom } from "../random";
import type { Question } from "../contracts";
import { directionDegrees,dot,normSquared } from "../refreshers/vectors";
import { standardDegrees,trigValue } from "../refreshers/trig";
import { composeRefresherQuestion } from "../refreshers/compose-question";
import { f07Identity,vc,ve,vn,vr,vectorFields,vectorText,vq } from "./f07-fields";
export const f07GeometryFamilyIds=["f07-vector-line","f07-vector-plane","f07-cylindrical","f07-spherical"];
const membership=(yes:boolean)=>vc("member","Does the candidate lie on the stated object?",yes?"yes":"no",[["yes","Yes","Every defining equation must be satisfied."],["no","No","One incompatible coordinate or nonzero plane residual is enough to reject membership."]]);
export function f07GeometryQuestion(family:string,variant:string,seed:string,id:string):Question{
 const rng=randomFrom(seed),p=Array.from({length:3},()=>rng.integer(-5,5)),d=[rng.integer(1,5),rng.integer(-4,4),rng.integer(-4,4)],t=rng.integer(-3,3),s=rng.integer(-2,3),match=rng.integer(0,1)===1;
 if(family==="f07-vector-line"&&["point","membership","segment","audit"].includes(variant)){
  const point=p.map((x,i)=>x+t*d[i]),candidate=p.map((x,i)=>x+s*d[i]+(!match&&i===2?1:0));
  const segment=vc("segment","Parameter interval for the closed segment from p to p+d","closed",[["closed","0 <= t <= 1","The endpoints occur at t=0 and t=1; values between them trace the segment."],["all","All real t","That describes the complete line."],["positive","t >= 0","That describes a ray, which extends beyond the second endpoint."]]);
  const fields=variant==="point"?vectorFields(point,"m"):variant==="membership"?[vr("parameter","Candidate parameter implied by x",String(s)),membership(match)]:variant==="segment"?[segment,...vectorFields(p.map((x,i)=>x+d[i]),"m")]:[...vectorFields(point,"m"),vr("parameter","Candidate parameter implied by x",String(s)),membership(match),segment];
  return vq(family,id,"m01-l05",`A line has vector equation r(t)=p+t d with p=${vectorText(p)} m, d=${vectorText(d)} m, and dimensionless parameter t. ${variant==="point"?`Find its point at t=${t}.`:variant==="membership"?`Test candidate ${vectorText(candidate)} m using one shared parameter.`:variant==="segment"?"Give the parameter interval for the closed segment from p to p+d and the coordinates of its second endpoint.":`Find the point at t=${t}; separately test candidate ${vectorText(candidate)} m using one shared parameter, and identify the closed segment from p to p+d.`}`,fields,{...Object.fromEntries(p.map((x,i)=>["p"+i,x])),...Object.fromEntries(d.map((x,i)=>["d"+i,x])),t,s,match:match?1:0},["A single parameter value must satisfy all three line coordinates.","The nonzero x direction component lets you solve t from x; substitute it into y and z too.","The full line permits every real parameter; a closed segment between p and p+d uses [0,1]."],[`At t=${t}, the point is ${vectorText(point)} m.`,`The candidate's x coordinate implies t=${s}; ${match?"all coordinates agree":"its z coordinate disagrees"}, so membership is ${match?"yes":"no"}.`,"The closed segment uses 0 <= t <= 1."]);
 }
 if(family==="f07-vector-plane"&&["constant","membership","distance","audit"].includes(variant)){
  const constant=dot(d,p),candidate=[p[0]-t*d[1]+(match?0:1),p[1]+t*d[0],p[2]],residual=dot(d,candidate)-constant,square=normSquared(d),distance=`${Math.abs(residual)}/sqrt(${square})`;
  const constantField=vr("constant","Constant c in n dot r = c",String(constant),"m"),residualField=vr("residual","Signed residual n dot candidate minus c",String(residual),"m"),distanceField=ve("distance","Perpendicular point-plane distance",distance,"m");
  const fields=variant==="constant"?[constantField]:variant==="membership"?[residualField,membership(match)]:variant==="distance"?[distanceField]:[constantField,residualField,membership(match),distanceField];
  return vq(family,id,"m01-l05",`A plane passes through p=${vectorText(p)} m with nonzero dimensionless normal n=${vectorText(d)} in an orthonormal Cartesian frame. ${variant==="constant"?"Find c in n dot r = c.":`${variant==="audit"?"":`The plane constant is c=${constant} m. `}For candidate point ${vectorText(candidate)} m, ${variant==="distance"?"find its perpendicular distance to the plane":variant==="membership"?"find the signed residual and test membership":"recover c, compute the signed residual, test membership, and find perpendicular distance"}.`}`,fields,{...Object.fromEntries(p.map((x,i)=>["p"+i,x])),...Object.fromEntries(d.map((x,i)=>["n"+i,x])),...Object.fromEntries(candidate.map((x,i)=>["q"+i,x])),constant},["Use n dot (r-p)=0, so the constant is n dot p.","Substitute the candidate into n dot r - c; membership requires a zero residual.","Distance is the absolute residual divided by the normal's magnitude, not just the residual."],[`The plane constant is ${constant} m and the candidate residual is ${residual} m.`,`The candidate ${match?"lies on":"does not lie on"} the plane; its perpendicular distance is ${distance} m.`]);
 }
 if(family==="f07-cylindrical"&&["to-cartesian","from-cartesian"].includes(variant)){
  const radius=rng.integer(1,8),angle=rng.shuffle(standardDegrees)[0],z=rng.integer(-6,6);
  if(variant==="to-cartesian"){
   const values=[`${radius}*(${trigValue("cos",angle)})`,`${radius}*(${trigValue("sin",angle)})`,String(z)];
   return vq(family,id,"m01-l05",`Cylindrical coordinates are (r,theta,z)=(${radius} m, ${angle} degrees, ${z} m). Here r is distance from the z-axis and theta is counterclockwise azimuth from +x toward +y. Find exact Cartesian coordinates.`,values.map((x,i)=>ve(["x","y","z"][i],`Cartesian ${["x","y","z"][i]} coordinate`,x,"m")),{radius,angle,z},["Project onto the xy plane first.","Use x=r cos(theta), y=r sin(theta); the height z stays unchanged.","Check the angle quadrant and x²+y²=r²."],[`The Cartesian coordinates are ${vectorText(values)} m.`,"Cylindrical radius measures distance from the z-axis, not distance from the origin."]);
  }
  const x=rng.integer(-5,5),y=x===0?rng.integer(1,5):rng.integer(-5,5),theta=directionDegrees([x,y])!;
  return vq(family,id,"m01-l05",`Convert Cartesian point (${x}, ${y}, ${z}) m to cylindrical (r,theta,z), with r>=0 and 0<=theta<360 degrees measured from +x toward +y.`,[ve("radius","Cylindrical radius",`sqrt(${x*x+y*y})`,"m"),vn("angle","Azimuth",theta,"degrees"),vr("height","Height",String(z),"m")],{x,y,z},["The cylindrical radius uses only x and y.","Choose azimuth using both coordinate signs, including axis cases.","The cylindrical height is the original Cartesian z coordinate."],[`The radius is sqrt(${x*x+y*y}) m, azimuth ${theta.toFixed(6)} degrees, and height ${z} m.`]);
 }
 if(family==="f07-spherical"){
  if(variant==="audit")return composeRefresherQuestion(["to-cartesian","axis"].map((v,i)=>f07GeometryQuestion(family,v,seed+":part-"+i,id)),f07Identity(family,id,"m01-l05"));
  if(variant==="to-cartesian"){
   const radius=rng.integer(1,10),angle=rng.shuffle(standardDegrees)[0],inclination=rng.shuffle([0,30,45,60,90,120,135,150,180])[0],values=[`${radius}*(${trigValue("sin",inclination)})*(${trigValue("cos",angle)})`,`${radius}*(${trigValue("sin",inclination)})*(${trigValue("sin",angle)})`,`${radius}*(${trigValue("cos",inclination)})`];
   return vq(family,id,"m01-l05",`Use spherical (rho,theta,phi)=(${radius} m, ${angle} degrees, ${inclination} degrees). Rho is distance from the origin, theta is azimuth from +x toward +y, and phi is inclination from +z. Find exact Cartesian coordinates under this convention.`,values.map((x,i)=>ve(["x","y","z"][i],`Cartesian ${["x","y","z"][i]} coordinate`,x,"m")),{radius,angle,inclination},["Read the convention: phi is measured from +z, not up from the xy plane.","The horizontal projected radius is rho sin(phi); z=rho cos(phi).","Resolve that horizontal radius with x=rho sin(phi) cos(theta), y=rho sin(phi) sin(theta)."],[`The Cartesian point is ${vectorText(values)} m.`,"Different texts may assign angle names differently; the definitions determine the formulas."]);
  }
  if(variant==="axis"){
   const z=rng.integer(-8,8),origin=z===0;
   return vq(family,id,"m01-l05",`A point is (0,0,${z}) m. In spherical coordinates rho is distance from the origin, theta is azimuth around z, and phi is inclination from +z. State rho and whether the angles are uniquely determined; allow 0<=theta<360 and 0<=phi<=180 degrees.`,[vr("radius","Spherical radius",String(Math.abs(z)),"m"),vc("azimuth","Azimuth theta","nonunique",[["nonunique","Not uniquely determined at this point","There is no nonzero projection in the xy plane from which to measure azimuth."],["unique","Uniquely zero","Zero is one optional convention, not a unique angle forced by the point."]]),origin?vc("inclination","Inclination phi at the origin","nonunique",[["nonunique","Not uniquely determined","At radius zero every inclination gives the same point."],["unique","Uniquely zero","A chosen coordinate convention does not make this geometric direction unique."]]):vr("inclination","Inclination from +z",z>0?"0":"180","degrees")],{z},["Compute the distance from the origin.","On the z-axis, rotating azimuth leaves the Cartesian point unchanged.","Away from the origin the sign of z determines inclination 0 or 180 degrees; at the origin no direction is unique."],[`Rho is ${Math.abs(z)} m. Azimuth is not unique. ${origin?"Inclination is also not unique at the origin.":`Inclination is ${z>0?0:180} degrees.`}`]);
  }
 }
 throw Error("Unknown F07 geometry structure");
}
