import { randomFrom } from "../random";
import { choice,num,truth,programQuestion,type ProgramCase } from "../refreshers/programming";
export const f10DebugFamilyIds=["f10-debug","f10-testing"];
export function f10DebugCase(family:string,variant:string,seed:string):ProgramCase{
 const r=randomFrom(seed),a=r.integer(1,6),b=r.integer(-4,5),c=r.integer(1,6),t=r.integer(-3,7),kind=variant==="classify-syntax"?0:variant==="classify-runtime"?1:variant==="classify-logic"?2:r.integer(0,2),p={a,b,c,t,kind},items=[a,b,c],sum=a+b+c;
 const make=(intro:string,code:string,fields:ProgramCase["fields"],checks:Record<string,string>,explanation:string[]):ProgramCase=>({intro,code,fields,checks,explanation,parameters:p});
 if(family==="f10-testing"){
  if(variant==="float"){
   const x=a/10,y=(a+1)/10,target=(2*a+1)/10;
   return make("For these approximate decimal computations, use the stated absolute tolerance 1e-12. Compare exact equality with a tolerance check.",`computed = ${x} + ${y}\nexpected = ${target}\nexact = computed == expected\nwithin = abs(computed - expected) <= 1e-12`,[truth("exact","Value of exact",x+y===target),truth("within","Value of within",Math.abs(x+y-target)<=1e-12),choice("rule","What justifies the tolerance?","context",[["context","The required accuracy and the computation's scale","A tolerance must come from the problem, not a universal magic number."],["always","Use 1e-12 for every physical quantity","Different units, scales and error requirements need different tolerances."],["proof","Passing this check proves the whole program correct","It checks this numerical comparison only."]])],{exact:"'true' if exact else 'false'",within:"'true' if within else 'false'"},["Many decimal fractions have approximate binary representations; exact equality may or may not happen for a particular expression.","This example explicitly uses an absolute tolerance of 1e-12. Passing this check does not prove general program correctness."]);
  }
  if(variant!=="matrix")throw Error("Unknown testing variant");
  return make("The specification accepts values at or above the threshold. Find the boundary that exposes the wrong comparison, then choose a sum-function regression strategy.",`threshold = ${t}\ndef accepts(value):\n    return value > threshold`,[num("boundary","Equality-boundary counterexample",t),num("empty","Expected sum of an empty list",0),choice("suite","Useful tests for a repaired integer-list sum","broad",[["broad","Empty, singleton, mixed signs, repeated values and ordinary lists","These probe distinct behaviors and likely failure boundaries."],["positive","One list with several positive values","It does not exercise empty input or cancellation."],["large","Only one very long list","Size alone does not cover the boundary classes."]]),choice("proof","Do finite passing examples prove correctness for every possible input?","no",[["no","No","They provide evidence and catch regressions; broader reasoning is still needed."],["yes","Yes","Untested inputs may reveal additional failures."]])],{boundary:"threshold",empty:"sum([])"},[`At value=${t}, the specification says True but the program returns False.`,"Keep the failing boundary as a regression test and add representative cases, including the empty list."]);
 }
 if(family!=="f10-debug")throw Error("Unknown debug family");
 if(["classify","classify-syntax","classify-runtime","classify-logic"].includes(variant)){
  const codes=[`if ${a} > 0\n    value = 1`,`items = [${a}, ${b}]\nvalue = items[2]`,`items = [${a}, ${b}, ${c}]\ntotal = 0\nfor value in items:\n    total = value`],correct=["syntax","runtime","logic"][kind];
  const out=make("The intended task is a valid program that sums every list item. Classify the shown failure.",codes[kind],[choice("kind","Failure category",correct,[["syntax","Syntax failure","Missing required punctuation prevents parsing."],["runtime","Runtime exception","Valid syntax can still request an invalid operation during execution."],["logic","Logic failure without an exception","Overwriting a total produces the wrong algorithm even when execution finishes."]])],{},["A syntax failure prevents parsing; a runtime exception occurs during execution; a logic failure can finish with the wrong behavior.","Identify the first divergence from the specification before choosing a repair."]);
  if(kind<2)out.error=kind===0?"SyntaxError":"IndexError";return out;
 }
 if(variant==="empty"){const out=make("The specification requires a nonempty mean input. Classify the empty-input failure.", "items = []\nresult = sum(items) / len(items)",[choice("error","Outcome","zero",[["zero","ZeroDivisionError","The sum and length are both zero, so this attempts 0/0."],["value","Returns 0","The empty sum identity does not define an empty mean."],["none","Returns None","This operation raises before returning a value."]])],{},["Validate the nonempty precondition or define an explicit empty-input policy before calculating a mean."]);out.error="ZeroDivisionError";return out;}
 if(variant==="boundary")return make("The specification says accept value >= threshold. Trace this equality case and repair its comparison.",`value = ${t}\naccepted = value > ${t}`,[truth("actual","Actual accepted value",false),choice("repair","Correct comparison","inclusive",[["inclusive",`value >= ${t}`,"This includes equality as required."],["strict",`value > ${t}`,"This repeats the boundary error."],["reverse",`value <= ${t}`,"This accepts the wrong side of the threshold."]])],{actual:"'true' if accepted else 'false'"},["Equality is a smallest counterexample to replacing >= with >. Test below, at and above the threshold."]);
 const modes=variant==="repair-audit"?["offbyone","reset","early"]:[variant];
 if(modes.some(m=>!["offbyone","reset","early"].includes(m)))throw Error("Unknown repair variant");
 const fields:ProgramCase["fields"]=[],checks:Record<string,string>={},code:string[]=[];
 modes.forEach((mode,i)=>{
  const body=mode==="offbyone"?"    total = 0\n    for index in range(len(items) - 1):\n        total = total + items[index]\n    return total":mode==="reset"?"    total = 0\n    for value in items:\n        total = 0\n        total = total + value\n    return total":"    total = 0\n    for value in items:\n        total = total + value\n        return total\n    return total";
  code.push(`def faulty${i}(items):\n${body}\nresult${i} = faulty${i}([${items.join(", ")}])`);
  fields.push(num("actual"+i,`Actual result${i}`,mode==="offbyone"?a+b:mode==="reset"?c:a),choice("repair"+i,`Repair for faulty${i}`,mode,[["offbyone","Use range(len(items)) to visit every index","The exclusive stop must be the length when traversing all indices."],["reset","Keep initialization before the loop; remove the reset inside","Repeated initialization discards previous contributions."],["early","Place return after the loop","Returning in the body ends the first iteration and exits the call."]]));
  checks["actual"+i]=`result${i}`;
 });
 if(variant!=="repair-audit"){fields.push(num("expected","Expected correct sum",sum));checks.expected=`sum([${items.join(", ")}])`;}
 return make("The contract is to return the sum of every integer item, including zero for an empty list. Trace the faulty result and choose the targeted repair.",code.join("\n\n"),fields,checks,[`The correct sum for [${items.join(", ")}] is ${sum}.`,"An excluded last index, repeated reset, or return inside the loop causes a different first divergence. Repair that cause and rerun boundary tests."]);
}
export function f10DebugQuestion(family:string,variant:string,seed:string,id:string){return programQuestion(family,id,"m01-l04",f10DebugCase(family,variant,seed));}

