import { randomFrom } from "../random";
import { choice,num,truth,programQuestion,type ProgramCase } from "../refreshers/programming";
export const f10StateFamilyIds=["f10-state","f10-values","f10-branch"];
export function f10StateCase(family:string,variant:string,seed:string):ProgramCase{
 const r=randomFrom(seed),a=r.integer(-6,8),b=r.integer(1,5),k=r.integer(2,4),t=r.integer(0,6),x=t+r.integer(-1,1),p={a,b,k,t,x};
 const make=(intro:string,code:string,fields:ProgramCase["fields"],checks:Record<string,string>,explanation:string[]):ProgramCase=>({intro,code,fields,checks,explanation,parameters:p});
 if(family==="f10-state"){
  if(!["reassign","swap","audit"].includes(variant))throw Error("Unknown state variant");
  if(variant==="swap")return make("Trace the temporary variable used to swap two values.",`x = ${a}\ny = ${b}\ntemp = x\nx = y\ny = temp`,[num("x","Final x",b),num("y","Final y",a)],{x:"x",y:"y"},["temp saves the original x before x is overwritten.",`The final x is ${b} and y is ${a}.`]);
  const audit=variant==="audit";return make("Trace assignments; updating x does not retroactively update y.",`x = ${a}\ny = x + ${b}\nx = y * ${k}`+(audit?"\nsame = (x == y)":""),[num("x","Final x",(a+b)*k),num("y","Final y",a+b),...(audit?[truth("same","Value of same",(a+b)*k===a+b)]:[])],{x:"x",y:"y",...(audit?{same:"'true' if same else 'false'"}:{})},[`y is assigned ${a+b} using the old x. x is then assigned ${(a+b)*k}.`,"Assignment stores the newly evaluated value; == compares values."]);
 }
 if(family==="f10-values"){
  if(!["division","types","precedence","audit"].includes(variant))throw Error("Unknown values variant");
  if(variant==="types")return make("Trace text conversion and identify the type returned by input() before conversion. Assume a valid integer string.",`raw = "${b}"\nvalue = int(raw) + ${k}`,[num("value","Value after conversion and addition",b+k),choice("type","Type of raw","str",[["str","str (text)","Quoted text stays text until converted."],["int","int (integer)","Digits inside quotes are text, even when conversion is possible."],["float","float (floating point)","A string's appearance does not change its type."]])],{value:"value",type:"type(raw).__name__"},["input() returns text; int(raw) explicitly converts valid integer text.",`The converted sum is ${b+k}.`]);
  if(variant==="precedence")return make("Evaluate parentheses and exponentiation. Python ** is exponentiation.",`value = (${a} + ${b}) ** 2\nother = ${a} + ${b} * 2`,[num("value","Value", (a+b)**2),num("other","Other",a+2*b)],{value:"value",other:"other"},["Parentheses run before exponentiation; multiplication precedes addition.",`The results are ${(a+b)**2} and ${a+2*b}.`]);
  const n=2*b+1,div=2,audit=variant==="audit";return make("Distinguish true division, floor division and remainder, including a negative dividend.",`q = ${n} / 2\nfloor_q = -${n} // 2\nrem = -${n} % 2`+(audit?`\nvalue = (${a} + ${b}) ** 2\nraw = "${k}"\nconverted = int(raw) + 1`:""),[num("q","True quotient",`${n}/${div}`),num("floor","Negative floor quotient",Math.floor(-n/2)),num("remainder","Negative dividend remainder",1),...(audit?[num("value","Parenthesized power",(a+b)**2),num("converted","Converted value",k+1),choice("type","Type of raw","str",[["str","str (text)","Quotes create text."],["int","int (integer)","Conversion creates a separate integer value."]])]:[])],{q:"q",floor:"floor_q",remainder:"rem",...(audit?{value:"value",converted:"converted",type:"type(raw).__name__"}:{})},[`True division gives ${n}/2. Floor division of -${n} by 2 rounds down to ${Math.floor(-n/2)}.`,"The identity dividend = divisor * floor_quotient + remainder gives remainder 1.",...(audit?["Parentheses precede **; converting raw does not change raw itself."]:[])]);
 }
 if(family!=="f10-branch")throw Error("Unknown state family");
 if(variant==="guard"){const denominator=r.integer(0,1)*b;return make("Trace the short-circuit guard. The right side of and runs only if the left side is true.",`denominator = ${denominator}\nsafe = denominator != 0 and ${b*k} / denominator > ${k-1}`,[truth("safe","Value of safe",denominator!==0),choice("error","Does this program divide by zero?","no",[["no","No","and skips its right operand when the denominator is zero."],["yes","Yes","The left comparison is evaluated first and guards the division."]])],{safe:"'true' if safe else 'false'"},["A false left operand short-circuits and, so division by zero is not evaluated."]);}
 if(!["threshold","independent","boolean","audit"].includes(variant))throw Error("Unknown branch variant");
 if(variant==="boolean")return make("Evaluate an inclusive interval and its negation.",`x = ${x}\ninside = x >= ${t} and x <= ${t+2}\noutside = not inside`,[truth("inside","Value of inside",x>=t&&x<=t+2),truth("outside","Value of outside",!(x>=t&&x<=t+2))],{inside:"'true' if inside else 'false'",outside:"'true' if outside else 'false'"},["Both comparisons must be true for and. not reverses the Boolean result."]);
 const first= x<t ? 1 : x===t ? 2 : 3, separate=(x>=t?1:0)+(x<=t?2:0),audit=variant==="audit";
 const code=`x = ${x}\nif x < ${t}:\n    branch = 1\nelif x == ${t}:\n    branch = 2\nelse:\n    branch = 3`;
 const second=`count = 0\nif x >= ${t}:\n    count = count + 1\nif x <= ${t}:\n    count = count + 2`;
 return make(variant==="independent"?"Trace two independent if statements.":"Trace the first true branch; compare the equality boundary.",variant==="independent"?`x = ${x}\n`+second:code+(audit?"\n"+second+`\ninside = x >= ${t} and x <= ${t+2}`:""),[...(variant!=="independent"?[num("branch","Selected branch number",first)]:[]),...(variant==="independent"||audit?[num("count","Final count",separate)]:[]),...(audit?[truth("inside","Value of inside",x>=t&&x<=t+2)]:[])],{...(variant!=="independent"?{branch:"branch"}:{}),...(variant==="independent"||audit?{count:"count"}:{}),...(audit?{inside:"'true' if inside else 'false'"}:{})},[`The input ${x} is compared with threshold ${t}; equality selects the middle elif branch. Two separate if statements may both execute.`,...(audit?["The interval condition requires both bounds."]:[])]);
}
export function f10StateQuestion(family:string,variant:string,seed:string,id:string){return programQuestion(family,id,"m01-l01",f10StateCase(family,variant,seed));}
