import { questionSchema,type Question } from "../contracts";
import { formatRational,parseRational } from "../rational";
import { formatIntervals,parseIntervals } from "../intervals";
import { randomFrom } from "../random";

export const exponentialAuditFamilyIds=["mth-exponential-audit"] as const;
const variants=["base-validity","power-confusion","offset-ratio","coefficient-initial","rate-confusion","discrete-domain","asymptote","finite-evidence","operating-window"];
const r=(source:string)=>formatRational(parseRational(source));
const number=(id:string,label:string,expected:string)=>({id,label,kind:"rational",expected:r(expected),help:"Give an exact number, fraction, or arithmetic expression."});
const approximate=(id:string,label:string,expected:number,unit="")=>({id,label,kind:"numeric",expected,absoluteTolerance:0.00000051,relativeTolerance:0,unit,help:"Round the final value to six decimal places; keep intermediate values unrounded."});
export function exponentialAuditQuestion(familyId:string,variant:string,seed:string,id:string):Question{
  if(familyId!=="mth-exponential-audit")throw new Error("Unknown exponential audit family");
  const rng=randomFrom(seed);if(variant==="mixed")variant=variants[rng.integer(0,variants.length-1)];const mode=variants.indexOf(variant);if(mode<0)throw new Error("Unknown exponential audit variant");
  const flag=rng.integer(0,1),a=rng.integer(2,6),b=mode===6?rng.integer(5,9):rng.integer(2,4),k=mode===3?-rng.integer(1,5):mode===6?rng.integer(-4,4):rng.integer(2,6),h=rng.integer(1,3),[qn,qd]=rng.shuffle([[2,1],[3,2],[1,2],[2,3]])[0],n=rng.integer(8,10),c=rng.integer(1,4),rn=(flag?-1:1)*rng.integer(1,3),rd=rng.shuffle([4,5,10])[0],step=rng.integer(2,4),sign=flag?-1:1;
  const q=r(qn+"/"+qd),choice=(id:string,label:string,correct:string,options:{id:string;label:string;feedback:string}[])=>({id,label,kind:"choice",correct,options:rng.shuffle(options)}),interval=(id:string,label:string,source:string)=>({id,label,kind:"intervals",expected:parseIntervals(source),help:"State the complete set with correct endpoint inclusion."});
  const base={id,familyId,familyVersion:1,courseId:"mth-215",objectiveId:"m05-l01",critical:true,category:"conceptual",parameters:{mode,flag,a,b,k,h,qn,qd,n,c,rn,rd,step,sign}};
  if(mode===0)return questionSchema.parse({...base,prompt:"Candidate bases are "+(-b)+", 0, 1, "+q+", and "+r("1/("+q+")")+". List every candidate that defines a nonconstant real function $f(x)=B^x$ for every real x. Explain each rejected base and give the common value at x=0 for the valid candidates.",fields:[{id:"valid",label:"All valid candidate bases",kind:"roots",numberSystem:"real",expected:[q,r("1/("+q+")")],help:"List all valid bases, separated by commas. Order does not matter."},choice("negative","Objection to the negative base","half",[{id:"half",label:"Its value at exponent one-half is not real",feedback:"A negative base cannot provide a real square root at input one-half."},{id:"sign",label:"Every negative output is forbidden for a function",feedback:"Real functions may have negative outputs; the issue is the missing real value at some real inputs."},{id:"decay",label:"A decreasing graph is not exponential",feedback:"A positive base below one gives a valid exponential decay graph."}]),choice("zero","Objection to base zero","negative",[{id:"negative",label:"A negative exponent would require division by zero",feedback:"At input -1, zero to that power cannot give a finite real output."},{id:"valid",label:"There is no objection on the full real domain",feedback:"The full real domain includes negative exponents."}]),choice("one","Objection to base one","constant",[{id:"constant",label:"It gives a constant function",feedback:"One raised to every real input remains one, so the requested nonconstant condition fails."},{id:"undefined",label:"It is undefined at every negative input",feedback:"Negative powers of one are still one."}]),number("zero-output","Output at zero for either valid base","1")],hints:["A positive base has a real value at every real exponent; exclude one when a nonconstant function is requested.","Use input one-half to test a negative base and input -1 to test base zero.","Every positive base raised to zero equals one."],explanation:["The valid bases are "+q+" and "+r("1/("+q+")")+".","A negative base fails at exponent one-half; base zero fails at negative exponents; base one is constant.","Both valid exponential functions have value one at input zero."],answerSummary:"Valid bases "+q+", "+r("1/("+q+")")+"; negative base fails at one-half; zero fails at -1; one is constant; output at zero 1."});
  if(mode===1)return questionSchema.parse({...base,prompt:"Compare $f(x)=x^{"+b+"}$ with $g(x)="+b+"^x$. Evaluate both functions at 0 and -1, then identify which rule is exponential in x.",fields:[number("f-zero","f(0)","0"),number("g-zero","g(0)","1"),number("f-negative","f(-1)",b%2?"-1":"1"),number("g-negative","g(-1)","1/"+b),choice("exponential","Exponential rule","g",[{id:"g",label:"g: the variable appears in the exponent",feedback:"The base is fixed and positive while the exponent varies."},{id:"f",label:"f: the variable appears in the base",feedback:"A fixed positive integer power of x is a power function, not an exponential in x."},{id:"both",label:"Both",feedback:"Sharing some numerical values does not make the two function structures the same."}])],hints:["Locate x before evaluating; the base and exponent play different roles.","Any nonzero base to exponent zero equals one, while zero to a positive integer power equals zero.","A negative exponent means a reciprocal, not a negative output."],explanation:["The zero-input values are f(0)=0 and g(0)=1.","At -1, f(-1)="+(b%2?-1:1)+" while g(-1)=1/"+b+".","The rule g is exponential in x; f is a power function."],answerSummary:"f(0)=0; g(0)=1; f(-1)="+(b%2?-1:1)+"; g(-1)=1/"+b+"; g is exponential."});
  if(mode===2){
    const y0=String(k+a),y1=r(k+"+"+a+"*("+q+")"),y2=r(k+"+"+a+"*("+q+")^2"),ratio1=r("("+y1+")/"+y0),ratio2=r("("+y2+")/("+y1+")"),naive=r("("+y1+")^2/"+y0);
    return questionSchema.parse({...base,prompt:"The supplied rule is $f(t)="+k+"+"+a+"("+q+")^t$. Its values at t=0,1,2 are "+y0+", "+y1+", "+y2+". A learner rejects exponential change because the raw output ratios differ. Compute the two raw ratios, the common baseline-relative ratio, a prediction at t=2 made by repeating the first raw ratio, and the correct supplied-model value. Assess the rejection.",fields:[number("first","First raw output ratio",ratio1),number("second","Second raw output ratio",ratio2),number("deviation","Common ratio after subtracting the baseline",q),number("naive","Prediction from repeating the first raw ratio",naive),number("actual","Correct model value at t = 2",y2),choice("verdict","Assessment of the rejection","offset",[{id:"offset",label:"Invalid rejection; the fixed baseline must be subtracted first",feedback:"The deviations from k, rather than raw outputs, follow the stated exponential."},{id:"reject",label:"Valid rejection; every transformed exponential has constant raw ratios",feedback:"A nonzero vertical shift changes raw output ratios."},{id:"linear",label:"The supplied rule is linear because the raw ratios differ",feedback:"Different raw ratios alone do not establish a constant output difference."}])],hints:["Use next output divided by the previous output for each raw ratio.","Subtract the supplied baseline "+k+" from every output before testing the exponential factor.","The naive prediction repeats the first raw ratio once more. Compare it with the supplied formula at t=2."],explanation:["The raw ratios are "+ratio1+" and "+ratio2+". They differ because of the baseline.","The baseline-relative ratio is "+q+" for both steps.","Repeating the first raw ratio predicts "+naive+", while the actual model gives "+y2+". This is a shifted exponential, and the proposed rejection is invalid."],answerSummary:"Raw ratios "+ratio1+", "+ratio2+"; deviation ratio "+q+"; naive "+naive+"; actual "+y2+"; retain the shifted exponential."});
  }
  if(mode===3){
    const anchor=String(a+k),initial=r(a+"/("+b+"^"+h+")+"+k);
    return questionSchema.parse({...base,prompt:"A learner calls the outside coefficient "+a+" the y-intercept of $f(x)="+a+"("+b+")^{x-"+h+"}+("+k+")$. Find f("+h+"), f(0), and the horizontal asymptote, then identify what the coefficient actually measures.",fields:[number("anchor","Value at the shifted anchor",anchor),number("initial","Actual y-intercept",initial),number("asymptote","Horizontal asymptote level",String(k)),choice("meaning","Meaning of the outside coefficient","deviation",[{id:"deviation",label:"The deviation from the baseline at the shifted anchor",feedback:"At x=h the exponential factor equals one, so f(h)-k=a."},{id:"intercept",label:"The y-intercept for this formula",feedback:"The y-intercept requires evaluating the complete shifted formula at x=0."},{id:"baseline",label:"The horizontal asymptote",feedback:"The outside additive constant determines the horizontal asymptote."}])],hints:["Substitute the horizontal shift to make the exponent zero.","For the y-intercept, substitute zero into the actual exponent instead.","Subtract the baseline from the anchor output to interpret the outside scale."],explanation:["The shifted anchor value is "+anchor+", while f(0)="+initial+".","The horizontal asymptote is y="+k+".","The coefficient "+a+" is f("+h+") minus the baseline, not the y-intercept."],answerSummary:"Anchor "+anchor+"; intercept "+initial+"; asymptote "+k+"; coefficient is the anchor deviation."});
  }
  if(mode===4){
    const rate=r(rn+"/"+rd),exponent=r(rn*step+"/"+rd),proposed=r("1+("+exponent+")"),factor=Math.exp(rn*step/rd),effective=100*Math.expm1(rn*step/rd);
    return questionSchema.parse({...base,prompt:"A continuous law has rate r="+rate+" per second. Over "+step+" s its multiplier is exp(r*t). A learner substitutes 1+r*t and calls this exactly the same model. Compute the exponent, true multiplier, proposed multiplier, and effective signed percentage change over the interval. Use a calculator for the exponential and round numerical fields to six decimal places.",fields:[number("exponent","Dimensionless exponent",exponent),approximate("factor","True interval multiplier",factor),number("proposed","Proposed linear multiplier",proposed),approximate("effective","True signed interval percentage change",effective,"%"),choice("identity","Is the proposed multiplier exactly equal here?","no",[{id:"no",label:"No",feedback:"The linear expression 1+z differs from exp(z) for this nonzero exponent. It can be a local approximation, not an exact replacement."},{id:"yes",label:"Yes",feedback:"A continuous rate must enter the exponential before becoming a finite-interval multiplier."}])],hints:["Multiply the rate by elapsed time before evaluating either expression.","The true factor is exp of that exponent; the proposed expression only adds the exponent to one.","Convert the true factor to a percentage by subtracting one and multiplying by 100."],explanation:["The exponent is "+exponent+". The true factor is approximately "+factor.toFixed(6)+"; the proposed factor is "+proposed+".","The true signed interval change is approximately "+effective.toFixed(6)+"%.","The nonzero exponent makes the proposed exact identity false. A negative or zero proposed factor is especially incompatible with a positive exponential multiplier."],answerSummary:"Exponent "+exponent+"; true factor approximately "+factor.toFixed(6)+"; proposed "+proposed+"; signed change approximately "+effective.toFixed(6)+"%; not exactly equal."});
  }
  if(mode===5){
    const square=b*b,half=String(a*b);
    return questionSchema.parse({...base,prompt:"A recorded-update rule is $Y(n)="+a+"("+square+")^n$ and is specified only for n=0,1,2,... . No continuous physical process between updates is assumed. State the domain of the formula's continuous real extension, identify the actual recorded-rule domain, evaluate the continuous extension at n=1/2, and decide whether that input is allowed by the recorded rule.",fields:[interval("extension-domain","Domain of the continuous real extension","R"),choice("recorded-domain","Domain of the specified recorded rule","integers",[{id:"integers",label:"Nonnegative integers only",feedback:"The rule was specified after whole updates beginning with update zero."},{id:"nonnegative",label:"Every nonnegative real number",feedback:"That would add fractional updates not included in the stated rule."},{id:"real",label:"All real numbers",feedback:"That is the extension's domain, not the supplied recorded-rule domain."}]),number("half","Continuous extension at n = 1/2",half),choice("allowed","Is n = 1/2 allowed by the recorded rule?","no",[{id:"no",label:"No",feedback:"A real algebraic extension can exist outside the explicitly stated input set."},{id:"yes",label:"Yes",feedback:"A valid numerical formula value does not add new allowed observation inputs."}]),choice("interpretation","Interpretation of the half-step value","extension",[{id:"extension",label:"A value of an additional continuous extension, not a recorded update",feedback:"The supplied data rule makes no claim about physical behavior between updates."},{id:"observation",label:"A guaranteed observed measurement",feedback:"The rule does not specify observations at fractional updates."}])],hints:["A positive-base formula can be evaluated at every real number as a mathematical extension.","The explicitly supplied recorded-rule domain is a separate set.","At exponent one-half, take the positive square root of the positive base, then apply the coefficient."],explanation:["The continuous extension has domain R, but the specified rule accepts only n=0,1,2,... .","The extension at n=1/2 is "+half+".","That real value does not make half an update an allowed input or establish behavior between recordings."],answerSummary:"Extension domain R; recorded domain nonnegative integers; extension at one-half "+half+"; input not allowed by the recorded rule; interpretation is extension only."});
  }
  if(mode===6){
    const coefficient=sign*a,deviation=r(coefficient+"/("+b+"^"+n+")"),value=r(k+"+("+deviation+")"),range=coefficient>0?"("+k+",inf)":"(-inf,"+k+")";
    return questionSchema.parse({...base,prompt:"For $f(x)="+k+"+("+coefficient+")("+b+")^{-x}$, a display rounded to three decimal places shows the baseline "+k+" at x="+n+". A learner concludes that the graph reaches its horizontal asymptote at this finite input. State the exact range, asymptote, exact deviation f("+n+") minus the baseline, and exact f("+n+"). Audit the conclusion.",fields:[interval("range","Complete exact range",range),number("asymptote","Horizontal asymptote level",String(k)),number("deviation","Exact deviation at the displayed input",deviation),number("value","Exact output at the displayed input",value),choice("reached","Does the exact graph reach its asymptote here?","no",[{id:"no",label:"No",feedback:"The nonzero coefficient times a positive exponential remains nonzero at every finite input."},{id:"yes",label:"Yes",feedback:"A rounded display cannot establish exact equality with the asymptote."}]),choice("display","Why does the display show the baseline?","rounding",[{id:"rounding",label:"A small nonzero deviation was lost to rounding",feedback:"The displayed digits can coincide even though the exact values differ."},{id:"zero",label:"The exact exponential factor became zero",feedback:"A positive base to a finite real exponent is never zero."}])],hints:["For every finite x, the exponential factor is strictly positive.","The sign of the outside coefficient determines which open side of the baseline contains the range.","Compute the exact reciprocal power before adding the baseline. Keep a nonzero fraction even when its decimal display rounds to zero."],explanation:["The exact range is "+formatIntervals(parseIntervals(range))+", excluding the baseline y="+k+".","The exact deviation at x="+n+" is "+deviation+", so the exact output is "+value+".","The deviation is nonzero. The matching display is caused by rounding, and the finite-input equality claim is false."],answerSummary:"Range "+range+"; asymptote "+k+"; deviation "+deviation+"; exact output "+value+"; no equality; rounded display only."});
  }
  if(mode===8){
    const coefficient=sign*a,start=String(k+coefficient),end=r(k+"+("+coefficient+")*("+q+")^"+step),probe=r(k+"+("+coefficient+")/("+q+")"),increasing=(coefficient>0)===(qn>qd),range="["+(increasing?start:end)+","+(increasing?end:start)+"]",fullRange=coefficient>0?"("+k+",inf)":"(-inf,"+k+")";
    return questionSchema.parse({...base,category:"application",prompt:"The response formula $Y(t)="+k+"+("+coefficient+")("+q+")^t$ gives Y in V for numerical time t in seconds. The physical model is authorized only for 0 through "+step+" s, including both endpoints. State the full formula domain, operating time interval, full formula range, and operating output range. Evaluate the formula at t=-1 and decide whether that algebraically valid value is an authorized physical prediction.",fields:[interval("domain","Full formula domain","R"),interval("operating-domain","Operating time interval (s)","[0,"+step+"]"),interval("range","Full formula range (V)",fullRange),interval("operating-range","Operating output range (V)",range),number("probe","Formula output at t = -1 (V)",probe),choice("allowed","Is the negative-time value authorized by this physical model?","no",[{id:"no",label:"No; it is outside the supplied operating interval",feedback:"The formula remains mathematically defined, but this physical model was specified only from time zero through the stated endpoint."},{id:"yes",label:"Yes; every defined formula input is physically authorized",feedback:"A formula's mathematical domain does not replace a stated physical operating interval."}])],hints:["A positive-base exponential is mathematically defined at every real input. Keep this separate from the supplied operating interval.","Evaluate both included endpoints, then use the sign of the output's monotonic direction to order the output bounds.","The full range excludes the horizontal asymptote. The finite operating range includes its attained endpoint values."],explanation:["The full domain is R and the operating input interval is [0,"+step+"] s.","The endpoint outputs are Y(0)="+start+" V and Y("+step+")="+end+" V. The response is "+(increasing?"increasing":"decreasing")+", giving operating range "+range+" V.","The full mathematical range is "+fullRange+" V. Both operating output endpoints are attained, while the asymptote is excluded from the full range.","At t=-1, the formula gives "+probe+" V. This value is algebraically defined but outside the authorized physical time window."],answerSummary:"Full domain R; operating domain [0,"+step+"]; full range "+fullRange+"; operating range "+range+"; negative-time output "+probe+" V; outside the authorized physical window."});
  }
  const first=r(a+"*("+q+")^3"),second=r("("+first+")+"+6*c);
  return questionSchema.parse({...base,prompt:"The three exact records at t=0,1,2 agree with $F(t)="+a+"("+q+")^t$. A learner claims they prove that formula at every real input. Compare the alternative $G(t)=F(t)+"+c+"t(t-1)(t-2)$. Find G(2)-F(2), both predictions at t=3, and their difference there. Assess what the records establish.",fields:[number("recorded","G(2) minus F(2)","0"),number("first","F(3)",first),number("second","G(3)",second),number("difference","G(3) minus F(3)",String(6*c)),choice("evidence","What do the three records establish?","consistent",[{id:"consistent",label:"Consistency with the candidate at those inputs, without a unique universal law",feedback:"The alternative agrees at every recorded input and differs at another input."},{id:"proved",label:"Proof that the candidate holds at every real input",feedback:"A finite list of matches does not rule out other functions between or beyond those inputs."},{id:"contradicted",label:"A contradiction of the candidate at one recorded input",feedback:"Both candidates agree with all three supplied records."}])],hints:["At each recorded input, one factor in t(t-1)(t-2) is zero.","At t=3 the correction is the coefficient times 3 times 2 times 1.","Two functions can agree at all recorded inputs and disagree elsewhere."],explanation:["The correction is zero at t=0,1,2, including G(2)-F(2)=0.","At t=3, F predicts "+first+" while G predicts "+second+", a difference of "+6*c+".","The records support consistency at those inputs. Choosing a model for other inputs requires an assumption or additional evidence."],answerSummary:"Recorded difference 0; F(3)="+first+"; G(3)="+second+"; difference "+6*c+"; finite consistency, not a unique universal law."});
}
