import { questionSchema,type Question } from "../contracts";
import { formatRational,parseRational } from "../rational";
import { evaluateExponential,exponentialFunctionSchema,factorFromPercent,percentFromFactor } from "../exponential-functions";
import { randomFrom } from "../random";

export const exponentialFactorFamilyIds=["mth-exponential-factor"] as const;
const variants=["percent-growth","percent-decay","factor-percent","repeated-change","reverse-change","step-conversion","compound-rate","continuous-rate"];
const r=(source:string)=>formatRational(parseRational(source));
const number=(id:string,label:string,expected:string,unit="")=>({id,label,kind:"rational",expected:r(expected),unit,help:"Give an exact fraction or arithmetic expression. Round only when a field explicitly requests it."});
const approximate=(id:string,label:string,expected:number,unit="")=>({id,label,kind:"numeric",expected,absoluteTolerance:0.00000051,relativeTolerance:0,unit,help:"Round the final value to six decimal places. Keep intermediate values unrounded."});
export function exponentialFactorQuestion(familyId:string,variant:string,seed:string,id:string):Question{
  if(familyId!=="mth-exponential-factor")throw new Error("Unknown exponential factor family");
  const rng=randomFrom(seed);if(variant==="mixed")variant=variants[rng.integer(0,variants.length-1)];const mode=variants.indexOf(variant);if(mode<0)throw new Error("Unknown exponential factor variant");
  const flag=rng.integer(0,1),initial=rng.integer(2,12)*5,percent=(mode===1||mode===4&&flag?-1:1)*rng.shuffle([10,20,25,50])[0],secondPercent=(flag?-1:1)*rng.shuffle([10,20,25,50])[0],step=rng.integer(2,4),count=rng.integer(2,4),[qn,qd]=rng.shuffle([[3,2],[5,4],[4,5],[2,3],[1,4]])[0],nominal=rng.shuffle([4,6,8,12])[0],updates=rng.integer(2,4),time=rng.integer(1,2),rn=(flag?-1:1)*rng.integer(1,4),rd=rng.shuffle([4,5,10])[0];
  const factor=factorFromPercent(String(percent)),combined=r("("+factor+")^"+count),output=r(initial+"*("+combined+")"),change=percentFromFactor(combined),givenFactor=r(qn+"/"+qd);
  const base={id,familyId,familyVersion:1,courseId:"mth-215",objectiveId:"m05-l01",critical:true,category:mode>=6?"application":"procedural",parameters:{mode,flag,initial,percent,secondPercent,step,count,qn,qd,nominal,updates,time,rn,rd}};
  if(mode<2)return questionSchema.parse({...base,prompt:"A positive response starts at "+initial+" V and "+(percent>0?"increases":"decreases")+" by "+Math.abs(percent)+"% of its current value every "+step+" s. The same proportional rule applies each period. At elapsed time "+(count*step)+" s, find the signed fractional rate per period, multiplier per period, number of periods, response, and total signed percentage change from the initial response.",fields:[number("rate","Signed fractional rate per period",percent+"/100"),number("factor","Multiplier per period",factor),number("periods","Number of elapsed periods",String(count)),number("output","Response after the elapsed time",output,"V"),number("change","Total signed percentage change",change,"%")],hints:["Write new value as old value plus its signed fractional change. This gives factor 1+r.","Divide elapsed time by the period length before choosing the exponent.","Apply the multiplier repeatedly, then compute 100 times (total multiplier minus 1). Do not add the same amount or percentage once per period."],explanation:["The signed fractional rate is "+r(percent+"/100")+", so the factor is "+factor+".","There are "+count+" periods. The total multiplier is "+combined+", giving "+output+" V.","The cumulative signed percentage change is "+change+"%. Each change acts on the current response, not the initial response."],answerSummary:"Rate "+r(percent+"/100")+"; factor "+factor+"; periods "+count+"; output "+output+" V; signed change "+change+"%."});
  if(mode===2)return questionSchema.parse({...base,prompt:"A positive response of "+initial+" V is multiplied by "+givenFactor+" over one stated interval. Find the signed percentage change, the percentage of the original response that remains, and the resulting response. Classify the change.",fields:[number("change","Signed percentage change",percentFromFactor(givenFactor),"%"),number("remaining","Result as a percentage of the original",r("100*("+givenFactor+")"),"%"),number("output","Resulting response",r(initial+"*("+givenFactor+")"),"V"),{id:"direction",label:"Direction of change",kind:"choice",correct:qn>qd?"increase":"decrease",options:rng.shuffle([{id:"increase",label:"Increase",feedback:"A positive multiplier above one increases a positive response."},{id:"decrease",label:"Decrease",feedback:"A multiplier strictly between zero and one reduces a positive response."},{id:"unchanged",label:"Unchanged",feedback:"No change would require multiplier one."}])}],hints:["A multiplier describes the resulting response as a fraction of the original.","Subtract one before multiplying by 100 to find the signed change.","The remaining percentage is 100 times the multiplier; it is not the percentage lost."],explanation:["The signed change is 100*("+givenFactor+"-1)="+percentFromFactor(givenFactor)+"%.","The resulting response is "+r(initial+"*("+givenFactor+")")+" V, or "+r("100*("+givenFactor+")")+"% of the original.","For a multiplier below one, the magnitude of the negative change is the percentage decrease."],answerSummary:"Signed change "+percentFromFactor(givenFactor)+"%; remaining "+r("100*("+givenFactor+")")+"%; response "+r(initial+"*("+givenFactor+")")+" V."});
  if(mode===3){
    const second=factorFromPercent(String(secondPercent)),total=r("("+factor+")*("+second+")"),final=r(initial+"*("+total+")"),net=percentFromFactor(total);
    return questionSchema.parse({...base,prompt:"A response starts at "+initial+" V, changes by "+percent+"% of its current value, then changes by "+secondPercent+"% of the new current value. Positive percentages mean increases and negative percentages mean decreases. Find each multiplier, their combined multiplier, the final response, and the total signed percentage change.",fields:[number("first","First multiplier",factor),number("second","Second multiplier",second),number("combined","Combined multiplier",total),number("output","Final response",final,"V"),number("change","Total signed percentage change",net,"%")],hints:["Convert each signed percentage to 1 plus its fractional rate.","Multiply the two factors because the second change acts on the changed response.","Only after combining the factors should you subtract one and convert back to percent."],explanation:["The factors are "+factor+" and "+second+", so the combined factor is "+total+".","The final response is "+final+" V, and the net signed change is "+net+"%.","Equal and opposite percentage changes generally do not cancel. Their factors multiply rather than their percentages adding."],answerSummary:"Factors "+factor+", "+second+"; combined "+total+"; output "+final+" V; net "+net+"%."});
  }
  if(mode===4){
    const changed=r(initial+"*("+factor+")"),undo=r("1/("+factor+")"),reverse=percentFromFactor(undo),wrong=r("("+changed+")*(1-("+percent+")/100)");
    return questionSchema.parse({...base,prompt:"After a signed change of "+percent+"%, a positive response is "+changed+" V. Recover the original response. Also find the applied multiplier, the exact restoring multiplier and its signed percentage change. For comparison, compute the response obtained by merely applying "+(-percent)+"% to the changed value.",fields:[number("factor","Applied multiplier",factor),number("undo","Restoring multiplier",undo),number("original","Original response",String(initial),"V"),number("reverse","Signed percentage change needed to restore",reverse,"%"),number("opposite","Response after merely reversing the percentage sign",wrong,"V")],hints:["The given response equals original response times the applied factor.","Undo a nonzero multiplication by its reciprocal.","Convert the reciprocal factor to a signed percentage. Reversing the old percentage sign does not generally produce that reciprocal."],explanation:["The applied factor is "+factor+". Its reciprocal is "+undo+".","Multiplying "+changed+" V by "+undo+" recovers "+initial+" V.","The restoring signed percentage is "+reverse+"%. Merely reversing the old percentage sign would instead give "+wrong+" V."],answerSummary:"Applied "+factor+"; restore by "+undo+" or "+reverse+"%; original "+initial+" V; opposite-sign attempt "+wrong+" V."});
  }
  if(mode===5){
    const observed=r("("+givenFactor+")^"+step),target=step+1,total=r("("+givenFactor+")^"+target),final=r(initial+"*("+total+")");
    return questionSchema.parse({...base,prompt:"A positive zero-baseline response starts at "+initial+" V and multiplies by "+observed+" every "+step+" s. Assume a constant exponential law. Find the positive one-second multiplier, its signed percentage change, the exponent to use on the given multi-second factor at t="+target+" s, the total multiplier at that time, and the response.",fields:[number("factor","One-second multiplier",givenFactor),number("change","Signed change per second",percentFromFactor(givenFactor),"%"),number("exponent","Exponent on the supplied multi-second factor",target+"/"+step),number("combined","Total multiplier at the requested time",total),number("output","Requested response",final,"V")],hints:["If b is the one-second factor, b raised to the number of seconds in the supplied interval must equal the supplied factor.","Choose the positive root, because a real exponential base is positive.","The original factor is raised to elapsed time divided by its own interval length. Do not divide the original percentage change by the number of seconds."],explanation:["The positive one-second factor is "+givenFactor+", since its power "+step+" is "+observed+".","Its signed per-second change is "+percentFromFactor(givenFactor)+"%.","At "+target+" s, raise the supplied factor to "+r(target+"/"+step)+". This equals multiplier "+total+", giving "+final+" V."],answerSummary:"One-second factor "+givenFactor+"; change "+percentFromFactor(givenFactor)+"%; exponent "+r(target+"/"+step)+"; total "+total+"; output "+final+" V."});
  }
  if(mode===6){
    const rate=r(nominal+"/100"),periodRate=r("("+rate+")/"+updates),periodFactor=r("1+("+periodRate+")"),periods=updates*time,final=r(initial+"*("+periodFactor+")^"+periods),effective=percentFromFactor(r("("+periodFactor+")^"+updates));
    return questionSchema.parse({...base,prompt:"An idealized accumulation process is defined by $A(t)=A_0(1+r/m)^{mt}$, with t measured numerically in seconds. Here A0="+initial+" V, the nominal fractional rate r="+rate+" per second, and m="+updates+" updates per second. The supplied law applies without any other inputs. Find the rate and multiplier per update, the number of updates in "+time+" s, the resulting response, and the effective signed percentage change over one second.",fields:[number("rate","Fractional rate per update",periodRate),number("factor","Multiplier per update",periodFactor),number("periods","Number of updates in the requested time",String(periods)),number("output","Response at the requested time",final,"V"),number("effective","Effective signed one-second change",effective,"%")],hints:["Divide the nominal rate by the updates per second to find the rate applied at each update.","One update multiplies by 1+r/m. There are m*t updates, not just t.","For the one-second effective change, combine m update factors before converting back to percent."],explanation:["The fractional rate per update is "+periodRate+", so its multiplier is "+periodFactor+".","Over "+time+" s there are "+periods+" updates, giving "+final+" V.","The effective one-second percentage is 100*(("+periodFactor+")^"+updates+"-1)="+effective+"%. It differs from the supplied nominal percentage "+nominal+"%."],answerSummary:"Per-update rate "+periodRate+"; factor "+periodFactor+"; updates "+periods+"; response "+final+" V; effective change "+effective+"%."});
  }
  const rate=r(rn+"/"+rd),exponent=r("("+rate+")*"+time),model=exponentialFunctionSchema.parse({kind:"natural-base",a:String(initial),rate,h:"0",k:"0"}),response=evaluateExponential(model,String(time));
  if(response.status!=="finite")throw new Error("This continuous-rate item requires a finite response.");
  const oneSecond=Math.exp(rn/rd),effective=100*Math.expm1(rn/rd);
  return questionSchema.parse({...base,prompt:"A supplied continuous model is $Y(t)="+initial+"e^{("+rate+")t}$ V, where t is the numerical time in seconds. A calculator is permitted. At t="+time+" s, find the dimensionless exponent and response. Also find the one-second multiplier and effective signed one-second percentage change. Round numerical fields to six decimal places, without rounding intermediate exponentials.",fields:[number("exponent","Dimensionless exponent at the requested time",exponent),approximate("factor","One-second multiplier",oneSecond),approximate("output","Response at the requested time",response.approximate,"V"),approximate("effective","Effective signed one-second change",effective,"%"),{id:"meaning",label:"Meaning of the coefficient in the exponent",kind:"choice",correct:"continuous",options:rng.shuffle([{id:"continuous",label:"A continuous fractional rate; its one-second factor is e raised to that rate",feedback:"Continuous rate r gives factor exp(r) over one second, not exactly 1+r."},{id:"discrete",label:"A discrete one-second percentage that gives factor 1 plus the coefficient",feedback:"That would replace the supplied continuous law with a different discrete law."},{id:"multiplier",label:"The multiplier itself",feedback:"The exponent coefficient must first enter the exponential to produce the time-step multiplier."}])}],hints:["Multiply the continuous rate by elapsed seconds to get the dimensionless exponent.","For a one-second interval, the multiplier is exp(r), while the response at time t is the initial response times exp(r*t).","Compute 100*(exp(r)-1) for the effective one-second percentage. Keep the sign of a decay rate."],explanation:["At the requested time, the exponent is "+exponent+" and the response is approximately "+response.approximate.toFixed(6)+" V.","The one-second multiplier is approximately "+oneSecond.toFixed(6)+", with effective signed change "+effective.toFixed(6)+"%.","The coefficient "+rate+" is a continuous rate per second. It is not itself the finite-interval multiplier or the effective percentage divided by 100."],answerSummary:"Exponent "+exponent+"; factor approximately "+oneSecond.toFixed(6)+"; output approximately "+response.approximate.toFixed(6)+" V; effective change approximately "+effective.toFixed(6)+"%; continuous rate."});
}
