import { questionSchema,type Question } from "../contracts";
import { parseIntervals } from "../intervals";
import { formatRational,parseRational } from "../rational";
import { rationalLatex } from "../transformations";
import { randomFrom } from "../random";

export const logRuleFamilyIds=["mth-log-rules"] as const;
const variants=["product","quotient","power","root","expand","condense","change-base","fractional-base"];
const r=(source:string)=>formatRational(parseRational(source));
const rational=(id:string,label:string,expected:string)=>({id,label,kind:"rational",expected:r(expected),help:"Give an exact number or fraction."});
const exact=(id:string,label:string,expected:string)=>({id,label,kind:"logarithmic",expected});
const domain=(expected:string)=>({id:"domain",label:"Complete original real domain",kind:"intervals",expected:parseIntervals(expected),help:"Use interval notation and U for a union. Retain every original restriction, even if the condensed formula accepts more inputs."});
export function logRuleQuestion(familyId:string,variant:string,seed:string,id:string):Question{
  if(familyId!=="mth-log-rules")throw new Error("Unknown logarithm rule family");
  const rng=randomFrom(seed);if(variant==="mixed")variant=variants[rng.integer(0,variants.length-1)];
  const mode=variants.indexOf(variant);if(mode<0)throw new Error("Unknown logarithm rule variant");
  const b=rng.shuffle([2,3,5,10])[0],u=rng.integer(2,9),v=rng.integer(1,7),p=rng.shuffle([-4,-3,-2,-1,2,3,4])[0],degree=rng.integer(2,5),h=rng.integer(-4,2),k=h+rng.integer(1,4),c=rng.integer(2,9),m=rng.integer(1,3),n=rng.integer(1,3);
  const argument=r(u+"/"+v),log="\\log_{"+b+"}",left="(x-("+h+"))",right="(x-("+k+"))",latexLeft="\\left(x-("+h+")\\right)",latexRight="\\left(x-("+k+")\\right)";
  const choice=(id:string,label:string,correct:string,options:{id:string;label:string;feedback:string}[])=>({id,label,kind:"choice",correct,options:rng.shuffle(options)});
  const conditions=choice("conditions","Conditions for the real product and quotient identities","positive-same",[
    {id:"positive-same",label:"Both arguments are positive and both logarithms have the same positive base other than one",feedback:"Each separate real logarithm must exist, and adding or subtracting exponents uses the same base."},
    {id:"product-positive",label:"Only the product or quotient must be positive; negative individual arguments are allowed",feedback:"Two negative factors can give a positive product, but each separate real logarithm still rejects a negative argument."},
    {id:"any-base",label:"The arguments are positive, so different logarithm bases can be combined directly",feedback:"Different bases require conversion before applying a same-base product or quotient identity."},
    {id:"nonnegative",label:"Zero arguments are allowed when the base is positive",feedback:"A real logarithm never accepts zero, and base one also fails."},
  ]);
  const base={id,familyId,familyVersion:1,courseId:"mth-215",objectiveId:"m05-l03",critical:true,category:"procedural",parameters:{mode,b,u,v,p,degree,h,k,c,m,n}};
  if(mode<=1){
    const combined=r(mode===0?u+"*"+v:u+"/"+v),value="ln("+combined+")/ln("+b+")",symbol=mode===0?"+":"-";
    return questionSchema.parse({...base,prompt:"Condense $"+log+"("+u+")"+symbol+log+"("+v+")$ into one logarithm with the original base. Give its argument and exact value, then state the general conditions under which this identity can be used for real logarithms.",fields:[rational("argument","Argument of the combined logarithm",combined),exact("value","Exact value of the expression",value),conditions],hints:["Check that both original arguments are strictly positive and that their bases agree.",mode===0?"Adding logarithms adds exponents, so multiply the arguments. Do not add them.":"Subtracting logarithms subtracts exponents, so divide the first argument by the second. Keep the order.","Use change of base for an exact value if it does not simplify to a rational number. Retain the logarithms rather than rounding."],explanation:["The arguments "+u+" and "+v+" are positive and the common base "+b+" is positive and different from one.","The combined argument is "+u+(mode===0?" times ":" divided by ")+v+" = "+combined+".","The exact value is $"+log+"("+rationalLatex(combined)+")=\\frac{\\ln("+rationalLatex(combined)+")}{\\ln("+b+")}$.","For the general identity, positivity of only the combined argument is insufficient: each original real logarithm must exist."],answerSummary:"Combined argument "+combined+"; exact value "+value+"; positive original arguments and the same valid base."});
  }
  if(mode===2||mode===3){
    const coefficient=mode===2?String(p):"1/"+degree,value="("+coefficient+")*ln("+argument+")/ln("+b+")";
    const expression=mode===2?log+"\\left(("+rationalLatex(argument)+")^{"+p+"}\\right)":log+"\\left(\\sqrt["+degree+"]{"+rationalLatex(argument)+"}\\right)";
    return questionSchema.parse({...base,prompt:"Rewrite $"+expression+"$ as $K"+log+"("+rationalLatex(argument)+")$. Find K and the exact value. The supplied argument is positive; use the positive root in the radical expression.",fields:[rational("coefficient","Coefficient K",coefficient),exact("value","Exact value of the expression",value),choice("power-rule","Condition needed for the stated real power identity","positive",[{id:"positive",label:"The unpowered logarithm argument is strictly positive",feedback:"A positive argument allows the real logarithm and its real powers. An even power alone does not make the logarithm of a negative unpowered argument legal."},{id:"nonzero",label:"The unpowered argument may be any nonzero real number",feedback:"Negative arguments require an appropriate absolute-value expression; the displayed logarithm without absolute values cannot accept them."},{id:"zero",label:"The unpowered argument may equal zero",feedback:"A zero argument is never allowed in a real logarithm."}])],hints:["Identify the exponent on the complete positive argument.",mode===2?"Move that signed exponent outside the logarithm as a multiplier. A negative exponent remains negative.":"A positive nth root is the argument to the power 1/n. That reciprocal becomes the multiplier.","Use the same valid logarithm base throughout. Keep the resulting expression exact."],explanation:["The supplied argument "+argument+" is strictly positive.","Its power is "+coefficient+", so the logarithm power identity gives coefficient K="+r(coefficient)+".","The exact result is "+value+". The identity is justified on positive unpowered arguments; it does not create a logarithm of a negative number."],answerSummary:"K="+r(coefficient)+"; exact value "+value+"; positive unpowered argument."});
  }
  if(mode===4){
    const originalDomain="(-inf,"+h+") U ("+h+","+k+") U ("+k+",inf)",constant="ln("+c+")/ln("+b+")";
    return questionSchema.parse({...base,prompt:"Expand $"+log+"\\left(\\frac{"+c+latexLeft+"^{"+2*m+"}}{"+latexRight+"^{"+2*n+"}}\\right)$ over its complete real domain. Construct the form $C+A"+log+"|x-("+h+")|+B"+log+"|x-("+k+")|$ by giving C, A and B. Determine the original domain without assuming x is positive.",fields:[exact("constant","Exact constant C",constant),rational("first","Coefficient A",String(2*m)),rational("second","Coefficient B",String(-2*n)),domain(originalDomain),choice("absolute","Why are the absolute values needed?","both-signs",[{id:"both-signs",label:"They preserve the allowed inputs on either side of each excluded point",feedback:"Even powers of nonzero real quantities are positive. The absolute-value arguments are positive on exactly those nonzero quantities."},{id:"positive-only",label:"They require x to lie above both excluded points",feedback:"Absolute values allow either sign of the nonzero shifted input, retaining every branch of the original domain."},{id:"zeros",label:"They make zero arguments acceptable",feedback:"An absolute value of zero is still zero, which a logarithm rejects."}])],hints:["The denominator cannot be zero, and the complete logarithm argument must be positive. Both even powers are positive away from their zeros.","Separate the positive constant, subtract the denominator logarithm, and rewrite each even power using the absolute value of its shifted input.","The quotient gives the denominator coefficient a minus sign. Keep both excluded points in the complete domain."],explanation:["The denominator excludes x="+k+". The numerator vanishes at x="+h+", producing a forbidden logarithm argument of zero. Everywhere else the quotient is positive.","The constant is "+constant+", the numerator coefficient is "+2*m+", and the denominator coefficient is "+(-2*n)+".","Absolute values preserve the branches where one or both shifted inputs are negative. Removing the absolute values would narrow the domain.","The complete domain is "+originalDomain+"."],answerSummary:"C="+constant+"; A="+2*m+"; B="+(-2*n)+"; domain "+originalDomain+"; absolute values preserve both signs."});
  }
  if(mode===5){
    const expression="("+c+"*"+left+"^"+m+")/("+right+"^"+n+")",originalDomain="("+k+",inf)";
    return questionSchema.parse({...base,prompt:"Condense $"+m+log+"("+latexLeft+")-"+n+log+"("+latexRight+")+"+log+"("+c+")$ as $"+log+"(A(x))$. Construct the single simplified fraction A(x), and retain the original real domain of the separate logarithms.",fields:[{id:"argument",label:"Combined argument A(x)",kind:"rational-expression",expected:expression,domainFieldId:"domain",help:"Enter one fraction with parentheses around its full numerator and denominator, using x and arithmetic. Do not include log(). Give the original domain separately."},domain(originalDomain)],hints:["Each separate shifted argument must be positive. Intersect the two inequalities before rewriting anything.","Move the coefficients into powers of their complete arguments. The subtracted logarithm becomes the denominator.","Multiply the positive constant into the numerator. Retain the original domain even if the condensed argument happens to be positive elsewhere."],explanation:["The original restrictions are x>"+h+" and x>"+k+", so their intersection is x>"+k+".","The power identity puts exponents "+m+" and "+n+" on their respective shifted arguments.","The product and quotient identities then give A(x)="+expression+". Its different shifted factors have no common variable factor.","The result is used only on "+originalDomain+", the original domain. Condensation cannot add new inputs to that expression."],answerSummary:"A(x)="+expression+" on "+originalDomain+"."});
  }
  if(mode===6){
    const numerator="ln("+argument+")",denominator="ln("+b+")",value=numerator+"/"+denominator,approximation=Math.log(u/v)/Math.log(b);
    return questionSchema.parse({...base,prompt:"Apply change of base to $"+log+"("+rationalLatex(argument)+")$ using natural logarithms. Give the numerator, denominator, exact quotient, and a final numerical value rounded to six decimal places. Keep the order of argument and base.",fields:[exact("numerator","Natural-log numerator",numerator),exact("denominator","Natural-log denominator",denominator),exact("value","Exact quotient",value),{id:"approximation",label:"Numerical value to six decimal places",kind:"numeric",expected:approximation,absoluteTolerance:.00000051,relativeTolerance:0,help:"Compute with extra digits, then round only the final numerical result to six decimal places."}],hints:["If y=log_b(a), then b^y=a. Take natural logarithms of both sides.","The power identity gives y ln(b)=ln(a). Divide by ln(b), which is nonzero because the base is not one.","The exact quotient is ln(argument)/ln(base). Use that same quotient for the separate numerical field."],explanation:["Starting with $"+b+"^y="+rationalLatex(argument)+"$ gives $y\\ln("+b+")=\\ln("+rationalLatex(argument)+")$.","The numerator is "+numerator+" and the nonzero denominator is "+denominator+".","The exact quotient is "+value+". A common-log quotient with the same ordering gives the same exact value.","The final numerical approximation is "+approximation.toFixed(6)+". It belongs in the numerical field, not as a substitute for an unsimplified exact logarithm."],answerSummary:"Numerator "+numerator+"; denominator "+denominator+"; exact "+value+"; numerical "+approximation.toFixed(6)+"."});
  }
  const value="-ln("+argument+")/ln("+b+")",sign=u===v?"zero":u<v?"positive":"negative";
  return questionSchema.parse({...base,category:"conceptual",prompt:"Rewrite $\\log_{1/"+b+"}("+rationalLatex(argument)+")$ as $K"+log+"("+rationalLatex(argument)+")$. Give K, the exact value, and its sign. Explain why the reciprocal base is valid.",fields:[rational("coefficient","Coefficient K","-1"),exact("value","Exact value of the expression",value),choice("sign","Sign of the logarithm",sign,[{id:"negative",label:"Negative",feedback:"For a base between zero and one, an argument above one gives a negative logarithm."},{id:"zero",label:"Zero",feedback:"Every valid logarithm of one equals zero."},{id:"positive",label:"Positive",feedback:"For a base between zero and one, an argument between zero and one gives a positive logarithm."}]),choice("base-rule","Why is the reciprocal base valid?","positive-not-one",[{id:"positive-not-one",label:"It is positive and different from one",feedback:"A valid real logarithm base may lie between zero and one; the logarithm is then decreasing."},{id:"invalid",label:"It is invalid because every logarithm base must exceed one",feedback:"Bases between zero and one are valid and occur in decay relationships."},{id:"negative",label:"It is treated as a negative base",feedback:"A reciprocal of a positive number remains positive."}])],hints:["Use change of base: ln(argument)/ln(1/b).", "The denominator is -ln(b), so its negative sign multiplies the whole quotient.","Compare the positive argument with one. A reciprocal base reverses the logarithm's sign relative to a base above one."],explanation:["The base 1/"+b+" lies strictly between zero and one, so it is valid.","Because ln(1/"+b+")=-ln("+b+"), K=-1 and the exact value is "+value+".","The argument "+argument+" is "+(u===v?"equal to":u<v?"below":"above")+" one. With this reciprocal base, the logarithm is "+sign+"."],answerSummary:"K=-1; exact value "+value+"; sign "+sign+"; the base is positive and different from one."});
}
