import { questionSchema,type Question } from "../contracts";
import { formatIntervals,type Interval } from "../intervals";
import { formatRational,parseRational } from "../rational";
import { inversePowerLatex,inverseRootLatex,powerFunctionLatex,powerFunctionRange,powerFunctionSchema,rootFunctionLatex,rootFunctionRange,rootFunctionSchema,type RootDegree } from "../radical-functions";
import { randomFrom } from "../random";

export const radicalAuditFamilyIds=["mth-radical-audit"] as const;
const variants=["wrong-branch","unrestricted-power","inverse-domain","one-composition","principal-sign","absolute-value","reciprocal-confusion","extraneous-candidate"];
const r=(source:string)=>formatRational(parseRational(source));
const number=(id:string,label:string,expected:string)=>({id,label,kind:"rational",expected:r(expected)});
const interval=(id:string,label:string,expected:Interval[])=>({id,label,kind:"intervals",expected,help:"Use complete interval notation with the correct included endpoints."});
const roots=(id:string,label:string,expected:string[])=>({id,label,kind:"roots",numberSystem:"real",expected,help:"List all distinct real values, separated by commas, or type empty."});
const half=(endpoint:number,right:boolean):Interval[]=>[{lower:right?String(endpoint):null,upper:right?null:String(endpoint),lowerClosed:right,upperClosed:!right}];
const compositionOptions=[{id:"identity",label:"Identity for every allowed inner input",feedback:"Both the intermediate input and the final identity must be valid over the entire stated inner domain."},{id:"blocked",label:"Some allowed inner inputs produce an undefined composition",feedback:"A formula may simplify to x while an intermediate value is outside the next function's stated domain."},{id:"folded",label:"Defined, but folds two input sides onto one branch",feedback:"A principal even root produces an absolute value; it cannot recover both original sides."},{id:"reflected",label:"Defined, but returns 2h - x away from the turning input",feedback:"Using the opposite root branch reflects the recovered original input about h."}];
const pairOptions=[{id:"yes",label:"Yes",feedback:"Both composition identities must hold on their full respective domains."},{id:"no",label:"No",feedback:"A failed identity or intermediate-domain condition prevents an inverse pair, even if one point or one composition works."}];
export function radicalAuditQuestion(familyId:string,variant:string,seed:string,id:string):Question{
  if(familyId!=="mth-radical-audit")throw new Error("Unknown radical audit family");
  const rng=randomFrom(seed);if(variant==="mixed")variant=variants[rng.integer(0,variants.length-1)];const mode=variants.indexOf(variant);if(mode<0)throw new Error("Unknown radical audit variant");
  const degree:RootDegree=mode===6||mode===7?2:rng.integer(0,1)?2:4,side=mode===5?-1:rng.integer(0,1)?1:-1,a=(mode===6?1:rng.integer(0,1)?1:-1)*rng.integer(1,3),b=(rng.integer(0,1)?1:-1)*rng.integer(1,3),h=mode===6?-rng.integer(0,3):rng.integer(-4,4),k=mode===6?rng.integer(1,4):rng.integer(-4,4),d=rng.integer(1,3);
  const base={id,familyId,familyVersion:1,courseId:"mth-215",objectiveId:"m04-l04",critical:true,category:"conceptual",parameters:{mode,degree,side,a,b,h,k,d}};
  const choice=(id:string,label:string,correct:string,options:typeof compositionOptions)=>({id,label,kind:"choice",correct,options:rng.shuffle(options)});
  const pair=(correct:string)=>choice("pair","Inverse pair on the stated domains?",correct,pairOptions);
  if(mode===7){
    const offset=d*(d+1),low=h-d,high=h+d+1;
    return questionSchema.parse({...base,category:"procedural",prompt:"Audit $\\sqrt{x-("+h+")+("+offset+")}=x-("+h+")$. State where the radical is real and where the right side is nonnegative. List all candidates obtained by squaring, the solutions of the original equation, and the rejected candidates. Identify why the rejected candidate fails.",fields:[interval("domain","Radical's real domain",half(h-offset,true)),interval("sign","Inputs satisfying the right-side sign condition",half(h,true)),roots("candidates","All candidates after squaring",[String(low),String(high)]),roots("solutions","Solutions of the original equation",[String(high)]),roots("rejected","Rejected candidates",[String(low)]),choice("reason","Reason the rejected candidate fails","negative-side",[{id:"negative-side",label:"A nonnegative principal root cannot equal its negative right side",feedback:"The radical is real at this candidate, but the two sides have opposite signs."},{id:"negative-radicand",label:"Its radicand is negative",feedback:"Both squared candidates have nonnegative radicands here; check the other side's sign."},{id:"both",label:"Both candidates satisfy the original equation",feedback:"Squaring can erase a sign distinction. Substitute into the original equation."}])],hints:["Set t=x-("+h+"). The equation becomes sqrt(t+"+offset+")=t, so the right side must be nonnegative.","Squaring gives t^2-t-"+offset+"=0, which factors as (t-("+(d+1)+"))(t+"+d+")=0.","The candidate t=-"+d+" has principal-root value "+d+" and right side -"+d+". Only t="+(d+1)+" survives."],explanation:["The radical's domain is "+formatIntervals(half(h-offset,true))+"; the additional right-side sign condition is "+formatIntervals(half(h,true))+".","Squaring produces x="+low+" and x="+high+".","At x="+low+", the principal root is "+d+" but the right side is -"+d+".","The only original-equation solution is "+high+". The rejected candidate was not outside the radical's real domain; it violated equality of the original signed sides."],answerSummary:"Candidates "+low+", "+high+"; retain "+high+"; reject "+low+" because its right side is negative."});
  }
  if(mode===4)return questionSchema.parse({...base,prompt:"A learner claims $\\sqrt["+degree+"]{(x-("+h+"))^{"+degree+"}}=x-("+h+")$ for every real x. Evaluate both sides at x="+(h-d)+", give the exact set of inputs where that equality holds, and choose the corrected identity on R. Here h="+h+".",fields:[number("root","Principal radical at the probe",String(d)),number("claimed","Claimed signed value at the probe",String(-d)),interval("equality","Inputs where the claimed equality holds",half(h,true)),choice("identity","Correct identity on all real inputs","absolute",[{id:"absolute",label:"The radical equals |x - h|",feedback:"The principal even root is nonnegative on both sides of h."},{id:"signed",label:"The radical equals x - h",feedback:"This is only true for x at least h."},{id:"negative",label:"The radical equals h - x",feedback:"This is only true for x at most h."}])],hints:["The base x-h is -d at the given probe. Its even power is positive.","The principal even root recovers the magnitude, not the original negative sign.","The equality |x-h|=x-h holds precisely when x is at least h."],explanation:["At the probe the principal radical equals "+d+", while the claimed value is -"+d+".","The general identity is the radical equal to |x-h|.","The learner's signed formula is correct only on "+formatIntervals(half(h,true))+"."],answerSummary:"Actual "+d+"; claimed -"+d+"; equality set "+formatIntervals(half(h,true))+"; corrected identity |x-h|."});
  if(mode===2){
    const model=rootFunctionSchema.parse({degree,transform:{a:String(a),b:String(b),h:String(h),k:String(k)}}),probe=k-a*d,returned=k+a*d,domain=rootFunctionRange(model);
    return questionSchema.parse({...base,prompt:"Let $f(x)="+rootFunctionLatex(model)+"$ on its full real domain. A learner writes the algebraic inverse formula $g(x)="+inverseRootLatex(model)+"$ but declares the domain of g to be R. Classify both compositions on their stated inner domains, compute f(g("+probe+")), and repair only g's domain while keeping f unchanged.",fields:[choice("fg","f after g on the stated domain of g","folded",compositionOptions),choice("gf","g after f on the stated domain of f","identity",compositionOptions),number("returned","f(g("+probe+"))",String(returned)),interval("repair","Correct domain of g",domain),pair("no")],hints:["The inverse formula has even degree, so it can be evaluated on both sides of k; that does not make both sides valid inverse inputs.","For the selected probe, the isolated root would be -"+d+". Raising its even power loses the negative sign.","Applying f again returns "+returned+" rather than "+probe+". Restrict g to the original output range."],explanation:["The composition g after f recovers every original input.","The composition f after g folds inputs onto the original output side because the principal root returns a magnitude.","The given probe returns "+returned+", not "+probe+".","The repaired inverse domain is "+formatIntervals(domain)+". With the stated all-real domain, the claimed pair is not an inverse pair."],answerSummary:"f after g folds; g after f is identity; probe returns "+returned+"; repair domain "+formatIntervals(domain)+"; claimed pair fails."});
  }
  const model=powerFunctionSchema.parse({degree,a:String(a),h:String(h),k:String(k),branch:mode===1?"all":side>0?"right":"left"});
  if(mode===6){
    const target=a*d*d+k,inverse=h+d,denominator=a*(target-h)**2+k;
    return questionSchema.parse({...base,prompt:"For $f(x)="+powerFunctionLatex({...model,branch:"right"})+"$ on "+formatIntervals(half(h,true))+", compare the inverse function with the reciprocal. Evaluate $f^{-1}("+target+")$ and $1/f("+target+")$, give their complete domains, and decide whether the reciprocal is the inverse on these domains. The shift k is positive, so f has no zero on its domain.",fields:[number("inverse","Inverse-function value",String(inverse)),number("reciprocal","Reciprocal value","1/"+denominator),interval("inverse-domain","Inverse-function domain",half(k,true)),interval("reciprocal-domain","Reciprocal-function domain",half(h,true)),choice("same","Is the reciprocal the inverse?","no",pairOptions)],hints:["The inverse recovers the original input that produces the requested output.","The reciprocal evaluates f at the argument first, then divides one by that output.","The inverse domain is f's range. The reciprocal domain is f's original domain with any f zeros removed; here there are no such zeros."],explanation:["The inverse value is "+inverse+".","The reciprocal value is 1/"+denominator+", because f at the same argument equals "+denominator+".","The inverse domain is "+formatIntervals(half(k,true))+" and the reciprocal domain is "+formatIntervals(half(h,true))+".","The values differ at this shared input. The superscript -1 in inverse-function notation does not mean taking a reciprocal."],answerSummary:"Inverse "+inverse+"; reciprocal 1/"+denominator+"; domains "+formatIntervals(half(k,true))+" and "+formatIntervals(half(h,true))+"; different functions."});
  }
  if(mode===3){
    const cut=k+a*d**degree,restricted=half(cut,a>0),repair=powerFunctionRange(model);
    return questionSchema.parse({...base,prompt:"Let $f(x)="+powerFunctionLatex(model)+"$ on "+formatIntervals(half(h,side>0))+". Its matching inverse formula is $g(x)="+inversePowerLatex(model)+"$, but g is assigned only the smaller domain "+formatIntervals(restricted)+". A learner checks f(g(x)) on that smaller domain and calls this an inverse pair. Classify both compositions, test whether g(f("+h+")) exists, and repair only g's domain.",fields:[choice("fg","f after g on the stated domain of g","identity",compositionOptions),choice("gf","g after f on the stated domain of f","blocked",compositionOptions),choice("center","Does g(f("+h+")) exist?","no",[{id:"yes",label:"Yes",feedback:"The inner output is k, which is missing from the narrowed g domain."},{id:"no",label:"No",feedback:"The original turning input is allowed, but its output is not accepted by this g."}]),interval("repair","Correct full domain of g",repair),pair("no")],hints:["A valid inverse formula can still have an incorrect domain.","At the original turning input h, f(h)=k. Compare k with the declared narrower domain of g.","To leave f unchanged, expand g's domain to all of f's range. Passing only f after g does not check this requirement."],explanation:["f after g is the identity on the narrowed g domain.","g after f is undefined at allowed original inputs whose outputs were removed from that domain, including h.","The correct full inverse domain is "+formatIntervals(repair)+".","The pair as stated fails. Both identities must hold over the appropriate entire domains."],answerSummary:"f after g identity; g after f partly blocked; center composition undefined; repair "+formatIntervals(repair)+"; not an inverse pair as stated."});
  }
  const candidate={...model,branch:mode===0?(side>0?"left" as const:"right" as const):side>0?"right" as const:"left" as const},probe=mode===1?h-side*d:h+side*d,returned=mode===1?h+side*d:mode===0?h-side*d:probe;
  const prompt="Let $f(x)="+powerFunctionLatex(model)+"$ on "+formatIntervals(mode===1?[{lower:null,upper:null,lowerClosed:false,upperClosed:false}]:half(h,side>0))+", and $g(x)="+inversePowerLatex(candidate)+"$ on "+formatIntervals(powerFunctionRange(model))+". Classify both compositions on their full stated inner domains, compute g(f("+probe+")), and decide whether these functions are inverses. Here h="+h+".";
  const fg=mode===0?"blocked":"identity",gf=mode===0?"reflected":mode===1?"folded":"identity";
  const extra=mode===1?[interval("repair","Restricted domain of f that makes this g its inverse",half(h,side>0))]:mode===5?[choice("absolute","On the stated original branch, |x - h| equals","left",[{id:"left",label:"h - x",feedback:"On the left branch x-h is nonpositive, so its magnitude is h-x."},{id:"right",label:"x - h",feedback:"That simplification belongs to the right branch."},{id:"zero",label:"0 for every input",feedback:"The magnitude is zero only at the turning input."}])]:[number("turning","g(f("+h+"))",String(h))];
  return questionSchema.parse({...base,prompt,fields:[choice("fg","f after g on the stated domain of g",fg,compositionOptions),choice("gf","g after f on the stated domain of f",gf,compositionOptions),number("returned","g(f("+probe+"))",String(returned)),...extra,pair(mode===5?"yes":"no")],hints:["First check that each inner output is accepted by the outer function's stated domain.","Taking a principal even root of (x-h) to that even power gives |x-h|.",mode===5?"On x<=h, |x-h|=h-x. The matching negative root branch therefore recovers x.":mode===1?"An unrestricted even power repeats outputs. The chosen g can recover only one original side.":"The opposite root branch returns 2h-x instead of x away from the turning input."],explanation:[mode===0?"Except at its endpoint, g returns inputs outside f's declared branch, so f after g is blocked there.":"f after g recovers each input from the stated domain of g.",mode===0?"g after f equals 2h-x on the original branch, rather than x except at h.":mode===1?"g after f folds both original sides onto the one branch selected by g.":"The left-branch condition makes h-|x-h|=x, so g after f is also the identity.","At the selected original input, g after f returns "+returned+".",mode===5?"Both identities and all domain requirements hold, so the pair is valid.":"The pair is not an inverse pair on its stated domains. Agreement at a boundary or one composition alone is insufficient."],answerSummary:"f after g: "+fg+"; g after f: "+gf+"; probe returns "+returned+"; inverse pair "+(mode===5?"yes":"no")+"."});
}
