import { questionSchema,type Question } from "../contracts";
import { formatIntervals,type Interval } from "../intervals";
import { formatRational,parseRational } from "../rational";
import { radicalRationalDomain,rootFunctionDomain,rootFunctionLatex,rootFunctionRange,rootFunctionSchema,type RootDegree } from "../radical-functions";
import { randomFrom } from "../random";

export const radicalDomainFamilyIds=["mth-radical-domain"] as const;
const variants=["linear-even","negative-inner","negative-outer","odd-root","fourth-root","rational-radicand","denominator-root","canceled-hole"];
const interval=(id:string,label:string,expected:Interval[])=>({id,label,kind:"intervals",expected,help:"Use interval notation; R means all real numbers. Preserve excluded inputs."});
const roots=(id:string,label:string,expected:string[])=>({id,label,kind:"roots",numberSystem:"real",expected,help:"List every distinct input, separated by commas, or type empty."});
const statusOptions=[{id:"defined",label:"Defined as a real value",feedback:"The original denominator and the root's real-domain condition must both hold."},{id:"undefined",label:"Undefined in the original real expression",feedback:"Check original denominator zeros, even-root signs, and a zero root in a denominator separately."}];
const conditionOptions=[{id:"nonnegative",label:"Radicand at least zero",feedback:"An even root in a numerator includes a zero radicand."},{id:"positive",label:"Radicand strictly positive",feedback:"An even root in a denominator must be real and nonzero."},{id:"all",label:"Any defined real radicand",feedback:"Odd roots allow negative, zero and positive radicands unless the root is a denominator."},{id:"nonzero",label:"Any defined nonzero real radicand",feedback:"An odd denominator root may be negative but cannot equal zero."}];
const r=(source:string)=>formatRational(parseRational(source));
export function radicalDomainQuestion(familyId:string,variant:string,seed:string,id:string):Question{
  if(familyId!=="mth-radical-domain")throw new Error("Unknown radical domain family");
  const rng=randomFrom(seed);if(variant==="mixed")variant=variants[rng.integer(0,variants.length-1)];const mode=variants.indexOf(variant);if(mode<0)throw new Error("Unknown radical domain variant");
  const direction=rng.integer(0,1)?1:-1,h=rng.integer(-5,5),k=rng.integer(-5,5),magnitude=rng.integer(1,4),inner=rng.integer(1,4),flag=rng.integer(0,1);
  const base={id,familyId,familyVersion:1,courseId:"mth-215",objectiveId:"m04-l04",critical:true,category:"conceptual"};
  if(mode<5){
    const degree:RootDegree=mode===3?(flag?3:5):mode===4?4:2;
    const a=(mode===2?-1:mode===0?1:direction)*magnitude,b=(mode===1?-1:mode===0?1:flag?1:-1)*inner;
    const t=degree%2?direction*2:2,anchor=r(h+"+("+t+")^("+degree+")/("+b+")"),output=a*t+k,probe=flag?h:h-Math.sign(b),valid=degree%2===1||flag===1;
    const model=rootFunctionSchema.parse({degree,transform:{a:String(a),b:String(b),h:String(h),k:String(k)}}),domain=rootFunctionDomain(model),range=rootFunctionRange(model);
    return questionSchema.parse({...base,parameters:{mode,degree,a,b,h,k,t,probe,flag},prompt:"For the real function $f(x)="+rootFunctionLatex(model)+"$, give the complete domain and range, evaluate f("+anchor+") exactly, and classify the separate input x="+probe+". The even-root symbol denotes its principal nonnegative root before the outside transformation.",fields:[interval("domain","Domain of f",domain),interval("range","Range of f",range),{id:"output",label:"Exact output at x = "+anchor,kind:"rational",expected:String(output)},{id:"probe",label:"Status at x = "+probe,kind:"choice",correct:valid?"defined":"undefined",options:rng.shuffle(statusOptions)}],hints:[degree%2?"An odd root accepts every real radicand, including negative values.":"For an even root, require the whole inside expression b(x-h) to be at least zero. Reverse the inequality when dividing by a negative b.","Determine the range from the principal root's outputs and the outside multiplier a and shift k; a horizontal reflection does not itself reverse the output range.","At the supplied exact evaluation input, the radicand is "+t**degree+". Its principal real root is "+t+". Check the separate probe in the original radicand."],explanation:["The domain is "+formatIntervals(domain)+" and the range is "+formatIntervals(range)+".","At x="+anchor+", the inner expression is "+t**degree+"; the transformed output is "+a+"("+t+")+("+k+")="+output+".",valid?"The separate probe satisfies the real-root condition. A zero radicand is allowed here because the root is not in a denominator.":"The separate probe gives a negative radicand for an even root, so it has no real output.","The inside scale controls admissible inputs; the outside scale controls the output direction."],answerSummary:"Domain "+formatIntervals(domain)+"; range "+formatIntervals(range)+"; output "+output+"; probe "+(valid?"defined":"undefined")+"."});
  }
  const left=rng.integer(-5,2),right=left+rng.integer(1,5),sign=direction,denominator=mode===6;
  const degree:RootDegree=mode===7?(flag?2:4):mode===6?([2,3,4,5] as const)[rng.integer(0,3)]:flag?2:3;
  const hole=mode===7?right+sign*rng.integer(1,4):left,probeMode=rng.integer(0,3),probe=mode===7?hole:probeMode===0?left:probeMode===1?right:probeMode===2?(left+right)/2:right+1;
  const expression=mode===7?"(("+sign+")*(x-("+hole+"))*(x-("+right+")))/(x-("+hole+"))":"(("+sign+")*(x-("+right+")))/(x-("+left+"))";
  const numerator=mode===7?"("+sign+")(x-("+hole+"))(x-("+right+"))":"("+sign+")(x-("+right+"))",radicand="\\frac{"+numerator+"}{x-("+hole+")}",root="\\sqrt"+(degree===2?"":"["+degree+"]")+"{"+radicand+"}",formula=denominator?"\\frac{1}{"+root+"}":root;
  const domain=radicalRationalDomain(expression,degree,denominator),condition=degree%2?(denominator?"nonzero":"all"):(denominator?"positive":"nonnegative");
  const raw=probe===hole?null:mode===7?sign*(probe-right):sign*(probe-right)/(probe-left),valid=raw!==null&&(degree%2===1||raw>=0)&&(!denominator||raw!==0);
  const fields=[interval("domain","Complete original domain",domain),roots("excluded","Original rational-denominator exclusions",[String(hole)]),{id:"condition",label:"Condition on the already-defined radicand",kind:"choice",correct:condition,options:rng.shuffle(conditionOptions)},...(denominator?[roots("zero-root","Inputs where a defined root is zero",[String(right)])]:[]),{id:"probe",label:"Status at x = "+probe,kind:"choice",correct:valid?"defined":"undefined",options:rng.shuffle(statusOptions)}];
  return questionSchema.parse({...base,parameters:{mode,degree,left,right,sign,hole,probeMode,probe},prompt:"Find the complete real domain of $f(x)="+formula+"$. State the original rational-denominator exclusions before simplifying, choose the root condition, "+(denominator?"list inputs where a defined root is zero, ":"")+"and classify x="+probe+" in the original formula."+(mode===7?" A common factor appears in the radicand, but the original expression still determines its domain.":""),fields,hints:["First record the original rational denominator's zero at x="+hole+". Cancellation cannot restore that input.",degree%2?denominator?"An odd root can be negative. As a denominator, however, it cannot be zero.":"An odd root accepts every real value of a defined radicand.":denominator?"An even denominator root requires a strictly positive radicand.":"An even numerator root requires a nonnegative radicand. Include allowed numerator zeros.","Use the sign intervals and the original exclusions together. A zero radicand and an undefined radicand are different conditions."],explanation:["The original rational denominator excludes x="+hole+".","The condition on its defined radicand is "+conditionOptions.find(option=>option.id===condition)!.label.toLowerCase()+".",mode===7?"The canceled factor leaves the signed linear radicand, but x="+hole+" remains missing from its allowed half-line.":"The radicand changes sign across its zero at "+right+" and excluded input at "+left+"; root parity determines which signs are permitted.","The complete domain is "+formatIntervals(domain)+".",...(denominator?["At x="+right+", the radicand is defined and zero, so the denominator root is zero and the reciprocal is undefined."]:[]),"The probe x="+probe+" is "+(valid?"defined":"undefined")+" in the original real formula."],answerSummary:"Domain "+formatIntervals(domain)+"; original exclusion "+hole+"; radicand condition "+condition+"; probe "+(valid?"defined":"undefined")+"."});
}
