import { questionSchema,type Question } from "../contracts";
import { formatRational,parseRational } from "../rational";
import { randomFrom } from "../random";
import { variationOutput,variationScale,type VariationRule } from "../variation";

export const jointVariationFamilyIds=["mth-joint-variation"] as const;
const r=(source:string)=>formatRational(parseRational(source));
const exact=(id:string,label:string,expected:string)=>({id,label,kind:"rational",expected:r(expected)});
export function jointVariationQuestion(familyId:string,variant:string,seed:string,id:string):Question{
  if(familyId!=="mth-joint-variation")throw new Error("Unknown joint variation family");
  const rng=randomFrom(seed),variants=["product","combined","powered-combination","simultaneous-scales","canceling-scales","solve-parameter","root-power"];
  if(variant==="mixed")variant=variants[rng.integer(0,variants.length-1)];const mode=variants.indexOf(variant);if(mode<0)throw new Error("Unknown joint variation variant");
  const a=rng.integer(1,4),b=a+rng.integer(1,4),c=rng.integer(1,4),d=c+rng.integer(1,3),kn=rng.integer(1,6),kd=rng.integer(1,3),k=r(kn+"/"+kd),sx=rng.integer(2,4),sz=mode===4?sx:rng.integer(2,4);
  const p=mode===2||mode===3||mode===5||mode===6?2:1,q=mode===0?1:mode===2?-3:-1,qd=mode===6?3:1;
  const rule:VariationRule={xPower:{numerator:p,denominator:1},zPower:{numerator:q,denominator:qd}};
  const baseline={x:String(a),z:String(mode===6?c**3:c)},changed={x:String(mode===3||mode===4?a*sx:b),z:String(mode===6?d**3:mode===3||mode===4?c*sz:d)};
  const y=variationOutput(rule,k,baseline).exact!,next=variationOutput(rule,k,changed).exact!,factor=variationScale(rule,baseline,changed).exact!;
  const words=mode===0?"jointly with x and z":mode===1||mode===4?"directly with x and inversely with z":mode===2?"directly with the square of x and inversely with the cube of z":mode===6?"directly with the square of x and inversely with the cube root of z":"directly with the square of x and inversely with z";
  const base={id,familyId,familyVersion:1,courseId:"mth-215",objectiveId:"m04-l03",critical:true,category:"procedural",parameters:{mode,a,b,c,d,kn,kd,p,q,qd,sx,sz}};
  if(mode===3||mode===4)return questionSchema.parse({...base,category:"conceptual",prompt:"The positive response y varies "+words+". Initially x="+a+", z="+c+", and y="+y+". Keeping the coefficient and units unchanged, multiply x by "+sx+" and z by "+sz+". Predict each input's separate contribution to the output multiplier, combine them, and calculate the new response.",fields:[exact("x-factor","Multiplier contributed by the x change",String(sx**p)),exact("z-factor","Multiplier contributed by the z change","1/"+sz),exact("factor","Combined output multiplier",factor),exact("output","New response",next)],hints:["Raise the x scale factor to the direct power specified in the words.","Because z is in the denominator to the first power, its contribution is the reciprocal of its scale factor.","Multiply the separate contributions. Adding them does not describe a product or quotient model."],explanation:["The x change contributes "+sx**p+" and the z change contributes 1/"+sz+".","Their product is "+factor+", making the new response "+next+".",mode===4?"The equal direct and inverse scale factors cancel. Both inputs change even though the response stays unchanged.":"The direct square and inverse first power act together. Neither input's scale factor alone determines the output."],answerSummary:"Contributions "+sx**p+" and 1/"+sz+"; combined "+factor+"; response "+next+"."});
  if(mode===5)return questionSchema.parse({...base,category:"application",prompt:"A supplied positive-input model has y varying directly with the square of x and inversely with z. The calibration record is x="+a+", z="+c+", y="+y+". Recover the variation constant, then find the positive z that gives y="+next+" when x="+b+". Keep the original z restriction.",fields:[exact("constant","Variation constant k",k),exact("input","Required z input",String(d)),{id:"excluded",label:"Inputs excluded for z by the original formula",kind:"roots",numberSystem:"real",expected:["0"],help:"List excluded real z inputs, separated by commas."}],hints:["Write y=kx^2/z and use the complete calibration observation to obtain k=yz/x^2.","At the new x and target y, isolate z=kx^2/y. Check that the target y is nonzero.","The resulting positive z must still satisfy the original denominator restriction z different from zero."],explanation:["The observation gives k="+k+".","Substituting x="+b+" and the target response gives z="+d+".","This input is positive and nonzero, so it is allowed by the supplied model. Zero remains an excluded z input."],answerSummary:"k="+k+"; z="+d+"; exclude z=0."});
  return questionSchema.parse({...base,prompt:"The response y varies "+words+" for positive x and z. An exact observation is x="+baseline.x+", z="+baseline.z+", y="+y+". Write its structure as $y=kx^p z^q$, find k, and predict the response at x="+changed.x+", z="+changed.z+". Both inputs use the same units as the calibration record.",fields:[exact("power-x","Exponent p of x",String(p)),exact("power-z","Exponent q of z",q+"/"+qd),exact("constant","Variation constant k",k),exact("output","Predicted response",next),exact("factor","Output multiplier from the calibration record",factor)],hints:["Translate each direct power into a positive exponent and each inverse power into a negative exponent.",mode===6?"The inverse cube root is z raised to -1/3. Both listed z inputs are perfect cubes, so their roots can be kept exact.":"Use all input factors in the calibration equation. Joint variation uses one constant multiplying the whole product or quotient.","Find k from the baseline, then substitute both changed inputs. Check using (new x / old x)^p times (new z / old z)^q."],explanation:["The exponents are p="+p+" and q="+r(q+"/"+qd)+".","The full calibration observation gives k="+k+".","Changing both inputs produces output "+next+", which is "+factor+" times the original response.","A product or quotient of contributions must be combined multiplicatively. Replacing it with a sum changes the model."],answerSummary:"p="+p+", q="+r(q+"/"+qd)+", k="+k+", response "+next+", multiplier "+factor+"."});
}
