import { questionSchema,type Question } from "../contracts";
import { logarithmDomain } from "../logarithm-domains";
import { logarithmicFunctionSchema,logarithmFeatures,logarithmLatex } from "../logarithmic-functions";
import { formatIntervals,parseIntervals } from "../intervals";
import { formatRational,parseRational } from "../rational";
import { rationalLatex } from "../transformations";
import { randomFrom } from "../random";

export const logAuditFamilyIds=["mth-log-audit"] as const;
const variants=["invalid-argument","invalid-base","division-confusion","negative-output","boundary-inclusion","composition-domain","canceled-restriction","rounded-boundary","operating-window"];
const r=(source:string)=>formatRational(parseRational(source));
const number=(id:string,label:string,expected:string)=>({id,label,kind:"rational",expected:r(expected),help:"Keep this answer exact. Use fractions rather than rounded decimals."});
const interval=(id:string,label:string,expected:string)=>({id,label,kind:"intervals",expected:parseIntervals(expected),help:"Use interval notation, U for a union, or R for all real inputs."});
export function logAuditQuestion(familyId:string,variant:string,seed:string,id:string):Question{
  if(familyId!=="mth-log-audit")throw new Error("Unknown logarithm audit family");
  const rng=randomFrom(seed);if(variant==="mixed")variant=variants[rng.integer(0,variants.length-1)];const mode=variants.indexOf(variant);if(mode<0)throw new Error("Unknown logarithm audit variant");
  const flag=rng.integer(0,2),b=rng.integer(2,5),p=-rng.integer(1,4),h=rng.shuffle([-4,-2,-1,1,2,4])[0],c=(flag%2?-1:1)*rng.integer(1,3),a=(rng.integer(0,1)?-1:1)*rng.integer(1,4),k=rng.integer(-4,4),u=rng.integer(1,3),digits=rng.integer(4,9),bn=(mode===3||mode===8)&&flag%2?1:b,bd=(mode===3||mode===8)&&flag%2?b:1,baseValue=r(bn+"/"+bd),argument=r("("+baseValue+")^("+p+")"),domain=c>0?"("+h+",inf)":"(-inf,"+h+")";
  const base={id,familyId,familyVersion:1,courseId:"mth-215",objectiveId:"m05-l02",critical:true,category:"conceptual",parameters:{mode,flag,b,p,h,c,a,k,u,digits,bn,bd}};
  const choice=(id:string,label:string,correct:string,options:{id:string;label:string;feedback:string}[])=>({id,label,kind:"choice",correct,options:rng.shuffle(options)});
  const decision=(id:string,label:string,correct:boolean,yes:string,no:string)=>choice(id,label,correct?"yes":"no",[{id:"yes",label:"Yes",feedback:yes},{id:"no",label:"No",feedback:no}]);
  if(mode===0){
    const probe=flag===0?String(h):String(h-Math.sign(c)*u),raw=flag===0?"0":String(-Math.abs(c)*u),witness=r(h+"+1/("+c+")");
    return questionSchema.parse({...base,prompt:"A learner tries to evaluate $f(x)=\\ln(("+c+")(x-("+h+")))$ at x="+probe+". Calculate the complete argument before applying the logarithm, state the full domain, and decide whether the requested value is real. Also find the input where that argument equals one and its exact logarithm value.",
      fields:[number("argument","Argument at the requested input",raw),interval("domain","Full real domain",domain),decision("valid","Is the requested logarithm real?",false,"A logarithm can be real only when its complete argument is strictly positive.","The computed nonpositive argument is outside the real logarithm domain."),number("witness","Input where the argument equals one",witness),number("witness-value","Function value at that valid input","0")],
      hints:["Evaluate the entire product c*(x-h), keeping its sign.","Zero and negative logarithm arguments are excluded. This restriction is on the argument, not the output.","Solve c*(x-h)=1 and use ln(1)=0 for a valid comparison point."],
      explanation:["At x="+probe+" the complete argument is "+raw+", so the requested real logarithm is undefined.","The positivity condition gives domain "+formatIntervals(parseIntervals(domain))+".","At x="+witness+" the argument equals one and the function value is zero. A zero logarithm output is allowed."],
      answerSummary:"Argument "+raw+"; domain "+domain+"; requested value not real; valid comparison input "+witness+" gives output 0."});
  }
  if(mode===1){
    const invalid=flag===0?"0":flag===1?"1":String(-b),reason=flag===1?"one":"nonpositive";
    return questionSchema.parse({...base,prompt:"A learner proposes "+invalid+" as the base of a real logarithm with positive argument "+b*b+". Identify the failed base condition and decide whether this defines a real logarithm function. Then replace the base with "+b+" and evaluate the repaired logarithm exactly.",
      fields:[number("argument","Proposed positive argument",String(b*b)),choice("reason","Which base condition fails?",reason,[{id:"nonpositive",label:"The base is not strictly positive",feedback:"A real logarithm is the inverse of a positive-base exponential defined for every real exponent."},{id:"one",label:"The base equals one",feedback:"The exponential with base one is constant and has no one-to-one inverse."},{id:"none",label:"No base condition fails",feedback:"A valid real logarithm needs a base greater than zero and different from one."}]),decision("valid","Does this define a real logarithm function?",false,"A positive argument cannot repair an invalid logarithm base.","The base itself must satisfy both restrictions."),number("repaired","Logarithm after replacing the base", "2")],
      hints:["Check b>0 and b!=1 separately from argument positivity.","For base one, every exponent produces one. An isolated integer power of a negative base does not define a real exponential for every real exponent.","The repaired argument is the square of the repaired base."],
      explanation:[flag===1?"Base one produces a constant exponential, so its outputs do not determine a unique exponent.":"The proposed base is nonpositive. It cannot support the required real logarithm function.","The argument "+b*b+" is positive, but that fact does not change the failed base condition.","After changing the base to "+b+", the logarithm equals two because "+b+"^2="+b*b+"."],
      answerSummary:"Argument "+b*b+"; failed base condition "+reason+"; invalid logarithm function; repaired value 2."});
  }
  if(mode===2){
    const quotient=r("("+argument+")/"+b);
    return questionSchema.parse({...base,prompt:"A learner evaluates $\\log_{"+b+"}("+rationalLatex(argument)+")$ by dividing the argument by the base. Calculate that proposed quotient and the actual logarithm, reconstruct the power of the base using your logarithm answer, and assess the claimed division rule.",
      fields:[number("quotient","Proposed argument divided by base",quotient),number("logarithm","Actual logarithm",String(p)),number("power","Base raised to the logarithm answer",argument),decision("rule","Is the proposed division rule valid here?",false,"Dividing the argument by the base does not recover the exponent.","The quotient and the actual logarithm differ, even in sign here.")],
      hints:["Compute the proposed quotient exactly as written.","Rewrite the positive argument as a reciprocal power of the base.","The actual logarithm is that exponent, and raising the base to it returns the original argument."],
      explanation:["The proposed quotient is "+quotient+", which is positive.","The actual logarithm is "+p+", because "+b+"^("+p+")="+argument+".","Reconstructing the power returns "+argument+". The logarithm recovers an exponent, so the division rule is false."],
      answerSummary:"Quotient "+quotient+"; logarithm "+p+"; reconstructed power "+argument+"; division rule false."});
  }
  if(mode===3)return questionSchema.parse({...base,prompt:"A learner rejects $\\log_{"+rationalLatex(baseValue)+"}("+rationalLatex(argument)+")="+p+"$ because the proposed output is negative. Check the argument by computing the base to this exponent, give the logarithm, and state the parent logarithm's domain and range. Decide whether the negative answer is valid.",
    fields:[number("argument","Reconstructed positive argument",argument),number("value","Actual logarithm",String(p)),interval("domain","Parent logarithm domain","(0,inf)"),interval("range","Parent logarithm range","R"),decision("valid","Is the negative logarithm answer valid?",true,"The argument is positive and the valid base raised to this exponent gives that argument.","A negative output is permitted; positivity restricts the argument instead.")],
    hints:["Check the whole fraction used as the base before evaluating its negative power.","A negative exponent means a reciprocal power, whose value stays positive.","Every valid parent logarithm has positive inputs and all-real outputs, including negative outputs."],
    explanation:["The exact power is ("+baseValue+")^("+p+")="+argument+">0, establishing the logarithm value "+p+".","The domain is (0, inf) and the range is R.","The rejection confuses a forbidden negative argument with a valid negative output. The proposed answer is valid."],
    answerSummary:"Argument "+argument+"; logarithm "+p+"; domain (0,inf); range R; negative output valid."});
  if(mode===4){
    const model=logarithmicFunctionSchema.parse({kind:"rational-base",base:String(b),a:String(a),c:String(c),h:String(h),k:String(k)}),features=logarithmFeatures(model);
    return questionSchema.parse({...base,prompt:"A learner includes the boundary x="+h+" in the domain of $g(x)="+logarithmLatex(model)+"$ because the inside affine expression has a value there. Correct the domain and range, compute that boundary argument, give the input and output where the argument is one, and assess the boundary-inclusion claim.",
      fields:[interval("domain","Correct domain",domain),interval("range","Complete range","R"),number("boundary-argument","Logarithm argument at the proposed boundary","0"),number("anchor-x","Input where the argument equals one",features.anchor.x),number("anchor-y","Output at that valid input",String(k)),decision("include","Can the boundary be included?",false,"Evaluating the affine expression does not make its zero value a valid logarithm argument.","The logarithm requires a strictly positive argument, so this boundary is excluded.")],
      hints:["The inside affine expression is defined everywhere, but the outside logarithm adds a stricter condition.","Substitution at x=h makes the argument zero.","The argument-one anchor is at x=h+1/c, where the logarithm contributes zero to the full output."],
      explanation:["The domain is "+formatIntervals(features.domain)+", with boundary x="+h+" excluded. The range is R.","At that boundary the logarithm argument is zero, so no finite real logarithm value exists.","The valid anchor is ("+features.anchor.x+", "+k+"). A zero logarithm output at argument one does not justify taking a logarithm of zero."],
      answerSummary:"Domain "+domain+"; range R; boundary argument 0; anchor ("+features.anchor.x+", "+k+"); boundary excluded."});
  }
  if(mode===5)return questionSchema.parse({...base,prompt:"Compare $L(t)=\\log_{"+b+"}("+b+"^t)$ and $E(x)="+b+"^{\\log_{"+b+"}(x)}$. Give each complete real domain, evaluate L("+p+"), and assess whether replacing E(x) by x permits using the original E at x="+p+" or x=0.",
    fields:[interval("first-domain","Domain of L","R"),interval("second-domain","Domain of the original E","(0,inf)"),number("first-value","Value of L at the supplied negative input",String(p)),decision("negative","Is the negative input allowed in original E?",false,"Its inner logarithm is not real at a negative argument.","The unsimplified inner logarithm still requires a positive argument."),decision("zero","Is zero allowed in original E?",false,"No finite logarithm of zero exists.","The original domain excludes zero even though the standalone identity function accepts it.")],
    hints:["For L, every real exponent produces a positive exponential value before the logarithm is applied.","For E, the inner logarithm is evaluated first and requires x>0.","An inverse identity holds on the original composition's domain. It does not add new inputs after simplification."],
    explanation:["L has domain R and satisfies L(t)=t there, giving L("+p+")="+p+".","The original E has domain (0, inf), and E(x)=x only on that domain.","The separate identity function accepts negative numbers and zero, but substituting it does not restore those excluded inputs to the original composition."],
    answerSummary:"L domain R; E domain (0,inf); L("+p+")="+p+"; negative and zero inputs excluded from original E."});
  if(mode===6){
    const width=b**u,hole=h+width,expression="((x-("+hole+"))*(x-("+h+")))/(x-("+hole+"))",original=logarithmDomain(expression),simplified=r(String(width));
    return questionSchema.parse({...base,prompt:"Consider $F(x)=\\log_{"+b+"}\\left(\\frac{(x-("+hole+"))(x-("+h+"))}{x-("+hole+")}\\right)$. A learner cancels the common factor and uses x="+hole+". State the original F domain, evaluate the simplified argument and simplified logarithm there, and determine whether these values restore the original input.",
      fields:[interval("domain","Original F domain",formatIntervals(original)),number("simplified-argument","Simplified argument at the canceled input",simplified),number("simplified-log","Value of the separately simplified logarithm",String(u)),choice("original","Original expression at the canceled input","undefined",[{id:"undefined",label:"Undefined",feedback:"The original inner fraction has a zero denominator at this input."},{id:"same",label:"Equal to the simplified logarithm",feedback:"The algebraic cancellation is valid only away from the original zero denominator."}]),decision("restore","Does cancellation restore this input to F?",false,"A separately extended formula does not change the domain of the original expression.","The canceled input must remain excluded from the original function.")],
      hints:["Record the original denominator exclusion before canceling.","Away from the hole, the inner expression equals x-h and must be positive.","The simplified logarithm can have a value at the hole while the original expression remains undefined."],
      explanation:["The original denominator excludes x="+hole+". Away from it, positivity requires x>"+h+". The full original domain is "+formatIntervals(original)+".","At x="+hole+" the simplified argument is "+simplified+"="+b+"^"+u+", so the separately simplified logarithm equals "+u+".","The original fraction is still undefined at that input. Cancellation preserves values only on the original domain and cannot restore its hole."],
      answerSummary:"Original domain "+formatIntervals(original)+"; simplified argument "+simplified+"; simplified log "+u+"; original undefined; input not restored."});
  }
  if(mode===8){
    const first=String(k+a),last=r(k+"+("+a+")*("+baseValue+")^"+u),probe=r(k+"+("+a+")/("+baseValue+")"),increasing=(a>0)===(bn>bd),operating="["+(increasing?first:last)+","+(increasing?last:first)+"]",fullDomain=a>0?"("+k+",inf)":"(-inf,"+k+")";
    return questionSchema.parse({...base,category:"application",prompt:"The response law $Y(t)="+k+"+("+a+")("+rationalLatex(baseValue)+")^t$ gives Y in volts; t is the numerical value of time in seconds. The model is authorized only for 0 through "+u+" seconds, including both endpoints. Its full-formula inverse is $G(y)=\\log_{"+rationalLatex(baseValue)+"}\\left(\\frac{y-("+k+")}{"+a+"}\\right)$. Distinguish the full inverse from the inverse restricted to the operating model. Evaluate the inverse at Y(0)="+first+", Y("+u+")="+last+", and the additional response y="+probe+".",
      fields:[interval("full-domain","Full inverse input domain (V)",fullDomain),interval("full-range","Full inverse output range (s)","R"),interval("operating-domain","Operating inverse input domain (V)",operating),interval("operating-range","Operating inverse output range (s)","[0,"+u+"]"),number("first-time","Inverse time at the first endpoint (s)","0"),number("last-time","Inverse time at the last endpoint (s)",String(u)),number("probe-time","Full-formula inverse time for the additional response (s)","-1"),decision("allowed","Is the additional response allowed by the operating inverse?",false,"A real value of the extended inverse does not enlarge the supplied operating model.","This response corresponds to time -1, outside the authorized time interval.")],
      hints:["Evaluate both included original time endpoints and order their response values using the monotonic direction.","The inverse exchanges input and output sets. Attained operating endpoints remain included even though the full inverse excludes its logarithm boundary.","For each response, subtract the original baseline and divide by its signed coefficient. Identify the exponent in that positive factor before interpreting the recovered time."],
      explanation:["The full inverse has domain "+fullDomain+" and range R. The response is "+(increasing?"increasing":"decreasing")+" on the supplied time interval.","The attained endpoint responses are "+first+" V and "+last+" V. The operating inverse therefore has input domain "+operating+" V and output range [0,"+u+"] s.","The endpoint inverse times are 0 and "+u+" seconds. Both are included because the original operating interval includes its endpoints.","At response "+probe+" V, the isolated exponential factor is the reciprocal of the base. The full-formula inverse gives -1 s, so this response is outside the authorized operating inverse."],
      answerSummary:"Full inverse domain "+fullDomain+" and range R; operating inverse domain "+operating+" and range [0,"+u+"]; endpoint times 0 and "+u+" s; additional response gives -1 s and is not allowed."});
  }
  const sign=Math.sign(c),small=r("1/(10^"+digits+")"),inside=r(h+"+("+sign+")*("+small+")"),outside=r(h+"-("+sign+")*("+small+")"),half=sign>0?"("+h+",inf)":"(-inf,"+h+")";
  return questionSchema.parse({...base,prompt:"For $F(x)=\\log_{10}(("+sign+")(x-("+h+")))$, compare the exact inputs x_in="+inside+" and x_out="+outside+". A display rounded to three decimal places shows "+h.toFixed(3)+" for both. Compute their exact logarithm arguments, evaluate F at the inside input, determine whether each input is allowed, and assess the exact boundary x="+h+".",
    fields:[number("inside-argument","Exact argument at x_in",small),number("inside-value","Exact F value at x_in",String(-digits)),decision("inside","Is x_in allowed?",true,"Its exact complete argument is positive, regardless of the rounded input display.","Exact subtraction gives a positive argument here."),number("outside-argument","Exact argument at x_out","-("+small+")"),decision("outside","Is x_out allowed?",false,"Its exact argument is negative despite the identical rounded display.","This exact input lies on the excluded side of the boundary."),interval("domain","Full exact domain",half),decision("boundary","Is the exact boundary input allowed?",false,"At the exact boundary the argument is zero.","A zero argument remains excluded; nearby positive arguments do not include the boundary.")],
    hints:["Subtract the exact boundary before rounding, and keep the sign of the inside coefficient.","The positive argument is a power of ten with a negative integer exponent.","Distinguish a point inside the domain, a point outside it, and the exact excluded boundary even if all display alike."],
    explanation:["The exact inside argument is "+small+"=10^(-"+digits+"), so F(x_in)=-"+digits+" and this input is allowed.","The exact outside argument is -("+small+"), so that real logarithm is undefined.","The domain is "+half+", excluding the exact boundary where the argument is zero. Rounding an input display does not change domain membership."],
    answerSummary:"Inside argument "+small+"; inside value "+(-digits)+"; inside allowed; outside argument -("+small+"); outside excluded; domain "+half+"; exact boundary excluded."});
}
