import { questionSchema,type Question } from "../contracts";
import { randomFrom } from "../random";
import { formatRational,parseRational } from "../rational";
import { rationalLatex } from "../transformations";

export const powerLevelFamilyIds=["mth-power-level"] as const;
const variants=["level-from-ratio","ratio-from-level","measured-power","changed-reference","level-difference","cascaded-gains","additive-powers","amplitude-condition","invalid-input"];
const rational=(id:string,label:string,expected:string,unit="")=>({id,label,kind:"rational",expected:formatRational(parseRational(expected)),unit});
const exact=(id:string,label:string,expected:string,unit="")=>({id,label,kind:"logarithmic",expected,unit});
const approximate=(id:string,label:string,expected:number,unit="")=>({id,label,kind:"numeric",expected,unit,absoluteTolerance:.00005,relativeTolerance:0,help:"Round only this numerical field to four decimal places."});
const log=(ratio:string)=>"10*log("+ratio+")";
export function powerLevelQuestion(familyId:string,variant:string,seed:string,id:string):Question{
  if(familyId!=="mth-power-level")throw new Error("Unknown power level family");
  const rng=randomFrom(seed);if(variant==="mixed")variant=variants[rng.integer(0,variants.length-1)];const mode=variants.indexOf(variant);if(mode<0)throw new Error("Unknown power level variant");
  const a=rng.integer(1,9),b=rng.integer(1,9),d=rng.integer(2,5),flag=rng.integer(0,5),level=rng.integer(-20,20);let c=rng.integer(1,9);
  if(mode===6&&a*b===c*(a+b))c++;
  const base={id,familyId,familyVersion:1,courseId:"mth-215",objectiveId:"m05-l04",critical:true,category:"application",parameters:{mode,a,b,c,d,flag,level}};
  const choice=(id:string,label:string,correct:string,options:{id:string;label:string;feedback:string}[])=>({id,label,kind:"choice",correct,options:rng.shuffle(options)});
  const signChoice=(value:number)=>choice("meaning","How does this power compare with the stated reference?",value<1?"below":value>1?"above":"equal",[{id:"below",label:"Positive power below the reference",feedback:"A negative power level can describe a strictly positive power smaller than its reference."},{id:"equal",label:"Power equals its positive reference",feedback:"A ratio of one has logarithm zero."},{id:"above",label:"Power above the reference",feedback:"A positive level corresponds to a ratio greater than one."},{id:"negative",label:"The power itself is negative",feedback:"The sign of a logarithmic level is not the sign of the measured power."}]);
  const rule="Use the supplied power-level formula $D=10\\log_{10}(P/P_{\\mathrm{ref}})$, with D expressed in dB. Both powers must be strictly positive and expressed in compatible units. ";
  if(mode===0)return questionSchema.parse({...base,prompt:rule+"The measured power is "+a+" W and the reference is "+1000*b+" mW. Form the dimensionless ratio, find the exact and rounded levels relative to this reference, and interpret the sign.",fields:[rational("reference","Reference converted to watts",String(b),"W"),rational("ratio","Dimensionless measured-to-reference power ratio",a+"/"+b),exact("level","Exact level relative to the stated reference",log(a+"/"+b),"dB"),approximate("rounded","Rounded level",10*Math.log10(a/b),"dB"),signChoice(a/b)],hints:["Use 1 W = 1000 mW before forming the ratio.","Divide measured power by reference power. Their units cancel.","Keep 10*log(ratio) exact; use a decimal only in the rounded field. Compare the positive ratio with one to interpret the sign."],explanation:["The reference is "+b+" W, so the dimensionless ratio is "+a+"/"+b+".","The exact referenced level is "+log(a+"/"+b)+" dB.","A ratio below, equal to, or above one produces a negative, zero, or positive level respectively. All the supplied powers remain positive."],answerSummary:"Reference "+b+" W; ratio "+a+"/"+b+"; level "+log(a+"/"+b)+" dB."});
  if(mode===1)return questionSchema.parse({...base,prompt:rule+"A power level of "+level+" dB is reported relative to "+b+" mW. Recover the exact and rounded dimensionless power ratio, state the reference in watts, and interpret what the ratio means.",fields:[exact("ratio","Exact power ratio","10^("+level+"/10)"),approximate("rounded","Rounded power ratio",10**(level/10)),rational("reference","Reference in watts",b+"/1000","W"),signChoice(10**(level/10))],hints:["Divide the numerical dB level by ten to isolate a base-10 logarithm.","Invert the logarithm with a power of ten. A negative exponent gives a positive reciprocal.","The ratio is independent of the unit used consistently for both powers; the reported reference must still be retained."],explanation:["The logarithm of the ratio is "+level+"/10, so the exact ratio is 10^("+level+"/10).","The reference is "+b+"/1000 W. The ratio is dimensionless and strictly positive.","Compare that ratio with one to interpret the level; do not mistake a negative level for a negative power."],answerSummary:"Power ratio 10^("+level+"/10); reference "+b+"/1000 W."});
  if(mode===2){
    const recoverReference=flag%2===1,ratio="10^("+level+"/10)",power=recoverReference?b+"/("+ratio+")":b+"*("+ratio+")";
    return questionSchema.parse({...base,prompt:rule+"The level is "+level+" dB. "+(recoverReference?"The measured power is "+b+" mW; recover the positive reference power.":"The reference is "+b+" mW; recover the measured power.")+" Give the dimensionless ratio, then the exact requested power in mW and W.",fields:[exact("ratio","Exact measured-to-reference power ratio",ratio),exact("power",recoverReference?"Exact reference power":"Exact measured power",power,"mW"),exact("watts","Requested power converted to watts","("+power+")/1000","W"),choice("operation","How is the requested power recovered?",recoverReference?"divide":"multiply",[{id:"multiply",label:"Multiply the known reference by the ratio",feedback:"P equals the dimensionless ratio times its reference."},{id:"divide",label:"Divide the known measured power by the ratio",feedback:"Solving P/P_ref = ratio for the reference gives P_ref = P/ratio."}])],hints:["First invert D/10 = log10(P/P_ref).","Write P = ratio * P_ref and identify which power is unknown.","Multiply or divide accordingly, then use 1000 mW = 1 W. Keep powers of ten exact."],explanation:["The dimensionless power ratio is "+ratio+".",recoverReference?"The known quantity is the numerator P, so divide it by the ratio to recover the reference.":"The known quantity is the reference denominator, so multiply it by the ratio to recover the measured power.","The requested power is "+power+" mW, or ("+power+")/1000 W. Substitution recovers the original ratio and level."],answerSummary:"Ratio "+ratio+"; requested power "+power+" mW."});
  }
  if(mode===3)return questionSchema.parse({...base,prompt:rule+"The measured power stays at "+a+" W. Change the reference from "+b+" W to "+b*d+" W. Find the old level, the new level, and new minus old, and decide whether the measured power changed.",fields:[exact("old","Old referenced level",log(a+"/"+b),"dB"),exact("new","New referenced level",log(a+"/"+(b*d)),"dB"),exact("change","New level minus old level","-10*log("+d+")","dB"),choice("physical","Did changing the reference change the measured power?","no",[{id:"no",label:"No, the same power has a different referenced level",feedback:"The measured power remains fixed; only the denominator used to report its level changes."},{id:"yes",label:"Yes, the measured power decreased",feedback:"A reporting reference does not change the supplied measured power."}])],hints:["Write one dimensionless ratio for each reference.","Subtract the old logarithmic level from the new one and combine as a quotient.","The two numerators cancel, leaving the old reference divided by the new reference."],explanation:["The old and new levels are "+log(a+"/"+b)+" and "+log(a+"/"+(b*d))+" dB, each relative to its own stated reference.","New minus old is 10*log(1/"+d+") = -10*log("+d+") dB.","The measured power stays "+a+" W. A larger reference lowers the reported level without changing that power."],answerSummary:"Old "+log(a+"/"+b)+"; new "+log(a+"/"+(b*d))+"; change -10*log("+d+") dB; power unchanged."});
  if(mode===4)return questionSchema.parse({...base,prompt:rule+"Two readings are P1="+a+" W and P2="+b+" W. Both reported levels use the same reference, "+c+" W. Give P2/P1, both referenced levels, and D2-D1. Decide whether that difference depends on the shared reference.",fields:[rational("ratio","Dimensionless P2/P1",b+"/"+a),exact("first","Level of P1",log(a+"/"+c),"dB"),exact("second","Level of P2",log(b+"/"+c),"dB"),exact("difference","D2 minus D1",log(b+"/"+a),"dB"),choice("reference","Does this difference depend on the shared reference?","no",[{id:"no",label:"No, the same reference cancels in the quotient",feedback:"Subtracting logarithms with the same reference gives 10*log10(P2/P1)."},{id:"yes",label:"Yes, every level difference depends on that reference",feedback:"Individual levels do depend on a reference, but their difference cancels a shared one."}])],hints:["Keep the order P2/P1 consistent with D2-D1.","Write each level with its supplied reference before subtracting.","Combine the difference as the logarithm of a quotient and cancel the common reference."],explanation:["The levels are D1="+log(a+"/"+c)+" and D2="+log(b+"/"+c)+" dB.","Their difference is 10*log(("+b+"/"+c+")/("+a+"/"+c+")) = "+log(b+"/"+a)+" dB.","The same reference cancels. Reversing the order of the readings would reverse the sign of the difference."],answerSummary:"Ratio "+b+"/"+a+"; D2-D1="+log(b+"/"+a)+" dB; shared reference cancels."});
  if(mode===5){
    const product="("+a+"/"+b+")*("+c+"/"+d+")";
    return questionSchema.parse({...base,prompt:rule+"Two successive stages have supplied power gain ratios G1="+a+"/"+b+" and G2="+c+"/"+d+". The supplied relation is P_out/P_in=G1*G2. Find the combined dimensionless gain, each stage's level difference, and the total output-to-input level difference.",fields:[rational("gain","Combined power gain",product),exact("first","First stage level difference",log(a+"/"+b),"dB"),exact("second","Second stage level difference",log(c+"/"+d),"dB"),exact("total","Total level difference",log(product),"dB"),choice("combine","Which operation combines these stage level differences?","add",[{id:"add",label:"Add the level differences because the power ratios multiply",feedback:"The logarithm of a positive product is the sum of its logarithms."},{id:"multiply",label:"Multiply the level differences",feedback:"Multiplication applies to the supplied gains, not to their logarithms."}])],hints:["Use the supplied multiplication law for the underlying power ratios.","Translate each positive gain with 10*log10(gain).","The product rule makes the total level difference the sum of the two stage differences."],explanation:["The net dimensionless gain is "+product+".","The stage differences are "+log(a+"/"+b)+" and "+log(c+"/"+d)+" dB.","Their sum equals "+log(product)+" dB. This addition follows from the explicitly supplied multiplication of gains."],answerSummary:"Net gain "+product+"; total level difference "+log(product)+" dB."});
  }
  if(mode===6)return questionSchema.parse({...base,prompt:rule+"For this system, the supplied combination law is P_total=P1+P2, with P1="+a+" W and P2="+b+" W. The shared reference is "+c+" W. Find the total power, its dimensionless reference ratio and level. Compare that level with the incorrect proposal D1+D2.",fields:[rational("power","Total power",String(a+b),"W"),rational("ratio","Total-to-reference power ratio",(a+b)+"/"+c),exact("total","Correct total referenced level",log((a+b)+"/"+c),"dB"),exact("proposed","Proposed D1 plus D2",log(a*b+"/"+(c*c)),"dB"),choice("valid","Does the proposed addition give the total level here?","no",[{id:"no",label:"No, add the supplied powers before taking the logarithm",feedback:"A logarithm of a sum does not split into the sum of logarithms."},{id:"yes",label:"Yes, logarithmic levels always add",feedback:"Level differences add for multiplicative gains; this supplied law adds powers instead."}])],hints:["Use the stated sum of powers first.","Divide that total by the positive reference and apply the given 10-log formula.","D1+D2 instead equals 10*log10(P1*P2/P_ref^2), which describes a different expression."],explanation:["The supplied power law gives "+(a+b)+" W and dimensionless ratio "+(a+b)+"/"+c+".","The correct referenced total level is "+log((a+b)+"/"+c)+" dB.","The proposal gives "+log(a*b+"/"+(c*c))+" dB, a different value for these data. A product identity cannot replace a logarithm of a sum."],answerSummary:"Total "+(a+b)+" W; correct level "+log((a+b)+"/"+c)+" dB; proposed level sum is different."});
  if(mode===7){
    const supplied=flag%2===0,ratio=a+"/"+b;
    return questionSchema.parse({...base,prompt:rule+"Positive amplitudes A="+a+" V and A_ref="+b+" V are supplied. "+(supplied?"The problem also establishes P/P_ref=(A/A_ref)^2.":"No relationship between these amplitudes and their corresponding powers is supplied.")+" Give the amplitude ratio and determine whether the power level follows from it."+(supplied?" Derive the power ratio, the coefficient multiplying log10(A/A_ref), and the exact power level.":" Identify the additional relationship needed before using 20*log10(A/A_ref) as a power level."),fields:[rational("amplitude","Dimensionless amplitude ratio",ratio),choice("enough","Is the supplied information sufficient for that power level?",supplied?"yes":"no",[{id:"yes",label:"Yes, the supplied squared-ratio relation determines it",feedback:"With the stated squared power ratio, the logarithm power rule gives the amplitude coefficient."},{id:"no",label:"No, the amplitude-to-power ratio relationship is missing",feedback:"Arbitrary voltage ratios alone do not establish corresponding power ratios."}]),...(supplied?[rational("power-ratio","Dimensionless power ratio","("+ratio+")^2"),rational("coefficient","Coefficient multiplying log10 of the amplitude ratio","20"),exact("level","Exact power level","20*log("+ratio+")","dB")]:[choice("needed","Which relationship would justify the proposed 20-log power expression?","square",[{id:"square",label:"P/P_ref = (A/A_ref)^2",feedback:"Substitute this positive squared ratio into the supplied 10-log power formula."},{id:"linear",label:"P/P_ref = A/A_ref",feedback:"A linear ratio would retain the coefficient ten."},{id:"none",label:"No relationship is needed",feedback:"The missing power relationship cannot be inferred from the amplitude units alone."}])])],hints:["Both amplitude measurements have the same units, so their positive ratio is dimensionless.","Check whether a relationship to the power ratio has actually been supplied.","If the ratio is squared, apply log10(r^2)=2*log10(r) for r>0. Otherwise, identify the missing premise instead of inventing a power level."],explanation:["The dimensionless amplitude ratio is "+ratio+".",supplied?"The supplied law makes the power ratio ("+ratio+")^2, giving 10*log10(("+ratio+")^2)=20*log10("+ratio+").":"The available amplitude ratio does not determine the power ratio. The squared-ratio relationship is needed to justify the proposed 20-log power formula.","The numerical coefficient follows from the given relationship between the quantities, not merely from seeing voltage units."],answerSummary:supplied?"Amplitude ratio "+ratio+"; power ratio ("+ratio+")^2; coefficient 20; level 20*log("+ratio+") dB.":"Amplitude ratio "+ratio+"; insufficient information; a squared power-ratio relationship is needed."});
  }
  const fault=flag<2?"power":flag<4?"reference":flag===4?"kind":"missing",scenario=["P=0 W and P_ref="+b+" W","P="+(-a)+" W and P_ref="+b+" W","P="+a+" W and P_ref=0 W","P="+a+" W and P_ref="+(-b)+" W","P="+a+" W and a proposed reference of "+b+" V","P="+a+" W, with no reference power stated"][flag];
  return questionSchema.parse({...base,category:"conceptual",prompt:rule+"Audit the proposed report: "+scenario+". Identify the failed requirement and whether it defines a valid reported power level. Then repair the report using the explicitly supplied positive powers P="+a+" W and P_ref="+b+" W, and give the repaired dimensionless ratio and exact level.",fields:[choice("fault","Which requirement fails?",fault,[{id:"power",label:"The measured power is not strictly positive",feedback:"Zero has no finite logarithm and a negative power does not satisfy this positive-power formula."},{id:"reference",label:"The reference power is not strictly positive",feedback:"Division by zero is undefined and a negative reference fails the supplied positive-power requirements."},{id:"kind",label:"The proposed reference is not a compatible power quantity",feedback:"Watts divided by volts is not the required dimensionless ratio of powers."},{id:"missing",label:"The reference power has not been specified",feedback:"A measured power alone does not determine its referenced level."}]),choice("valid","Does the proposed report define a valid power level?","no",[{id:"no",label:"No, the stated requirement must first be repaired",feedback:"A calculator entry cannot replace the required positive compatible powers and explicit reference."},{id:"yes",label:"Yes, any supplied numbers can enter the logarithm",feedback:"Check positivity, compatible quantities and the reference before evaluating."}]),rational("ratio","Repaired dimensionless power ratio",a+"/"+b),exact("level","Repaired referenced power level",log(a+"/"+b),"dB")],hints:["Check the two quantities and the reference before performing arithmetic.","A zero, negative, dimensionful or unspecified logarithm argument does not define this report.","Use only the explicitly supplied repaired powers to compute the new ratio and level."],explanation:["The proposed report fails the "+fault+" requirement, so it does not define the requested referenced power level.","The repaired data use two strictly positive powers in watts, with reference "+b+" W.","Their ratio is $"+rationalLatex(a+"/"+b)+"$, giving "+log(a+"/"+b)+" dB relative to that repaired reference."],answerSummary:"Invalid proposed report; failed "+fault+" requirement; repaired ratio "+a+"/"+b+" and level "+log(a+"/"+b)+" dB."});
}
