import { questionSchema,type Question } from "../contracts";
import { evaluateLogarithm,logarithmFeatures,logarithmFromExponential,logarithmicFunctionSchema,logarithmLatex } from "../logarithmic-functions";
import { exponentialFunctionSchema,exponentialLatex } from "../exponential-functions";
import { formatRational,parseRational } from "../rational";
import { formatIntervals } from "../intervals";
import { randomFrom } from "../random";

export const logGraphFamilyIds=["mth-log-graph"] as const;
const variants=["increasing-parent","decreasing-parent","outer-reflection","inner-reflection","scaled-shifted","anchor-map","y-intercept","inverse-pair"];
const r=(value:string)=>formatRational(parseRational(value));
const number=(id:string,label:string,expected:string)=>({id,label,kind:"rational",expected:r(expected),help:"Give an exact number or fraction."});
const interval=(id:string,label:string,expected:ReturnType<typeof logarithmFeatures>["domain"])=>({id,label,kind:"intervals",expected,help:"Use interval notation or R. A logarithm excludes its vertical asymptote."});
export function logGraphQuestion(familyId:string,variant:string,seed:string,id:string):Question{
  if(familyId!=="mth-log-graph")throw new Error("Unknown logarithm graph family");
  const rng=randomFrom(seed);if(variant==="mixed")variant=variants[rng.integer(0,variants.length-1)];const mode=variants.indexOf(variant);if(mode<0)throw new Error("Unknown logarithm graph variant");
  const flag=rng.integer(0,1),b=rng.integer(2,4),decay=mode===1||mode>=2&&mode!==6&&flag,bn=decay?1:b,bd=decay?b:1,u=rng.shuffle([-2,-1,1,2])[0],m=rng.integer(1,3),ea=(flag?-1:1)*rng.integer(2,4),en=(rng.integer(0,1)?-1:1)*rng.integer(1,2),ed=rng.integer(1,2),eh=rng.shuffle([-3,-1,1,3])[0],ek=rng.shuffle([-4,-2,2,4])[0];
  let an=mode===2?-rng.integer(1,3):mode>=4?(rng.integer(0,1)?-1:1)*rng.integer(1,3):1,ad=mode>=4?rng.integer(1,2):1,cn=mode===3?-rng.integer(1,3):mode>=4?(rng.integer(0,1)?-1:1)*rng.integer(1,3):1,cd=mode>=4?rng.integer(1,2):1,h=mode>=4?rng.shuffle([-4,-2,2,4])[0]:0,k=mode>=4?rng.integer(5,9):0;
  if(mode===6){ad=1;cn=flag?-1:1;cd=1;h=(rng.integer(0,1)?-1:1)*cn*b**m;}
  const source=exponentialFunctionSchema.parse({kind:"rational-base",base:r(bn+"/"+bd),a:String(ea),rate:r(en+"/"+ed),h:String(eh),k:String(ek)});
  if(mode===7){an=ed*Math.sign(en);ad=Math.abs(en);cn=Math.sign(ea);cd=Math.abs(ea);h=ek;k=eh;}
  const a=r(an+"/"+ad),c=r(cn+"/"+cd),model=mode===7?logarithmFromExponential(source):logarithmicFunctionSchema.parse({kind:"rational-base",base:r(bn+"/"+bd),a,c,h:String(h),k:String(k)}),features=logarithmFeatures(model),formula=logarithmLatex(model);
  const choice=(id:string,label:string,correct:string,options:{id:string;label:string;accessibleLabel?:string;feedback:string}[])=>({id,label,kind:"choice",correct,options:rng.shuffle(options)});
  const base={id,familyId,familyVersion:1,courseId:"mth-215",objectiveId:"m05-l02",critical:true,category:"conceptual",parameters:{mode,flag,bn,bd,an,ad,cn,cd,h,k,u,m,ea,en,ed,eh,ek}};
  if(mode===5){
    const parent=r("("+r(bn+"/"+bd)+")^("+u+")"),x=r(h+"+("+parent+")/("+c+")"),y=r(k+"+("+a+")*"+u),reflection=an<0?cn<0?"both":"vertical":cn<0?"horizontal":"none";
    return questionSchema.parse({...base,category:"procedural",prompt:"The parent logarithm has point ("+parent+", "+u+"). For $g(x)="+formula+"$, map that point, identify the positive horizontal and vertical length multipliers and reflections before translation, and state the domain and range.",
      fields:[number("x","Mapped input coordinate",x),number("y","Mapped output coordinate",y),number("horizontal","Positive horizontal length multiplier",cd+"/"+Math.abs(cn)),number("vertical","Positive vertical length multiplier",Math.abs(an)+"/"+ad),choice("reflection","Reflections before translation",reflection,[{id:"none",label:"Neither coordinate",feedback:"Both scale signs are positive before translation."},{id:"horizontal",label:"Input coordinates across the y-axis only",feedback:"A negative inside scale reflects input coordinates before the horizontal shift."},{id:"vertical",label:"Output coordinates across the x-axis only",feedback:"A negative outside scale reflects output coordinates before the vertical shift."},{id:"both",label:"Both input and output coordinates",feedback:"Both scale signs are negative before translation."}]),interval("domain","Complete domain",features.domain),interval("range","Complete range",features.range)],
      hints:["Set c*(x-h) equal to the parent input coordinate.","The parent output is u. Apply a*u+k to that coordinate separately.","Horizontal lengths are divided by the magnitude of c, while vertical lengths are multiplied by the magnitude of a."],
      explanation:["The mapped input is h+(parent input)/c="+x+", and the mapped output is k+a*u="+y+".","The positive length multipliers are "+r(cd+"/"+Math.abs(cn))+" horizontally and "+r(Math.abs(an)+"/"+ad)+" vertically. Reflections are "+reflection+" before translation.","The domain is "+formatIntervals(features.domain)+" and the range is R. The vertical boundary x="+h+" remains excluded."],
      answerSummary:"Point ("+x+", "+y+"); length factors "+r(cd+"/"+Math.abs(cn))+", "+r(Math.abs(an)+"/"+ad)+"; reflections "+reflection+"; domain "+formatIntervals(features.domain)+"; range R."});
  }
  if(mode===6){
    const intercept=evaluateLogarithm(model,"0"),allowed=intercept.status==="defined";
    if(allowed&&intercept.exact===null)throw new Error("This intercept question requires an exact value.");
    const candidate=r(k+"+("+a+")*"+m),values=[...new Set([candidate,a,String(k)])];
    const options=values.map((value,i)=>({id:"value-"+i,label:value,accessibleLabel:"The y-intercept is "+value,feedback:"A y-intercept requires x=0 to belong to the domain, followed by evaluation of the entire function."}));
    const correct=allowed?"value-"+values.indexOf(intercept.exact!):"undefined";
    return questionSchema.parse({...base,category:"procedural",prompt:"For $g(x)="+formula+"$, distinguish the outside coefficient, the shifted point where the logarithm argument equals one, and any y-intercept. State the original domain, complete range and vertical asymptote. Do not substitute zero until checking its domain membership.",
      fields:[number("coefficient","Outside coefficient a",a),number("anchor-x","Input where the logarithm argument is one",features.anchor.x),number("anchor-y","Output at that anchor",features.anchor.y),choice("intercept","The actual y-intercept",correct,[...options,{id:"undefined",label:"There is no y-intercept",accessibleLabel:"There is no y-intercept",feedback:"The graph meets the y-axis only if zero is in its domain."}]),interval("domain","Complete domain",features.domain),interval("range","Complete range",features.range),number("asymptote","Vertical asymptote input",String(h))],
      hints:["The logarithm argument equals one at x=h+1/c, giving output k because log(1)=0.","Check the sign of c*(0-h) to decide whether a y-intercept exists.","If that argument is positive, reconstruct it as a power of the base and then apply the outside scale and shift."],
      explanation:["The outside coefficient is "+a+". The argument-one anchor is ("+features.anchor.x+", "+k+").",allowed?"At zero the positive logarithm argument is "+b+"^"+m+", so the actual y-intercept is "+intercept.exact+".":"At zero the logarithm argument is negative. The function has no y-intercept even though the affine input expression can be evaluated.","The domain is "+formatIntervals(features.domain)+", range R, and vertical asymptote x="+h+"."],
      answerSummary:"Coefficient "+a+"; anchor ("+features.anchor.x+", "+k+"); intercept "+(allowed?intercept.exact:"does not exist")+"; domain "+formatIntervals(features.domain)+"; range R; asymptote "+h+"."});
  }
  if(mode===7)return questionSchema.parse({...base,category:"procedural",prompt:"Find the inverse of $f(x)="+exponentialLatex(source)+"$. Write it in the template $g(x)=A\\log_b(C(x-H))+K$, using the same base as f. Give A, C, H and K, the inverse domain and range, and the inverse point obtained from f("+eh+").",
    fields:[number("a","Inverse outside coefficient A",a),number("c","Inverse inside coefficient C",c),number("h","Inverse input shift H",String(h)),number("k","Inverse output shift K",String(k)),interval("domain","Inverse domain",features.domain),interval("range","Inverse range",features.range),number("point-x","Input coordinate of the exchanged anchor",String(ea+ek)),number("point-y","Output coordinate of the exchanged anchor",String(eh))],
    hints:["Subtract the exponential baseline, then divide by its signed outside coefficient. This quotient must be positive.","Apply the base-b logarithm to recover the affine exponent, then divide by its rate and restore the original input shift.","The inverse accepts exactly the exponential's output range. Exchange both coordinates of the point f(h)=a+k."],
    explanation:["The isolated exponential factor is (x-("+ek+"))/("+ea+"). Its logarithm equals ("+r(en+"/"+ed)+")*(g(x)-("+eh+")).","Solving gives A="+a+", C="+c+", H="+h+" and K="+k+", hence $g(x)="+formula+"$.","The inverse domain is "+formatIntervals(features.domain)+" and its range is R. A signed outside coefficient in f can put the inverse domain below its boundary.","The exponential point ("+eh+", "+(ea+ek)+") becomes the inverse point ("+(ea+ek)+", "+eh+")."],
    answerSummary:"A="+a+"; C="+c+"; H="+h+"; K="+k+"; domain "+formatIntervals(features.domain)+"; range R; exchanged anchor ("+(ea+ek)+", "+eh+")."});
  const direction=choice("direction","Direction as x increases",features.increasing?"increasing":"decreasing",[{id:"increasing",label:"Increasing",feedback:"Combine the base direction with both the inside and outside signs."},{id:"decreasing",label:"Decreasing",feedback:"Either reflection reverses direction; two reflections preserve the parent's direction."}]);
  const infinity=(id:string,label:string,correct:string)=>choice(id,label,correct,[{id:"positive-infinity",label:"Positive infinity",feedback:"Track the sign of the logarithm and the outside coefficient. A finite vertical shift does not bound the output."},{id:"negative-infinity",label:"Negative infinity",feedback:"Track both the base direction and outside sign when the argument approaches zero or grows without bound."}]);
  return questionSchema.parse({...base,prompt:"Analyze the full real graph of $g(x)="+formula+"$. Give the domain, range and vertical asymptote, the direction as x increases, the output behavior at the excluded domain boundary and at the unbounded end of the domain, and the point where the logarithm argument equals one.",
    fields:[interval("domain","Complete domain",features.domain),interval("range","Complete range",features.range),number("asymptote","Vertical asymptote input",String(h)),direction,infinity("boundary","Output approaching the boundary from within the domain",features.boundaryOutput),infinity("far","Output at the unbounded end of the domain",features.farOutput),number("anchor-x","Input where the logarithm argument is one",features.anchor.x),number("anchor-y","Output at that anchor",features.anchor.y)],
    hints:["Solve c*(x-h)>0. Its strict boundary gives the vertical asymptote, while a nonconstant real logarithm has all-real output range.","A base above one makes the parent increasing; a fractional base makes it decreasing. Each negative scale reverses direction.","At the domain boundary the positive argument approaches zero. At the unbounded domain end it grows without bound. Apply the outside sign, and use argument one for the exact anchor."],
    explanation:["The argument is positive on "+formatIntervals(features.domain)+", excluding x="+h+". The range is R and the vertical asymptote is x="+h+".","The output is "+(features.increasing?"increasing":"decreasing")+" as x increases, after combining the base with both scale signs.","At the boundary approached from the "+features.domainSide+", the output tends to "+features.boundaryOutput+". At the unbounded end it tends to "+features.farOutput+".","Solving c*(x-h)=1 gives the anchor ("+features.anchor.x+", "+features.anchor.y+")."],
    answerSummary:"Domain "+formatIntervals(features.domain)+"; range R; asymptote "+h+"; "+(features.increasing?"increasing":"decreasing")+"; boundary output "+features.boundaryOutput+"; far output "+features.farOutput+"; anchor ("+features.anchor.x+", "+features.anchor.y+")."});
}
