import { questionSchema,type Question } from "../contracts";
import { formatRational,parseRational } from "../rational";
import { randomFrom } from "../random";

export const variationAuditFamilyIds=["mth-variation-audit"] as const;
const r=(source:string)=>formatRational(parseRational(source));
const exact=(id:string,label:string,expected:string,unit="")=>({id,label,kind:"rational",expected:r(expected),unit});
const roots=(id:string,label:string,expected:string[])=>({id,label,kind:"roots",numberSystem:"real",expected,help:"List every distinct real input, separated by commas, or type empty if there are none."});
const choice=(id:string,label:string,correct:string,options:[string,string,string][])=>({id,label,kind:"choice",correct,options:options.map(([id,label,feedback])=>({id,label,feedback}))});
const yesNo=(id:string,label:string,yes:boolean,feedback:string)=>choice(id,label,yes?"yes":"no",[["yes","Yes",feedback],["no","No",feedback]]);
export function variationAuditQuestion(familyId:string,variant:string,seed:string,id:string):Question{
  if(familyId!=="mth-variation-audit")throw new Error("Unknown variation audit family");
  const rng=randomFrom(seed),variants=["units","table-consistency","unknown-held-variable","wrong-inverse","wrong-power","nonidentifying-observation","model-window","physical-branch","measured-tolerance"];
  if(variant==="mixed")variant=variants[rng.integer(0,variants.length-1)];const mode=variants.indexOf(variant);if(mode<0)throw new Error("Unknown variation audit variant");
  const a=rng.integer(1,4),b=a+rng.integer(1,4),c=rng.integer(1,4),d=c+rng.integer(1,3),kn=rng.integer(1,6),kd=rng.integer(1,3),k=r(kn+"/"+kd),flag=rng.integer(0,1),offset=rng.integer(1,4);
  const base={id,familyId,familyVersion:1,courseId:"mth-215",objectiveId:"m04-l03",critical:true,category:"conceptual",parameters:{mode,a,b,c,d,kn,kd,flag,offset}};
  if(mode===0){
    const y=r("("+k+")*"+a+"^2/"+c);
    return questionSchema.parse({...base,prompt:"A supplied model is y=kx^2/z. Here y is measured in meters, x in seconds, and z in kilograms. An observation gives x="+a+", z="+c+", y="+y+". Recover k and write the exponents of kg, m, and s in its unit. For reference, one newton is one kg*m/s^2.",fields:[exact("constant","Numerical variation constant",k),exact("mass","Exponent of kg in the coefficient unit","1"),exact("length","Exponent of m in the coefficient unit","1"),exact("time","Exponent of s in the coefficient unit","-2"),choice("unit","Equivalent unit of k","force",[["force","N","The unit kg*m/s^2 is a newton, using the supplied definition."],["speed","m/s","This would leave a different output unit after multiplication by x squared and division by z."],["none","Dimensionless","The input and output dimensions do not cancel in this coefficient."]])],hints:["Isolate the coefficient as k=yz/x^2 before considering units.","Substitute the quantity units into that formula: meters times kilograms divided by seconds squared.","A denominator unit has a negative exponent. Compare the result with the supplied newton definition."],explanation:["The numerical coefficient is "+k+".","Its unit is kg^1*m^1*s^-2, equal to N by the stated definition.","Numerical calibration and dimensional consistency are separate requirements; both must hold."],answerSummary:"k="+k+"; unit exponents kg:1, m:1, s:-2; N."});
  }
  if(mode===1){
    const ys=[r("("+k+")*"+a+"/"+c),r("("+k+")*"+b+"/"+d),r("("+k+")*"+(a+1)+"/"+(c+1)+"+"+(flag?offset:0))],third=r("("+ys[2]+")*"+(c+1)+"/"+(a+1));
    return questionSchema.parse({...base,prompt:"Test the proposed exact law y=kx/z using three records (x,z,y): ("+a+","+c+","+ys[0]+"), ("+b+","+d+","+ys[1]+"), and ("+(a+1)+","+(c+1)+","+ys[2]+"). Compute k from each record and state the conclusion justified by these records.",fields:[exact("first","Constant implied by record 1",k),exact("second","Constant implied by record 2",k),exact("third","Constant implied by record 3",third),choice("conclusion","Conclusion from exact records",flag?"inconsistent":"compatible",[["compatible","Compatible with one coefficient at these records only","Equal inferred coefficients are consistent with the proposed law at the observed inputs; they do not prove unobserved behavior."],["inconsistent","Inconsistent with one exact coefficient","Different inferred coefficients cannot all satisfy one exact y=kx/z law."],["proven","The records prove this law for all inputs","A finite set of observations does not determine every unobserved input."]])],hints:["Rearrange each observation into k=yz/x.","Use each record's own x and z values when computing its coefficient.","Compare all three exact constants. Compatibility at records is weaker than proof over a whole domain."],explanation:["The inferred coefficients are "+k+", "+k+", and "+third+".",flag?"The third coefficient differs, so the exact records contradict one shared coefficient.":"The three coefficients agree, so the records are compatible with the proposed law at those inputs.","No finite collection here establishes behavior at every unobserved input."],answerSummary:"Coefficients "+k+", "+k+", "+third+"; "+(flag?"inconsistent":"compatible at records only")+"."});
  }
  if(mode===2)return questionSchema.parse({...base,prompt:"In y=kx/z, all current inputs and the constant are positive. The x input is multiplied by "+(a+1)+", but no information is given about the change in z. Compute the output factor if z is held fixed, then if z is multiplied by that same factor. Decide whether the original statement determines one output factor.",fields:[exact("held","Output factor if z stays fixed",String(a+1)),exact("doubled","Output factor if z changes by the same factor","1"),yesNo("determined","Does the stated x change determine the output factor without information about z?",false,"The output factor is the x multiplier divided by the z multiplier. Different z changes give different output factors.")],hints:["Write the ratio of changed output to original output.","The ratio equals (changed x / original x) divided by (changed z / original z).","Substitute a z factor of 1 and then "+(a+1)+". These two valid possibilities give different answers."],explanation:["With z fixed, the output factor is "+(a+1)+". With z multiplied by the same factor, it is 1.","The original statement does not specify one output factor because z may change.","Claims about the effect of one variable need an explicit statement about other inputs and the model constant."],answerSummary:"Factors "+(a+1)+" and 1; not determined without the z change."});
  if(mode===3){
    const y=r("("+k+")*"+a+"/"+c),correct=r("2*("+y+")"),proposed=r("("+y+")/2");
    return questionSchema.parse({...base,prompt:"The response y varies directly with x and inversely with z. A learner instead uses y=Cz/x and fits C to the record x="+a+", z="+c+", y="+y+". Audit the formula, write the correct powers in y=kx^p z^q, recover k, and compare both predictions when x doubles with z fixed.",fields:[yesNo("valid","Does the learner's formula match the stated variation?",false,"The learner swapped the direct and inverse roles. One matching record does not validate the structure."),exact("power-x","Correct exponent p of x","1"),exact("power-z","Correct exponent q of z","-1"),exact("constant","Correct coefficient k",k),exact("correct","Response from the correct model after x doubles",correct),exact("proposed","Response from the learner's fitted model after x doubles",proposed)],hints:["A direct first power goes in the numerator; an inverse first power goes in the denominator.","The correct calibration coefficient is yz/x.","Holding z fixed, the correct rule doubles y while the swapped rule halves it, even if each fits the baseline with its own coefficient."],explanation:["The correct structure is y=kx/z, with powers 1 and -1 and coefficient "+k+".","After x doubles, the correct prediction is "+correct+"; the learner's fitted rule predicts "+proposed+".","Matching one calibration record does not repair an incorrectly translated model."],answerSummary:"Invalid structure; p=1, q=-1, k="+k+"; predictions "+correct+" and "+proposed+"."});
  }
  if(mode===4){
    const y=r("("+k+")/"+a+"^2"),correct=r("("+y+")/4");
    return questionSchema.parse({...base,prompt:"A positive response varies inversely with the square of x and equals "+y+" at x="+a+". A learner says doubling x halves the response. Audit this claim and repair the output multiplier and predicted response, keeping the same constant.",fields:[yesNo("valid","Is the claimed halving correct?",false,"Doubling an input inside a square multiplies its square by four."),exact("factor","Correct output multiplier","1/4"),exact("output","Correct new response",correct)],hints:["Write the changed denominator as (2x)^2, not 2x^2.","The entire square gives 4x^2.","The reciprocal denominator effect multiplies the original response by one quarter."],explanation:["The claim confuses inverse first-power and inverse-square models.","The correct output factor is 1/4, so the response becomes "+correct+".","A 75% decrease is not the same as a 50% decrease."],answerSummary:"Invalid; multiplier 1/4; response "+correct+"."});
  }
  if(mode===5){
    const first=flag?offset:0,second=r("("+k+")*"+a+"*"+c);
    return questionSchema.parse({...base,prompt:"For the proposed joint law y=kxz with nonzero k, the first exact record is x=0, z="+c+", y="+first+". A second record is x="+a+", z="+c+", y="+second+". Classify the first record, find k from the second record alone, and decide whether one coefficient fits both.",fields:[choice("first","What does the first record establish?",flag?"inconsistent":"underdetermined",[["underdetermined","It leaves the coefficient unidentified","When the product xz is zero and y is zero, every nonzero coefficient fits that record."],["inconsistent","It contradicts this joint law","The proposed product law gives zero whenever x is zero; a nonzero observed y contradicts it."],["undefined","The product law is undefined at x = 0","Multiplication by zero is defined. Dividing by zero during a proposed calibration is the invalid operation."]]),exact("constant","Constant from the second record alone",k),yesNo("shared","Can one coefficient satisfy both records?",!flag,"Fit the nonzero-product observation, but retain any contradiction in the zero-product observation.")],hints:["Substitute x=0 into the product law before trying to isolate k.","A zero product cannot be used as a divisor when recovering k.","The second record has a nonzero product xz; its ratio y/(xz) identifies a candidate coefficient."],explanation:[flag?"The first record is inconsistent with the product law.":"The first record is defined but does not identify k.","The second record alone gives k="+k+".",flag?"The first contradiction remains, so the two records cannot share one coefficient.":"This coefficient fits both records; only the second identifies it."],answerSummary:(flag?"Inconsistent":"Underdetermined")+" first record; k="+k+" from the second; "+(flag?"no shared model":"shared model")+"."});
  }
  if(mode===6){
    const lower=a,upper=b,probe=flag?upper+1:rng.integer(0,1)?lower:upper,target=r("("+k+")/"+probe);
    return questionSchema.parse({...base,category:"application",parameters:{...base.parameters,probe},prompt:"The supplied rule y=("+k+")/x is validated only for inputs in the closed interval ["+lower+","+upper+"]. Solve the equation for target response y="+target+". State whether the resulting input is mathematically defined and whether the supplied operating window validates that prediction.",fields:[exact("input","Algebraic input producing the target",String(probe)),yesNo("defined","Is the original formula defined at this input?",true,"The candidate is nonzero, so the reciprocal formula is mathematically defined."),yesNo("validated","Is this input inside the supplied validated interval?",!flag,"Check both closed endpoints. A mathematically defined extrapolation is not automatically validated."),{id:"operating",label:"Supplied operating interval",kind:"intervals",expected:[{lower:String(lower),upper:String(upper),lowerClosed:true,upperClosed:true}],help:"Use interval notation and retain the supplied endpoint inclusions."}],hints:["Rearrange the nonzero-target reciprocal equation into x=k/y.","Check the original denominator at the resulting input.","Then compare the input separately with the closed operating interval. Algebraic validity and model validation are different checks."],explanation:["The algebraic input is "+probe+", and the original formula is defined there.",flag?"This input exceeds the supplied upper bound, so its response is an extrapolation outside the validated window.":"This input is an included operating endpoint, so it lies inside the supplied window.","The operating interval remains ["+lower+","+upper+"]."],answerSummary:"Input "+probe+"; mathematically defined; "+(flag?"outside":"inside")+" the validated interval."});
  }
  if(mode===7){
    const target=r("("+k+")*"+b+"^2/"+c);
    return questionSchema.parse({...base,category:"application",prompt:"For the supplied rule y=("+k+")x^2/z, hold z="+c+" and require physical inputs x>0. Find every real x giving y="+target+", then select the physically allowed inputs. Separately decide whether the original formula at this fixed nonzero z is defined at x=0.",fields:[roots("algebraic","All real algebraic x candidates",["-"+b,String(b)]),roots("allowed","Physically allowed x candidates",[String(b)]),yesNo("defined","Is the original formula defined at x = 0 with this fixed z?",true,"Only z is in the denominator. At x=0 and this fixed nonzero z, the formula gives zero."),yesNo("physical","Does the supplied physical requirement allow x = 0?",false,"The physical condition is strictly x>0 even though the formula itself is defined at zero.")],hints:["Substitute the fixed z and rearrange the equation into x squared equal to a positive number.","Include both signs when reporting real algebraic candidates.","Apply the positive physical restriction separately. Do not turn that restriction into a false claim that the polynomial-in-x formula is undefined at zero."],explanation:["The real candidates are -"+b+" and "+b+", but only "+b+" is physically allowed.","At x=0 the original formula is defined and has output zero because z is fixed and nonzero.","The supplied physical condition excludes x=0 for a different reason. Mathematical domains and application restrictions must stay distinguishable."],answerSummary:"Real candidates -"+b+", "+b+"; physical candidate "+b+"; zero is mathematically defined but physically excluded."});
  }
  const residuals=["1/20","-1/20","1/10","-1/10","1/4","-1/4"],ri=rng.integer(0,residuals.length-1),residual=residuals[ri],predicted=r("("+k+")*"+b+"/"+d),observed=r("("+predicted+")+("+residual+")"),within=ri<4;
  return questionSchema.parse({...base,category:"application",parameters:{...base.parameters,ri},prompt:"A supplied calibrated model y=("+k+")x/z predicts a response in volts. At x="+b+", z="+d+", the measured response is "+observed+" V. The permitted absolute residual is at most 1/10 V, inclusive. Compute observed minus predicted, apply this tolerance, and state whether this one measurement proves the law for every input.",fields:[exact("prediction","Predicted response",predicted,"V"),exact("residual","Observed minus predicted residual",residual,"V"),yesNo("within","Is the measurement within the stated absolute tolerance?",within,"Compare the residual magnitude, not its sign, with the inclusive limit 1/10 V."),yesNo("proves","Does this one measurement prove the law for every input?",false,"A measurement can be consistent with a model within its stated tolerance without proving an entire law.")],hints:["Evaluate the calibrated formula at this measurement's x and z.","Subtract predicted from observed, retaining the sign of the residual.","Compare the absolute residual with 1/10. Equality meets an inclusive tolerance, but does not turn finite data into a proof of the model."],explanation:["The predicted response is "+predicted+" V and the signed residual is "+residual+" V.",within?"The residual magnitude is no greater than 1/10 V, so the measurement meets the stated tolerance.":"The residual magnitude exceeds 1/10 V, so this measurement does not meet the stated tolerance.","Neither outcome proves the law at every input. Use the stated measurement tolerance without treating rounded or measured data as exact identities."],answerSummary:"Prediction "+predicted+" V; residual "+residual+" V; "+(within?"within":"outside")+" tolerance; no universal proof."});
}
