import { questionSchema,type Question } from "../contracts";
import { formatRational,parseRational } from "../rational";
import { randomFrom } from "../random";

export const modelTimescaleFamilyIds=["mth-model-timescale"] as const;
const variants=["half-life","doubling-time","rate-to-time","time-constant","remaining-fraction","observed-change","additional-time","rate-comparison"];
const number=(id:string,label:string,expected:string,unit="")=>({id,label,kind:"rational",expected:formatRational(parseRational(expected)),unit});
const exact=(id:string,label:string,expected:string,unit="")=>({id,label,kind:"logarithmic",expected,unit});
export function modelTimescaleQuestion(familyId:string,variant:string,seed:string,id:string):Question{
  if(familyId!=="mth-model-timescale")throw new Error("Unknown model timescale family");
  const rng=randomFrom(seed);if(variant==="mixed")variant=variants[rng.integer(0,variants.length-1)];const mode=variants.indexOf(variant);if(mode<0)throw new Error("Unknown model timescale variant");
  const p=rng.integer(1,4),q=rng.integer(2,8),amplitude=rng.integer(2,12),baseline=rng.integer(3,10),flag=rng.integer(0,5),b=rng.integer(2,5),n=rng.integer(1,3),percent=[10,20,25,40,50][rng.integer(0,4)];
  const base={id,familyId,familyVersion:1,courseId:"mth-215",objectiveId:"m05-l04",critical:true,category:"application",parameters:{mode,p,q,amplitude,baseline,flag,b,n,percent}};
  const choice=(id:string,label:string,correct:string,options:{id:string;label:string;feedback:string}[])=>({id,label,kind:"choice",correct,options:rng.shuffle(options)});
  const positiveTime=choice("sign","Why is the requested future interval positive?","same",[{id:"same",label:"The logarithm of the target ratio and the signed rate have the same sign",feedback:"Solving exp(kT)=ratio gives T=ln(ratio)/k, so matching nonzero signs give a positive time."},{id:"absolute",label:"Every negative algebraic time should be replaced by its absolute value",feedback:"A negative crossing can indicate a past event. Taking its absolute value is not a valid general repair."},{id:"drop",label:"The minus sign of a decay rate can be dropped",feedback:"Keep the signed rate and the logarithm's sign throughout the calculation."}]);
  if(mode===0||mode===1){
    const growing=mode===1,rate=(growing?"":"-")+p+"/"+q,ratio=growing?"2":"1/2",time=q+"*ln(2)/"+p;
    return questionSchema.parse({...base,prompt:"A positive quantity follows $Y(t)="+amplitude+"\\exp("+(growing?"":"-")+"\\tfrac{"+p+"}{"+q+"}t)$ for t>=0, where t is measured numerically in seconds and Y in volts. The signed rate has units per second. Find its "+(growing?"doubling time":"half-life")+", the target-to-initial ratio, and the fraction or multiple after two such intervals.",fields:[number("rate","Signed continuous rate",rate,"1/s"),number("ratio","Dimensionless target-to-initial ratio",ratio),exact("time",growing?"Doubling time":"Half-life",time,"s"),number("twice","Ratio after two requested intervals",growing?"4":"1/4"),positiveTime],hints:["Divide the future value by its positive initial value to remove the amplitude.","Set exp(kT) equal to the requested dimensionless ratio and take natural logarithms.","Keep the signed rate. Two equal intervals multiply the same ratio twice."],explanation:["The signed rate is "+rate+" per second, and the target ratio is "+ratio+".","Solving exp(kT)="+ratio+" gives T=ln("+ratio+")/("+rate+")="+time+" seconds.","After two such intervals the initial value is multiplied by "+(growing?"four":"one quarter")+". The interval depends on the rate, not the positive initial amplitude."],answerSummary:"Rate "+rate+" per second; ratio "+ratio+"; interval "+time+" s; two-interval ratio "+(growing?"4":"1/4")+"."});
  }
  if(mode===2){
    const growing=flag%2===1,rate=(growing?"":"-")+"ln(2)/"+q;
    return questionSchema.parse({...base,prompt:"A positive exponential quantity has a "+(growing?"doubling time":"half-life")+" of "+q+" minutes. Recover its signed continuous rate per minute and per second, the exact one-minute multiplication factor, and its ratio after "+2*q+" minutes. The same physical model must result from either time unit.",fields:[exact("minute","Signed rate per minute",rate,"1/min"),exact("second","Signed rate per second","("+rate+")/60","1/s"),exact("factor","One-minute multiplication factor","exp("+rate+")"),number("ratio","Ratio after the stated two intervals",growing?"4":"1/4")],hints:["Use exp(kT)=2 for doubling or exp(kT)=1/2 for half-life.","One minute contains 60 seconds. The numerical rate per second is the rate per minute divided by 60.","A one-minute factor is exp(k_minute). Two complete half-lives or doubling times apply the corresponding ratio twice."],explanation:["The rate per minute is "+rate+", obtained by taking the logarithm of the target ratio and dividing by "+q+" minutes.","The rate per second is ("+rate+")/60. Multiplying by the corresponding numerical time in seconds gives the same dimensionless exponent.","The one-minute factor is exp("+rate+"). After two stated intervals the ratio is "+(growing?"4":"1/4")+"."],answerSummary:"Per-minute rate "+rate+"; per-second rate ("+rate+")/60; one-minute factor exp("+rate+"); two-interval ratio "+(growing?"4":"1/4")+"."});
  }
  if(mode===3){
    const deviation=flag%2?-amplitude:amplitude;
    return questionSchema.parse({...base,prompt:"The supplied voltage model is $V(t)="+baseline+"+("+deviation+")\\exp(-t/"+q+")$, with V in volts and t numerically in seconds, t>=0. The positive time constant is "+q+" seconds. Find the signed rate, the ratio of the deviation V-baseline after one time constant to its initial deviation, the resulting voltage, and the half-life of the deviation magnitude.",fields:[number("rate","Signed continuous rate","-1/"+q,"1/s"),exact("fraction","Deviation ratio after one time constant","1/e"),exact("voltage","Voltage after one time constant",baseline+"+("+deviation+")/e","V"),exact("half-life","Half-life of the deviation magnitude",q+"*ln(2)","s"),choice("same","Does one time constant halve the deviation?","no",[{id:"no",label:"No, it leaves 1/e; the half-life is tau*ln(2)",feedback:"exp(-1) is approximately 0.368, so it differs from one half."},{id:"yes",label:"Yes, a time constant and a half-life are identical",feedback:"Half-life solves exp(-T/tau)=1/2, not exp(-1)=1/2."}])],hints:["Compare the supplied exponent with k*t and retain its negative sign.","At t=tau the exponent is -1. Apply that factor to the signed deviation, then add the baseline back.","Solve exp(-T/tau)=1/2 for the deviation half-life. The total voltage need not halve when its baseline is nonzero."],explanation:["The signed rate is -1/"+q+" per second, while the time constant is "+q+" seconds.","The deviation ratio after one time constant is exp(-1)=1/e. The voltage then is "+baseline+"+("+deviation+")/e V.","The deviation magnitude halves after "+q+"*ln(2) seconds. This reasoning also applies to an approach from below because the positive exponential preserves the deviation's sign."],answerSummary:"Rate -1/"+q+" per second; deviation ratio 1/e; voltage "+baseline+"+("+deviation+")/e V; half-life "+q+"*ln(2) s."});
  }
  if(mode===4){
    const [numerator,denominator]=[[1,3],[2,5],[1,8],[3,4]][flag%4],ratio=numerator+"/"+denominator,time="-"+q+"*ln("+ratio+")/"+p;
    return questionSchema.parse({...base,parameters:{...base.parameters,numerator,denominator},prompt:"A positive signal follows $Y(t)="+amplitude+"\\exp(-\\tfrac{"+p+"}{"+q+"}t)$, with t numerically in seconds and Y in volts. How much time since t=0 is required for it to reach "+numerator+"/"+denominator+" of its initial value? Give the target voltage, dimensionless logarithm argument, and exact time.",fields:[number("target","Target voltage",amplitude+"*"+numerator+"/"+denominator,"V"),number("ratio","Dimensionless argument used after isolating the exponential",ratio),exact("time","Elapsed time since the initial observation",time,"s"),positiveTime],hints:["Multiply the initial voltage by the requested fraction to obtain the target.","Divide target voltage by initial voltage before taking a logarithm.","The logarithm of a fraction between zero and one is negative, as is the signed decay rate. Their quotient gives the elapsed time."],explanation:["The target is "+amplitude+"*("+ratio+") V. Dividing by the initial voltage yields the dimensionless ratio "+ratio+".","Taking natural logarithms gives (-"+p+"/"+q+")t=ln("+ratio+"), hence t="+time+" seconds.","The time is positive. Substitution returns the requested fractional voltage without rounding an intermediate logarithm."],answerSummary:"Target "+amplitude+"*("+ratio+") V; logarithm argument "+ratio+"; elapsed time "+time+" s."});
  }
  if(mode===5){
    const growing=flag%2===1,numerator=100+(growing?percent:-percent),factor=numerator+"/100",rate="ln("+factor+")/"+q,time=(growing?"":"-")+q+"*ln(2)/ln("+factor+")";
    return questionSchema.parse({...base,prompt:"A positive quantity "+(growing?"increases":"decreases")+" by "+percent+" percent every "+q+" minutes under a continuous exponential model. Give the multiplication factor for that interval, signed continuous rate per minute, and future "+(growing?"doubling time":"half-life")+". Decide whether the signed continuous rate equals the signed fractional change divided by the interval.",fields:[number("factor","Multiplication factor per stated interval",factor),exact("rate","Signed continuous rate","ln("+factor+")/"+q,"1/min"),exact("time",growing?"Doubling time":"Half-life",time,"min"),choice("percent","Is the signed fractional change divided by time the exact continuous rate?","no",[{id:"no",label:"No, the exact rate uses the logarithm of the factor",feedback:"The continuous rate satisfies exp(k*interval)=factor, so k=ln(factor)/interval."},{id:"yes",label:"Yes, percentage change and continuous rate are interchangeable",feedback:"A per-interval fractional change is factor minus one, which differs from the logarithm of that factor."}])],hints:["Turn a percentage increase into 1+p/100, or a decrease into 1-p/100.","Match exp(k*interval) to that positive factor and solve for the signed rate.","Use ln(2)/k for growth doubling, or ln(1/2)/k for decay half-life. Preserve the signs."],explanation:["The per-interval factor is "+factor+", not "+percent+"/100.","The exact signed continuous rate is "+rate+" per minute. The signed fractional change divided by time is a different quantity.","The requested future interval is "+time+" minutes. The amplitude cancels when the target-to-initial ratio is formed."],answerSummary:"Interval factor "+factor+"; rate "+rate+" per minute; requested time "+time+" min; percentage shortcut is not exact."});
  }
  if(mode===6){
    const later=n*q,initial=amplitude*2**n,laterRatio="1/"+b,additional=q+"*ln("+b+")/ln(2)",elapsed=later+"+("+additional+")";
    return questionSchema.parse({...base,prompt:"A voltage follows $V(t)="+initial+"\\,2^{-t/"+q+"}$, with t numerically in seconds and V in volts. At time "+later+" s its voltage is "+amplitude+" V. The target is "+amplitude+"/"+b+" V. Find the target-to-current ratio, the additional waiting time from that later observation, and the total elapsed time since t=0.",fields:[number("ratio","Target divided by the current voltage",laterRatio),exact("additional","Additional time after the later observation",additional,"s"),exact("elapsed","Total time since t = 0",elapsed,"s"),choice("clock","Does the additional time start at the model's original t = 0?","no",[{id:"no",label:"No, it starts at the stated later observation",feedback:"The additional interval is total elapsed time minus the time already passed."},{id:"yes",label:"Yes, additional and total elapsed time are the same",feedback:"The model has already evolved for the stated number of seconds before this new waiting interval begins."}])],hints:["Form the new ratio using the current voltage at the later observation.","The same exponential factor applies over any interval of a given length. Solve 2^(-delta/q)=target/current.","Add the time already passed to the additional interval to recover total elapsed time."],explanation:["At "+later+" s, the original model gives "+initial+"*2^(-"+n+")="+amplitude+" V, confirming the supplied current reading.","The target/current ratio is 1/"+b+". Solving the interval equation gives additional time "+additional+" s.","The total elapsed time is "+elapsed+" s. Using the initial voltage instead of the current voltage would directly compute total time rather than this additional interval."],answerSummary:"Current ratio 1/"+b+"; additional time "+additional+" s; total elapsed time "+elapsed+" s."});
  }
  const other=q+b,caseRate=flag%3===0?"0":flag%3===1?"1/"+p:"-1/"+p,exists=flag%3===2;
  return questionSchema.parse({...base,category:"conceptual",prompt:"Two positive exponential signals have signed decay rates k1=-1/"+q+" per second and k2=-1/"+other+" per second. Find their half-lives, T2/T1, and which halves sooner. Separately, a positive model Y=A*exp(k*t) has k="+caseRate+" per second. Does this separate model have a positive future half-life?",fields:[exact("first","Half-life for k1",q+"*ln(2)","s"),exact("second","Half-life for k2",other+"*ln(2)","s"),number("ratio","Dimensionless T2/T1",other+"/"+q),choice("faster","Which signal halves sooner?","first",[{id:"first",label:"The first, whose signed rate is more negative",feedback:"A greater positive decay constant corresponds to a shorter half-life."},{id:"second",label:"The second, whose signed rate is closer to zero",feedback:"A rate closer to zero changes the signal more slowly."}]),choice("exists","Does the separate model have a positive future half-life?",exists?"yes":"no",[{id:"yes",label:"Yes, its nonzero negative rate gives a future halving",feedback:"For a negative rate, ln(1/2)/k is strictly positive."},{id:"no",label:"No, it is constant or growing",feedback:"A constant positive signal never halves, and a growing signal reached half its current value only in the past."}])],hints:["For each decaying signal use T=ln(1/2)/k and keep both negative signs.","Compare the positive half-lives, or compare the positive decay constants -k.","For the separate model, examine k before dividing. A zero rate is constant, while a positive rate gives no future halving."],explanation:["The two half-lives are "+q+"*ln(2) s and "+other+"*ln(2) s. Their ratio T2/T1 is "+other+"/"+q+">1.","The first signal halves sooner because its signed rate is more negative.",exists?"The separate model has a negative rate, so its positive future half-life is "+p+"*ln(2) s.":flag%3===0?"The separate model is constant. Dividing by its zero rate cannot produce a half-life.":"The separate model grows. Its algebraic half-value time is negative and represents a past time, not a positive future half-life."],answerSummary:"Half-lives "+q+"*ln(2) s and "+other+"*ln(2) s; ratio "+other+"/"+q+"; first is faster; separate future half-life "+(exists?"exists":"does not exist")+"."});
}
