import { questionSchema,type Question } from "../contracts";
import { logarithmDomain } from "../logarithm-domains";
import { formatIntervals,parseIntervals } from "../intervals";
import { formatRational,parseRational } from "../rational";
import { rationalLatex } from "../transformations";
import { randomFrom } from "../random";

export const logEquationFamilyIds=["mth-log-equation"] as const;
const variants=["single","equal-arguments","sum","difference","two-roots","excluded-root","original-hole","empty","identity-domain"];
const r=(source:string)=>formatRational(parseRational(source));
const rational=(id:string,label:string,expected:string)=>({id,label,kind:"rational",expected:r(expected)});
const roots=(expected:string[])=>({id:"solutions",label:"Complete exact real solution set for x",kind:"logarithmic-roots",expected});
const candidates=(expected:string[])=>({id:"candidates",label:"All distinct algebraic candidates before original-domain checks",kind:"roots",numberSystem:"real",expected,help:"List exact real candidates, separated by commas. Use sqrt() where needed, or none if the algebraic equation has no real candidates."});
const rejected=(expected:string[])=>({id:"rejected",label:"Candidates rejected by the original equation",kind:"roots",numberSystem:"real",expected,help:"List every rejected real candidate, separated by commas, or none."});
const domain=(expected:string)=>({id:"domain",label:"Complete real domain of the original equation",kind:"intervals",expected:parseIntervals(expected),help:"Every logarithm on both sides must exist. Retain strict positivity and all original denominator exclusions."});
export function logEquationQuestion(familyId:string,variant:string,seed:string,id:string):Question{
  if(familyId!=="mth-log-equation")throw new Error("Unknown logarithmic equation family");
  const rng=randomFrom(seed);if(variant==="mixed")variant=variants[rng.integer(0,variants.length-1)];const mode=variants.indexOf(variant);if(mode<0)throw new Error("Unknown logarithmic equation variant");
  const magnitude=rng.shuffle([2,3,5])[0],reciprocal=rng.integer(0,1),bn=reciprocal?1:magnitude,bd=reciprocal?magnitude:1,b=r(bn+"/"+bd),p=rng.integer(-2,3),flag=rng.integer(0,1),natural=mode===0&&flag===1,a=mode===1?rng.integer(1,3):rng.shuffle([-3,-2,-1,1,2,3])[0],d=a+rng.integer(1,3),x0=rng.integer(-4,4),t=rng.integer(1,5),c=mode===1?t-a*x0:rng.integer(-4,4),f=t-d*x0,h=rng.integer(-4,2),width=rng.integer(1,4),k=h+width,s=rng.shuffle([-5,-3,-1,1,3,5])[0],margin=rng.integer(1,4);
  const target=r("("+b+")^("+p+")"),L=natural?"\\ln":"\\log_{"+rationalLatex(b)+"}",left="(x-("+h+"))",right="(x-("+k+"))",A="\\left(x-("+h+")\\right)",B="\\left(x-("+k+")\\right)",half="("+k+",inf)";
  const base={id,familyId,familyVersion:1,courseId:"mth-215",objectiveId:"m05-l03",critical:true,category:"procedural",parameters:{mode,bn,bd,p,flag,a,d,x0,t,c,f,h,width,k,s,margin}};
  if(mode===0){
    const input=a+"*x+("+c+")",originalDomain=formatIntervals(logarithmDomain(input)),argument=natural?"e^("+p+")":target,solution="(("+argument+")-("+c+"))/("+a+")";
    return questionSchema.parse({...base,prompt:"Solve $"+L+"("+a+"x+("+c+"))="+p+"$ exactly over the real numbers. State the original domain first, convert the logarithm to an exponential statement, and give the required argument value and every real solution.",fields:[domain(originalDomain),{id:"argument",label:"Exact argument value required by the logarithm equation",kind:"logarithmic",expected:argument},roots([solution])],hints:["The complete affine argument must be strictly positive. Solving that inequality may reverse its direction when the coefficient is negative.","Convert log_b(A)=p into A=b^p. For a natural logarithm use the exact constant e.","Solve the resulting affine equation and substitute into the original argument. The recovered argument must equal the strictly positive exponential value."],explanation:["The original domain is "+originalDomain+".","The required positive argument is "+argument+", so "+a+"x+("+c+")="+argument+".","The nonzero coefficient gives the unique solution x="+solution+".","Substitution produces the positive argument "+argument+". Taking its original logarithm recovers "+p+", so this candidate is valid."],answerSummary:"Domain "+originalDomain+"; argument "+argument+"; x="+solution+"."});
  }
  if(mode===1){
    const boundary=r("-("+f+")/"+d),originalDomain="("+boundary+",inf)";
    return questionSchema.parse({...base,prompt:"Solve $"+L+"("+a+"x+("+c+"))="+L+"("+d+"x+("+f+"))$ over the real numbers. Find the common original domain, solve by equating arguments, and check the value of both arguments at the proposed solution.",fields:[domain(originalDomain),roots([String(x0)]),rational("argument","Common argument value at the valid solution",String(t))],hints:["Require both original affine arguments to be strictly positive and intersect their two domains.","Logarithms with the same valid base are one-to-one. On the original common domain, equal logarithms imply equal arguments.","Solve the affine equation, then check that both arguments at that input are positive and equal."],explanation:["The two positivity conditions intersect in "+originalDomain+".","Equating arguments gives "+a+"x+("+c+")="+d+"x+("+f+"). Their unequal slopes give x="+x0+".","At that input, both arguments equal "+t+", which is positive. The original logarithms therefore exist and agree.","The underlying affine equation has only this solution, so the original equation cannot have any additional solutions."],answerSummary:"Domain "+originalDomain+"; x="+x0+"; both arguments "+t+"."});
  }
  if(mode===2){
    const constant=r(h*k+"-("+target+")"),discriminant=r(width**2+"+4*("+target+")"),low="("+(h+k)+"-sqrt("+discriminant+"))/2",high="("+(h+k)+"+sqrt("+discriminant+"))/2";
    return questionSchema.parse({...base,prompt:"Solve $"+L+A+"+"+L+B+"="+p+"$ exactly. State the common original domain, combine the logarithms there, and construct the equation $x^2+Cx+D=0$. Give all real algebraic candidates, then retain exactly the valid original solutions.",fields:[domain(half),rational("linear","Coefficient C of x",String(-h-k)),rational("constant","Constant D",constant),candidates([low,high]),roots([high])],hints:["Each separate shifted argument must be positive. A positive product alone is not enough for the original sum of logarithms.","On the common domain, combine the sum into a logarithm of the product and set that product equal to the positive base power.","Solve the quadratic completely. Its smaller candidate makes both original shifted arguments negative; check the larger candidate against each original argument."],explanation:["The original requirements x>"+h+" and x>"+k+" give "+half+".","The product identity gives (x-("+h+"))(x-("+k+"))="+target+", hence x^2+("+(-h-k)+")x+("+constant+")=0.","The discriminant is "+discriminant+", giving candidates "+low+" and "+high+".","Because the positive target makes the square root larger than "+width+", the smaller candidate lies below "+h+" and the larger lies above "+k+". Only the larger candidate is in the common original domain.","At the retained input, both original arguments are positive and their product is "+target+". The sum of their original logarithms is therefore "+p+"."],answerSummary:"Domain "+half+"; C="+(-h-k)+"; D="+constant+"; candidates "+low+", "+high+"; solution "+high+"."});
  }
  if(mode===3){
    const value=parseRational(target),isOne=value.numerator===value.denominator,aboveOne=value.numerator>value.denominator,solution=isOne?null:r("(("+target+")*"+k+"-("+h+"))/("+target+"-1)"),argument="("+left+")/("+right+")";
    return questionSchema.parse({...base,prompt:"Solve $"+L+A+"-"+L+B+"="+p+"$ over the real numbers. Retain the common domain of the original logarithms, construct their combined argument, and list all algebraic candidates before deciding which solve the original equation.",fields:[domain(half),{id:"argument",label:"Combined logarithm argument",kind:"rational-expression",expected:argument,domainFieldId:"domain",help:"Enter one simplified fraction with parentheses around its complete numerator and denominator. Do not include log()."},candidates(solution===null?[]:[solution]),roots(aboveOne&&solution!==null?[solution]:[])],hints:["Each original shifted argument must be positive. Subtraction of logarithms becomes a quotient in the same order.","Set the quotient equal to the positive base power. Check the coefficient after clearing the original nonzero denominator; it may be zero.","If a candidate exists, compare it with the strict original-domain boundary. A positive quotient obtained from two negative arguments does not validate the original logarithms."],explanation:["The original common domain is "+half+", and the combined argument is "+argument+".","The required quotient is "+target+". Clearing the denominator gives (1-("+target+"))x="+h+"-("+target+")("+k+").",isOne?"The x coefficient is zero but the remaining constants differ. This algebraic equation has no candidate.":"The algebraic candidate is x="+solution+". Its distance above the original boundary is "+width+"/("+target+"-1).",aboveOne?"That distance is positive, so both original arguments are positive. Substitution into their quotient gives the required value, validating this unique solution.":"There are no original solutions. "+(isOne?"The reduced equation is contradictory.":"The candidate lies below both shifted zeros and makes both original logarithm arguments negative.")],answerSummary:"Domain "+half+"; combined argument "+argument+"; algebraic candidates "+(solution??"none")+"; valid x solutions "+(aboveOne?solution:"none")+"."});
  }
  if(mode===4){
    const originalDomain="(-inf,"+h+") U ("+h+",inf)",distance="sqrt("+target+")",low=h+"-"+distance,high=h+"+"+distance;
    return questionSchema.parse({...base,prompt:"Solve $"+L+"\\left("+A+"^2\\right)="+p+"$ over the real numbers. Give the original domain, required squared argument, positive distance from x="+h+", and the complete solution set. Do not discard the negative branch of the shifted input.",fields:[domain(originalDomain),{id:"argument",label:"Required squared argument",kind:"logarithmic",expected:target},{id:"distance",label:"Positive distance from the shifted zero",kind:"logarithmic",expected:distance},roots([low,high])],hints:["The square must be strictly positive, so only its zero is excluded from the original logarithm's domain.","Convert to (x-h)^2=b^p, a strictly positive target. Taking a square root gives both signs for x-h.","Keep both shifted roots. Each squares to the positive target and therefore satisfies the original logarithm equation."],explanation:["The original domain is "+originalDomain+".","The squared argument must equal "+target+", giving |x-("+h+")|="+distance+".","Both x="+low+" and x="+high+" are valid. They lie on opposite sides of the excluded shifted zero.","Substitution into the original squared argument yields the positive target for each root. Taking the original logarithm yields "+p+", so neither branch can be omitted."],answerSummary:"Domain "+originalDomain+"; squared argument "+target+"; distance "+distance+"; x="+low+" or "+high+"."});
  }
  if(mode===5){
    const originalDomain=s>0?"("+h+",inf)":"(-inf,"+h+")",valid=h+s;
    return questionSchema.parse({...base,prompt:"Solve $"+L+"\\left("+A+"^2\\right)="+L+"\\left(("+s+")"+A+"\\right)$ over the real numbers. Find the original common domain, equate arguments, list every algebraic candidate, reject invalid candidates, and give the complete solution set.",fields:[domain(originalDomain),candidates([String(h),String(valid)]),rejected([String(h)]),roots([String(valid)])],hints:["The square must be positive and the signed linear argument must also be positive. Their common domain lies on the side selected by the linear coefficient.","Equating arguments gives a quadratic. Bring both terms to one side and factor before canceling a potentially zero factor.","The candidate at the shifted zero makes both logarithm arguments zero and must be rejected. Check the other candidate in both original arguments."],explanation:["The common original domain is "+originalDomain+".","The algebraic equation is (x-("+h+"))[(x-("+h+"))-("+s+")]=0. Its candidates are "+h+" and "+valid+".","At x="+h+", both original arguments are zero, so both logarithms are undefined. This candidate is rejected.","At x="+valid+", both original arguments equal "+s*s+">0. Their logarithms agree, so this is the only original solution."],answerSummary:"Domain "+originalDomain+"; candidates "+h+", "+valid+"; reject "+h+"; solution "+valid+"."});
  }
  if(mode===6){
    const originalDomain="("+h+","+k+") U ("+k+",inf)";
    return questionSchema.parse({...base,prompt:"Solve $"+L+"\\left(\\frac{"+A+B+"}{"+B+"}\\right)="+L+"("+width+")$. Give the original domain before cancellation, the simplified left argument with its original restrictions, all algebraic candidates, rejected candidates, and the complete solution set.",fields:[domain(originalDomain),{id:"argument",label:"Simplified left logarithm argument",kind:"rational-expression",expected:left,domainFieldId:"domain",help:"Enter the simplified expression using x and arithmetic. Preserve the original excluded denominator input in the separate domain answer."},candidates([String(k)]),rejected([String(k)]),roots([])],hints:["Check the original denominator before canceling its common factor. The full logarithm argument must also be positive.","Where cancellation is allowed, the left argument simplifies to x-h. The same valid log base permits equating arguments.","The resulting candidate lands on the canceled denominator zero. It is excluded from the original equation even though the simplified equation can be evaluated there."],explanation:["The original domain is "+originalDomain+"; x="+k+" is excluded by its zero denominator.","Away from that hole the left argument simplifies to x-("+h+"). Equating it with "+width+" gives x="+k+".","This sole algebraic candidate is the original hole. It cannot be substituted into the original fraction, so it is rejected.","There are no real solutions to the original equation. The algebraically simplified expression must retain its original restriction."],answerSummary:"Domain "+originalDomain+"; simplified argument "+left+"; candidate and rejected input "+k+"; no real solutions."});
  }
  if(mode===7){
    const constant=r(target+"+"+margin),square=flag?r("-("+target+")-("+constant+")"):String(-margin),originalDomain=flag?"empty":"R",argument=(flag?"-":"")+"\\left("+A+"^2+"+rationalLatex(constant)+"\\right)";
    return questionSchema.parse({...base,category:"conceptual",prompt:"Solve $"+L+"\\left("+argument+"\\right)="+p+"$ over the real numbers. Check the original domain first. For an algebraic comparison, give the value that the square $(x-("+h+"))^2$ would have to equal, then report the complete real solution set.",fields:[domain(originalDomain),rational("square","Value the real square would have to equal",square),roots([])],hints:["A real square is nonnegative. Compare the entire signed argument with zero before using the logarithm.","A defined logarithm equal to p would require its argument to be the positive base power. Rearrange that necessary condition for the square.","A real square cannot equal a negative value. If the original domain is empty, there are already no original inputs to consider."],explanation:["The added constant "+constant+" is positive. "+(flag?"The outside minus sign makes the whole argument negative for every real x, so the original domain is empty.":"The whole argument is positive for every real x, so the original domain is R."),"The necessary exponential target is "+target+". Rearranging would require (x-("+h+"))^2="+square+".","That right-hand side is negative, so there are no real algebraic candidates and no real original solutions.",flag?"This formal comparison does not give meaning to an undefined logarithm. The original-domain failure alone already rules out all solutions.":"A nonempty original domain does not guarantee an equation has a solution; this target is below the minimum possible argument."],answerSummary:"Original domain "+originalDomain+"; required square "+square+"; no real solutions."});
  }
  const outside="(-inf,"+h+") U ("+k+",inf)",combined=flag?"\\frac{"+A+"}{"+B+"}":A+B;
  return questionSchema.parse({...base,category:"conceptual",prompt:"Find the complete real solution set of $"+L+"\\left("+combined+"\\right)="+L+A+(flag?"-":"+")+L+B+"$. Give the complete domain of each side separately, then determine every input for which this original equation is true.",fields:[{...domain(outside),id:"left-domain",label:"Complete real domain of the left side"},{...domain(half),id:"right-domain",label:"Complete real domain of the right side"},{id:"solutions",label:"Complete real solution set",kind:"intervals",expected:parseIntervals(half),help:"Use interval notation for the entire solution set; R means every real number."},{id:"reason",label:"Why is this the complete solution set?",kind:"choice",correct:"common-domain",options:rng.shuffle([{id:"common-domain",label:"The logarithm identity holds for every input in the common original domain",feedback:"Both individual arguments must be positive. The identity then proves equality for every input in that intersection."},{id:"all-real",label:"A logarithm identity makes every real input valid",feedback:"An identity cannot create logarithms of zero or negative arguments."},{id:"left-domain",label:"Only the combined expression's domain matters",feedback:"Both sides of an equation must be defined. Two negative factors or terms can make the combined argument positive without defining the separate logarithms."}])}],hints:["The combined argument is positive when both shifted terms have the same sign, while the separate logarithms require each term to be positive.","Intersect the original domains of both sides. Inputs accepted by only the left side are not solutions of the equation.","On that intersection, the valid same-base product or quotient identity proves equality for every input. Report the whole interval, not a sample point."],explanation:["The left-side domain is "+outside+". The right-side domain is "+half+".","The original equation's common domain is their intersection, "+half+".","Both arguments are positive throughout that interval. The "+(flag?"quotient":"product")+" identity proves equality there for every input.","The complete solution set is therefore "+half+". Inputs in the additional negative branch of the left expression do not define the original right side."],answerSummary:"Left domain "+outside+"; right domain "+half+"; complete solution set "+half+"; identity on the common original domain."});
}
