import { questionSchema,type Question } from "../contracts";
import { formatRational,parseRational } from "../rational";
import { randomFrom } from "../random";
import { variationOutput,variationScale,type VariationRule } from "../variation";

export const basicVariationFamilyIds=["mth-direct-variation","mth-inverse-variation"] as const;
const r=(source:string)=>formatRational(parseRational(source));
const exact=(id:string,label:string,expected:string,unit="")=>({id,label,kind:"rational",expected:r(expected),unit});
const roots=(id:string,label:string,expected:string[])=>({id,label,kind:"roots",numberSystem:"real",expected,help:"List every distinct real input, separated by commas, or type empty if none qualifies."});
const choices=(id:string,label:string,correct:string,options:[string,string,string][])=>({id,label,kind:"choice",correct,options:options.map(([id,label,feedback])=>({id,label,feedback}))});
const intervals=(id:string,label:string,expected:{lower:string|null;upper:string|null;lowerClosed:boolean;upperClosed:boolean}[])=>({id,label,kind:"intervals",expected,help:"Use U between intervals, parentheses for excluded endpoints, and -inf or inf for unbounded ends."});
const model=(p:number):VariationRule=>({xPower:{numerator:p,denominator:1},zPower:{numerator:0,denominator:1}});
export function basicVariationQuestion(familyId:string,variant:string,seed:string,id:string):Question{
  const rng=randomFrom(seed),direct=familyId==="mth-direct-variation";
  if(!direct&&familyId!=="mth-inverse-variation")throw new Error("Unknown basic variation family");
  const variants=direct?["linear-calibration","signed-constant","square","cube","target-input","affine-rejection","zero-calibration","unit-change"]:["reciprocal","inverse-square","inverse-cube","scale-ratio","target-input","impossible-target","zero-exclusion","inverse-not-linear"];
  if(variant==="mixed")variant=variants[rng.integer(0,variants.length-1)];const mode=variants.indexOf(variant);if(mode<0)throw new Error("Unknown basic variation variant");
  const a=rng.integer(1,5),b=a+rng.integer(1,5),kn=rng.integer(1,6)*(direct&&mode===1?-1:1),kd=rng.integer(1,4),k=r(kn+"/"+kd),offset=rng.integer(1,6),flag=rng.integer(0,1),scaleNumerator=[1,2,3,1][rng.integer(0,3)],scaleDenominator=scaleNumerator===1?2:scaleNumerator===3?2:1;
  const p=direct?(mode===2||mode===4?2:mode===3?3:mode===7?1+flag:1):-(mode===1||mode===4?2:mode===2?3:mode>=3?1+rng.integer(0,2):1);
  const rule=model(p),baseline={x:String(a),z:"1"},changed={x:String(b),z:"1"},y=variationOutput(rule,k,baseline).exact!,next=variationOutput(rule,k,changed).exact!;
  const base={id,familyId,familyVersion:1,courseId:"mth-215",objectiveId:"m04-l03",critical:true,category:"procedural",parameters:{mode,a,b,kn,kd,p,offset,flag,scaleNumerator,scaleDenominator}};
  const units=choices("units","Units of the variation constant","correct",[
    ["correct",p>0?"m / s"+(p===1?"":"^"+p):"m * s"+(p===-1?"":"^"+(-p)),"Divide the output unit by the complete input power. A negative input power moves seconds into the constant's numerator."],
    ["reversed",p>0?"s"+(p===1?"":"^"+p)+" / m":"1 / (m * s"+(p===-1?"":"^"+(-p))+")","The coefficient's units must produce meters after multiplication by x to the specified power."],
    ["none","Dimensionless","The response is measured in meters and the input in seconds, so the constant needs units."],
  ]);
  if(direct&&mode===5){
    const first=r("("+k+")*"+a+"+"+offset),second=r("("+k+")*"+(2*a)+"+"+offset),ratio1=r("("+first+")/"+a),ratio2=r("("+second+")/"+(2*a));
    return questionSchema.parse({...base,category:"conceptual",prompt:"A supplied rule is y = ("+k+")x + "+offset+". A learner calls it direct proportionality to x because it is a line. Check that claim using x = "+a+" and x = "+(2*a)+", and identify the output at zero.",fields:[exact("first","First ratio y / x",ratio1),exact("second","Second ratio y / x",ratio2),exact("zero","Output at x = 0",String(offset)),choices("model","Model classification","affine",[["affine","Affine with a nonzero offset, not direct proportionality to x","A nonzero intercept and changing y/x ratios rule out y=kx."],["direct","Direct proportionality to x","A straight graph must also pass through the origin to have the form y=kx."],["inverse","Inverse proportionality to x","An affine rule is not a reciprocal law merely because its ratios change."]])],hints:["Compute the two outputs before dividing each by its own input.","A direct model y=kx must give the same y/x ratio at both nonzero inputs.","The supplied nonzero offset remains when x is zero."],explanation:["The two ratios are "+ratio1+" and "+ratio2+", so they are not one constant.","The output at zero is "+offset+", whereas y=kx would give zero.","This is a supplied affine rule with an offset. Being a line alone does not establish direct proportionality."],answerSummary:"Ratios "+ratio1+" and "+ratio2+"; zero output "+offset+"; affine."});
  }
  if(direct&&mode===6){
    const observed=flag?offset:0,second=r("("+k+")*"+a);
    return questionSchema.parse({...base,category:"conceptual",prompt:"Assume a proposed direct model y=kx with nonzero k. One exact record says y="+observed+" when x=0. A second record says y="+second+" when x="+a+". Classify what the first record establishes, calculate k from the second record alone, and decide whether both records can belong to one direct model.",fields:[choices("first","Information from the zero-input record",flag?"inconsistent":"underdetermined",[["underdetermined","It does not identify k","When both input and output are zero, every nonzero k fits that record."],["inconsistent","It contradicts the proposed model","A direct rule gives zero at zero; a nonzero output there contradicts it."],["unique","It uniquely identifies k as zero","Dividing zero by zero is undefined, and this model requires a nonzero constant."]]),exact("constant","Constant from the nonzero-input record alone",k),choices("combined","Can one nonzero constant satisfy both records?",flag?"no":"yes",[["yes","Yes","The zero record must be compatible, and the nonzero record identifies k."],["no","No","A nonzero output at zero cannot be repaired by fitting the other record."]])],hints:["Substitute zero into y=kx without dividing by x.","The second record has a nonzero input, so its ratio y/x identifies a candidate k.",flag?"The first record still contradicts y=kx after the second record is fitted.":"The first record is compatible with the unique constant identified by the second."],explanation:[flag?"The first record contradicts direct proportionality because it assigns a nonzero output to zero.":"The first record leaves k unidentified because k times zero is zero for every k.","The second record alone gives k="+k+".",flag?"No constant satisfies both exact records.":"Together the records identify that nonzero constant."],answerSummary:(flag?"Inconsistent first record; no shared model":"Underdetermined first record; shared model exists")+"; second-record k="+k+"."});
  }
  if(direct&&mode===7){
    const converted=r("("+k+")/100^"+p),physicalX=100*a;
    return questionSchema.parse({...base,category:"application",prompt:"The supplied model y=kx^"+p+" uses x in meters and y in volts. It gives y="+y+" V at x="+a+" m. Rewrite it as y=c u^"+p+" when u is the numerical length in centimeters. Since u=100x, the same length is u="+physicalX+" cm. Find both coefficients and check the response at that length.",fields:[exact("constant","Original coefficient k",k),exact("converted","Coefficient c for centimeter inputs",converted),exact("output","Response at the same physical length",y,"V"),choices("units","Units of the new coefficient","new",[["new","V / cm"+(p===1?"":"^"+p),"The new input is a numerical length in centimeters, so its full power belongs in the coefficient's unit denominator."],["old","V / m"+(p===1?"":"^"+p),"Keeping the old coefficient units would not describe the requested centimeter-input form."],["none","Dimensionless","The coefficient relates voltage to a length power and is not dimensionless."]])],hints:["First recover k from the meter-based calibration record.","Substitute x=u/100 into the whole power: (u/100)^p=u^p/100^p.","The coefficient changes to k/100^p, but the physical response at the same length stays unchanged."],explanation:["The original coefficient is "+k+"; the new coefficient is "+converted+".","At u="+physicalX+", the output remains "+y+" V.","Constants can have different numerical values when units change. Compare their units and definitions before treating them as conflicting calibrations."],answerSummary:"k="+k+", c="+converted+"; response "+y+" V; coefficient unit V/cm"+(p===1?"":"^"+p)+"."});
  }
  if(mode===4){
    const magnitude=String(b),originalDomain=direct?[]:["0"];
    return questionSchema.parse({...base,category:"application",prompt:"A supplied model is $y="+(direct?"("+k+")x^2":"\\frac{"+k+"}{x^2}")+"$. Find every real algebraic input producing y="+next+", then retain the input allowed by the physical requirement x>0. "+(direct?"The polynomial rule has no excluded real input.":"Retain the original denominator restriction."),fields:[roots("algebraic","All real algebraic candidate inputs",["-"+magnitude,magnitude]),roots("allowed","Physically allowed inputs",[magnitude]),roots("excluded","Inputs excluded by the original formula",originalDomain)],hints:["Rearrange the equation into x squared equal to a positive number.","A positive square has two real square-root candidates, one positive and one negative.","The physical condition keeps only the positive candidate; denominator exclusions remain separate."],explanation:["The algebraic candidates are -"+b+" and "+b+".","The physical condition x>0 retains "+b+" only.",direct?"No real input is excluded by this polynomial formula itself.":"The reciprocal-square formula also excludes zero, independently of the target equation."],answerSummary:"Candidates -"+b+", "+b+"; allowed "+b+"; original exclusions "+(direct?"none":"0")+"."});
  }
  if(!direct&&mode===3){
    const ratio=r(scaleNumerator+"/"+scaleDenominator),newInput=r(a+"*("+ratio+")"),factor=variationScale(rule,baseline,{x:newInput,z:"1"}).exact!,output=variationOutput(rule,k,{x:newInput,z:"1"}).exact!,percent=r("100*(("+factor+")-1)");
    return questionSchema.parse({...base,category:"application",prompt:"A positive response y varies inversely with x to power "+(-p)+". At x="+a+" the response is "+y+". The input is multiplied by "+ratio+", with the model constant and units unchanged. Find the output multiplier, new response, and signed percentage change in the response. A decrease has a negative percentage.",fields:[exact("factor","Output multiplier",factor),exact("output","New response",output),exact("percent","Signed percentage change",percent,"%")],hints:["For inverse power n, an input multiplier s gives output multiplier 1/s^n.","Multiply the original response by that factor, rather than subtracting the input change.","The signed percentage change is 100 times (output multiplier minus 1)."],explanation:["The input factor "+ratio+" produces output factor "+factor+".","The new response is "+output+".","The signed percentage change is "+percent+"%. This compares the changed output with its baseline, not with the changed input."],answerSummary:"Factor "+factor+"; response "+output+"; change "+percent+"%."});
  }
  if(!direct&&mode===5){
    const target=flag?r("-("+next+")"):"0",candidates=flag&&Math.abs(p)%2===1?["-"+b]:[];
    return questionSchema.parse({...base,category:"application",prompt:"The supplied inverse-power model is $y=\\frac{"+k+"}{x^{"+(-p)+"}}$ with physical inputs x>0. Find all real algebraic inputs for target y="+target+", then state the physically allowed inputs and original exclusions.",fields:[roots("algebraic","All real algebraic candidate inputs",candidates),roots("allowed","Physically allowed inputs",[]),roots("excluded","Inputs excluded by the original formula",["0"])],hints:["The model has positive output for every positive input because its constant is positive.",flag?"A negative target may have a negative real candidate when the denominator power is odd; an even power cannot produce a negative target here.":"A nonzero numerator divided by a finite nonzero value never equals zero.","Apply the physical input condition after finding real algebraic candidates. Infinity is not an input solution."],explanation:[flag?"The negative target has "+(candidates.length?"the real candidate -"+b:"no real candidate for this even power")+".":"No finite real input makes this nonzero-numerator reciprocal equal zero.","No candidate satisfies the positive physical-input requirement.","The original formula excludes zero regardless of the target."],answerSummary:"Real candidates "+(candidates.join(",")||"none")+"; physically allowed none; original exclusion 0."});
  }
  if(!direct&&mode===6)return questionSchema.parse({...base,category:"application",prompt:"A supplied response model is $y=\\frac{"+k+"}{x^{"+(-p)+"}}$. Its validated operating inputs are positive and no greater than "+b+" seconds. State its full mathematical domain, its allowed operating domain, and its response at the upper operating endpoint.",fields:[intervals("mathematical","Full real mathematical domain",[{lower:null,upper:"0",lowerClosed:false,upperClosed:false},{lower:"0",upper:null,lowerClosed:false,upperClosed:false}]),intervals("operating","Allowed operating domain",[{lower:"0",upper:String(b),lowerClosed:false,upperClosed:true}]),exact("output","Response at the upper operating endpoint",next)],hints:["The integer-power denominator is zero only at zero.","Intersect the mathematical domain with x>0 and x no greater than the stated upper bound.","The upper bound is included and nonzero, so substitute it into the original model."],explanation:["The mathematical domain contains negative and positive nonzero inputs.","The supplied model permits only (0,"+b+"]. Its positive upper endpoint is included.","At that endpoint the response is "+next+". A value outside the operating interval can be mathematically defined without being validated for the supplied application."],answerSummary:"Mathematical: (-inf,0) U (0,inf); operating: (0,"+b+"]; response "+next+"."});
  if(!direct&&mode===7){
    const slope=rng.integer(1,4),intercept=slope*(a+3)+offset,xs=[a,a+1,a+2],ys=xs.map(x=>intercept-slope*x),products=xs.map((x,i)=>x*ys[i]);
    return questionSchema.parse({...base,category:"conceptual",parameters:{...base.parameters,slope,intercept},prompt:"Three exact records have inputs "+xs.join(", ")+" and corresponding positive outputs "+ys.join(", ")+". The outputs decrease as inputs increase. Compute each product xy and decide whether these records support simple inverse proportionality y=k/x. Do not infer an entire physical law from three records.",fields:[...products.map((value,i)=>exact("product"+i,"Product xy for record "+(i+1),String(value))),choices("conclusion","Conclusion supported by the records","affine",[["affine","They fit a decreasing affine line, but do not fit one y=k/x rule","The products are not all equal. Equal output differences over equal input steps make these records collinear, without proving a law between records."],["inverse","They fit one y=k/x rule because the outputs decrease","A decreasing trend alone does not establish a constant product."],["both","They prove both an affine and an inverse law for all real inputs","Finite records do not establish every unseen input, and the inverse products disagree."]])],hints:["Multiply each input by its corresponding output.","Simple inverse variation requires every product xy to equal the same k.","Decreasing output is not sufficient; compare all three products rather than only the direction of change."],explanation:["The products are "+products.join(", ")+", which are not all equal.","These records do not fit one simple inverse-proportional rule.","Their equal-step differences fit a decreasing affine line at the recorded inputs; this does not establish behavior between observations."],answerSummary:"Products "+products.join(", ")+"; affine-compatible records, not simple inverse proportionality."});
  }
  const word=p===1?"x":p===2?"the square of x":p===3?"the cube of x":p===-1?"x":p===-2?"the square of x":"the cube of x",factor=variationScale(rule,baseline,changed).exact!;
  return questionSchema.parse({...base,prompt:"A response y, in meters, varies "+(direct?"directly with ":"inversely with ")+word+". The input x is in seconds. An exact observation gives y="+y+" when x="+a+". Write the rule as y=kx^p by finding k and p, predict y at x="+b+", and state the output multiplier and coefficient units. Keep the same units and constant throughout.",fields:[exact("constant","Variation constant k",k),exact("power","Exponent p in y = k x^p",String(p)),exact("output","Predicted response",next,"m"),exact("factor","Output multiplier from the observation",factor),units],hints:["Translate the specified power into y=kx^p. An inverse power gives a negative exponent.","Use the complete calibration record: divide y by x^p to find k, then substitute the new input.","The output multiplier is (new input / old input)^p. The constant's unit is meters divided by seconds to power p."],explanation:["The power is "+p+", and the calibration gives k="+k+".","At x="+b+", the response is "+next+" m.","The output multiplier is "+factor+". "+(kn<0?"A negative constant makes the direct response decrease with input; it does not turn the direct model into an inverse model.":"The specified exponent, not the size of an additive input change, controls this multiplier."),"The coefficient carries the units needed to leave meters after multiplication by x^p."],answerSummary:"k="+k+", p="+p+", response "+next+" m, multiplier "+factor+"."});
}
