import { questionSchema, type Question } from "../contracts";
import { formatRational, parseRational } from "../rational";
import { randomFrom } from "../random";

export const foundationCoordinateFamilyIds = ["mth-coordinate-read", "mth-line-slope", "mth-measurement-units", "mth-linear-intercept"];
export function foundationCoordinateQuestion(familyId: string, variant: string, seed: string, id: string): Question {
  const rng = randomFrom(seed), base = { id, familyId, familyVersion: 1, courseId: "mth-215", objectiveId: "b05" };
  if (familyId === "mth-coordinate-read") {
    if (!["scaled", "axes"].includes(variant)) throw new Error("Unknown coordinate reading variant");
    const axis = rng.integer(0, 1), xTicks = variant === "axes" && axis === 0 ? 0 : rng.integer(-4, 4), yTicks = variant === "axes" && axis === 1 ? 0 : rng.integer(-4, 4);
    const scale = rng.integer(0, 2), xStep = [1, 2, 5][scale], yStep = [1, 2, 5][(scale+1)%3], x = xTicks*xStep, y = yTicks*yStep;
    return questionSchema.parse({ ...base, parameters: { xTicks, yTicks, xStep, yStep }, category: variant === "scaled" ? "application" : "conceptual", critical: true,
      prompt: "Read the coordinates of point A from the graph. Use each axis's labeled scale and keep the horizontal coordinate first.",
      figure: { kind: "coordinates", title: "Read point A", xLabel: "Voltage (V)", yLabel: "Current (mA)", xStep, yStep, points: [{ name: "A", xTicks, yTicks }] },
      fields: [{ id: "x", kind: "rational", label: "Horizontal coordinate", expected: String(x), unit: "V" }, { id: "y", kind: "rational", label: "Vertical coordinate", expected: String(y), unit: "mA" }],
      hints: ["Read the value of a tick interval on each axis. The two scales need not match.", `Each horizontal interval represents ${xStep} V; each vertical interval represents ${yStep} mA. Left and below the origin use negative signs.`, `Multiply the signed tick counts: x=${xTicks} times ${xStep}, and y=${yTicks} times ${yStep}.`],
      explanation: [`The horizontal coordinate is $${xTicks}(${xStep})=${x}$ V.`, `The vertical coordinate is $${yTicks}(${yStep})=${y}$ mA.`, "A point on an axis has zero displacement in the perpendicular direction. Reading the two coordinates in reverse gives a different point."], answerSummary: `(${x} V, ${y} mA)` });
  }
  if (familyId === "mth-line-slope") {
    if (!["general", "horizontal", "vertical"].includes(variant)) throw new Error("Unknown slope variant");
    const [ax, otherX] = rng.shuffle(Array.from({ length: 9 }, (_, i) => i-4)), [ay, otherY] = rng.shuffle(Array.from({ length: 9 }, (_, i) => i-4));
    const bx = variant === "vertical" ? ax : otherX, by = variant === "horizontal" ? ay : otherY, xStep = rng.integer(1, 2), yStep = [1, 5][rng.integer(0, 1)], run = (bx-ax)*xStep, rise = (by-ay)*yStep;
    const expected = run === 0 ? "undefined" : formatRational(parseRational(`${rise}/${run}`));
    const figure = { kind: "coordinates", title: "Line through A and B", xLabel: "Voltage (V)", yLabel: "Current (mA)", xStep, yStep, points: [{ name: "A", xTicks: ax, yTicks: ay }, { name: "B", xTicks: bx, yTicks: by }], line: true };
    const fields = run === 0 ? [
      { id: "slope", kind: "choice", label: "Slope of the line", correct: "undefined", options: rng.shuffle([{ id: "undefined", label: "Undefined", feedback: "Two distinct points have the same horizontal coordinate, so rise divided by run would divide by zero." }, { id: "zero", label: "Zero", feedback: "Zero slope requires zero rise and nonzero run. This line has zero run." }, { id: "one", label: "One", feedback: "A slope of one needs equal nonzero rise and run in the stated units." }]) },
      { id: "reason", kind: "choice", label: "Reason", correct: "run", options: rng.shuffle([{ id: "run", label: "The horizontal change is zero", feedback: "A vertical line has no finite slope." }, { id: "rise", label: "The vertical change is zero", feedback: "The plotted points have different vertical coordinates. Zero vertical change would make a horizontal line." }, { id: "same", label: "The two points are identical", feedback: "The points share a horizontal coordinate but have different vertical coordinates." }]) },
    ] : [{ id: "slope", kind: "rational", label: "Numerical slope", expected, help: "Use vertical change divided by horizontal change. Keep fractions exact." }, { id: "unit", kind: "choice", label: "Slope unit", correct: "y-per-x", options: rng.shuffle([{ id: "y-per-x", label: "mA per V", feedback: "Slope divides a change in the vertical quantity by a change in the horizontal quantity." }, { id: "x-per-y", label: "V per mA", feedback: "These units describe the reciprocal ratio, horizontal change divided by vertical change." }, { id: "y-only", label: "mA", feedback: "Current alone is a coordinate. A slope also accounts for the change in voltage." }]) }];
    return questionSchema.parse({ ...base, parameters: { ax, ay, bx, by, xStep, yStep, run, rise }, category: variant === "general" ? "application" : "conceptual", critical: true,
      prompt: `Find the slope of the straight line through A = (${ax*xStep} V, ${ay*yStep} mA) and B = (${bx*xStep} V, ${by*yStep} mA). Distinguish a horizontal line from a vertical line.`, figure, fields,
      hints: ["Use (vertical coordinate of B minus vertical coordinate of A) divided by (horizontal coordinate of B minus horizontal coordinate of A).", `The rise from A to B is ${rise} mA and the run is ${run} V.`, run === 0 ? "A nonzero rise divided by zero has no finite value." : `The ratio is ${rise}/${run}, in mA per V.`],
      explanation: [`Using the same point order in both differences gives rise ${rise} mA and run ${run} V.`, run === 0 ? "The run is zero while the rise is nonzero. This is a vertical line with undefined slope." : `The exact slope is ${expected} mA per V. ${rise === 0 ? "Zero rise with nonzero run makes the line horizontal." : "Reversing the point order changes both signs, so the ratio stays the same."}`, "The visual angle alone does not determine a numerical slope unless you account for both axis scales."], answerSummary: run === 0 ? "Undefined slope because the horizontal change is zero." : `${expected} mA per V.` });
  }
  if (familyId === "mth-measurement-units") {
    if (!["ms-to-s", "s-to-ms", "mm-to-m", "rate"].includes(variant)) throw new Error("Unknown unit conversion variant");
    const count = rng.integer(-9, 9)*125, seconds = rng.integer(-9, 9)/10, length = rng.integer(2, 9), milliseconds = rng.integer(1, 8)*125;
    const expected = variant === "s-to-ms" ? String(seconds*1000) : variant === "rate" ? formatRational(parseRational(`${length}*1000/${milliseconds}`)) : formatRational(parseRational(`${count}/1000`));
    const prompt = variant === "ms-to-s" ? `A recorded time offset is ${count} ms. Convert that signed offset to seconds.` : variant === "s-to-ms" ? `A recorded time offset is ${seconds} s. Convert it to milliseconds.` : variant === "mm-to-m" ? `A signed position is ${count} mm relative to a reference. Convert it to meters.` : `A distance increases by ${length} m during ${milliseconds} ms. Convert the time interval to seconds and calculate the average rate in m/s.`;
    return questionSchema.parse({ ...base, parameters: { count, seconds, length, milliseconds }, category: variant === "rate" ? "application" : "procedural", critical: true, prompt,
      fields: variant === "rate" ? [{ id: "time", kind: "rational", label: "Time interval", expected: `${milliseconds}/1000`, unit: "s" }, { id: "value", kind: "rational", label: "Average rate", expected, unit: "m/s" }] : [{ id: "value", kind: "rational", label: "Converted value", expected, unit: variant === "s-to-ms" ? "ms" : variant === "mm-to-m" ? "m" : "s" }],
      hints: ["The prefix milli means one thousandth of the base unit. Keep the sign of the original value.", variant === "s-to-ms" ? "Each second contains 1000 milliseconds." : "Divide the number of milliseconds or millimeters by 1000 to obtain the base unit.", variant === "rate" ? `The interval is ${milliseconds}/1000 seconds; divide ${length} meters by that time.` : `The converted value is ${expected}.`],
      explanation: [variant === "s-to-ms" ? `${seconds} s times 1000 ms/s gives ${expected} ms.` : variant === "mm-to-m" ? `${count} mm times 1 m/1000 mm gives ${expected} m.` : variant === "rate" ? `${milliseconds} ms equals ${milliseconds}/1000 s. The rate is ${length} divided by that time, giving ${expected} m/s.` : `${count} ms times 1 s/1000 ms gives ${expected} s.`, "A unit conversion changes the numerical representation of the same quantity, not the quantity itself. Check that the unwanted unit cancels."], answerSummary: variant === "rate" ? `${milliseconds}/1000 s; ${expected} m/s.` : `${expected} ${variant === "s-to-ms" ? "ms" : variant === "mm-to-m" ? "m" : "s"}.` });
  }
  if (familyId === "mth-linear-intercept") {
    if (variant !== "position") throw new Error("Unknown intercept variant");
    const velocity = rng.integer(1, 5)*(rng.integer(0, 1) ? -1 : 1), initial = rng.integer(-10, 10), time = rng.integer(1, 8), position = velocity*time+initial;
    return questionSchema.parse({ ...base, parameters: { velocity, initial, time }, category: "application", critical: false,
      prompt: `A position model is $d(t)=${velocity}t${initial < 0 ? "-" : "+"}${Math.abs(initial)}$, with t in seconds and d in meters, for t≥0. Identify the vertical intercept's meaning and predict the position at t=${time} s.`,
      fields: [{ id: "initial", kind: "rational", label: "Vertical intercept value", expected: String(initial), unit: "m" }, { id: "meaning", kind: "choice", label: "Meaning of the vertical intercept", correct: "start", options: rng.shuffle([{ id: "start", label: "Position when t = 0", feedback: "The vertical axis is reached when the horizontal time coordinate is zero." }, { id: "rate", label: "Change in position during each second", feedback: "That is the slope, with units m/s. The intercept has units m." }, { id: "crossing", label: "The time when the position is zero", feedback: "That would be a horizontal intercept, with units s, if it lies in the model's domain." }]) }, { id: "position", kind: "rational", label: "Position at the stated time", expected: String(position), unit: "m" }],
      hints: ["At the vertical intercept, the horizontal input t is zero.", `Substitute t=0 to find the initial position, then substitute t=${time}.`, `The initial position is ${initial} m and the later position is ${position} m.`],
      explanation: [`The vertical intercept is (0 s, ${initial} m), so the object starts ${initial} m from the chosen reference in the signed coordinate system.`, `The slope is ${velocity} m/s. At t=${time} s, the position is ${velocity} times ${time} plus ${initial}, or ${position} m.`, "A negative position describes a location on the negative side of the reference. It does not make the elapsed time negative."], answerSummary: `Intercept ${initial} m means position at t=0; predicted position ${position} m.` });
  }
  throw new Error("This question family is not available.");
}
