import { questionSchema,type Question } from "../contracts";
import { logarithmValue } from "../logarithmic-functions";
import { formatRational,parseRational } from "../rational";
import { rationalLatex } from "../transformations";
import { randomFrom } from "../random";

export const logInverseFamilyIds=["mth-log-inverse"] as const;
const variants=["identify-parts","exponential-to-log","log-to-exponential","exact-integer","exact-reciprocal","fractional-exponent","fractional-base","common-natural"];
const r=(value:string)=>formatRational(parseRational(value));
const field=(id:string,label:string,expected:string)=>({id,label,kind:"rational",expected:r(expected),help:"Give an exact number or fraction."});
const numeric=(id:string,label:string,expected:number)=>({id,label,kind:"numeric",expected,absoluteTolerance:.00000051,relativeTolerance:0,help:"Use the lesson calculator and round the final value to six decimal places."});
export function logInverseQuestion(familyId:string,variant:string,seed:string,id:string):Question{
  if(familyId!=="mth-log-inverse")throw new Error("Unknown logarithm inverse family");
  const rng=randomFrom(seed);if(variant==="mixed")variant=variants[rng.integer(0,variants.length-1)];const mode=variants.indexOf(variant);if(mode<0)throw new Error("Unknown logarithm inverse variant");
  const root=rng.integer(2,5),degree=mode===5?rng.integer(2,3):1,p=mode===3?rng.integer(0,5):mode===5?rng.shuffle([-5,-3,-1,1,3,5])[0]:mode===6?rng.shuffle([-4,-3,-2,2,3,4])[0]:-rng.integer(1,4),natural=rng.integer(-4,4),common=rng.integer(-4,4),pair=mode===6?rng.shuffle([[1,2],[2,3],[3,4]])[0]:[root**degree,1];
  const [bn,bd]=pair,b=r(bn+"/"+bd),exponent=r(p+"/"+degree),argument=mode===5?r(root+"^("+p+")"):r("("+b+")^("+p+")");
  const value=logarithmValue({kind:"rational-base",base:b},argument);if(value.status!=="defined"||value.exact!==exponent)throw new Error("The authored logarithm power relation must be exact.");
  const logarithm="\\log_{"+rationalLatex(b)+"}\\left("+rationalLatex(argument)+"\\right)",power="\\left("+rationalLatex(b)+"\\right)^{"+rationalLatex(exponent)+"}";
  const choice=(id:string,label:string,correct:string,options:{id:string;label:string;feedback:string}[])=>({id,label,kind:"choice",correct,options:rng.shuffle(options)});
  const positiveArgument=choice("argument-rule","Allowed real logarithm arguments","positive",[
    {id:"positive",label:"Strictly positive arguments only",feedback:"Every real power of a valid positive base is positive. Zero is excluded."},
    {id:"nonnegative",label:"Zero or positive arguments",feedback:"No finite real exponent makes a positive base equal zero."},
    {id:"all",label:"Every real argument",feedback:"Negative arguments also fail to be outputs of a real positive-base exponential."},
  ]);
  const base={id,familyId,familyVersion:1,courseId:"mth-215",objectiveId:"m05-l02",critical:true,category:"procedural",parameters:{mode,root,degree,p,bn,bd,natural,common}};
  if(mode<=2){
    const statement=mode===1?power+"="+rationalLatex(argument):logarithm+"="+rationalLatex(exponent);
    const meaning=choice("meaning","What does the logarithm output represent?","exponent",[
      {id:"exponent",label:"The exponent applied to the base to obtain the argument",feedback:"A logarithm recovers the exponent in the equivalent exponential statement."},
      {id:"quotient",label:"The argument divided by the base",feedback:"Division by the base is not the inverse of raising the base to a variable exponent."},
      {id:"product",label:"The base multiplied by the argument",feedback:"Multiplication does not recover the exponent."},
    ]);
    const prompt=mode===0?"Identify the base, argument and output in $"+statement+"$. Explain what that output means and state the restriction on real logarithm arguments.":mode===1?"Rewrite $"+statement+"$ as a logarithmic statement by supplying its base, argument and value. Explain the recovered value's meaning and state the allowed real argument values.":"Rewrite $"+statement+"$ in exponential form by supplying the base, exponent and resulting power value. Explain the logarithm's role and state its real argument restriction.";
    return questionSchema.parse({...base,prompt,fields:mode===2?[field("base","Exponential base",b),field("exponent","Exponent",exponent),field("result","Result of the power",argument),meaning,positiveArgument]:[field("base","Logarithm base",b),field("argument","Logarithm argument",argument),field("value","Logarithm output",exponent),meaning,positiveArgument],hints:["Read log base b of A equals u as b raised to u equals A.","Keep the base in the base position. The logarithm's output becomes the exponent.","A negative exponent gives a positive reciprocal power. It does not require a negative logarithm argument."],explanation:["The base is "+b+", the argument is "+argument+", and the recovered exponent is "+exponent+".","The equivalent statements are $"+logarithm+"="+rationalLatex(exponent)+"$ and $"+power+"="+rationalLatex(argument)+"$.","The negative logarithm output is valid because the argument remains strictly positive. The logarithm recovers an exponent, not a quotient."],answerSummary:"Base "+b+"; argument or power result "+argument+"; exponent or log output "+exponent+"; meaning: exponent; arguments strictly positive."});
  }
  if(mode===3)return questionSchema.parse({...base,prompt:"Evaluate $"+logarithm+"$, $\\log_{"+b+"}(1)$ and $\\log_{"+b+"}("+b+")$ exactly. Identify the sign of the first output and justify it using a power of the base.",fields:[field("value","First logarithm",exponent),field("at-one","Logarithm of one","0"),field("at-base","Logarithm of the base","1"),choice("sign","Sign of the first logarithm",p===0?"zero":"positive",[{id:"negative",label:"Negative",feedback:"For this base above one, a negative exponent gives an argument below one."},{id:"zero",label:"Zero",feedback:"The zero exponent gives argument one."},{id:"positive",label:"Positive",feedback:"A positive exponent gives an argument above one for this base."}])],hints:["Find the power of the base that equals the displayed argument.","For every valid logarithm base, b^0=1 and b^1=b.","An argument of one produces zero. For a base above one, an argument greater than one produces a positive output."],explanation:["Since $"+power+"="+rationalLatex(argument)+"$, the first logarithm is "+exponent+".","The other values are zero and one, respectively.","The first value is "+(p===0?"zero because the argument is one":"positive because the argument is greater than one and the base is greater than one")+"."],answerSummary:"First log "+exponent+"; log of one 0; log of base 1; first sign "+(p===0?"zero":"positive")+"."});
  if(mode===4)return questionSchema.parse({...base,prompt:"Evaluate $"+logarithm+"$ exactly. Then raise the same base to the opposite of your logarithm answer, and decide whether the original negative answer is a valid real logarithm.",fields:[field("value","Logarithm value",exponent),field("opposite-power","Base raised to the opposite exponent",r("1/("+argument+")")),choice("valid","Is the negative logarithm value valid?","yes",[{id:"yes",label:"Yes; the argument is positive",feedback:"Only the argument must be positive. A negative exponent gives a positive reciprocal."},{id:"no",label:"No; a logarithm cannot have a negative output",feedback:"This confuses the sign restriction on arguments with the unrestricted real output range."}])],hints:["Rewrite the positive fraction as the reciprocal of an integer power of the base.","The reciprocal power needs a negative exponent.","Negating that exponent gives the reciprocal of the original argument."],explanation:["The power relation is $"+power+"="+rationalLatex(argument)+"$, so the logarithm is "+exponent+".","Using the opposite exponent gives "+r("1/("+argument+")")+".","The answer is valid: the original argument is positive even though its logarithm is negative."],answerSummary:"Log "+exponent+"; opposite power "+r("1/("+argument+")")+"; valid negative output."});
  if(mode===5){
    const check=r(b+"^("+p+")");
    return questionSchema.parse({...base,prompt:"Evaluate $"+logarithm+"$ exactly. The base is "+root+" raised to "+degree+". Give the logarithm, "+degree+" times that value, and the common value of (base)^"+p+" and (argument)^"+degree+". Use this power check to justify the fractional exponent.",fields:[field("value","Exact logarithm",exponent),field("scaled","Logarithm multiplied by "+degree,String(p)),field("power-check","Common exact power value",check)],hints:["Express both the base and argument as powers of "+root+".","If the unknown logarithm is u, the exponent relation is "+degree+"*u="+p+".","Use an exact fraction for u. Check the relation with integer powers of the positive base and argument."],explanation:["The base equals "+root+"^"+degree+" and the argument equals "+root+"^("+p+"). Thus the recovered exponent satisfies "+degree+"*u="+p+".","The logarithm is "+exponent+", giving the scaled exponent "+p+".","Both integer-power checks equal "+check+". Positive arguments and a valid base make this a real logarithm."],answerSummary:"Log "+exponent+"; scaled value "+p+"; exact check "+check+"."});
  }
  if(mode===6)return questionSchema.parse({...base,prompt:"Evaluate $"+logarithm+"$ exactly. The base lies between zero and one. State whether this parent logarithm increases or decreases, and whether its displayed argument is above or below one.",fields:[field("value","Exact logarithm",exponent),choice("direction","Direction of the parent logarithm","decreasing",[{id:"increasing",label:"Increasing",feedback:"A base between zero and one reverses the direction found for a base greater than one."},{id:"decreasing",label:"Decreasing",feedback:"Larger positive arguments require smaller exponents for a fractional base."}]),choice("argument-position","Position of this argument relative to one",p>0?"below":"above",[{id:"below",label:"Below one",feedback:"Positive powers of a positive base less than one stay below one."},{id:"above",label:"Above one",feedback:"Negative powers of a positive base less than one are reciprocals greater than one."}])],hints:["Reconstruct the argument as a power of the complete fraction, including its numerator and denominator.","A negative exponent reverses that positive fraction.","For a fractional base, increasing the exponent makes the power smaller. The inverse function is decreasing too."],explanation:["The relation $"+power+"="+rationalLatex(argument)+"$ gives logarithm "+exponent+".","The base "+b+" is between zero and one, so the parent logarithm is decreasing.","This argument is "+(p>0?"below":"above")+" one, consistently with the "+(p>0?"positive":"negative")+" exponent."],answerSummary:"Log "+exponent+"; decreasing; argument "+(p>0?"below":"above")+" one."});
  const naturalApproximation=Math.log(root+1),specifiedApproximation=Math.log(root+1)/Math.log(root);
  return questionSchema.parse({...base,prompt:"In this lesson, log without a written base denotes the common logarithm. Evaluate $\\log(10^{"+common+"})$ and $\\ln(e^{"+natural+"})$ exactly. State the common-log base and identify the exact natural-log base. Then use the calculator to evaluate $\\ln("+(root+1)+")$ and $\\log_{"+root+"}("+(root+1)+")$, rounding only those two numerical answers to six decimal places.",fields:[field("common","Common logarithm value",String(common)),field("natural","Natural logarithm value",String(natural)),field("common-base","Common logarithm base","10"),choice("natural-base","Exact natural logarithm base","e",[{id:"e",label:"The constant e",feedback:"The symbol e denotes the exact base; a finite decimal only approximates it."},{id:"two",label:"Exactly 2",feedback:"The natural exponential base is not the integer two."},{id:"decimal",label:"Exactly 2.718",feedback:"This finite decimal is an approximation, not the exact constant."},{id:"ten",label:"Exactly 10",feedback:"Ten is the common logarithm base."}]),numeric("natural-approximation","Numerical natural logarithm",naturalApproximation),numeric("specified-approximation","Numerical logarithm with the specified base",specifiedApproximation)],hints:["Common logarithms reverse powers of ten under the stated notation convention.","Natural logarithms reverse powers of the exact constant e. Both inverse identities accept every real exponent.","For the two numerical fields, select the correct logarithm type or specified base. Keep extra digits before rounding the final answers to six decimal places."],explanation:["The common logarithm recovers exponent "+common+" from the power of ten.","The natural logarithm recovers exponent "+natural+" from the power of e. The bases are exactly 10 and e; negative or zero recovered exponents remain valid.","The numerical natural logarithm is approximately "+naturalApproximation.toFixed(6)+". With specified base "+root+", the numerical logarithm is approximately "+specifiedApproximation.toFixed(6)+". These finite decimals are approximations, while the corresponding logarithm expressions remain exact."],answerSummary:"Common value "+common+"; natural value "+natural+"; bases 10 and e; numerical values approximately "+naturalApproximation.toFixed(6)+" and "+specifiedApproximation.toFixed(6)+"."});
}
