import { questionSchema,type Question } from "../contracts";
import { formatIntervals,type Interval } from "../intervals";
import { formatPolynomial,parsePolynomial } from "../polynomial";
import { formatRational,parseRational } from "../rational";
import { inversePowerFunction,inversePowerLatex,inverseRootFunction,powerFunctionDomain,powerFunctionLatex,powerFunctionRange,powerFunctionSchema,rootFunctionDomain,rootFunctionLatex,rootFunctionRange,rootFunctionSchema,type PowerFunction,type RootDegree,type RootValue } from "../radical-functions";
import { randomFrom } from "../random";

export const restrictedInverseFamilyIds=["mth-restricted-inverse"] as const;
const variants=["right-branch","left-branch","downward","scaled-shifted","root-to-power","cubic","fourth-branch","physical-window"];
const r=(source:string)=>formatRational(parseRational(source));
const number=(id:string,label:string,expected:string)=>({id,label,kind:"rational",expected:r(expected),help:"Use an exact number or fraction."});
const interval=(id:string,label:string,expected:Interval[])=>({id,label,kind:"intervals",expected,help:"Give the complete interval, including every required restriction."});
const exact=(value:RootValue)=>{if(value.status!=="defined"||value.exact===null)throw new Error("This inverse question needs an exact value.");return value.exact;};
const inverseWords=(model:PowerFunction)=>"g of x equals ("+model.h+") "+(model.branch==="left"?"minus":"plus")+" the "+({2:"square",3:"cube",4:"fourth",5:"fifth"}[model.degree])+" root of ((x minus ("+model.k+")) divided by ("+model.a+")).";
const powerWords=(model:PowerFunction)=>"("+model.a+") times (x minus ("+model.h+")) raised to power "+model.degree+", plus ("+model.k+")";
const formulaOptions=(model:PowerFunction)=>[
  {id:"correct",label:"$g(x)="+inversePowerLatex(model)+"$",accessibleLabel:inverseWords(model),feedback:"The chosen root branch must return values to the original restricted domain."},
  {id:"opposite",label:"$g(x)="+inversePowerLatex({...model,branch:model.branch==="left"?"right":"left"})+"$",accessibleLabel:inverseWords({...model,branch:model.branch==="left"?"right":"left"}),feedback:"Changing the root sign sends non-endpoint values to the wrong branch or fails the inverse equation."},
  {id:"original",label:"$g(x)="+powerFunctionLatex(model)+"$",accessibleLabel:"g of x equals "+powerWords(model)+".",feedback:"Repeating the original power operation does not undo it."},
  {id:"reciprocal",label:"$g(x)=\\frac{1}{"+powerFunctionLatex(model)+"}$",accessibleLabel:"g of x equals 1 divided by ("+powerWords(model)+").",feedback:"A reciprocal divides one by an output. An inverse function recovers the original input."},
];
export function restrictedInverseQuestion(familyId:string,variant:string,seed:string,id:string):Question{
  if(familyId!=="mth-restricted-inverse")throw new Error("Unknown restricted inverse family");
  const rng=randomFrom(seed);if(variant==="mixed")variant=variants[rng.integer(0,variants.length-1)];const mode=variants.indexOf(variant);if(mode<0)throw new Error("Unknown restricted inverse variant");
  const sign=rng.integer(0,1)?1:-1,side=mode===0?1:mode===1?-1:rng.integer(0,1)?1:-1,degree:RootDegree=mode===5?(rng.integer(0,1)?3:5):mode===6?4:mode===4?(rng.integer(0,1)?2:4):2;
  const an=(mode===2?-1:mode<2?1:sign)*rng.integer(1,4),ad=mode===3||mode===4?rng.integer(2,4):1,a=r(an+"/"+ad),b=(rng.integer(0,1)?1:-1)*rng.integer(1,4),k=rng.integer(-4,4),d=rng.integer(1,3),u=rng.integer(0,2),v=u+rng.integer(1,3),h=mode===7?(side<0?v+2:2):rng.integer(-4,4);
  const base={id,familyId,familyVersion:1,courseId:"mth-215",objectiveId:"m04-l04",critical:true,category:"procedural",parameters:{mode,degree,an,ad,b,h,k,d,side,u,v}};
  if(mode===4){
    const model=rootFunctionSchema.parse({degree,transform:{a,b:String(b),h:String(h),k:String(k)}}),target=r(k+"+("+a+")*"+d),probe=r(k+"-("+a+")*"+d),domain=rootFunctionRange(model),range=rootFunctionDomain(model),answer=exact(inverseRootFunction(model,target));
    const polynomial=formatPolynomial(parsePolynomial("("+h+")+(((x-("+k+"))/("+a+"))^"+degree+")/("+b+")"));
    return questionSchema.parse({...base,prompt:"For the real function $f(x)="+rootFunctionLatex(model)+"$, derive its inverse g. Give an equivalent polynomial formula in x, its required domain and range, g("+target+"), and g("+k+"). Decide whether the inverse function accepts the separate input "+probe+". A polynomial formula alone does not remove the inverse's restrictions.",fields:[{id:"formula",label:"Polynomial formula for g(x)",kind:"polynomial",expected:polynomial,form:"equivalent",help:"Enter an equivalent polynomial in x. Report its restricted domain separately."},interval("domain","Domain of g",domain),interval("range","Range of g",range),number("value","g("+target+")",answer),number("boundary","g("+k+")",String(h)),{id:"probe",label:"Does the inverse accept input "+probe+"?",kind:"choice",correct:"no",options:rng.shuffle([{id:"yes",label:"Yes",feedback:"The polynomial extension is defined there, but this input is outside the original function's range."},{id:"no",label:"No",feedback:"The inverse domain must equal the original radical function's range."}])}],hints:["Isolate the root as (y-k)/a, then raise to its index. Solve b(x-h)=((y-k)/a)^n for the original input.","After swapping names, g(x)=h+((x-k)/a)^n/b. Its domain is the original range.","The first target has isolated root "+d+"; the separate probe would require a negative principal even root."],explanation:["An equivalent inverse polynomial is $g(x)="+formatPolynomial(parsePolynomial(polynomial),true)+"$.","Its domain is "+formatIntervals(domain)+" and its range is "+formatIntervals(range)+".","The requested values are "+answer+" and "+h+", respectively.","The separate input is excluded by the inverse domain even though the same polynomial can be evaluated outside that domain."],answerSummary:"g(x)="+polynomial+"; domain "+formatIntervals(domain)+"; range "+formatIntervals(range)+"; values "+answer+", "+h+"; reject separate input."});
  }
  const model=powerFunctionSchema.parse({degree,a,h:String(h),k:String(k),branch:degree%2?"all":side>0?"right":"left"});
  if(mode===7){
    const first=h+side*u,last=h+side*v,lower=Math.min(first,last),upper=Math.max(first,last),y1=an*u*u+k,y2=an*v*v+k,lowY=Math.min(y1,y2),highY=Math.max(y1,y2),outside=an*(v+1)**2+k;
    const domain:Interval[]=[{lower:String(lowY),upper:String(highY),lowerClosed:true,upperClosed:true}],range:Interval[]=[{lower:String(lower),upper:String(upper),lowerClosed:true,upperClosed:true}];
    return questionSchema.parse({...base,category:"application",prompt:"A supplied response model is $f(x)="+powerFunctionLatex(model)+"$, validated only for input lengths x in ["+lower+", "+upper+"] m. The response is in V. Derive the inverse formula g, its permitted input and output intervals, and the length for response "+y2+" V. Also calculate the algebraic extension at response "+outside+" V and classify that extension against the supplied operating window.",fields:[{id:"formula",label:"Inverse formula",kind:"choice",correct:"correct",options:rng.shuffle(formulaOptions(model))},{...interval("domain","Allowed inverse inputs",domain),unit:"V"},{...interval("range","Allowed inverse outputs",range),unit:"m"},{...number("value","Input length for response "+y2+" V",String(last)),unit:"m"},{...number("extension","Algebraic extension at response "+outside+" V",String(h+side*(v+1))),unit:"m"},{id:"status",label:"Status of the extension",kind:"choice",correct:"outside",options:rng.shuffle([{id:"inside",label:"Inside the supplied operating window",feedback:"Compare the recovered length and response with both permitted intervals."},{id:"outside",label:"Real formula value outside the supplied operating window",feedback:"The algebraic branch still gives a real value, but the model was not validated at that length."},{id:"undefined",label:"No real value of the algebraic inverse formula",feedback:"The isolated squared quantity is positive here, so a real algebraic branch value does exist."}])}],hints:["The allowed original interval stays on one side of h. Choose the inverse root sign that returns to that side.","Map both original endpoints through f, order their output values, and retain the closed endpoints. This output interval becomes the inverse domain.","The second response corresponds algebraically to distance "+(v+1)+" from h, beyond the supplied maximum distance "+v+"."],explanation:["The inverse formula is $g(x)="+inversePowerLatex(model)+"$.","The inverse domain is "+formatIntervals(domain)+" V and its range is "+formatIntervals(range)+" m.","The first requested response gives the allowed endpoint length "+last+" m.","The algebraic extension gives "+(h+side*(v+1))+" m, outside the permitted input-length interval. It is not a validated operating prediction."],answerSummary:"Inverse domain "+formatIntervals(domain)+" V; range "+formatIntervals(range)+" m; endpoint length "+last+" m; extension "+(h+side*(v+1))+" m outside the window."});
  }
  const target=r("("+a+")*("+side*d+")^"+degree+"+("+k+")"),value=inversePowerFunction(model,target),probe=k-Math.sign(an),domain=powerFunctionRange(model),range=powerFunctionDomain(model);
  if(value.status==="no-inverse")throw new Error(value.reason);
  return questionSchema.parse({...base,prompt:"Let $f(x)="+powerFunctionLatex(model)+"$ on the stated domain "+formatIntervals(range)+". Derive its inverse g, give the complete inverse domain and range, evaluate g("+target+") and g("+k+"), and decide whether the inverse accepts the separate input "+probe+".",fields:[{id:"formula",label:"Inverse formula",kind:"choice",correct:"correct",options:rng.shuffle(formulaOptions(model))},interval("domain","Domain of g",domain),interval("range","Range of g",range),number("value","g("+target+")",exact(value)),number("boundary","g("+k+")",String(h)),{id:"probe",label:"Does the inverse accept input "+probe+"?",kind:"choice",correct:degree%2?"yes":"no",options:rng.shuffle([{id:"yes",label:"Yes",feedback:"The inverse input must lie in the original range. An odd power on R has every real output."},{id:"no",label:"No",feedback:"For an even power, one side of the turning output is outside the original range."}])}],hints:["Isolate the original input power as (y-k)/a, then take the appropriate real root.",degree%2?"An odd power is one-to-one on R. Its real inverse root preserves the sign of its radicand.":"Choose the root sign using the stated input branch, not the sign of a. The inverse outputs must return to that branch.","The inverse domain is the original range, and the inverse range is the original domain. Check the turning or center value separately."],explanation:["The inverse formula is $g(x)="+inversePowerLatex(model)+"$.","Its domain is "+formatIntervals(domain)+" and range is "+formatIntervals(range)+".","The requested values are "+exact(value)+" and "+h+".",degree%2?"The separate real input is accepted by the odd-root inverse.":"The separate input lies on the wrong side of the original turning output and is outside the inverse domain."],answerSummary:"Domain "+formatIntervals(domain)+"; range "+formatIntervals(range)+"; values "+exact(value)+", "+h+"; separate input "+(degree%2?"accepted":"rejected")+"."});
}
