import { questionSchema,type Question } from "../contracts";
import { formatIntervals,type Interval } from "../intervals";
import { formatRational,parseRational } from "../rational";
import { rootFunctionDomain,rootFunctionLatex,rootFunctionRange,rootFunctionSchema,type RootDegree } from "../radical-functions";
import { mapPoint } from "../transformations";
import { randomFrom } from "../random";

export const radicalTransformFamilyIds=["mth-radical-transform"] as const;
const variants=["anchors","reflections","scale","endpoint","input-recovery","signed-odd","fourth-power","principal-value"];
const r=(source:string)=>formatRational(parseRational(source));
const number=(id:string,label:string,expected:string)=>({id,label,kind:"rational",expected:r(expected),help:"Use an exact number or fraction."});
const roots=(id:string,label:string,expected:string[])=>({id,label,kind:"roots",numberSystem:"real",expected,help:"List all distinct real values or type empty."});
const interval=(id:string,label:string,expected:Interval[])=>({id,label,kind:"intervals",expected,help:"Use interval notation; R means all real numbers."});
const yesNo=[{id:"yes",label:"Yes",feedback:"An even root of zero is defined here because it is not in a denominator."},{id:"no",label:"No",feedback:"A zero radicand is allowed in this formula. Do not apply a denominator-root exclusion where there is no denominator root."}];
export function radicalTransformQuestion(familyId:string,variant:string,seed:string,id:string):Question{
  if(familyId!=="mth-radical-transform")throw new Error("Unknown radical transformation family");
  const rng=randomFrom(seed);if(variant==="mixed")variant=variants[rng.integer(0,variants.length-1)];const mode=variants.indexOf(variant);if(mode<0)throw new Error("Unknown radical transformation variant");
  const flag=rng.integer(0,1),sign=rng.integer(0,1)?1:-1,h=rng.integer(-4,4),k=rng.integer(-4,4),d=rng.integer(1,3);
  const degree:RootDegree=mode===5?(flag?3:5):mode===6?4:mode===3||mode===4||mode===7?(flag?2:4):flag?2:3;
  const an=sign*rng.integer(1,4),ad=mode===2?rng.integer(1,3):1,bn=(rng.integer(0,1)?1:-1)*(mode===2&&flag?1:rng.integer(1,4)),bd=mode===2&&flag?rng.integer(2,4):1;
  const a=r(an+"/"+ad),b=r(bn+"/"+bd),t=degree%2?sign*d:d,model=rootFunctionSchema.parse({degree,transform:{a,b,h:String(h),k:String(k)}}),mapped=mapPoint(model.transform,{x:String(t**degree),y:String(t)}),formula=rootFunctionLatex(model);
  const base={id,familyId,familyVersion:1,courseId:"mth-215",objectiveId:"m04-l04",critical:true,category:"procedural",parameters:{mode,degree,an,ad,bn,bd,h,k,d,t,flag}};
  if(mode===7){
    const u=rng.integer(-1,1)*d,magnitude=Math.abs(u),solutions=magnitude?[String(-magnitude),String(magnitude)]:["0"];
    return questionSchema.parse({...base,category:"conceptual",parameters:{...base.parameters,u},prompt:"Let u="+u+". Distinguish the principal radical value $\\sqrt["+degree+"]{u^{"+degree+"}}$ from all real solutions of $v^{"+degree+"}=u^{"+degree+"}$. Also evaluate the negative of the principal radical. Then choose the identity valid for every real u.",fields:[number("principal","Principal radical value",String(magnitude)),roots("solutions","All real solutions for v",solutions),number("negative","Negative of the principal radical",String(-magnitude)),{id:"identity",label:"Principal even root of u to the same even power",kind:"choice",correct:"absolute",options:rng.shuffle([{id:"absolute",label:"|u|",feedback:"The principal even root is nonnegative for both signs of u."},{id:"signed",label:"u",feedback:"This fails for negative u."},{id:"both",label:"Both u and -u as a two-valued function",feedback:"An equation can have two roots; the principal radical function assigns one value."}])}],hints:["An even power removes the sign of a nonzero base.","The principal even root returns the nonnegative magnitude, while solving the power equation requires every real candidate.","A minus sign outside the radical negates its one principal value."],explanation:["The principal value is |"+u+"|="+magnitude+".","The power equation has the distinct real solutions "+solutions.join(", ")+".","Negating the principal value gives "+(-magnitude)+". These are three different requests.","For every real u, the principal even root of u to that even power is |u|."],answerSummary:"Principal "+magnitude+"; equation solutions "+solutions.join(", ")+"; negative principal "+(-magnitude)+"; identity |u|."});
  }
  if(mode===4){
    const invalidTarget=r(k+"-("+a+")*"+d),candidate=mapPoint(model.transform,{x:String(d**degree),y:String(d)}).x;
    return questionSchema.parse({...base,category:"application",prompt:"For $f(x)="+formula+"$, find every real input producing y="+mapped.y+". Separately, consider the requested output y="+invalidTarget+": list the candidate produced by raising the isolated radical equation to power "+degree+", then list the inputs that actually satisfy that original equation.",fields:[roots("valid","Inputs for the first target",[mapped.x]),roots("raised","Candidate after raising to the even power for the second target",[candidate]),roots("retained","Inputs satisfying the original second-target equation",[])],hints:["Isolate the principal root as (y-k)/a before raising a power.","For the first target the isolated root is "+d+". For the second target it is -"+d+", which a principal even root cannot equal.","The even power gives the same numerical candidate in both cases, but substitution rejects it for the negative isolated-root target."],explanation:["The first target gives the one input "+mapped.x+".","For the second target, raising the equation to the even power produces candidate "+candidate+".","Its actual output is "+mapped.y+", not "+invalidTarget+". The second target is outside the original range, so no input survives.","Raising an equation to an even power may erase a sign condition. Check the original equation."],answerSummary:"First target input "+mapped.x+"; raised candidate "+candidate+"; second target has no real input."});
  }
  if(mode===3){
    const domain=rootFunctionDomain(model),range=rootFunctionRange(model);
    return questionSchema.parse({...base,category:"conceptual",prompt:"For $f(x)="+formula+"$, locate the endpoint, give the full domain and range, and decide whether the endpoint belongs to this function. The displayed formula has no denominator root.",fields:[number("x","Endpoint input",String(h)),number("y","Endpoint output",String(k)),interval("domain","Full domain",domain),interval("range","Full range",range),{id:"included",label:"Endpoint included?",kind:"choice",correct:"yes",options:rng.shuffle(yesNo)}],hints:["Set the inside expression equal to zero to find the endpoint input.","A principal even root of zero equals zero, so the outside shift gives the endpoint output.","Include the endpoint in both intervals. The sign of b determines the domain direction and the sign of a the range direction."],explanation:["The endpoint is ("+h+", "+k+").","The domain is "+formatIntervals(domain)+" and the range is "+formatIntervals(range)+".","The zero radicand is defined, so the endpoint is included. A root used as a denominator would require a separate zero exclusion."],answerSummary:"Endpoint ("+h+", "+k+"); domain "+formatIntervals(domain)+"; range "+formatIntervals(range)+"; included."});
  }
  if(mode===5){
    const input=r(h+"-"+d**degree+"/("+b+")"),output=r(k+"-("+a+")*"+d);
    return questionSchema.parse({...base,category:"conceptual",prompt:"Use the real odd-root function $f(x)="+formula+"$. At x="+input+", find the radicand's real root and the transformed output. State the complete domain and range, and decide whether ("+h+", "+k+") is an endpoint of the domain.",fields:[number("root","Real root of the radicand",String(-d)),number("output","Transformed output",output),interval("domain","Full domain",rootFunctionDomain(model)),interval("range","Full range",rootFunctionRange(model)),{id:"endpoint",label:"Is the transformed center a domain endpoint?",kind:"choice",correct:"no",options:rng.shuffle([{id:"yes",label:"Yes",feedback:"That endpoint rule belongs to an even-root graph, not this odd root."},{id:"no",label:"No",feedback:"The odd-root domain extends in both directions through its transformed center."}])}],hints:["At this input the radicand is -"+d**degree+". Odd roots preserve the sign.","Apply the outside multiplier and shift to the negative root.","Nonzero affine transformations of an odd root still have all real inputs and outputs."],explanation:["The real root is -"+d+", giving transformed output "+output+".","The domain and range are both R.","The point ("+h+", "+k+") is the transformed center, not a domain endpoint."],answerSummary:"Root -"+d+"; output "+output+"; domain R; range R; no endpoint."});
  }
  if(mode===6)return questionSchema.parse({...base,category:"conceptual",prompt:"For $f(x)="+formula+"$, evaluate the function at x="+mapped.x+". Give the principal fourth root of its radicand, the final output, and every real solution of the separate equation $v^4="+d**4+"$.",fields:[number("principal","Principal fourth root of the radicand",String(d)),number("output","Transformed function output",mapped.y),roots("solutions","All real solutions of the separate fourth-power equation",[String(-d),String(d)])],hints:["The radicand at the requested input is "+d**4+".","Its principal fourth root is nonnegative. Apply the outside operations only after finding that root.","The separate power equation admits both signs; the function's principal radical does not."],explanation:["The principal fourth root is "+d+".","The transformed output is "+mapped.y+".","The separate equation has real solutions -"+d+" and "+d+". They do not make f a two-valued function."],answerSummary:"Principal root "+d+"; output "+mapped.y+"; equation solutions -"+d+", "+d+"."});
  const reflection=an<0?(bn<0?"both":"vertical"):(bn<0?"horizontal":"none"),horizontal=r(bd+"/"+Math.abs(bn)),vertical=r(Math.abs(an)+"/"+ad);
  const fields=[number("x","Corresponding transformed input",mapped.x),number("y","Corresponding transformed output",mapped.y),...(mode===2?[number("horizontal","Positive horizontal length multiplier",horizontal),number("vertical","Positive vertical length multiplier",vertical)]:[]),...(mode===1?[{id:"reflection",label:"Reflections before translation",kind:"choice",correct:reflection,options:rng.shuffle([{id:"none",label:"Neither coordinate is reflected",feedback:"Both multipliers must be positive for this description."},{id:"horizontal",label:"Input coordinates only, across the y-axis",feedback:"A negative b reverses input positions before translation."},{id:"vertical",label:"Output coordinates only, across the x-axis",feedback:"A negative a reverses output signs before translation."},{id:"both",label:"Both input and output coordinates",feedback:"Negative inside and outside multipliers reverse both coordinates before their shifts."}])}]:[])];
  return questionSchema.parse({...base,prompt:"The parent function is the principal real degree-"+degree+" root. Its point ("+t**degree+", "+t+") is known. For $g(x)="+formula+"$, find the corresponding point."+(mode===1?" Identify the reflection steps specified by the multipliers before the translations.":mode===2?" Give the positive horizontal and vertical length multipliers as well.":" Match the inside expression to the parent input before computing the transformed output."),fields,hints:["The original input u maps to x=h+u/b; it is divided by the inside multiplier.","The original output v maps to y=av+k. Input and output use different operations.",mode===2?"The horizontal length multiplier is 1/|b| and the vertical multiplier is |a|.":mode===1?"Negative b reflects the input coordinate; negative a reflects the output coordinate. Apply translations afterward.":"Substitute the transformed input into b(x-h) to recover the parent input."],explanation:["The parent point ("+t**degree+", "+t+") maps to ("+mapped.x+", "+mapped.y+").","The horizontal multiplier is "+horizontal+"; the vertical multiplier is "+vertical+".","The signed multipliers specify the reflection steps before the shifts. Symmetry can make different transformation descriptions produce the same graph."],answerSummary:"Point ("+mapped.x+", "+mapped.y+"); horizontal multiplier "+horizontal+"; vertical multiplier "+vertical+"; reflection "+reflection+"."});
}
