import { questionSchema, type Question } from "../contracts";
import { formatPiMultiple } from "../angles";
import { formatRational, parseRational } from "../rational";
import { randomFrom } from "../random";

export const foundationTriangleFamilyIds = ["mth-triangle-geometry", "mth-triangle-ratios", "mth-angle-conversion", "mth-calculator-mode", "mth-triangle-solve"];
const piHelp = "Use pi for the exact constant, such as pi/6 or -3*pi/4. A rounded decimal does not answer an exact-angle question.";
export function foundationTriangleQuestion(familyId: string, variant: string, seed: string, id: string): Question {
  const rng = randomFrom(seed), base = { id, familyId, familyVersion: 1, courseId: "mth-215", objectiveId: "b06" };
  const triple = [[3, 4, 5], [5, 12, 13], [8, 15, 17], [7, 24, 25]][rng.integer(0, 3)], scale = rng.integer(1, 3);
  const [a, b, h] = triple.map(value => value*scale), atB = rng.integer(0, 1) === 0, angleAt = atB ? "B" : "C", opposite = atB ? b : a, adjacent = atB ? a : b;
  const oppositeSide = atB ? "ac" : "ab", adjacentSide = atB ? "ab" : "ac";
  const figure = { kind: "right-triangle", title: "Right triangle ABC", angleAt, AB: `${a} cm`, AC: `${b} cm`, BC: `${h} cm` };
  const sideField = (id: string, label: string, correct: string) => ({ id, kind: "choice", label, correct, options: rng.shuffle(["ab", "ac", "bc"].map(side => ({ id: side, label: side.toUpperCase(), feedback: side === "bc" ? "BC is across from the right angle at A, so it is always the hypotenuse." : side === oppositeSide ? `${side.toUpperCase()} does not touch the marked angle at ${angleAt}; it is the opposite side.` : `${side.toUpperCase()} touches the marked angle at ${angleAt} and is not the hypotenuse; it is the adjacent leg.` }))) });
  if (familyId === "mth-triangle-geometry") {
    if (!["labels", "hypotenuse", "leg"].includes(variant)) throw new Error("Unknown triangle geometry variant");
    if (variant === "labels") return questionSchema.parse({ ...base, parameters: { a, b, h, atB: Number(atB) }, category: "conceptual", critical: true, prompt: "Identify the sides relative to the marked acute angle. Adjacent means the adjacent leg, excluding the hypotenuse.", figure,
      fields: [sideField("hypotenuse", "Hypotenuse", "bc"), sideField("opposite", "Opposite side", oppositeSide), sideField("adjacent", "Adjacent leg", adjacentSide)],
      hints: ["Find the right-angle square first. The side across from it is the hypotenuse.", `The marked angle is at ${angleAt}. Its opposite side does not touch ${angleAt}.`, `Hypotenuse BC; opposite ${oppositeSide.toUpperCase()}; adjacent leg ${adjacentSide.toUpperCase()}.`],
      explanation: ["The hypotenuse is always BC because the right angle is at A.", `Relative to the marked angle at ${angleAt}, ${oppositeSide.toUpperCase()} is opposite and ${adjacentSide.toUpperCase()} is the adjacent leg.`, "Changing the reference acute angle swaps the two leg roles, but never changes the hypotenuse."], answerSummary: `BC; ${oppositeSide.toUpperCase()}; ${adjacentSide.toUpperCase()}.` });
    const legA = rng.integer(2, 12), legB = rng.integer(2, 12), sum = legA*legA+legB*legB, isHypotenuse = variant === "hypotenuse";
    const expected = isHypotenuse ? `sqrt(${sum})` : String(a);
    return questionSchema.parse({ ...base, parameters: { a, b, h, legA, legB, sum, atB: Number(atB) }, category: "procedural", critical: true,
      prompt: isHypotenuse ? "Find the hypotenuse length exactly. Lengths are positive; keep a radical exact when necessary." : "Find the missing length AB and choose a correctly grouped calculator expression for it.",
      figure: isHypotenuse ? { ...figure, AB: `${legA} cm`, AC: `${legB} cm`, BC: "Unknown hypotenuse" } : { ...figure, AB: "Unknown leg" },
      fields: isHypotenuse ? [{ id: "length", kind: "exact", label: "Hypotenuse length", expected, unit: "cm", help: "Use sqrt(number), such as sqrt(13). Do not round an exact length." }] : [{ id: "length", kind: "exact", label: "Length AB", expected, unit: "cm", help: "Use the positive square root." }, { id: "formula", kind: "choice", label: "Correct calculator expression", correct: "difference", options: rng.shuffle([{ id: "difference", label: `sqrt(${h}^2 - ${b}^2)`, feedback: "Subtract the known leg's square from the hypotenuse's square, then take the square root of the whole difference." }, { id: "outside", label: `sqrt(${h}^2) - ${b}^2`, feedback: "This takes the square root before subtracting the leg's square. The whole difference belongs under the root." }, { id: "lengths", label: `${h} - ${b}`, feedback: "The Pythagorean relation combines squared lengths, not the difference of the unsquared sides." }]) }],
      hints: ["For a right triangle, the hypotenuse squared equals the sum of the leg squares.", isHypotenuse ? `Add ${legA}² and ${legB}², then take the positive square root.` : `The missing leg squared is ${h}²-${b}².`, isHypotenuse ? `The exact length is sqrt(${sum}) cm.` : `The difference is ${a*a}, so the length is ${a} cm.`],
      explanation: [isHypotenuse ? `$BC^2=${legA}^2+${legB}^2=${sum}$.` : `$AB^2=${h}^2-${b}^2=${a*a}$.`, `The positive square root gives ${expected} cm. A negative root is not a side length.`, isHypotenuse ? "The hypotenuse must be longer than either leg, which provides a useful magnitude check." : "Taking the square root of the entire difference requires parentheses around that difference in a typed expression."], answerSummary: `${expected} cm${isHypotenuse ? "" : `; sqrt(${h}^2 - ${b}^2)`}.` });
  }
  if (familyId === "mth-triangle-ratios") {
    if (!["sin", "cos", "tan"].includes(variant)) throw new Error("Unknown triangle ratio variant");
    const numerator = variant === "cos" ? adjacent : opposite, denominator = variant === "tan" ? adjacent : h;
    const correct = variant === "sin" ? `${oppositeSide}-bc` : variant === "cos" ? `${adjacentSide}-bc` : `${oppositeSide}-${adjacentSide}`;
    const rule = variant === "sin" ? "opposite/hypotenuse" : variant === "cos" ? "adjacent/hypotenuse" : "opposite/adjacent";
    return questionSchema.parse({ ...base, parameters: { a, b, h, atB: Number(atB) }, category: "procedural", critical: true, prompt: `Find $\\${variant}(\\theta)$ exactly, where θ is the marked angle at ${angleAt}. Choose the side ratio before evaluating it.`, figure,
      fields: [{ id: "ratio", kind: "choice", label: "Side ratio", correct, options: rng.shuffle(["ab-bc", "ac-bc", "ab-ac", "ac-ab"].map(pair => ({ id: pair, label: pair.toUpperCase().replace("-", "/"), feedback: pair === correct ? `This is ${rule} relative to the marked angle.` : `For ${variant}, use ${rule} relative to the marked angle at ${angleAt}.` }))) }, { id: "value", kind: "rational", label: "Exact ratio value", expected: `${numerator}/${denominator}`, help: "Enter an exact fraction. Both lengths have the same units, so their ratio is dimensionless." }],
      hints: [`Use ${rule}.`, `At ${angleAt}, the opposite leg is ${opposite} cm and the adjacent leg is ${adjacent} cm; the hypotenuse is ${h} cm.`, `The ratio is ${numerator}/${denominator}.`],
      explanation: [`The requested ratio uses ${rule}, so it is ${numerator}/${denominator}.`, `Its exact value is ${formatRational(parseRational(`${numerator}/${denominator}`))}. The centimeter units cancel.`, "Opposite and adjacent depend on the reference angle, so identify them before choosing a trigonometric ratio."], answerSummary: `${correct.toUpperCase().replace("-", "/")} = ${formatRational(parseRational(`${numerator}/${denominator}`))}.` });
  }
  if (familyId === "mth-angle-conversion") {
    if (!["to-radians", "to-degrees"].includes(variant)) throw new Error("Unknown angle conversion variant");
    const degrees = [0, 15, 30, 45, 60, 75, 90, 120, 135, 150, 180, 270, 360, -30, -45, -90, -180][rng.integer(0, 16)], coefficient = parseRational(`${degrees}/180`), radians = formatPiMultiple(coefficient, true), toRadians = variant === "to-radians";
    return questionSchema.parse({ ...base, parameters: { degrees }, category: "procedural", critical: true, prompt: toRadians ? `Convert ${degrees} degrees to an exact radian measure.` : `Convert $${radians}$ radians to degrees.`,
      fields: [toRadians ? { id: "angle", kind: "pi-multiple", label: "Exact radian measure", expected: formatRational(coefficient), unit: "rad", help: piHelp } : { id: "angle", kind: "rational", label: "Degree measure", expected: String(degrees), unit: "degrees" }],
      hints: ["A half turn is 180 degrees or pi radians.", toRadians ? "Multiply the degree measure by pi/180." : "Multiply the radian measure by 180/pi, canceling pi.", `The same angle is ${degrees} degrees or $${radians}$ radians.`],
      explanation: [`Using $180^\\circ=\\pi$ radians gives ${degrees} degrees $=${radians}$ radians.`, "The sign of a directed angle is retained by the conversion. Zero stays zero, and a full positive turn is 2pi radians."], answerSummary: toRadians ? `$${radians}$ radians.` : `${degrees} degrees.` });
  }
  if (familyId === "mth-calculator-mode") {
    if (!["matched", "mismatch"].includes(variant)) throw new Error("Unknown calculator mode variant");
    const degrees = [15, 25, 30, 40, 45, 60, 75][rng.integer(0, 6)], radians = formatPiMultiple(parseRational(`${degrees}/180`), true), expected = Math.sin(degrees*Math.PI/180), incorrect = Math.sin(degrees);
    const valueField = (id: string, label: string) => ({ id, kind: "numeric", label, expected, absoluteTolerance: .0005, relativeTolerance: 0, help: "Give at least three decimal places. Keep the calculator's angle mode consistent with the input." });
    return questionSchema.parse({ ...base, parameters: { degrees }, category: "conceptual", critical: true,
      prompt: variant === "matched" ? `Evaluate $\\sin(${degrees}^\\circ)$ in degree mode and $\\sin(${radians})$ in radian mode. Give each value to at least three decimal places.` : `A learner wants $\\sin(${degrees}^\\circ)$, but enters sin(${degrees}) in radian mode and obtains about ${incorrect.toFixed(6)}. Identify the correction and calculate the intended value to at least three decimal places.`,
      fields: variant === "matched" ? [valueField("degrees", "Sine using the degree input"), valueField("radians", "Sine using the radian input")] : [{ id: "correction", kind: "choice", label: "Correction", correct: "mode", options: rng.shuffle([{ id: "mode", label: `Use ${degrees} in degree mode, or its converted radian measure in radian mode`, feedback: "The angle unit belongs to the input. Either correctly matched representation gives the same sine." }, { id: "absolute", label: "Take the absolute value of the displayed answer", feedback: "Changing a result's sign does not repair an incorrectly interpreted angle." }, { id: "result", label: "Multiply the displayed sine value by pi/180", feedback: "Convert the angle before taking sine. Sine values themselves are not degree or radian measures." }]) }, valueField("value", "Intended sine value")],
      hints: ["Degree and radian modes interpret the numerical angle differently.", `The intended angle is ${degrees} degrees, which equals $${radians}$ radians.`, `The intended sine is approximately ${expected.toFixed(6)}.`],
      explanation: [`Both ${degrees} degrees and $${radians}$ radians describe the same angle, so both correctly entered calculations give approximately ${expected.toFixed(6)}.`, `Entering the bare number ${degrees} in radian mode instead describes ${degrees} radians, a different angle.`, "Convert or relabel the input correctly; do not apply an angle-conversion factor to the trigonometric result."], answerSummary: `Approximately ${expected.toFixed(6)} for the intended angle${variant === "matched" ? " in both modes" : "; match the input angle to the calculator mode"}.` });
  }
  if (familyId === "mth-triangle-solve") {
    if (!["sides", "angles"].includes(variant)) throw new Error("Unknown triangle solving variant");
    const degrees = variant === "sides" ? [20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70][rng.integer(0, 10)] : Math.atan2(opposite, adjacent)*180/Math.PI, hypotenuse = variant === "sides" ? rng.integer(5, 20) : h;
    const opp = hypotenuse*Math.sin(degrees*Math.PI/180), adj = hypotenuse*Math.cos(degrees*Math.PI/180), ab = atB ? adj : opp, ac = atB ? opp : adj;
    const numeric = (id: string, label: string, expected: number, tolerance: number, unit: string) => ({ id, kind: "numeric", label, expected, absoluteTolerance: tolerance, relativeTolerance: 0, unit });
    return questionSchema.parse({ ...base, parameters: { a, b, h, atB: Number(atB), degrees, hypotenuse }, category: variant === "sides" ? "application" : "procedural", critical: true,
      prompt: variant === "sides" ? `A right triangular panel has hypotenuse BC = ${hypotenuse} cm and marked angle θ = ${degrees} degrees at ${angleAt}. Find both legs to the nearest 0.01 cm and the other acute angle.` : `Find the marked angle θ at ${angleAt} and the other acute angle, both to the nearest 0.1 degree. All three side lengths are given.`,
      figure: variant === "sides" ? { ...figure, AB: "Unknown leg", AC: "Unknown leg", BC: `${hypotenuse} cm` } : figure,
      fields: variant === "sides" ? [numeric("ab", "Length AB", ab, .005, "cm"), numeric("ac", "Length AC", ac, .005, "cm"), { id: "other", kind: "rational", label: "Other acute angle", expected: String(90-degrees), unit: "degrees" }] : [numeric("angle", "Marked angle theta", degrees, .05, "degrees"), numeric("other", "Other acute angle", 90-degrees, .05, "degrees")],
      hints: [variant === "sides" ? "The opposite leg equals hypotenuse times sine; the adjacent leg equals hypotenuse times cosine." : "Use inverse tangent of opposite/adjacent, or another appropriate inverse trigonometric ratio.", variant === "sides" ? `At ${angleAt}, ${oppositeSide.toUpperCase()} is opposite and ${adjacentSide.toUpperCase()} is adjacent.` : `The ratio opposite/adjacent is ${opposite}/${adjacent}. Ask for the inverse-tangent result in degrees.`, "The two acute angles of a right triangle add to 90 degrees."],
      explanation: [variant === "sides" ? `The opposite leg is $${hypotenuse}\\sin(${degrees}^\\circ)$ and the adjacent leg is $${hypotenuse}\\cos(${degrees}^\\circ)$. This gives AB ≈ ${ab.toFixed(4)} cm and AC ≈ ${ac.toFixed(4)} cm.` : `The inverse tangent of ${opposite}/${adjacent}, in degree mode, gives θ ≈ ${degrees.toFixed(4)} degrees.`, `The other acute angle is 90 minus θ, approximately ${(90-degrees).toFixed(4)} degrees.`, "An inverse trigonometric function returns an angle. It is different from taking the reciprocal of a trigonometric ratio."], answerSummary: variant === "sides" ? `AB ≈ ${ab.toFixed(2)} cm; AC ≈ ${ac.toFixed(2)} cm; other angle ${90-degrees} degrees.` : `θ ≈ ${degrees.toFixed(1)} degrees; other angle ≈ ${(90-degrees).toFixed(1)} degrees.` });
  }
  throw new Error("This question family is not available.");
}
