import { questionSchema,type Question } from "../contracts";
import { formatRational,parseRational } from "../rational";
import { analyzeExponentialTable,evaluateExponential,exponentialFunctionSchema } from "../exponential-functions";
import { randomFrom } from "../random";

export const exponentialPatternFamilyIds=["mth-exponential-pattern"] as const;
const variants=["linear-table","geometric-table","unequal-steps","step-model","initial-value","shifted-table","constant-table","contradiction"];
const r=(source:string)=>formatRational(parseRational(source));
const number=(id:string,label:string,expected:string,unit="")=>({id,label,kind:"rational",expected:r(expected),unit,help:"Use an exact number or fraction."});
const options=[
  {id:"linear",label:"Nonconstant linear change",feedback:"Equal input steps give a constant nonzero output difference."},
  {id:"exponential",label:"Nonconstant exponential change relative to the stated baseline",feedback:"Equal input steps multiply each nonzero baseline-relative output by the same positive factor other than one."},
  {id:"constant",label:"Constant output",feedback:"All recorded outputs are equal. Keep this separate from a nonconstant exponential."},
  {id:"neither",label:"Neither of these exact nonconstant patterns",feedback:"Use every record; a failed difference and ratio check can reject both proposed patterns."},
];
export function exponentialPatternQuestion(familyId:string,variant:string,seed:string,id:string):Question{
  if(familyId!=="mth-exponential-pattern")throw new Error("Unknown exponential pattern family");
  const rng=randomFrom(seed);if(variant==="mixed")variant=variants[rng.integer(0,variants.length-1)];const mode=variants.indexOf(variant);if(mode<0)throw new Error("Unknown exponential pattern variant");
  const [qn,qd]=rng.shuffle([[2,1],[3,1],[3,2],[1,2],[2,3]])[0],q=r(qn+"/"+qd),flag=rng.integer(0,1),a=rng.integer(1,6)*(mode===5&&flag?-1:1),k=mode===5?rng.integer(4,10):0,step=mode===3?rng.integer(2,4):rng.integer(1,3),n0=mode===4?rng.shuffle([-2,-1,1,2,3])[0]:rng.integer(-2,3),x0=n0*step,s=(flag?1:-1)*rng.integer(1,4),delta=rng.integer(1,3),constant=flag?rng.integer(1,8):0;
  const indices=mode===2?[0,1,3,4]:[0,1,2,3],power=(i:number)=>r(a+"*("+q+")^("+i+")"),y=(i:number)=>mode===0?String(a+s*i):mode===6?String(constant):r(k+"+("+power(i)+")+"+(mode===7&&i===3?delta:0));
  const points=indices.map(i=>({x:String(x0+i*step),y:y(i)})),analysis=analyzeExponentialTable(points,String(k));
  const model=exponentialFunctionSchema.parse({kind:"rational-base",base:q,a:String(a),rate:"1/"+step,h:String(x0),k:String(k)});
  const output=(x:number)=>{const result=evaluateExponential(model,String(x));if(result.status!=="finite"||result.exact===null)throw new Error("This table needs exact predictions.");return result.exact;};
  const choice=(id:string,label:string,correct:string,choices:typeof options)=>({id,label,kind:"choice",correct,options:rng.shuffle(choices)});
  const classification=choice("pattern","Pattern consistent with every record",analysis.classification,options);
  const table="Exact records with t in seconds relative to a reference and y in V: "+points.map(point=>"(t="+point.x+", y="+point.y+")").join("; ")+". ";
  const base={id,familyId,familyVersion:1,courseId:"mth-215",objectiveId:"m05-l01",critical:true,category:mode===3||mode===4?"procedural":"conceptual",parameters:{mode,qn,qd,a,k,step,n0,x0,s,delta,constant,flag}};
  if(mode===0)return questionSchema.parse({...base,prompt:table+"Compare the three output differences over the equal input steps. Find the output change per second and predict the next value at t="+(x0+4*step)+" if this pattern continues. The stated baseline is zero.",fields:[number("first","First output difference",analysis.differences[0],"V"),number("second","Second output difference",analysis.differences[1],"V"),number("third","Third output difference",analysis.differences[2],"V"),number("rate","Output change per second",s+"/"+step,"V/s"),number("next","Predicted next output",String(a+4*s),"V"),classification],hints:["Subtract each preceding output from the next, keeping the record order.","Divide an output difference by the actual input step to obtain the per-second rate.","A constant difference supports a linear pattern on these records. Continue it by one more addition."],explanation:["Each input gap is "+step+" s and each output difference is "+s+" V.","The rate is "+r(s+"/"+step)+" V/s; the next predicted output is "+(a+4*s)+" V.","These records fit a nonconstant linear rule. The prediction assumes that the rule continues beyond the records."],answerSummary:"Differences "+s+" V; rate "+r(s+"/"+step)+" V/s; next "+(a+4*s)+" V; linear."});
  if(mode===2)return questionSchema.parse({...base,prompt:table+"Find the first two input gaps and the first two consecutive output ratios. Decide whether their unequal ratios alone rule out a single exponential model.",fields:[number("first-gap","First input gap",String(step),"s"),number("second-gap","Second input gap",String(2*step),"s"),number("first-ratio","First consecutive output ratio",q),number("second-ratio","Second consecutive output ratio",r("("+q+")^2")),choice("verdict","Do unequal consecutive ratios alone rule out an exponential here?","no",[
    {id:"no",label:"No; these ratios cover different input lengths",feedback:"The second interval is twice as long, so an exponential factor is applied twice."},
    {id:"yes",label:"Yes; every consecutive ratio must match regardless of spacing",feedback:"The constant-ratio test requires equal input increments."},
    {id:"linear",label:"Yes; unequal ratios prove the data are linear",feedback:"Linearity requires constant output change per input change, not merely unequal output ratios."},
  ])],hints:["Check the time gaps before comparing output ratios.","The middle gap spans two of the first gaps.","An exponential that multiplies by q over one gap multiplies by q squared over a gap twice as long."],explanation:["The first two gaps are "+step+" s and "+(2*step)+" s.","Their output ratios are "+q+" and "+r("("+q+")^2")+", respectively.","The middle ratio equals the square of the first. All four records are consistent with factor "+q+" per "+step+" s, so unequal consecutive ratios do not reject an exponential when spacing differs."],answerSummary:"Gaps "+step+", "+(2*step)+" s; ratios "+q+", "+r("("+q+")^2")+"; no rejection from unequal-spacing ratios."});
  if(mode===3){
    const exponent="\\frac{t-("+x0+")}{"+step+"}",math="("+a+")\\left("+q+"\\right)^{"+exponent+"}";
    const formulas=[
      {id:"step",label:"$y(t)="+math+"$",accessibleLabel:"y of t equals "+a+" times ("+q+") raised to ((t minus ("+x0+")) divided by "+step+").",feedback:"The exponent counts complete or fractional intervals of the stated step length."},
      {id:"seconds",label:"$y(t)=("+a+")\\left("+q+"\\right)^{t-("+x0+")}$",accessibleLabel:"y of t equals "+a+" times ("+q+") raised to (t minus ("+x0+")).",feedback:"This incorrectly applies the observed multi-second factor every second."},
      {id:"sum",label:"$y(t)="+a+"+("+q+")"+exponent+"$",accessibleLabel:"y of t equals "+a+" plus ("+q+") times ((t minus ("+x0+")) divided by "+step+").",feedback:"Adding a fixed amount creates a linear rule, not the observed multiplicative pattern."},
    ];
    return questionSchema.parse({...base,prompt:table+"Assume one exponential law with zero baseline. In y(t)=A*B^((t-t0)/d), use t0="+x0+" s. Recover A, B and d, select the matching rule, and predict y at t="+(x0+4*step)+" s.",fields:[number("amplitude","A at the reference input",String(a),"V"),number("factor","Observed step multiplier B",q),number("step","Step duration d",String(step),"s"),choice("formula","Exponential rule","step",formulas),number("next","Predicted next output",output(x0+4*step),"V")],hints:["At t=t0 the exponent is zero, so A is the recorded response there.","B is the ratio over d seconds, not automatically the per-second factor.","The requested input is four step durations after t0, so use the fourth power of B."],explanation:["A="+a+" V, B="+q+", and d="+step+" s.","The rule is $y(t)="+math+"$.","At t="+(x0+4*step)+" s the exponent is 4, giving "+output(x0+4*step)+" V.","The exponent is dimensionless because elapsed seconds are divided by the step duration in seconds."],answerSummary:"A="+a+" V; B="+q+" per "+step+" s; divide elapsed time by "+step+"; next "+output(x0+4*step)+" V."});
  }
  if(mode===4)return questionSchema.parse({...base,prompt:table+"Assume a single unshifted exponential y(t)=A*b^t. Determine the multiplier over one observed interval, the first recorded response, and the model's response at t=0. Which quantity is A?",fields:[number("factor","Multiplier over the observed interval",q),number("recorded","First recorded response",String(a),"V"),number("initial","Response at t = 0",output(0),"V"),choice("coefficient","Meaning of A in y(t) = A*b^t","zero",[
    {id:"zero",label:"The model response at t = 0",feedback:"The exponent is zero at t=0, so b to that power is one."},
    {id:"recorded",label:"Always the first recorded response",feedback:"The first record here is at a nonzero time."},
    {id:"factor",label:"The observed step multiplier",feedback:"A scales the response; the base and step determine the multiplier."},
  ])],hints:["Consecutive records are separated by the stated common time gap.","Move from the first record to t=0 by "+(-n0)+" observed steps, using reciprocal factors for backward steps.","The coefficient A is defined by the model's value at zero, not by the order of the records."],explanation:["The step factor is "+q+" over "+step+" s, and the first recorded response is "+a+" V at t="+x0+" s.","Zero is "+(-n0)+" steps from that record, so y(0)="+output(0)+" V.","Therefore A="+output(0)+" V. The positive per-second base raised to power "+step+" equals the observed factor; no decimal approximation of that base is needed for this calculation."],answerSummary:"Step factor "+q+"; first record "+a+" V; A=y(0)="+output(0)+" V."});
  if(mode===5)return questionSchema.parse({...base,prompt:table+"The supplied baseline is k="+k+" V. Analyze the deviations y-k, then predict the next output at t="+(x0+4*step)+" s under the same model. Decide which ratio should stay constant.",fields:[number("first","First deviation from baseline",String(a),"V"),number("second","Second deviation from baseline",power(1),"V"),number("factor","Common deviation multiplier",q),number("next","Predicted next output",output(x0+4*step),"V"),choice("ratio","Ratio appropriate to this baseline","deviation",[
    {id:"deviation",label:"Next deviation divided by preceding deviation",feedback:"Subtract the supplied baseline before testing exponential scaling."},
    {id:"raw",label:"Next raw output divided by preceding raw output",feedback:"A nonzero fixed offset generally prevents the raw output ratio from staying constant."},
    {id:"difference",label:"The ratio is unnecessary because all output differences match",feedback:"The baseline-relative exponential still changes differences from one interval to the next."},
  ])],hints:["Subtract k from each output before computing a ratio.","A negative deviation is permitted; two consecutive deviations have the same sign and a positive ratio.","Multiply the initial deviation by the fourth power of the step factor, then add the baseline back."],explanation:["The first two deviations are "+a+" V and "+power(1)+" V.","All baseline-relative ratios equal "+q+" over "+step+" s.","The next predicted output is "+k+"+("+a+")*("+q+")^4="+output(x0+4*step)+" V.","Ratios apply to y-k. The original outputs may have changing ratios or even cross zero without invalidating the shifted exponential."],answerSummary:"Deviations "+a+", "+power(1)+" V; factor "+q+"; next "+output(x0+4*step)+" V; use deviation ratios."});
  if(mode===6)return questionSchema.parse({...base,prompt:table+"Classify the records and report their output difference. Extend the stated constant-output rule by one step. Are raw consecutive output ratios equal to one or undefined? Does this fit a nonconstant y=A*b^t with A nonzero and b positive but unequal to one?",fields:[number("difference","Output difference","0","V"),number("next","Next output under the constant rule",String(constant),"V"),classification,choice("ratios","Raw output ratio status",constant?"one":"undefined",[
    {id:"one",label:"Defined and equal to one",feedback:"A nonzero constant divided by itself is one."},
    {id:"undefined",label:"Undefined because the preceding output is zero",feedback:"Zero divided by zero does not define a growth factor."},
  ]),choice("nonconstant","Is this the specified nonconstant exponential?","no",[
    {id:"no",label:"No",feedback:"A nonconstant real exponential with nonzero scale cannot give a constant output at these distinct inputs."},
    {id:"yes",label:"Yes",feedback:"The stated exclusions A not zero and b not one rule out the constant cases."},
  ])],hints:["Compare all output values before dividing anything.","If the constant is zero, the output ratio would divide zero by zero.","A nonzero constant would require base one in A*b^t; the zero function would require scale zero. Both are excluded in the question."],explanation:["The output difference is zero and the continued constant output is "+constant+" V.",constant?"Every raw output ratio is one.":"The raw output ratios are undefined, not zero or one.","These are constant records. Under the stated constant rule, they are not a nonconstant exponential of the specified form."],answerSummary:"Difference 0; next "+constant+" V; constant; ratios "+(constant?"one":"undefined")+"; not the specified nonconstant exponential."});
  if(mode===7)return questionSchema.parse({...base,prompt:table+"Fit the zero-baseline exponential factor using the first two records, then audit every remaining record. Compute all three consecutive ratios, predict the fourth response from that fitted factor, and give observed minus predicted at the fourth input.",fields:[number("first","First consecutive ratio",analysis.ratios[0]!),number("second","Second consecutive ratio",analysis.ratios[1]!),number("third","Third consecutive ratio",analysis.ratios[2]!),number("predicted","Predicted fourth response",power(3),"V"),number("residual","Fourth observed minus predicted",String(delta),"V"),choice("consistent","Are all exact records consistent with that exponential?","no",[
    {id:"no",label:"No; the fourth record contradicts the fitted factor",feedback:"A nonzero exact residual rejects the proposed exact model for all these records."},
    {id:"yes",label:"Yes; fitting two records establishes every other value",feedback:"Additional records must also satisfy the fitted rule."},
  ])],hints:["Use next output divided by previous output because the time gaps are equal and the baseline is zero.","Apply the first ratio three times to the first response to predict the fourth.","Subtract the predicted fourth output from the observed one. These are exact records, so a nonzero residual is a contradiction."],explanation:["The first two ratios equal "+q+", but the third is "+analysis.ratios[2]+".","The fitted fourth response is "+power(3)+" V, while the observed response is "+y(3)+" V.","The residual is "+delta+" V. The records therefore contradict the proposed exact zero-baseline exponential."],answerSummary:"Ratios "+analysis.ratios.join(", ")+"; predicted fourth "+power(3)+" V; residual "+delta+" V; inconsistent."});
  return questionSchema.parse({...base,prompt:table+"The baseline is zero. Identify the equal time step and common output multiplier, classify the pattern, and predict the next output at t="+(x0+4*step)+" s if the same rule continues.",fields:[number("step","Common input step",String(step),"s"),number("factor","Common output multiplier",q),number("next","Predicted next output",output(x0+4*step),"V"),classification],hints:["Check the input spacing before applying the constant-ratio test.","Divide each next output by the preceding one; all three ratios must agree.","One more step multiplies the fourth recorded output by the same factor."],explanation:["The time step is "+step+" s and every output ratio is "+q+".","This is consistent with a nonconstant exponential at the recorded inputs.","The next output is "+output(x0+4*step)+" V under the continued rule. Finite data do not establish the model at every unobserved input."],answerSummary:"Step "+step+" s; multiplier "+q+"; exponential; next "+output(x0+4*step)+" V."});
}
