import { questionSchema,type Question } from "../contracts";
import { analyzeSignChart } from "../sign-chart";
import { compareRealExact,parseRealEndpoint } from "../exact-order";
import { formatExact } from "../exact-number";
import { formatIntervals } from "../intervals";
import { relationLatex,reverseRelation,type Relation } from "../inequalities";
import { formatPolynomial,parsePolynomial } from "../polynomial";
import { formatRationalFunction } from "../rational-function";
import { formatRational,parseRational } from "../rational";
import { randomFrom } from "../random";

export const signReasoningFamilyIds=["mth-sign-boundary","mth-sign-audit"] as const;
const yesNo=(id:string,label:string,yes:boolean,feedback:string)=>({id,label,kind:"choice",correct:yes?"yes":"no",options:[{id:"yes",label:"Yes",feedback},{id:"no",label:"No",feedback}]});
const roots=(expected:string[])=>({id:"excluded",label:"Original excluded inputs",kind:"roots",numberSystem:"real",expected});
export function signReasoningQuestion(familyId:string,variant:string,seed:string,id:string):Question{
  const rng=randomFrom(seed),a=-rng.integer(1,4),b=rng.integer(1,4),k=rng.integer(1,3),d=[2,3,5][rng.integer(0,2)],scale=k*(rng.integer(0,1)?1:-1);
  const relations:Relation[]=["lt","le","gt","ge"];let relationIndex=rng.integer(0,3);
  const base={id,familyId,familyVersion:1,courseId:"mth-215",objectiveId:"m04-l02",critical:true,category:"conceptual"};
  const factor=(n:number)=>"("+formatPolynomial(parsePolynomial("x-("+n+")"))+")";
  if(familyId==="mth-sign-boundary"){
    const variants=["zero","pole","hole","partial-pole","isolated-zero","irrational-zero","crossing-hole"];
    if(variant==="mixed")variant=variants[rng.integer(0,variants.length-1)];const mode=variants.indexOf(variant);if(mode<0)throw new Error("Unknown sign-boundary variant");
    if(mode===4)relationIndex=1;
    const source=["("+scale+"*"+factor(a)+")/"+factor(b),"("+scale+"*"+factor(a)+")/"+factor(b),"("+scale+"*"+factor(a)+")/("+factor(a)+"*"+factor(b)+")", "("+scale+"*"+factor(a)+")/("+factor(a)+"^3)",k+"*"+factor(a)+"^2","("+scale+"*(x^2-"+d+"))/"+factor(b),"("+scale+"*"+factor(a)+"^2)/("+factor(a)+"*"+factor(b)+")"][mode];
    const relation=relations[relationIndex],chart=analyzeSignChart(source,relation),input=mode===1?String(b):mode===5?"sqrt("+d+")":String(a),index=chart.critical.findIndex(point=>compareRealExact(parseRealEndpoint(point.input),parseRealEndpoint(input))===0),point=chart.critical[index];
    const type=point.kind==="zero"?"zero":point.numeratorMultiplicity!==null&&point.numeratorMultiplicity>=point.denominatorMultiplicity?"hole":"pole";
    const sign=(id:string,label:string,value:number)=>({id,label,kind:"choice",correct:value>0?"positive":"negative",options:[{id:"positive",label:"Positive",feedback:"Use a test input in the adjacent open interval, including the signed scale."},{id:"negative",label:"Negative",feedback:"Use a test input in the adjacent open interval, including the signed scale."}]});
    return questionSchema.parse({...base,parameters:{a,b,k,d,scale,mode,relationIndex},prompt:"For $"+formatRationalFunction(chart.original,true)+relationLatex[relation]+"0$, inspect the critical input $x="+formatExact(parseRealEndpoint(input),true)+"$. Classify the point, determine whether the inequality includes it, and compare the two adjacent interval signs.",
      fields:[{id:"kind",label:"Type of critical input",kind:"choice",correct:type,options:[{id:"zero",label:"Allowed zero of the original expression",feedback:"An allowed zero has a zero numerator and nonzero original denominator."},{id:"hole",label:"Excluded input with a removable hole",feedback:"All denominator copies cancel, but the original input remains excluded."},{id:"pole",label:"Excluded input with a remaining pole",feedback:"Denominator copies remain after any cancellation, so the original input is excluded."}]},
        yesNo("include","Include this input in the solution set?",point.included,"Include an allowed zero only when equality is permitted. A hole or pole stays excluded for every relation."),
        sign("left","Sign immediately to the left",chart.intervals[index].sign),sign("right","Sign immediately to the right",chart.intervals[index+1].sign)],
      hints:["Check the original denominator at the specified input before assigning it a value.","Compare numerator and denominator multiplicities to distinguish an allowed zero, a hole, and a remaining pole.","Work out both interval signs separately. A point's inclusion depends on its original value and the relation, not only on whether the sign changes."],
      explanation:["The input is an "+(type==="zero"?"allowed zero":type==="hole"?"excluded hole":"excluded pole")+".","Its numerator and denominator multiplicities are "+point.numeratorMultiplicity+" and "+point.denominatorMultiplicity+".","The adjacent signs are "+(chart.intervals[index].sign>0?"positive":"negative")+" on the left and "+(chart.intervals[index+1].sign>0?"positive":"negative")+" on the right.",point.included?"Equality is allowed at this original zero, so include it even if neither adjacent interval qualifies.":"This boundary does not belong to the solution. Strict relations reject zero, and every original exclusion remains excluded."],
      answerSummary:type+"; "+(point.included?"include":"exclude")+"; left "+(chart.intervals[index].sign>0?"positive":"negative")+", right "+(chart.intervals[index+1].sign>0?"positive":"negative")+"."});
  }
  if(familyId!=="mth-sign-audit")throw new Error("Unknown sign-reasoning family");
  const variants=["unknown-sign","negative-branch","positive-branch","safe-square","restored-pole","nonzero-right","model-domain"];
  if(variant==="mixed")variant=variants[rng.integer(0,variants.length-1)];const mode=variants.indexOf(variant);if(mode<0)throw new Error("Unknown sign-audit variant");
  const source="("+factor(a)+")/"+factor(b),relation=mode===0?"gt":mode===4||mode===5?"ge":relations[relationIndex],chart=analyzeSignChart(source,relation,mode===5?String(k):"0"),formula="$"+formatRationalFunction(chart.original,true)+relationLatex[relation]+(mode===5?k:0)+"$";
  if(mode===0)return questionSchema.parse({...base,parameters:{a,b,mode},prompt:"A learner multiplies "+formula+" by x-"+b+" and concludes x- ("+a+") > 0 for all real inputs except "+b+". Audit this step using the allowed test input x=0.",
    fields:[yesNo("valid","Is the multiplication valid across the whole original domain?",false,"The denominator has different signs on different intervals. Multiplying by a negative value must reverse the relation."),{id:"value",label:"Original fraction at x = 0",kind:"rational",expected:formatRational(parseRational(a+"/"+b))},yesNo("original","Does x = 0 satisfy the original inequality?",false,"At zero the original fraction is negative."),yesNo("proposed","Does x = 0 satisfy the learner's proposed inequality?",true,"The proposed numerator-only inequality is positive at zero, creating a false solution.")],
    hints:["Zero is allowed because the pole input is positive.","At zero the numerator is positive and the denominator is negative.","The original quotient is negative, while the proposed numerator is positive. The conditions disagree."],explanation:["At zero the quotient is "+formatRational(parseRational(a+"/"+b))+", which is negative.","The proposed numerator-only inequality accepts zero, so it is not equivalent.","Use a sign chart, split according to denominator sign, or multiply by the positive denominator square on the original domain."],answerSummary:"Invalid; original quotient "+formatRational(parseRational(a+"/"+b))+"; original false, proposed true."});
  if(mode===1||mode===2){
    const negative=mode===1,newRelation=negative?reverseRelation[relation]:relation,branch=[{lower:negative?null:String(b),upper:negative?String(b):null,lowerClosed:false,upperClosed:false}];
    return questionSchema.parse({...base,parameters:{a,b,mode,relationIndex},prompt:"Solve the transformation step in "+formula+" only on the branch x "+(negative?"<":">")+" "+b+". After multiplying by its denominator on that branch, which relation compares x- ("+a+") with zero? State the branch domain, not the full final solution.",
      fields:[{id:"relation",label:"Relation after multiplying on this branch",kind:"choice",correct:newRelation,options:relations.map(r=>({id:r,label:r==="lt"?"Less than":r==="le"?"Less than or equal":r==="gt"?"Greater than":"Greater than or equal",feedback:negative?"The denominator is negative throughout this branch, so reverse the relation.":"The denominator is positive throughout this branch, so keep the relation."}))},{id:"branch",label:"Stated branch domain",kind:"intervals",expected:branch}],
      hints:["Determine the sign of x-"+b+" on the stated branch.",negative?"Every branch input makes the denominator negative.":"Every branch input makes the denominator positive.","A negative multiplier reverses the relation; a positive multiplier preserves it. The pole is never in the branch."],explanation:["The denominator is "+(negative?"negative":"positive")+" on "+formatIntervals(branch)+".","The transformed comparison is $x-("+a+")"+relationLatex[newRelation]+"0$ on this branch only.","Intersect any resulting inequality solution with this branch before combining it with another branch."],answerSummary:newRelation+" on "+formatIntervals(branch)+"."});
  }
  if(mode===3||mode===4){
    const polynomial=parsePolynomial(factor(a)+"*"+factor(b));
    return questionSchema.parse({...base,parameters:{a,b,mode,relationIndex},prompt:mode===3?"For "+formula+", multiply by $(x-"+b+")^2$ on the original domain. State whether the step is reversible there, give the resulting polynomial on the left, and retain the original exclusion.":"For "+formula+", a learner multiplies by $(x-"+b+")^2$ and solves the resulting polynomial inequality over all real numbers, including x="+b+". Audit this claimed equivalence and repair the domain.",
      fields:[yesNo("valid",mode===3?"Is multiplication by the square reversible on the original domain?":"Is the learner's enlarged solution domain valid?",mode===3,"The square is strictly positive at every allowed original input. At the pole it is zero, and the original fraction is undefined."),{id:"polynomial",label:"Polynomial after multiplying by the denominator square",kind:"polynomial",form:"equivalent",expected:formatPolynomial(polynomial)},roots([String(b)])],
      hints:["On the original domain, the denominator square is strictly positive.","One denominator copy cancels, leaving numerator times denominator.","Keep x different from the original pole. A zero of the transformed polynomial does not automatically become an original solution."],explanation:["The polynomial comparison uses $"+formatPolynomial(polynomial,true)+relationLatex[relation]+"0$ with x different from "+b+".",mode===3?"Strict positivity makes the transformation reversible throughout that retained domain.":"The enlarged domain is invalid. The transformed polynomial is zero at the pole, but the original quotient has no value there."],answerSummary:(mode===3?"Valid on the original domain":"Invalid enlarged domain")+"; polynomial "+formatPolynomial(polynomial)+"; exclude "+b+"."});
  }
  if(mode===5)return questionSchema.parse({...base,parameters:{a,b,k,mode},prompt:"Rewrite "+formula+" with zero on the right. A learner subtracts "+k+" from only the numerator. Audit that step, then give the correct comparison numerator and original exclusions.",
    fields:[yesNo("valid","Does subtracting only from the numerator preserve the comparison?",false,"Rewrite the constant over the same denominator. Subtract k times the whole denominator, not k alone."),{id:"numerator",label:"Correct numerator after moving the right side",kind:"polynomial",form:"equivalent",expected:formatPolynomial(chart.numerator)},roots([String(b)])],
    hints:["Move the constant to the left without multiplying by an unknown-sign expression.","Write the constant as k times the denominator over the denominator, on the original domain.","Subtract k(x-b) from the complete original numerator and collect terms."],explanation:["The comparison becomes $\\frac{"+formatPolynomial(chart.numerator,true)+"}{"+formatPolynomial(chart.original.denominator,true)+"}\\ge0$.","The original exclusion remains x="+b+".","The new numerator, not the old numerator, determines the zero boundaries for the sign chart."],answerSummary:"Invalid subtraction; comparison numerator "+formatPolynomial(chart.numerator)+"; exclude "+b+"."});
  const h=rng.integer(1,3),pole=h+rng.integer(1,3),maximum=pole+2,expected=[{lower:"0",upper:String(h),lowerClosed:true,upperClosed:true},{lower:String(pole),upper:String(maximum),lowerClosed:false,upperClosed:true}];
  return questionSchema.parse({...base,category:"application",parameters:{h,pole,maximum,k,mode},prompt:"A supplied calibration model has response $R(t)=\\frac{"+k+"(t-"+h+")}{t-"+pole+"}$ for times from 0 through "+maximum+" seconds inclusive. Find every allowed time for which the response is nonnegative. The formula remains undefined at its denominator zero.",
    fields:[{id:"solution",label:"Allowed time intervals",kind:"intervals",unit:"s",expected},yesNo("zero","Include the numerator-zero time?",true,"Nonnegative includes an allowed output of zero."),yesNo("pole","Include the denominator-zero time?",false,"The original model is undefined at that time, even though the inequality is non-strict.")],
    hints:["First solve the rational inequality on its original mathematical domain.","The positive scale does not change the signs. The response is nonnegative on or left of the numerator zero, or strictly right of the pole.","Intersect those intervals with the supplied closed time window. Keep the numerator zero and window endpoints when allowed, but remove the pole."],
    explanation:["The unrestricted nonnegative set is $(-\\infty,"+h+"]\\cup("+pole+",\\infty)$.","Intersecting with $[0,"+maximum+"]$ gives "+formatIntervals(expected)+" seconds.","The numerator zero is a valid boundary; the denominator zero is excluded. The supplied time window also limits the answer."],answerSummary:formatIntervals(expected)+" seconds."});
}
