import { questionSchema,type Question } from "../contracts";
import { parseIntervals } from "../intervals";
import { formatRational,parseRational } from "../rational";
import { rationalLatex } from "../transformations";
import { randomFrom } from "../random";

export const expEquationFamilyIds=["mth-exp-equation"] as const;
const variants=["common-base","related-bases","shifted-factor","natural-base","different-bases","nonpositive-target","identity-or-empty","quadratic-two","quadratic-filter"];
const r=(source:string)=>formatRational(parseRational(source));
const rational=(id:string,label:string,expected:string)=>({id,label,kind:"rational",expected:r(expected)});
const roots=(expected:string[])=>({id:"solutions",label:"Complete exact real solution set for x",kind:"logarithmic-roots",expected});
const affine=(a:number,c:number)=>a+"x+("+c+")";
export function expEquationQuestion(familyId:string,variant:string,seed:string,id:string):Question{
  if(familyId!=="mth-exp-equation")throw new Error("Unknown exponential equation family");
  const rng=randomFrom(seed);if(variant==="mixed")variant=variants[rng.integer(0,variants.length-1)];const mode=variants.indexOf(variant);if(mode<0)throw new Error("Unknown exponential equation variant");
  const magnitude=rng.shuffle(mode===4?[2,3]:[2,3,5])[0],reciprocal=rng.integer(0,1),bn=reciprocal?1:magnitude,bd=reciprocal?magnitude:1,b=r(bn+"/"+bd),a=rng.shuffle([-3,-2,-1,1,2,3])[0],c=rng.integer(-3,3),m=rng.integer(2,3),n=rng.integer(1,3);
  let d=rng.shuffle([-3,-2,-1,1,2,3])[0];if(mode===0&&d===a||mode===1&&m*a===n*d)d=-d;
  const f=rng.integer(-3,3),s=rng.shuffle([-4,-3,-2,-1,1,2,3,4])[0],k=rng.integer(-6,6),uN=rng.integer(2,9),uD=rng.integer(1,4),flag=rng.integer(0,1),quadraticFlag=rng.integer(0,4),otherMagnitude=rng.shuffle([5,7])[0],otherReciprocal=rng.integer(0,1),otherN=otherReciprocal?1:otherMagnitude,otherD=otherReciprocal?otherMagnitude:1,other=r(otherN+"/"+otherD);
  const candidates=[[1,2],[1,1],[2,1],[3,1],[5,1]],firstIndex=rng.integer(0,4),secondIndex=(firstIndex+rng.integer(1,4))%5;
  const r1d=candidates[firstIndex][1];let r1n=candidates[firstIndex][0],[r2n,r2d]=candidates[secondIndex];
  if(mode===8){
    if(quadraticFlag===0)r2n=0;
    if(quadraticFlag===1)r2n=-r2n;
    if(quadraticFlag===2){r1n=-r1n;r2n=-r2n;}
    if(quadraticFlag===3){r1n=0;r2n=-r2n;}
    if(quadraticFlag===4){r2n=r1n;r2d=r1d;}
  }
  const u=mode===5?flag?"0":String(-uN):r(uN+"/"+uD),target=r(s+"*("+u+")+("+k+")"),B="\\left("+rationalLatex(b)+"\\right)",E=mode===3?"e":B;
  const base={id,familyId,familyVersion:1,courseId:"mth-215",objectiveId:"m05-l03",critical:true,category:"procedural",parameters:{mode,bn,bd,a,c,d,f,m,n,s,k,uN,uD,flag,quadraticFlag,otherN,otherD,r1n,r1d,r2n,r2d}};
  if(mode<=1){
    const leftPower=mode===1?m:1,rightPower=mode===1?n:1,slope=leftPower*a-rightPower*d,constant=rightPower*f-leftPower*c,solution=r(constant+"/("+slope+")"),leftBase=r("("+b+")^"+leftPower),rightBase=r("("+b+")^"+rightPower);
    return questionSchema.parse({...base,prompt:"Solve $\\left("+rationalLatex(leftBase)+"\\right)^{"+affine(a,c)+"}=\\left("+rationalLatex(rightBase)+"\\right)^{"+affine(d,f)+"}$ over the real numbers. Use the supplied common base "+b+", expand the exponents, and construct the linear equation $Ax=C$ before giving every solution.",fields:[rational("coefficient","Coefficient A after collecting x terms",String(slope)),rational("constant","Constant C after collecting constant terms",String(constant)),roots([solution])],hints:["Rewrite each positive base as a power of the supplied common base, using the full exponent on each side.","A positive-base exponential with base different from one is one-to-one, including a base below one. Equate exponents and distribute every multiplier.","Move the x terms to the left and constant terms to the right. Divide by the nonzero coefficient and substitute into both original exponents."],explanation:["The left base is "+b+" to power "+leftPower+" and the right base is "+b+" to power "+rightPower+".","Equality of the same valid exponential base requires "+leftPower+"("+a+"x+("+c+"))="+rightPower+"("+d+"x+("+f+")).","Collecting terms gives "+slope+"x="+constant+", so x="+solution+".","The coefficient "+slope+" is nonzero, so this linear equation has exactly one solution. Substitution makes the two original exponents of the common base equal; every real x was permitted initially."],answerSummary:"A="+slope+"; C="+constant+"; x="+solution+"."});
  }
  if(mode===2||mode===3||mode===5){
    const expression=mode===3?"(ln("+u+")-("+c+"))/("+a+")":"(ln("+u+")/ln("+b+")-("+c+"))/("+a+")";
    return questionSchema.parse({...base,prompt:"Solve $"+s+E+"^{"+affine(a,c)+"}+("+k+")="+rationalLatex(target)+"$ over the real numbers. First isolate the exponential term, then give the complete exact solution set. Keep all signs when subtracting the offset and dividing by the outside coefficient.",fields:[rational("isolated","Isolated exponential value",u),roots(mode===5?[]:[expression]),{id:"range",label:"Range fact used to check the isolated equation",kind:"choice",correct:"positive",options:rng.shuffle([{id:"positive",label:"A real exponential with a positive base is strictly positive",feedback:"Its value can approach zero but never reach or cross it. This rules out zero and negative isolated targets."},{id:"nonnegative",label:"A real exponential can equal zero but cannot be negative",feedback:"Zero is not attained by any finite real exponent of a positive base."},{id:"all",label:"Every real isolated target can be used as a logarithm argument",feedback:"A real logarithm requires a strictly positive argument."}])}],hints:["Subtract the offset before dividing by the outside coefficient. The isolated target can have a different sign from the original right-hand side.","Check whether that isolated target is strictly positive before taking any logarithm.",mode===5?"No finite real exponent of a positive base can give zero or a negative number. Do not try to take a real logarithm of that target.":"Take the appropriate logarithm, then undo the exponent's shift and nonzero coefficient. Keep the exact logarithm in the solution."],explanation:["Subtracting "+k+" and dividing by "+s+" gives the isolated exponential value "+u+".",mode===5?"This value is "+(flag?"zero":"negative")+", outside the strictly positive range. There are no real solutions.":"The positive isolated value permits a logarithm. Solving the affine exponent gives x="+expression+".",mode===5?"An approach toward zero is not an attained zero. The original shifted equation still has no real solution, regardless of the outside coefficient's sign.":"Substitution makes the exponent the logarithm of "+u+" in the original base, so the exponential equals "+u+" and the full expression equals "+target+". Its nonzero exponent coefficient and valid base ensure exactly one solution."],answerSummary:"Isolated exponential "+u+"; "+(mode===5?"no real solutions":"x="+expression)+"; a positive-base exponential is strictly positive."});
  }
  if(mode===4){
    const coefficient="("+a+")*ln("+b+")-("+d+")*ln("+other+")",constant="("+f+")*ln("+other+")-("+c+")*ln("+b+")",solution="("+constant+")/("+coefficient+")";
    return questionSchema.parse({...base,prompt:"Solve $"+B+"^{"+affine(a,c)+"}=\\left("+rationalLatex(other)+"\\right)^{"+affine(d,f)+"}$ exactly. Take natural logarithms, then collect terms as $Ax=C$. Give the exact coefficient A, constant C, and complete real solution set.",fields:[{id:"coefficient",label:"Exact coefficient A",kind:"logarithmic",expected:coefficient},{id:"constant",label:"Exact constant C",kind:"logarithmic",expected:constant},roots([solution])],hints:["Both original sides are positive for every real x, so taking natural logarithms is reversible.","Use the power identity to move each complete affine exponent outside its logarithm. Group both x terms on the left.","Divide the exact constant by the exact coefficient. Do not round the logarithms before solving or treat different bases as equal."],explanation:["Taking natural logarithms gives $("+affine(a,c)+")\\ln("+rationalLatex(b)+")=("+affine(d,f)+")\\ln("+rationalLatex(other)+")$.","Collecting terms gives A="+coefficient+" and C="+constant+".","The exact coefficient is nonzero. Otherwise, nonzero integer powers of the two distinct underlying primes would be equal, contradicting their different prime factorizations.","The unique real solution is x="+solution+". Substituting this expression makes the logarithms of both original sides equal, and the exponential function returns equal positive sides."],answerSummary:"A="+coefficient+"; C="+constant+"; x="+solution+"."});
  }
  if(mode===6){
    const rightConstant=flag?c:c+m;
    return questionSchema.parse({...base,category:"conceptual",prompt:"Solve $"+B+"^{"+affine(a,c)+"}="+B+"^{"+affine(a,rightConstant)+"}$ over the real numbers. After equating exponents, the x terms cancel. Give the remaining difference between the left and right exponents and describe the complete real solution set with interval notation, R, or empty.",fields:[rational("difference","Left exponent minus right exponent",String(c-rightConstant)),{id:"solutions",label:"Complete real solution set",kind:"intervals",expected:parseIntervals(flag?"R":"empty"),help:"Use R for all real numbers, empty for no solutions, or interval notation for another set."},{id:"reason",label:"What does the reduced equation establish?",kind:"choice",correct:flag?"identity":"contradiction",options:rng.shuffle([{id:"identity",label:"An identity true for every original real input",feedback:"When the exponents are identical, both positive exponential expressions agree for every real x."},{id:"contradiction",label:"A contradiction, so no real input can solve it",feedback:"Canceling equal x terms can leave unequal constants. That contradiction cannot be fixed by choosing x."},{id:"zero",label:"A unique solution x = 0",feedback:"The disappearance of x does not force x to be zero. Check whether the remaining statement is always true or false."}])}],hints:["The common positive base is different from one, so equal outputs require equal exponents.","Subtract the same x term from each side, then compare the remaining constants.","A true constant statement keeps every original input; a false constant statement keeps none. All real x were allowed by the original exponentials."],explanation:["The exponent difference is "+(c-rightConstant)+".",flag?"The reduced equation is 0=0. It is an identity, and every real x satisfies the original equation.":"The reduced equation would require two unequal constants to be equal. There is no real solution.","The solution set is "+(flag?"R":"empty")+". Do not divide by a zero x coefficient or replace the whole set with the single value zero."],answerSummary:"Exponent difference "+(c-rightConstant)+"; solution set "+(flag?"R":"empty")+"; "+(flag?"identity":"contradiction")+"."});
  }
  const first=r(r1n+"/"+r1d),second=r(r2n+"/"+r2d),sum=r("("+first+")+("+second+")"),product=r("("+first+")*("+second+")"),uRoots=[...new Set([first,second])],accepted=uRoots.filter(value=>parseRational(value).numerator>0n),rejected=uRoots.filter(value=>parseRational(value).numerator<=0n),solutions=accepted.map(value=>"ln("+value+")/ln("+b+")");
  const realRoots=(id:string,label:string,expected:string[])=>({id,label,kind:"roots",numberSystem:"real",expected,help:"List every distinct real value, separated by commas; use none for an empty set. Keep fractions exact."});
  return questionSchema.parse({...base,prompt:"Solve $"+B+"^{2x}-("+rationalLatex(sum)+")"+B+"^x+("+rationalLatex(product)+")=0$ over the real numbers. Set $u="+B+"^x$. Give the allowed range of u, all distinct roots of the resulting quadratic before filtering, the rejected u roots, and every exact real x solution.",fields:[{id:"u-domain",label:"Allowed range of u from the substitution",kind:"intervals",expected:parseIntervals("(0,inf)"),help:"Give the range in interval notation. Zero is not attained."},realRoots("u-roots","All distinct quadratic roots for u before filtering",uRoots),realRoots("rejected","Quadratic u roots rejected by the exponential substitution",rejected),roots(solutions)],hints:["The exponent identity b^(2x)=(b^x)^2 turns this into a quadratic in u, but u must remain strictly positive.","Solve or factor the complete quadratic. List every distinct candidate before applying the substitution restriction.","Reject zero and negative u values. Each remaining positive u gives exactly one x=ln(u)/ln(b). Repeated quadratic roots give only one distinct x value."],explanation:["The substitution has range u>0 and gives $u^2-("+rationalLatex(sum)+")u+("+rationalLatex(product)+")=0$.","Factoring gives $(u-("+rationalLatex(first)+"))(u-("+rationalLatex(second)+"))=0$. The distinct quadratic roots are "+uRoots.join(", ")+".","Reject "+(rejected.length?rejected.join(", "):"none of these candidates")+" because only strictly positive u values can equal the original exponential.","The complete real x solution set is "+(solutions.length?solutions.join(", "):"empty")+".","For each retained value, exponentiating x recovers its positive u root, which satisfies the original quadratic expression. These are all solutions because the substitution is one-to-one from all real x onto all positive u."],answerSummary:"u range (0,inf); quadratic roots "+uRoots.join(", ")+"; rejected "+(rejected.join(", ")||"none")+"; x solutions "+(solutions.join(", ")||"none")+"."});
}
