import { questionSchema } from "../contracts";
import { randomFrom } from "../random";
import { formatRational,parseRational } from "../rational";

export const phs231StepVariants=["explicit-step","semi-step","midpoint-step","constant-acceleration","decay-stability","oscillator-energy","oscillator-stability","endpoint","energy-audit","error-budget"] as const;
export const phs231StepFamilyIds=["phs231-step-audit"];
const rational=(s:string)=>formatRational(parseRational(s));
const field=(id:string,label:string,expected:string,unit:string)=>({id,label,expected:rational(expected),unit,kind:"rational",help:"Use an exact expression or equivalent fraction in the labeled unit."});
export function phs231StepQuestion(familyId:string,variant:string,seed:string,id:string){
  if(familyId!=="phs231-step-audit"||!(phs231StepVariants as readonly string[]).includes(variant))throw Error("Unknown PHS 231 time-step variant.");
  const rng=randomFrom(`${familyId}:${variant}:${seed}`);
  const base={id,familyId,familyVersion:1,courseId:"phs-231",objectiveId:"m09-l01",category:"application",critical:true};
  const choice=(id:string,label:string,correct:string,options:{id:string;label:string;feedback:string}[])=>({id,label,kind:"choice",correct,options:rng.shuffle(options)});
  const finish=(parameters:Record<string,number>,prompt:string,fields:unknown[],hints:string[],explanation:string[],answerSummary:string)=>questionSchema.parse({...base,parameters:Object.fromEntries(Object.entries(parameters).map(([k,v])=>[k,v||0])),prompt,fields,hints,explanation,answerSummary});
  if(["explicit-step","semi-step","midpoint-step"].includes(variant)){
    const m=rng.integer(2,8),k=rng.integer(2,12),b=rng.integer(0,4),X=rng.integer(-6,6),V=rng.integer(-4,4),H=rng.integer(1,5);
    const x=`${X}/10`,v=`${V}/10`,h=`${H}/10`,a=rational(`-(${k}*(${x})+${b}*(${v}))/${m}`);
    const vm=rational(`(${v})+(${h})*(${a})/2`),xm=rational(`(${x})+(${h})*(${v})/2`),am=rational(`-(${k}*(${xm})+${b}*(${vm}))/${m}`);
    const nextV=rational(variant==="midpoint-step"?`(${v})+(${h})*(${am})`:`(${v})+(${h})*(${a})`);
    const nextX=rational(`(${x})+(${h})*(${variant==="explicit-step"?v:variant==="semi-step"?nextV:vm})`);
    const name=variant==="explicit-step"?"simultaneous explicit Euler":variant==="semi-step"?"velocity-first semi-implicit Euler":"explicit midpoint";
    const instruction=variant==="explicit-step"?"Both increments use only the old state.":variant==="semi-step"?"Compute v_new=v+h*a_old, then x_new=x+h*v_new. Here even the damping force uses old velocity.":"Compute x_mid=x+h*v/2 and v_mid=v+h*a_old/2, evaluate a_mid from that midpoint state, then x_new=x+h*v_mid and v_new=v+h*a_mid.";
    return finish({m,k,b,X,V,H},`A synthetic one-dimensional system obeys x'=v and m*v'=-k*x-b*v. Use m=${m} kg, k=${k} N/m, b=${b} kg/s, x=${x} m, v=${v} m/s, and h=${h} s. Perform one step of ${name}. ${instruction} Report old acceleration, updated position and velocity, and updated spring force -k*x_new.`,
      [field("acceleration","Old acceleration",a,"m/s²"),field("position","Updated position",nextX,"m"),field("velocity","Updated velocity",nextV,"m/s"),field("force","Updated spring force",`-${k}*(${nextX})`,"N"),choice("order","Why keep old and intermediate state values separate?","specified",[
        {id:"specified",label:"Each method specifies which state supplies each derivative; overwriting changes the method",feedback:"A new position or velocity is not interchangeable with an old one. Explicit midpoint also needs both midpoint components before its second derivative evaluation."},
        {id:"any",label:"All three methods give the same update if the time step is written down",feedback:"They share a differential equation but use different derivative evaluations. Their finite-step trajectories generally differ."},
        {id:"physical",label:"An updated spring force proves the real force was constant throughout the interval",feedback:"A pointwise force evaluated at a computed endpoint says nothing about a constant physical force across the entire interval."}
      ])],["First compute the signed spring and damping forces at the old state and divide their sum by mass.","Write separate names for old, midpoint, and updated values. Follow the supplied order without overwriting a value still needed.","Reevaluate only the requested spring force at x_new; do not include drag in a field explicitly labeled spring force."],
      [`Old acceleration is (${a}) m/s². ${instruction}`,`The updated position is (${nextX}) m and velocity (${nextV}) m/s. Updated spring force is (${-k}) times the updated position, in newtons.`,"These are numerical updates for the supplied law. They are not exact finite-time solutions merely because the arithmetic is exact."],
      `a_old=${a} m/s²; x_new=${nextX} m; v_new=${nextV} m/s; F_spring=-${k}*x_new N.`);
  }
  if(variant==="constant-acceleration"){
    const x0=rng.integer(-5,5),v0=rng.integer(-4,4),a=(rng.integer(0,1)?1:-1)*rng.integer(1,5),H=rng.integer(1,3),N=rng.integer(2,8),T=H*N;
    const exact=`${x0}+(${v0})*${T}/2+(${a})*(${T}/2)^2/2`,bias=`(${a})*${T}*${H}/8`;
    return finish({x0,v0,a,H,N},`Constant acceleration is a=${a} m/s², with x0=${x0} m and v0=${v0} m/s. Take ${N} equal steps of h=${H}/2 s, reaching T=${T}/2 s. Calculate the exact final velocity and position, and the final positions from simultaneous explicit Euler, velocity-first semi-implicit Euler, and explicit midpoint. Also give the signed explicit-Euler position error. Arithmetic is exact for this exercise.`,
      [field("velocity","Exact final velocity",`${v0}+(${a})*${T}/2`,"m/s"),field("exact","Exact final position",exact,"m"),field("explicit","Explicit Euler final position",`(${exact})-(${bias})`,"m"),field("semi","Velocity-first final position",`(${exact})+(${bias})`,"m"),field("midpoint","Explicit midpoint final position",exact,"m"),field("error","Explicit position minus exact position",`-(${bias})`,"m"),choice("meaning","What does the midpoint result establish?","constant",[
        {id:"constant",label:"Midpoint is exact for this supplied constant-acceleration case; that does not prove universal exactness",feedback:"Velocity is linear in time, so midpoint integration gives the exact position increment here. More general force laws need independent error checks."},
        {id:"all",label:"Midpoint is exact for every acceleration law at any time step",feedback:"An exact result on a constant derivative case does not remove truncation error for a varying acceleration."},
        {id:"sign",label:"Explicit Euler always has a negative position error regardless of the acceleration sign",feedback:"The signed bias is -a*T*h/2. Reversing the acceleration reverses that bias."}
      ])],["All three velocity updates are exact here because the acceleration is constant.","Sum the old velocities for explicit Euler, the new velocities for velocity-first Euler, and the interval midpoint velocities for midpoint.","The explicit position bias is -a*T*h/2; velocity-first has the opposite bias. Keep the sign of a."],
      [`Exact velocity is ${v0}+(${a})*${T}/2 m/s, and exact position is (${exact}) m.`,`Summing the arithmetic velocity sequences gives explicit x = exact x - (${bias}) m, velocity-first x = exact x + (${bias}) m, and midpoint x = exact x.`,"The endpoint time and initial conditions are identical. A negative acceleration reverses the two signed first-order biases."],
      `Exact x=${exact} m; Euler bias=-(${bias}) m; velocity-first bias=(${bias}) m; midpoint bias=0.`);
  }
  if(variant==="decay-stability"){
    const lambda=rng.integer(1,6),R=rng.integer(1,5),y0=rng.integer(2,8),N=rng.integer(3,6),factor=2-R;
    const behavior=R===1?"monotone":R===2?"zero":R===3?"alternating":R===4?"boundary":"growth";
    return finish({lambda,R,y0,N},`The exact model is y'=-λy with λ=${lambda} s⁻¹ and y(0)=${y0} m. Explicit Euler uses h=${R}/${2*lambda} s for ${N} steps. Find λh, the one-step multiplier, and the resulting numerical y. Classify the repeated-step behavior. The exact solution stays positive and decays at every finite positive time.`,
      [field("ratio","Dimensionless λh",`${R}/2`,"1"),field("multiplier","Euler multiplier",`${factor}/2`,"1"),field("value","Numerical value after the stated steps",`${y0}*(${factor}/2)^${N}`,"m"),choice("behavior","Repeated-step behavior",behavior,[
        {id:"monotone",label:"Positive monotone decay toward zero",feedback:R===1?"The multiplier lies strictly between zero and one. This preserves positivity while still having numerical error.":"Positive monotone decay requires a multiplier strictly between zero and one."},
        {id:"zero",label:"Reaches numerical zero in one step, then stays there",feedback:R===2?"The multiplier is zero. This scheme is stable here, but the exact positive solution never reaches zero at a finite time.":"One-step numerical extinction occurs only at λh=1, when the multiplier is zero."},
        {id:"alternating",label:"Alternates sign with decaying magnitude",feedback:R===3?"The multiplier lies between -1 and zero. Magnitudes decay, but positivity is lost.":"Sign-alternating decay requires -1 < 1-λh < 0."},
        {id:"boundary",label:"Alternates with constant nonzero magnitude; no asymptotic decay",feedback:R===4?"At λh=2 the multiplier is -1. This is the marginal boundary, not a decaying approximation.":"Constant alternating magnitude occurs at the multiplier -1."},
        {id:"growth",label:"Alternates sign with increasing magnitude",feedback:R===5?"The multiplier is below -1. A physically decaying model has a numerically growing path.":"Growing alternating magnitude needs a multiplier whose magnitude exceeds one."}
      ])],["Rewrite one Euler update as y_new=(1-λh)*y_old.","Raise that signed multiplier to the number of steps; negative factors alternate sign.","Check multiplier sign and magnitude separately. Stable decay and positivity are different requirements."],
      [`Here λh=${R}/2 and the multiplier is ${factor}/2. After ${N} steps y=${y0}*(${factor}/2)^${N} m.`,"Magnitude decays for 0<λh<2. Nonnegative updates additionally require λh≤1 for positive starting data. Equality λh=2 gives no decay, and larger steps grow numerically.","These statements concern the stated scalar model and algorithm. They are not a universal safe-step test for arbitrary force laws."],
      `Multiplier ${factor}/2; numerical value ${y0}*(${factor}/2)^${N} m; behavior ${behavior}.`);
  }
  if(variant==="oscillator-energy"){
    const omega=rng.integer(2,6),m=rng.integer(1,4),X=rng.integer(1,8),R=rng.integer(1,3),N=rng.integer(2,4),midpoint=rng.integer(0,1);
    const E=`${m}*${omega}^2*(${X}/10)^2/2`,factor=midpoint?`1+(${R}/2)^4/4`:`1+(${R}/2)^2`;
    return finish({omega,m,X,R,N,midpoint},`An undamped oscillator obeys x''=-ω²x with ω=${omega} s⁻¹, m=${m} kg, initial x=${X}/10 m, and initial v=0. Use ${midpoint?"explicit midpoint":"simultaneous explicit Euler"} with h=${R}/${2*omega} s. Calculate initial mechanical energy, its exact per-step numerical multiplication factor, and energy after one and ${N} equal steps. Here E=m(v²+ω²x²)/2 and arithmetic is exact.`,
      [field("initial","Initial mechanical energy",E,"J"),field("factor","Numerical energy multiplier",factor,"1"),field("first","Energy after one numerical step",`(${E})*(${factor})`,"J"),field("final","Energy after all stated steps",`(${E})*(${factor})^${N}`,"J"),choice("interpretation","Origin of the energy growth","algorithm",[
        {id:"algorithm",label:"The time-step method injects an energy error; the supplied undamped model has constant true energy",feedback:"The numerical update is not an exact rotation in the energy-scaled phase plane. Growth does not establish a physical energy source."},
        {id:"physical",label:"The spring creates physical energy, proving the conservation law is wrong",feedback:"An algebraic numerical trajectory is not independent measurement evidence against the supplied conservative model."},
        {id:"midpoint",label:"Every second-order method conserves oscillator energy exactly",feedback:"Explicit midpoint has energy factor 1+(ωh)^4/4. Higher order does not imply exact conservation."}
      ])],["Compute initial spring energy with k=m*ω².","Substitute each update into v_new²+ω²*x_new² and collect the old energy terms.","Explicit Euler gives 1+(ωh)²; explicit midpoint gives 1+(ωh)^4/4. Equal steps repeat the same positive factor."],
      [`Initially E=${E} J and ωh=${R}/2. Expanding the update gives energy factor (${factor}).`,`The first energy is (${E})*(${factor}) J; after ${N} steps it is (${E})*(${factor})^${N} J.`,"For this nonzero state and positive step, either factor exceeds one. An order statement describes finite-time error as steps shrink, not energy conservation at a fixed step."],
      `E0=${E} J; factor=${factor}; E_N=E0*factor^${N}.`);
  }
  if(variant==="oscillator-stability"){
    const omega=rng.integer(1,6),R=rng.integer(1,5),behavior=R<4?"bounded":R===4?"boundary":"growth";
    return finish({omega,R},`For the undamped model x''=-ω²x, take ω=${omega} s⁻¹ and velocity-first Euler step h=${R}/${2*omega} s. In the state coordinates (x,v/ω), its matrix is [[1-q²,q],[-q,1]], where q=ωh. Find q, the matrix trace, and determinant; classify repeated steps for generic nonzero initial data. No numerical rounding is assumed.`,
      [field("ratio","Dimensionless q",`${R}/2`,"1"),field("trace","Update matrix trace",`2-(${R}/2)^2`,"1"),field("determinant","Update matrix determinant","1","1"),choice("stability","Generic repeated-step behavior",behavior,[
        {id:"bounded",label:"Bounded for this undamped model because 0<q<2; physical energy need not be constant step by step",feedback:R<4?"The eigenvalues are distinct conjugates on the unit circle. Bounded oscillation is not exact physical energy conservation.":"The strict interior condition 0<q<2 is required; its endpoint cannot be included."},
        {id:"boundary",label:"At q=2, a repeated eigenvalue -1 generally gives growing amplitudes; special initial states are exceptions",feedback:R===4?"The matrix is not -I and has a repeated eigenvalue. Its Jordan part creates linear amplitude growth for generic states.":"The repeated -1 boundary occurs exactly when q=2."},
        {id:"growth",label:"For q>2, a generic component grows because one eigenvalue has magnitude greater than one",feedback:R>4?"The real reciprocal eigenvalues include one with magnitude above one. A special decaying eigendirection does not make the method generally stable.":"This exterior growth classification requires q>2."}
      ]),choice("energy","What follows from determinant one?","area",[
        {id:"area",label:"Area preservation in these coordinates, not exact conservation of physical mechanical energy",feedback:"A determinant controls oriented area scaling. It does not require every vector to keep its energy norm."},
        {id:"exact",label:"Every state has identical physical energy before and after the step",feedback:"Area preservation permits stretching in one direction and contraction in another. Physical energy needs a separate calculation."},
        {id:"damped",label:"The same undamped threshold automatically validates all drag coefficients",feedback:"Damping changes the update matrix. The stated bound was derived for b=0 and cannot be silently reused."}
      ])],["Multiply ω by the supplied step, then substitute q into the matrix.","The trace is 2-q² and determinant (1-q²)+q²=1.","Use the strict interval 0<q<2. At q=2, repeated unit-magnitude eigenvalues alone are not sufficient for bounded powers."],
      [`q=${R}/2, trace=2-(${R}/2)^2, and determinant=1.`,"For 0<q<2, distinct conjugate eigenvalues have modulus one and the repeated-step trajectory is bounded. At q=2 the nondiagonalizable repeated -1 case generally grows; above two one reciprocal eigenvalue grows.","These are generic statements. A zero equilibrium or a special eigendirection is not a general stability test. Mechanical energy can oscillate even in the bounded interval."],
      `q=${R}/2; trace=2-(${R}/2)^2; determinant=1; behavior ${behavior}.`);
  }
  if(variant==="endpoint"){
    const N=rng.integer(2,5),H=rng.integer(2,5),tail=rng.integer(1,H-1),T=N*H+tail,a=(rng.integer(0,1)?1:-1)*rng.integer(1,6),v0=rng.integer(-4,4),x0=rng.integer(-3,3),sum=N*H*H+tail*tail;
    const exact=`${x0}+(${v0})*${T}/10+(${a})*(${T}/10)^2/2`,bias=`(${a})*${sum}/200`;
    return finish({N,H,tail,T,a,v0,x0},`Integrate constant acceleration a=${a} m/s² from x0=${x0} m and v0=${v0} m/s to exactly T=${T}/10 s. The nominal step is h=${H}/10 s. Shorten only the last step to land at T. Report the number of steps, last width, final velocity, exact position, and positions from old-velocity explicit Euler and velocity-first Euler.`,
      [field("steps","Number of actual steps",String(N+1),"1"),field("last","Last actual step width",`${tail}/10`,"s"),field("velocity","Final velocity",`${v0}+(${a})*${T}/10`,"m/s"),field("exact","Exact final position",exact,"m"),field("explicit","Explicit Euler final position",`(${exact})-(${bias})`,"m"),field("semi","Velocity-first final position",`(${exact})+(${bias})`,"m"),choice("comparison","A fair endpoint comparison","same",[
        {id:"same",label:"Compare every method and analytic value at the same requested T, using actual step widths",feedback:"A method stopped early or overshooting T has changed the physical comparison time. The final increment must use its shorter actual width."},
        {id:"overshoot",label:"Take one full extra step and relabel its state with the requested T",feedback:"Changing a timestamp does not change the state that was computed at a different physical time."},
        {id:"discard",label:"Discard the remaining interval and call the preceding state the endpoint",feedback:"That compares an earlier state with the exact solution at T and mixes timing error with discretization error."}
      ])],["Subtract full nominal steps from T until the remainder is positive and smaller than h.","For each interval, exact position increment exceeds old-velocity Euler by a*(actual width)²/2.","Sum those squared widths. Velocity-first has the opposite bias; the velocity increments still sum to a*T."],
      [`There are ${N} full steps and one last step of ${tail}/10 s. Their squared widths sum to ${sum}/100 s².`,`Exact x=(${exact}) m. Explicit Euler differs by -(${bias}) m and velocity-first by +(${bias}) m. Both final velocities are ${v0}+(${a})*${T}/10 m/s.`,"Using T*h in place of the sum of squared actual widths would be wrong for this shortened last step."],
      `${N+1} steps; last ${tail}/10 s; x_exact=${exact} m; Euler bias=-(${bias}) m.`);
  }
  if(variant==="energy-audit"){
    const m=rng.integer(1,4),k=rng.integer(1,8),b=rng.integer(1,5),X=rng.integer(1,5),H=rng.integer(1,3);
    const x=`${X}/10`,h=`${H}/10`,v=rational(`-(${h})*${k}*(${x})/${m}`),E0=rational(`${k}*(${x})^2/2`),E1=rational(`(${E0})+${m}*(${v})^2/2`),D=rational(`${b}*(${v})^2*(${h})/2`);
    return finish({m,k,b,X,H},`For m=${m} kg, k=${k} N/m, and viscous coefficient b=${b} kg/s, start at x=${x} m and v=0. Perform one simultaneous explicit-Euler step of h=${h} s for m*x''=-k*x-b*x'. Estimate dissipated mechanical energy using the trapezoid of b*v² on that numerical step. Find E0, E1, D_trap, and residual R=E1+D_trap-E0.`,
      [field("initial","Initial mechanical energy",E0,"J"),field("final","Updated mechanical energy",E1,"J"),field("dissipation","Trapezoid dissipation estimate",D,"J"),field("residual","Numerical energy balance residual",`(${E1})+(${D})-(${E0})`,"J"),choice("claim","What does a positive residual establish?","audit",[
        {id:"audit",label:"The numerical state and approximate dissipation do not exactly satisfy the model's energy account",feedback:"The analytic model has dE/dt=-b*v². This discrete residual combines state-integration and dissipation-quadrature errors; it is not a measured physical source."},
        {id:"source",label:"A newly observed physical source supplies exactly the residual",feedback:"All inputs and outputs here are synthetic calculations. A residual in an approximation is not an independent measurement of a source."},
        {id:"exact",label:"The trapezoid estimate is exact heat released to the surroundings",feedback:"It integrates approximate squared velocities and is itself approximate. Mechanical energy transfer into an ideal drag term is not a measured thermal partition."}
      ])],["At v0=0, old drag force is zero. Explicit Euler leaves x unchanged for the first step and changes v by -h*k*x/m.","Compute both endpoint energies from their own positions and velocities.","The power samples are 0 and b*v1², so D_trap=h*b*v1²/2. Add D_trap before subtracting E0."],
      [`The first position remains ${x} m and first velocity is (${v}) m/s. E0=(${E0}) J and E1=(${E1}) J.`,`D_trap=(${D}) J. R=E1+D_trap-E0 is positive because both the new kinetic energy and this dissipation estimate are positive.`,"The true damped model cannot gain total accounted energy. Refining state integration and the dissipation integral should be checked together; the residual is an audit, not a measurement of heat."],
      `E0=${E0} J; E1=${E1} J; D=${D} J; R=E1+D-E0.`);
  }
  const reference=rng.integer(0,1)?rng.integer(2,10):0,difference=(rng.integer(0,1)?1:-1)*rng.integer(1,5),U=rng.integer(1,5),B=Math.abs(difference)+rng.integer(0,3),scale=rng.integer(1,4);
  return finish({reference,difference,U,B,scale},`At one endpoint, a synthetic exact-model reference is ${reference} m and its numerical approximation is ${reference}+(${difference})/1000 m. A declared comparison scale is ${scale} m. Separately, justified output bounds for this calculation are measurement-input contribution ≤${U}/1000 m and discretization contribution ≤${B}/1000 m. No distribution, independence assumption, or model-discrepancy bound is supplied. Find the absolute numerical error, error divided by the declared scale, ${reference?"relative error divided by the magnitude of the reference, ":""}and worst-case sum of the two supplied bounds. Decide what can be claimed.`,
    [field("absolute","Absolute numerical error",`${Math.abs(difference)}/1000`,"m"),field("scaled","Error divided by declared comparison scale",`${Math.abs(difference)}/${1000*scale}`,"1"),...(reference?[field("relative","Relative error divided by reference magnitude",`${Math.abs(difference)}/${1000*reference}`,"1")]:[]),field("bound","Sum of the two supplied output-error bounds",`${U+B}/1000`,"m"),choice("relative-status","Reference-relative error",reference?"defined":"undefined",[
      {id:"defined",label:"Defined because the supplied reference is nonzero",feedback:reference?"Divide the absolute difference by the absolute reference. This differs from scaling by an independently declared comparison size.":"The reference is exactly zero; division by its magnitude is undefined."},
      {id:"undefined",label:"Undefined at this zero reference; report absolute or declared-scale error instead",feedback:reference?"This reference is nonzero, so the usual reference-relative error is defined.":"A zero denominator does not become a small nonzero denominator just to produce a percentage."}
    ]),choice("scope","Meaning of the combined bound","partial",[
      {id:"partial",label:"A worst-case bound for the two stated contributions; total physical error remains unbounded by the supplied evidence",feedback:"Adding magnitudes is conservative without a dependence model. An unbounded model discrepancy prevents calling this a certified total physical-error bound."},
      {id:"rss",label:"A complete 95% physical-error bound from the square root of the squared bounds",feedback:"Neither a probability distribution nor independent random errors nor a bound on model discrepancy has been supplied."},
      {id:"digits",label:"Displaying more digits makes the omitted model discrepancy vanish",feedback:"Output precision does not validate a force law or create missing experimental evidence."}
    ])],["Subtract approximation and reference, then take the absolute value.","Use the specified denominator for each normalization. A zero reference makes its usual relative error undefined.","Without a statistical model, add worst-case magnitude bounds. State explicitly which contributions are still not bounded."],
    [`The absolute difference is ${Math.abs(difference)}/1000 m and its declared-scale value is ${Math.abs(difference)}/${1000*scale}.`,reference?`Reference-relative error is ${Math.abs(difference)}/${1000*reference}.`:"Reference-relative error is undefined because the reference is zero; the declared-scale value is a different stated normalization.",`The two justified contribution bounds sum to ${U+B}/1000 m. This excludes unknown model discrepancy and is not a confidence interval or complete validation.`],
    `Absolute error ${Math.abs(difference)}/1000 m; scaled ${Math.abs(difference)}/${1000*scale}; partial bound ${U+B}/1000 m.`);
}
