import { questionSchema, type AnswerField } from "../contracts";
import { randomFrom } from "../random";
import { pendulumModel } from "../phs-232-oscillator-energy";
import { phs232Approximate, phs232Choice, phs232Exact, phs232Pi, phs232Rational } from "./phs-232-fields";

export const phs232OscillatorModelFamilyIds = ["phs232-oscillator-model"] as const;
export const phs232OscillatorModelVariants = ["simple-pendulum", "physical-pendulum", "torsion", "potential-curvature", "unstable-equilibrium", "small-angle-error"] as const;

export function phs232OscillatorModelQuestion(familyId: string, variant: string, seed: string, id: string) {
  if (familyId !== "phs232-oscillator-model" || !(phs232OscillatorModelVariants as readonly string[]).includes(variant)) throw new Error("Unknown PHS 232 oscillator model family or variant.");
  const rng = randomFrom(`${familyId}:${variant}:${seed}`);
  const massNumerator = rng.integer(1, 8), lengthNumerator = rng.integer(1, 10), gravity = rng.integer(5, 15), omega = rng.integer(1, 8), scale = rng.integer(1, 6);
  const shape = rng.integer(0, 1), beta = rng.integer(1, 5), offset = rng.integer(-10, 10), caseIndex = rng.integer(0, 3);
  const angleDegrees = [5, 10, 15, 30, 60, 90, 120][rng.integer(0, 6)], tolerance = [.5, 1, 2, 5][rng.integer(0, 3)];
  const parameters = { massNumerator, lengthNumerator, gravity, omega, scale, shape, beta, offset, caseIndex, angleDegrees, tolerance };
  const choice = (id: string, label: string, correct: string, options: [string, string, string][]) => phs232Choice(id, label, correct, rng.shuffle(options));
  const finish = (prompt: string, fields: AnswerField[], hints: string[], explanation: string[], answerSummary: string) => questionSchema.parse({
    id, familyId, familyVersion: 1, courseId: "phs-232", objectiveId: "m01-l02", category: "application", critical: true, parameters, prompt, fields, hints, explanation, answerSummary,
  });
  const m = `${massNumerator}/4`, length = `${lengthNumerator}/5`;
  if (variant === "simple-pendulum") {
    const omegaSquared = `${5 * gravity}/${lengthNumerator}`, period = 2 * Math.PI * Math.sqrt(lengthNumerator / (5 * gravity));
    return finish(`A point mass m=${m} kg is fixed to a massless rigid rod of length L=${length} m, pivoted without friction in uniform g=${gravity} m/s². Angle theta is measured in radians from downward vertical. The rod can push or pull. Determine the pivot inertia, restoring torque coefficient in the linearized equation I*theta''=-kappa*theta, local natural angular frequency and small-angle period. Identify the approximation; these are local linear results, not an exact period for every amplitude.`,
      [phs232Rational("inertia", "Pivot inertia", `${massNumerator * lengthNumerator * lengthNumerator}/100`, "kg·m²"), phs232Rational("curvature", "Linear restoring torque coefficient", `${massNumerator * gravity * lengthNumerator}/20`, "N·m/rad"), phs232Exact("omega", "Local natural angular frequency", `sqrt(${omegaSquared})`, "rad/s"), phs232Approximate("period", "Small-angle period", period, "s"), choice("approximation", "Required angular approximation", "sine", [["sine", "Replace sin(theta) by theta in radians", "The exact gravitational torque is -mgL sin(theta). Its first derivative at zero supplies the linear restoring coefficient."], ["degrees", "Replace sin(theta) by its numerical angle in degrees", "The unit derivative of sine at zero uses radians. A degree argument requires the pi/180 conversion."], ["exact", "No approximation: gravity produces exactly linear torque", "The exact sine torque is nonlinear. A large-amplitude period generally exceeds this local period."]])],
      ["Use I=mL² for a point mass at fixed distance L from the pivot.", "The exact torque is -mgL sin(theta). Linearization about downward vertical gives kappa=mgL.", "Divide kappa by I before taking a square root. The mass cancels, and T0=2*pi*sqrt(L/g)."],
      [`I=mL²=${massNumerator * lengthNumerator * lengthNumerator}/100 kg·m² and kappa=mgL=${massNumerator * gravity * lengthNumerator}/20 N·m/rad.`, `omega0²=kappa/I=g/L=${omegaSquared} s⁻². Thus omega0=sqrt(${omegaSquared}) rad/s and T0=${period.toFixed(9)} s.`, "Radians are dimensionless in dimensional analysis; the /rad label identifies the angular derivative. The mass cancellation follows from inertial and gravitational factors together, not from omitting either one.", "The small-angle replacement is local. A rigid rod permits both tension and compression; a flexible string has an additional tautness constraint."],
      `I=${massNumerator * lengthNumerator * lengthNumerator}/100 kg·m²; kappa=${massNumerator * gravity * lengthNumerator}/20 N·m/rad; omega0=sqrt(${omegaSquared}) rad/s; T0≈${period.toFixed(9)} s; sin(theta)≈theta in radians.`);
  }
  if (variant === "physical-pendulum") {
    const inertia = shape ? `${3 * massNumerator * lengthNumerator * lengthNumerator}/200` : `${massNumerator * lengthNumerator * lengthNumerator}/300`;
    const d = shape ? length : `${lengthNumerator}/10`, omegaSquared = shape ? `${10 * gravity}/${3 * lengthNumerator}` : `${15 * gravity}/${2 * lengthNumerator}`;
    const squared = shape ? 10 * gravity / (3 * lengthNumerator) : 15 * gravity / (2 * lengthNumerator), period = 2 * Math.PI / Math.sqrt(squared);
    return finish(`A rigid ${shape ? `uniform disk of radius R=${length} m swings in its own vertical plane about a fixed frictionless pivot at its rim, with axis perpendicular to the disk. Its center-of-mass inertia about a parallel axis is I_cm=mR²/2` : `uniform slender rod of length L=${length} m swings in a vertical plane about a fixed frictionless pivot at one end. Its center-of-mass inertia about a parallel transverse axis is I_cm=mL²/12`}. Its mass is m=${m} kg and g=${gravity} m/s². The center of mass is below the pivot at stable equilibrium. Find the pivot-to-center distance, pivot inertia, local angular frequency and small-angle period. Ignore drag and pivot friction.`,
      [phs232Rational("distance", "Pivot-to-center distance", d, "m"), phs232Rational("inertia", "Moment of inertia about the pivot", inertia, "kg·m²"), phs232Exact("omega", "Local natural angular frequency", `sqrt(${omegaSquared})`, "rad/s"), phs232Approximate("period", "Small-angle period", period, "s")],
      ["Gravitational torque about the pivot is -mgd sin(theta), with d measured to the center of mass.", "Apply the parallel-axis theorem I_p=I_cm+m*d². The center-of-mass inertia alone is not the pivot inertia.", "Linearizing gives I_p*theta''=-mgd*theta, so omega0²=mgd/I_p and T0=2*pi/omega0."],
      [`The center distance is d=${d} m. The parallel-axis theorem gives I_p=${shape ? "mR²/2+mR²=3mR²/2" : "mL²/12+m(L/2)²=mL²/3"}=${inertia} kg·m².`, `omega0²=mgd/I_p=${omegaSquared} s⁻², so omega0=sqrt(${omegaSquared}) rad/s and T0≈${period.toFixed(9)} s.`, "Using m*d² alone would collapse the extended body into a point mass and omit its rotational inertia about its center. Using I_cm alone would use the wrong axis.", "This frequency describes small oscillations about the downward stable equilibrium. Finite-angle motion retains sin(theta); the upward equilibrium is unstable."],
      `d=${d} m; I_p=${inertia} kg·m²; omega0=sqrt(${omegaSquared}) rad/s; T0≈${period.toFixed(9)} s.`);
  }
  if (variant === "torsion") return finish(`A rotor has fixed-axis inertia I=${massNumerator}/20 kg·m². An ideal torsion element supplies net torque tau=-kappa*theta with kappa=${massNumerator * omega * omega}/20 N·m/rad. The angular displacement theta is in radians from equilibrium; damping and gravity torque about this axis are absent. Release it from rest at theta0=${scale}/10 rad within the stated linear range. Find its angular frequency, period, oscillation energy and maximum magnitude of angular velocity.`,
    [phs232Rational("omega", "Natural angular frequency", String(omega), "rad/s"), phs232Pi("period", "Natural period", `2*pi/${omega}`, "s"), phs232Rational("energy", "Oscillation energy", `${massNumerator * omega * omega * scale * scale}/4000`, "J"), phs232Rational("speed", "Maximum angular speed", `${omega * scale}/10`, "rad/s")],
    ["The rotational equation is I*theta''=-kappa*theta, so omega0²=kappa/I.", "Use U=kappa*theta²/2 and rotational K=I*theta_dot²/2, with the angular displacement in radians.", "At release all oscillation energy is potential; at equilibrium it is kinetic. The angular-speed amplitude is omega0*theta0."],
    [`omega0=sqrt(kappa/I)=${omega} rad/s; T0=2*pi/${omega} s.`, `E=kappa*theta0²/2=${massNumerator * omega * omega * scale * scale}/4000 J, measured above equilibrium.`, `|theta_dot|_max=sqrt(2E/I)=${omega * scale}/10 rad/s. Its unit matches angular frequency, but it measures the rotor's instantaneous angular-speed scale, not the rate of oscillation phase.`, "This torsion element is assumed linear over the supplied range. A real element's elastic limit and nonlinearity need separate evidence; this exercise does not certify a hardware operating range."],
    `omega0=${omega} rad/s; T0=2*pi/${omega} s; E=${massNumerator * omega * omega * scale * scale}/4000 J; |theta_dot|_max=${omega * scale}/10 rad/s.`);
  if (variant === "potential-curvature") {
    const k = `${massNumerator * omega * omega}/4`, q = `${scale}/10`, force = `-(${k})*(${q})-4*${beta}*(${q})^3`;
    return finish(`A one-dimensional mass m=${m} kg has potential U(x)=(${offset} J)+(k/2)*(x-b)²+beta*(x-b)^4, where b=${lengthNumerator}/10 m, k=${k} N/m and beta=${beta} J/m⁴. No other forces act. Find the equilibrium coordinate, potential curvature there, local natural angular frequency and exact force at x=b+${q} m. Decide whether the local harmonic model is exact over arbitrary displacement.`,
      [phs232Rational("equilibrium", "Equilibrium coordinate", `${lengthNumerator}/10`, "m"), phs232Rational("curvature", "Potential curvature at equilibrium", k, "N/m"), phs232Rational("omega", "Local natural angular frequency", String(omega), "rad/s"), phs232Rational("force", "Signed force at the requested coordinate", force, "N"), choice("range", "Scope of the harmonic model", "local", [["local", "Local approximation; the cubic force matters away from equilibrium", "The potential's quartic term produces a cubic force. Positive curvature gives the local linear coefficient but does not remove that nonlinear term."], ["global", "Exact at every displacement because the curvature is positive", "Positive curvature establishes local restoring behavior; it does not imply a globally quadratic potential."], ["offset", "Changing the constant energy offset changes the force and frequency", "A constant energy offset has zero derivative and does not affect force or curvature."]])],
      ["Differentiate: F=-k*(x-b)-4*beta*(x-b)^3. Equilibrium requires F=0.", "Because k and beta are positive, the only real root is x=b. There U''=k>0.", "For small q=x-b, neglect the cubic force compared with k*q: omega0=sqrt(k/m). Retain the cubic term when the exact force is requested."],
      [`F=-(x-b)[k+4*beta*(x-b)²]. The bracket is strictly positive, so the unique equilibrium is x=b=${lengthNumerator}/10 m.`, `U''=k+12*beta*(x-b)²; at b this is ${k} N/m. The local natural angular frequency is sqrt(k/m)=${omega} rad/s.`, `At q=${q} m the exact force is ${force} N. The cubic force relative to the linear term has magnitude 4*beta*q²/k, providing a scale test for neglecting it.`, `The constant ${offset} J sets the energy reference only. The quartic potential confines motion but generally makes its finite-amplitude period amplitude-dependent.`],
      `x_eq=${lengthNumerator}/10 m; curvature=${k} N/m; omega0=${omega} rad/s; F=${force} N; harmonic description is local.`);
  }
  if (variant === "unstable-equilibrium") {
    const descriptions = ["U(q)=U0-k*q²/2 with k>0 in N/m", "U(q)=U0+beta*q⁴ with beta>0 in J/m⁴", "U(q)=U0-beta*q⁴ with beta>0 in J/m⁴", "U(q)=U0 for every q"];
    const curvature = caseIndex === 0 ? "negative" : "zero", character = ["unstable", "quartic-minimum", "unstable", "neutral"][caseIndex];
    return finish(`Near q=0 a one-dimensional positive mass has ${descriptions[caseIndex]}. Assume no damping or driving. Classify the curvature at q=0 and the potential's behavior under a small displacement released from rest. Does the potential supply a positive nonzero local harmonic frequency? For a constant potential, distinguish neutral positional equilibrium from a restoring oscillator; a nonzero initial velocity would drift.`,
      [choice("curvature", "Curvature at q = 0", curvature, [["positive", "Positive", "Positive curvature requires a positive quadratic term; inspect the supplied potential rather than the sign of U itself."], ["negative", "Negative", "The negative quadratic term gives U''=-k<0 and a locally destabilizing force."], ["zero", "Zero", "A quartic term has zero second derivative at zero, and a constant potential has zero derivatives everywhere."]]), choice("character", "Behavior around the equilibrium", character, [["unstable", "A potential maximum: displacement is driven farther away", "The force points away from zero for the negative quadratic or negative quartic potential. A vanishing curvature does not prevent instability."], ["quartic-minimum", "A quartic minimum: restoring motion, but no nonzero linear frequency", "For +beta*q⁴ the force -4*beta*q³ restores a displaced mass. Its frequency depends on amplitude; the linearized equation alone loses this restoring term."], ["neutral", "Flat potential: no force after a displacement", "With an exactly constant potential a displaced mass released from rest stays there. A small nonzero velocity causes drift, so this is not an oscillation."]]), choice("frequency", "Positive nonzero local harmonic frequency", "no", [["yes", "Yes", "A positive nonzero harmonic frequency requires positive curvature divided by positive mass. None of the supplied negative or zero curvatures meets that condition."], ["no", "No", "For negative curvature the linear response grows or decays exponentially. For zero curvature the linear equation has zero restoring coefficient; higher terms or the complete potential determine the behavior."]])],
      ["Equilibria satisfy U'=0, but their character is determined by the nearby potential, not by the value U0.", "Use F=-U'. If U''=0, inspect the quartic term or the stated complete constant potential before classifying.", "Do not turn a negative omega² into a real oscillation frequency by dropping its sign. A zero quadratic term also does not justify a positive harmonic frequency."],
      [caseIndex === 0 ? "U''(0)=-k<0 and m*q''=+k*q. Its linear solutions are combinations of exp(±sqrt(k/m)*t), not bounded sinusoids." : caseIndex === 1 ? "U''(0)=0, but U(q)>U(0) for q≠0 and F=-4*beta*q³ restores toward zero. Nonzero finite-energy motion is bounded in this quartic potential, with an amplitude-dependent period." : caseIndex === 2 ? "U''(0)=0, but U(q)<U(0) for q≠0 and F=+4*beta*q³ points away from zero. The equilibrium is unstable despite zero curvature." : "U''(0)=0 and F=0 everywhere. A displaced mass released from rest stays at the new position; a nonzero velocity produces uniform drift.", "The expression omega0²=U''(0)/m supplies a positive harmonic frequency only when the numerator is positive. Zero curvature alone is inconclusive: the positive quartic, negative quartic and flat examples have different behavior.", "An arbitrary additive constant U0 does not change any force, derivative or stability classification."],
      `Curvature ${curvature}; behavior ${character}; no positive nonzero local harmonic frequency.`);
  }
  const model = pendulumModel({ mass: 1, length: 1, gravity: 10, amplitudeDegrees: angleDegrees });
  const forceError = model.forceDifferenceRelativeToLinearPercent!, periodError = model.periodIncreasePercent!;
  const passes = forceError <= tolerance ? periodError <= tolerance ? "both" : "force" : periodError <= tolerance ? "period" : "neither";
  return finish(`A frictionless point-mass pendulum on a massless rigid rod is released from rest at ${angleDegrees}° from downward vertical. Compare the exact sine torque with its linear approximation at release. Define force discrepancy relative to the linear magnitude as 100*(theta0-sin(theta0))/theta0, with theta0 in radians. The independently converged nonlinear-to-small-angle period ratio for this amplitude is ${((model.referencePeriod!) / model.linearPeriod).toFixed(12)}. Calculate the force discrepancy and the period increase (both in percent), then decide which meets a ${tolerance}% tolerance. Treat the supplied period ratio as sufficiently accurate for this tolerance. Neither quantity is a numerical-integration error.`,
    [phs232Approximate("force-error", "Force discrepancy relative to linear magnitude", forceError, "%", .00001), phs232Approximate("period-error", "Period increase relative to small-angle period", periodError, "%", .00001), choice("passes", "Quantities within the stated tolerance", passes, [["both", "Both force discrepancy and period increase", "Apply the threshold to each independently; the two percentages are different physical measures."], ["force", "Only force discrepancy", "Compare both calculated percentages with the threshold; do not infer period error by equating it to force error."], ["period", "Only period increase", "A period can meet a tolerance even when the release-force approximation does not. The period depends on the whole trajectory."], ["neither", "Neither", "Reject each approximation only if its own specified discrepancy exceeds the tolerance."]])],
    ["Convert degrees to radians before evaluating both theta0 and its sine in the ratio.", "The force percentage uses the linear force as denominator. The period percentage is 100*(supplied ratio-1).", "Compare each result with the same stated tolerance, retaining enough digits to avoid changing the decision by rounding."],
    [`theta0=${angleDegrees}*pi/180 rad. The force discrepancy is 100*(1-sin(theta0)/theta0)≈${forceError.toFixed(9)}%.`, `The period increase is 100*(${((model.referencePeriod!) / model.linearPeriod).toFixed(12)}-1)≈${periodError.toFixed(9)}%.`, `For tolerance ${tolerance}%, the result is ${passes}. The maximum release-force discrepancy and full-cycle period increase need not have the same percentage.`, "These compare physical models. Step-size convergence measures numerical error within a chosen model and must be assessed separately. Using the exact sine force as denominator would define a different force percentage."],
    `Force discrepancy≈${forceError.toFixed(9)}%; period increase≈${periodError.toFixed(9)}%; within tolerance: ${passes}.`);
}
