import { questionSchema, type AnswerField } from "../contracts";
import { randomFrom } from "../random";
import { phs232Approximate, phs232Choice, phs232Exact, phs232Pi, phs232Rational } from "./phs-232-fields";

export const phs232DrivenResponseFamilyIds = ["phs232-driven-response"] as const;
export const phs232DrivenResponseVariants = ["amplitude", "phase", "static-limit", "high-frequency-limit", "transient-condition", "undamped-resonance"] as const;

export function phs232DrivenResponseQuestion(familyId: string, variant: string, seed: string, id: string) {
  if (familyId !== "phs232-driven-response" || !(phs232DrivenResponseVariants as readonly string[]).includes(variant)) throw Error("Unknown PHS 232 driven-response family or variant.");
  const rng = randomFrom(`${familyId}:${variant}:${seed}`), massNumerator = rng.integer(1, 6), scale = rng.integer(1, 4), a = rng.integer(1, 8), ratioNumerator = rng.integer(1, 4), mode = rng.integer(0, 2), sign = rng.integer(0, 1) ? 1 : -1, quarter = rng.integer(1, 4);
  const parameters = { massNumerator, scale, a, ratioNumerator, mode, sign, quarter }, m = `${massNumerator}/2`, k = 2 * massNumerator * scale * scale, b = `${massNumerator * scale}/2`, force = `${a}/10`, omega = ratioNumerator * scale;
  const re = 4 - ratioNumerator ** 2, d2 = re * re + ratioNumerator ** 2, A = `${a}/(${5 * massNumerator * scale * scale}*sqrt(${d2}))`;
  const C = `${a * re}/${5 * massNumerator * scale * scale * d2}`, D = `${a * ratioNumerator}/${5 * massNumerator * scale * scale * d2}`;
  const choice = (id: string, label: string, correct: string, options: [string, string, string][]) => phs232Choice(id, label, correct, rng.shuffle(options));
  const finish = (prompt: string, fields: AnswerField[], hints: string[], explanation: string[], answerSummary: string) => questionSchema.parse({ id, familyId, familyVersion: 1, courseId: "phs-232", objectiveId: "m01-l04", category: "application", critical: true, parameters, prompt, fields, hints, explanation, answerSummary });
  const setup = `A linear oscillator obeys m*x''+b*x'+k*x=F0*cos(Omega*t), with m=${m} kg, b=${b} kg/s, k=${k} N/m and fixed force amplitude F0=${force} N. At Omega=${omega} rad/s, consider its periodic particular response x=A*cos(Omega*t-delta), A≥0 and 0≤delta≤pi.`;
  if (variant === "amplitude") return finish(`${setup} Find the real and imaginary dynamic-stiffness components, displacement amplitude and velocity amplitude. At a positive displacement maximum of this periodic response, what is its instantaneous velocity? Amplitude is a nonnegative envelope value, not the position at an arbitrary time.`,
    [phs232Rational("real", "Real dynamic stiffness k minus m Omega squared", `${massNumerator * scale * scale * re}/2`, "N/m"), phs232Rational("imaginary", "Imaginary dynamic stiffness b Omega", `${massNumerator * scale * scale * ratioNumerator}/2`, "N/m"), phs232Exact("amplitude", "Displacement amplitude", A, "m"), phs232Exact("speed-amplitude", "Velocity amplitude", `${omega}*(${A})`, "m/s"), phs232Rational("peak-velocity", "Signed velocity at a displacement maximum", "0", "m/s")],
    ["Two derivatives of the cosine contribute -Omega², while damping couples the sine and cosine coefficients. Keep the signed real component k-m*Omega².", "The magnitude of the dynamic stiffness is sqrt((k-m*Omega²)²+(b*Omega)²), in N/m. Divide the force amplitude by it.", "Differentiating A*cos(Omega*t-delta) gives velocity amplitude Omega*A. At a displacement maximum the sine is zero, so this instantaneous velocity is not the velocity amplitude."],
    [`omega0=${2 * scale} rad/s. The signed real component is ${massNumerator * scale * scale * re}/2 N/m and the imaginary component is ${massNumerator * scale * scale * ratioNumerator}/2 N/m.`, `Their magnitude is (${massNumerator * scale * scale}/2)*sqrt(${d2}) N/m, so A=${A} m. A negative real component does not make A negative.`, `The velocity amplitude is ${omega}*(${A}) m/s, obtained by differentiation. The actual velocity at a positive displacement maximum is 0 m/s.`, "These describe the periodic particular solution. An arbitrary startup response includes an additional homogeneous term fixed by both initial coordinates."], `A=${A} m; velocity amplitude=${omega}*(${A}) m/s; velocity at displacement maximum=0.`);
  if (variant === "phase") {
    const lag = Math.atan2(ratioNumerator, re), band = ratioNumerator < 2 ? "below" : ratioNumerator === 2 ? "quarter" : "above";
    return finish(`${setup} Write that response as C*cos(Omega*t)+D*sin(Omega*t). Find signed C and D, the lag delta in radians, and the signed initial velocity of this periodic particular response. Identify its lag interval. Use the supplied cosine forcing convention.`,
      [phs232Rational("cosine", "Cosine coefficient C", C, "m"), phs232Rational("sine", "Sine coefficient D", D, "m"), phs232Approximate("lag", "Displacement phase lag delta", lag, "rad"), phs232Rational("initial-velocity", "Particular velocity at t equals zero", `${omega}*(${D})`, "m/s"), choice("interval", "Lag interval", band, [["below", "Between 0 and pi/2", "Below the natural frequency, both dynamic-stiffness components are positive and displacement lags by less than a quarter-cycle."], ["quarter", "Exactly pi/2", "At the natural frequency k-m*Omega² vanishes while b*Omega remains positive."], ["above", "Between pi/2 and pi", "Above the natural frequency the real component is negative. atan of a ratio alone loses this quadrant."]])],
      ["Expanding cos(Omega*t-delta) gives C=A*cos(delta) and D=A*sin(delta); the sine coefficient is positive for this lag convention.", "Substitution gives (k-m*Omega²)C+b*Omega*D=F0 and (k-m*Omega²)D-b*Omega*C=0. Solve both equations.", "Use atan2(b*Omega,k-m*Omega²). Then differentiate C*cos(Omega*t)+D*sin(Omega*t): its initial velocity is Omega*D."],
      [`The two coefficient equations give C=${C} m and D=${D} m. Their signs are tied to the explicitly specified cosine reference.`, `delta=atan2(${ratioNumerator},${re})≈${lag.toFixed(9)} rad. It lies ${band === "below" ? "below pi/2" : band === "quarter" ? "at pi/2" : "above pi/2"}.`, `The particular initial velocity is Omega*D=${omega}*(${D}) m/s. Setting it to zero would generally add a startup transient.`, "Check C²+D²=A² and reconstruct the signed cosine/sine coefficients from the phase. A wrong quadrant can preserve a tangent while reversing the displacement."], `C=${C} m; D=${D} m; delta≈${lag.toFixed(9)} rad; v_part(0)=${omega}*(${D}) m/s.`);
  }
  if (variant === "static-limit") return finish(`Use m=${m} kg, b=${b} kg/s, k=${k} N/m and F0=${force} N in m*x''+b*x'+k*x=F0*cos(Omega*t). Set Omega=0 exactly, and start at x0=v0=0. Find the constant particular displacement, initial acceleration, and long-time dissipated power. Does this constant input have a finite forcing-cycle duration, and does the initial state already equal the static particular state?`,
    [phs232Rational("displacement", "Constant particular displacement", `${a}/${10 * k}`, "m"), phs232Rational("acceleration", "Initial acceleration", `${a}/${5 * massNumerator}`, "m/s²"), phs232Rational("power", "Long-time dissipated power", "0", "W"), choice("cycle", "Finite forcing-cycle duration", "none", [["none", "No: the input is constant", "At Omega=0, 2*pi/Omega is not a finite period. A constant signal has no least positive period."], ["natural", "Use the natural period as its forcing cycle", "The natural period belongs to the unforced reference oscillator and does not turn a constant force into a periodic drive."]]), choice("initial", "Does the initial state equal the static particular state?", "no", [["no", "No: the system starts away from F0/k", "The positive force shifts the final static displacement. The specified zero state initially accelerates."], ["yes", "Yes: zero drive frequency prevents motion", "A constant nonzero force can accelerate a mass. Zero drive frequency is not zero force."]])],
    ["cos(0*t)=1. A constant particular state has zero velocity and acceleration, so k*x_part=F0.", "At the supplied zero initial state, spring and damping forces are initially zero. Newton's law then gives acceleration=F0/m.", "Because b>0, the homogeneous correction decays and v tends to zero. Dissipated power b*v² then tends to zero, although energy was dissipated during startup."],
    [`x_part=F0/k=${a}/${10 * k} m. This is a displacement from the original spring equilibrium, not an oscillation amplitude about the new static state.`, `At t=0, acceleration=F0/m=${a}/${5 * massNumerator} m/s². The mass begins moving even though the input force is constant.`, "Positive damping makes the homogeneous correction decay. Long-time velocity and dissipated power are zero; neither is zero throughout the startup.", "No finite forcing-cycle duration exists at Omega=0. The natural reference period still exists, but it is a different quantity."], `x_part=${a}/${10 * k} m; initial acceleration=${a}/${5 * massNumerator} m/s²; long-time power=0 W; no finite forcing cycle; initial state differs.`);
  if (variant === "high-frequency-limit") return finish(`For the same viscous model with m=${m} kg, b=${b} kg/s, k=${k} N/m and fixed F0=${force} N, take Omega much larger than both sqrt(k/m) and b/m. Use leading asymptotic terms, not exact finite-frequency ratios. When Omega doubles, find the displacement-amplitude ratio and velocity-amplitude ratio. Also find the limiting acceleration amplitude as Omega tends to infinity and the limiting displacement lag.`,
    [phs232Rational("displacement-ratio", "Leading A at 2 Omega divided by A at Omega", "1/4"), phs232Rational("velocity-ratio", "Leading velocity-amplitude ratio", "1/2"), phs232Rational("acceleration-limit", "Limiting acceleration amplitude", `${a}/${5 * massNumerator}`, "m/s²"), phs232Pi("lag", "Limiting displacement lag", "pi", "rad")],
    ["At sufficiently large Omega, the dynamic-stiffness magnitude is dominated by m*Omega², so A is asymptotic to F0/(m*Omega²).", "Velocity amplitude is Omega*A, while acceleration amplitude is Omega²*A. Apply the extra frequency factor before comparing ratios.", "The real component is large and negative while the positive imaginary component grows only linearly. Its phase approaches pi from below."],
    ["A(2*Omega)/A(Omega) approaches 1/4. This is an asymptotic ratio, not an exact identity at every frequency.", "Velocity amplitude is asymptotic to F0/(m*Omega), giving ratio 1/2. Acceleration amplitude tends to F0/m, not zero.", `F0/m=${a}/${5 * massNumerator} m/s². The high-frequency displacement lag tends to pi rad: acceleration is then nearly in phase with the drive.`, "The result assumes a fixed force amplitude and constant linear parameters. Prescribing base displacement or allowing force amplitude to change with frequency is a different experiment."], `Asymptotic displacement ratio=1/4; velocity ratio=1/2; acceleration limit=${a}/${5 * massNumerator} m/s²; lag tends to pi rad.`);
  if (variant === "transient-condition") {
    const undamped = mode === 2, frequency = undamped ? scale : 2 * scale, particularC = undamped ? `${a}/${15 * massNumerator * scale * scale}` : "0", particularV = undamped ? "0" : `${a}/${5 * massNumerator * scale}`;
    const x0 = mode === 1 ? "0" : `${sign * a}/100`, v0 = mode === 1 ? particularV : "0", hx = `(${x0})-(${particularC})`, hv = `(${v0})-(${particularV})`;
    const behavior = mode === 1 ? "absent" : undamped ? "persists" : "decays";
    return finish(`An oscillator has m=${m} kg, k=${k} N/m, b=${undamped ? "0" : b} kg/s and F(t)=(${force} N)*cos(${frequency}t), with time in seconds. Initially x0=${x0} m and v0=${v0} m/s. Find the position and velocity at zero of a bounded sinusoidal particular response. Subtract them from the supplied initial state to obtain the homogeneous correction's initial coordinates. Decide whether that correction is absent, decays, or persists.`,
      [phs232Rational("particular-position", "Particular position at zero", particularC, "m"), phs232Rational("particular-velocity", "Particular velocity at zero", particularV, "m/s"), phs232Rational("correction-position", "Homogeneous correction position at zero", hx, "m"), phs232Rational("correction-velocity", "Homogeneous correction velocity at zero", hv, "m/s"), choice("behavior", "Homogeneous correction", behavior, [["absent", "Absent: both initial corrections are zero", "A unique linear initial-value solution remains exactly on the particular response only when both initial coordinates match."], ["decays", "Present and decaying", "Positive viscous damping makes the homogeneous modes decay, but does not erase them at the instant forcing begins."], ["persists", "Present and nondecaying", "At zero damping away from resonance, the bounded particular response exists while the free harmonic correction persists."]])],
      ["Find a bounded particular response before applying initial conditions. Its initial position is its cosine coefficient; its initial velocity is Omega times its sine coefficient.", undamped ? "Here the force frequency differs from omega0 and b=0. The particular solution is [F0/(k-m*Omega²)]*cos(Omega*t)." : "Here Omega=omega0 and b>0. The particular displacement is [F0/(b*Omega)]*sin(Omega*t), so its initial position is zero but its initial velocity is F0/b.", "The total state is particular plus homogeneous. Subtract both coordinates separately, then inspect the damping coefficient and whether both differences vanish."],
      [`x_part(0)=${particularC} m and v_part(0)=${particularV} m/s.`, `The homogeneous correction starts at x_h(0)=${hx} m and v_h(0)=${hv} m/s.`, mode === 1 ? "Both differences vanish. The specified trajectory is exactly the periodic response from t=0, without a transient." : undamped ? "The nonzero correction persists because there is no damping. A bounded particular solution is not an asymptotically selected response in this case." : "The correction is nonzero and decays because b>0. The periodic response describes the late-time limit, not the entire startup.", "Matching only position is insufficient. The velocity equation is an independent initial condition."], `Particular initial state (${particularC} m, ${particularV} m/s); correction (${hx} m, ${hv} m/s); ${behavior}.`);
  }
  const w = 2 * scale, phase = quarter * Math.PI / 2, time = quarter * Math.PI / (2 * w), coefficient = a / (10 * massNumerator * w), x = coefficient * time * Math.sin(phase), v = coefficient * (Math.sin(phase) + w * time * Math.cos(phase));
  return finish(`Set b=0, m=${m} kg and k=${k} N/m. Start at x0=v0=0 and apply F(t)=(${force} N)*cos(${w}t). This is exact resonance with Omega=omega0=${w} rad/s. Determine the coefficient B in x(t)=B*t*sin(omega0*t), signed x and v at t=${quarter}*pi/${2 * w} s, and whether a bounded sinusoidal particular response exists.`,
    [phs232Rational("coefficient", "Secular coefficient B", `${a}/${10 * massNumerator * w}`, "m/s"), phs232Approximate("position", "Signed position at the requested time", x, "m"), phs232Approximate("velocity", "Signed velocity at the requested time", v, "m/s"), choice("bounded", "Bounded sinusoidal particular response at exact resonance", "none", [["none", "None: the ideal resonant response grows", "Substitution requires a time times sine term. Finite-time position is finite, but no constant-amplitude sinusoid balances this force."], ["finite", "Use F0/k as a finite resonant amplitude", "F0/k is the static deflection. At this undamped resonant frequency the harmonic dynamic stiffness vanishes."], ["zero", "Zero because damping is zero", "Zero damping means no viscous loss, not zero response to a nonzero force."]])],
    ["A pure cosine particular guess repeats a homogeneous solution and cannot supply the nonzero resonant force. Try B*t*sin(omega0*t).", "Substitution into x''+omega0²*x=(F0/m)*cos(omega0*t) gives 2*B*omega0=F0/m.", "Differentiate the whole product: v=B[sin(omega0*t)+omega0*t*cos(omega0*t)]. Retain both terms and their signs."],
    [`B=F0/(2*m*omega0)=${a}/${10 * massNumerator * w} m/s. This response satisfies both zero initial coordinates.`, `At the requested time omega0*t=${quarter}*pi/2, giving x≈${x.toFixed(9)} m.`, `Differentiating both factors gives v≈${v.toFixed(9)} m/s. In particular, x can vanish while v is nonzero and growing between corresponding zero crossings.`, "The ideal linear solution remains finite at every finite time but grows without a bounded sinusoidal steady amplitude. Real systems can leave the linear regime; this equation alone does not describe that later behavior."], `B=${a}/${10 * massNumerator * w} m/s; x≈${x.toFixed(9)} m; v≈${v.toFixed(9)} m/s; no bounded sinusoidal particular response.`);
}
