import { questionSchema, type AnswerField } from "../contracts";
import { randomFrom } from "../random";
import { phs232Choice, phs232Exact, phs232Pi, phs232Rational } from "./phs-232-fields";

export const phs232OscillatorEnergyFamilyIds = ["phs232-oscillator-energy"] as const;
export const phs232OscillatorEnergyVariants = ["energy-partition", "turning-amplitude", "vertical-offset", "spring-combination", "speed-bound", "parameter-scaling"] as const;

export function phs232OscillatorEnergyQuestion(familyId: string, variant: string, seed: string, id: string) {
  if (familyId !== "phs232-oscillator-energy" || !(phs232OscillatorEnergyVariants as readonly string[]).includes(variant)) throw new Error("Unknown PHS 232 oscillator energy family or variant.");
  const rng = randomFrom(`${familyId}:${variant}:${seed}`);
  const massNumerator = rng.integer(1, 8), omega = rng.integer(1, 8), scale = rng.integer(1, 8), sx = rng.integer(0, 1) ? 1 : -1, sv = rng.integer(0, 1) ? 1 : -1;
  const energyCase = rng.integer(-1, 1), gravity = rng.integer(5, 15), k1 = rng.integer(1, 12), k2 = rng.integer(1, 12), parallel = rng.integer(0, 1), positionIndex = rng.integer(0, 6);
  const massFactor = rng.integer(1, 4), stiffnessFactor = [1, 2, 4, 9][rng.integer(0, 3)], amplitudeFactor = rng.integer(1, 3);
  const parameters = { massNumerator, omega, scale, sx, sv, energyCase, gravity, k1, k2, parallel, positionIndex, massFactor, stiffnessFactor, amplitudeFactor };
  const m = `${massNumerator}/4`, k = `${massNumerator * omega * omega}/4`, energy = `${massNumerator * omega * omega * scale * scale}/3200`;
  const choice = (id: string, label: string, correct: string, options: [string, string, string][]) => phs232Choice(id, label, correct, rng.shuffle(options));
  const roots = (expected: string[]): AnswerField => ({ id: "positions", label: "All positions where kinetic energy is zero", kind: "roots", numberSystem: "real", expected, unit: "m", help: "List every distinct exact real position, separated by commas. Enter none if there are no admissible positions. Do not repeat a zero root." });
  const finish = (prompt: string, fields: AnswerField[], hints: string[], explanation: string[], answerSummary: string) => questionSchema.parse({
    id, familyId, familyVersion: 1, courseId: "phs-232", objectiveId: "m01-l02", category: "application", critical: true, parameters, prompt, fields, hints, explanation, answerSummary,
  });
  if (variant === "energy-partition") {
    const kinetic = `${massNumerator * omega * omega * scale * scale}/5000`, potential = `${9 * massNumerator * omega * omega * scale * scale}/80000`;
    return finish(`An ideal horizontal spring oscillator has m=${m} kg, k=${k} N/m and potential U=k*x²/2 with zero at equilibrium. At one instant x=${sx * 3 * scale}/100 m and v=${sv * 4 * scale * omega}/100 m/s. Find kinetic energy, spring energy, total energy and the fraction of the total currently stored in the spring. Would reversing only the velocity sign at this state change the total energy? Treat these exercise values as exact.`,
      [phs232Rational("kinetic", "Kinetic energy", kinetic, "J"), phs232Rational("potential", "Spring potential energy", potential, "J"), phs232Rational("total", "Total mechanical energy", energy, "J"), phs232Rational("fraction", "Fraction stored in the spring", "9/25"), choice("reversal", "Effect of reversing only velocity", "unchanged", [["unchanged", "Total energy is unchanged", "Kinetic energy depends on v². Reversing velocity changes phase and direction but leaves this state's energy unchanged."], ["negative", "Kinetic energy becomes negative", "Kinetic energy is nonnegative; the direction of motion does not set its sign."], ["zero", "Total energy becomes zero", "An instantaneous reversal does not put both displacement and speed at zero. The specified initial and final states have the same energy; a real reversal mechanism would need its own work account."]])],
      ["Evaluate K=m*v²/2 and U=k*x²/2, preserving the factors of one half and the SI units.", "Add K and U before finding the spring fraction U/(K+U). Squaring removes each coordinate's sign.", "The normalized state has displacement and velocity-length magnitudes in a 3:4 ratio, so their squared contributions are 9:16."],
      [`K=(${m})(${sv * 4 * scale * omega}/100)²/2=${kinetic} J; U=(${k})(${sx * 3 * scale}/100)²/2=${potential} J.`, `E=K+U=${energy} J. The potential fraction is U/E=9/(9+16)=9/25; the kinetic fraction is 16/25.`, "Velocity reversal preserves v² and therefore K and E. Energy alone cannot distinguish the two velocity directions. This comparison concerns the two states, not an unspecified physical procedure for reversing motion."],
      `K=${kinetic} J; U=${potential} J; E=${energy} J; U/E=9/25; reversal leaves E unchanged.`);
  }
  if (variant === "turning-amplitude") {
    const supplied = `${energyCase * massNumerator * omega * omega * scale * scale}/3200`;
    const meaning = energyCase < 0 ? "impossible" : energyCase === 0 ? "stationary" : "oscillating";
    const fields: AnswerField[] = [roots(energyCase < 0 ? [] : energyCase === 0 ? ["0"] : [`-${scale}/20`, `${scale}/20`])];
    if (energyCase >= 0) fields.push(phs232Rational("amplitude", "Amplitude", energyCase === 0 ? "0" : `${scale}/20`, "m"), phs232Rational("maximum-speed", "Maximum speed", energyCase === 0 ? "0" : `${omega * scale}/20`, "m/s"));
    fields.push(choice("meaning", "Physical interpretation with this energy reference", meaning, [["impossible", "No physical state has the supplied energy", "With U=k*x²/2 referenced to zero at its minimum and K=m*v²/2, their sum cannot be negative. Negative total energy is not forbidden for every possible potential reference."], ["stationary", "The mass remains at equilibrium", "Zero energy under this reference requires x=0 and v=0. That state is not a turning point of a nonzero oscillation."], ["oscillating", "Nonzero oscillation between two turning positions", "Positive energy gives two displacement extremes and a nonzero speed at equilibrium in this ideal model."]]));
    return finish(`An undamped horizontal oscillator has m=${m} kg and k=${k} N/m. Its potential is exactly U=k*x²/2, with U=0 at equilibrium. A proposed total energy is E=${supplied} J. Find every real position where K=0 while satisfying this energy equation. If a state exists, also find amplitude and maximum speed; then interpret the motion. Do not change the potential reference.`, fields,
      ["Because K and this particular U are both nonnegative, first check whether the supplied E is admissible.", "For E>0, set k*x²/2=E to find both signs of x; at equilibrium K=E gives the maximum speed.", "Treat E=0 separately: x and v must both be zero, so the single position is stationary rather than one of two distinct turning points."],
      energyCase < 0 ? [`Here E=${supplied} J is negative, but K+U≥0 under the specified reference.`, "There are no real zero-kinetic positions satisfying the energy equation and no physical amplitude or speed for this proposed state.", "This conclusion depends on the stated zero of potential energy. A negative energy with a different reference could be admissible; it cannot be rejected merely for being negative."] : [`At K=0, x²=2E/k=${energyCase === 0 ? "0" : `${scale * scale}/400`} m². The distinct allowed positions are ${energyCase === 0 ? "only zero" : `-${scale}/20 and +${scale}/20`} m.`, `A=${energyCase === 0 ? "0" : `${scale}/20`} m. At x=0, v_max=sqrt(2E/m)=${energyCase === 0 ? "0" : `${omega * scale}/20`} m/s.`, energyCase === 0 ? "Both state coordinates remain zero. There is no nonzero-amplitude reversal and no least positive trajectory period." : "At each extreme speed vanishes and restoring acceleration reverses the motion; at equilibrium all of this energy is kinetic."],
      `State: ${meaning}; zero-kinetic positions: ${energyCase < 0 ? "none" : energyCase === 0 ? "0 m" : `±${scale}/20 m`}.`);
  }
  if (variant === "vertical-offset") return finish(
    `An ideal vertical spring can pull or push and stays linear throughout this motion. Its mass is m=${m} kg, stiffness k=${k} N/m and uniform downward gravity is g=${gravity} m/s². Let y be downward displacement from the spring's unstretched position, so m*y''=m*g-k*y. Release the mass from rest at y0=(${gravity}/${omega * omega})+(${sx * scale}/20) m. Find the equilibrium offset, amplitude about that equilibrium, natural period and oscillation energy measured above the combined potential minimum. Would changing only g change the natural frequency in this same ideal model?`,
    [phs232Rational("equilibrium", "Equilibrium offset from unstretched position", `${gravity}/${omega * omega}`, "m"), phs232Rational("amplitude", "Amplitude about equilibrium", `${scale}/20`, "m"), phs232Pi("period", "Natural period", `2*pi/${omega}`, "s"), phs232Rational("energy", "Energy above the combined potential minimum", energy, "J"), choice("gravity", "Effect of changing g on natural frequency", "unchanged", [["unchanged", "Frequency is unchanged; equilibrium shifts", "Writing q=y-mg/k removes the constant force term. The restoring curvature remains k."], ["larger", "Frequency necessarily increases with g", "Gravity shifts this linear spring's equilibrium. A pendulum has a different restoring law and must not be substituted here."], ["zero", "Gravity removes all oscillation", "The constant weight cancels the spring force only at equilibrium, not at displaced states."]])],
    ["Set the net force to zero to find y_eq=m*g/k. Define displacement q=y-y_eq.", "The release is at rest, so A=|q0|. Substitution gives m*q''=-k*q.", "Complete the square in U(y)=k*y²/2-m*g*y. The energy above its minimum is K+k*q²/2."],
    [`y_eq=m*g/k=${gravity}/${omega * omega} m. The initial displacement about it is q0=${sx * scale}/20 m, so A=${scale}/20 m.`, `The shifted equation has omega=sqrt(k/m)=${omega} rad/s and T=2*pi/${omega} s. The static extension and oscillation amplitude are different quantities.`, `U(y)=k(y-y_eq)²/2-m*g²/(2*omega²). Adding K and subtracting U_min leaves E_osc=k*A²/2=${energy} J.`, "Changing the constant g changes y_eq and the potential minimum, but not the curvature k or this natural frequency. This conclusion assumes the spring remains in its linear operating range."],
    `y_eq=${gravity}/${omega * omega} m; A=${scale}/20 m; T=2*pi/${omega} s; E_osc=${energy} J; frequency unchanged.`);
  if (variant === "spring-combination") {
    const effective = parallel ? String(k1 + k2) : `${k1 * k2}/${k1 + k2}`;
    return finish(`Two ideal massless springs have k1=${k1} N/m and k2=${k2} N/m. ${parallel ? "They act in parallel: both have the same displacement of the attached mass, and their restoring forces add." : "They act in series through a massless junction: their signed extensions add to the attached mass's displacement, and the same force magnitude acts through each spring."} The only moving inertia is m=${m} kg. From the common equilibrium the mass is displaced by q=${scale}/100 m. Find effective stiffness, natural angular frequency, restoring force magnitude and total spring energy above its minimum.`,
      [phs232Rational("stiffness", "Effective stiffness", effective, "N/m"), phs232Exact("omega", "Natural angular frequency", `sqrt((${effective})/(${m}))`, "rad/s"), phs232Rational("force", "Restoring force magnitude", `(${effective})*${scale}/100`, "N"), phs232Rational("energy", "Total stored spring energy", `(${effective})*${scale * scale}/20000`, "J")],
      [parallel ? "With equal displacements, F=(k1+k2)*q." : "With equal force F, q=F/k1+F/k2. Solve for F/q.", "Once k_eff is found, omega=sqrt(k_eff/m). Keep the mass outside the spring-combination rule.", "Find F=k_eff*|q| and U=k_eff*q²/2. For series springs you can check the energy using each separate extension F/ki."],
      [parallel ? `F=k1*q+k2*q, so k_eff=${effective} N/m. Both springs store energy at the same q.` : `q=F(1/${k1}+1/${k2}), so k_eff=${effective} N/m. It is smaller than either individual stiffness.`, `omega=sqrt((${effective})/(${m})) rad/s. F=(${effective})*${scale}/100 N and U=(${effective})*${scale * scale}/20000 J.`, parallel ? "Summing k1*q²/2 and k2*q²/2 reproduces the total energy." : "Using q1=F/k1 and q2=F/k2 gives U=F²(1/k1+1/k2)/2=F*q/2, which reproduces the effective-spring result.", "A connector with appreciable mass or additional independent moving masses would require a different dynamical model; the static combination alone would not describe every mode."],
      `k_eff=${effective} N/m; omega=sqrt((${effective})/(${m})) rad/s; F=(${effective})*${scale}/100 N; U=(${effective})*${scale * scale}/20000 J.`);
  }
  if (variant === "speed-bound") {
    const allowed = positionIndex <= 5, kinetic = `${massNumerator * omega * omega * scale * scale * (25 - positionIndex * positionIndex)}/80000`;
    const fields: AnswerField[] = [phs232Rational("required-kinetic", "Formal kinetic-energy requirement E minus U", kinetic, "J"), phs232Rational("maximum-speed", "Maximum speed anywhere on the admissible trajectory", `${omega * scale}/20`, "m/s")];
    if (allowed) fields.push(phs232Exact("speed", "Speed at the requested position", `${omega * scale}/100*sqrt(${25 - positionIndex * positionIndex})`, "m/s"));
    fields.push(choice("allowed", "Is the requested position reachable at this energy?", allowed ? "yes" : "no", [["yes", "Yes", "Reachability requires E-U≥0. Equality describes a turning position in this nonzero-energy motion."], ["no", "No", "A negative formal value E-U is a failed reachability test, not negative kinetic energy or a negative speed. No real velocity can satisfy the stated energy at that position."]]));
    return finish(`A horizontal oscillator has m=${m} kg, k=${k} N/m, U=k*x²/2 and conserved energy E=${energy} J. Consider x=${sx * positionIndex * scale}/100 m. Calculate the formal requirement K_required=E-U and the maximum speed anywhere on this energy's trajectory. If this position is reachable, also give the nonnegative speed there. Interpret a negative formal requirement as an inadmissible position, not as an actual kinetic energy.`, fields,
      ["The amplitude satisfies k*A²/2=E. Compare the target's magnitude with A.", "At a reachable position, speed=sqrt(2*(E-U)/m). A negative radicand is a failure of the proposed state.", "Maximum speed occurs at the potential minimum, where v_max=sqrt(2E/m). A turning position has zero speed but nonzero restoring acceleration."],
      [`A=sqrt(2E/k)=${scale}/20 m. The requested position is ${positionIndex}/5 of that amplitude in magnitude.`, `K_required=E-k*x²/2=${kinetic} J. The maximum speed on the actual trajectory is ${omega * scale}/20 m/s.`, allowed ? `The requirement is nonnegative. The speed is (${omega * scale}/100)*sqrt(${25 - positionIndex * positionIndex}) m/s; energy does not choose a velocity sign when this speed is nonzero.` : "The negative requirement would need a negative kinetic energy, which is impossible. Do not report an imaginary speed as a physical answer; this position lies outside the turning bounds."],
      `K_required=${kinetic} J; v_max=${omega * scale}/20 m/s; reachable=${allowed ? "yes" : "no"}${allowed ? `; speed=(${omega * scale}/100)*sqrt(${25 - positionIndex * positionIndex}) m/s` : ""}.`);
  }
  return finish(`Compare two separately prepared ideal horizontal oscillators. The first has positive mass m, stiffness k and nonzero amplitude A. The second has mass ${massFactor}m, stiffness ${stiffnessFactor}k and amplitude ${amplitudeFactor}A. Both are linear and undamped. Find the second-to-first ratios of natural period, cyclic frequency, maximum speed and total oscillation energy above equilibrium. This compares specified states; it does not describe changing parameters during one trajectory.`,
    [phs232Exact("period", "Period ratio T2/T1", `sqrt(${massFactor}/${stiffnessFactor})`), phs232Exact("frequency", "Frequency ratio f2/f1", `sqrt(${stiffnessFactor}/${massFactor})`), phs232Exact("speed", "Maximum-speed ratio", `${amplitudeFactor}*sqrt(${stiffnessFactor}/${massFactor})`), phs232Rational("energy", "Total-energy ratio", String(stiffnessFactor * amplitudeFactor * amplitudeFactor))],
    ["Use T proportional to sqrt(m/k) and f=1/T, so their ratios must be reciprocals.", "The maximum speed is A*sqrt(k/m); retain the separate amplitude factor.", "At a turning point all energy is k*A²/2. The amplitude factor is squared, while mass enters only if other state conditions change."],
    [`T2/T1=sqrt(${massFactor}/${stiffnessFactor}); f2/f1=sqrt(${stiffnessFactor}/${massFactor}). Their product is one.`, `v_max,2/v_max,1=${amplitudeFactor}*sqrt(${stiffnessFactor}/${massFactor}). Speed changes through both the length scale and angular frequency.`, `E2/E1=${stiffnessFactor}*${amplitudeFactor}²=${stiffnessFactor * amplitudeFactor * amplitudeFactor}. At fixed specified A, this turning-point energy contains no mass factor.`, "A real parameter change during motion can exchange energy with an external mechanism and change amplitude. Those conditions are not supplied here, so that different problem cannot be inferred from these ratios."],
    `T ratio=sqrt(${massFactor}/${stiffnessFactor}); f ratio=sqrt(${stiffnessFactor}/${massFactor}); speed ratio=${amplitudeFactor}*sqrt(${stiffnessFactor}/${massFactor}); energy ratio=${stiffnessFactor * amplitudeFactor * amplitudeFactor}.`);
}
