import { questionSchema } from "../contracts";
import { randomFrom } from "../random";
import { formatRational,parseRational } from "../rational";

export const phs231ModelDiagnosisVariants=["damping-pair","nonlinear-pair","identifiability","energy-source","coarse-step","clipped-run","parameter-change","offset-drift","relative-error","revision-plan"] as const;
export const phs231ModelDiagnosisFamilyIds=["phs231-model-diagnosis"];
const field=(id:string,label:string,expected:string,unit:string)=>({id,label,kind:"rational",expected:formatRational(parseRational(expected)),unit,help:"Use an exact expression or equivalent fraction in the labeled unit."});
export function phs231ModelDiagnosisQuestion(familyId:string,variant:string,seed:string,id:string){
  if(familyId!=="phs231-model-diagnosis"||!(phs231ModelDiagnosisVariants as readonly string[]).includes(variant))throw Error("Unknown PHS 231 model-diagnosis variant.");
  const rng=randomFrom(`${familyId}:${variant}:${seed}`);
  const choice=(id:string,label:string,correct:string,options:{id:string;label:string;feedback:string}[])=>({id,label,kind:"choice",correct,options:rng.shuffle(options)});
  const finish=(parameters:Record<string,number>,prompt:string,fields:unknown[],hints:string[],explanation:string[],answerSummary:string)=>questionSchema.parse({id,familyId,familyVersion:1,courseId:"phs-231",objectiveId:"m09-l02",category:"application",critical:true,parameters:Object.fromEntries(Object.entries(parameters).map(([k,v])=>[k,v||0])),prompt,fields,hints,explanation,answerSummary});
  if(variant==="damping-pair"){
    const k=rng.integer(2,12),X=rng.integer(-4,4),V=rng.integer(1,5),B=rng.integer(1,5),Z=rng.integer(-5,5),minus=-k*X+B*V+Z,plus=-k*X-B*V+Z;
    return finish({k,X,V,B,Z},`Exact synthetic readings obey y=-k*x-b*v+z. Independently known k=${k} N/m. At the same x=${X}/100 m, velocities -${V}/10 and +${V}/10 m/s give readings ${minus}/100 and ${plus}/100 N. Find b, average output, z, and positive dissipative power b*v² at either state.`,
      [field("drag","Viscous coefficient",`${B}/10`,"kg/s"),field("mean","Average sensor output",`${-k*X+Z}/100`,"N"),field("zero","Sensor zero",`${Z}/100`,"N"),field("power","Positive dissipative power",`${B*V*V}/1000`,"W"),choice("assumption","Assumption needed for the separation","matched",[
        {id:"matched",label:"Only velocity reverses; x, k, b and the sensor zero remain the same",feedback:"The difference cancels the spring term and common zero while the viscous contribution reverses."},
        {id:"static",label:"Static states identify b equally well",feedback:"At v=0 the viscous force vanishes for every b."},
        {id:"universal",label:"The fitted b proves all drag is linear",feedback:"Other physical regimes can require different drag laws."}
      ])],["Subtract positive-velocity output from negative-velocity output.","Divide by the positive velocity separation; use the mean to remove drag.","Positive dissipative power is b*v². Signed mechanical power of drag is its negative."],
      [`The output difference ${2*B*V}/100 N divided by ${2*V}/10 m/s gives b=${B}/10 kg/s.`,`Mean output is ${-k*X+Z}/100 N=-k*x+z, so z=${Z}/100 N. Dissipative power is ${B*V*V}/1000 W.`,"The identification depends on matched states and a common correction."],
      `b=${B}/10 kg/s; mean=${-k*X+Z}/100 N; z=${Z}/100 N; power=${B*V*V}/1000 W.`);
  }
  if(variant==="nonlinear-pair"){
    const C=rng.integer(1,9),X=rng.integer(1,4),k=rng.integer(2,10),R=-C*X**3;
    return finish({C,X,k},`After known-zero correction, a frozen candidate F=-${k}x leaves exact synthetic residuals observed-minus-candidate of ${R}/10000 N at x=${X}/100 m and ${8*R}/10000 N at twice that positive displacement; both v=0. Test a missing term -c*x³. Find residual ratio, inferred c, and additional spring potential at the first displacement using U_add=c*x⁴/4 with U_add(0)=0.`,
      [field("ratio","Second residual divided by first","8","1"),field("cubic","Proposed cubic force coefficient",String(100*C),"N/m³"),field("energy","Additional potential at first displacement",`${C*X**4}/4000000`,"J"),choice("claim","Meaning of the pattern","candidate",[
        {id:"candidate",label:"Consistent with the cubic candidate here; further independent checks are needed",feedback:"Two matching points do not uniquely distinguish a mechanical nonlinearity from other force or sensor explanations."},
        {id:"proof",label:"Unique proof of a cubic mechanical law at all displacements",feedback:"Many functions or observation errors can agree at two points."},
        {id:"drag",label:"Identification of viscous drag",feedback:"Both velocities vanish, so these records cannot identify a velocity-proportional term."}
      ])],["Doubling x multiplies x³ by eight.","Solve c=-r/x³, using meters.","Integrate the restoring term with the sign convention F=-dU/dx."],
      [`The residual ratio is 8. Solving the first state gives c=${100*C} N/m³.`,`Then c*x⁴/4=${C*X**4}/4000000 J, positive despite the negative restoring force at positive x.`,"This calculation checks a candidate; it does not prove its unique physical cause."],
      `Ratio 8; c=${100*C} N/m³; U_add=${C*X**4}/4000000 J.`);
  }
  if(variant==="identifiability"){
    const mode=rng.integer(0,2),k=rng.integer(2,10),B=rng.integer(1,5),C=rng.integer(1,4),X=rng.integer(1,5),V=rng.integer(1,5),K=10*k+B*C;
    const prompt=mode===0?`Known-zero corrected synthetic records obey F=-k*x-b*v with unknown k>0, b≥0. Every velocity is zero. At x=${X}/100 m, F=${-k*X}/100 N. Determine k and how many of the two coefficients remain free after all such static records.`:mode===1?`Known-zero corrected records obey F=-k*x-b*v. Every record has v=c*x with known c=${C} s⁻¹. At x=${X}/100 m, F=${-K*X}/1000 N. Determine effective stiffness K=k+b*c. If b is separately supplied as ${B}/10 kg/s, find conditional k. Count free coefficients when BOTH k and b are unknown and only these coupled records are used.`:`Known-zero corrected records obey F=-k*x-b*v. At x=${X}/100 m, v=0, F=${-k*X}/100 N. Independently, at x=0, v=${V}/10 m/s, F=${-B*V}/100 N. Determine k, b, and the number of unresolved coefficients in this exact model.`;
    return finish({mode,k,B,C,X,V},prompt,
      [...(mode===1?[field("effective","Identifiable effective stiffness",`${K}/10`,"N/m"),field("stiffness","Conditional stiffness with separately supplied b",String(k),"N/m")]:[field("stiffness","Stiffness",String(k),"N/m")]),...(mode===2?[field("drag","Viscous coefficient",`${B}/10`,"kg/s")]:[]),field("free","Unresolved free coefficients",mode===2?"0":"1","1"),choice("claim","What is identifiable?",["static","coupled","separate"][mode],[
        {id:"static",label:"Only k; static states contain no information about b",feedback:mode===0?"Every allowed b gives the same static forces.":"These supplied state relations include additional velocity information."},
        {id:"coupled",label:"Only k+b*c without extra information; fixing b gives conditional k",feedback:mode===1?"Substitution gives F=-(k+b*c)x. More states on that same line supply no new independent equation.":"The supplied states do not all satisfy this nonzero proportional relation."},
        {id:"separate",label:"Both coefficients within the specified law, using independent nonzero x and v conditions",feedback:mode===2?"One state isolates k and the other b; known zero and model form are still assumptions.":"These equations cannot independently identify both unknowns."}
      ])],["Write the force equation for each kind of state.","Check whether another record is only a multiple of the first equation.","Fixing a parameter by assumption is different from identifying it with data."],
      [mode===0?`The static state gives k=-F/x=${k} N/m, while any b≥0 remains possible.`:mode===1?`K=-F/x=${K}/10 N/m. With independent b=${B}/10 kg/s, k=K-b*c=${k} N/m. Without it, a continuum of k>0 and b≥0 shares this K.`:`The independent states give k=${k} N/m and b=${B}/10 kg/s.`,mode===2?"Zero of these two coefficients remain free under the supplied law. This does not establish sensor or model validity.":"One coefficient remains free; repeated copies of the same relation do not remove that freedom."],
      `k=${k} N/m ${mode===1?"conditionally":""}; ${mode===1?`K=${K}/10 N/m; `:""}${mode===2?`b=${B}/10 kg/s; `:""}free=${mode===2?0:1}.`);
  }
  if(variant==="energy-source"){
    const E=rng.integer(2,6),D=rng.integer(1,5),W=rng.integer(-3,3),R=rng.integer(-3,3),E1=100*E-10*D+10*W+R;
    return finish({E,D,W,R},`A synthetic account uses E1+D=E0+W_ext+R. E0=${E} J; E1=${E1}/100 J; positive dissipative transfer D=${D}/10 J; signed external work W_ext=${W}/10 J. Calculate residual R and final energy predicted by a balanced account (R=0). Values are independently supplied with exact arithmetic.`,
      [field("residual","Energy-account residual",`${R}/100`,"J"),field("balanced","Final energy predicted with R=0",`${10*E-D+W}/10`,"J"),choice("claim","Interpret the residual",R===0?"consistent":"investigate",[
        {id:"consistent",label:"The supplied account closes, without proving every physical assumption",feedback:R===0?"The arithmetic balances; compensating errors or missing evidence can still limit physical conclusions.":"The nonzero residual means this exact account does not close."},
        {id:"investigate",label:"Investigate numerical, measurement or omitted-transfer explanations for a mismatch",feedback:R!==0?"A signed mismatch does not identify a unique source by itself.":"This exact account closes, though broader validity remains limited."},
        {id:"source",label:"Label the residual a measured new force or heat source",feedback:"An accounting residual does not identify a unique mechanism. Establish that mechanism separately."}
      ])],["Rearrange to R=E1+D-E0-W_ext.","A balanced prediction uses E1=E0+W_ext-D.","Do not invent a physical transfer from an unexplained discrepancy."],
      [`R=(${E1}/100)+(${D}/10)-${E}-(${W}/10)=${R}/100 J.`,`Balanced E1=${10*E-D+W}/10 J. Positive D removes mechanical energy; positive external work supplies it.`,"Closing an account and validating all underlying evidence are different claims."],
      `R=${R}/100 J; balanced E1=${10*E-D+W}/10 J.`);
  }
  if(variant==="coarse-step"){
    const order=rng.integer(1,2),Q=rng.integer(-5,5),A=rng.integer(1,5),sign=rng.integer(0,1)?1:-1,U=rng.integer(1,4),ratio=2**order,den=4**order;
    return finish({order,Q,A,sign,U},`At a common endpoint an exact synthetic fixture gives Q(h)=${100*Q+sign*A}/100 m, Q(h/2)=${100*ratio*Q+sign*A}/${100*ratio} m, Q(h/4)=${100*den*Q+sign*A}/${100*den} m. Assume Q(h)=Q_*+C*h^p EXACTLY, with p=1 or 2. Separately, a held-out force residual magnitude is ${2*U}/100 N with bound ${U}/100 N. Find p, Q_*, finest absolute numerical error, and normalized force discrepancy.`,
      [field("order","Order under the supplied exact error law",String(order),"1"),field("limit","Extrapolated limit",String(Q),"m"),field("error","Finest absolute numerical error",`${A}/${100*den}`,"m"),field("force-ratio","Force residual divided by bound","2","1"),choice("claim","Can numerical refinement repair the force comparison?","separate",[
        {id:"separate",label:"No; convergence to the model solution leaves the separate force discrepancy unresolved",feedback:"A convergent method can accurately solve an inappropriate equation or use a biased observation."},
        {id:"cure",label:"Yes; convergence proves the physical force law",feedback:"A smaller step does not fix a missing force or sensor correction."},
        {id:"rigorous",label:"Any three nearby values prove a universal rigorous error bound",feedback:"This exercise supplied an exact single-power law. General computations need additional assumptions and checks."}
      ])],["The ratio of successive differences equals 2^p under this supplied law.","Eliminate the error term with the two finer values.","Keep the independent force tolerance check separate."],
      [`Successive-difference ratio ${ratio} gives p=${order}; extrapolation gives Q_*=${Q} m.`,`Finest absolute error is ${A}/${100*den} m. Force discrepancy is twice its bound and fails that comparison.`,"Three actual refinements can suggest asymptotic behavior; cancellation and roundoff can invalidate an unsupported error claim."],
      `p=${order}; Q_*=${Q} m; finest error=${A}/${100*den} m; force ratio=2.`);
  }
  if(variant==="clipped-run"){
    const T=rng.integer(2,6),R=rng.integer(1,9),E=rng.integer(1,9);
    return finish({T,R,E},`A simulation requested T=${T} s but stopped at t=${10*T-R}/10 s before an unsafe numerical update. Its last computed absolute position error against the analytic reference is ${E}/1000 m at that earlier time. Give the missing duration and known last-state error; classify the requested-endpoint result.`,
      [field("missing","Requested time minus last computed time",`${R}/10`,"s"),field("last-error","Known error at the actual last time",`${E}/1000`,"m"),choice("endpoint","Error at the requested endpoint","unavailable",[
        {id:"unavailable",label:"Unavailable; the earlier error cannot stand in for a result at T",feedback:"Preserve actual time and completion status. A revised run must reach T before comparison at that endpoint."},
        {id:"same",label:"Equal to the earlier error because it was the final row",feedback:"Final computed row and requested endpoint are different after an early stop."},
        {id:"zero",label:"Zero because the program rejected the unsafe update",feedback:"Rejecting an update prevents invalid output; it does not supply the missing state."}
      ])],["Subtract actual last time from requested T.","Retain the printed error with its actual time.","No formula or valid computed state at T is supplied."],
      [`The uncomputed duration is ${R}/10 s. The known error remains ${E}/1000 m at t=${10*T-R}/10 s.`,"No requested-endpoint error can be inferred. Revise the numerical setup, preserve the stopped record, and complete an independently checked run."],
      `Missing duration ${R}/10 s; actual last-state error ${E}/1000 m; requested-endpoint error unavailable.`);
  }
  if(variant==="parameter-change"){
    const mode=rng.integer(0,2),m=rng.integer(1,4),k=rng.integer(2,10),X=rng.integer(1,5),factor=rng.integer(2,3);
    const description=mode===0?`multiply mass by ${factor}`:mode===1?`multiply stiffness by ${factor}`:"halve only the numerical time step";
    const newA=mode===0?`${-k*X}/${100*m*factor}`:mode===1?`${-k*X*factor}/${100*m}`:`${-k*X}/${100*m}`;
    const frequency=mode===0?`1/sqrt(${factor})`:mode===1?`sqrt(${factor})`:"1";
    return finish({mode,m,k,X,factor},`An undamped linear oscillator has m=${m} kg, k=${k} N/m, x0=${X}/100 m and v0=0. A controlled comparison will ${description}, leaving the other physical inputs and initial state unchanged. Find old and new physical initial acceleration, new/old natural angular frequency, and new/old initial mechanical energy. Classify the comparison.`,
      [field("old-acceleration","Original physical initial acceleration",`${-k*X}/${100*m}`,"m/s²"),field("new-acceleration","New physical initial acceleration",newA,"m/s²"),{id:"frequency-ratio",label:"New divided by old natural angular frequency",kind:"exact",expected:frequency,unit:"1",help:"Use an exact positive real value, with sqrt(...) if needed."},field("energy-ratio","New divided by old initial mechanical energy",mode===1?String(factor):"1","1"),choice("comparison","What was varied?",mode===2?"numerical":"physical",[
        {id:"physical",label:"A physical model parameter; this is parameter sensitivity, not a pure step-refinement check",feedback:mode!==2?"Changing m or k changes the equation and its analytic solution. Compare numerical methods at fixed physical inputs separately.":"Only the algorithm's step changes here; the physical equation is unchanged."},
        {id:"numerical",label:"Only the discretization; the physical equation and initial state stay fixed",feedback:mode===2?"A pure step refinement holds mass, stiffness and initial conditions fixed.":"Changing mass or stiffness changes physical predictions even with an exact solver."},
        {id:"sensor",label:"Only the force sensor zero",feedback:"No observation correction was changed in the supplied comparison."}
      ])],["Use a0=-k*x0/m for the physical initial derivative.","Use ω=sqrt(k/m) and E0=k*x0²/2 since v0=0.","A numerical step is not a parameter of the continuous mechanical equation."],
      [`Original a0=${-k*X}/${100*m} m/s²; new a0=${newA} m/s². The frequency ratio is ${frequency}.`,`The initial energy ratio is ${mode===1?factor:1}. At v0=0 changing only mass leaves initial spring energy unchanged.`,mode===2?"Step refinement tests the discretization at a fixed model.":"This comparison tests physical parameter sensitivity; it does not isolate numerical error."],
      `Old a0=${-k*X}/${100*m}, new a0=${newA} m/s²; frequency ratio ${frequency}; energy ratio ${mode===1?factor:1}.`);
  }
  if(variant==="offset-drift"){
    const k=rng.integer(2,12),X=rng.integer(-5,5),Z=rng.integer(-4,4),D=(rng.integer(0,1)?1:-1)*rng.integer(1,6),later=Z+D,reading=-k*X+later;
    return finish({k,X,Z,D},`A sensor follows y=F+z. Its earlier zero-force reading was ${Z}/100 N. A later independent zero-force check reads ${later}/100 N. At that later time the output at x=${X}/100 m, v=0 is ${reading}/100 N. The candidate spring has k=${k} N/m. Find the later zero, residual against a prediction that still uses the old zero, and force corrected with the later zero.`,
      [field("zero","Later sensor zero",`${later}/100`,"N"),field("residual","Observation minus prediction using the old zero",`${D}/100`,"N"),field("force","Force after the later zero correction",`${-k*X}/100`,"N"),choice("revision","What does the new reference support?","recalibrate",[
        {id:"recalibrate",label:"Update the sensor zero for this group, retain the old calibration record, and check stability",feedback:"The independent zero-force check supports an observation correction. It does not require inventing a new spring force."},
        {id:"drive",label:"Add the zero shift as a physical driving force to the motion equation",feedback:"The reference establishes a sensor output change at zero force, not a force on the body."},
        {id:"delete",label:"Delete the earlier record and claim the sensor never drifted",feedback:"Preserve when and how a correction was obtained; drift is relevant evidence."}
      ])],["A zero-force reference directly measures the additive output zero in this model.","Keep the same mechanical force while comparing old and new predicted sensor readings.","Correct the later observation by subtracting the later zero."],
      [`The later zero is ${later}/100 N. Prediction with the old zero leaves residual ${D}/100 N.`,`Subtracting the later zero gives F=${-k*X}/100 N. This is an observation correction supported by an independent reference.`,"A single later reference does not establish stability over every subsequent time or force range."],
      `Later zero ${later}/100 N; old-zero residual ${D}/100 N; corrected force ${-k*X}/100 N.`);
  }
  if(variant==="relative-error"){
    const Q=rng.integer(0,1)?rng.integer(1,5):0,E=rng.integer(1,5),sign=rng.integer(0,1)?1:-1,S=rng.integer(1,5),computed=Q+sign*E;
    return finish({Q,E,sign,S},`At a completed numerical endpoint the analytic reference position for the same model is ${Q}/100000 m and computed position is ${computed}/100000 m. An independently declared displacement scale is ${S}/100 m. Find absolute error, absolute error divided by that scale, ${Q?"and absolute error divided by the reference magnitude.":"and classify reference-relative error at this state."} These are numerical comparisons, not observations of hardware.`,
      [field("absolute","Absolute position error",`${E}/100000`,"m"),field("scaled","Absolute error divided by declared scale",`${E}/${1000*S}`,"1"),...(Q?[field("relative","Absolute error divided by reference magnitude",`${E}/${Q}`,"1")]:[]),choice("meaning","How should the comparison be reported?",Q?"defined":"undefined",[
        {id:"defined",label:"Reference-relative error is defined here; report its scale and absolute error too",feedback:Q?"A nonzero denominator allows the ratio, but a very small reference can magnify it.":"The reference equals zero, so that ratio has no defined value."},
        {id:"undefined",label:"Reference-relative error is undefined; use the absolute error and separately declared scale",feedback:Q?"The reference is nonzero in this case.":"Division by zero is undefined. A declared nonzero scale gives a different, explicitly named normalization."},
        {id:"zero",label:"A small absolute error makes relative error zero and physically validates the model",feedback:"Neither statement follows. Relative error depends on its denominator, and comparison to the same model is a numerical check."}
      ])],["Subtract states at the same time, then take the absolute value.","Normalize by the printed independent nonzero displacement scale.","Check whether the reference itself is zero before forming a reference-relative ratio."],
      [`Absolute error is ${E}/100000 m; scale-normalized error is ${E}/${1000*S}.`,Q?`Reference-relative error is ${E}/${Q}. Its size reflects the small reference magnitude.`:"Reference-relative error is undefined, not zero, infinity as an accepted value, or the separate scale-normalized result.","Agreement with an analytic solution checks the supplied equation and numerical implementation, not an unobserved physical apparatus."],
      `Absolute error ${E}/100000 m; scaled error ${E}/${1000*S}; reference-relative ${Q?`${E}/${Q}`:"undefined"}.`);
  }
  const mode=rng.integer(0,3),B=rng.integer(1,5),V=rng.integer(1,5),C=rng.integer(1,8),X=rng.integer(1,4),D=(rng.integer(0,1)?1:-1)*rng.integer(1,5),E=rng.integer(1,5);
  const scenario=mode===0?`At fixed x, a candidate omits drag. Exact synthetic residuals at v=-${V}/10 and +${V}/10 m/s are +${B*V}/100 and -${B*V}/100 N. Under a proposed missing -b*v term, infer b.`:mode===1?`At v=0 a candidate leaves exact synthetic residual -${C*X**3}/10000 N at x=${X}/100 m, and eight times that residual at twice the displacement. Under a proposed missing -c*x³ term, infer c.`:mode===2?`Every held-out residual is ${D}/100 N. A separate known-zero-force check shows the sensor zero has shifted by exactly ${D}/100 N. Compute the signed zero correction to add to the candidate sensor prediction.`:`With unchanged physical inputs and completed common endpoints, absolute numerical errors are ${E}/1000 m at h and ${E}/2000 m at h/2. Held-out force checks meet their declared bounds. Assuming error C*h^p exactly for this exercise, infer p.`;
  const expected=mode===0?`${B}/10`:mode===1?String(100*C):mode===2?`${D}/100`:"1";
  return finish({mode,B,V,C,X,D,E},scenario+" Choose a discriminating next check before extending the conclusion.",
    [field("inference",["Proposed viscous coefficient","Proposed cubic coefficient","Signed sensor-zero correction","Order under the supplied error law"][mode],expected,["kg/s","N/m³","N","1"][mode]),choice("next","Most directly discriminating next check",["drag-test","spring-test","zero-test","step-test"][mode],[
      {id:"drag-test",label:"At fixed x, test new positive and negative velocities with an independently stable sensor zero",feedback:mode===0?"This varies the proposed viscous effect while controlling spring contribution and zero.":"This is valuable for a velocity-dependent hypothesis, but the current evidence motivates a different targeted check."},
      {id:"spring-test",label:"Test new static displacement magnitudes and independently check sensor scale and nonlinearity",feedback:mode===1?"This challenges the cubic candidate beyond the fitted pair and checks a competing observation explanation.":"This is targeted at a displacement nonlinearity, not the primary pattern supplied here."},
      {id:"zero-test",label:"Repeat independent zero-force references over the affected time or group interval",feedback:mode===2?"The known reference supports drift; repeated references test its extent and stability.":"A reference is useful, but the stated pattern primarily calls for another controlled comparison."},
      {id:"step-test",label:"Run another same-endpoint step refinement at fixed physical inputs and compare with an independent solution",feedback:mode===3?"This challenges the numerical error trend without changing the physical equation.":"Step refinement cannot alone resolve the supplied observation or force-law discrepancy."}
    ]),choice("limit","Limit on the resulting claim","limited",[
      {id:"limited",label:"The evidence supports a targeted hypothesis or numerical check within its stated conditions",feedback:"Record what changed, the independent check, and what remains untested. A pattern does not by itself establish unique physical causation."},
      {id:"universal",label:"The pattern uniquely proves the entire physical model for every state",feedback:"Finite synthetic records and a stipulated error law cannot establish universal physical validity."}
    ])],["Write the candidate missing term or error law and isolate its coefficient.","Choose a new condition that changes that term while controlling plausible alternatives.","Keep synthetic provenance, supplied assumptions and untested conditions in the conclusion."],
    [`The inferred quantity is ${expected} ${["kg/s","N/m³","N","1"][mode]}.`,["An opposite-velocity difference isolates the antisymmetric drag contribution if the sensor zero and displacement match.","Cubic residual scaling supplies a candidate coefficient; new static states and sensor checks challenge it.","The independent zero-force reference supports a signed observation correction, not an invented mechanical force.","The error ratio is two for a halved step, giving p=1 under the supplied exact power law."][mode],"The proposed next check can discriminate among explanations without turning this limited result into a universal claim."],
    `Inferred value ${expected} ${["kg/s","N/m³","N","1"][mode]}; use the targeted next check and retain the limits.`);
}
