import { questionSchema, type AnswerField } from "../contracts";
import { randomFrom } from "../random";
import { phs232Choice, phs232Exact, phs232Pi, phs232Rational } from "./phs-232-fields";

export const phs232TravelingWaveFamilyIds = ["phs232-traveling-wave"] as const;
export const phs232TravelingWaveVariants = ["direction", "phase-speed", "local-velocity", "local-acceleration", "phase-delay", "wave-equation"] as const;

export function phs232TravelingWaveQuestion(familyId: string, variant: string, seed: string, id: string) {
  if (familyId !== "phs232-traveling-wave" || !(phs232TravelingWaveVariants as readonly string[]).includes(variant)) throw Error("Unknown PHS 232 traveling-wave family or variant.");
  const rng = randomFrom(familyId + ":" + variant + ":" + seed), a = rng.integer(1, 9), k = rng.integer(1, 4), c = rng.integer(2, 8), direction = rng.integer(0, 1) ? 1 : -1, phaseIndex = rng.integer(0, 7), cycles = rng.integer(1, 4), quarter = rng.integer(0, 3), mode = rng.integer(0, 3), densityNumerator = rng.integer(1, 9);
  const parameters = { a, k, c, direction, phaseIndex, cycles, quarter, mode, densityNumerator }, omega = k * c, amplitude = a + "/1000", phase = phaseIndex + "*pi/4";
  const sine = ["0", "sqrt(2)/2", "1", "sqrt(2)/2", "0", "-sqrt(2)/2", "-1", "-sqrt(2)/2"][phaseIndex], cosine = ["1", "sqrt(2)/2", "0", "-sqrt(2)/2", "-1", "-sqrt(2)/2", "0", "sqrt(2)/2"][phaseIndex];
  const choice = (id: string, label: string, correct: string, options: [string, string, string][]) => phs232Choice(id, label, correct, rng.shuffle(options));
  const finish = (prompt: string, fields: AnswerField[], hints: string[], explanation: string[], answerSummary: string) => questionSchema.parse({ id, familyId, familyVersion: 1, courseId: "phs-232", objectiveId: "m02-l01", category: "application", critical: true, parameters, prompt, fields, hints, explanation, answerSummary });
  const setup = "An ideal string carries y(x,t)=(" + amplitude + " m)*cos((" + k + " rad/m)*x " + (direction === 1 ? "-" : "+") + " (" + omega + " rad/s)*t + " + phase + "). Coordinates x and y are in meters and t is in seconds; +x is right and +y is up. This is a single traveling wave on a uniform medium.";
  if (variant === "direction") return finish(setup + " Find the signed velocity of a tracked crest and y_t/y_x wherever y_x is nonzero. Could the initial displacement snapshot alone distinguish this wave from the one with the opposite sign of the time term?",
    [phs232Rational("crest", "Signed crest velocity", String(direction * c), "m/s"), phs232Rational("ratio", "Partial derivative ratio y_t / y_x", String(-direction * c), "m/s"),
      choice("snapshot", "Does the t=0 displacement snapshot fix direction?", "no", [["no", "No: the two waves have the same initial shape", "Reversing the time sign leaves the t=0 profile unchanged but reverses its subsequent translation."], ["yes", "Yes: positive wave number means rightward travel", "A positive k does not fix the direction without the sign of the time term."]])],
    ["Hold the phase constant while following a crest: k*dx/dt minus sigma*omega is zero.", "Differentiate with respect to x at fixed t and t at fixed x. Their ratio is the negative of the crest velocity when the denominator is nonzero.", "At t=0 the time term vanishes for either sign. A snapshot shows displacement, not its time derivative."],
    ["The fixed phase moves at sigma*omega/k=" + direction * c + " m/s. This describes a pattern location, not a material point translating along x.", "The translated-profile identity is y_t=-sigma*c*y_x, hence y_t/y_x=" + -direction * c + " m/s wherever the slope is nonzero.", "At a crest both first derivatives vanish, so their ratio is undefined there; do not evaluate 0/0.", "The opposite-time-sign function has the same initial snapshot. Further time information or the specified equation distinguishes the direction."],
    "Crest velocity=" + direction * c + " m/s; derivative ratio=" + -direction * c + " m/s off zero-slope points; a snapshot alone is insufficient.");
  if (variant === "phase-speed") return finish(setup + " Find the wavelength, period, frequency, positive propagation speed and maximum transverse particle speed. Keep pi exact.",
    [phs232Pi("wavelength", "Wavelength", "2*pi/" + k, "m"), phs232Pi("period", "Period", "2*pi/" + omega, "s"), phs232Pi("frequency", "Frequency", omega + "/(2*pi)", "Hz"), phs232Rational("speed", "Positive propagation speed", String(c), "m/s"), phs232Rational("particle", "Maximum transverse particle speed", a * omega + "/1000", "m/s")],
    ["One full spatial or temporal phase cycle is 2*pi radians: k*lambda=2*pi and omega*tau=2*pi.", "Frequency is the reciprocal of the period, not the angular frequency.", "The crest speed is omega/k. At fixed x, differentiating the displacement gives transverse velocity amplitude A*omega."],
    ["lambda=2*pi/k=2*pi/" + k + " m and tau=2*pi/omega=2*pi/" + omega + " s.", "f=1/tau=" + omega + "/(2*pi) Hz. Radians and cycles have distinct conversion factors even though radian measure is dimensionless.", "c=omega/k=" + c + " m/s, while max|y_t|=A*omega=" + a * omega + "/1000 m/s.", "The ratio max|y_t|/c=A*k=" + a * k + "/1000 is also the maximum slope here. The ideal small-slope model does not equate the two speeds."],
    "lambda=2*pi/" + k + " m; tau=2*pi/" + omega + " s; f=" + omega + "/(2*pi) Hz; c=" + c + " m/s; max|y_t|=" + a * omega + "/1000 m/s.");
  if (variant === "local-velocity") {
    const signSine = [0, 1, 1, 1, 0, -1, -1, -1][phaseIndex], motion = direction * signSine, velocity = direction * a * omega + "/1000*(" + sine + ")", slope = -a * k + "/1000*(" + sine + ")";
    return finish(setup + " At x=0,t=0, find the local transverse velocity and spatial slope, then describe the material point's instantaneous motion. The slope is a ratio of lengths and has no unit.",
      [phs232Exact("velocity", "Transverse velocity at zero", velocity, "m/s"), phs232Exact("slope", "Spatial slope at zero", slope), choice("motion", "Instantaneous transverse motion", motion > 0 ? "up" : motion < 0 ? "down" : "rest", [["up", "Upward", "The sign of y_t determines upward motion, not the sign of the wave's propagation velocity."], ["down", "Downward", "Negative y_t means downward local motion even if the pattern travels right."], ["rest", "Instantaneously at rest", "At a turning displacement y_t=0, but acceleration generally is nonzero; the point is not permanently stationary."]])],
      ["Differentiate cosine while holding x fixed. The negative from cosine and the time-term sign both matter.", "Differentiate with respect to x separately: y_x=-A*k*sin(theta). Evaluate the common phase only after differentiating.", "Use the exact sine of " + phase + "; direction of pattern travel and sign of local y_t are different questions."],
      ["At zero the phase is " + phase + ", with sine " + sine + ".", "y_t=sigma*A*omega*sin(theta)=" + velocity + " m/s. The sign gives the stated instantaneous motion.", "y_x=-A*k*sin(theta)=" + slope + ". Check y_t=-sigma*c*y_x.", "A zero result at a turning point does not erase the wave or make its phase speed zero."],
      "y_t=" + velocity + " m/s; y_x=" + slope + "; instantaneous motion=" + (motion > 0 ? "upward" : motion < 0 ? "downward" : "at rest") + ".");
  }
  if (variant === "local-acceleration") {
    const y = a + "/1000*(" + cosine + ")", acceleration = -a * omega * omega + "/1000*(" + cosine + ")", curvature = -a * k * k + "/1000*(" + cosine + ")";
    return finish(setup + " At x=0,t=0, calculate displacement, transverse acceleration and spatial curvature. Does reversing only the sign of the time term change this initial acceleration?",
      [phs232Exact("displacement", "Displacement at zero", y, "m"), phs232Exact("acceleration", "Transverse acceleration at zero", acceleration, "m/s²"), phs232Exact("curvature", "Spatial curvature at zero", curvature, "1/m"), choice("reversal", "Acceleration after time-sign reversal at zero", "same", [["same", "Unchanged", "The second time derivative contains omega squared; both initial shapes and accelerations agree."], ["opposite", "Opposite sign", "The first time derivative changes sign. Differentiating twice removes that propagation sign."]])],
      ["The displacement at zero uses cos(phi). Differentiate twice instead of confusing velocity and acceleration.", "For this harmonic profile, y_tt=-omega²*y and y_xx=-k²*y.", "A second derivative with respect to time includes sigma²=1. Compare the same initial coordinate and phase."],
      ["cos(phi)=" + cosine + ", so y=" + y + " m.", "y_tt=-omega²*y=" + acceleration + " m/s² and y_xx=-k²*y=" + curvature + " 1/m.", "Their relation y_tt=c²*y_xx holds everywhere for this specified wave. At a crest, acceleration is nonzero even though transverse velocity vanishes.", "Reversing propagation preserves the t=0 displacement and acceleration, while reversing the initial transverse velocity."],
      "y=" + y + " m; y_tt=" + acceleration + " m/s²; y_xx=" + curvature + " 1/m; initial acceleration is unchanged.");
  }
  if (variant === "phase-delay") {
    const n = 4 * cycles + quarter, first = quarter || 4;
    return finish("Use y(x,t)=(" + amplitude + " m)*cos(" + k + "*x " + (direction === 1 ? "-" : "+") + " " + omega + "*t), with x in meters and t in seconds. Track the particular crest at x=0 when t=0. The downstream point is x=" + direction * n + "*pi/" + 2 * k + " m, in the wave's direction of travel. Find the tracked crest's arrival time and, separately, the first strictly positive time any crest reaches that point. Also give the unwrapped spatial phase change k*delta_x at a fixed time.",
      [phs232Pi("tracked", "Arrival time of the tracked crest", n + "*pi/" + 2 * omega, "s"), phs232Pi("first", "First strictly positive crest time at the downstream point", first + "*pi/" + 2 * omega, "s"), phs232Pi("phase", "Unwrapped spatial phase change", direction * n + "*pi/2", "rad")],
      ["The tracked crest travels the full positive downstream distance at speed c=omega/k. Do not reduce that travel time modulo a period.", "Other crests are one wavelength apart. Solve the phase congruence for the first strictly positive event at the downstream point.", quarter === 0 ? "A crest is already at the downstream point at t=0, but this event is excluded. The first allowed event is one full period later." : "The remaining downstream distance after whole wavelengths is " + quarter + "/4 of a wavelength. Its travel time is the same fraction of a period."],
      ["The full downstream distance is " + n + "*pi/" + 2 * k + " m. Dividing by c=" + c + " m/s gives t_tracked=" + n + "*pi/" + 2 * omega + " s.", "The location contains " + cycles + " whole wavelengths plus " + quarter + "/4 wavelength. Earlier crests are already between the tracked crest and this point.", "The first strictly positive local crest occurs at " + first + "*pi/" + 2 * omega + " s. The time-zero exclusion matters when the fractional distance is zero.", "The signed unwrapped spatial phase change is k*delta_x=" + direction * n + "*pi/2 rad. Replacing it by a principal phase would discard the tracked distance."],
      "Tracked arrival=" + n + "*pi/" + 2 * omega + " s; first positive crest=" + first + "*pi/" + 2 * omega + " s; unwrapped phase=" + direction * n + "*pi/2 rad.");
  }
  const candidateSpeed = mode % 2 ? 2 * c : c, residual = candidateSpeed ** 2 - c ** 2, valid = mode % 2 === 0;
  const candidate = mode < 2 ? "y=(" + amplitude + ")*cos(" + k + "*x " + (direction === 1 ? "-" : "+") + " " + k * candidateSpeed + "*t + " + phase + ")" : "y=(" + amplitude + ")*exp(-(" + k + "*(x " + (direction === 1 ? "-" : "+") + " " + candidateSpeed + "*t))²/2)";
  return finish("A uniform ideal string has mu=" + densityNumerator + "/100 kg/m and tension F_T=" + densityNumerator * c * c + "/100 N. Test the candidate " + candidate + ", using meters and seconds. Express y_tt-(F_T/mu)*y_xx as R*y_xx. Find R, decide whether the candidate solves the string equation everywhere, and find the tension that would make it a solution at the same density. Does a zero residual at one point prove the equation globally?",
    [phs232Rational("residual", "Coefficient R", String(residual), "m²/s²"), phs232Rational("tension", "Required tension for the candidate", densityNumerator * candidateSpeed * candidateSpeed + "/100", "N"),
      choice("solution", "Solution for the supplied string everywhere?", valid ? "yes" : "no", [["yes", "Yes", "The candidate's translation speed squared must equal F_T/mu, so the residual coefficient must vanish."], ["no", "No", "A nonzero coefficient multiplying a curvature that is not identically zero prevents a global solution."]]),
      choice("point", "Does one zero residual establish a global solution?", "no", [["no", "No", "Curvature can vanish at particular points even when the equation fails elsewhere."], ["yes", "Yes", "A differential equation must hold throughout the specified domain, not merely at a specially chosen point."]])],
    ["For any twice differentiable translated profile f(x-sigma*v*t), differentiate to obtain y_tt=v²*y_xx.", "The actual medium requires c²=F_T/mu. Subtract its coefficient from the candidate's v².", "To support that translation at the same density, tension must be mu*v². Check the entire profile, not only a zero of curvature."],
    ["The supplied string has c²=" + c * c + " m²/s², while the candidate translates at v=" + candidateSpeed + " m/s.", "y_tt-c²*y_xx=(" + candidateSpeed ** 2 + "-" + c ** 2 + ")*y_xx, so R=" + residual + " m²/s². The candidate " + (valid ? "does" : "does not") + " solve the supplied wave equation everywhere.", "At fixed mu, the required tension is mu*v²=" + densityNumerator * candidateSpeed * candidateSpeed + "/100 N.", "Both the nonzero cosine and Gaussian profiles have nonzero curvature somewhere. A zero at an isolated point cannot rescue a wrong medium coefficient; a Gaussian pulse does not need a harmonic frequency to satisfy the equation."],
    "R=" + residual + " m²/s²; required tension=" + densityNumerator * candidateSpeed * candidateSpeed + "/100 N; global solution=" + (valid ? "yes" : "no") + "; one point is insufficient.");
}
