import { questionSchema } from "../contracts";
import { randomFrom } from "../random";

export const phs231SampledVariants=["unequal","reversal","acceleration","work","curvature","refinement","rounding","missing-sample","units","simpson"] as const;
export const phs231SampledFamilyIds=["phs231-sampled-integration"];
const field=(id:string,label:string,expected:string,unit:string)=>({id,label,expected,unit,kind:"rational",help:"Enter an exact value or equivalent fraction in the labeled unit."});
export function phs231SampledQuestion(familyId:string,variant:string,seed:string,id:string){
  if(familyId!=="phs231-sampled-integration"||!(phs231SampledVariants as readonly string[]).includes(variant))throw Error("Unknown PHS 231 sampled-integration variant.");
  const rng=randomFrom(`${familyId}:${variant}:${seed}`);
  const base={id,familyId,familyVersion:1,courseId:"phs-231",objectiveId:"m09-l01",category:"application",critical:!["curvature","refinement","simpson"].includes(variant)};
  const choice=(id:string,label:string,correct:string,options:{id:string;label:string;feedback:string}[])=>({id,label,kind:"choice",correct,options:rng.shuffle(options)});
  const finish=(parameters:Record<string,number>,prompt:string,fields:unknown[],hints:string[],explanation:string[],answerSummary:string)=>questionSchema.parse({...base,parameters:Object.fromEntries(Object.entries(parameters).map(([k,v])=>[k,v||0])),prompt,fields,hints,explanation,answerSummary});
  if(variant==="unequal"){
    const a=rng.integer(1,3),b=rng.integer(1,4),c=rng.integer(1,3),v0=rng.integer(-6,6),v1=rng.integer(-6,6),v2=rng.integer(-6,6),v3=rng.integer(-6,6),x0=rng.integer(-5,5),n1=a*(v0+v1),n2=b*(v1+v2),n3=c*(v2+v3),sum=n1+n2+n3;
    return finish({a,b,c,v0,v1,v2,v3,x0},`A synthetic velocity table has times [0, ${a}, ${a+b}, ${a+b+c}] s and signed velocities [${v0}, ${v1}, ${v2}, ${v3}] m/s. The model explicitly connects consecutive samples by straight lines. Initial position is ${x0} m. Find each signed displacement, total displacement, and final position.`,
      [field("first","First interval displacement",`${n1}/2`,"m"),field("second","Second interval displacement",`${n2}/2`,"m"),field("third","Third interval displacement",`${n3}/2`,"m"),field("displacement","Total signed displacement",`${sum}/2`,"m"),field("position","Final position",`${2*x0+sum}/2`,"m"),choice("meaning","Meaning of the signed sum","displacement",[
        {id:"displacement",label:"Signed displacement under the supplied interpolation; it need not equal distance",feedback:"Integrating signed velocity accumulates displacement. Negative and positive contributions can cancel even when motion occurred."},
        {id:"distance",label:"Total distance because every velocity sample was used",feedback:"Distance requires integrating speed and handling any zero crossing inside an interval. Sampling every listed endpoint does not remove signs."},
        {id:"average",label:"Average velocity because the velocities were averaged",feedback:"Each mean velocity is multiplied by its own time width. The resulting sum has meters, not meters per second."}
      ])],["Subtract consecutive timestamps to get each width.","For each linear segment use its endpoint mean velocity times its own width; retain signs.","Add initial position only after accumulating displacement. Distance would require a separate speed integral."],
      [`The three widths are ${a}, ${b}, and ${c} s. Their signed areas are ${n1}/2, ${n2}/2, and ${n3}/2 m.`,`The displacement is ${sum}/2 m; adding x0 gives final position ${2*x0+sum}/2 m.`,"The interpolation is supplied explicitly, so these areas are exact for this synthetic piecewise-linear model. They are not proof of unknown motion between real samples."],
      `Displacements ${n1}/2, ${n2}/2, ${n3}/2 m; total ${sum}/2 m; final position ${2*x0+sum}/2 m.`);
  }
  if(variant==="reversal"){
    const T=rng.integer(2,8),p=rng.integer(1,6),q=rng.integer(1,6),den=p+q;
    return finish({T,p,q},`Over 0≤t≤${T} s, a supplied velocity is linear from +${p} m/s to −${q} m/s. Find the reversal time, signed displacement, distance traveled, and the excess in a trapezoid formed directly from the two endpoint speeds.`,
      [field("zero","Reversal time",`${T*p}/${den}`,"s"),field("displacement","Signed displacement",`${T*(p-q)}/2`,"m"),field("distance","Distance traveled",`${T*(p*p+q*q)}/${2*den}`,"m"),field("excess","Endpoint-speed trapezoid minus actual distance",`${T*p*q}/${den}`,"m"),choice("rule","How should the speed area be computed?","split",[
        {id:"split",label:"Split at the within-interval zero and add the two positive triangular areas",feedback:"The absolute value of a crossing linear velocity is V-shaped, not one straight segment between the endpoint speeds."},
        {id:"absolute",label:"Take the absolute value of the signed displacement",feedback:"Opposite-direction displacement can cancel. Its absolute value omits some traveled distance."},
        {id:"endpoints",label:"Use one trapezoid joining the endpoint speeds without a split",feedback:"That line lies above the V-shaped speed graph, producing the positive excess requested here."}
      ])],["The velocity decreases by p+q over the whole interval; reaching zero takes the fraction p/(p+q).","Displacement uses the signed trapezoid. Distance uses separate triangles on each side of the zero.","Subtract the two-triangle distance from T(p+q)/2 to find the endpoint-speed overestimate."],
      [`The zero occurs at ${T*p}/${den} s. Signed displacement is ${T*(p-q)}/2 m.`,`Adding positive triangular areas gives ${T*(p*p+q*q)}/${2*den} m. The endpoint-speed trapezoid is ${T*den}/2 m, exceeding the distance by ${T*p*q}/${den} m.`,"The distinction persists when the endpoint velocities have equal magnitude: displacement is then zero but distance is positive."],
      `Reversal ${T*p}/${den} s; displacement ${T*(p-q)}/2 m; distance ${T*(p*p+q*q)}/${2*den} m; excess ${T*p*q}/${den} m.`);
  }
  if(variant==="acceleration"||variant==="work"){
    const a=rng.integer(1,3),b=rng.integer(1,4),y0=rng.integer(-4,5),y1=rng.integer(-4,5),y2=rng.integer(-4,5),v0=rng.integer(-8,8),n1=a*(y0+y1),n2=b*(y1+y2),sum=n1+n2,acceleration=variant==="acceleration";
    return finish({a,b,y0,y1,y2,v0},acceleration?`An explicitly piecewise-linear acceleration record gives [${y0}, ${y1}, ${y2}] m/s² at times [0, ${a}, ${a+b}] s. Initial velocity is ${v0} m/s. Find the velocity change in each interval, final velocity, and average acceleration over the record.`:`A supplied force component along increasing x is piecewise linear through positions [0, ${a}, ${a+b}] m with signed values [${y0}, ${y1}, ${y2}] N. Find its work in each interval, total work, and mean force over this traveled position interval. This is one applied force, not necessarily the net force.`,
      [field("first",acceleration?"First velocity change":"First interval work",`${n1}/2`,acceleration?"m/s":"J"),field("second",acceleration?"Second velocity change":"Second interval work",`${n2}/2`,acceleration?"m/s":"J"),field("total",acceleration?"Final velocity":"Total work",`${acceleration?2*v0+sum:sum}/2`,acceleration?"m/s":"J"),field("average",acceleration?"Average acceleration":"Mean force",`${sum}/${2*(a+b)}`,acceleration?"m/s²":"N"),choice("interpretation","What does this integral establish?",acceleration?"change":"one-force",[
        {id:acceleration?"change":"one-force",label:acceleration?"Acceleration area gives velocity change; the initial velocity is still needed":"This force's work; kinetic-energy change needs the net work of all forces",feedback:acceleration?"Integrating a derivative supplies a change. Add the supplied initial value once.":"The work-energy theorem uses net work. A single applied force need not be the whole force inventory."},
        {id:"direct",label:acceleration?"Acceleration area alone is the final velocity":"This force's work alone is always the change in kinetic energy",feedback:acceleration?"That omits the initial velocity, which may be nonzero.":"Other forces can also do work. The prompt does not identify this component as the net force."},
        {id:"units",label:acceleration?"Acceleration area is displacement":"Force-position area is impulse",feedback:acceleration?"Acceleration times time has velocity units. Displacement would require a velocity integral.":"Force times position has energy units. Impulse instead integrates force over time."}
      ])],["Compute each actual interval width.","Multiply each width by its signed mean endpoint ordinate.","Divide the summed integral by the total interval for its mean rate or force. Add the initial value only for a final-state request."],
      [`The signed interval integrals are ${n1}/2 and ${n2}/2 ${acceleration?"m/s":"J"}.`,acceleration?`Adding initial velocity gives (${2*v0}+${sum})/2=${2*v0+sum}/2 m/s. Average acceleration is ${sum}/${2*(a+b)} m/s².`:`Total work is ${sum}/2 J and mean force is ${sum}/${2*(a+b)} N. This is the work of the stated force, not an unstated net-force claim.`],
      `Interval integrals ${n1}/2 and ${n2}/2; ${acceleration?"final velocity":"total work"} ${acceleration?2*v0+sum:sum}/2; mean ${sum}/${2*(a+b)} in the labeled units.`);
  }
  if(variant==="curvature"){
    const A=rng.integer(-2,5),B=rng.integer(-2,5),C=rng.integer(1,3),T=rng.integer(2,6),N=rng.integer(2,6),I=6*A*T+3*B*T*T+2*C*T*T*T,err=C*T*T*T,den=6*N*N;
    return finish({A,B,C,T,N},`The exact synthetic velocity law is v(t)=${A}+(${B})t+${C}t² in m/s when t is in seconds. Over [0,${T}] s use N=${N} equal trapezoid intervals. Find the exact displacement, trapezoid approximation, signed approximation-minus-exact error, and error after doubling N. Coefficients carry the corresponding SI time powers.`,
      [field("exact","Exact displacement",`${I}/6`,"m"),field("approximation","Trapezoid displacement",`${I*N*N+err}/${den}`,"m"),field("error","Trapezoid minus exact displacement",`${err}/${den}`,"m"),field("refined","Error with twice as many intervals",`${err}/${4*den}`,"m"),choice("cause","Source of this computed difference","quadrature",[
        {id:"quadrature",label:"Quadrature error for the supplied exact polynomial; halving the uniform step quarters this error",feedback:"The exact polynomial and exact samples remove measurement uncertainty from this comparison. The trapezoid error is proportional to h² here."},
        {id:"measurement",label:"An experimentally measured sensor bias",feedback:"These values are generated from a supplied exact function. No sensor measurement or bias observation was supplied."},
        {id:"probability",label:"A probability that the displacement is incorrect",feedback:"The difference is a deterministic signed numerical error in meters, not a probability."}
      ])],["Integrate A, Bt, and Ct² separately over the given interval.","For a quadratic, the uniform trapezoid error is C*T³/(6*N²); alternatively sum all endpoint trapezoids independently.","Replacing N by 2N multiplies that denominator by four. The positive curvature makes the signed error positive."],
      [`Direct integration gives ${I}/6 m. Summing endpoint means gives ${I*N*N+err}/${den} m.`,`Their difference is ${err}/${den} m. With twice as many intervals it is ${err}/${4*den} m.`,`The second derivative is 2C=${2*C} m/s³; M*T³/(12*N²) equals this error magnitude. A similar bound for unknown data would require justified smoothness and a derivative bound.`],
      `Exact ${I}/6 m; trapezoid ${I*N*N+err}/${den} m; error ${err}/${den} m; refined error ${err}/${4*den} m.`);
  }
  if(variant==="refinement"){
    const A=rng.integer(-5,10),C=(rng.integer(0,1)?1:-1)*rng.integer(1,9),order=rng.integer(1,2),r=2**order;
    return finish({A,C,order},`At the same physical endpoint, a synthetic calculation returns Q(h)=${A+C}, Q(h/2)=${A*r+C}/${r}, and Q(h/4)=${A*r*r+C}/${r*r} m. For this exercise the error relation Q(s)=Qstar+C0*s^p is explicitly exact with a nonzero fixed C0 and positive integer p. Find the successive signed differences, their ratio, inferred p, Qstar, and the finest absolute error.`,
      [field("first","Q(h) minus Q(h/2)",`${C*(r-1)}/${r}`,"m"),field("second","Q(h/2) minus Q(h/4)",`${C*(r-1)}/${r*r}`,"m"),field("ratio","Ratio of successive differences",String(r),"1"),field("order","Inferred order p",String(order),"1"),field("limit","Extrapolated Qstar",String(A),"m"),field("error","Finest absolute error",`${Math.abs(C)}/${r*r}`,"m"),choice("scope","What makes the extrapolation exact here?","supplied",[
        {id:"supplied",label:"The exact supplied power-error relation; a general computation would need evidence for that regime",feedback:"Three values alone do not make a universal rigorous error bound. This exercise explicitly supplies the form that permits the exact extrapolation."},
        {id:"always",label:"Three refinements always prove the exact physical answer",feedback:"Convergence of a chosen numerical model does not validate its physical assumptions, and its asymptotic error form need not hold at arbitrary steps."},
        {id:"confidence",label:"The ratio supplies a statistical confidence level",feedback:"No probability model is supplied. This is a deterministic scaling calculation."}
      ])],["Subtract the two successive pairs, keeping their signs.","Their ratio is 2^p when the same nonzero leading coefficient and exact power law apply.","Subtract the last difference divided by 2^p−1 from the finest approximation; then take an absolute error."],
      [`The signed differences are ${C*(r-1)}/${r} and ${C*(r-1)}/${r*r} m, so their ratio is ${r}=2^${order}.`,`Extrapolation gives Qstar=${A} m, and the finest absolute error is ${Math.abs(C)}/${r*r} m.`,"This exact result depends on the supplied model for numerical error. Equal approximations or changing leading terms would require different reasoning; no physical uncertainty is inferred."],
      `Ratio ${r}; p=${order}; Qstar=${A} m; finest error ${Math.abs(C)}/${r*r} m.`);
  }
  if(variant==="rounding"){
    const a=rng.integer(1,3),b=rng.integer(1,4),v0=rng.integer(-5,5),v1=rng.integer(-5,5),v2=rng.integer(-5,5),q=[1,2,5][rng.integer(0,2)],sum=a*(v0+v1)+b*(v1+v2),bound=(a+b)*q;
    return finish({a,b,v0,v1,v2,q},`Exact timestamps are [0,${a},${a+b}] s. Displayed velocities are [${v0},${v1},${v2}] m/s, each rounded to the nearest ${q}/10 m/s. All endpoint rounding errors are allowed. Assume linear interpolation of the true endpoint velocities and no additional drift or timing error. Find the displayed trapezoid displacement, maximum rounding-error magnitude, and smallest/largest allowed true displacement.`,
      [field("estimate","Displayed trapezoid displacement",`${sum}/2`,"m"),field("bound","Maximum rounding-error magnitude",`${bound}/20`,"m"),field("lower","Smallest allowed displacement",`${10*sum-bound}/20`,"m"),field("upper","Largest allowed displacement",`${10*sum+bound}/20`,"m"),choice("meaning","Meaning of this interval","bounded",[
        {id:"bounded",label:"A deterministic allowed interval under the stated rounding and interpolation assumptions",feedback:"Positive trapezoid weights let every endpoint error reinforce at one bound. No distribution or confidence level has been supplied."},
        {id:"confidence",label:"A 95% confidence interval because three measurements were used",feedback:"Rounding bounds and sample count do not establish a probability distribution or coverage level."},
        {id:"halve",label:"A bound that must halve when the same line is plotted with twice as many interpolated points",feedback:"Interpolated display points are not new observations. They do not reduce the original endpoint uncertainty."}
      ])],["Each endpoint velocity can differ from its display by at most half the stated rounding step.","The velocity weights are a/2, (a+b)/2, and b/2 seconds; their sum is the total duration.","Multiply their positive sum by the common velocity-error bound, then subtract/add it to the displayed estimate."],
      [`The estimate is ${sum}/2 m. Weights ${a}/2, ${a+b}/2, and ${b}/2 s sum to ${a+b} s.`,`Each velocity error is bounded by ${q}/20 m/s, giving displacement error at most ${bound}/20 m. The resulting interval is [${10*sum-bound}/20,${10*sum+bound}/20] m.`,"All allowed errors may have the same sign, so adding bounds is appropriate. The calculation excludes any uncertainty not stated in the prompt."],
      `Estimate ${sum}/2 m; bound ${bound}/20 m; allowed displacement [${10*sum-bound}/20,${10*sum+bound}/20] m.`);
  }
  if(variant==="missing-sample"){
    const T=rng.integer(1,6),v=rng.integer(-3,3);
    return finish({T,v},`Two observations give v(0)=v(${T})=${v} m/s. There is no supplied interpolation law, intermediate observation, or acceleration bound. Compute the endpoint trapezoid approximation and decide what it establishes about the actual displacement and distance.`,
      [field("approximation","Endpoint trapezoid approximation",String(v*T),"m"),choice("claim","Actual motion between the samples","unknown",[
        {id:"unknown",label:"The approximation is known, but actual displacement and distance are not fixed by these two observations",feedback:"Different continuous velocity curves can share the same endpoints and have different signed and absolute integrals."},
        {id:"constant",label:"The velocity must have been constant because its endpoint values match",feedback:"Equal endpoint values do not exclude intermediate acceleration or reversal."},
        {id:"distance",label:"The absolute approximation is the exact distance traveled",feedback:"Even an exact displacement would not fix distance if reversals occurred. Here the interior velocity itself is unspecified."}
      ]),choice("repair","Useful additional evidence","observations",[
        {id:"observations",label:"Additional independent time samples or a justified bound/model for the interior behavior",feedback:"These can constrain what happened between endpoints. Any interpolation assumption should remain explicit."},
        {id:"pixels",label:"More points interpolated from the same two observations",feedback:"That draws the assumed line more finely without adding information about the actual trajectory."},
        {id:"digits",label:"More displayed decimal places for the same two numbers",feedback:"Formatting cannot supply missing intermediate behavior or improve the original measurement resolution."}
      ])],["The endpoint rule gives T times the shared velocity.","Imagine adding a smooth hump that vanishes at both endpoints; the observations stay the same but the integral changes.","Distinguish a new observation from a point calculated by interpolation."],
      [`The trapezoid approximation is ${T}(${v})=${T*v} m.`,`For example, v(t)=${v}+A*t*(${T}−t), with A carrying the needed units, shares both endpoint values but changes displacement by A*${T**3}/6.`,"Thus neither actual displacement nor actual distance is established. New independent evidence or a justified model is needed."],
      `Trapezoid approximation ${T*v} m; actual displacement and distance remain unestablished from endpoints alone.`);
  }
  if(variant==="units"){
    const a=rng.integer(1,4),b=rng.integer(1,5),v0=10*rng.integer(-6,6),v1=10*rng.integer(-6,6),v2=10*rng.integer(-6,6),sum=a*(v0+v1)+b*(v1+v2);
    return finish({a,b,v0,v1,v2},`A synthetic table gives times [0,${200*a},${200*(a+b)}] milliseconds and velocities [${v0},${v1},${v2}] centimeters per second, with explicitly linear interpolation. Express the duration, initial velocity, signed displacement, and average velocity in SI units.`,
      [field("duration","Total duration",`${a+b}/5`,"s"),field("velocity","Initial velocity",`${v0}/100`,"m/s"),field("displacement","Signed displacement",`${sum}/1000`,"m"),field("average","Average velocity",`${sum}/${200*(a+b)}`,"m/s")],
      ["Convert milliseconds by 1/1000 and centimeters by 1/100 before combining units.","Use each actual time width with its endpoint mean velocity.","Average velocity is signed displacement divided by total elapsed time, not the unweighted average of all three samples."],
      [`Duration is ${a+b}/5 s and initial velocity ${v0}/100 m/s.`,`The trapezoid sum is [${a}(${v0+v1})+${b}(${v1+v2})]/1000=${sum}/1000 m.`,`Dividing by duration gives ${sum}/${200*(a+b)} m/s. Unequal time intervals require time weighting.`],
      `Duration ${a+b}/5 s; initial velocity ${v0}/100 m/s; displacement ${sum}/1000 m; average ${sum}/${200*(a+b)} m/s.`);
  }
  const h=rng.integer(1,3),equal=rng.integer(0,1),factor=equal?2:3,A=rng.integer(-3,5),B=rng.integer(-3,5),C=rng.integer(1,3),v0=A,v1=A+B*h+C*h*h,v2=A+B*factor*h+C*factor*factor*h*h;
  const trap=h*((v0+v1)+(factor-1)*(v1+v2)),simpson=h*(v0+4*v1+v2);
  return finish({h,equal,factor,A,B,C,v0,v1,v2},`A synthetic velocity table gives times [0,${h},${factor*h}] s and velocities [${v0},${v1},${v2}] m/s. The underlying supplied law is v(t)=${A}+(${B})t+${C}t² m/s. Compute the two-interval trapezoid approximation. ${equal?"Also compute the standard three-point Simpson 1/3 approximation.":"Do not apply a standard equal-step Simpson formula to unequal intervals."} Decide which statement is justified.`,
    [field("trapezoid","Two-interval trapezoid approximation",`${trap}/2`,"m"),...(equal?[field("simpson","Three-point Simpson approximation",`${simpson}/3`,"m")]:[]),choice("spacing","Spacing and exactness",equal?"exact":"unequal",[
      {id:"exact",label:"Equal spacing permits standard Simpson 1/3; it integrates this supplied quadratic exactly",feedback:equal?"The three nodes form two equal intervals. The 1:4:1 weights with h/3 integrate this exact quadratic.":"The second interval is twice the first. The standard equal-step 1:4:1 formula does not apply to these three nodes."},
      {id:"unequal",label:"The grid is unequal; its standard equal-step Simpson calculation would be invalid",feedback:equal?"Both intervals have the same width. The supplied quadratic is within Simpson's polynomial exactness.":"Correct: use actual interval widths for the trapezoid. An unequal-node quadratic interpolatory rule would require separately derived weights."},
      {id:"any",label:"Three points always justify standard Simpson weights regardless of timestamps",feedback:"The usual three-point formula assumes equal spacing. The number of points alone does not establish its domain."}
    ])],
    ["Check both adjacent timestamp differences before choosing a formula.","The trapezoid uses a separate mean and width for each interval.","For two equal intervals of width h, Simpson is h(v0+4v1+v2)/3. Polynomial exactness does not remove measurement uncertainty in a different measured-data problem."],
    [`The trapezoid uses widths ${h} and ${(factor-1)*h} s, giving ${trap}/2 m.`,equal?`The equally spaced Simpson result is ${simpson}/3 m, agreeing with the independently integrated supplied quadratic.`:"The node spacing is unequal. Do not silently apply the uniform-step Simpson weights; no Simpson number is requested for this invalid use.","The exactness claim applies to the supplied polynomial with exact samples, not to arbitrary unknown or noisy interior behavior."],
    `Trapezoid ${trap}/2 m; ${equal?`Simpson ${simpson}/3 m is exact for this supplied quadratic`:"standard equal-step Simpson is inapplicable to the unequal grid"}.`);
}
