import { questionSchema } from "../contracts";
import { randomFrom } from "../random";

export const phs231MaterialEvidenceVariants=["units","slope","landmarks","unloading","energy","offset","comparison","true-stress","inverse","measurement"] as const;
export const phs231MaterialEvidenceFamilyIds=["phs231-material-evidence"];
const field=(id:string,label:string,expected:string,unit:string)=>({id,label,expected,unit,kind:"rational",help:"Enter an exact value or equivalent fraction in the labeled unit."});
export function phs231MaterialEvidenceQuestion(familyId:string,variant:string,seed:string,id:string){
  if(familyId!=="phs231-material-evidence"||!(phs231MaterialEvidenceVariants as readonly string[]).includes(variant))throw Error("Unknown PHS 231 material-evidence variant.");
  const rng=randomFrom(`${familyId}:${variant}:${seed}`);
  const base={id,familyId,familyVersion:1,courseId:"phs-231",objectiveId:"m08-l03",category:"application",critical:variant!=="slope"&&variant!=="comparison"};
  const choice=(id:string,label:string,correct:string,options:{id:string;label:string;feedback:string}[])=>({id,label,kind:"choice",correct,options:rng.shuffle(options)});
  const finish=(parameters:Record<string,number>,prompt:string,fields:unknown[],hints:string[],explanation:string[],answerSummary:string)=>questionSchema.parse({...base,parameters:Object.fromEntries(Object.entries(parameters).map(([key,value])=>[key,value||0])),prompt,fields,hints,explanation,answerSummary});
  const record=()=>{const E=50*rng.integer(1,4),S=50*rng.integer(1,4),hy=rng.integer(4,8),hf=hy+rng.integer(2,6),u=rng.integer(2,3),t=rng.integer(1,2*u);return {E,S,hy,hf,u,t};};
  const points=(p:ReturnType<typeof record>)=>`The synthetic engineering (strain, stress in MPa) vertices are (0, 0), (${p.S}/${1000*p.E}, ${p.S}), (${p.hy*p.S}/${1000*p.E}, ${p.u*p.S}), and (${p.hf*p.S}/${1000*p.E}, ${p.t*p.S}/2). Straight segments join consecutive points under prescribed increasing extension.`;
  if(variant==="units"){
    const F=50*rng.integer(1,30),A=rng.integer(2,10),L=25*rng.integer(2,8),d=rng.integer(1,20);
    return finish({F,A,L,d},`A synthetic tensile record gives internal force ${F} N, original area ${A} mm², original gauge length ${L} mm, and extension ${d}/10 mm. Find engineering stress, dimensionless engineering strain, its percentage, and current gauge length. The opposite end forces balance externally.`,
      [field("stress","Engineering normal stress",`${F}/${A}`,"MPa"),field("strain","Engineering strain",`${d}/${10*L}`,"dimensionless"),field("percent","Engineering strain in percent",`${10*d}/${L}`,"%"),field("length","Current gauge length",`${10*L+d}/10`,"mm"),choice("area","Stress convention","original",[
        {id:"original",label:"Use original area and one internal force, even when the external resultant is zero",feedback:"Engineering stress is internal force divided by original area. Whole-specimen equilibrium does not remove internal stress."},
        {id:"current",label:"Engineering stress must use the current neck area",feedback:"Current area defines a different stress measure. It has not been supplied and cannot replace the original area in engineering stress."},
        {id:"net",label:"The engineering stress is zero because the opposite end forces cancel",feedback:"A cut isolates one side with a nonzero internal force. Zero external resultant allows a stressed specimen to remain in equilibrium."}
      ])],
      ["N/mm² equals MPa. Do not add the two opposite end-force magnitudes.","Divide extension by original length in the same unit. Multiply dimensionless strain by 100 to express percent.","Current length is original length plus extension; L/L0 is one plus strain."],
      [`Stress=${F}/${A} MPa, and ε=(${d}/10)/${L}=${d}/${10*L}.`,`The percentage is ${10*d}/${L}%, while current length is ${10*L+d}/10 mm. A percent axis and a dimensionless strain axis differ by 100.`,"The original area defines the engineering measure. Local stress at a neck requires additional geometry and stress-state evidence."],
      `Engineering stress ${F}/${A} MPa; strain ${d}/${10*L}; percentage ${10*d}/${L}%; current length ${10*L+d}/10 mm; use original area.`);
  }
  if(variant==="slope"){
    const {E,S,hy,u}=record();
    return finish({E,S,hy,u},`A synthetic curve is linear from the origin to (strain ${S}/${1000*E}, stress ${S} MPa), then linear to (${hy*S}/${1000*E}, ${u*S} MPa). Find its initial modulus, secant modulus from the origin to the second point, and tangent modulus on the second segment. Decide whether these slopes alone establish residual deformation.`,
      [field("initial","Initial modulus",String(E),"GPa"),field("secant","Secant modulus to the second point",`${u*E}/${hy}`,"GPa"),field("tangent","Second-segment tangent modulus",`${E*(u-1)}/${hy-1}`,"GPa"),choice("history","What does the loading record establish?","unloading",[
        {id:"unloading",label:"The slopes differ; an unloading law or observations are still needed to establish residual strain",feedback:"A nonlinear loading response can be reversible. Residual strain depends on the path followed when load is removed."},
        {id:"plastic",label:"Any change of slope proves permanent deformation",feedback:"Proportionality and elastic recovery are different properties. A nonlinear elastic material can recover along its loading curve."},
        {id:"fracture",label:"The smaller tangent modulus proves the sample has fractured",feedback:"A changed slope is not a recorded fracture event. The stated curve remains a loading record of an intact specimen."}
      ])],
      ["Initial modulus is the first stress divided by its strain.","Secant uses total stress divided by total strain; tangent on a straight segment uses differences.","Convert MPa to GPa by dividing by 1000. A slope is not an unloading history."],
      [`Initial E=${E} GPa. The second point gives secant modulus (${u*S})/(${hy*S}/${1000*E})/1000=${u*E}/${hy} GPa.`,`The segment's stress increment is ${(u-1)*S} MPa and strain increment ${(hy-1)*S}/${1000*E}, so its tangent modulus is ${E*(u-1)}/${hy-1} GPa.`,"The two definitions answer different questions. Neither the final secant nor the second-segment tangent replaces the initial modulus; unloading evidence is needed for a permanent-set claim."],
      `Initial ${E} GPa; secant ${u*E}/${hy} GPa; tangent ${E*(u-1)}/${hy-1} GPa; residual deformation remains undetermined from this loading record alone.`);
  }
  if(variant==="landmarks"){
    const p=record(),documented=rng.integer(0,1),{E,S,hf,u,t}=p;
    return finish({...p,documented},`${points(p)} The first nonzero vertex is explicitly designated the supplied yield point. ${documented?"The final vertex is a documented fracture event.":"The recording stops at the final vertex; no fracture observation is supplied."} Find the initial modulus, supplied yield stress, maximum engineering stress, last recorded stress, and last recorded strain in percent. Interpret the endpoint.`,
      [field("modulus","Initial modulus",String(E),"GPa"),field("yield","Supplied yield stress",String(S),"MPa"),field("ultimate","Maximum recorded engineering stress",String(u*S),"MPa"),field("last","Last recorded engineering stress",`${t*S}/2`,"MPa"),field("percent","Last recorded strain in percent",`${hf*S}/${10*E}`,"%"),choice("endpoint","Endpoint evidence",documented?"fracture":"unknown",[
        {id:"fracture",label:"The supplied observation identifies fracture at the final vertex",feedback:documented?"The endpoint is explicitly documented as fracture. Its stress may differ from the maximum engineering stress reached earlier.":"Recording ended without a fracture observation. A graph endpoint alone does not establish fracture."},
        {id:"unknown",label:"The final point is only the end of the available record; fracture is not established",feedback:documented?"This problem explicitly supplies a fracture observation. Use that evidence while keeping its stress separate from the maximum.":"Correct: an instrument may stop recording for many reasons. Do not turn the last data point into an unobserved event."},
        {id:"maximum",label:"Fracture always occurs at the maximum engineering stress",feedback:"Maximum engineering stress and fracture stress are distinct descriptors. A ductile specimen can continue deforming on a descending engineering curve before breaking."}
      ])],
      ["Compute the first straight-segment slope; use the explicitly supplied yield designation rather than inferring it from slope alone.","Inspect every stress value for the maximum, including a possible tie. The final stress need not be the maximum.","Multiply the final dimensionless strain by 100 and read the supplied event description."],
      [`Initial modulus ${E} GPa and supplied yield stress ${S} MPa describe different properties. The maximum engineering stress is ${u*S} MPa, while the last recorded stress is ${t*S}/2 MPa.`,`Last recorded strain is ${hf*S}/${10*E}%. ${documented?"The problem documents fracture there.":"No fracture event is established by the supplied record."}`,"Ultimate tensile strength denotes a maximum on a complete tensile record; when only a partial record is supplied, the measured maximum need not be the eventual ultimate strength."],
      `E=${E} GPa; supplied yield=${S} MPa; recorded maximum=${u*S} MPa; final stress=${t*S}/2 MPa; final strain=${hf*S}/${10*E}%; endpoint ${documented?"documents fracture":"does not establish fracture"}.`);
  }
  if(variant==="unloading"){
    const {E,S,hy,u}=record(),r=rng.integer(0,6),L=25*rng.integer(2,8),a=6+(u-1)*r,b=6+(hy-1)*r;
    const loss=36+(hy-1)*r*(12+(u-1)*r)-a*a;
    return finish({E,S,hy,u,r,L},`A hypothetical specimen has gauge length ${L} mm. Its loading curve is linear through (0,0), (strain ${S}/${1000*E}, stress ${S} MPa), and (${hy*S}/${1000*E}, ${u*S} MPa). Load it to strain ${b*S}/${6000*E}, strictly before any fracture. A supplied unloading law is a straight line of slope ${E} GPa to zero stress, then stops. Calculate peak stress, residual strain, permanent extension, returned work per original volume, and the part of loading work not returned.`,
      [field("stress","Peak engineering stress",`${a*S}/6`,"MPa"),field("residual","Residual engineering strain",`${(hy-u)*r*S}/${6000*E}`,"dimensionless"),field("extension","Permanent gauge extension",`${(hy-u)*r*S*L}/${6000*E}`,"mm"),field("returned","Returned work per original volume",`${a*a*S*S}/${72000*E}`,"MJ/m³"),field("unreturned","Nonreturned work per original volume",`${loss*S*S}/${72000*E}`,"MJ/m³"),choice("energy","Energy interpretation","account",[
        {id:"account",label:"Nonreturned work is an energy account under this unloading law; its full conversion to heat is not established",feedback:"Loading work minus returned work can include heat and changes of internal structure or other stored energy. The supplied curve alone does not partition those mechanisms."},
        {id:"heat",label:"Every part of nonreturned work must have become heat immediately",feedback:"A work difference does not measure temperature or distinguish hardening energy and other internal changes. A thermal model or observations are needed."},
        {id:"all-elastic",label:"The whole area under loading is recoverable elastic energy",feedback:"The area under the supplied unloading path is the recoverable part. Loading area alone includes work that this unloading law does not return."}
      ])],
      ["Interpolate the loading segment at the requested peak strain.","The unloading line reaches zero at εres=εpeak−σpeak/E; multiply by original length for permanent extension.","Integrate the loading pieces. Returned work is the unloading triangle σpeak²/(2E); subtract it from loading work, using MPa=MJ/m³."],
      [`Interpolation gives peak stress ${a*S}/6 MPa. Its recovered strain is ${a*S}/${6000*E}; subtracting from total strain ${b*S}/${6000*E} gives residual strain ${(hy-u)*r*S}/${6000*E}.`,`Permanent extension is ${(hy-u)*r*S*L}/${6000*E} mm. The returned triangle is ${a*a*S*S}/${72000*E} MJ/m³.`,`Loading area is ${(36+(hy-1)*r*(12+(u-1)*r))*S*S}/${72000*E} MJ/m³. Subtracting the returned triangle leaves ${loss*S*S}/${72000*E} MJ/m³ unreturned under this supplied law.`,"No unspecified compressive continuation is added after zero load. Nonreturned work is not automatically a measured quantity of heat."],
      `Peak stress ${a*S}/6 MPa; residual ${(hy-u)*r*S}/${6000*E}; permanent extension ${(hy-u)*r*S*L}/${6000*E} mm; returned ${a*a*S*S}/${72000*E} and unreturned ${loss*S*S}/${72000*E} MJ/m³.`);
  }
  if(variant==="energy"){
    const p=record(),{E,S,hy,hf,u,t}=p,A=rng.integer(2,10),L=25*rng.integer(2,8),total=2+2*(1+u)*(hy-1)+(2*u+t)*(hf-hy);
    return finish({...p,A,L},`${points(p)} The final vertex is documented fracture. Original gauge length is ${L} mm and area ${A} mm². Integrate each segment using its actual strain width, then find total loading work per original volume and total specimen work. No unloading curve is supplied.`,
      [field("first","First segment work density",`${S*S}/${2000*E}`,"MJ/m³"),field("second","Second segment work density",`${(1+u)*(hy-1)*S*S}/${2000*E}`,"MJ/m³"),field("third","Third segment work density",`${(2*u+t)*(hf-hy)*S*S}/${4000*E}`,"MJ/m³"),field("total","Work to fracture per original volume",`${total*S*S}/${4000*E}`,"MJ/m³"),field("work","Total loading work to fracture",`${total*S*S*A*L}/${4000000*E}`,"J"),choice("meaning","What does the integrated area mean?","work",[
        {id:"work",label:"Mechanical input work per original volume along this documented loading path",feedback:"Engineering stress times engineering-strain increment equals F d(delta)/(A0 L0). Its integral gives input work per original volume."},
        {id:"stored",label:"All this area remains stored as recoverable elastic energy",feedback:"Recoverable work requires an unloading law. Plasticity and fracture can make much of the input work nonrecoverable."},
        {id:"intensity",label:"The numerical area is the crack fracture toughness KIc",feedback:"This area has energy-per-volume units. KIc has stress times square-root-length units and needs separate fracture evidence."}
      ])],
      ["Each straight segment contributes its mean endpoint stress times its strain width.","Add the three areas without treating unequal strain intervals as equal.","Multiply MJ/m³ by reference volume in cm³ to get J; A in mm² times L in mm gives mm³, which must be divided by 1000 for cm³."],
      [`The three areas are ${S*S}/${2000*E}, ${(1+u)*(hy-1)*S*S}/${2000*E}, and ${(2*u+t)*(hf-hy)*S*S}/${4000*E} MJ/m³.`,`Their sum is ${total*S*S}/${4000*E} MJ/m³. Reference volume is ${A*L}/1000 cm³, so total work is ${total*S*S*A*L}/${4000000*E} J.`,"The final point is an observed event in this hypothetical record. The integral supplies work to that event, not an invented connected unloading path or a crack-toughness property."],
      `Total work density ${total*S*S}/${4000*E} MJ/m³ and specimen work ${total*S*S*A*L}/${4000000*E} J; the area represents input work.`);
  }
  if(variant==="offset"){
    const E=25*rng.integer(2,6),S=50*rng.integer(2,6),hy=rng.integer(6,10),u=rng.integer(2,3),D=hy-u,eps=S*D+2*E*(hy-1),stress=S*D+2*E*(u-1);
    return finish({E,S,hy,u},`A supplied synthetic record is linear from (0,0) to (strain ${S}/${1000*E}, stress ${S} MPa), then to (${hy*S}/${1000*E}, ${u*S} MPa). Find the intersection with a 0.2% offset proof line parallel to the initial slope. Report intersection strain, proof stress, and the line's zero-stress strain intercept. Use the segment only if the intersection lies on it.`,
      [field("strain","Intersection engineering strain",`${eps}/${1000*E*D}`,"dimensionless"),field("stress","0.2 percent offset proof stress",`${stress}/${D}`,"MPa"),field("offset","Proof-line zero-stress intercept","1/500","dimensionless"),choice("definition","Meaning of the offset stress","convention",[
        {id:"convention",label:"A specified proof-stress convention, which can differ from the first onset of plasticity",feedback:"The construction uses a chosen residual-strain offset. It need not identify the exact first departure from recoverable behavior."},
        {id:"percent",label:"The line begins at strain 0.2, meaning twenty percent",feedback:"0.2% equals 0.002 dimensionless strain. Using 0.2 shifts the proof line by a factor of 100 too much."},
        {id:"ultimate",label:"The intersection is necessarily the ultimate tensile strength",feedback:"An offset proof stress and maximum engineering stress are different definitions. They need not occur at the same point."}
      ])],
      ["Convert 0.2% to 0.002. The proof line is σ=1000E(ε−0.002) with E in GPa and σ in MPa.","Write the hardening segment as a line through its two vertices and equate it to the proof line.","Check the strain falls between the two segment endpoints. Substitution into each line must give the same stress."],
      [`The hardening slope is ${1000*E*(u-1)}/${hy-1} MPa. Equating that segment with σ=${1000*E}(ε−0.002) gives ε=${eps}/${1000*E*D}.`,`Substitution gives proof stress ${stress}/${D} MPa. The intersection is on the supplied hardening segment because 2E≤(hy−u)S for these data.`,"The zero-stress intercept is 1/500 strain. This construction is a specified offset convention, not a measurement of an exact microscopic onset or an automatic ultimate-strength value."],
      `Intersection strain ${eps}/${1000*E*D}; proof stress ${stress}/${D} MPa; offset 1/500; a proof-stress convention.`);
  }
  if(variant==="comparison"){
    const p={...record(),u:2,t:2},{E,S,hf}=p,total=(3*hf-2)*S*S;
    return finish(p,`${points(p)} This first record ends in fracture. A second hypothetical specimen has the same initial modulus ${E} GPa and is linear to fracture at ${2*S} MPa, strain ${2*S}/${1000*E}. Compare first/second initial modulus, maximum engineering stress, and fracture strain; calculate each work-to-fracture density.`,
      [field("modulus","First/second initial modulus ratio","1","dimensionless"),field("strength","First/second maximum-stress ratio","1","dimensionless"),field("first","First record work-to-fracture density",`${total}/${2000*E}`,"MJ/m³"),field("second","Second record work-to-fracture density",`${2*S*S}/${1000*E}`,"MJ/m³"),field("strain","First/second fracture-strain ratio",`${hf}/2`,"dimensionless"),choice("comparison","Which comparison is justified?","area",[
        {id:"area",label:"Equal initial modulus and maximum stress coexist with different strain capacity and work to fracture",feedback:"The records share an initial slope and maximum stress but have different paths and endpoints. Their integrals and fracture strains distinguish them."},
        {id:"stiffness",label:"Equal initial modulus forces equal toughness",feedback:"A local initial slope does not fix the area under the rest of a curve."},
        {id:"strength",label:"Equal maximum stress means the records absorb equal work",feedback:"The work integral includes all stress and strain values, not only the largest stress."}
      ])],
      ["The two initial slopes and maximum stresses are explicitly equal.","Integrate the first three segments; the second record is one triangle.","A fracture-strain ratio compares endpoints, while a work ratio compares whole paths. Neither follows from the initial slope alone."],
      [`Initial-modulus and maximum-stress ratios are both 1. The first strain endpoint is ${hf*S}/${1000*E}, so its ratio to the second is ${hf}/2.`,`The first area is ${total}/${2000*E} MJ/m³, while the second is ${2*S*S}/${1000*E} MJ/m³. Their work-density ratio is ${3*hf-2}/4.`,"This comparison applies to the supplied test records and conditions. It does not turn either hypothetical curve into a universal material specification."],
      `Modulus ratio 1; strength ratio 1; fracture-strain ratio ${hf}/2; work densities ${total}/${2000*E} and ${2*S*S}/${1000*E} MJ/m³.`);
  }
  if(variant==="true-stress"){
    const F=50*rng.integer(2,20),A=rng.integer(2,12),r=rng.integer(1,3),percent=rng.integer(1,20);
    return finish({F,A,r,percent},`At a recorded tensile state, axial force is ${F} N, original area ${A} mm², and the independently measured current neck area is ${r*A}/4 mm². The whole gauge length has engineering strain ${percent}%. Find engineering stress, current-section average axial stress, and their ratio. State whether the local neck strain follows from the given global strain.`,
      [field("engineering","Engineering stress",`${F}/${A}`,"MPa"),field("current","Current-section average axial stress",`${4*F}/${r*A}`,"MPa"),field("ratio","Current/engineering stress ratio",`4/${r}`,"dimensionless"),choice("strain","Local neck-strain inference","unknown",[
        {id:"unknown",label:"The local neck strain is not established by the whole-gauge strain alone",feedback:"After localization, deformation is nonuniform. Current area determines the average axial stress at that section, but global extension does not identify local neck strain."},
        {id:"same",label:"The local neck strain must equal the whole-gauge engineering strain",feedback:"A neck concentrates deformation in part of the gauge length. Uniform strain cannot be assumed after localization."},
        {id:"log",label:"Taking the logarithm of one plus global engineering strain gives the local neck strain",feedback:"That homogeneous conversion cannot recover a local nonuniform strain without the required measurements and assumptions."}
      ])],
      ["Engineering stress uses original area; the current-section measure uses the measured neck area.","The force is the same in both quotients, so the stress ratio is original area divided by current area.","Average axial stress does not describe every local stress component or supply a neck-strain measurement."],
      [`Engineering stress is ${F}/${A} MPa. The current-section average is ${4*F}/${r*A} MPa, a ratio of 4/${r}.`,`The supplied ${percent}% whole-gauge strain does not identify how that extension is distributed between necked and unnecked regions.`,"No homogeneous constant-volume or logarithmic-strain conversion is asserted after localization. Additional local geometry or displacement data would be required."],
      `Engineering ${F}/${A} MPa; current-section average ${4*F}/${r*A} MPa; ratio 4/${r}; local neck strain remains unknown.`);
  }
  if(variant==="inverse"){
    const {E,S,hy,hf,u}=record(),r=rng.integer(1,4),A=rng.integer(2,10),a=(4+(hy-1)*r)*S,b=(4*hy+(hf-hy)*(4-r))*S,den=4000*E,target=(4+(u-1)*r)*S;
    const roots=r===4?[`${a}/${den}`]:[`${a}/${den}`,`${b}/${den}`];
    return finish({E,S,hy,hf,u,r,A},`A supplied engineering record has vertices (0,0), (${S}/${1000*E}, ${S} MPa), (${hy*S}/${1000*E}, ${u*S} MPa), and (${hf*S}/${1000*E}, ${S} MPa), with straight segments and fracture at the final vertex. At stress ${target}/4 MPa, find every strain on this loading record and the corresponding axial force for original area ${A} mm². No branch history is supplied.`,
      [{id:"strains",label:"All strain intersections",kind:"roots",numberSystem:"real",expected:roots,unit:"dimensionless",help:"Enter every distinct exact fraction, separated by commas. Do not duplicate a shared endpoint."},field("force","Axial force at these intersections",`${target*A}/4`,"N"),choice("branch","What does the stress value identify?",r===4?"peak":"multiple",[
        {id:"multiple",label:"Two distinct positions on the supplied loading record; branch history is needed",feedback:r===4?"At this exact maximum the two segment intersections coincide. Keep one distinct strain.":"One intersection lies on the ascending branch and one on the descending branch. Equal engineering stress does not choose a loading history."},
        {id:"peak",label:"One unique intersection at the shared peak vertex",feedback:r===4?"Both line equations reach the same peak vertex; the distinct solution set contains one strain.":"The target is below the maximum and above the final stress. It has two distinct intersections, not one peak state."},
        {id:"hooke",label:"Use stress divided by the initial modulus as the actual strain",feedback:"That extrapolated initial line is not the supplied post-yield record. Solve the actual piecewise segments and check their domains."}
      ])],
      ["Locate the target stress relative to yield, peak, and final stress.","Use a fractional interpolation on both ascending and descending segments.","Check segment domains and merge a shared endpoint. Force is engineering stress times original area."],
      [`The ascending intersection is ${a}/${den}; the descending intersection is ${b}/${den}. ${r===4?"They coincide at the peak and count once.":"They are distinct, so a loading-history claim needs more information."}`,`Both have axial force ${target*A}/4 N. The stress-to-strain map on this record is ${r===4?"unique at this maximum":"not one-to-one at this stress"}.`,"A curve intersection does not establish that a force-controlled experiment can follow its descending segment quasistatically."],
      `Distinct strains: ${roots.join(", ")}; force ${target*A}/4 N; ${r===4?"one peak intersection":"two branches require history"}.`);
  }
  if(variant==="measurement"){
    const L=25*rng.integer(2,8),h=rng.integer(1,5),r=rng.integer(0,4);
    return finish({L,h,r},`A hypothetical unloaded specimen has original gauge length ${L} mm. Before/after displacement readings each round independently to the nearest ${h}/100 mm step, and their displayed difference is ${r*h}/100 mm. Treat rounding as the only possible error and all endpoint combinations as allowed; temperature, fixture motion, and baseline are held fixed. Bound the signed residual extension and strain. Does this evidence exclude zero permanent set?`,
      [field("lower","Lower residual-extension bound",`${(r-1)*h}/100`,"mm"),field("upper","Upper residual-extension bound",`${(r+1)*h}/100`,"mm"),field("strain-lower","Lower residual-strain bound",`${(r-1)*h}/${100*L}`,"dimensionless"),field("strain-upper","Upper residual-strain bound",`${(r+1)*h}/${100*L}`,"dimensionless"),choice("resolved","Resolution-limited evidence",r>1?"resolved":"unresolved",[
        {id:"resolved",label:"The entire allowed interval is positive, so zero set is excluded under the stated error model",feedback:r>1?"The lower endpoint is positive. This resolves a positive residual set only under the explicitly limited rounding and stable-apparatus assumptions.":"The interval contains zero, including an endpoint when the displayed difference equals one step. Positive set is not resolved by these readings."},
        {id:"unresolved",label:"Zero lies in the allowed interval, so these readings do not resolve a nonzero permanent set",feedback:r>1?"The allowed interval is strictly positive here. The stated error model excludes zero even though other unmodeled errors could change that conclusion.":"Each reading may err by half a step, so their difference may err by a full step; the resulting interval includes zero."},
        {id:"standard",label:"The interval is automatically a 95% confidence interval",feedback:"No probability distribution or coverage model was supplied. These are finite allowed rounding bounds, not statistical confidence limits."}
      ])],
      ["A single rounded reading has error at most half a step under rounding-to-nearest.","Subtracting two independently rounded readings produces a worst-case full-step error, not half a step.","Divide the signed extension endpoints by exact original length. Zero at an endpoint still means zero is allowed."],
      [`Displayed difference is ${r*h}/100 mm and its allowed error is ±${h}/100 mm. The interval is [${(r-1)*h}/100, ${(r+1)*h}/100] mm.`,`Divide by ${L} mm for strain bounds [${(r-1)*h}/${100*L}, ${(r+1)*h}/${100*L}]. ${r>1?"Both endpoints are positive, excluding zero.":"The interval includes zero, so a positive permanent set is not resolved."}`,"This conclusion depends on the stated error model. A temperature shift, changing fixture, or uncertain reference would require additional bounds."],
      `Residual extension [${(r-1)*h}/100, ${(r+1)*h}/100] mm; strain [${(r-1)*h}/${100*L}, ${(r+1)*h}/${100*L}]; ${r>1?"zero excluded":"zero allowed"}.`);
  }
  throw Error("Unreachable material-evidence variant.");
}

