import { questionSchema, type AnswerField } from "../contracts";
import { randomFrom } from "../random";
import { phs232Choice, phs232Exact, phs232Pi, phs232Rational } from "./phs-232-fields";

export const phs232WaveTransportFamilyIds = ["phs232-wave-transport"] as const;
export const phs232WaveTransportVariants = ["string-speed", "density-unit", "average-power", "energy-density", "amplitude-scaling", "medium-change"] as const;

export function phs232WaveTransportQuestion(familyId: string, variant: string, seed: string, id: string) {
  if (familyId !== "phs232-wave-transport" || !(phs232WaveTransportVariants as readonly string[]).includes(variant)) throw Error("Unknown PHS 232 wave-transport family or variant.");
  const rng = randomFrom(familyId + ":" + variant + ":" + seed), m = rng.integer(1, 9), c = rng.integer(5, 12), a = rng.integer(1, 5), k = rng.integer(1, 4), direction = rng.integer(0, 1) ? 1 : -1, phaseIndex = rng.integer(0, 7), length = rng.integer(2, 8), amplitudeFactor = rng.integer(2, 3), frequencyFactor = rng.integer(1, 3), mode = rng.integer(0, 3);
  const parameters = { m, c, a, k, direction, phaseIndex, length, amplitudeFactor, frequencyFactor, mode }, omega = c * k, energyNumerator = m * a * a * omega * omega, tension = m * c * c + "/1000";
  const choice = (id: string, label: string, correct: string, options: [string, string, string][]) => phs232Choice(id, label, correct, rng.shuffle(options));
  const finish = (prompt: string, fields: AnswerField[], hints: string[], explanation: string[], answerSummary: string) => questionSchema.parse({ id, familyId, familyVersion: 1, courseId: "phs-232", objectiveId: "m02-l01", category: "application", critical: true, parameters, prompt, fields, hints, explanation, answerSummary });
  const setup = "A uniform ideal string has constant tension F_T=" + tension + " N and linear density mu=" + m + "/1000 kg/m. A single traveling wave has displacement amplitude A=" + a + "/1000 m and angular frequency omega=" + omega + " rad/s. It travels " + (direction === 1 ? "rightward (+x)" : "leftward (-x)") + ". Use the small-slope model; the string has no damping or reflected contribution in the observed region.";
  if (variant === "string-speed") return finish(setup + " Find the positive wave speed, wavelength and the tension required to double the speed while keeping the same string density.",
    [phs232Exact("speed", "Positive wave speed", String(c), "m/s"), phs232Pi("wavelength", "Wavelength", "2*pi/" + k, "m"), phs232Rational("tension", "Tension for double speed", 4 * m * c * c + "/1000", "N")],
    ["The vertical force equation gives c²=F_T/mu. Use mass per length, not volume density.", "At the given angular frequency, wavelength is 2*pi*c/omega.", "At fixed density, tension is proportional to speed squared. A doubled speed requires four times the tension."],
    ["F_T/mu=(" + tension + ")/(" + m + "/1000)=" + c * c + " m²/s², so c=" + c + " m/s.", "lambda=2*pi*c/omega=2*pi/" + k + " m. The positive wavelength does not take the sign of propagation.", "F_T,new=mu*(2*c)²=4*F_T=" + 4 * m * c * c + "/1000 N.", "This is a property of the ideal medium under its stated tension. Changing amplitude alone would not change c in this linear model."],
    "c=" + c + " m/s; lambda=2*pi/" + k + " m; required tension=" + 4 * m * c * c + "/1000 N.");
  if (variant === "density-unit") return finish("A uniform string segment of equilibrium length " + length + " m has mass " + m * length + " g. Its tension is " + tension + " N. Compute its SI linear density and wave speed. A calculation incorrectly substitutes the numerical density in g/m as though it were kg/m. Give that mistaken speed divided by the correct speed.",
    [phs232Rational("density", "SI linear density", m + "/1000", "kg/m"), phs232Exact("speed", "Correct positive wave speed", String(c), "m/s"), phs232Exact("bias", "Mistaken speed divided by correct speed", "1/sqrt(1000)")],
    ["Convert grams to kilograms before dividing by equilibrium length.", "Use c=sqrt(F_T/mu); verify that N divided by kg/m gives m²/s².", "The incorrect density is 1000 times the correct one. The square root turns that into a speed factor of 1/sqrt(1000)."],
    ["The mass is " + m * length + "/1000 kg. Dividing by " + length + " m gives mu=" + m + "/1000 kg/m.", "c=sqrt((" + tension + ")/(" + m + "/1000))=" + c + " m/s.", "With density overstated by 1000, c_wrong/c_correct=1/sqrt(1000). The speed is too small, not too large.", "The ratio is dimensionless. Linear density and volume density are different quantities and cannot be exchanged without a cross-sectional area."],
    "mu=" + m + "/1000 kg/m; c=" + c + " m/s; mistaken/correct speed=1/sqrt(1000).");
  if (variant === "average-power") return finish(setup + " Find the mean energy per equilibrium length, signed mean power toward +x, energy stored in one wavelength, and signed energy crossing a cut toward +x during one period. Keep pi exact where needed.",
    [phs232Rational("density", "Mean energy per length", energyNumerator + "/2000000000", "J/m"), phs232Rational("power", "Signed mean power toward +x", direction * c * energyNumerator + "/2000000000", "W"), phs232Pi("stored", "Energy stored in one wavelength", energyNumerator + "*pi/" + 1000000000 * k, "J"), phs232Pi("crossing", "Signed energy crossing in one period", direction * energyNumerator + "*pi/" + 1000000000 * k, "J")],
    ["For a single harmonic traveling wave, mean u=mu*A²*omega²/2. This is energy per length, not energy per volume.", "Signed mean power is sigma*c*mean u; the sign describes transport direction while energy density stays nonnegative.", "Multiply mean u by lambda=2*pi*c/omega for stored energy, and multiply signed mean P by period 2*pi/omega for transported energy."],
    ["Averaging the local squared sine over a full period gives mean u=" + energyNumerator + "/2000000000 J/m.", "The medium speed is c=" + c + " m/s. Therefore mean P=" + direction * c * energyNumerator + "/2000000000 W, with the sign fixed by propagation.", "E_lambda=mean u*lambda=" + energyNumerator + "*pi/" + 1000000000 * k + " J is nonnegative.", "The signed crossing energy is mean P*tau=" + direction * energyNumerator + "*pi/" + 1000000000 * k + " J. Its magnitude equals E_lambda; a negative crossing value does not mean negative stored energy.", "An infinite harmonic train has infinite total energy. One wavelength and one forcing period are finite, explicitly chosen measures."],
    "Mean u=" + energyNumerator + "/2000000000 J/m; signed mean P=" + direction * c * energyNumerator + "/2000000000 W; E_lambda=" + energyNumerator + "*pi/" + 1000000000 * k + " J; crossing energy has sign " + direction + ".");
  if (variant === "energy-density") {
    const h = [0, 1, 2, 1, 0, 1, 2, 1][phaseIndex], n = energyNumerator * h;
    return finish(setup + " At the point of interest, the phase in y=A*cos(k*x-sigma*omega*t+phi) is theta=" + phaseIndex + "*pi/4. Find local kinetic, stretch-potential and total energy per equilibrium length, and signed instantaneous power toward +x. Is this local string element an isolated oscillator with a constant local total energy?",
      [phs232Rational("kinetic", "Local kinetic energy per length", n + "/4000000000", "J/m"), phs232Rational("potential", "Local stretch energy per length", n + "/4000000000", "J/m"), phs232Rational("total", "Local total energy per length", n + "/2000000000", "J/m"), phs232Rational("power", "Signed instantaneous power", direction * c * n + "/2000000000", "W"), choice("isolated", "Is the string element an isolated constant-energy oscillator?", "no", [["no", "No: its neighbors transfer energy across its boundaries", "Local motion is harmonic, but stretch energy depends on the spatial slope. Local energy can vary as energy crosses the element."], ["yes", "Yes: sinusoidal motion makes its local energy constant", "A harmonic time dependence does not isolate the element from forces and energy transfer through neighboring string segments."]])],
      ["Differentiate: y_t=sigma*A*omega*sin(theta) and y_x=-A*k*sin(theta), with k=omega/c.", "Use kinetic density mu*y_t²/2 and stretch density F_T*y_x²/2. Do not substitute displacement squared for local stretch energy.", "Add the two nonnegative densities, then calculate P=-F_T*y_x*y_t. A leftward wave has negative signed power away from zero-slope points."],
      ["sin²(theta)=" + h + "/2. The local kinetic density is mu*A²*omega²*sin²(theta)/2=" + n + "/4000000000 J/m.", "The tension relation F_T*k²=mu*omega² gives the same local stretch density. For this single traveling wave these two energies peak together.", "Their sum is " + n + "/2000000000 J/m, and signed P=sigma*c*u=" + direction * c * n + "/2000000000 W.", "At a crest or trough both slope and transverse velocity vanish, so both local energy densities vanish at that point even though its acceleration need not vanish.", "A finite neighboring segment still has energy. Local energy varies because boundary work transfers energy; the string element is not isolated."],
      "K/length=U/length=" + n + "/4000000000 J/m; total=" + n + "/2000000000 J/m; P=" + direction * c * n + "/2000000000 W; the element is not isolated.");
  }
  if (variant === "amplitude-scaling") {
    const scale = amplitudeFactor * frequencyFactor;
    return finish(setup + " Change the source so A_new=" + amplitudeFactor + "*A and f_new=" + frequencyFactor + "*f, while keeping tension, density and propagation direction fixed. The resulting maximum slope remains at most 0.18. Find new/old ratios for mean power, maximum transverse particle speed, positive wave speed and wavelength.",
      [phs232Rational("power", "Mean power ratio", String(scale * scale)), phs232Rational("particle", "Maximum transverse speed ratio", String(scale)), phs232Rational("wave", "Propagation speed ratio", "1"), phs232Rational("wavelength", "Wavelength ratio", "1/" + frequencyFactor)],
      ["At fixed medium, c does not change. Angular frequency has the same ratio as f.", "Mean power magnitude scales with A²*omega², while maximum transverse speed scales with A*omega.", "The wavelength is c/f, so its ratio is the reciprocal frequency ratio when c is fixed."],
      ["The product A*omega changes by factor " + amplitudeFactor + "*" + frequencyFactor + "=" + scale + ".", "Mean power changes by the square of this product, giving ratio " + scale * scale + "; maximum transverse speed changes by factor " + scale + ".", "c=sqrt(F_T/mu) is unchanged, so its ratio is 1 and lambda_new/lambda_old=1/" + frequencyFactor + ".", "Because direction is unchanged, the ratio of signed mean powers equals the positive magnitude ratio. These conclusions require the stated fixed medium and the continued validity of the small-slope approximation."],
      "Mean-power ratio=" + scale * scale + "; particle-speed ratio=" + scale + "; wave-speed ratio=1; wavelength ratio=1/" + frequencyFactor + ".");
  }
  const changes = [{ tension: "4", density: "1", speed: "2", power: "2" }, { tension: "1", density: "4", speed: "1/2", power: "2" }, { tension: "9", density: "4", speed: "3/2", power: "6" }, { tension: "1/4", density: "9", speed: "1/6", power: "3/2" }][mode];
  return finish(setup + " In a separate uniform-string run, multiply tension by " + changes.tension + " and density by " + changes.density + ". Keep the imposed source frequency, displacement amplitude and propagation direction fixed. Treat each run as a single traveling wave, not a joined-string interface experiment. Find new/old ratios for speed, wavelength, source frequency, mean energy density and signed mean power.",
    [phs232Rational("speed", "Propagation speed ratio", changes.speed), phs232Rational("wavelength", "Wavelength ratio", changes.speed), phs232Rational("frequency", "Imposed source frequency ratio", "1"), phs232Rational("density", "Mean energy density ratio", changes.density), phs232Rational("power", "Signed mean power ratio", changes.power)],
    ["Use c_new/c_old=sqrt((F_T,new/F_T,old)/(mu_new/mu_old)). Changing medium properties does not change the externally imposed frequency.", "At fixed f, wavelength changes in the same ratio as speed. At fixed A and omega, mean energy density changes in the density ratio.", "Mean power is sigma*c*mean u. Multiply the speed and energy-density ratios instead of treating c as constant while density changes."],
    ["The speed ratio is sqrt((" + changes.tension + ")/(" + changes.density + "))=" + changes.speed + ".", "The imposed source frequency ratio remains 1. Since lambda=c/f, the wavelength ratio is " + changes.speed + ".", "Mean u=mu*A²*omega²/2 changes in the density ratio " + changes.density + ".", "Mean P=sigma*c*mean u changes by (" + changes.speed + ")*(" + changes.density + ")=" + changes.power + ".", "These are separate uniform-media comparisons. Reflection and transmitted amplitude at an actual interface need boundary conditions and are developed in the next lesson."],
    "Speed and wavelength ratios=" + changes.speed + "; source frequency ratio=1; mean-energy-density ratio=" + changes.density + "; mean-power ratio=" + changes.power + ".");
}
