import { questionSchema } from "../contracts";
import { randomFrom } from "../random";

export const phs231ElasticVariants={
  "phs231-elastic-deformation":["axial","units","diameter","scaling","shear","bulk","energy","series","parallel","selfweight"],
  "phs231-elastic-model":["validity","inverse","poisson","calibration","uncertainty","resolution","cycle","control"],
} as const;
export const phs231ElasticFamilyIds=Object.keys(phs231ElasticVariants);
const field=(id:string,label:string,expected:string,unit:string)=>({id,label,expected,unit,kind:"rational",help:"Enter an exact signed value or equivalent fraction in the labeled unit."});
const pi=(id:string,label:string,expected:string,unit:string)=>({id,label,expected,unit,kind:"pi-multiple",help:"Keep pi exact, for example 3*pi/4. Include pi in this field."});

export function phs231ElasticQuestion(familyId:string,variant:string,seed:string,id:string){
  const variants=phs231ElasticVariants[familyId as keyof typeof phs231ElasticVariants];
  if(!variants||!(variants as readonly string[]).includes(variant))throw Error("Unknown PHS 231 elasticity family or variant.");
  const rng=randomFrom(`${familyId}:${variant}:${seed}`);
  const base={id,familyId,familyVersion:1,courseId:"phs-231",objectiveId:"m08-l02",category:"application",critical:["units","bulk","series","parallel","validity","poisson","calibration","uncertainty","resolution","cycle","control"].includes(variant)};
  const choice=(id:string,label:string,correct:string,options:{id:string;label:string;feedback:string}[])=>({id,label,kind:"choice",correct,options:rng.shuffle(options)});
  const finish=(parameters:Record<string,number>,prompt:string,fields:unknown[],hints:string[],explanation:string[],answerSummary:string)=>questionSchema.parse({...base,parameters:Object.fromEntries(Object.entries(parameters).map(([k,n])=>[k,n||0])),prompt,fields,hints,explanation,answerSummary});
  const assumed="Use the supplied hypothetical uniform, small-strain, linearly elastic model throughout the stated loading. Material properties are synthetic, not a strength rating. Buckling, end effects, and losses are excluded.";
  if(variant==="axial"){
    const F=20*rng.integer(-6,6),L2=rng.integer(1,6),A=rng.integer(2,8),E=20*rng.integer(1,6);
    return finish({F,L2,A,E},`${assumed} A specimen has original length ${L2}/2 m, original cross-sectional area ${A} mm², and E=${E} GPa. Its signed internal axial force is ${F} N, with tension positive. Find nominal stress, engineering strain, signed extension, axial stiffness, and stored energy. The two opposite end forces are not added together at a cut.`,
      [field("stress","Signed nominal stress",`${F}/${A}`,"MPa"),field("strain","Engineering axial strain",`${F}/${1000*E*A}`,"dimensionless"),field("extension","Signed extension",`${F*L2}/${2*E*A}`,"mm"),field("stiffness","Axial stiffness",`${2*E*A}/${L2}`,"kN/m"),field("energy","Stored elastic energy",`${F*F*L2}/${4000*E*A}`,"J")],
      ["One N/mm² is one MPa. Use the internal force on one face, not the net external resultant.","Divide stress by E in the same pressure unit, then multiply strain by the original length.","k=EA/L and U=FΔL/2; signed compression has both F and ΔL negative, so U is nonnegative."],
      [`σ=F/A=${F}/${A} MPa. E=${1000*E} MPa, so ε=${F}/${1000*E*A}.`,`ΔL=εL=${F*L2}/${2*E*A} mm; k=${2*E*A}/${L2} kN/m. Modulus and specimen stiffness have different units.`,`Integrating the linearly increasing load gives U=${F*F*L2}/${4000*E*A} J, not final force times the full extension.`],
      `σ=${F}/${A} MPa; ε=${F}/${1000*E*A}; ΔL=${F*L2}/${2*E*A} mm; k=${2*E*A}/${L2} kN/m; U=${F*F*L2}/${4000*E*A} J.`);
  }
  if(variant==="units"){
    const A=rng.integer(2,20),F=25*rng.integer(1,10),L2=rng.integer(1,6),d=10*rng.integer(1,50);
    return finish({A,F,L2,d},`A uniform specimen is pulled by opposite end forces of magnitude ${F} N and remains in static equilibrium. Its original area is ${A} mm² and original gauge length is ${L2}/2 m. Its measured extension is ${d} μm. Convert area to m², calculate nominal tensile stress in MPa, strain, and microstrain. Identify the internal force used for stress.`,
      [field("area","Original cross-sectional area",`${A}/1000000`,"m²"),field("stress","Nominal tensile stress",`${F}/${A}`,"MPa"),field("strain","Engineering strain",`${2*d}/${1000000*L2}`,"dimensionless"),field("microstrain","Strain in microstrain",`${2*d}/${L2}`,"με"),choice("cut","Internal force at an unloaded cut","one",[
        {id:"one",label:"Use one end-force magnitude; a cut balances one side of the specimen",feedback:"Equilibrium of either isolated side gives internal axial force F. Whole-body force cancellation does not eliminate internal loading."},
        {id:"double",label:"Add both end-force magnitudes and use twice the stated force",feedback:"The two end forces act on opposite sides of the cut. Adding their magnitudes would double-count the internal load."},
        {id:"zero",label:"Use zero because the two external end forces cancel",feedback:"Zero resultant permits equilibrium while the specimen deforms. Stress concerns internal force transmitted through a section."}
      ])],
      ["Square the millimeter-to-meter conversion: 1 mm²=(10^-3 m)².","Convert extension and original length to the same unit before dividing.","One microstrain is 10^-6 strain; multiply a dimensionless strain by one million for its numerical value in microstrain."],
      [`Area=${A}/1000000 m², and σ=${F}/${A} MPa because N/mm²=MPa.`,`The extension-to-original-length ratio is ε=${2*d}/${1000000*L2}; its microstrain value is ${2*d}/${L2}.`,"A force inventory on one side of a cut gives F, not 2F or zero. Strain normalizes extension by gauge length and is dimensionless."],
      `A=${A}/1000000 m²; σ=${F}/${A} MPa; ε=${2*d}/${1000000*L2}; microstrain=${2*d}/${L2}; internal force=one end-force magnitude.`);
  }
  if(variant==="diameter"){
    const d=rng.integer(1,5),C=10*rng.integer(1,8),L=rng.integer(1,3),E=20*rng.integer(1,6);
    return finish({d,C,L,E},`${assumed} A round axial specimen has diameter ${d} mm, length ${L} m, and E=${E} GPa. The tensile force is $${C}\\pi$ N. Keep pi exact. Find original area, nominal stress, extension, stiffness, and stored energy. Pi cancels from stress and extension but remains in area, stiffness, and energy.`,
      [pi("area","Circular area",`${d*d}/4`,"mm²"),field("stress","Nominal tensile stress",`${4*C}/${d*d}`,"MPa"),field("extension","Extension",`${4*C*L}/${E*d*d}`,"mm"),pi("stiffness","Axial stiffness",`${E*d*d}/${4*L}`,"kN/m"),pi("energy","Stored elastic energy",`${C*C*L}/${500*E*d*d}`,"J")],
      ["Radius is half the diameter, so area is pi times d²/4.","Divide C*pi by the circular area; use E in MPa before calculating strain.","Use ΔL=FL/(EA), k=EA/L, and U=FΔL/2 with ΔL in meters for energy."],
      [`A=${d*d}π/4 mm². Hence σ=${4*C}/${d*d} MPa.`,`ΔL=${4*C*L}/${E*d*d} mm, while k=${E*d*d}π/${4*L} kN/m. The area changes quadratically with diameter.`,`Integrating force over extension gives U=${C*C*L}π/${500*E*d*d} J. Treating diameter as radius would quadruple the area and distort every subsequent result.`],
      `A=${d*d}π/4 mm²; σ=${4*C}/${d*d} MPa; ΔL=${4*C*L}/${E*d*d} mm; k=${E*d*d}π/${4*L} kN/m; U=${C*C*L}π/${500*E*d*d} J.`);
  }
  if(variant==="scaling"){
    const length=rng.integer(1,4),area=rng.integer(1,4),modulus=rng.integer(1,3);
    return finish({length,area,modulus},`Two uniform linear-elastic axial specimens carry the same nonzero tensile force. The second has ${length} times the original length, ${area} times the original area, and ${modulus} times the Young modulus. Both stay within their supplied linear ranges. Give second/first ratios for stress, strain, extension, stiffness, and energy.`,
      [field("stress","Stress ratio",`1/${area}`,"dimensionless"),field("strain","Strain ratio",`1/${area*modulus}`,"dimensionless"),field("extension","Extension ratio",`${length}/${area*modulus}`,"dimensionless"),field("stiffness","Stiffness ratio",`${area*modulus}/${length}`,"dimensionless"),field("energy","Energy ratio",`${length}/${area*modulus}`,"dimensionless")],
      ["Hold the specified force fixed: stress varies as 1/A, not as 1/L.","Strain=F/(EA), while extension=strain times L.","Stiffness=EA/L and energy=F²/(2k) under fixed-force loading."],
      [`σ₂/σ₁=1/${area}; dividing additionally by the modulus ratio gives ε₂/ε₁=1/${area*modulus}.`,`Multiplying by the length ratio gives ΔL₂/ΔL₁=${length}/${area*modulus}.`,`k₂/k₁=${area*modulus}/${length}. With the same force, U₂/U₁ is its reciprocal, ${length}/${area*modulus}. These energy and extension trends would change if extension were held fixed instead.`],
      `Ratios: stress1/${area}, strain1/${area*modulus}, extension${length}/${area*modulus}, stiffness${area*modulus}/${length}, energy${length}/${area*modulus}.`);
  }
  if(variant==="shear"){
    const F=50*rng.integer(-4,4),A=40*rng.integer(1,5),h=10*rng.integer(1,4),G10=rng.integer(2,20);
    return finish({F,A,h,G10},`${assumed} A homogeneous shear element has loaded-face area ${A} mm² and distance between those faces ${h} mm. Its shear modulus is ${G10}/10 GPa. A signed tangential force ${F} N acts on the upper face, balanced by the full set of complementary boundary tractions; positive means the upper face shifts right. Find shear stress, engineering shear strain, signed upper-face shift, and stored energy.`,
      [field("stress","Signed shear stress",`${F}/${A}`,"MPa"),field("strain","Engineering shear strain",`${F}/${100*G10*A}`,"dimensionless"),field("shift","Signed face shift",`${10*F*h}/${G10*A}`,"μm"),field("energy","Stored shear energy",`${F*F*h}/${200000*G10*A}`,"J")],
      ["Use tangential force divided by the area of the loaded face.","G in MPa is 100 times the printed numerator. Engineering shear strain is shift divided by the face separation.","The work of quasistatic linear loading is one half of force times the signed shift in meters."],
      [`τ=${F}/${A} MPa and γ=τ/G=${F}/${100*G10*A}.`,`The shift γh=${10*F*h}/${G10*A} μm. For small angles γ approximates the shear angle in radians; it is not an axial strain calculated with E.`,`The recoverable energy is ${F*F*h}/${200000*G10*A} J. Complementary tractions balance moments; two isolated separated horizontal forces alone would leave a couple.`],
      `τ=${F}/${A} MPa; γ=${F}/${100*G10*A}; shift=${10*F*h}/${G10*A} μm; U=${F*F*h}/${200000*G10*A} J.`);
  }
  if(variant==="bulk"){
    const K=rng.integer(2,10),p=rng.integer(1,20),V=100*rng.integer(1,9);
    return finish({K,p,V},`A hypothetical material has reference volume ${V} cm³ and constant bulk modulus K=${K} GPa. Its uniform pressure increases by ${p} MPa. The supplied reversible small-strain range includes this entire change. Positive pressure is compressive; positive volume change means expansion. Find volumetric strain, signed volume change, final volume, compressibility, and incremental elastic energy about the reference state.`,
      [field("strain","Signed volumetric strain",`-${p}/${1000*K}`,"dimensionless"),field("volume","Signed volume change",`-${p*V}/${1000*K}`,"cm³"),field("final","Final volume",`${V*(1000*K-p)}/${1000*K}`,"cm³"),field("compressibility","Compressibility",`1/${K*1000000000}`,"Pa⁻¹"),field("energy","Incremental elastic energy",`${p*p*V}/${2000*K}`,"J")],
      ["K=−Δp/(ΔV/V0). The minus sign makes a positive pressure increment produce negative volume strain.","Use the original volume, not the final volume, in this small-strain definition. Compressibility is 1/K in reciprocal pascals.","Integrate −Δp dV from the reference: U=−ΔpΔV/2. Convert MPa and cm³ consistently."],
      [`εV=−${p}/${1000*K}; ΔV=−${p*V}/${1000*K} cm³, so Vfinal=${V*(1000*K-p)}/${1000*K} cm³.`,`The compressibility is 1/${K*1000000000} Pa⁻¹. It measures volume response per pressure increment, not a dimensionless strain.`,`The increasing pressure does positive incremental work during compression: U=${p*p*V}/${2000*K} J. Equal pressure on opposite faces can have zero net force while the volume decreases.`],
      `εV=−${p}/${1000*K}; ΔV=−${p*V}/${1000*K} cm³; Vfinal=${V*(1000*K-p)}/${1000*K} cm³; compressibility=1/${K*1000000000} Pa⁻¹; U=${p*p*V}/${2000*K} J.`);
  }
  if(variant==="energy"){
    const stress=10*rng.integer(1,10)*(rng.integer(0,1)?1:-1),E=20*rng.integer(1,8),V=10*rng.integer(1,5);
    return finish({stress,E,V},`A hypothetical uniform axial specimen of original volume ${V} cm³ and E=${E} GPa is loaded quasistatically from zero to nominal stress ${stress} MPa, then completely unloaded along the same line. Tension is positive. The supplied reversible linear regime and compression stability hold throughout. Find peak strain, peak stored energy per original volume, total peak energy, and net work over the closed loading-unloading cycle.`,
      [field("strain","Peak signed axial strain",`${stress}/${1000*E}`,"dimensionless"),field("density","Peak energy density",`${500*stress*stress}/${E}`,"J/m³"),field("energy","Peak stored energy",`${stress*stress*V}/${2000*E}`,"J"),field("cycle","Net work over the closed cycle","0","J")],
      ["The stress-strain line has slope E; strain=stress/E with consistent units.","Energy density is the area under stress versus strain. A straight line from zero encloses a triangle.","Multiply energy density by reference volume in m³. Reversible unloading returns the stored energy, so the signed loop area is zero."],
      [`ε=${stress}/${1000*E}. Integrating σ dε from zero gives u=σ²/(2E)=${500*stress*stress}/${E} J/m³.`,`U=uV=${stress*stress*V}/${2000*E} J. Squared stress makes this positive for compression as well as tension.`,"The unloading work is the negative of loading work, so net cycle work is zero. This conclusion uses the supplied reversible path; it is not available after an unsupported overload."],
      `ε=${stress}/${1000*E}; u=${500*stress*stress}/${E} J/m³; U=${stress*stress*V}/${2000*E} J; net closed-cycle work=0 J.`);
  }
  if(variant==="series"){
    const F=10*rng.integer(1,8),L1=rng.integer(1,4),L2=rng.integer(1,4),A1=rng.integer(1,4),A2=rng.integer(1,4),E1=50*rng.integer(1,3),E2=50*rng.integer(1,3),product=E1*A1*E2*A2,compliance=L1*E2*A2+L2*E1*A1;
    return finish({F,L1,L2,A1,A2,E1,E2},`${assumed} Two axial segments join end to end in series. Segment1: L=${L1}/2 m, A=${A1} mm², E=${E1} GPa. Segment2: L=${L2}/2 m, A=${A2} mm², E=${E2} GPa. A ${F} N tensile load is transmitted through both, with no intermediate external load or preload. Find each extension, total extension, equivalent stiffness, total energy, and the shared compatibility condition.`,
      [field("first","First extension",`${F*L1}/${2*E1*A1}`,"mm"),field("second","Second extension",`${F*L2}/${2*E2*A2}`,"mm"),field("total","Total extension",`${F*compliance}/${2*product}`,"mm"),field("stiffness","Equivalent axial stiffness",`${2*product}/${compliance}`,"kN/m"),field("energy","Total elastic energy",`${F*F*compliance}/${4000*product}`,"J"),choice("condition","Series force and displacement condition","series",[
        {id:"series",label:"Both carry the same force and their extensions add",feedback:"Equilibrium of the unloaded junction gives equal axial forces. The total end displacement is the sum of the segment extensions."},
        {id:"parallel",label:"Both must have the same extension and their forces add",feedback:"That describes parallel members between translation-only end plates. End-to-end members generally have unequal extensions."},
        {id:"equal",label:"Each carries half the applied force",feedback:"There is no separate branch to share the load. Each cut through the series chain transmits the whole applied force."}
      ])],
      ["Cut each segment: the same F crosses both because the junction has no external load.","Calculate each FL/(EA) separately and add the signed extensions.","The reciprocal equivalent stiffness is the sum of the two compliances; U=F times total extension divided by two."],
      [`ΔL1=${F*L1}/${2*E1*A1} mm; ΔL2=${F*L2}/${2*E2*A2} mm; total=${F*compliance}/${2*product} mm.`,`1/keq=L1/(E1A1)+L2/(E2A2), giving keq=${2*product}/${compliance} kN/m.`,`The energy is ${F*F*compliance}/${4000*product} J. Each segment's stress F/A and strain must be checked against its own range in an actual supplied material model.`],
      `Extensions=${F*L1}/${2*E1*A1}, ${F*L2}/${2*E2*A2} mm; total=${F*compliance}/${2*product} mm; keq=${2*product}/${compliance} kN/m; U=${F*F*compliance}/${4000*product} J; same force, extensions add.`);
  }

  if(variant==="parallel"){
    const F=50*rng.integer(1,8),L2=rng.integer(1,6),A1=rng.integer(1,5),A2=rng.integer(1,5),E1=20*rng.integer(1,6),E2=20*rng.integer(1,6),sum=E1*A1+E2*A2;
    return finish({F,L2,A1,A2,E1,E2},`${assumed} Two initially unstressed rods connect rigid end plates constrained to translate without rotation. Both lengths are ${L2}/2 m. Rod1 has A=${A1} mm²,E=${E1} GPa; rod2 has A=${A2} mm²,E=${E2} GPa. The total tensile load is ${F} N. Find each rod's force, common extension, equivalent stiffness, and total energy.`,
      [field("first","First rod force",`${F*E1*A1}/${sum}`,"N"),field("second","Second rod force",`${F*E2*A2}/${sum}`,"N"),field("extension","Common extension",`${F*L2}/${2*sum}`,"mm"),field("stiffness","Equivalent axial stiffness",`${2*sum}/${L2}`,"kN/m"),field("energy","Total stored energy",`${F*F*L2}/${4000*sum}`,"J"),choice("compatibility","Reason for the load sharing","common",[
        {id:"common",label:"Equal plate displacement makes each force proportional to that rod's stiffness",feedback:"F1=k1δ and F2=k2δ, with F1+F2=F. Equal force follows only when the stiffnesses are equal under these no-preload conditions."},
        {id:"half",label:"Two rods always split the total force in half regardless of stiffness",feedback:"Equilibrium gives only the sum. Compatibility and the separate force-extension laws determine the split."},
        {id:"series",label:"Each rod must carry the entire applied load because the lengths are equal",feedback:"These are separate parallel paths between common plates. Their forces add; series equal-force logic does not apply."}
      ])],
      ["The no-rotation plates impose equal extension, not generally equal force.","Add k1=E1A1/L and k2=E2A2/L, then use δ=F/(k1+k2).","Recover each force from its own stiffness times δ. Sum the two elastic energies or use Fδ/2."],
      [`The stiffness sum is ${2*sum}/${L2} kN/m, giving δ=${F*L2}/${2*sum} mm.`,`The forces are ${F*E1*A1}/${sum} N and ${F*E2*A2}/${sum} N. They sum to the applied ${F} N and produce the same extension.`,`Total energy is ${F*F*L2}/${4000*sum} J. This sharing depends on equal plate motion, known stiffness, and no initial gap or preload; equilibrium alone does not establish it.`],
      `F1=${F*E1*A1}/${sum} N; F2=${F*E2*A2}/${sum} N; δ=${F*L2}/${2*sum} mm; keq=${2*sum}/${L2} kN/m; U=${F*F*L2}/${4000*sum} J.`);
  }
  if(variant==="selfweight"){
    const P=10*rng.integer(1,10),L=rng.integer(1,3),A=rng.integer(2,10),E=50*rng.integer(1,4),density=rng.integer(1,8),top=100*P+density*A*L,extension=200*P*L+density*L*L*A,energy=30000*P*P*L+300*P*density*A*L*L+density*density*A*A*L*L*L;
    return finish({P,L,A,E,density},`In a paper model a uniform vertical rod hangs from its top and supports ${P} N at the bottom. Original L=${L} m,A=${A} mm²,E=${E} GPa,density=${1000*density} kg/m³,g=10 m/s². Include the rod's weight and assume the entire stated elastic model remains valid. Coordinate x runs upward from the bottom along the original rod. Find the largest axial force, largest nominal stress, total extension, and elastic energy. No physical hanging-load experiment is assigned.`,
      [field("force","Largest internal axial force",`${top}/100`,"N"),field("stress","Largest nominal tensile stress",`${top}/${100*A}`,"MPa"),field("extension","Total extension",`${extension}/${200*E*A}`,"mm"),field("energy","Stored elastic energy",`${energy}/${60000000*E*A}`,"J"),choice("location","Location of largest axial stress","top",[
        {id:"top",label:"At the top, because a cut there carries the end load and all rod weight",feedback:"The portion below a higher cut includes more rod weight. With uniform area, the increasing axial force gives increasing stress."},
        {id:"bottom",label:"At the bottom, because that is where the external end load is attached",feedback:"The bottom cut carries only the end load; cuts above also carry the weight below them."},
        {id:"uniform",label:"Uniform everywhere because the whole rod is in equilibrium",feedback:"Equilibrium of each cut includes a different amount of distributed weight. A static body need not have spatially uniform stress."}
      ])],
      ["For a cut at x, N(x)=P+ρAgx, with A converted to m².","Extension is the integral of N(x)/(EA), not peak strain times the entire length.","Integrate N(x)²/(2EA) for energy; retain the cross term when squaring the affine force."],
      [`N(x)=${P}+(${density*A}/100)x N, increasing to ${top}/100 N at the top. Maximum stress is ${top}/${100*A} MPa.`,`Integrating gives ΔL=PL/(EA)+ρgL²/(2E)=${extension}/${200*E*A} mm. Peak stress times full length would overestimate the self-weight contribution.`,`U=[P²L+PqL²+q²L³/3]/(2EA), where q=ρAg. In consistent SI units this is ${energy}/${60000000*E*A} J. The one-dimensional small-strain model neglects changes in geometry under load.`],
      `Top N=${top}/100 N; top σ=${top}/${100*A} MPa; ΔL=${extension}/${200*E*A} mm; U=${energy}/${60000000*E*A} J.`);
  }
  if(variant==="validity"){
    const E=20*rng.integer(1,8),A=rng.integer(1,8),L=rng.integer(1,3),stressLimit=10*rng.integer(1,8),strainNum=rng.integer(1,8),limit=Math.min(stressLimit,E*strainNum),ratio=rng.integer(1,3),sign=rng.integer(0,1)?1:-1,F=sign*A*limit*ratio/2,admitted=ratio<=2;
    return finish({E,A,L,stressLimit,strainNum,ratio,sign,F},`An ideal uniform axial specimen has L=${L} m,A=${A} mm²,E=${E} GPa. Its supplied reversible linear law is validated only for |σ|≤${stressLimit} MPa AND |ε|≤${strainNum}/1000. The signed applied force is ${F} N, tension positive; compression stability is separately assumed. Find demanded stress, the largest admitted force magnitude, and the extension magnitude at that limit. Decide whether the linear law establishes the applied-load deformation.`,
      [field("stress","Demanded signed stress",`${F}/${A}`,"MPa"),field("force","Largest admitted force magnitude",String(A*limit),"N"),field("extension","Extension magnitude at the admitted limit",`${limit*L}/${E}`,"mm"),choice("model","Applied-load constitutive decision",admitted?"admitted":"unknown",[
        {id:"admitted",label:"Both supplied range checks pass, so this ideal linear law establishes deformation",feedback:"The effective stress limit is the smaller of the supplied stress ceiling and E times the strain ceiling. Equality is admitted but limiting."},
        {id:"unknown",label:"At least one range check fails, so actual deformation is not established by this law",feedback:"An algebraic Hooke-law extrapolation is not a validated deformation. Range failure does not by itself identify yielding, fracture, or the unloading path."},
        {id:"fracture",label:"Exceeding the supplied linear range proves immediate fracture",feedback:"A proportional-range limit is not necessarily a fracture stress. Additional material evidence is needed to predict behavior beyond the stated range."},
        {id:"strain-only",label:"A small computed strain is sufficient even if the stated stress ceiling fails",feedback:"Both independently supplied validity conditions are required. Passing one does not cancel failure of the other."}
      ])],
      ["Convert the strain limit to an equivalent stress ceiling using E in MPa.","Take the smaller stress ceiling, multiply by area for force, and divide by E for limiting strain.","Compare the absolute applied stress with that effective ceiling before claiming an actual Hooke-law deformation."],
      [`The two stress ceilings are ${stressLimit} MPa and ${E*strainNum} MPa, so |σ|≤${limit} MPa and |F|≤${A*limit} N.`,`The limiting extension magnitude is ${limit*L}/${E} mm. The applied stress is ${F}/${A} MPa.`,admitted?ratio===2?"The applied state is exactly at the admitted range limit. It has no stated remaining margin.":"Both supplied range conditions pass. The calculation remains conditional on the ideal axial and material assumptions.":"The applied load lies beyond at least one supplied linear bound. Neither its actual extension nor its later residual deformation is determined by these data."],
      `Demand=${F}/${A} MPa; force limit=${A*limit} N; limiting extension=${limit*L}/${E} mm; applied deformation ${admitted?"established in the supplied model":"not established"}.`);
  }

  if(variant==="inverse"){
    const mode=rng.integer(0,2),F=mode===0?0:20*rng.integer(1,8),L2=rng.integer(1,6),A=rng.integer(1,8),E=20*rng.integer(1,6),num=(mode===2?-1:1)*F*L2,den=2*E*A;
    const fields:unknown[]=[field("stress","Signed nominal stress",`${F}/${A}`,"MPa"),field("strain","Measured engineering strain",`${2*num}/${1000*den*L2}`,"dimensionless")];
    if(mode!==0)fields.push(field("modulus","Algebraic modulus candidate",String(mode===2?-E:E),"GPa"));
    fields.push(choice("meaning","Inference from this force-extension pair",mode===0?"undetermined":mode===2?"inconsistent":"conditional",[
      {id:"conditional",label:"A positive modulus is identified conditional on the stated uniform linear specimen model",feedback:"A nonzero force and extension determine E=FL/(AΔL) in this model. One pair does not independently establish linearity over a range or remove fixture error."},
      {id:"undetermined",label:"Zero force and zero extension do not determine a unique positive modulus",feedback:"Every positive E in the assumed linear model permits the zero-load reference. The ratio is 0/0, so a nonzero incremental measurement is needed."},
      {id:"inconsistent",label:"The algebraic modulus is negative, contradicting the stipulated passive positive-E model",feedback:"Positive tensile force with negative extension cannot fit the stated unstressed positive-modulus model. Recheck sign, reference, fixture motion, or assumptions rather than taking an absolute value."},
      {id:"proof",label:"A single pair proves the complete constitutive law and failure strength",feedback:"Identifying one slope under assumptions is not a test of all loads, unloading paths, or failure mechanisms."}
    ]));
    return finish({F,L2,A,num,den},`An initially unstressed uniform specimen has L=${L2}/2 m and A=${A} mm². A signed force ${F} N is paired with signed gauge extension ${num}/${den} mm, with tension and elongation positive. Geometry and readings are exact for this classroom calculation. The proposed material law is σ=Eε with finite E>0. Find stress and strain; when the measured extension is nonzero, report the algebraic E candidate even if it contradicts the proposed model. Interpret what the pair establishes.`,
      fields,
      ["Compute engineering strain from the measured extension and original length; keep its sign.","For nonzero strain, E=σ/ε. Convert MPa to GPa in the final modulus.","Zero/zero is indeterminate, and a negative candidate cannot be made positive by dropping its sign."],
      [`σ=${F}/${A} MPa and ε=${2*num}/${1000*den*L2}.`,mode===0?"Both measurements vanish, so there is no identified slope; many positive moduli fit this reference point.":`The algebraic ratio gives E=${mode===2?-E:E} GPa. ${mode===2?"Its negative sign contradicts the proposed positive-E model.":"This identifies a conditional slope, not an independently validated full stress-strain law."}`,"Additional nonzero increments, apparatus checks, and unloading evidence are needed to distinguish constitutive behavior from an offset, compliance, or model error."],
      mode===0?"Stress=0, strain=0; modulus is undetermined.":`Stress=${F}/${A} MPa; strain=${2*num}/${1000*den*L2}; candidate E=${mode===2?-E:E} GPa; ${mode===2?"model inconsistent":"conditional identification"}.`);
  }
  if(variant==="poisson"){
    const E=30*rng.integer(1,6),v=[-5,-2,0,2,4,5][rng.integer(0,5)],stress=10*rng.integer(-5,5),incompressible=v===5;
    const fields:unknown[]=[field("shear","Isotropic shear modulus",`${5*E}/${10+v}`,"GPa"),field("axial","Axial strain in microstrain",`${1000*stress}/${E}`,"με"),field("lateral","Each lateral strain in microstrain",`${-100*v*stress}/${E}`,"με"),field("volume","First-order volume strain in microstrain",`${(1000-200*v)*stress}/${E}`,"με")];
    if(!incompressible)fields.push(field("bulk","Isotropic bulk modulus",`${10*E}/${3*(10-2*v)}`,"GPa"));
    fields.push(choice("scope","Scope of the inferred moduli",incompressible?"limit":"isotropic",[
      {id:"isotropic",label:"These relations require homogeneous isotropic small-strain elasticity with the stated finite moduli",feedback:"Uniaxial lateral response links E,G,K only under the isotropic constitutive assumptions. Negative Poisson ratio can be compatible with positive finite moduli."},
      {id:"limit",label:"Nu=1/2 is an incompressible limit; there is no finite positive bulk modulus from this formula",feedback:"E=3K(1−2ν) cannot give finite positive K at ν=1/2 with E>0. Zero first-order volume strain here identifies a limiting incompressible model."},
      {id:"universal",label:"Young modulus and Poisson ratio determine all directional behavior of any material",feedback:"Anisotropic materials need additional directional constitutive information. These isotropic formulas are not universal."},
      {id:"negative",label:"Any negative Poisson ratio necessarily requires negative stored elastic energy",feedback:"For isotropic positive finite E,G,K, the permitted range is −1<ν<1/2. A negative ν inside that interval can describe positive lateral expansion under tension."}
    ]));
    return finish({E,v,stress},`Use a homogeneous isotropic small-strain model with E=${E} GPa and ν=${v}/10 under uniaxial stress ${stress} MPa. Lateral faces are traction-free. Find G, axial strain, each equal lateral strain, and first-order volume strain. Also find finite K when ν<1/2; for ν=1/2 interpret the incompressible limit instead of dividing by zero. Strain fields request numerical microstrain values.`,
      fields,
      ["Use εaxial=σ/E and εlateral=−ν εaxial; multiply dimensionless strains by 10^6 for microstrain.","To first order, volume strain is the sum of the three normal strains.","For isotropy, G=E/[2(1+ν)] and K=E/[3(1−2ν)]. Inspect the denominator before giving K."],
      [`G=${5*E}/${10+v} GPa. Axial and each lateral strain are ${1000*stress}/${E} and ${-100*v*stress}/${E} microstrain.`,`Their sum gives first-order volume strain ${(1000-200*v)*stress}/${E} microstrain. This is a small-strain approximation, not exact finite-volume geometry.`,incompressible?"At ν=1/2, the bulk-modulus relation is a limiting statement with K tending to infinity, not a finite modulus calculation.":`K=${10*E}/${3*(10-2*v)} GPa is positive. Both moduli are conditional on the stated isotropic model.`],
      `G=${5*E}/${10+v} GPa; axial=${1000*stress}/${E}, lateral=${-100*v*stress}/${E}, volume=${(1000-200*v)*stress}/${E} microstrain; ${incompressible?"K has no finite value in this incompressible limit":`K=${10*E}/${3*(10-2*v)} GPa`}.`);
  }
  if(variant==="calibration"){
    const L=rng.integer(1,3),A=rng.integer(1,6),c=rng.integer(2,10),fixture=rng.integer(0,4),offset=rng.integer(-3,3),F1=50*rng.integer(1,4),F2=F1+50*rng.integer(1,4),reading1=100*offset+(c+fixture)*F1,reading2=100*offset+(c+fixture)*F2;
    return finish({L,A,fixture,F1,F2,reading1,reading2},`A synthetic axial measurement uses L=${L} m and A=${A} mm². Apparatus readings are ${reading1}/1000 mm at ${F1} N and ${reading2}/1000 mm at ${F2} N. The readings include an unknown constant zero offset and known fixture compliance ${fixture}/1000 mm/N in series with the specimen. Assume uniform reversible linear specimen response and exact classroom data. Find total compliance, specimen compliance, corrected E, E inferred if fixture compliance is ignored, and the constant reading offset.`,
      [field("total","Apparatus compliance",`${c+fixture}/1000`,"mm/N"),field("specimen","Specimen compliance",`${c}/1000`,"mm/N"),field("modulus","Corrected Young modulus",`${1000*L}/${A*c}`,"GPa"),field("naive","Modulus if fixture compliance is ignored",`${1000*L}/${A*(c+fixture)}`,"GPa"),field("offset","Constant reading offset",`${offset}/10`,"mm")],
      ["Subtract the two readings and divide by the force change. The constant offset cancels.","Series compliances add, so subtract the known fixture compliance to get specimen compliance.","For compliance C in mm/N, E in GPa equals L/(A C), with L in m and A in mm². Recover the reading offset from either point."],
      [`Ctotal=(reading2−reading1)/(F2−F1)=${c+fixture}/1000 mm/N; Cspecimen=${c}/1000 mm/N.`,`Ecorrected=${1000*L}/${A*c} GPa, whereas using total compliance gives ${1000*L}/${A*(c+fixture)} GPa. ${fixture?"Fixture motion would make the material appear less stiff.":"Here the stated fixture compliance is zero, so the two moduli agree."}`,`Offset=reading1−F1 Ctotal=${offset}/10 mm. One raw extension reading cannot distinguish a constant zero error from true displacement; differences remove only a constant offset, not load-dependent fixture motion.`],
      `Compliances=${c+fixture}/1000 and ${c}/1000 mm/N; corrected E=${1000*L}/${A*c} GPa; uncorrected E=${1000*L}/${A*(c+fixture)} GPa; offset=${offset}/10 mm.`);
  }

  if(variant==="uncertainty"){
    const F=50*rng.integer(2,6),dF=rng.integer(1,5),L=rng.integer(1,3),size=rng.integer(2,8),E=20*rng.integer(1,8),round=rng.integer(0,1);
    const low=round?`${400*(F-dF)*(100*L-1)}/${(E+1)*101*101*size*size}`:`${(F-dF)*(100*L-1)}/${10*(E+1)*(10*size+1)}`;
    const high=round?`${400*(F+dF)*(100*L+1)}/${(E-1)*99*99*size*size}`:`${(F+dF)*(100*L+1)}/${10*(E-1)*(10*size-1)}`;
    const stress=round?`${40000*(F+dF)}/${99*99*size*size}`:`${10*(F+dF)}/${10*size-1}`;
    const geometry=round?`diameter d∈[${99*size}/100,${101*size}/100] mm and tensile force F∈[$${F-dF}\\pi$,$${F+dF}\\pi$] N`:`area A∈[${10*size-1}/10,${10*size+1}/10] mm² and tensile force F∈[${F-dF},${F+dF}] N`;
    return finish({F,dF,L,size,E,round},`A supplied uniform axial model is valid throughout these independent allowed input intervals: ${geometry}; L∈[${100*L-1}/100,${100*L+1}/100] m; E∈[${E-1},${E+1}] GPa. Find the smallest and largest extension, largest nominal tensile stress, and largest axial strain. Interpret the bounds without adding a probability model.`,
      [field("lower","Smallest allowed extension",low,"mm"),field("upper","Largest allowed extension",high,"mm"),field("stress","Largest allowed nominal stress",stress,"MPa"),field("strain","Largest allowed axial strain",`(${stress})/${1000*(E-1)}`,"dimensionless"),choice("meaning","Interpretation of the interval","allowed",[
        {id:"allowed",label:"These are extrema of the independent allowed inputs; no probability level follows",feedback:"Monotonic dependence selects permitted corner combinations. The result is a deterministic enclosure, not a confidence interval without further statistical assumptions."},
        {id:"midpoint",label:"Using every midpoint determines the largest possible extension",feedback:"The midpoint calculation is only one allowed case. Largest extension combines larger force and length with smaller area and modulus."},
        {id:"standard",label:"The same endpoints automatically describe one standard deviation",feedback:"Allowed bounds do not specify distributions, correlations, or standard deviations. Those require an explicit measurement model."}
      ])],
      ["For positive inputs, extension increases with F and L and decreases with E and area.","For a circular specimen area depends on d². Apply the actual diameter endpoints before squaring; do not substitute a first-order percentage approximation for exact bounds.","Stress is largest at largest force and smallest area; strain also uses the smallest modulus. The largest extension additionally uses largest length."],
      [`Using the monotone endpoint combinations gives ΔLmin=${low} mm and ΔLmax=${high} mm.`,`Maximum nominal stress is ${stress} MPa, and maximum strain is that stress divided by ${1000*(E-1)} MPa. Length affects extension but not uniform nominal stress or strain at fixed F,A,E.`,round?"The pi in the force cancels the pi in circular area. Diameter uncertainty is squared exactly; the familiar doubled relative sensitivity is only a small-change approximation.":"The area interval is already an area measurement. Do not square its uncertainty again as though it were a diameter interval.","Independence here means every rectangular corner is permitted, not statistical independence or a probability distribution. Correlated bounds would require a joint allowed set."],
      `Extension∈[${low},${high}] mm; maximum stress=${stress} MPa; maximum strain=(${stress})/${1000*(E-1)}; allowed bounds only.`);
  }
  if(variant==="resolution"){
    const n=rng.integer(0,10),h=rng.integer(1,5),L=rng.integer(1,3),F=50*rng.integer(1,6),A=rng.integer(1,8);
    return finish({n,h,L,F,A},`A gauge rounds each position reading to the nearest ${h}/100 mm; no other error is included in this synthetic model. A loaded-minus-unloaded reading is ${n*h}/100 mm across original gauge length ${L} m. Each rounding error can independently lie within half a displayed increment, including the endpoints. Find the instrument-only signed extension and strain bounds before applying a constitutive model. Then consider exact tensile force ${F} N and area ${A} mm² under a finite positive-E uniform linear model: does the admissible positive-extension portion give a finite upper bound on E?`,
      [field("lower","Instrument-only extension lower bound",`${(n-1)*h}/100`,"mm"),field("upper","Instrument-only extension upper bound",`${(n+1)*h}/100`,"mm"),field("strain-lower","Instrument-only strain lower bound",`${(n-1)*h}/${100000*L}`,"dimensionless"),field("strain-upper","Instrument-only strain upper bound",`${(n+1)*h}/${100000*L}`,"dimensionless"),choice("inference","Upper-bound inference for a positive modulus",n>1?"bounded":"unbounded",[
        {id:"bounded",label:"The entire extension interval is positive, so this model gives finite modulus bounds",feedback:"When the smallest extension is strictly positive, E=FL/(AΔL) has a finite maximum at that endpoint. This remains conditional on the supplied error and specimen model."},
        {id:"unbounded",label:"Positive extensions can approach zero, so these readings give no finite upper bound on E",feedback:"Restricting to positive extension leaves arbitrarily small values when the instrument interval includes zero. E then grows without a finite upper bound; E at exactly zero is not computed by division."},
        {id:"zero",label:"Any displayed zero extension proves an infinitely rigid material",feedback:"A rounded reading can hide small finite extension. The resolution model limits inference; it does not prove a physically infinite stiffness."},
        {id:"probability",label:"The rounding increment alone specifies a standard deviation and confidence interval",feedback:"A bound on rounding error is not automatically a probability distribution. The difference of two bounded errors spans a full increment in either direction here."}
      ])],
      ["Subtracting two readings with error magnitude at most h/2 gives a difference error magnitude at most h.","Divide both signed extension endpoints by the original gauge length in the same unit.","For the conditional positive-modulus calculation, inspect whether positive extensions are bounded away from zero."],
      [`The instrument-only extension interval is [${(n-1)*h}/100,${(n+1)*h}/100] mm. Its lower endpoint can be negative even though the subsequently proposed tensile material model requires positive extension.`,`The corresponding strain bounds are ${(n-1)*h}/${100000*L} and ${(n+1)*h}/${100000*L}.`,n>1?"Both extension endpoints are positive, so inversion gives a finite conditional E interval.":"After restricting to positive extension, there is no positive lower endpoint separated from zero. No finite upper E bound follows.","This reasoning does not include fixture compliance, calibration drift, or other uncertainty; it uses exactly the stated independent rounding bounds."],
      `Extension bounds=${(n-1)*h}/100,${(n+1)*h}/100 mm; strain bounds=${(n-1)*h}/${100000*L},${(n+1)*h}/${100000*L}; E upper bound ${n>1?"finite":"not finite from these data"}.`);
  }

  if(variant==="cycle"){
    const E=20*rng.integer(1,8),A=rng.integer(1,8),L=rng.integer(1,3),S=10*rng.integer(1,8),factor=rng.integer(0,3),limit=A*S,peak=limit*factor/2,trusted=Math.min(peak,limit);
    return finish({E,A,L,S,factor,peak},`A hypothetical axial specimen has E=${E} GPa,A=${A} mm²,L=${L} m. Its only supplied constitutive law is reversible σ=Eε for |σ|≤${S} MPa. The intended quasistatic force path is 0→${peak}→0 N. Find the largest force magnitude allowed by that law, the largest force actually reached while the initial loading leg is still established by it, and the extension and stored energy at that last trusted loading state. Decide what the data establish about unloading.`,
      [field("limit","Force magnitude at the constitutive limit",String(limit),"N"),field("trusted","Largest trusted force reached on initial loading",String(trusted),"N"),field("extension","Extension at the last trusted loading state",`${trusted*L}/${E*A}`,"mm"),field("energy","Energy at the last trusted loading state",`${trusted*trusted*L}/${2000*E*A}`,"J"),choice("history","Unloading conclusion",factor<=2?"reversible":"unknown",[
        {id:"reversible",label:"The entire path remains in the supplied reversible range and returns to zero extension and stored energy",feedback:"No excursion beyond the supplied range occurs, including the admitted equality case. The same constitutive line therefore applies on unloading in this stipulated model."},
        {id:"unknown",label:"Loading exceeds the supplied range, so subsequent unloading and residual extension are not established",feedback:"A later small or zero load does not erase the unsupported part of the material history. A plastic or other post-range model would require additional evidence."},
        {id:"always-zero",label:"The final zero force always proves zero extension even after an unsupported overload",feedback:"Zero force can coexist with permanent deformation. Reversible return follows only when the supplied law covers the entire path."},
        {id:"break",label:"Any exceeded linear limit proves that the specimen breaks and has zero stored energy",feedback:"The linear-range boundary is not a fracture law. Neither failure mode nor final energy is determined by extrapolating that boundary."}
      ])],
      ["The admitted force magnitude is area times the supplied stress limit.","On the initial loading leg, use the smaller of the requested peak and that force limit.","Only a path entirely inside the reversible range has established unloading. Do not restart the original law merely because the load later drops."],
      [`The constitutive bound is F=${limit} N. The largest established loading state actually reached is ${trusted} N, with extension ${trusted*L}/${E*A} mm.`,`Its stored energy is ${trusted*trusted*L}/${2000*E*A} J. The requested peak is ${peak} N.`,factor<=2?"The full specified path stays admitted. Linear reversible unloading retraces loading and returns the stored energy.":"The requested peak is outside the supplied law. The trusted loading calculation stops at the bound, and the later unloading state remains unknown from these data."],
      `Limit=${limit} N; trusted reached force=${trusted} N; trusted extension=${trusted*L}/${E*A} mm; trusted energy=${trusted*trusted*L}/${2000*E*A} J; unloading ${factor<=2?"reversible within the supplied law":"not established"}.`);
  }
  if(variant==="control"){
    const F=50*rng.integer(1,6),L=rng.integer(1,3),E=20*rng.integer(1,6),A=rng.integer(1,6),factor=rng.integer(2,4);
    return finish({F,L,E,A,factor},`An original uniform axial specimen has E=${E} GPa,L=${L} m,A=${A} mm² and carries ${F} N in tension. A second specimen has the same E and L but ${factor} times the area. All compared states lie in supplied linear ranges. First hold the force at ${F} N and find the second specimen's extension and energy. Separately impose the original specimen's extension on the second specimen and find its force, stress, and energy.`,
      [field("force-extension","Extension with force held fixed",`${F*L}/${E*A*factor}`,"mm"),field("force-energy","Energy with force held fixed",`${F*F*L}/${2000*E*A*factor}`,"J"),field("held-force","Force with original extension imposed",String(F*factor),"N"),field("held-stress","Stress with original extension imposed",`${F}/${A}`,"MPa"),field("held-energy","Energy with original extension imposed",`${factor*F*F*L}/${2000*E*A}`,"J"),choice("cause","Reason the energy trends differ","control",[
        {id:"control",label:"Fixed force uses U=F²/(2k), while fixed extension uses U=k delta²/2",feedback:"Increasing area raises specimen stiffness. Under fixed force energy decreases, whereas under imposed extension it increases. The controlled quantity is part of the model."},
        {id:"modulus",label:"Increasing area changes the intrinsic Young modulus by the same factor",feedback:"Geometry changes EA/L, not E for the same material model. Modulus and specimen stiffness are different quantities."},
        {id:"always-less",label:"Greater stiffness always means less elastic energy under every loading condition",feedback:"At the same imposed extension a stiffer specimen requires more force and stores more energy. The boundary condition cannot be omitted."}
      ])],
      ["The second stiffness is the area factor times the first stiffness.","At fixed force, extension and energy vary inversely with stiffness.","At fixed extension, force and energy vary with stiffness. Stress stays the same here because force and area increase by the same factor."],
      [`Under fixed force, ΔL₂=${F*L}/${E*A*factor} mm and U₂=${F*F*L}/${2000*E*A*factor} J.`,`The imposed original extension requires F₂=${F*factor} N; dividing by the enlarged area gives the original stress ${F}/${A} MPa.`,`At that imposed extension, U₂=${factor*F*F*L}/${2000*E*A} J. Geometry alone does not specify a response without the load or displacement constraint.`],
      `Fixed force: extension=${F*L}/${E*A*factor} mm, energy=${F*F*L}/${2000*E*A*factor} J. Fixed original extension: force=${F*factor} N, stress=${F}/${A} MPa, energy=${factor*F*F*L}/${2000*E*A} J.`);
  }

  throw Error("Unreachable elasticity variant.");
}
