import { questionSchema, type AnswerField } from "../contracts";
import type { DataTableFigureData } from "../figures";
import { randomFrom } from "../random";
import { phs232Approximate, phs232Choice, phs232Pi, phs232Rational } from "./phs-232-fields";

export const phs232DampingEvidenceFamilyIds = ["phs232-damping-evidence"] as const;
export const phs232DampingEvidenceVariants = ["decrement", "peak-spacing", "energy-balance", "envelope-limit", "settling-definition", "model-rejection"] as const;
const logarithmic = (id: string, label: string, expected: string, unit = ""): AnswerField => ({ id, label, kind: "logarithmic", expected, unit, help: "Keep natural logarithms exact. Use ln(2), ln(4/3), fractions and equivalent supported arithmetic. Do not include unit text." });

export function phs232DampingEvidenceQuestion(familyId: string, variant: string, seed: string, id: string) {
  if (familyId !== "phs232-damping-evidence" || !(phs232DampingEvidenceVariants as readonly string[]).includes(variant)) throw new Error("Unknown PHS 232 damping-evidence family or variant.");
  const rng = randomFrom(`${familyId}:${variant}:${seed}`);
  const massNumerator = rng.integer(1, 8), scale = rng.integer(1, 4), a = rng.integer(1, 8), c = rng.integer(1, 8), sx = rng.integer(0, 1) ? 1 : -1, sv = rng.integer(0, 1) ? 1 : -1;
  const cycles = rng.integer(1, 4), ratioPower = rng.integer(1, 4), elapsed = rng.integer(2, 10), quarter = rng.integer(1, 4), mode = rng.integer(0, 2), gammaNumerator = rng.integer(4, 8), bandNumerator = rng.integer(1, 3);
  const parameters = { massNumerator, scale, a, c, sx, sv, cycles, ratioPower, elapsed, quarter, mode, gammaNumerator, bandNumerator };
  const choice = (id: string, label: string, correct: string, options: [string, string, string][]) => phs232Choice(id, label, correct, rng.shuffle(options));
  const finish = (prompt: string, fields: AnswerField[], hints: string[], explanation: string[], answerSummary: string, figure?: DataTableFigureData) => questionSchema.parse({ id, familyId, familyVersion: 1, courseId: "phs-232", objectiveId: "m01-l03", category: "application", critical: true, parameters, prompt, fields, hints, explanation, answerSummary, ...(figure ? { figure } : {}) });

  if (variant === "decrement") {
    const ratio = 2 ** ratioPower, beta = ratioPower * Math.LN2 / elapsed, wd = 2 * Math.PI * cycles / elapsed, w0 = Math.hypot(beta, wd);
    return finish(`For an ideal free viscously damped oscillator of mass ${massNumerator}/2 kg, a positive displacement maximum is ${a}/100 m. After exactly ${cycles} complete damped cycles and ${elapsed} s, the positive maximum is ${a}/${100 * ratio} m. Treat the supplied quantities as exact model data. Find beta, the logarithmic decrement PER CYCLE, omega_d, omega0 and the viscous coefficient b.`,
      [logarithmic("beta", "Exponential damping rate beta", `${ratioPower}*ln(2)/${elapsed}`, "1/s"), logarithmic("decrement", "Logarithmic decrement per cycle", `${ratioPower}*ln(2)/${cycles}`), phs232Pi("frequency", "Damped angular frequency", `${2 * cycles}*pi/${elapsed}`, "rad/s"), phs232Approximate("natural", "Undamped natural angular frequency", w0, "rad/s"), logarithmic("coefficient", "Viscous coefficient b", `${massNumerator * ratioPower}*ln(2)/${elapsed}`, "kg/s")],
      ["Same-sign peaks separated by whole cycles have the same phase factor. Their ratio is exp(beta*elapsed time).", "Take the natural log of the ratio. Divide by elapsed time for beta, but by the number of cycles for the per-cycle decrement.", "T_d=elapsed time/cycle count, omega_d=2*pi/T_d, omega0=sqrt(omega_d²+beta²), and b=2*m*beta."],
      [`The peak ratio is ${ratio}. Thus beta=ln(${ratio})/${elapsed}=${ratioPower}*ln(2)/${elapsed} 1/s.`, `The per-cycle decrement is ln(${ratio})/${cycles}, not the log ratio across all ${cycles} cycles unless the cycle count is one. T_d=${elapsed}/${cycles} s.`, `omega_d=${2 * cycles}*pi/${elapsed} rad/s and omega0=sqrt(omega_d²+beta²)≈${w0.toFixed(9)} rad/s. The damping lowers the oscillation frequency below the natural parameter.`, `b=2*(${massNumerator}/2)*beta=${massNumerator * ratioPower}*ln(2)/${elapsed} kg/s. beta, b and the dimensionless decrement describe different quantities.`],
      `beta=${ratioPower}*ln(2)/${elapsed} 1/s; decrement=${ratioPower}*ln(2)/${cycles}; omega_d=${2 * cycles}*pi/${elapsed} rad/s; omega0≈${w0.toFixed(9)} rad/s; b=${massNumerator * ratioPower}*ln(2)/${elapsed} kg/s.`);
  }
  if (variant === "peak-spacing") {
    const A = a / 100, firstZero = (Math.PI / 2 + Math.atan(.75)) / (4 * scale), nextPositive = A * Math.exp(-3 * Math.PI / 2);
    return finish(`A free oscillator has omega0=${5 * scale} rad/s, beta=${3 * scale} 1/s and omega_d=${4 * scale} rad/s. It starts at x=A=${a}/100 m with v=0. The next displacement extremum is a negative minimum at t=pi/${4 * scale} s. Determine the full damped phase period, the first positive-time equilibrium crossing, the NEXT POSITIVE maximum, and the coefficient R in the bounding envelope ±R*exp(-beta*t). Decide whether that envelope passes through every true displacement maximum.`,
      [phs232Pi("period", "Full damped phase period", `pi/${2 * scale}`, "s"), phs232Approximate("zero", "First positive-time equilibrium crossing", firstZero, "s"), phs232Approximate("peak", "Next positive displacement maximum", nextPositive, "m", .00000001), phs232Rational("envelope", "Envelope coefficient R", `${5 * a}/400`, "m"), choice("touches", "Does the envelope pass through every true displacement maximum?", "no", [["no", "No: extrema satisfy v=0, not simply cosine equal to one", "Differentiating the decay factor shifts the condition for a displacement extremum. The envelope bounds the curve but need not pass through its peaks."], ["yes", "Yes: the envelope is the curve joining the true peaks", "At the initial maximum, |x|=A while R=5*A/4. These are already different; the decay derivative cannot be omitted."]])],
      ["Opposite-sign adjacent extrema are separated by half a damped period; positive-to-positive maxima are separated by a full period.", "The release-from-rest solution is x=A*exp(-beta*t)[cos(omega_d*t)+(3/4)*sin(omega_d*t)]. Its first zero is in the second quadrant of phase.", "R=A*sqrt(1+(3/4)²). At the next positive maximum the phase advances by 2*pi and the initial bracket is one again."],
      [`T_d=2*pi/${4 * scale}=pi/${2 * scale} s. Doubling the adjacent-extremum interval is essential.`, `Write the bracket as (5/4)*cos(omega_d*t-atan(3/4)). The first positive zero has phase pi/2+atan(3/4), giving t≈${firstZero.toFixed(9)} s. It is later than T_d/4.`, `The next positive maximum is A*exp(-beta*T_d)=(${a}/100)*exp(-3*pi/2)≈${nextPositive.toFixed(12)} m.`, `R=5*A/4=${5 * a}/400 m. At each positive maximum the actual displacement is four fifths of the upper envelope at that time. The two curves do not pass through the same peak points.`],
      `T_d=pi/${2 * scale} s; first zero≈${firstZero.toFixed(9)} s; next positive maximum≈${nextPositive.toFixed(12)} m; R=${5 * a}/400 m; envelope does not pass through the true peaks.`);
  }
  if (variant === "energy-balance") {
    const velocityNumerator = mode === 0 ? 0 : sv * c * scale, energyNumerator = massNumerator * (25 * scale * scale * a * a + velocityNumerator * velocityNumerator), powerNumerator = 3 * massNumerator * scale * velocityNumerator * velocityNumerator;
    return finish(`An unforced oscillator has m=${massNumerator}/2 kg, k=${25 * massNumerator * scale * scale}/2 N/m and b=${3 * massNumerator * scale} kg/s. At the specified instant x=${sx * a}/100 m and v=${velocityNumerator}/100 m/s. Compute its mechanical energy E, the NONNEGATIVE rate of energy transfer to the viscous environment, and signed dE/dt. Later its mechanical energy is one quarter of this E; find the energy transferred over that interval. No other work is done. Select the exact instantaneous power law.`,
      [phs232Rational("energy", "Mechanical energy at the stated instant", `${energyNumerator}/40000`, "J"), phs232Rational("power", "Rate of energy transfer to the environment", `${powerNumerator}/10000`, "W"), phs232Rational("derivative", "Signed mechanical energy derivative", `${-powerNumerator}/10000`, "W"), phs232Rational("transferred", "Energy transferred before E falls to one quarter", `${3 * energyNumerator}/160000`, "J"), choice("law", "Exact instantaneous mechanical energy derivative", "velocity", [["velocity", "dE/dt = -b*v²", "Multiplying m*a+b*v+k*x=0 by v gives the exact mechanical power balance for this model."], ["average", "dE/dt = -2*beta*E at every instant", "That would predict loss at a displaced turning point even when v=0. The phase-dependent instantaneous energy cannot generally be replaced by a simple exponential."], ["direction", "The sign reverses when velocity is negative", "The damper force reverses with velocity too. Their product remains -b*v², so the damper removes mechanical energy for either velocity sign."]])],
      ["Mechanical energy above the spring minimum is m*v²/2+k*x²/2. Keep the two factors of one half.", "Damper force times velocity is (-b*v)*v. The mechanical power is negative or zero; the transfer rate to the environment has the opposite sign.", "Integrating the exact balance gives transferred energy E_initial-E_later when no other work acts. The elapsed time is unnecessary for this energy difference."],
      [`E=[(${massNumerator}/2)*(${velocityNumerator}/100)²+(${25 * massNumerator * scale * scale}/2)*(${sx * a}/100)²]/2=${energyNumerator}/40000 J.`, `The transfer rate b*v²=${powerNumerator}/10000 W, and dE/dt=${-powerNumerator}/10000 W. ${velocityNumerator === 0 ? "Zero power at this turning point is instantaneous: the nonzero spring force will accelerate the mass." : "The squared velocity makes the loss independent of its sign."}`, `The interval transfer is E-E/4=3E/4=${3 * energyNumerator}/160000 J. This is energy, not power.`, "The power law follows directly from the force balance. A fitted amplitude decay or a cycle-averaged energy approximation is not a replacement for that instantaneous identity."],
      `E=${energyNumerator}/40000 J; transfer rate=${powerNumerator}/10000 W; dE/dt=${-powerNumerator}/10000 W; interval transfer=${3 * energyNumerator}/160000 J; exact law -b*v².`);
  }
  if (variant === "envelope-limit") {
    const attenuation = Math.exp(-3 * quarter * Math.PI / 4), factor = quarter % 2 ? 17 / 8 : 1, actual = factor * attenuation;
    return finish(`A viscous oscillator with omega0=${5 * scale} rad/s and beta=${3 * scale} 1/s starts at x=${a}/100 m and v=0. At t=${quarter}*pi/${8 * scale} s, compare the actual mechanical energy E(t) with the proposed formula E_guess=E(0)*exp(-2*beta*t). Find E(t)/E(0), E_guess/E(0), their ratio E(t)/E_guess, and the exact initial derivative E'(0). Decide whether the proposed formula is exact at EVERY time for this nonzero release.`,
      [phs232Approximate("actual", "Actual energy fraction E(t)/E(0)", actual), phs232Approximate("guess", "Proposed energy fraction", attenuation), phs232Rational("ratio", "Actual energy divided by proposed energy", quarter % 2 ? "17/8" : "1"), phs232Rational("initial", "Exact initial energy derivative", "0", "W"), choice("universal", "Is the proposed expression exact at every time for this release?", "no", [["no", "No: compute energy from both coordinates of the state", "At t=0, v=0 gives E'=0. The proposed exponential has a strictly negative derivative there because beta and E(0) are positive."], ["yes", "Yes: a decaying displacement envelope always gives that exact energy", "Kinetic and potential energy have different phase factors. Even agreement at a selected extremum does not establish an identity for every time."]])],
      [`Use x=A*e^(-beta*t)[cos(omega_d*t)+(3/4)sin(omega_d*t)] and v=-(${25 * scale}/4)*A*e^(-beta*t)*sin(omega_d*t), in m and m/s.`, `Here omega_d=${4 * scale} rad/s and omega_d*t=${quarter}*pi/2. Divide m*v²/2+k*x²/2 by k*A²/2.`, "For this release the normalized energy factor is e^(-2*beta*t)[(cos+(3/4)sin)²+(25/16)sin²]. Check the initial power law independently."],
      [`At the requested phase the bracketed energy factor is ${quarter % 2 ? "9/16+25/16=17/8" : "1"}. Thus E/E(0)=${quarter % 2 ? "(17/8)*" : ""}exp(-${3 * quarter}*pi/4)≈${actual.toFixed(9)}.`, `The proposed fraction is exp(-${3 * quarter}*pi/4)≈${attenuation.toFixed(9)}. The ratio is ${quarter % 2 ? "17/8" : "1 at this particular phase"}.`, "At release, E'(0)=-b*v0²=0 W, while the proposed derivative is -2*beta*E(0)<0. The proposed function therefore cannot equal the exact energy for every time.", "A weak-damping cycle average may follow a simple exponential approximately. This question uses instantaneous energy and substantial damping, so that averaging approximation is not being invoked."],
      `Actual fraction≈${actual.toFixed(9)}; proposed fraction≈${attenuation.toFixed(9)}; ratio=${quarter % 2 ? "17/8" : "1"}; E'(0)=0 W; proposed expression not exact for every time.`);
  }
  if (variant === "settling-definition") {
    const gamma = gammaNumerator / 100, band = bandNumerator / 10, end = Math.ceil(Math.log(Math.sqrt(1 + gamma * gamma) / band) / (gamma * Math.PI / 4)) + 2;
    const records = Array.from({ length: 11 }, (_, i) => {
      const n = end - 10 + i, phase = n * Math.PI / 4, attenuation = Math.exp(-gamma * phase);
      const u = (attenuation * (Math.cos(phase) + gamma * Math.sin(phase))).toFixed(6), w = (-Math.sqrt(1 + gamma * gamma) * attenuation * Math.sin(phase)).toFixed(6);
      return { n, u, w, inside: Math.abs(Number(u)) <= band && Math.abs(Number(w)) <= band };
    });
    const first = records.find(record => record.inside)!, lastOutside = records.reduce((index, record, i) => record.inside ? index : i, -1), suffix = records[lastOutside + 1], outside = records.filter(record => !record.inside).length;
    const figure: DataTableFigureData = { kind: "data-table", title: "Finite sampled state record", columns: ["t/T_d", "u = x/A", "w = v/(omega0*A)"], rows: records.map(record => [`${record.n}/8`, record.u, record.w]), note: "Dimensionless simulated values rounded to six decimal places. Judge the printed numbers with inclusive band boundaries. No continuous trajectory or later samples are supplied as evidence for this question." };
    return finish(`Use only the printed record. The joint band requires BOTH |u|≤${bandNumerator}/10 and |w|≤${bandNumerator}/10. Give the first recorded in-band time, the earliest recorded time for which that sample and EVERY LATER PRINTED sample are in band, and the number of printed samples outside the joint band. Express both times as t/T_d. Decide what these finite samples alone establish about all future continuous-time motion.`,
      [phs232Rational("first", "First recorded in-band time t/T_d", `${first.n}/8`), phs232Rational("suffix", "Start of the final all-in-band sample sequence t/T_d", `${suffix.n}/8`), phs232Rational("outside", "Number of printed samples outside the joint band", String(outside)), choice("inference", "What do the finite samples alone prove?", "record", [["record", "Only the stated sampled behavior; permanent continuous settling is not proved", "Between-sample excursions and future behavior are not determined by this finite table alone. A validated model and a suitable future bound can provide additional evidence."], ["first", "The first in-band sample proves permanent settling", "Earlier entries are followed by later exits in this record. A first entry is not the last exit."], ["suffix", "The final in-band sequence proves the state remains there forever", "All later printed samples are in band, but no printed sample reaches all future times or rules out every between-sample excursion."]])],
      ["Check the absolute values of BOTH columns in every row. A small position with excessive speed is outside the joint band.", "Find the first passing row. Separately scan backward from the end until the last failing row; the following row starts the final passing sequence.", "Report only the record's evidence. Do not infer a permanent continuous-time property from a finite list of samples."],
      [`The first printed row satisfying both inequalities is t/T_d=${first.n}/8. It is followed by an outside sample, so this is a temporary recorded entry.`, `The last outside row is t/T_d=${records[lastOutside].n}/8. The next row, ${suffix.n}/8, starts the final sequence in which every remaining printed sample satisfies both bands.`, `${outside} of the 11 printed samples are outside at least one band. Requiring only the position band would answer a different question.`, "Finite sampling establishes neither the exact continuous last-exit time nor permanent future containment. An energy bound under a justified autonomous dissipative model can certify future containment; that is additional reasoning, not information supplied by the samples alone."],
      `First recorded entry=${first.n}/8; final passing sequence starts=${suffix.n}/8; outside samples=${outside}; permanent settling is not proved.`, figure);
  }
  const amplitudes = [8 * a, 4 * a, 2 * a, mode === 1 ? 1.5 * a : a], times = [0, elapsed, 2 * elapsed, (mode === 2 ? 4 : 3) * elapsed];
  const result = ["compatible", "decay", "spacing"][mode], lastRatio = mode === 1 ? "4/3" : "2";
  const figure: DataTableFigureData = { kind: "data-table", title: "Consecutive positive displacement maxima", columns: ["Peak", "Time (s)", "Displacement (mm)"], rows: amplitudes.map((value, i) => [String(i + 1), String(times[i]), value.toFixed(2)]), note: "Synthetic instrument report: each displacement has an absolute bound of ±0.01 mm and each timestamp ±0.001 s. The report identifies these as consecutive positive maxima with no missing peak. Bounds are guaranteed ranges for this exercise, not standard deviations." };
  return finish(`Assess the hypothesis of ONE free underdamped oscillator with constant viscous parameters and no driving force. From peaks 1 and 2, give the nominal fitted beta. Give the nominal logarithmic decrement from peak 3 to peak 4. Taking the stated bounds into account, identify whether the record rules out the hypothesis through changing per-cycle decay, changing positive-peak spacing, or neither. Finally state whether these data alone uniquely identify a different damping mechanism.`,
    [logarithmic("beta", "Nominal beta from the first two peaks", `ln(2)/${elapsed}`, "1/s"), logarithmic("last", "Nominal decrement from peak 3 to peak 4", `ln(${lastRatio})`), choice("diagnosis", "Evidence against a single fixed underdamped viscous model", result, [["compatible", "Neither pattern rules it out within the stated bounds", "Equal positive-peak intervals and a geometric sequence of peak amplitudes are compatible with the model, but finite compatible evidence does not prove it uniquely."], ["decay", "The per-cycle peak ratios disagree beyond the bounds", "One fixed underdamped viscous model predicts a constant logarithmic decrement between consecutive same-sign peaks. Compare the full allowed ratio intervals, not just rounded central values."], ["spacing", "The positive-peak time intervals disagree beyond the bounds", "One fixed underdamped model has constant omega_d and therefore constant spacing between consecutive positive maxima. The no-missing-peak condition matters."]]), choice("unique", "Do these data alone uniquely identify another damping mechanism?", "no", [["no", "No: additional evidence is required", "A contradiction can reject the stated hypothesis without distinguishing nonlinear damping, driving, changing parameters or a flawed measurement model. Compatible data also fail to identify a unique mechanism."], ["yes", "Yes: this record uniquely establishes Coulomb friction", "A short peak record does not uniquely specify the force law. A model comparison needs more discriminating observations and justified uncertainty assumptions."]])],
    ["For consecutive positive maxima, T_d should be constant and ln(A_n/A_(n+1)) should be constant. Fit beta=ln(A1/A2)/(t2-t1).", "A ratio A/B with positive values and absolute bound d lies between (A-d)/(B+d) and (A+d)/(B-d). A time difference has a worst-case bound of ±0.002 s here.", "An incompatible pattern rejects the stated fixed model, but does not uniquely diagnose the physical cause. Honor the explicit no-missing-peak condition."],
    [`The first nominal ratio is 2 and its time interval is ${elapsed} s, so beta=ln(2)/${elapsed} 1/s. The last nominal per-cycle decrement is ln(${lastRatio}).`, mode === 1 ? `The first ratio lies in [${((amplitudes[0] - .01) / (amplitudes[1] + .01)).toFixed(6)}, ${((amplitudes[0] + .01) / (amplitudes[1] - .01)).toFixed(6)}]; the last lies in [${((amplitudes[2] - .01) / (amplitudes[3] + .01)).toFixed(6)}, ${((amplitudes[2] + .01) / (amplitudes[3] - .01)).toFixed(6)}]. These disjoint ranges reject a constant per-cycle decrement. The time intervals agree.` : mode === 2 ? `The first time interval is ${elapsed}±0.002 s and the last is ${2 * elapsed}±0.002 s. These disjoint ranges reject a constant damped period for consecutive positive maxima, even though the nominal amplitude ratios agree.` : `The nominal ratio is 2 in each step and every time interval is ${elapsed} s. These central values lie within all the supplied bounds and admit a single fixed-model fit. Compatibility is not proof of uniqueness.`, "The conclusion uses explicit absolute bounds rather than pretending the printed central values are perfect physical measurements. No probability distribution or confidence percentage was supplied.", "Neither rejection nor compatibility uniquely establishes a different force law. Additional state, force or repeated-run evidence would be needed to distinguish competing explanations."],
    `Nominal beta=ln(2)/${elapsed} 1/s; last decrement=ln(${lastRatio}); diagnosis=${["compatible within stated bounds", "changing per-cycle decay", "changing positive-peak spacing"][mode]}; no unique alternate mechanism.`, figure);
}
