import { questionSchema } from "../contracts";
import { randomFrom } from "../random";

export const phs231FractureAuditVariants=["allowable","concentration","crack","scaling","inspection","fracture-work","cyclic","competing","load-control","evidence"] as const;
export const phs231FractureAuditFamilyIds=["phs231-fracture-audit"];
const field=(id:string,label:string,expected:string,unit:string)=>({id,label,expected,unit,kind:"rational",help:"Enter an exact signed value or equivalent fraction in the labeled unit."});
const numeric=(id:string,label:string,expected:number,unit:string)=>({id,label,expected,unit,kind:"numeric",absoluteTolerance:.00005,relativeTolerance:0,help:"Enter a decimal rounded to five or more places. Absolute tolerance: 0.00005 in the labeled unit."});
const display=(n:number)=>n.toFixed(6);
export function phs231FractureAuditQuestion(familyId:string,variant:string,seed:string,id:string){
  if(familyId!=="phs231-fracture-audit"||!(phs231FractureAuditVariants as readonly string[]).includes(variant))throw Error("Unknown PHS 231 fracture-audit variant.");
  const rng=randomFrom(`${familyId}:${variant}:${seed}`);
  const base={id,familyId,familyVersion:1,courseId:"phs-231",objectiveId:"m08-l03",category:"application",critical:true};
  const choice=(id:string,label:string,correct:string,options:{id:string;label:string;feedback:string}[])=>({id,label,kind:"choice",correct,options:rng.shuffle(options)});
  const finish=(parameters:Record<string,number>,prompt:string,fields:unknown[],hints:string[],explanation:string[],answerSummary:string)=>questionSchema.parse({...base,parameters:Object.fromEntries(Object.entries(parameters).map(([key,value])=>[key,value||0])),prompt,fields,hints,explanation,answerSummary});
  const scope="All properties and criteria below are supplied hypothetical classroom models. They are not equipment ratings or certification of a real structure.";
  const crackScope="Use the supplied opening-mode law KI=Yσ√(πa), with a in meters and stress in MPa. The supplied KIc is valid only under the stated linear-elastic, small-plastic-zone, fixed-geometry-factor assumptions. KI reaching KIc is the criterion boundary; it is not an admitted safety margin.";
  if(variant==="allowable"){
    const S=30*rng.integer(2,12),n=rng.integer(2,5),A=rng.integer(2,12),ratio=rng.integer(1,3),Fnum=S*A*ratio,Fden=2*n;
    return finish({S,n,A,ratio,Fnum,Fden},`${scope} A rule limits nominal tensile stress to supplied strength ${S} MPa divided by factor ${n}. Original area is ${A} mm² and the applied force is ${Fnum}/${Fden} N. Find allowable stress, demanded stress, force cap, and allowable-minus-demand margin. Equality satisfies this classroom inequality but is limiting.`,
      [field("allowable","Allowable nominal stress",`${S}/${n}`,"MPa"),field("demand","Demanded nominal stress",`${S*ratio}/${2*n}`,"MPa"),field("force","Nominal force cap",`${S*A}/${n}`,"N"),field("margin","Allowable-minus-demand margin",`${S*(2-ratio)}/${2*n}`,"MPa"),choice("decision","Specified-rule decision",ratio<=2?"admitted":"fails",[
        {id:"admitted",label:"The stated nominal-stress inequality is satisfied, without establishing other failure modes",feedback:ratio<=2?"Demand is no larger than the supplied allowable stress. Equality is limiting; cracks, fatigue, stability, environment, and other constraints remain separate.":"The stress demand exceeds the supplied allowable value. A positive material strength does not make this particular inequality pass."},
        {id:"fails",label:"The stated nominal-stress inequality fails, without proving immediate fracture",feedback:ratio<=2?"This supplied inequality includes equality, and the computed margin is nonnegative. That limited result is separate from a general safety claim.":"The margin is negative. This violates the supplied design rule, but that rule alone does not predict an instantaneous fracture event."},
        {id:"rating",label:"The calculation certifies indefinite safe use",feedback:"A single supplied stress rule does not cover every failure mechanism, uncertainty, loading history, or relevant engineering requirement."}
      ])],
      ["The factor divides the supplied strength; it does not multiply the applied force capacity upward.","Divide the given force by the stated original area; N/mm² equals MPa.","Compare demand with allowable stress, including equality. A negative margin means failure of the specified inequality."],
      [`Allowable stress is ${S}/${n} MPa and demand is ${S*ratio}/${2*n} MPa. Multiplying allowable stress by area gives a force cap of ${S*A}/${n} N.`,`The margin is ${S*(2-ratio)}/${2*n} MPa. ${ratio<2?"It is positive.":ratio===2?"It is zero, so this is an admitted but limiting classroom state.":"It is negative, so the supplied inequality fails."}`,"The supplied factor is an assessment assumption. It neither identifies every physical failure mode nor certifies equipment."],
      `Allowable ${S}/${n} MPa; demand ${S*ratio}/${2*n} MPa; force cap ${S*A}/${n} N; margin ${S*(2-ratio)}/${2*n} MPa; rule ${ratio<=2?"satisfied":"fails"}.`);
  }
  if(variant==="concentration"){
    const S=30*rng.integer(3,12),Knum=rng.integer(2,8),A=rng.integer(2,10),ratio=rng.integer(1,3),net=rng.integer(0,1),Fnum=S*A*ratio;
    return finish({S,Knum,A,ratio,net,Fnum},`${scope} A supplied elastic stress-concentration factor Kt=${Knum}/2 is explicitly based on the ${net?"net":"gross"} nominal area ${A} mm². With force ${Fnum}/${Knum} N, estimate nominal stress and local peak stress. The local allowable is ${S} MPa. Find the nominal force cap and local margin without changing the factor's reference-area convention.`,
      [field("nominal","Nominal stress using the specified area",`${S*ratio}/${Knum}`,"MPa"),field("local","Estimated local peak stress",`${S*ratio}/2`,"MPa"),field("force","Force cap under this local criterion",`${2*S*A}/${Knum}`,"N"),field("margin","Local allowable-minus-demand margin",`${S*(2-ratio)}/2`,"MPa"),choice("reference","Reference convention","supplied",[
        {id:"supplied",label:`Use the stated ${net?"net":"gross"} area because that is how this Kt was defined`,feedback:"The factor and nominal-stress definition form a matched model. Changing area without re-deriving the factor changes the meaning of the local estimate."},
        {id:"switch",label:`Silently replace the stated area with a ${net?"gross":"net"} area while keeping Kt`,feedback:"A different area convention generally requires a different concentration factor. Do not apply the same number to incompatible reference stresses."},
        {id:"intensity",label:"Treat Kt as KI and compare it directly with crack toughness",feedback:"Kt is dimensionless. Stress intensity KI has stress times square-root-length units and is a different model quantity."}
      ])],
      ["First compute force divided by the exact area used to define Kt.","Multiply that nominal stress by the dimensionless Kt.","Solve Kt(F/A)≤local allowable for F. Keep local stress and nominal force distinct."],
      [`Nominal stress is ${S*ratio}/${Knum} MPa. Multiplying by ${Knum}/2 gives local stress ${S*ratio}/2 MPa.`,`Solving the local inequality gives F≤${2*S*A}/${Knum} N, and the local margin is ${S*(2-ratio)}/2 MPa.`,`This conclusion uses the stated ${net?"net":"gross"} area. It does not establish a crack criterion, and a changed reference area cannot be inserted without changing the model.`],
      `Nominal ${S*ratio}/${Knum} MPa; local ${S*ratio}/2 MPa; force cap ${2*S*A}/${Knum} N; local margin ${S*(2-ratio)}/2 MPa; keep the supplied area convention.`);
  }
  if(variant==="crack"){
    const sigma=20*rng.integer(2,12),aMm=rng.integer(1,9),Ynum=rng.integer(10,18),Y=Ynum/10,K=Y*sigma*Math.sqrt(Math.PI*aMm/1000);let Kc=2*rng.integer(4,25);
    if(Math.abs(K-Kc)<.01)Kc+=1;
    const aCritical=1000*(Kc/(Y*sigma))**2/Math.PI,sigmaCritical=Kc/(Y*Math.sqrt(Math.PI*aMm/1000));
    return finish({sigma,aMm,Ynum,Kc},`${scope} ${crackScope} Here σ=${sigma} MPa, crack length a=${aMm} mm, Y=${Ynum}/10, and KIc=${Kc} MPa √m. Find KI, the criterion crack length at this stress, and the criterion stress at this crack length. Decide whether the applied state reaches the supplied crack criterion.`,
      [numeric("intensity","Applied stress intensity KI",K,"MPa √m"),numeric("length","Criterion crack length at the supplied stress",aCritical,"mm"),numeric("stress","Criterion stress at the supplied crack length",sigmaCritical,"MPa"),choice("criterion","Applied-state crack criterion",K<Kc?"below":"reached",[
        {id:"below",label:"KI is below KIc under the supplied model, without establishing every other constraint",feedback:K<Kc?"The calculated intensity is below the supplied critical value. This conditional crack check does not establish yield, fatigue, inspection adequacy, or general safety.":"The calculated intensity reaches or exceeds the supplied critical value, so it is not below the criterion boundary."},
        {id:"reached",label:"KI reaches or exceeds KIc under the supplied model",feedback:K<Kc?"The intensity is smaller than the supplied critical value; the criterion has not been reached in this model.":"The supplied opening-mode criterion is reached. Its stated assumptions and geometry remain necessary; no subsequent crack-speed history is provided."},
        {id:"nominal",label:"Compare the MPa stress number directly with the MPa √m toughness number",feedback:"These quantities have different dimensions. Compute KI using crack length and the geometry factor before comparing like units."}
      ])],
      ["Convert millimeters to meters inside the square root. The geometry factor is dimensionless.","Solve KIc=Yσ√(πa) for a and for σ separately; convert the resulting a in meters back to millimeters.","Compare KI with KIc in the same units. The displayed numerical tolerance does not change the criterion's meaning."],
      [`a=${aMm}/1000 m gives KI≈${display(K)} MPa √m. Leaving a in millimeters would introduce an erroneous factor √1000.`,`The crack-length boundary is a=(KIc/(Yσ))²/π≈${display(aCritical)} mm. At the specified a, the stress boundary is σ=KIc/(Y√(πa))≈${display(sigmaCritical)} MPa.`,`KI ${K<Kc?"is below":"reaches or exceeds"} KIc. The result is a conditional criterion comparison, not a material-independent strength rating or a prediction of the whole fracture event.`],
      `KI≈${display(K)} MPa √m; criterion a≈${display(aCritical)} mm; criterion σ≈${display(sigmaCritical)} MPa; ${K<Kc?"below":"criterion reached"}.`);
  }
  if(variant==="scaling"){
    const r=rng.integer(2,5),q=rng.integer(2,4),a=rng.integer(1,5),sigma=20*rng.integer(2,10);
    return finish({r,q,a,sigma},`${scope} Assume KI=Yσ√(πa) with the same valid geometry factor and KIc in all comparisons. A crack grows from ${a} mm to ${r*r*a} mm while σ=${sigma} MPa stays fixed. Find the new/old KI ratio and new/old criterion-stress ratio. In a separate comparison, multiply stress by ${q}; find the new/old criterion-crack-length ratio.`,
      [field("intensity","New/old KI ratio",String(r),"dimensionless"),field("stress","New/old criterion-stress ratio",`1/${r}`,"dimensionless"),field("length","Criterion-length ratio after stress multiplication",`1/${q*q}`,"dimensionless"),choice("model","Scope of these ratios","fixed",[
        {id:"fixed",label:"These ratios require the supplied fixed geometry factor and unchanged critical toughness",feedback:"KI scales with square root of crack length only while the other factors are held fixed as stated. Geometry or material-condition changes can invalidate that comparison."},
        {id:"linear",label:"KI always grows in direct proportion to crack length",feedback:"The supplied law contains √a, so multiplying a by r² multiplies KI by r, not r²."},
        {id:"young",label:"A larger Young modulus alone guarantees the same increase in crack toughness",feedback:"Initial elastic slope and crack toughness are separate properties. No relationship between their changes was supplied."}
      ])],
      ["Form a ratio so Y, stress, and pi cancel in the first comparison.","At fixed KIc and Y, criterion stress is proportional to 1/√a.","Solving for criterion a makes it proportional to 1/σ²."],
      [`The crack-length ratio is ${r*r}, so the KI ratio is √${r*r}=${r}. The criterion-stress ratio is its reciprocal, 1/${r}.`,`Multiplying stress by ${q} changes the criterion crack length by 1/${q*q}. These are different controlled comparisons.`,"Do not transfer these ratios to a geometry in which Y changes or to conditions with a different valid toughness."],
      `KI ratio ${r}; criterion-stress ratio 1/${r}; criterion-length ratio 1/${q*q}; conditional on fixed Y and KIc.`);
  }
  if(variant==="inspection"){
    const sigma=50*rng.integer(2,5),dSigma=5*rng.integer(1,3),Ynum=rng.integer(10,18),mode=rng.integer(0,2),aLow=mode===2?rng.integer(1,4):rng.integer(0,3),aHigh=aLow+rng.integer(1,5);
    const low=Ynum/10*(sigma-dSigma)*Math.sqrt(Math.PI*aLow/1000),high=Ynum/10*(sigma+dSigma)*Math.sqrt(Math.PI*aHigh/1000),Kc=mode===0?Math.ceil(high)+5:mode===2?Math.max(1,Math.floor(low/2)):Number(((low+high)/2).toFixed(4));
    const result=high<Kc?"all":low>=Kc?"none":"mixed";
    return finish({sigma,dSigma,Ynum,aLow,aHigh,Kc},`${scope} ${crackScope} Stress lies in [${sigma-dSigma}, ${sigma+dSigma}] MPa and crack length a lies in [${aLow}, ${aHigh}] mm. All endpoint combinations are allowed; Y=${Ynum}/10 and KIc=${Kc} MPa √m are fixed. Find the smallest and largest allowed KI and the worst-case KIc−KI margin. Classify the entire allowed set, keeping possible undetected flaws distinct from an assertion of zero crack length.`,
      [numeric("lower","Smallest allowed KI",low,"MPa √m"),numeric("upper","Largest allowed KI",high,"MPa √m"),numeric("margin","Worst-case KIc minus KI",Kc-high,"MPa √m"),choice("set","Allowed-set criterion",result,[
        {id:"all",label:"Every allowed state stays strictly below the supplied crack criterion",feedback:result==="all"?"Even the largest allowed KI is below KIc, so the whole supplied uncertainty set passes this limited crack comparison.":"The largest allowed KI is not below KIc; checking a central estimate cannot certify every allowed endpoint combination."},
        {id:"mixed",label:"Some allowed states are below the criterion and some reach or exceed it",feedback:result==="mixed"?"KIc lies inside the allowed intensity range. These bounds cannot establish that every possible state stays below the criterion.":"Compare both endpoint intensities. This set is wholly below or wholly at/above the threshold rather than straddling it."},
        {id:"none",label:"Every allowed state reaches or exceeds the supplied criterion",feedback:result==="none"?"Even the smallest allowed KI reaches the threshold, so no allowed state remains strictly below it.":"At least the lower endpoint is below the threshold. Do not label the entire interval as reaching the criterion."}
      ]),choice("inspection","What does a detection bound establish?","bound",[
        {id:"bound",label:"A bounded possible flaw size; it does not turn a possible undetected crack into zero size",feedback:"Inspection information restricts an allowed set. Only the supplied bound, not an invented no-flaw claim, belongs in the criterion calculation."},
        {id:"zero",label:"Any crack not directly seen must have exactly zero length",feedback:"Finite detection capability can leave smaller flaws undetected. Absence of detection is not proof of absence."},
        {id:"confidence",label:"The allowed endpoints automatically specify a confidence level",feedback:"No probability distribution or coverage statement was supplied. These are deterministic allowed bounds."}
      ])],
      ["For nonnegative a and positive stress, KI increases with both quantities.","Use both lower endpoints for the minimum and both upper endpoints for the maximum. Convert a to meters inside the square root.","Compare the entire KI interval with KIc. Equality reaches the criterion rather than providing a positive crack margin."],
      [`Allowed KI ranges from ${display(low)} to ${display(high)} MPa √m. The worst-case margin is ${display(Kc-high)} MPa √m.`,`${result==="all"?"The entire interval is strictly below KIc.":result==="none"?"The entire interval is at or above KIc.":"The interval straddles KIc, so the supplied bounds do not establish a uniform outcome."}`,"This is a conditional comparison of an allowed set. It does not establish a probability of failure, perfect detection, or other service-life constraints."],
      `KI interval [${display(low)}, ${display(high)}] MPa √m; worst-case margin ${display(Kc-high)} MPa √m; ${result==="all"?"all below":result==="none"?"all reach the criterion":"mixed outcomes"}.`);
  }
  if(variant==="fracture-work"){
    const resistance=500*rng.integer(2,12),areaMicro=rng.integer(1,20),ratio=rng.integer(1,3),energyNum=resistance*areaMicro*ratio;
    return finish({resistance,areaMicro,ratio,energyNum},`${scope} A supplied crack-advance model makes ${energyNum}/2000000 J available for a newly advanced projected crack area ${areaMicro}/1000000 m². Its resistance is ${resistance} J per square meter of that projected area, already accounting for both new physical surfaces. Find release rate G, required resistance work for this area, and resistance-minus-G margin. In this model G≥resistance makes advance energetically possible; no rate law is supplied.`,
      [field("release","Available energy release per projected area",`${resistance*ratio}/2`,"J/m²"),field("required","Resistance work for the stated advance",`${resistance*areaMicro}/1000000`,"J"),field("margin","Resistance minus release rate",`${resistance*(2-ratio)}/2`,"J/m²"),choice("criterion","Energy criterion",ratio<2?"below":"possible",[
        {id:"below",label:"Available release is below the supplied resistance for this advance",feedback:ratio<2?"The available energy per area is less than the required resistance, so this supplied energy criterion is not reached.":"Available release reaches or exceeds the supplied resistance; it is not below the energy criterion."},
        {id:"possible",label:"The energy criterion is met; the model does not determine an actual crack speed or complete failure history",feedback:ratio<2?"The available release is below resistance, so the supplied energetic condition is not met.":"G is at least the resistance. This is an energetic condition, not a supplied kinetic law or a prediction of every stage of fracture."},
        {id:"double",label:"Double the resistance again because every crack has two surfaces",feedback:"The stated resistance already accounts for both surfaces per projected advance area. Doubling it again would count them twice."}
      ])],
      ["Divide the available energy by the specified projected advance area.","Required work is the supplied resistance times that same area convention.","Check G against resistance, including equality. An energy criterion does not supply a time or crack speed."],
      [`G=(${energyNum}/2000000)/(${areaMicro}/1000000)=${resistance*ratio}/2 J/m². Required resistance work is ${resistance*areaMicro}/1000000 J.`,`The resistance-minus-G margin is ${resistance*(2-ratio)}/2 J/m², so the supplied energetic criterion is ${ratio<2?"not reached":"met"}.`,"Energy per advanced area is different from work per specimen volume and from stress intensity. The two-surface convention is already contained in the supplied resistance."],
      `G=${resistance*ratio}/2 J/m²; required work ${resistance*areaMicro}/1000000 J; margin ${resistance*(2-ratio)}/2 J/m²; ${ratio<2?"below resistance":"advance energetically possible, rate unknown"}.`);
  }
  if(variant==="cyclic"){
    const high=20*rng.integer(3,12),kind=rng.integer(0,3),low=[-high,0,high/2,-2*high][kind],N=1000*rng.integer(1,100);
    return finish({high,low,N},`${scope} A hypothetical stress cycle runs between σmin=${low} MPa and σmax=${high} MPa. After ${N} completed cycles under these particular test conditions, the specimen has not fractured. Find stress amplitude, mean stress, and R=σmin/σmax. Interpret the survival observation without inventing an S–N curve or a failure-life distribution.`,
      [field("amplitude","Cyclic stress amplitude",`${high-low}/2`,"MPa"),field("mean","Mean stress",`${high+low}/2`,"MPa"),field("ratio","Stress ratio R",`${low}/${high}`,"dimensionless"),choice("life","Life evidence","survival",[
        {id:"survival",label:"The specimen survived the stated cycles; its eventual failure cycle and indefinite endurance are not established",feedback:"This observation is a survival lower bound under specified conditions. A failure event, a validated life model, and variability evidence are needed for a stronger claim."},
        {id:"failure",label:`The failure life is exactly ${N} cycles`,feedback:"The specimen has not failed at the end of the stated observation. The run length is not a measured failure cycle."},
        {id:"infinite",label:"Surviving the run establishes unlimited fatigue life at this stress",feedback:"A finite survival observation cannot establish indefinite endurance, and a monotone or single-run record does not provide a universal fatigue-life model."}
      ])],
      ["Amplitude is half the range, not the maximum stress unless the cycle is fully reversed.","Mean stress is the midpoint of the signed extremes. A negative mean is possible.","Compute R from the signed minimum and positive maximum. Keep an observation of survival separate from a failure-time measurement."],
      [`Amplitude=(${high}−(${low}))/2=${high-low}/2 MPa. Mean=(${high}+(${low}))/2=${high+low}/2 MPa, and R=${low}/${high}.`,`No fracture was observed through ${N} cycles; the eventual failure cycle, if any, lies beyond the observation.`,"Transferring such evidence to another mean stress, temperature, environment, specimen geometry, or frequency needs additional validation. The numerical cycle descriptors alone do not supply a life."],
      `Amplitude ${high-low}/2 MPa; mean ${high+low}/2 MPa; R=${low}/${high}; finite survival evidence, eventual failure life unknown.`);
  }
  if(variant==="competing"){
    const sigma=40*rng.integer(1,5),n=rng.integer(2,4),aMm=rng.integer(1,9),Ynum=rng.integer(10,18),mode=rng.integer(0,3),yieldPass=mode===0||mode===2,crackPass=mode===0||mode===1;
    const S=yieldPass?n*sigma*rng.integer(1,2):n*sigma/2,K=Ynum/10*sigma*Math.sqrt(Math.PI*aMm/1000),Kc=crackPass?Math.ceil(K)+5:Math.max(1,Math.floor(K/2)),yieldUse=n*sigma/S,crackUse=K/Kc;
    const result=yieldPass?(crackPass?"both":"crack"):(crackPass?"yield":"neither");
    return finish({sigma,n,aMm,Ynum,S,Kc},`${scope} One rule requires σ≤strength/factor, with strength ${S} MPa and factor ${n}. A separate crack rule requires KI<KIc, with a=${aMm} mm, Y=${Ynum}/10, and KIc=${Kc} MPa √m. Applied σ=${sigma} MPa. Use KI=Yσ√(πa) under its supplied valid assumptions. Find utilization for each criterion, each dimensional margin, and which checks fail. A utilization of one is included in the first rule but reaches the critical crack boundary in the second.`,
      [field("yield-use","Nominal-stress utilization",`${n*sigma}/${S}`,"dimensionless"),numeric("crack-use","Crack-intensity utilization",crackUse,"dimensionless"),field("yield-margin","Allowable nominal stress minus demand",`${S-n*sigma}/${n}`,"MPa"),numeric("crack-margin","KIc minus applied KI",Kc-K,"MPa √m"),choice("decision","Combined supplied criteria",result,[
        {id:"both",label:"Both supplied checks pass",feedback:result==="both"?"The nominal utilization is at most one and crack utilization is strictly below one. This is still only the pair of specified checks.":"At least one specified condition fails. Passing the other condition does not remove that failure."},
        {id:"yield",label:"The nominal-stress rule fails; the crack-intensity rule passes",feedback:result==="yield"?"Nominal utilization exceeds one while KI remains below KIc. The criteria are separate.":"Compare each utilization against its own stated boundary; this label does not match both calculated results."},
        {id:"crack",label:"The crack-intensity rule fails; the nominal-stress rule passes",feedback:result==="crack"?"The nominal stress fits its supplied rule, but KI reaches or exceeds KIc. A stress-factor pass does not establish crack tolerance.":"Compare each utilization against its own stated boundary; this label does not match both calculated results."},
        {id:"neither",label:"Both supplied checks fail",feedback:result==="neither"?"The nominal utilization exceeds one and the crack criterion is reached. Neither supplied check passes.":"At least one of these two supplied checks passes. Distinguish their dimensions and inequality conventions."}
      ])],
      ["Normalize nominal stress by strength/factor.","Convert a to meters, calculate KI, then divide by KIc. Do not compare a stress number directly with a stress-intensity number.","Evaluate each inequality with its stated equality convention; report both margins in their own units."],
      [`Nominal utilization is ${n*sigma}/${S}=${display(yieldUse)}, with stress margin ${S-n*sigma}/${n} MPa.`,`KI≈${display(K)} MPa √m, giving crack utilization ${display(crackUse)} and margin ${display(Kc-K)} MPa √m.`,`The supplied nominal rule ${yieldPass?"passes":"fails"} and the supplied crack rule ${crackPass?"passes":"fails"}. Neither calculation supplies omitted fatigue, stability, environment, or inspection requirements.`],
      `Nominal utilization ${n*sigma}/${S}; crack utilization ≈${display(crackUse)}; nominal margin ${S-n*sigma}/${n} MPa; crack margin ≈${display(Kc-K)} MPa √m; ${result==="both"?"both pass":result==="neither"?"both fail":result+" check fails"}.`);
  }
  if(variant==="load-control"){
    const peak=100*rng.integer(5,15),first=rng.integer(1,5),last=first+rng.integer(1,6),fraction=rng.integer(1,3),end=peak*fraction/4;
    return finish({peak,first,last,fraction},`A supplied hypothetical force–extension record is linear from (0 mm,0 N) to (${first} mm,${peak} N), then to (${last} mm,${end} N) before a documented endpoint event. Prescribed extension increased along the entire record. Find the descending-segment slope, its force change, and positive input work on that segment. Explain why the record alone does not establish stable continuation under monotonically increasing force control.`,
      [field("slope","Descending-segment force/extension slope",`${peak*(fraction-4)}/${4*(last-first)}`,"N/mm"),field("change","Signed force change on that segment",`${peak*(fraction-4)}/4`,"N"),field("work","Input work on that segment",`${peak*(4+fraction)*(last-first)}/8000`,"J"),choice("control","Control interpretation","conditional",[
        {id:"conditional",label:"The descending record requires its stated displacement control; a force-controlled continuation needs a separate stability and apparatus model",feedback:"Extension rises while recorded force falls. Increasing force cannot simply trace that same segment; the control apparatus and stability matter."},
        {id:"same",label:"Any force-controlled test must follow the same descending segment while force increases",feedback:"Along the segment, the recorded force decreases as extension increases. That conflicts with the proposed monotonically increasing force path."},
        {id:"negative",label:"A negative slope makes the positive-force loading work negative",feedback:"Work is the integral of force over displacement, not the derivative of force. Positive force acting through increasing extension gives positive input work here."}
      ])],
      ["Slope is force difference divided by extension difference; preserve its negative sign.","Work uses average positive force times the positive extension interval.","Convert N mm to joules by dividing by 1000. A descending curve is not a control-independent stability claim."],
      [`The force change is ${peak*(fraction-4)}/4 N over ${last-first} mm, so the slope is ${peak*(fraction-4)}/${4*(last-first)} N/mm.`,`The trapezoid area is ${peak*(4+fraction)*(last-first)}/8000 J, which is positive even though the slope is negative.`,"A stress or force record under one control mode does not define a stable path under every other control mode. It also does not by itself identify the local true-stress evolution in a neck."],
      `Slope ${peak*(fraction-4)}/${4*(last-first)} N/mm; force change ${peak*(fraction-4)}/4 N; work ${peak*(4+fraction)*(last-first)}/8000 J; control and stability remain conditional.`);
  }
  if(variant==="evidence"){
    const mode=rng.integer(0,3),S=20*rng.integer(2,15),k=rng.integer(1,10);
    if(mode===0)return finish({mode,S,k},`A synthetic loading record contains engineering stress ${S} MPa at strain ${k}/1000. No unloading or fracture record is available. Find the secant modulus to that point and identify what it does not establish.`,
      [field("secant","Secant modulus to the supplied point",`${S}/${k}`,"GPa"),choice("claim","Permitted inference","limited",[
        {id:"limited",label:"The secant is calculable; permanent set, recovery, and fracture behavior remain undetermined",feedback:"A stress-to-strain ratio at one loaded state is not a loading/unloading history or a fracture observation."},
        {id:"recovery",label:"The ratio proves complete recovery after unloading",feedback:"The same loaded point can belong to different reversible or irreversible histories. No unloading law was supplied."},
        {id:"initial",label:"This secant must equal the initial tangent modulus",feedback:"A total ratio to a finite-strain point need not equal the slope at the origin."}
      ])],
      ["A secant modulus is stress divided by strain.","The quotient is in MPa; divide by 1000 for GPa.","List the observations missing for a statement about recovery or fracture."],
      [`Secant modulus=(${S}/(${k}/1000))/1000=${S}/${k} GPa.`,"Only the ratio to this loaded point follows. An unloading path is needed to establish residual strain or recoverable work; an endpoint observation is needed for fracture.","No initial tangent or full failure record can be reconstructed uniquely from one point."],
      `Secant ${S}/${k} GPa; recovery, permanent set, initial tangent, and fracture behavior are not established by this point alone.`);
    if(mode===1){
      const last=S*k/12;
      return finish({mode,S,k},`A hypothetical recording reaches a maximum engineering stress ${S} MPa, later reads ${S*k}/12 MPa, and then the instrument stops recording. There is no reported fracture event. Find the last/maximum stress ratio and decide whether the final point establishes fracture stress or the eventual ultimate tensile strength of a complete test.`,
        [field("ratio","Last/recorded-maximum stress ratio",`${k}/12`,"dimensionless"),field("last","Last recorded engineering stress",`${S*k}/12`,"MPa"),choice("claim","Endpoint interpretation","limited",[
          {id:"limited",label:"Only the available recorded values are established; recording termination does not prove fracture or completion of the test",feedback:"A data gap or stopped instrument is not itself a failure observation. The maximum of a partial record need not be the eventual maximum of the completed test."},
          {id:"fracture",label:"The last value is necessarily the fracture stress",feedback:"The record ended without a reported fracture event. Do not add an event that was not observed."},
          {id:"ultimate",label:"The recorded maximum must be the eventual ultimate tensile strength",feedback:"A partial record may omit later behavior. Only its observed maximum is established without a completed-test assumption."}
        ])],
        ["Divide last stress by recorded maximum; the common stress scale cancels.","Distinguish a recorded quantity from an inferred event.","A complete tensile test or an explicit endpoint event would supply information absent here."],
        [`The last/maximum ratio is ${k}/12 and the last recorded stress is ${S*k}/12≈${display(last)} MPa.`,"Neither value supplies an unobserved fracture event. A recording can stop for reasons unrelated to the specimen.","Report the maximum of the available record with its scope, rather than naming it the eventual ultimate strength of an unfinished test."],
        `Ratio ${k}/12; final recorded stress ${S*k}/12 MPa; fracture and complete-test ultimate strength are not established.`);
    }
    if(mode===2)return finish({mode,S,k},`A hypothetical old tensile test at 20 °C supplied a classroom allowable stress ${2*S} MPa for those conditions. A later scenario uses nominal stress ${S} MPa at 80 °C for ${100*k} hours. Compute the arithmetic margin against the old number, then state whether it establishes an allowable value for the new temperature and sustained-load duration. No transfer or creep model is supplied.`,
      [field("margin","Arithmetic margin against the old supplied value",String(S),"MPa"),choice("claim","Transfer to the new conditions","limited",[
        {id:"limited",label:"The arithmetic margin is positive, but validity at the new temperature and duration is not established",feedback:"A numerical comparison does not validate transferring material behavior across temperature and time-dependent conditions. The old test's scope matters."},
        {id:"same",label:"The old test guarantees the same allowable value at every temperature and duration",feedback:"Temperature and sustained loading can change material response. No transfer or creep law was provided."},
        {id:"failure",label:"Any changed temperature proves immediate fracture",feedback:"Missing validity evidence does not prove a particular failure event. It limits what can be concluded from the old record."}
      ])],
      ["Subtract the new demand from the old numerical allowable.","Separate that arithmetic result from validation of the allowable under changed conditions.","Identify the missing temperature and time-dependent material evidence."],
      [`The arithmetic margin is ${2*S}−${S}=${S} MPa.`,`The old value came from 20 °C conditions and does not establish behavior at 80 °C over ${100*k} hours without further evidence.`,"The correct conclusion is limited evidence, not either guaranteed safety or guaranteed immediate fracture."],
      `Arithmetic margin ${S} MPa; transfer to the changed temperature and duration remains unvalidated.`);
    const returned=S*k/12;
    return finish({mode,S,k},`A hypothetical loading/unloading measurement records input work ${S} J and returned mechanical work ${S*k}/12 J. Find nonreturned work. No temperature, internal-structure, damage, or other energy measurements are supplied. What partition of that nonreturned energy is established?`,
      [field("difference","Nonreturned mechanical work",`${S*(12-k)}/12`,"J"),choice("claim","Energy partition","limited",[
        {id:"limited",label:"The work difference is established; its partition into heat and other internal changes is not",feedback:"Mechanical input minus mechanical return is an account of nonreturned work. Additional evidence is needed to separate heating, stored structural changes, damage, and other mechanisms."},
        {id:"heat",label:"All of the work difference is measured heat",feedback:"No thermal measurement or complete thermodynamic model was supplied. A work difference alone does not prove its entire partition."},
        {id:"lost",label:"The work difference means energy conservation has failed",feedback:"Energy not returned mechanically can appear in other forms. A complete system energy account must include them."}
      ])],
      ["Subtract returned mechanical work from input work.","Keep the joule unit: this is a specimen work difference, not automatically an energy density.","Ask which other measurements would distinguish heat from structural or damage energy."],
      [`Returned work is ${S*k}/12≈${display(returned)} J. Nonreturned work is ${S*(12-k)}/12 J.`,"The mechanical difference is known, but the given observations do not identify every destination of that energy.","Energy conservation remains compatible with heat and internal changes; it does not make any one partition known without evidence."],
      `Nonreturned work ${S*(12-k)}/12 J; energy partition remains undetermined.`);
  }

  throw Error("Unreachable fracture-audit variant.");
}
