import { questionSchema, type AnswerField } from "../contracts";
import { randomFrom } from "../random";
import { phs232Choice, phs232Exact, phs232Pi, phs232Rational } from "./phs-232-fields";

export const phs232WaveSuperpositionFamilyIds = ["phs232-wave-superposition"] as const;
export const phs232WaveSuperpositionVariants = ["phase-resultant", "fixed-reflection", "free-reflection", "node-location", "net-power", "coherent-intensity", "interface-amplitude", "interface-power"] as const;
export function phs232WaveSuperpositionQuestion(familyId: string, variant: string, seed: string, id: string) {
  if (familyId !== "phs232-wave-superposition" || !(phs232WaveSuperpositionVariants as readonly string[]).includes(variant)) throw Error("Unknown PHS 232 wave-superposition family or variant.");
  const rng = randomFrom(familyId + ":" + variant + ":" + seed), a = rng.integer(1, 8), mode = rng.integer(0, 3), b = mode === 0 ? a : rng.integer(1, 8);
  const k = rng.integer(1, 4), c = rng.integer(3, 9), m = rng.integer(1, 7), phaseIndex = rng.integer(0, 3), zLeft = rng.integer(1, 5), zRight = rng.integer(1, 5), frequencyScale = rng.integer(1, 4);
  const parameters = { a, b, mode, k, c, m, phaseIndex, zLeft, zRight, frequencyScale }, omega = k * c, cosine = [1, 0, -1, 0][phaseIndex], sine = [0, 1, 0, -1][phaseIndex];
  const choice = (id: string, label: string, correct: string, options: [string, string, string][]) => phs232Choice(id, label, correct, rng.shuffle(options));
  const finish = (prompt: string, fields: AnswerField[], hints: string[], explanation: string[], answerSummary: string) => questionSchema.parse({ id, familyId, familyVersion: 1, courseId: "phs-232", objectiveId: "m02-l02", category: "application", critical: true, parameters, prompt, fields, hints, explanation, answerSummary });
  const medium = "Use an ideal linear, lossless string with mu=" + m + "/1000 kg/m, tension F_T=" + m * c * c + "/1000 N, k=" + k + " rad/m and omega=" + omega + " rad/s. Coordinates are in meters and seconds; positive power is toward +x.";
  if (variant === "phase-resultant") {
    const real = a + b * cosine, imaginary = b * sine, square = real * real + imaginary * imaginary, phase = square === 0 ? "undefined" : imaginary > 0 ? "first" : imaginary < 0 ? "fourth" : real < 0 ? "pi" : "zero";
    return finish("Two coherent rightward waves are y1=(" + a + "/1000)*cos(theta) and y2=(" + b + "/1000)*cos(theta+" + phaseIndex + "*pi/2), in meters, with theta=" + k + "*x-" + omega + "*t. Write their sum as X*cos(theta)-Y*sin(theta)=C*cos(theta+alpha), C>=0 and -pi<alpha<=pi. Find X, Y, C and the phase classification.",
      [phs232Rational("real", "Coefficient X", real + "/1000", "m"), phs232Rational("imaginary", "Coefficient Y", imaginary + "/1000", "m"), phs232Exact("amplitude", "Nonnegative resultant amplitude C", "sqrt(" + square + ")/1000", "m"),
        choice("phase", "Resultant phase alpha", phase, [["zero", "Zero", "A positive cosine coefficient with zero sine coefficient has alpha=0."], ["pi", "Pi radians", "A negative cosine coefficient is represented by a positive amplitude and alpha=pi."], ["first", "First quadrant", "Both X and Y are positive; atan2(Y,X) lies in the first quadrant."], ["fourth", "Fourth quadrant", "X is positive and Y is negative, so the principal phase is negative."], ["undefined", "Undefined because the resultant vanishes", "When both coefficients vanish there is no nonzero resultant whose phase could be determined."]])],
      ["Expand cos(theta+delta)=cos(theta)*cos(delta)-sin(theta)*sin(delta). Match the stated minus sign before Y.", "C is the length of the coefficient vector (X,Y), so it cannot be negative.", "Use both coefficient signs for the phase. If X=Y=0, assigning alpha=0 would falsely identify a phase."],
      ["X=A+B*cos(delta)=" + real + "/1000 m and Y=B*sin(delta)=" + imaginary + "/1000 m.", "C²=X²+Y²=" + square + "/1000000 m², hence C=sqrt(" + square + ")/1000 m.", "For C>0, cos(alpha)=X/C and sin(alpha)=Y/C. The stated principal-phase classification is " + phase + ".", "For C=0 the field is identically zero and the phase is undefined. A negative signed coefficient would require a phase change, not a negative amplitude."],
      "X=" + real + "/1000 m; Y=" + imaginary + "/1000 m; C=sqrt(" + square + ")/1000 m; phase=" + phase + ".");
  }
  if (variant === "fixed-reflection" || variant === "free-reflection") {
    const fixed = variant === "fixed-reflection", r = fixed ? -1 : 1, power = -m * c * a * a * omega * omega;
    return finish(medium + " The string occupies x<=0 and ends at an ideal " + (fixed ? "fixed" : "massless freely sliding") + " boundary at x=0. The incident field is yi=(" + a + "/1000)*cos(k*x-omega*t); write yr=Ar*cos(k*x+omega*t), with signed coefficient Ar. Find r=Ar/A, Ar, boundary displacement amplitude and signed mean reflected power. Then choose the required boundary condition and the reflected shape for a general incident pulse f(x-c*t).",
      [phs232Rational("reflection", "Signed displacement reflection coefficient r", String(r)), phs232Rational("reflected", "Signed reflected displacement coefficient Ar", r * a + "/1000", "m"),
        phs232Rational("boundary", "Boundary displacement amplitude", (fixed ? 0 : 2 * a) + "/1000", "m"), phs232Rational("power", "Signed mean reflected power", power + "/2000000000", "W"),
        choice("condition", "All-time boundary condition", fixed ? "displacement" : "slope", [["displacement", "Zero displacement", "A fixed support stays at y=0; incident and reflected displacements cancel there."], ["slope", "Zero transverse slope", "A massless free endpoint has zero transverse force, so its slope vanishes; displacement need not vanish."]]),
        choice("pulse", "Reflected pulse on x<=0", fixed ? "inverted" : "same", [["inverted", "-f(-x-c*t)", "This travels left and cancels f(-c*t) at the fixed endpoint."], ["same", "f(-x-c*t)", "This travels left and cancels the incident slope at the free endpoint."], ["right", "-f(x-c*t)", "Changing the sign without reversing the x dependence does not produce a reflected leftward pulse."]])],
      ["At x=0 the two cosine factors agree. A fixed support cancels displacement; a free endpoint cancels spatial slope.", "The free endpoint can move through twice the incident amplitude even though no energy crosses it.", "Reflected energy travels toward -x for either displacement sign. Its mean power is negative and proportional to Ar squared."],
      ["The boundary equation gives r=" + r + " and Ar=" + r * a + "/1000 m. A negative Ar encodes a pi phase inversion.", "The total boundary displacement coefficient is A+Ar, giving amplitude " + (fixed ? "0" : 2 * a + "/1000") + " m.", "Mean reflected P=-mu*c*omega²*Ar²/2=" + power + "/2000000000 W. The sign of r does not decide the power direction.", "For a pulse, reversing x in f(x-c*t) yields leftward f(-x-c*t). Its " + (fixed ? "negative sign enforces zero displacement" : "positive sign enforces zero slope") + " at x=0.", "Boundary power is zero because " + (fixed ? "boundary velocity" : "transverse force") + " is zero; internal instantaneous power need not be zero."],
      "r=" + r + "; Ar=" + r * a + "/1000 m; boundary amplitude=" + (fixed ? 0 : 2 * a) + "/1000 m; reflected P=" + power + "/2000000000 W.");
  }
  if (variant === "node-location") {
    const numerator = (6 - phaseIndex) % 4;
    return finish(medium + " Superpose y1=(" + a + "/1000)*cos(k*x-omega*t) and y2=(" + a + "/1000)*cos(k*x+omega*t+" + phaseIndex + "*pi/2). On the unbounded string find the first permanent displacement node at x>=0, the spacing between nodes, and the first time t>=0 when the entire field has zero displacement. Does that single frame make every point a permanent node?",
      [phs232Pi("node", "First node at nonnegative x", numerator + "*pi/" + 4 * k, "m"), phs232Pi("spacing", "Node spacing", "pi/" + k, "m"), phs232Pi("flat", "First all-zero displacement time at t>=0", numerator + "*pi/" + 4 * omega, "s"),
        choice("everywhere", "Does one all-zero frame make every point a node?", "no", [["no", "No: most points are crossing equilibrium", "A permanent node remains stationary at every time; the time factor can vanish while local velocity is nonzero."], ["yes", "Yes: every zero displacement is a node", "A snapshot cannot establish an all-time constraint. Check the amplitude and the time derivative."]])],
      ["The sum is 2*A*cos(k*x+delta/2)*cos(omega*t+delta/2). Spatial and temporal zeros have different meanings.", "Solve each cosine zero with pi/2+n*pi and choose the smallest allowed nonnegative coordinate or time.", "Adjacent spatial zeros differ by pi/k. At an all-zero frame the time derivative usually does not vanish."],
      ["delta/2=" + phaseIndex + "*pi/4. The first nonnegative cosine-zero argument requires k*x=" + numerator + "*pi/4, so x=" + numerator + "*pi/" + 4 * k + " m.", "Node spacing is pi/k=pi/" + k + " m, half a wavelength.", "The time factor first vanishes at t=" + numerator + "*pi/" + 4 * omega + " s. The domain includes zero, so t=0 is allowed when it qualifies.", "At that instant y_t=-2*A*omega*cos(k*x+delta/2)*sin(omega*t+delta/2). It is nonzero away from the permanent nodes. Energy is then kinetic in this standing-wave field."],
      "First node=" + numerator + "*pi/" + 4 * k + " m; spacing=pi/" + k + " m; first flat frame=" + numerator + "*pi/" + 4 * omega + " s; the frame does not create nodes everywhere.");
  }
  if (variant === "net-power") {
    const power = m * c * omega * omega * (a * a - b * b);
    return finish(medium + " The rightward wave has amplitude " + a + "/1000 m; the leftward wave has amplitude " + b + "/1000 m and relative phase " + phaseIndex + "*pi/2. Find signed net mean power and the smallest/largest local time-oscillation amplitude as position varies. Are there permanent displacement nodes?",
      [phs232Rational("power", "Signed net cycle-mean power", power + "/2000000000", "W"), phs232Rational("minimum", "Smallest local time amplitude", Math.abs(a - b) + "/1000", "m"), phs232Rational("maximum", "Largest local time amplitude", a + b + "/1000", "m"),
        choice("nodes", "Permanent displacement nodes?", a === b ? "yes" : "no", [["yes", "Yes: equal counterwave amplitudes can cancel for all time at selected positions", "Equal amplitudes permit both time coefficients to vanish at periodically spaced positions."], ["no", "No: the nonzero amplitude minimum prevents permanent cancellation", "Unequal amplitudes leave a nonzero residual local oscillation even at minimum-envelope positions."]])],
      ["Use signed constituent powers: the leftward contribution has a minus sign, regardless of its phase.", "The two rotating time coefficients can reinforce to A+B or oppose to |A-B| as position changes.", "A permanent node requires the minimum local amplitude to vanish, not just y=0 at one instant."],
      ["Mean P=Z*omega²*(A²-B²)/2=" + power + "/2000000000 W, with c=" + c + " m/s and Z=mu*c.", "The local oscillation amplitude ranges from |A-B|=" + Math.abs(a - b) + "/1000 m to A+B=" + (a + b) + "/1000 m.", "Both input amplitudes are positive. Therefore permanent nodes exist exactly when A=B; here the answer is " + (a === b ? "yes" : "no") + ".", "Zero mean power for equal amplitudes does not require instantaneous internal power to vanish. The total field's derivatives determine its local energy and power."],
      "Mean P=" + power + "/2000000000 W; envelope range " + Math.abs(a - b) + "/1000 to " + (a + b) + "/1000 m; nodes=" + (a === b ? "yes" : "no") + ".");
  }
  if (variant === "coherent-intensity") {
    const numerator = a * a + b * b + 2 * a * b * cosine, denominator = a * a + b * b, cross = m * c * omega * omega * a * b * cosine;
    return finish(medium + " Two coherent waves travel right with amplitudes A=" + a + "/1000 m, B=" + b + "/1000 m and relative phase delta=" + phaseIndex + "*pi/2. Find the combined mean power divided by the sum of the two isolated mean powers, and the signed interference contribution P_combined-(P_A+P_B). Does linear displacement superposition imply additive energy for arbitrary coherent phase?",
      [phs232Rational("ratio", "Combined power divided by isolated-power sum", numerator + "/" + denominator), phs232Rational("interference", "Signed interference contribution", cross + "/1000000000", "W"),
        choice("additive", "Does linear displacement superposition imply additive coherent energy?", "no", [["no", "No: squared derivatives produce cross terms", "Energy is quadratic in the total field; coherent cross terms survive cycle averaging in general."], ["yes", "Yes: linear fields always have additive energy", "Linearity applies to the wave equation and displacement. It does not remove cross terms from squared velocities or slopes."]])],
      ["The resultant amplitude squared is A²+B²+2*A*B*cos(delta). Mean power in this same medium is proportional to that quantity.", "The isolated-power sum is proportional to A²+B²; it is not the power from one wave alone.", "The surviving cross contribution is Z*omega²*A*B*cos(delta), which can be positive, negative or zero."],
      ["C²=" + numerator + "/1000000 m² while A²+B²=" + denominator + "/1000000 m². Their ratio is " + numerator + "/" + denominator + ".", "The signed cross contribution is " + cross + "/1000000000 W. A negative cross term reduces the combined power; it does not imply negative energy density.", "For equal in-phase waves, combined power is four times one isolated wave but twice their isolated-power sum.", "If phases fluctuate so that the relevant average cosine is zero, powers can add on that statistical average. That is an additional assumption, not the present fixed coherent phase."],
      "Power ratio=" + numerator + "/" + denominator + "; interference contribution=" + cross + "/1000000000 W; coherent energy is not generally additive.");
  }
  const sum = zLeft + zRight, difference = zLeft - zRight, interfaceOmega = 10 * frequencyScale;
  const setup = "Two semi-infinite ideal strings join at a massless junction x=0 with common tension 10 N, mu1=" + zLeft * zLeft + "/1000 kg/m on x<0 and mu2=" + zRight * zRight + "/1000 kg/m on x>0. A wave of amplitude A=" + a + "/1000 m and angular frequency " + interfaceOmega + " rad/s is incident from the left; nothing arrives from the right. Write the displacement coefficients as Ar=r*A and At=t_a*A, allowing signed r.";
  if (variant === "interface-amplitude") return finish(setup + " Find r, t_a, signed Ar and transmitted wavelength divided by incident wavelength. Classify the reflected displacement phase.",
    [phs232Rational("reflection", "Signed displacement coefficient r", difference + "/" + sum), phs232Rational("transmission", "Displacement coefficient t_a", 2 * zLeft + "/" + sum), phs232Rational("reflected", "Signed reflected coefficient Ar", a * difference + "/" + 1000 * sum, "m"), phs232Rational("wavelength", "Transmitted/incident wavelength", zLeft + "/" + zRight),
      choice("phase", "Reflected displacement phase relative to the boundary reference", difference < 0 ? "inverted" : difference > 0 ? "same" : "absent", [["inverted", "Pi phase inversion", "A higher second impedance makes r negative."], ["same", "No phase inversion", "A lower second impedance makes r positive."], ["absent", "No reflected wave, so no reflected phase", "Equal impedances give r=0; a zero-amplitude reflected wave has no observable phase."]])],
    ["Z=sqrt(F_T*mu); here Z1=" + zLeft + "/10 and Z2=" + zRight + "/10 kg/s.", "Displacement continuity gives 1+r=t_a; transverse-force continuity gives Z1*(1-r)=Z2*t_a. Solve both equations.", "The source fixes a common frequency. Since c=sqrt(F_T/mu), wavelength ratio equals c2/c1."],
    ["The two matching equations yield r=(Z1-Z2)/(Z1+Z2)=" + difference + "/" + sum + " and t_a=2*Z1/(Z1+Z2)=" + 2 * zLeft + "/" + sum + ".", "Ar=r*A=" + a * difference + "/" + 1000 * sum + " m is signed. Its absolute value is the reflected amplitude.", "The speeds are c1=100/" + zLeft + " and c2=100/" + zRight + " m/s. At their common frequency, lambda2/lambda1=" + zLeft + "/" + zRight + ".", "The sign of r fixes inversion for a nonzero reflection. At r=0 no reflected phase can be measured. Displacement continuity alone would not be enough to determine both coefficients."],
    "r=" + difference + "/" + sum + "; t_a=" + 2 * zLeft + "/" + sum + "; Ar=" + a * difference + "/" + 1000 * sum + " m; wavelength ratio=" + zLeft + "/" + zRight + ".");
  const incidentNumerator = zLeft * a * a * interfaceOmega * interfaceOmega, transmittedNumerator = incidentNumerator * 4 * zLeft * zRight;
  return finish(setup + " Find the nonnegative reflected and transmitted power fractions, signed mean reflected power toward +x, and mean transmitted power. May t_a exceed one without creating energy?",
    [phs232Rational("reflection", "Reflected power fraction R", difference * difference + "/" + sum * sum), phs232Rational("transmission", "Transmitted power fraction", 4 * zLeft * zRight + "/" + sum * sum), phs232Rational("reflected", "Signed mean reflected power toward +x", -incidentNumerator * difference * difference + "/" + 20000000 * sum * sum, "W"), phs232Rational("transmitted", "Mean transmitted power", transmittedNumerator + "/" + 20000000 * sum * sum, "W"),
      choice("amplification", "Can t_a exceed one while energy is conserved?", "yes", [["yes", "Yes: the transmitted impedance changes the power per amplitude squared", "Power scales as Z*A² at common omega; t_a>1 can accompany a smaller Z2 and a power fraction below one."], ["no", "No: transmitted power fraction is always t_a squared", "The missing Z2/Z1 factor makes this claim false when the two media differ."]])],
    ["Power is quadratic in amplitude, but its coefficient also depends on impedance.", "R=r² and transmitted fraction=(Z2/Z1)*t_a². Their sum must be one for this lossless junction.", "Mean incident power is Z1*omega²*A²/2. Reflected signed power is minus R times that positive value."],
    ["R=" + difference * difference + "/" + sum * sum + " and transmitted fraction=" + 4 * zLeft * zRight + "/" + sum * sum + "; their numerators sum to the common denominator.", "The positive incident mean power is " + incidentNumerator + "/20000000 W.", "Signed reflected power is " + -incidentNumerator * difference * difference + "/" + 20000000 * sum * sum + " W; transmitted power is " + transmittedNumerator + "/" + 20000000 * sum * sum + " W.", "For lower transmitted impedance t_a can exceed one. The power fraction includes Z2/Z1 and remains at most one. Frequency is common; equal amplitudes alone would not imply equal powers in different strings."],
    "R=" + difference * difference + "/" + sum * sum + "; transmitted fraction=" + 4 * zLeft * zRight + "/" + sum * sum + "; powers have units W and obey P_incident+P_reflected=P_transmitted.");
}
