import { questionSchema, type AnswerField } from "../contracts";
import { randomFrom } from "../random";
import { phs232Choice, phs232Exact, phs232Pi, phs232Rational } from "./phs-232-fields";

export const phs232ResonancePowerFamilyIds = ["phs232-resonance-power"] as const;
export const phs232ResonancePowerVariants = ["displacement-peak", "velocity-peak", "average-power", "cycle-work", "quality-factor", "no-interior-peak"] as const;

export function phs232ResonancePowerQuestion(familyId: string, variant: string, seed: string, id: string) {
  if (familyId !== "phs232-resonance-power" || !(phs232ResonancePowerVariants as readonly string[]).includes(variant)) throw Error("Unknown PHS 232 resonance-power family or variant.");
  const rng = randomFrom(`${familyId}:${variant}:${seed}`), massNumerator = rng.integer(1, 6), scale = rng.integer(1, 4), a = rng.integer(1, 8), dampingNumerator = rng.integer(1, 3), frequencyIndex = rng.integer(0, 3), mode = rng.integer(0, 2);
  const parameters = { massNumerator, scale, a, dampingNumerator, frequencyIndex, mode }, d = dampingNumerator, m = `${massNumerator}/2`, k = `${25 * massNumerator * scale * scale}/2`, b = massNumerator * d * scale, force = `${a}/10`, w0 = 5 * scale;
  const choice = (id: string, label: string, correct: string, options: [string, string, string][]) => phs232Choice(id, label, correct, rng.shuffle(options));
  const finish = (prompt: string, fields: AnswerField[], hints: string[], explanation: string[], answerSummary: string) => questionSchema.parse({ id, familyId, familyVersion: 1, courseId: "phs-232", objectiveId: "m01-l04", category: "application", critical: true, parameters, prompt, fields, hints, explanation, answerSummary });
  const setup = `Consider m*x''+b*x'+k*x=F0*cos(Omega*t), with m=${m} kg, b=${b} kg/s, k=${k} N/m and F0=${force} N. Hold that force amplitude fixed while varying Omega≥0. Use the periodic response after the homogeneous correction has decayed.`;
  if (variant === "displacement-peak") {
    const wd = `${scale}*sqrt(${25 - d * d})`, peak = `${scale}*sqrt(${25 - 2 * d * d})`, A = `${a}/(${10 * massNumerator * d * scale * scale}*sqrt(${25 - d * d}))`;
    return finish(`${setup} Find the natural angular frequency omega0, damping rate beta, free damped frequency omega_d, positive forcing frequency that maximizes displacement amplitude, and that maximum displacement amplitude. Keep the free-response frequency distinct from the frequency of the drive.`,
      [phs232Rational("natural", "Natural angular frequency omega0", String(w0), "rad/s"), phs232Rational("beta", "Damping rate beta", String(d * scale), "1/s"), phs232Exact("free-frequency", "Free damped angular frequency", wd, "rad/s"), phs232Exact("peak-frequency", "Forcing angular frequency at maximum displacement amplitude", peak, "rad/s"), phs232Exact("amplitude", "Maximum displacement amplitude", A, "m")],
      ["omega0²=k/m and beta=b/(2m). The free damped frequency uses omega0²-beta².", "For fixed F0, maximize A by minimizing (omega0²-Omega²)²+4*beta²*Omega². The positive stationary frequency satisfies Omega²=omega0²-2*beta²; check it is positive.", "At that frequency the dynamic-stiffness magnitude becomes 2*m*beta*sqrt(omega0²-beta²). Divide F0 by it. This result is not F0/(b*omega0)."],
      [`omega0=${w0} rad/s and beta=${d * scale} 1/s. The free decay oscillates at omega_d=${wd} rad/s.`, `The displacement denominator has derivative 4*Omega*(Omega²-omega0²+2*beta²). Since omega0²-2*beta²=${(25 - 2 * d * d) * scale * scale}>0, the positive minimum occurs at Omega=${peak} rad/s.`, `Substitution gives A_max=F0/[2*m*beta*sqrt(omega0²-beta²)]=${A} m.`, "All three frequencies are different for this positive damping: the displacement peak lies below omega_d, which lies below omega0. Velocity and power select a different peak because their numerators depend on frequency."], `omega0=${w0}; beta=${d * scale}; omega_d=${wd}; displacement peak=${peak} rad/s; A_max=${A} m.`);
  }
  if (variant === "velocity-peak") return finish(`${setup} Find the forcing frequency at maximum velocity amplitude, the maximum velocity amplitude, and the maximum mean dissipated power. Do those two peaks occur at the positive displacement-amplitude peak for this positively damped system?`,
    [phs232Rational("frequency", "Forcing angular frequency for maximum velocity amplitude", String(w0), "rad/s"), phs232Rational("velocity", "Maximum velocity amplitude", `${a}/${10 * b}`, "m/s"), phs232Rational("power", "Maximum mean dissipated power", `${a * a}/${200 * b}`, "W"), choice("same", "Same frequency as the displacement-amplitude maximum?", "different", [["different", "No: displacement peaks at a lower frequency", "With fixed force amplitude, the extra Omega factor in velocity shifts its maximum to omega0. Mean power is proportional to velocity amplitude squared."], ["same", "Yes: every response quantity has the same resonance peak", "The measured output matters. A displacement peak need not maximize velocity or power."]])],
    ["The velocity amplitude is V=Omega*F0/sqrt((k-m*Omega²)²+(b*Omega)²). Include the numerator's frequency dependence when differentiating.", "The derivative of V² has the sign of k²-m²*Omega⁴ for positive Omega. Its maximum is at sqrt(k/m).", "At Omega=omega0, V=F0/b and mean power=b*V²/2. Compare this frequency with sqrt(omega0²-2*beta²)."],
    [`The sign change in the derivative gives Omega=omega0=${w0} rad/s for both V and mean dissipated power.`, `V_max=F0/b=${a}/${10 * b} m/s and P_max=F0²/(2b)=${a * a}/${200 * b} W.`, "At this frequency the displacement lags force by pi/2, making velocity in phase with force. Instantaneous power is then nonnegative for the periodic response.", "The displacement maximum lies at sqrt(omega0²-2*beta²), which is smaller here. Specifying only 'the resonance frequency' without the output can conceal this difference."], `Velocity/power peak at ${w0} rad/s; V_max=${a}/${10 * b} m/s; P_max=${a * a}/${200 * b} W; displacement peaks lower.`);
  if (variant === "average-power") {
    const r = [2, 3, 5, 7][frequencyIndex], omega = r * scale, denominator = (25 - r * r) ** 2 + 4 * d * d * r * r, power = `${a * a * d * r * r}/${50 * massNumerator * scale * denominator}`, negative = r !== 5;
    return finish(`${setup} Set Omega=${omega} rad/s. Find the mean input power, mean viscous loss power, and net change in mechanical energy over one complete forcing cycle of the periodic response. Can instantaneous input power F(t)*v(t) be negative during this particular cycle?`,
      [phs232Rational("input", "Mean input power", power, "W"), phs232Rational("loss", "Mean viscous loss power", power, "W"), phs232Rational("energy-change", "Mechanical energy change over a full periodic cycle", "0", "J"), choice("negative", "Negative instantaneous input power during this cycle?", negative ? "yes" : "no", [["yes", "Yes: the mass returns energy to the driver during part of the cycle", "Away from omega0, velocity is not exactly in phase with the force. Their product can be negative despite positive cycle-average input."], ["no", "No: force and velocity are in phase here", "At Omega=omega0 for this periodic viscous response, v=(F0/b)*cos(Omega*t), so F*v=(F0²/b)*cos²(Omega*t)≥0. This special case is not a universal power-sign rule."]])],
      ["For a periodic response, averaging dE/dt=F*v-b*v² over one full cycle gives equal mean input and loss. This does not require equal instantaneous powers.", "If displacement amplitude is A, the average of v² is Omega²*A²/2. Compute A from the full dynamic-stiffness magnitude.", "The force and velocity are exactly in phase only at omega0 in this positive-damping model. Otherwise their product changes sign during some part of a cycle."],
      [`The squared normalized dynamic-stiffness factor is (${25 - r * r})²+(${2 * d * r})²=${denominator}. Therefore mean loss=b*Omega²*F0²/[2*((k-m*Omega²)²+(b*Omega)²)]=${power} W.`, `Mean input is also ${power} W. Mechanical energy returns to its starting value after a full periodic cycle, so its net change is 0 J.`, negative ? "Here Omega differs from omega0. Force and velocity have a nonzero phase difference whose magnitude is below pi/2; their product includes negative intervals even though the mean is positive." : "Here Omega=omega0. Velocity is in phase with force, so instantaneous input power is never negative in this particular periodic response.", "Viscous power b*v² is nonnegative at every instant. Signed driver power and nonnegative viscous transfer are different quantities."], `Mean input=mean loss=${power} W; cycle energy change=0 J; negative instantaneous input=${negative ? "yes" : "no"}.`);
  }
  if (variant === "cycle-work") {
    const power = `${a * a}/${200 * b}`, work = `${a * a}*pi/${100 * b * w0}`;
    return finish(`${setup} Set Omega=omega0=${w0} rad/s. Find the forcing period, mean input power, input work per cycle, and net mechanical-energy change over a full periodic cycle. Must the first complete cycle after a release from rest have the same input work as this periodic cycle?`,
      [phs232Pi("period", "Forcing period", `2*pi/${w0}`, "s"), phs232Rational("power", "Mean input power", power, "W"), phs232Pi("work", "Input work per periodic cycle", work, "J"), phs232Rational("net", "Mechanical energy change over a periodic cycle", "0", "J"), choice("startup", "First startup cycle necessarily has the same input work?", "not-guaranteed", [["not-guaranteed", "No: a transient can change the work and stored energy", "A full cycle of the force does not guarantee that the entire startup state is periodic. Apply Delta E=W_in-D to the actual state."], ["same", "Yes: one force cycle always returns every state to its start", "The force repeats, but the initial-state correction generally does not. The complete trajectory can store a different amount of energy at the two endpoints."]])],
      ["T_drive=2*pi/Omega for positive Omega. Mean power has units J/s, while its cycle integral has units J.", "At the natural frequency, mean input power is F0²/(2b). Multiply this mean by one forcing period, not by the angular frequency.", "The periodic state returns to itself and has Delta E=0; its positive input work equals the positive viscous transfer. A startup state need not return to itself after one force cycle."],
      [`T_drive=2*pi/${w0} s and mean input=${power} W.`, `W_cycle=P_mean*T_drive=${work} J. The same positive energy is transferred to the viscous environment during that periodic cycle.`, "Delta E=0 J does not mean the driver did zero work. Input and dissipated work balance over this cycle.", "A release from rest generally includes a homogeneous correction. Its first forcing cycle must use the actual work/loss integrals and endpoint energies; steady-cycle work cannot simply be assigned to it."], `T=2*pi/${w0} s; mean power=${power} W; input work=${work} J; net mechanical change=0 J; startup work is not guaranteed equal.`);
  }
  if (variant === "quality-factor") {
    const lower = `${scale}*(sqrt(${25 + d * d})-${d})`, upper = `${scale}*(sqrt(${25 + d * d})+${d})`;
    return finish(`${setup} Define Q=m*omega0/b. Find Q and the two positive forcing frequencies at which mean dissipated power is half its maximum. Find their separation. Is the formula 'Q equals 2*pi times stored energy divided by free energy lost in one cycle' an exact identity for arbitrary damping when loss is a finite cycle difference?`,
      [phs232Rational("quality", "Quality factor Q", `5/${2 * d}`), phs232Exact("lower", "Lower half-power angular frequency", lower, "rad/s"), phs232Exact("upper", "Upper half-power angular frequency", upper, "rad/s"), phs232Rational("width", "Half-power angular-frequency separation", String(2 * d * scale), "rad/s"), choice("loss-definition", "Finite free-cycle energy-loss interpretation", "approximation", [["approximation", "Requires a weak-damping approximation", "Replacing a differential decay rate by a finite-cycle fractional loss is accurate only when the energy changes little during a cycle; the damped and natural periods also differ."], ["exact", "Exact at every damping strength", "The exponential finite-cycle energy difference is not the same as its first-order small-loss approximation. Q's viscous-model definition remains exact."]])],
      ["At half the maximum mean power, (omega0²-Omega²)²=4*beta²*Omega². Solve the two signs while retaining positive frequencies.", "The roots are sqrt(omega0²+beta²)-beta and sqrt(omega0²+beta²)+beta. Their difference is 2*beta=b/m.", "Use Q=omega0/(2*beta). Do not substitute half displacement amplitude for half mean power, or silently replace finite free-cycle loss by a differential loss rate."],
      [`Q=m*omega0/b=5/${2 * d}. The two positive half-power frequencies are ${lower} and ${upper} rad/s.`, `Their exact separation is ${2 * d * scale} rad/s=b/m. For this fixed-force viscous response, omega0 divided by this bandwidth equals Q without a weak-damping approximation.`, "At half power, velocity amplitude is its maximum divided by sqrt(2). This is not generally the frequency pair at half displacement amplitude.", "The free-cycle energy interpretation requires weak damping when using a finite loss. Expanding the small loss and using T_d approximately equal to T0 justifies that approximation; neither replacement is exact for arbitrary damping."], `Q=5/${2 * d}; half-power roots ${lower}, ${upper} rad/s; width=${2 * d * scale} rad/s; finite-cycle loss interpretation is approximate.`);
  }
  const actualB = mode === 0 ? String(4 * massNumerator * scale) : mode === 1 ? String(5 * massNumerator * scale) : `${5 * massNumerator * scale}*sqrt(2)/2`, threshold = `${5 * massNumerator * scale}*sqrt(2)/2`;
  return finish(`A viscous oscillator has m=${m} kg, k=${k} N/m, b=${actualB} kg/s and a fixed force amplitude F0=${force} N. Sweep Omega over the full domain Omega≥0. Find the coefficient b at the displacement-peak threshold, the forcing frequency of the global displacement-amplitude maximum, that maximum amplitude, and the velocity-amplitude peak frequency. Does a positive interior displacement peak exist?`,
    [phs232Exact("threshold", "Damping coefficient at the displacement-peak threshold", threshold, "kg/s"), phs232Rational("frequency", "Frequency of the global displacement-amplitude maximum", "0", "rad/s"), phs232Rational("amplitude", "Global displacement-amplitude maximum", `${a}/${125 * massNumerator * scale * scale}`, "m"), phs232Rational("velocity-frequency", "Velocity-amplitude peak frequency", String(w0), "rad/s"), choice("interior", "Positive interior displacement-amplitude peak", "none", [["none", "None: the maximum is the static endpoint", "When beta≥omega0/sqrt(2), no positive stationary displacement peak remains. Equality puts the candidate at the endpoint, not inside Omega>0."], ["natural", "Yes: always at the natural frequency", "That frequency maximizes velocity and mean power for fixed positive force and damping. It does not always maximize displacement."], ["negative", "Use an imaginary forcing frequency from the peak formula", "A negative radicand means there is no positive real interior extremum on the specified sweep domain."]])],
    ["The displacement peak requires omega0²-2*beta²>0. Equality occurs at b=2*m*(omega0/sqrt(2))=sqrt(2*m*k).", "At or above that coefficient, the displacement-amplitude denominator increases for every Omega>0. Compare the endpoint Omega=0, where the displacement is F0/k.", "Velocity amplitude includes an extra Omega factor, so it still has its positive maximum at omega0. No positive displacement peak does not mean no forced response."],
    [`omega0=${w0} rad/s and the threshold is b_threshold=sqrt(2*m*k)=${threshold} kg/s. The given coefficient is ${mode === 2 ? "exactly at" : "above"} that threshold.`, `The maximum on Omega≥0 is at Omega=0 rad/s, with A_max=F0/k=${a}/${125 * massNumerator * scale * scale} m. At zero frequency this is a constant particular displacement.`, `There is no positive interior displacement peak, including at threshold equality. Velocity amplitude still peaks at Omega=${w0} rad/s.`, "The displacement-peak threshold b=sqrt(2mk) is lower than the free-response critical-damping coefficient 2*sqrt(mk). The two classifications answer different questions."], `Threshold=${threshold} kg/s; displacement maximum at 0 rad/s with value ${a}/${125 * massNumerator * scale * scale} m; velocity peak=${w0} rad/s; no positive interior displacement peak.`);
}
