import { questionSchema, type AnswerField } from "../contracts";
import { randomFrom } from "../random";
import { phs232Approximate, phs232Choice, phs232Exact, phs232Pi, phs232Rational } from "./phs-232-fields";

export const phs232FreeDecayFamilyIds = ["phs232-free-decay"] as const;
export const phs232FreeDecayVariants = ["regime", "underdamped-state", "critical-state", "overdamped-state", "initial-constants", "zero-damping"] as const;

export function phs232FreeDecayQuestion(familyId: string, variant: string, seed: string, id: string) {
  if (familyId !== "phs232-free-decay" || !(phs232FreeDecayVariants as readonly string[]).includes(variant)) throw new Error("Unknown PHS 232 free-decay family or variant.");
  const rng = randomFrom(`${familyId}:${variant}:${seed}`);
  const massNumerator = rng.integer(1, 8), scale = rng.integer(1, 4), a = rng.integer(1, 8), c = rng.integer(1, 8), sx = rng.integer(0, 1) ? 1 : -1, sv = rng.integer(0, 1) ? 1 : -1;
  const regimeIndex = rng.integer(0, 3), quarter = rng.integer(1, 4), timeIndex = rng.integer(1, 3), mode = rng.integer(0, 2);
  const parameters = { massNumerator, scale, a, c, sx, sv, regimeIndex, quarter, timeIndex, mode };
  const choice = (id: string, label: string, correct: string, options: [string, string, string][]) => phs232Choice(id, label, correct, rng.shuffle(options));
  const finish = (prompt: string, fields: AnswerField[], hints: string[], explanation: string[], answerSummary: string) => questionSchema.parse({
    id, familyId, familyVersion: 1, courseId: "phs-232", objectiveId: "m01-l03", category: "application", critical: true, parameters, prompt, fields, hints, explanation, answerSummary,
  });
  const m = `${massNumerator}/2`;
  if (variant === "regime") {
    const w0 = 2 * scale, ratios = ["0", "3/5", "1", "5/4"], b = `(${massNumerator * w0})*(${ratios[regimeIndex]})`, beta = `(${w0})*(${ratios[regimeIndex]})`;
    const regime = ["undamped", "under", "critical", "over"][regimeIndex];
    const regimeLabel = ["undamped", "underdamped", "critically damped", "overdamped"][regimeIndex];
    const fields: AnswerField[] = [phs232Rational("critical-b", "Critical viscous coefficient", String(massNumerator * w0), "kg/s"), phs232Rational("beta", "Exponential damping rate beta", beta, "1/s"), choice("regime", "Regime of the linear model", regime, [["undamped", "Undamped", "A zero damping coefficient gives constant mechanical energy and a nonzero-amplitude harmonic response."], ["under", "Underdamped", "A positive coefficient smaller than 2*sqrt(mk) gives complex conjugate characteristic roots and decaying oscillations."], ["critical", "Critically damped", "At b=2*sqrt(mk) the characteristic root is repeated; the full solution includes a time times exponential term."], ["over", "Overdamped", "Above the critical coefficient there are two negative real characteristic roots. A suitable initial velocity can still cause one equilibrium crossing."]])];
    if (regimeIndex < 2) fields.push(phs232Rational("frequency", "Oscillation angular frequency", regimeIndex === 0 ? String(w0) : `${4 * w0}/5`, "rad/s"));
    else fields.push(choice("frequency", "Positive oscillation frequency for this free response", "none", [["none", "None: the response uses real exponential modes", "The natural frequency sqrt(k/m) remains a parameter, but it is not a sustained oscillation frequency in this regime."], ["natural", "Use sqrt(k/m) as the actual oscillation frequency", "That natural frequency describes the undamped reference system; it does not convert real decaying modes into oscillations."], ["absolute", "Take the absolute value inside the underdamped square root", "Changing the sign of the radicand changes the equation. Negative omega_d squared indicates real exponential modes, not a real oscillatory frequency."]]));
    return finish(`A horizontal linear system obeys m*x''+b*x'+k*x=0 with m=${m} kg, k=${massNumerator * w0 * w0}/2 N/m and b=${b} kg/s. It is displaced from equilibrium and released from rest. Calculate the critical viscous coefficient, beta=b/(2m), the regime, and the oscillation angular frequency when one exists. Keep the natural parameter omega0 distinct from the frequency of the actual free response.`, fields,
      ["Compute omega0=sqrt(k/m), then b_critical=2*m*omega0. The coefficient b has units kg/s, while beta has units 1/s.", "Compare b with zero and b_critical before choosing a solution form.", "Only b<b_critical gives omega_d=sqrt(omega0²-beta²)>0. At equality a repeated real root requires the critical solution."],
      [`omega0=${w0} rad/s and b_critical=${massNumerator * w0} kg/s. beta=${beta} 1/s, giving b/b_critical=${ratios[regimeIndex]}.`, regimeIndex < 2 ? `The oscillation angular frequency is ${regimeIndex === 0 ? w0 : `${4 * w0}/5`} rad/s. ${regimeIndex === 0 ? "There is no decay." : "The phase repeats at fixed intervals while amplitude decreases, so the full trajectory is not periodic."}` : `The model is ${regimeLabel}. It has no positive oscillation frequency for this free response. The natural parameter omega0 is still defined.`, "Damping classification describes the equation. Whether a particular trajectory crosses equilibrium also depends on both initial conditions; a single crossing is not repeated oscillation."],
      `b_critical=${massNumerator * w0} kg/s; beta=${beta} 1/s; regime=${regimeLabel}.`);
  }
  const cos = [1, 0, -1, 0, 1][quarter], sin = [0, 1, 0, -1, 0][quarter];
  if (variant === "underdamped-state") {
    const x0 = sx * a / 100, attenuation = Math.exp(-3 * quarter * Math.PI / 8), x = x0 * attenuation * (cos + .75 * sin), v = -25 * scale * x0 / 4 * attenuation * sin, acceleration = -(25 * scale * scale) * x - 6 * scale * v;
    return finish(`A free damped oscillator has m=${m} kg, k=${25 * massNumerator * scale * scale}/2 N/m and b=${3 * massNumerator * scale} kg/s. At t=0, x=${sx * a}/100 m and v=0. Find omega_d and signed x, v and acceleration at t=${quarter}*pi/${8 * scale} s. Also decide whether the complete nonzero trajectory is periodic. The damping is viscous and parameters are constant. Give numerical states within 0.000001 in each labeled SI unit.`,
      [phs232Rational("frequency", "Damped oscillation angular frequency", String(4 * scale), "rad/s"), phs232Approximate("position", "Signed position", x, "m"), phs232Approximate("velocity", "Signed velocity", v, "m/s"), phs232Approximate("acceleration", "Signed acceleration", acceleration, "m/s²"), choice("periodic", "Does the complete nonzero state repeat periodically?", "no", [["yes", "Yes: displacement and velocity both repeat every damped cycle", "Their values at the same phase are multiplied by exp(-beta*T_d), which is less than one here."], ["no", "No: phase repeats while the state decays", "A damped oscillation has a repeating phase interval but a changing amplitude. The complete state does not recur unless it is the zero equilibrium."]])],
      [`The given coefficients give omega0=${5 * scale} rad/s, beta=${3 * scale} 1/s and omega_d=${4 * scale} rad/s. Use x=e^(-beta*t)(C*cos(omega_d*t)+D*sin(omega_d*t)).`, "C=x0 and D=(v0+beta*x0)/omega_d=3*x0/4. A release from rest does not generally make D zero.", `At this time omega_d*t=${quarter}*pi/2. Differentiate the entire product for velocity, then use acceleration=-(k/m)*x-(b/m)*v.`],
      [`omega0=${5 * scale} rad/s, beta=${3 * scale} 1/s and omega_d=${4 * scale} rad/s. C=${sx * a}/100 m and D=${3 * sx * a}/400 m.`, `At the requested time, cos=${cos}, sin=${sin} and the attenuation is exp(-${3 * quarter}*pi/8). This gives x≈${x.toFixed(9)} m and v≈${v.toFixed(9)} m/s.`, `The force equation gives acceleration=-${25 * scale * scale}*x-${6 * scale}*v≈${acceleration.toFixed(9)} m/s². Using only -omega0²*x would omit damping force.`, `After T_d=2*pi/${4 * scale} s the state is multiplied by exp(-3*pi/2), not repeated. At an extremum v=0 only instantaneously; it does not make this entire response stationary.`],
      `omega_d=${4 * scale} rad/s; x≈${x.toFixed(9)} m; v≈${v.toFixed(9)} m/s; acceleration≈${acceleration.toFixed(9)} m/s²; complete trajectory not periodic.`);
  }
  if (variant === "critical-state") {
    const xNumerator = sx * a, vNumerator = mode === 0 ? 0 : mode === 1 ? -scale * xNumerator : sv * c * scale;
    const dNumerator = vNumerator + scale * xNumerator, x = (xNumerator + dNumerator * timeIndex / scale) / 20 * Math.exp(-timeIndex), v = (vNumerator - dNumerator * timeIndex) / 20 * Math.exp(-timeIndex), crossing = xNumerator * dNumerator < 0;
    return finish(`A critically damped oscillator obeys m*x''+b*x'+k*x=0 with m=${m} kg, k=${massNumerator * scale * scale}/2 N/m and b=${massNumerator * scale} kg/s. Initially x0=${xNumerator}/20 m and v0=${vNumerator}/20 m/s. Write x(t)=(C+D*t)*exp(-${scale}t). Find C, D, signed x and v at t=${timeIndex}/${scale} s, and whether this particular response crosses equilibrium at any strictly positive time.`,
      [phs232Rational("c", "Constant C", `${xNumerator}/20`, "m"), phs232Rational("d", "Constant D", `${dNumerator}/20`, "m/s"), phs232Approximate("position", "Position at the requested time", x, "m"), phs232Approximate("velocity", "Velocity at the requested time", v, "m/s"), choice("crossing", "Equilibrium crossing at some t greater than zero", crossing ? "yes" : "no", [["yes", "Yes, one crossing", "The exponential never vanishes. A positive root of C+D*t gives a single crossing; a repeated characteristic root does not prohibit it."], ["no", "No positive-time crossing", "Check t=-C/D if D is nonzero. A negative root is outside the requested time domain; D=0 gives a single nonzero exponential with no crossing."]])],
      [`The repeated root is -${scale} 1/s. Both constants are needed: C=x0, D=v0+${scale}*x0.`, `Differentiate the product: v=exp(-${scale}t)[D-${scale}*(C+D*t)].`, "A finite zero requires C+D*t=0. If D=0 there is no crossing here; otherwise retain the restriction t>0."],
      [`C=${xNumerator}/20 m and D=${dNumerator}/20 m/s. The critical response retains a t*exp(-${scale}t) term unless D happens to vanish for these initial conditions.`, `At t=${timeIndex}/${scale} s, the attenuation is exp(-${timeIndex}); x≈${x.toFixed(9)} m and v≈${v.toFixed(9)} m/s.`, dNumerator === 0 ? "D=0, so the entire response is one signed exponential and never crosses zero at finite positive time." : `The only possible crossing time is t=-C/D=${-xNumerator}/${dNumerator} s. It is ${crossing ? "positive and admissible" : "negative and outside t>0"}.`, "Statements that critical damping never overshoots require appropriate initial conditions, such as a displaced release from rest. This question supplies both initial coordinates explicitly."],
      `C=${xNumerator}/20 m; D=${dNumerator}/20 m/s; x≈${x.toFixed(9)} m; v≈${v.toFixed(9)} m/s; positive-time crossing=${crossing ? "yes" : "no"}.`);
  }
  if (variant === "overdamped-state") {
    const slow = mode === 2 ? 0 : sx * a, fast = mode === 1 ? 0 : sv * c, xNumerator = slow + fast, vNumerator = -scale * (slow + 4 * fast);
    const x = (slow * Math.exp(-timeIndex) + fast * Math.exp(-4 * timeIndex)) / 100, v = -scale * (slow * Math.exp(-timeIndex) + 4 * fast * Math.exp(-4 * timeIndex)) / 100;
    const roots: AnswerField = { id: "rates", label: "Both real characteristic rates", kind: "roots", numberSystem: "real", expected: [String(-scale), String(-4 * scale)], unit: "1/s", help: "List both distinct rates, separated by a comma. These are signed exponents, not oscillation frequencies." };
    return finish(`A free oscillator has m=${m} kg, k=${2 * massNumerator * scale * scale} N/m and b=${5 * massNumerator * scale}/2 kg/s. Initially x0=${xNumerator}/100 m and v0=${vNumerator}/100 m/s. Find its two real characteristic rates. Then write x=C_slow*exp(r_slow*t)+C_fast*exp(r_fast*t), with r_slow the root closer to zero. Find both coefficients and signed x and v at t=${timeIndex}/${scale} s. Retain both system roots even if one coefficient vanishes for this state.`,
      [roots, phs232Rational("slow", "Coefficient of the slower exponential", `${slow}/100`, "m"), phs232Rational("fast", "Coefficient of the faster exponential", `${fast}/100`, "m"), phs232Approximate("position", "Position at the requested time", x, "m", .000000001), phs232Approximate("velocity", "Velocity at the requested time", v, "m/s", .000000001)],
      [`Divide by m to obtain r²+${5 * scale}r+${4 * scale * scale}=0. Factor or apply the quadratic formula without changing any signs.`, "Use C_slow+C_fast=x0 and r_slow*C_slow+r_fast*C_fast=v0. The equation for velocity is independent of the equation for position.", `At the requested time the exponentials are exp(-${timeIndex}) and exp(-${4 * timeIndex}). Differentiate each exponential with its own rate. The small fast-mode values require the tighter tolerance printed beside these fields.`],
      [`The characteristic equation factors as (r+${scale})(r+${4 * scale})=0, so r_slow=-${scale} 1/s and r_fast=-${4 * scale} 1/s.`, `Solving the two initial-condition equations gives C_slow=${slow}/100 m and C_fast=${fast}/100 m. A negative coefficient is allowed and can affect crossing behavior.`, `At t=${timeIndex}/${scale} s, x≈${x.toFixed(12)} m and v≈${v.toFixed(12)} m/s. The faster term decays four times as rapidly in its exponent.`, "A zero coefficient suppresses that mode in this particular response; it does not remove the corresponding characteristic root from the system. Two real negative rates do not describe sinusoidal oscillation."],
      `Rates -${scale} and -${4 * scale} 1/s; C_slow=${slow}/100 m; C_fast=${fast}/100 m; x≈${x.toFixed(12)} m; v≈${v.toFixed(12)} m/s.`);
  }
  if (variant === "initial-constants") {
    const cNumerator = sx * a, dNumerator = sv * c + 3 * sx * a, C = cNumerator / 100, D = dNumerator / 400;
    let phase = Math.atan2(-D, C); if (phase >= Math.PI) phase -= 2 * Math.PI;
    return finish(`A viscously damped oscillator has omega0=${5 * scale} rad/s, beta=${3 * scale} 1/s and omega_d=${4 * scale} rad/s. Its initial position is ${sx * a}/100 m and initial velocity is ${sv * c * scale}/100 m/s. Determine C and D in x=e^(-beta*t)[C*cos(omega_d*t)+D*sin(omega_d*t)]. Also determine the positive envelope coefficient R and principal phase phi in x=R*e^(-beta*t)*cos(omega_d*t+phi), using -pi≤phi<pi.`,
      [phs232Rational("c", "Cosine coefficient C", `${cNumerator}/100`, "m"), phs232Rational("d", "Sine coefficient D", `${dNumerator}/400`, "m"), phs232Exact("amplitude", "Envelope coefficient R", `sqrt((${cNumerator}/100)^2+(${dNumerator}/400)^2)`, "m"), phs232Approximate("phase", "Principal phase", phase, "rad")],
      ["At zero, x0=C. Differentiating at zero gives v0=-beta*C+omega_d*D; the derivative of the exponential contributes.", "Then R=sqrt(C²+D²), cos(phi)=C/R and sin(phi)=-D/R.", "Use atan2(-D,C) and reduce to the requested principal interval. An arccos value alone does not recover the sign of the sine."],
      [`C=${cNumerator}/100 m. From v0=-${3 * scale}C+${4 * scale}D, obtain D=${dNumerator}/400 m.`, `R=sqrt((${cNumerator}/100)²+(${dNumerator}/400)²) m. The coefficient R is generally different from the initial displacement magnitude and from a true peak's magnitude.`, `phi=atan2(-D,C)≈${phase.toFixed(9)} rad in [-pi,pi). Substituting it recovers both C=R*cos(phi) and D=-R*sin(phi).`, "Finally v0=-beta*C+omega_d*D checks the initial velocity by a second route. Omitting the decay derivative can give the right initial position and the wrong motion."],
      `C=${cNumerator}/100 m; D=${dNumerator}/400 m; R=sqrt((${cNumerator}/100)²+(${dNumerator}/400)²) m; phi≈${phase.toFixed(9)} rad.`);
  }
  const w0 = 2 * scale, xNumerator = sx * a * cos + sv * c * sin, vNumerator = w0 * (sv * c * cos - sx * a * sin), energy = `${massNumerator * w0 * w0 * (a * a + c * c)}/40000`;
  return finish(`Set b=0 in m*x''+b*x'+k*x=0. Let m=${m} kg, k=${massNumerator * w0 * w0}/2 N/m, x0=${sx * a}/100 m and v0=${sv * c * w0}/100 m/s. Find signed x and v at t=${quarter}*pi/${2 * w0} s, total energy above the spring minimum, and the least positive trajectory period. Determine whether mechanical energy decays exponentially in this zero-damping limit.`,
    [phs232Rational("position", "Signed position", `${xNumerator}/100`, "m"), phs232Rational("velocity", "Signed velocity", `${vNumerator}/100`, "m/s"), phs232Rational("energy", "Mechanical energy", energy, "J"), phs232Pi("period", "Least positive trajectory period", `2*pi/${w0}`, "s"), choice("decay", "Mechanical energy in the stated model", "constant", [["constant", "Constant: no viscous power loss", "The exact power loss is b*v². Setting b to zero removes it even though the mass still moves."], ["decays", "Still decreases exponentially at a positive rate", "The decay rate beta=b/(2m) becomes zero. A positive damping rate would change the stated model."], ["zero", "Becomes zero because the damping coefficient is zero", "The supplied nonzero initial state has positive mechanical energy; zero loss is not zero stored energy."]])],
    ["The undamped initial-state solution is x=x0*cos(omega0*t)+(v0/omega0)*sin(omega0*t).", `At this time the phase is ${quarter}*pi/2. Differentiate to obtain signed velocity.`, "Compute E=m*v0²/2+k*x0²/2 and T=2*pi/omega0. Both initial coordinates are not zero here, so a least positive trajectory period exists."],
    [`omega0=${w0} rad/s. At the requested time cosine=${cos} and sine=${sin}, giving x=${xNumerator}/100 m and v=${vNumerator}/100 m/s.`, `The initial energy is E=${energy} J. Computing m*v²/2+k*x²/2 from the propagated state returns the same value.`, `T=2*pi/${w0} s. With b=0, dE/dt=-b*v²=0 and no positive exponential decay remains.`, "The equilibrium exception would require x0=v0=0; those are not the given conditions. The nonzero initial state cycles with constant amplitude."],
    `x=${xNumerator}/100 m; v=${vNumerator}/100 m/s; E=${energy} J; T=2*pi/${w0} s; energy constant.`);
}
