import { questionSchema, type AnswerField } from "../contracts";
import { randomFrom } from "../random";
import { phs232Choice, phs232Rational } from "./phs-232-fields";

export const phs232WaveModesFamilyIds = ["phs232-wave-modes"] as const;
export const phs232WaveModesVariants = ["fixed-spectrum", "mixed-spectrum", "mode-index", "coupled-symmetric", "coupled-antisymmetric", "beat-envelope"] as const;
export function phs232WaveModesQuestion(familyId: string, variant: string, seed: string, id: string) {
  if (familyId !== "phs232-wave-modes" || !(phs232WaveModesVariants as readonly string[]).includes(variant)) throw Error("Unknown PHS 232 wave-modes family or variant.");
  const rng = randomFrom(familyId + ":" + variant + ":" + seed), lengthNumerator = rng.integer(2, 8), c = rng.integer(5, 20), n = rng.integer(1, 6), nodeIndex = rng.integer(0, n), boundary = rng.integer(0, 1), mode = rng.integer(0, 3);
  const m = rng.integer(1, 9), lower = rng.integer(2, 6), upper = lower + rng.integer(0, 4), a = rng.integer(1, 5), b = mode === 0 ? a : rng.integer(1, 5), sign = rng.integer(0, 1) ? 1 : -1, u = rng.integer(-5, 5), v = rng.integer(-5, 5), frequencyBase = rng.integer(20, 100), difference = mode === 0 ? 0 : rng.integer(1, 8);
  const parameters = { lengthNumerator, c, n, nodeIndex, boundary, mode, m, lower, upper, a, b, sign, u, v, frequencyBase, difference };
  const choice = (id: string, label: string, correct: string, options: [string, string, string][]) => phs232Choice(id, label, correct, rng.shuffle(options));
  const finish = (prompt: string, fields: AnswerField[], hints: string[], explanation: string[], answerSummary: string) => questionSchema.parse({ id, familyId, familyVersion: 1, courseId: "phs-232", objectiveId: "m02-l02", category: "application", critical: true, parameters, prompt, fields, hints, explanation, answerSummary });
  const string = "A uniform small-slope ideal string has equilibrium length L=" + lengthNumerator + "/2 m, linear density " + m + "/1000 kg/m and tension " + m * c * c + "/1000 N. Its left endpoint is fixed at x=0.";
  if (variant === "fixed-spectrum") return finish(string + " The right endpoint at x=L is also fixed. For positive mode index n=" + n + ", find wavelength, frequency, period and the number of internal displacement nodes. Find node x_j for j=" + nodeIndex + ", counting the left endpoint as j=0.",
    [phs232Rational("wavelength", "Mode wavelength", lengthNumerator + "/" + n, "m"), phs232Rational("frequency", "Mode frequency", c * n + "/" + lengthNumerator, "Hz"), phs232Rational("period", "Mode period", lengthNumerator + "/" + c * n, "s"), phs232Rational("internal", "Number of internal displacement nodes", String(n - 1)), phs232Rational("node", "Position of the specified node", nodeIndex * lengthNumerator + "/" + 2 * n, "m")],
    ["First derive c=sqrt(F_T/mu). Both fixed ends require a whole number of half-wavelengths along L.", "For n>=1, k_n*L=n*pi, lambda_n=2*L/n and f_n=c/lambda_n.", "Nodes j=0 and j=n are endpoints, so only n-1 nodes are internal. Node positions are j*L/n."],
    ["The medium speed is " + c + " m/s. The selected mode has " + n + " half-wavelengths across the string.", "lambda=" + lengthNumerator + "/" + n + " m; f=" + c * n + "/" + lengthNumerator + " Hz; period=" + lengthNumerator + "/" + c * n + " s.", "There are n+1 nodes including both endpoints, hence " + (n - 1) + " internal nodes.", "The requested node is x_j=j*L/n=" + nodeIndex * lengthNumerator + "/" + 2 * n + " m. Mode n=0 would give a trivial zero sine shape and is excluded."],
    "Wavelength=" + lengthNumerator + "/" + n + " m; frequency=" + c * n + "/" + lengthNumerator + " Hz; internal nodes=" + (n - 1) + "; x_j=" + nodeIndex * lengthNumerator + "/" + 2 * n + " m.");
  if (variant === "mixed-spectrum") {
    const harmonic = 2 * n - 1;
    return finish(string + " Its right endpoint is massless and freely sliding, so transverse slope is zero there. For mode index n=" + n + ", find wavelength, frequency, the harmonic number relative to the fundamental, the number of internal displacement nodes and the last displacement node before the free endpoint.",
      [phs232Rational("wavelength", "Mode wavelength", 2 * lengthNumerator + "/" + harmonic, "m"), phs232Rational("frequency", "Mode frequency", c * harmonic + "/" + 2 * lengthNumerator, "Hz"), phs232Rational("harmonic", "Harmonic number relative to the fundamental", String(harmonic)), phs232Rational("internal", "Number of internal displacement nodes", String(n - 1)), phs232Rational("node", "Last displacement node before the free endpoint", (n - 1) * lengthNumerator + "/" + harmonic, "m")],
      ["The left-fixed shape is sin(k*x). Its slope at L is proportional to cos(k*L), not sin(k*L).", "cos(k*L)=0 gives k*L=(2*n-1)*pi/2 and lambda=4*L/(2*n-1).", "Nodes remain at j*pi/k. The final node has j=n-1, while the right endpoint is a displacement antinode."],
      ["The speed is " + c + " m/s. For n=" + n + ", the positive harmonic number is 2*n-1=" + harmonic + ".", "lambda=" + 2 * lengthNumerator + "/" + harmonic + " m and f=" + c * harmonic + "/" + 2 * lengthNumerator + " Hz.", "The left endpoint is one node; the other n-1 nodes lie inside. The free right endpoint is not a displacement node.", "The last node is x=2*(n-1)*L/(2*n-1)=" + (n - 1) * lengthNumerator + "/" + harmonic + " m. For n=1 this is simply the left endpoint."],
      "Wavelength=" + 2 * lengthNumerator + "/" + harmonic + " m; frequency=" + c * harmonic + "/" + 2 * lengthNumerator + " Hz; harmonic=" + harmonic + "; internal nodes=" + (n - 1) + ".");
  }
  if (variant === "mode-index") {
    const fixed = boundary === 0, h = fixed ? mode === 0 ? 0 : n : mode % 2 === 0 ? 2 * n : 2 * n - 1;
    const valid = fixed ? h > 0 : h % 2 === 1, index = fixed ? h : (h + 1) / 2, residual = fixed || h % 2 ? 0 : (h / 2) % 2 ? -1 : 1;
    const options: [string, string, string][] = Array.from({ length: 6 }, (_, i) => ["mode-" + (i + 1), "Mode " + (i + 1), fixed ? "For two fixed endpoints, positive harmonic number equals mode index; zero gives a trivial shape." : "For fixed-free endpoints, allowed harmonic numbers are 2*n-1; solve for n only when that condition holds."]);
    options.push(["none", "No nontrivial displacement mode", "An endpoint residual or the trivial zero-frequency sine shape can exclude a candidate."]);
    return finish(string + " The right endpoint is " + (fixed ? "fixed" : "massless and free") + ". A candidate has frequency f=" + h + "*f1, where f1 is this boundary configuration's fundamental. Test the shape B*sin(k*x)*cos(omega*t), B nonzero and k=omega/c. Find k*L/pi and the endpoint factor " + (fixed ? "sin(k*L)" : "cos(k*L)") + ", then identify its positive mode index or reject it. A zero-frequency, identically zero sine shape does not count as a nontrivial mode.",
      [phs232Rational("phase", "Dimensionless k*L/pi", h + "/" + (fixed ? 1 : 2)), phs232Rational("residual", "Endpoint sine or cosine factor specified in the prompt", String(residual)), choice("index", "Allowed mode index", valid ? "mode-" + index : "none", options)],
      ["Use this endpoint configuration's fundamental before converting f/f1 to k*L/pi.", fixed ? "For two fixed ends the endpoint factor is sin(k*L). Check the separate nontrivial-shape condition at zero frequency." : "A free endpoint tests cos(k*L). Even multiples of the fixed-free fundamental leave this factor at +1 or -1.", "The mixed-boundary harmonic number is 2*n-1; it is not the mode index itself."],
      ["Here k*L/pi=" + h + "/" + (fixed ? 1 : 2) + ". The specified endpoint factor is " + residual + ".", valid ? "Both endpoints are satisfied by a nontrivial shape, giving positive mode index n=" + index + "." : fixed ? "Although sin(0)=0, k=0 makes B*sin(k*x) zero everywhere. It is not an additional oscillatory displacement mode." : "The nonzero slope factor violates the free-end condition. The candidate is not one of the allowed mixed-boundary modes.", "For a free-free string, a separate rigid translation solution can exist. That is a different boundary configuration and spatial shape."],
      "k*L/pi=" + h + "/" + (fixed ? 1 : 2) + "; endpoint factor=" + residual + "; " + (valid ? "mode n=" + index : "no nontrivial allowed mode") + ".");
  }
  if (variant === "coupled-symmetric" || variant === "coupled-antisymmetric") {
    const symmetric = variant === "coupled-symmetric", sum = a + sign * b, differencePosition = a - sign * b, sumVelocity = u + v, differenceVelocity = u - v;
    const position = symmetric ? sum : differencePosition, velocity = symmetric ? sumVelocity : differenceVelocity, omega = symmetric ? lower : upper;
    const energy = m * (velocity * velocity + omega * omega * position * position), coupling = m * (upper * upper - lower * lower);
    const fields: AnswerField[] = [phs232Rational("position", "Initial normal coordinate", position + "/200", "m"), phs232Rational("velocity", "Initial normal-coordinate velocity", velocity + "/200", "m/s"), phs232Rational("omega", "Normal-mode angular frequency", String(omega), "rad/s"), phs232Rational("energy", "Conserved energy of this normal component", energy + "/400000", "J")];
    if (symmetric) fields.push(choice("shape", "Mass-displacement ratio x2/x1 for this component alone when x1 is nonzero", "same", [["same", "+1", "The symmetric component has equal displacements; it does not stretch the coupling spring."], ["opposite", "-1", "Opposite displacements belong to the antisymmetric component."], ["zero", "0", "A normal component generally moves both masses; one stationary mass is not the symmetric shape."]]));
    else fields.push(phs232Rational("extension", "Initial coupling-spring extension x2-x1", -differencePosition + "/100", "m"), phs232Rational("force", "Initial coupling-spring force on mass 1", -coupling * differencePosition + "/2000", "N"));
    return finish("Two equal masses m=" + m + "/10 kg have wall springs k=" + m * lower * lower + "/10 N/m and a coupling spring k_c=" + coupling + "/20 N/m. Displacements are measured from equilibrium and positive rightward. Initially x1=" + a + "/100 m, x2=" + sign * b + "/100 m, v1=" + u + "/100 m/s and v2=" + v + "/100 m/s. Analyze q_" + (symmetric ? "plus=(x1+x2)/2" : "minus=(x1-x2)/2") + ". Find its initial position/velocity, angular frequency and conserved modal energy." + (symmetric ? " Identify the mass-displacement ratio for this component alone." : " Also find the initial coupling extension and its signed force on mass 1.") + " Use the stated half-sum/half-difference normalization; modal energy is not just one mass's energy.",
      fields,
      ["Add or subtract the original equations m*x1_tt=-(k+k_c)*x1+k_c*x2 and m*x2_tt=k_c*x1-(k+k_c)*x2.", symmetric ? "The symmetric coordinate obeys m*q_plus_tt=-k*q_plus. The coupling spring is unchanged in this component alone." : "The antisymmetric coordinate obeys m*q_minus_tt=-(k+2*k_c)*q_minus. The factor two comes from relative motion of both masses.", "With the chosen coordinate normalization, modal energy is m*q_t² plus its restoring coefficient times q². Reconstructing both masses supplies this energy, without an extra factor 1/2."],
      ["Initial q=" + position + "/200 m and q_t=" + velocity + "/200 m/s, obtained by the stated half-" + (symmetric ? "sum" : "difference") + ".", "The effective coefficient is " + (symmetric ? "k" : "k+2*k_c") + ", giving omega=" + omega + " rad/s.", "The conserved modal energy is " + energy + "/400000 J. This can vanish if that component is absent even though its natural frequency remains a property of the system.", symmetric ? "The symmetric shape is (1,1); x2/x1=+1 whenever the denominator is nonzero. This statement describes that component, not necessarily the full mixed motion." : "The initial relative extension is x2-x1=" + -differencePosition + "/100 m, and force on mass 1 is k_c*(x2-x1)=" + -coupling * differencePosition + "/2000 N.", upper === lower ? "Here k_c=0: the frequencies coincide and the masses are uncoupled. The chosen symmetric/antisymmetric coordinates remain valid but are not uniquely selected by distinct frequencies." : "The full physical energy is the sum of both modal energies and also equals both mass kinetic/wall-spring energies plus the coupling-spring energy."],
      "q(0)=" + position + "/200 m; q_t(0)=" + velocity + "/200 m/s; omega=" + omega + " rad/s; modal energy=" + energy + "/400000 J.");
  }
  const secondFrequency = frequencyBase + difference, maximum = a + b, minimum = difference === 0 ? maximum : Math.abs(a - b);
  const fields: AnswerField[] = [phs232Rational("frequency", "Beat frequency of the nonnegative magnitude", String(difference), "Hz"), phs232Rational("mean", "Mean of the two frequencies", 2 * frequencyBase + difference + "/2", "Hz"), phs232Rational("maximum", "Largest magnitude envelope", maximum + "/1000", "m"), phs232Rational("minimum", "Smallest magnitude envelope over all time", minimum + "/1000", "m")];
  if (difference > 0) fields.push(phs232Rational("period", "Magnitude beat period", "1/" + difference, "s"));
  else fields.push(choice("period", "Beat-cycle period", "none", [["none", "No beat cycle: the magnitude is constant", "Equal frequencies and fixed equal phase produce one constant-amplitude sinusoid."], ["zero", "Zero seconds", "Zero frequency does not imply a zero period; no repeated beat maximum/minimum cycle exists."]]));
  if (a === b && difference > 0) fields.push(phs232Rational("signed", "Period of the signed cosine modulation factor", "2/" + difference, "s"));
  return finish("At one observation point, two coherent signals add: y(t)=(" + a + "/1000)*cos(2*pi*" + frequencyBase + "*t)+(" + b + "/1000)*cos(2*pi*" + secondFrequency + "*t), in meters, with t in seconds. Find the beat frequency, mean frequency and maximum/minimum of the nonnegative magnitude envelope. Give the beat period or identify its absence." + (a === b && difference > 0 ? " Since the amplitudes are equal, also give the period of the signed cosine modulation factor in the exact sum-to-product identity." : "") + " The envelope is a bound on displacement; it need not be a turning-point curve when the frequencies are not very close.",
    fields,
    ["The squared magnitude is A²+B²+2*A*B*cos(2*pi*(f2-f1)*t). Distinguish magnitude from a signed modulation factor.", difference === 0 ? "Here the relative phase never changes, so the two positive amplitudes remain in phase. The minimum is not |A-B|." : "A nonzero difference sweeps every relative phase: the magnitude ranges from |A-B| to A+B and repeats every 1/|f2-f1|.", "For equal amplitudes, the signed factor is cos(pi*(f2-f1)*t). It changes sign after one magnitude beat and returns after two."],
    ["The separation is " + difference + " Hz and the mean frequency is " + (2 * frequencyBase + difference) + "/2 Hz.", difference === 0 ? "The same-frequency in-phase signals reduce to one sinusoid of amplitude " + maximum + "/1000 m. Maximum and minimum envelope values agree, and there is no beat-cycle period." : "The magnitude ranges from " + minimum + "/1000 to " + maximum + "/1000 m and repeats after 1/" + difference + " s.", a === b && difference > 0 ? "The exact identity is y=2*A*cos(2*pi*f_mean*t)*cos(pi*Delta_f*t). The signed modulation period is 2/" + difference + " s; its absolute value repeats twice as often." : "For unequal amplitudes, cancellation may be incomplete. The magnitude formula remains exact; a slowly varying interpretation additionally requires a small separation compared with the carrier frequencies.", "A displacement envelope does not by itself determine physical energy transfer in a coupled system. Velocities and coupling-spring energy must also be included."],
    "Beat frequency=" + difference + " Hz; mean=" + (2 * frequencyBase + difference) + "/2 Hz; envelope range " + minimum + "/1000 to " + maximum + "/1000 m; " + (difference ? "magnitude period=1/" + difference + " s" : "no beat cycle") + ".");
}
