import { questionSchema,type Question } from "../contracts";
import { cc,cr,yesNo } from "../families/f08-fields";
import { parseRational,formatRational } from "../rational";
import { parsePolynomial,evaluatePolynomial } from "../polynomial";
import { recoverInitial,secantSlope } from "./calculus";
export type CalculusMode="limit"|"secant"|"chain"|"accumulation"|"initial";
export type CalculusCurve={label:string;points:[number,number][];openStart?:boolean;openEnd?:boolean;area?:boolean};
export type CalculusModel={question:Question;curves:CalculusCurve[];points?:[number,number][];rows:(string|number)[][];caption:string;xLabel:string;yLabel:string};
function checked(...numbers:number[]){if(numbers.some(n=>!Number.isFinite(n)||Math.abs(n)>10000))throw Error("Use finite values within the activity range.");}
const sample=(f:(x:number)=>number,from:number,to:number):[number,number][]=>Array.from({length:41},(_,i)=>{const x=from+(to-from)*i/40;return[x,f(x)];});
const question=(mode:CalculusMode,prompt:string,fields:unknown[],explanation:string[]):Question=>questionSchema.parse({id:"calculus-lab-"+mode,familyId:"guided-calculus-"+mode,familyVersion:1,courseId:"f08",objectiveId:"investigation",category:"application",critical:false,prompt,fields,hints:["Identify the quantity to predict before revealing the table.","Use the stated function, interval, and domain conditions.","Compare exact results with your prediction, then change one control and explain why."],explanation,answerSummary:explanation.join(" ")});
export function limitInvestigation(center:number,left:number,right:number,value:number):CalculusModel{
 checked(center,left,right,value);
 const agrees=left===right,continuous=agrees&&left===value;
 return{question:question("limit",`For x<${center}, f(x)=${left}+(x-(${center})); for x>${center}, f(x)=${right}-(x-(${center})); at the junction, f(${center})=${value}. Predict the approaches and continuity.`,[cr("left","Predicted left-hand limit",String(left)),cr("right","Predicted right-hand limit",String(right)),yesNo("exists","Finite two-sided limit?",agrees,"The two approach values must agree.","A jump between approach values prevents a two-sided limit."),yesNo("continuous","Continuous at the junction?",continuous,"The common limit must also equal the point value.","Changing an isolated point cannot repair unequal one-sided limits.")],[`The approaches are ${left} and ${right}; the point value is ${value}.`,agrees?continuous?"The common limit matches the point: continuity holds.":"The limit exists but does not match the point.":"No two-sided limit exists."]),curves:[{label:"Left branch",points:[[center-2,left-2],[center,left]],openEnd:true},{label:"Right branch",points:[[center,right],[center+2,right-2]],openStart:true}],points:[[center,value]],rows:[...[-1,-.1,-.01].map(h=>[`f(${center+h}) from left`,Number((left+h).toFixed(6))]),["Assigned point value",value],...[.01,.1,1].map(h=>[`f(${center+h}) from right`,Number((right-h).toFixed(6))]),["Two-sided finite limit",agrees?String(left):"Does not exist"]],caption:"Approach values and the independent point value",xLabel:"x",yLabel:"f(x)"};
}
export function secantInvestigation(a:number,b:number,base:number,h:number):CalculusModel{
 checked(a,b,base,h);const f=parsePolynomial(`${a}x^2+${b}x`),s=secantSlope(f,parseRational(String(base)),parseRational(String(h))),slope=2*a*base+b,fn=(x:number)=>a*x*x+b*x,value=fn(base),sec=Number(s.numerator)/Number(s.denominator),lo=base-Math.max(2,Math.abs(h)),hi=base+Math.max(2,Math.abs(h));
 return{question:question("secant",`For f(x)=${a}x²+(${b})x, base x=${base}, and nonzero h=${h}, predict the finite secant slope and tangent slope at the base.`,[cr("secant","Predicted secant slope",formatRational(s)),cr("tangent","Predicted tangent slope",String(slope))],[`The secant slope is ${formatRational(s)}, while the tangent slope is ${slope}.`,"The original quotient remains undefined at h=0; its limit can still exist."]),curves:[{label:"Function",points:sample(fn,lo,hi)},{label:"Finite secant",points:sample(x=>value+sec*(x-base),lo,hi)},{label:"Limiting tangent",points:sample(x=>value+slope*(x-base),lo,hi)}],points:[[base,value],[base+h,fn(base+h)]],rows:[...[-1,-.5,-.1,.1,.5,1].map(delta=>[`Secant with h=${delta}`,Number((a*(2*base+delta)+b).toFixed(6))]),["Current finite secant",formatRational(s)],["Tangent slope",slope]],caption:"Finite slopes approaching the derivative",xLabel:"x",yLabel:"f or line"};
}
export function chainInvestigation(a:number,b:number,n:number,x:number):CalculusModel{
 checked(a,b,n,x);if(!Number.isInteger(n)||n<2||n>4)throw Error("Choose an integer outer power from two to four.");
 const inner=a*x+b,outer=n*inner**(n-1),result=outer*a,fn=(t:number)=>(a*t+b)**n;
 return{question:question("chain",`For f(x)=(${a}x+(${b}))^${n}, predict the inner value, outer derivative at that value, inner derivative, and full derivative at x=${x}.`,[cr("inner","Inner value",String(inner)),cr("outer","Outer derivative at the inner value",String(outer)),cr("factor","Inner derivative",String(a)),cr("derivative","Composite derivative",String(result))],[`The inner value is ${inner}; outer derivative ${outer} times inner derivative ${a} gives ${result}.`,"A zero or negative inner slope also participates in the product."]),curves:[{label:"Composite function",points:sample(fn,x-.75,x+.75)},{label:"Local tangent",points:sample(t=>fn(x)+result*(t-x),x-.75,x+.75)}],points:[[x,fn(x)]],rows:[["Inner value",inner],["Outer derivative",outer],["Inner derivative",a],["Composite derivative",result],["Actual change for increment 0.1",Number((fn(x+.1)-fn(x)).toFixed(6))],["Tangent change prediction",Number((.1*result).toFixed(6))]],caption:"Two rates combine by multiplication",xLabel:"x",yLabel:"f or tangent"};
}
export function accumulationInvestigation(u:number,v:number,first:number,second:number):CalculusModel{
 checked(u,v,first,second);if(first<=0||second<=0)throw Error("Both interval durations must be positive.");
 const net=u*first+v*second,total=Math.abs(u)*first+Math.abs(v)*second,average=formatRational(parseRational(`(${net})/(${first+second})`));
 return{question:question("accumulation",`Velocity is ${u}m/s for ${first}s, then ${v}m/s for ${second}s. Predict net displacement, total distance, and average velocity.`,[cr("net","Net displacement",String(net),"m"),cr("total","Total distance",String(total),"m"),cr("average","Average velocity",average,"m/s")],[`Signed contributions are ${u*first}m and ${v*second}m, totaling ${net}m. Their absolute contributions total ${total}m. Average velocity is ${average}m/s.`,"Cancellation can give zero displacement while the traveled distance is positive."]),curves:[{label:"First velocity interval",points:[[0,u],[first,u]],area:true},{label:"Second velocity interval",points:[[first,v],[first+second,v]],area:true}],rows:[["First signed contribution",u*first+" m"],["Second signed contribution",v*second+" m"],["Running net after first interval",u*first+" m"],["Final net",net+" m"],["Total distance",total+" m"],["Whole-interval average",average+" m/s"]],caption:"Signed rectangles and accumulated motion",xLabel:"time (s)",yLabel:"velocity (m/s)"};
}
export function initialInvestigation(a:number,b:number,x0:number,y0:number):CalculusModel{
 checked(a,b,x0,y0);const F=recoverInitial(parsePolynomial(`${a}x+${b}`),parseRational(String(x0)),parseRational(String(y0))),constant=formatRational(F[0]),next=x0+2,nextValue=formatRational(evaluatePolynomial(F,parseRational(String(next)))),C=Number(F[0].numerator)/Number(F[0].denominator),fn=(x:number)=>a*x*x/2+b*x+C;
 return{question:question("initial",`Given y′(x)=${a}x+(${b}) and y(${x0})=${y0}, use y(x)=(${a}/2)x²+(${b})x+C. Predict C and y(${next}).`,[cr("constant","Required constant C",constant),cr("next","Value at the second input",nextValue),cc("slope","What does changing C do to the derivative?","same",[["same","Leaves the derivative unchanged","A constant vertical shift has zero derivative."],["adds","Adds C to every derivative value","Differentiate the constant itself: its derivative is zero."],["scales","Multiplies every derivative by C","Adding a constant and scaling the whole function are different operations."]])],[`The required constant is ${constant}, and y(${next})=${nextValue}.`,"The three curves share the same derivative. Only the selected curve matches the supplied initial value."]),curves:[{label:"Selected initial value",points:sample(fn,x0-2,x0+2)},{label:"Constant increased by 2",points:sample(x=>fn(x)+2,x0-2,x0+2)},{label:"Constant decreased by 2",points:sample(x=>fn(x)-2,x0-2,x0+2)}],points:[[x0,y0]],rows:[["Required constant",constant],["Initial condition check",`y(${x0})=${y0}`],["Second point",`y(${next})=${nextValue}`],["Derivative at initial input",a*x0+b],["Derivative after either constant shift",a*x0+b]],caption:"Initial data selects one vertical offset",xLabel:"x",yLabel:"y"};
}
