import calculusPack from "@/content/learning-packs/f08.json";
import calculusPath from "@/content/refresher-paths/f08.json";
import { f08Lessons } from "./f08";
import vectorPack from "@/content/learning-packs/f07.json";
import vectorPath from "@/content/refresher-paths/f07.json";
import { f07Lessons } from "./f07";
import measurementPack from "@/content/learning-packs/f06.json";
import measurementPath from "@/content/refresher-paths/f06.json";
import { f06Lessons } from "./f06";
import pack from "@/content/learning-packs/f01.json";
import l01 from "@/content/lessons/f01/m01-l01.json";
import l02 from "@/content/lessons/f01/m01-l02.json";
import l03 from "@/content/lessons/f01/m01-l03.json";
import l04 from "@/content/lessons/f01/m01-l04.json";
import path from "@/content/refresher-paths/f01.json";
import algebraPack from "@/content/learning-packs/f02.json";
import algebraPath from "@/content/refresher-paths/f02.json";
import { f02Lessons } from "./f02";
import functionsPack from "@/content/learning-packs/f03.json";
import functionsPath from "@/content/refresher-paths/f03.json";
import { f03Lessons } from "./f03";
import trigPack from "@/content/learning-packs/f04.json";
import trigPath from "@/content/refresher-paths/f04.json";
import { f04Lessons } from "./f04";
import explogPack from "@/content/learning-packs/f05.json";
import explogPath from "@/content/refresher-paths/f05.json";
import { f05Lessons } from "./f05";
import { lessonSchema, packSchema } from "../contracts";
import { refresherPathSchema } from "./contracts";

export const refresherPacks = [packSchema.parse(pack), packSchema.parse(algebraPack), packSchema.parse(functionsPack), packSchema.parse(trigPack), packSchema.parse(explogPack), packSchema.parse(measurementPack), packSchema.parse(vectorPack), packSchema.parse(calculusPack)];
export const refresherLessons = [...[l01, l02, l03, l04].map(data => lessonSchema.parse(data)), ...f02Lessons, ...f03Lessons, ...f04Lessons, ...f05Lessons, ...f06Lessons, ...f07Lessons, ...f08Lessons];
export const refresherPaths = [refresherPathSchema.parse(path), refresherPathSchema.parse(algebraPath), refresherPathSchema.parse(functionsPath), refresherPathSchema.parse(trigPath), refresherPathSchema.parse(explogPath), refresherPathSchema.parse(measurementPath), refresherPathSchema.parse(vectorPath), refresherPathSchema.parse(calculusPath)];
export const refresherPath = (courseId: string) => refresherPaths.find(path => path.courseId === courseId);
