import { questionSchema,type Question } from "../contracts";
import { addExact,approximateExact,divideExact,formatExact,multiplyExact,negateExact,parseExact } from "../exact-number";
import { formatRational,parseRational } from "../rational";
import { ze,zp,zr,zs } from "../families/f09-fields";
import { undefinedArgument } from "../families/f09-polar";
import { complexConjugate,complexNormSquared,complexParts,complexPolar,principalDegrees,rootsWithRadius } from "./complex";
export type ComplexMode="arithmetic"|"conjugate"|"polar"|"roots";
export type ComplexArrow={from:[number,number];to:[number,number];label:string};
export type ComplexModel={question:Question;arrows:ComplexArrow[];radius?:number;rows:(string|number)[][];caption:string};
const point=(s:string):[number,number]=>{const p=approximateExact(parseExact(s));return[p.real,p.imaginary];},origin:[number,number]=[0,0];
const checked=(...values:number[])=>{if(values.some(v=>!Number.isFinite(v)||Math.abs(v)>10000))throw Error("Use finite components within the activity range.");};
const question=(mode:ComplexMode,prompt:string,fields:unknown[],explanation:string[]):Question=>questionSchema.parse({id:"complex-lab-"+mode,familyId:"guided-complex-"+mode,familyVersion:1,courseId:"f09",objectiveId:"investigation",category:"application",critical:false,prompt,fields,hints:["Predict using the named operation and the stated representation.","Keep i²=-1, the quadrant, and all nonzero conditions explicit.","Compare the exact result and geometry, then change one control and explain the change."],explanation,answerSummary:explanation.join(" ")});
export function rectangularInvestigation(a:number,b:number,c:number,d:number,operation:"add"|"subtract"|"multiply"):ComplexModel{
 checked(a,b,c,d);const z=parseExact(`${a}+(${b})i`),w=parseExact(`${c}+(${d})i`),result=operation==="add"?addExact(z,w):operation==="subtract"?addExact(z,negateExact(w)):multiplyExact(z,w),value=formatExact(result),parts=complexParts(value),symbol=operation==="add"?"+":operation==="subtract"?"-":"*",first=point(formatExact(z)),second=point(formatExact(w)),tip=point(value);
 return{question:question("arithmetic",`For z=${formatExact(z)} and w=${formatExact(w)}, predict z ${symbol} w, its real part, and its imaginary part. Enter i for the imaginary unit.`,[ze("value","Predicted complex result",value),ze("real","Result real part",parts.real),ze("imaginary","Result imaginary part",parts.imaginary)],[`The result is ${value}, with coordinates (${parts.real},${parts.imaginary}).`,operation==="multiply"?"Multiplication distributes four terms and uses i²=-1. It does not multiply matching coordinates separately.":"Addition or subtraction combines matching coordinates, including the signs on the whole second value."]),arrows:[{from:origin,to:first,label:"z"},{from:operation==="multiply"?origin:first,to:operation==="multiply"?second:tip,label:operation==="subtract"?"-w from the tip of z":operation==="add"?"w from the tip of z":"w"},{from:origin,to:tip,label:"result"}],rows:[["First value",formatExact(z)],["Second value",formatExact(w)],["Operation",operation],["Result",value],["Real part",parts.real],["Imaginary part",parts.imaginary]],caption:"Complex arithmetic and component meaning"};
}
export function conjugateInvestigation(a:number,b:number,c:number,d:number):ComplexModel{
 checked(a,b,c,d);if(c===0&&d===0)throw Error("The denominator is zero. Complex division is undefined; choose a nonzero denominator.");
 const z=`${a}+(${b})i`,w=`${c}+(${d})i`,conjugate=complexConjugate(w),square=complexNormSquared(w),quotient=formatExact(divideExact(parseExact(z),parseExact(w))),check=formatExact(multiplyExact(parseExact(quotient),parseExact(w)));
 return{question:question("conjugate",`For numerator z=${formatExact(parseExact(z))} and denominator w=${formatExact(parseExact(w))}, predict conjugate(w), |w|², and z/w.`,[ze("conjugate","Denominator conjugate",conjugate),zr("square","Denominator squared magnitude",square),ze("quotient","Predicted quotient",quotient)],[`The conjugate is ${conjugate}; the squared magnitude is ${square}; the quotient is ${quotient}.`,`Multiplying the quotient by w recovers ${check}, the original numerator.`]),arrows:[{from:origin,to:point(w),label:"denominator w"},{from:origin,to:point(conjugate),label:"conjugate of w"},{from:origin,to:point(quotient),label:"quotient z/w"}],rows:[["Numerator",formatExact(parseExact(z))],["Denominator",formatExact(parseExact(w))],["Conjugate",conjugate],["Squared magnitude",square],["Quotient",quotient],["Quotient times denominator",check]],caption:"Conjugate reflection and division check"};
}
export function polarInvestigation(radius:number,degrees:number):ComplexModel{
 checked(radius,degrees);if(radius<0)throw Error("Use a nonnegative radius.");
 const value=complexPolar(String(radius),degrees),angle=principalDegrees(degrees),radians=radius===0?"Undefined":formatRational(parseRational(`${angle}/180`))+" pi";
 return{question:question("polar",`The radius is ${radius} and the displayed angle is ${degrees} degrees. Predict the rectangular value and ${radius===0?"whether zero has a defined principal argument":"the principal radian argument in (-pi,pi]"}.`,[ze("value","Predicted rectangular value",value),...(radius===0?[undefinedArgument()]:[zp("argument","Principal radian argument",angle)])],[`The rectangular value is ${value}. ${radius===0?"Zero has no defined argument.":`Its principal angle is ${radians} radians.`}`,"Euler exponentials require radians even when an interface control displays degrees. Full turns preserve the complex point."]),arrows:[{from:origin,to:point(value),label:radius===0?"zero value":"complex value"}],radius,rows:[["Radius",radius],["Displayed angle",degrees+" degrees"],["Rectangular value",value],["Principal argument",radians+(radius===0?"":" radians")]],caption:"Polar coordinates with a radian principal argument"};
}
export function rootsInvestigation(radius:number,n:number,negative:boolean):ComplexModel{
 checked(radius,n);const angle=negative?180:0,roots=rootsWithRadius(radius,angle,n),target=(negative?-1:1)*radius**n;
 return{question:question("roots",`Find all distinct complex roots of z^${n}=${target}. Give the exact root set and the number of distinct roots. This asks for all roots, not only a principal value.`,[zs("roots","Predicted complete root set",roots),zr("count","Number of distinct roots",String(roots.length))],[radius===0?`Only0 is distinct; its multiplicity is ${n}.`:`There are ${n} roots of radius ${radius}, spaced by 360/${n} degrees. Each raised to power ${n} returns ${target}.`,"For a nonzero target, include k=0 through n-1 in the angle formula before taking powers back."]),arrows:roots.map((z,i)=>({from:origin,to:point(z),label:radius===0?"zero root":"root "+(i+1)})),radius,rows:roots.flatMap((z,i)=>[[`Root ${i+1}`,z],[`Root ${i+1} raised to ${n}`,formatExact(parseExact(`(${z})^${n}`))]]),caption:"Every distinct root and its power check"};
}
