import { randomFrom } from "../random";
import type { PracticalCase } from "./practical-contracts";
type OrientationCase=PracticalCase&{kind:string;facts:Record<string,number|string>};
export function f12Case(lessonId:string,seed:string):OrientationCase{
 const random=randomFrom(seed),variant=random.integer(0,2),n=random.integer(2,8);
 if(lessonId==="m01-l01"){
  const minutes=20+random.integer(0,2)*5,gap=random.integer(2,5),topics=[
   {kind:"unit-conversion",name:"minute-to-second conversion",reference:`One minute contains 60 seconds. To convert a duration in minutes to seconds, multiply by 60 s/min. This conversion factor is exact.`,prompt:`Convert ${n} minutes to seconds and explain why the conversion multiplies.`,answer:`${n} min × 60 s/min = ${n*60} s; minute units cancel.`,result:n*60},
   {kind:"function-input",name:"function input and grouping",reference:`The function f(x) = 2(x + 1) adds one to its input, then doubles that sum. Parentheses include both terms.`,prompt:`Find f(${n}) and explain the order of operations.`,answer:`f(${n}) = 2(${n}+1) = ${2*(n+1)}; adding first respects the parentheses.`,result:2*(n+1)},
   {kind:"loop-range",name:"a counted loop boundary",reference:`In Python, range(n) for a positive integer n produces 0 through n-1, one integer at a time. The upper endpoint is excluded.`,prompt:`For range(${n}), give the first value, last value and number of values.`,answer:`The first value is 0, the last is ${n-1}, and there are ${n} values. The upper bound itself is excluded.`,result:n}
  ],topic=topics[variant];
  return{kind:topic.kind,facts:{n,minutes,gap,result:topic.result},title:"A retrieval cycle and return plan",scenario:`You have ${minutes} minutes today and can return in ${gap} days. The topic is ${topic.name}. First read the source briefly, close it, and attempt this prompt: ${topic.prompt}`,reference:topic.reference,task:"Preserve your unaided attempt, reopen the source to check it, record a specific correction or verified detail, then plan the next session with a feasible trigger and fallback.",review:[`An attempted answer to compare after recall: ${topic.answer} Record what you actually wrote before checking, not this sentence as if it were recalled.`,"Check the source and name the exact missing step, boundary or label. If your attempt agrees, identify the detail you verified and choose a harder fresh example.",`One feasible ${minutes}-minute allocation is 4 minutes of recall, 6 of focused review, ${minutes-15} of fresh application and 5 to check and plan. Arrange a return in ${gap} days with a specific cue and a new example.`,"A fallback can be a five-minute recall-and-check cycle, followed by a rescheduled application. Adjust the plan using what you can actually retrieve; this record does not prove lasting retention."]};
 }
 if(lessonId==="m01-l02"){
  const initial=random.integer(1,5)*10,time=random.integer(1,5),offset=random.integer(1,4)*5,rate=random.integer(1,5)*100;
  const passages:Array<{kind:string;passage:string;symbols:string;example:string;condition:string;facts:Record<string,number>}>= [
   {kind:"rate-passage",passage:`For a tank with no outflow and constant inflow q = ${n} L/min, V(t) = V₀ + qt for 0 ≤ t ≤ 10 min. Here V₀ = ${initial} L is the initial volume. Find V(${time}) and state the model conditions.`,symbols:"V(t) is volume in L at time t in min; V₀ labels initial volume, not V times zero; q is inflow in L/min.",example:`V(${time}) = ${initial} + ${n} × ${time} = ${initial+n*time} L. Subtracting the initial volume recovers ${n*time} L added.`,condition:"The claim assumes constant inflow, no outflow, and the stated time interval. Ask whether the rate remains steady.",facts:{n,initial,time,result:initial+n*time}},
   {kind:"function-passage",passage:`A hypothetical sensor model is f(x) = ${n}x + ${offset} mV when x is temperature in °C between 0 and 30. The slope is ${n} mV/°C. Read f(${time*5}) and state what the model does not establish outside its domain.`,symbols:"x is the temperature input in °C; f(x) is a voltage output in mV, not f multiplied by x; the slope carries mV/°C.",example:`f(${time*5}) = ${n} × ${time*5} + ${offset} = ${n*time*5+offset} mV. At x = 0, the output is the offset ${offset} mV.`,condition:"The supplied model applies only to 0–30 °C. Ask how it was checked at additional temperatures; the formula alone does not justify extrapolation.",facts:{n,offset,input:time*5,result:n*time*5+offset}},
   {kind:"sampling-passage",passage:`Uniform samples are taken at rate r = ${rate} samples/s. Their interval is T = 1/r seconds. With the first sample labeled n = 0 at t₀ = 0, tₙ = nT. Find the time of sample n = ${n} and distinguish its index from the number of samples through that point.`,symbols:"r is sample rate in samples/s; T is interval in s; n is a dimensionless index; tₙ is the time labeled by n, not time multiplied by n.",example:`T = 1/${rate} s; tₙ = ${n}/${rate} s. There are ${n} intervals but ${n+1} sample instants from index 0 through ${n}, inclusive.`,condition:"Uniform intervals and the index-zero origin are assumptions. Ask whether actual timestamps show missed or irregular samples.",facts:{rate,n,result:n/rate}}
  ],p=passages[variant];
  return{kind:p.kind,facts:p.facts,title:"Read a technical claim carefully",scenario:p.passage,task:"Paraphrase the claim with its conditions, define the symbols and units, check the requested small example, and write a precise follow-up question.",review:[p.condition,p.symbols,p.example,"Keep the equation's conditions beside your paraphrase. A useful question identifies a missing definition, boundary or observation, then names the source or measurement that would resolve it."]};
 }
 if(lessonId==="m01-l03"){
  if(variant===0){const angle=random.integer(0,1)===0?30:90,result=angle===30?.5:1;return{kind:"angle-check",facts:{angle,result},title:"An angle-mode audit",scenario:`You want sin(${angle}°). A note records 'sin(${angle})' without the calculator mode. Establish a benchmark, perform a matching degree or radian check, and explain what that omitted setting could change.`,task:"Use the calculator lab or your own tool. Record the intended angle, actual settings and entry, predicted and observed result, and a recheck.",review:[`The intended input is ${angle} degrees. Select degree mode for the numeric input ${angle}, or convert it to ${angle===30?"π/6":"π/2"} and select radians.`,`A known unit-circle benchmark is ${result}. The sine output is dimensionless.`,`Record the displayed result and exact input. Changing mode while keeping the number ${angle} means a different angle.`,"If the display disagrees, inspect mode and entry before rounding. Verify with the equivalent angle in the other mode; record the observation you actually made."]};}
  if(variant===1){const b=random.integer(2,5),c=random.integer(1,4),numerator=n*(b+c);return{kind:"grouping-check",facts:{n,b,c,numerator,result:n},title:"A grouping audit",scenario:`A written fraction has numerator ${numerator} and denominator (${b}+${c}). A calculator note instead shows ${numerator}/${b}+${c}. Predict both meanings before checking.`,task:"Record the intended fraction, explicit entry, prediction, actual calculation and correction. State whether angle mode matters.",review:[`The intended entry is ${numerator}/(${b}+${c}); the entire sum belongs in the denominator. Angle mode is irrelevant.`,`The grouped denominator is ${b+c}, so the intended result is ${n}.`,`The ungrouped entry means (${numerator}/${b})+${c}, which is a different operation sequence. Record what your tool actually shows.`,`Repair the parentheses, then check by multiplication: ${n} × ${b+c} = ${numerator}. A matching result checks this entry, not every future input.`]};}
  const exponent=random.integer(2,5),result=n*10**(-exponent);
  return{kind:"scientific-check",facts:{n,exponent,result},title:"A scientific-notation audit",scenario:`A tool display uses ${n}e-${exponent} to mean ${n} × 10 raised to minus ${exponent}. Write the intended value, predict its scale, and check an equivalent decimal entry.`,task:"Explain the display convention, record the predicted and observed decimal, and verify the exponent's sign. Angle mode does not affect this arithmetic.",review:[`In the stated display convention, e-${exponent} means times 10 to the negative ${exponent}; it is not Euler's number.`,`The value is positive and below 1: ${result}.`,`Check by multiplying by 10^${exponent}; the result should return to ${n}. Record the decimal your tool actually displays.`,"Keep the sign in the exponent distinct from a leading negative sign. Displayed zeros or rounding settings do not change the intended exact power-of-ten expression."]};
 }
 if(lessonId==="m01-l04"){
  const revision=random.integer(1,4),marker=String(random.integer(1000,9999)),topic=["angles","loop-traces","unit-checks"][variant],names=["version-choice","restore-review","reopen-check"],situations=[
   `A study folder contains ${topic}-r0${revision}.json and ${topic}-r0${revision+1}.json. Their revision labels suggest an order, but neither has been reopened. Propose how to identify the intended copy without deleting either.`,
   `A hypothetical older progress export contains a note marked CHECK-${marker}. Your current browser notes contain a later correction. Explain how you would review the older file without losing the newer work.`,
   `Two files have the same visible name after being copied to different folders. The intended note contains marker CHECK-${marker}. Explain what content comparison can establish that the name alone cannot.`
  ];
  return{kind:names[variant],facts:{revision,marker,topic},title:"A file and recovery rehearsal",scenario:situations[variant],task:"Use the harmless file tool above to download and reopen a practice file. Record the actual filename and verified marker/note, then write a naming rule, progress-backup plan and response to the supplied situation.",review:["Choose a stable topic/folder and an explicit revision, for example study/f12/tool-check-r02.json. A filename describes a file; it does not verify its contents or convert its format.","Actually download and select the small practice file, then record its observed filename, marker, revision and matching note. Do not report a successful reopen if you only planned one.","For real progress, save drafts and export the current state first. Inspect the chosen backup and its import review in Settings. Replacement is not a merge; an older file can omit newer notes.","Keep an unreadable or mismatched original, locate another copy, and verify that it opens and contains expected work. Plan an independent copy in another suitable location and a future readability check. This rehearsal does not itself prove recovery of all real progress."]};
 }
 throw Error("Unknown study-orientation lesson");
}
