import { questionSchema, type Question } from "../contracts";
import { measurementField as field } from "../families/f06-fields";
import { boundsField } from "../families/f06-uncertainty";
import { canonical, convertPrefix, decimalNumber, roundAt, roundSignificant, significantInfo, symmetricBounds, withinBounds } from "./measurement";
export type MeasurementMode="prefix"|"conversion"|"dimensions"|"rounding"|"measurement";
export type MeasurementModel={question:Question;rows:(string|number)[][];caption:string;scale?:{center:number;lower:number;upper:number;reference:number}};
const choice=(id:string,label:string,correct:string,options:[string,string][])=>({id,kind:"choice",label,correct,options:options.map(([id,label])=>({id,label,feedback:"Check the explicit definition and the supplied assumptions before choosing."}))});
const q=(mode:string,prompt:string,fields:unknown[],explanation:string[]):Question=>questionSchema.parse({id:"measurement-lab-"+mode,familyId:"guided-measurement-"+mode,familyVersion:1,courseId:"f06",objectiveId:"investigation",category:"application",critical:false,prompt,fields,hints:["Predict before revealing the table.","Write the units, definitions, and any stated bound assumptions.","Change one control after checking, and explain which quantities stay invariant."],explanation,answerSummary:explanation[0]});
export function prefixInvestigation(value:string,from:number,to:number):MeasurementModel{
 const result=convertPrefix(value,from,to),base=convertPrefix(value,from,0),factor=from-to;
 return{question:q("prefix",`Convert ${value} units with prefix exponent ${from} to the same unit with prefix exponent ${to}. Predict the numerical value and the exponent of the conversion factor.`,[field("value","Predicted converted value",result),field("factor","Predicted exponent in the numerical factor 10^n",String(factor))],[`The converted value is ${result}; the numerical factor is 10^${factor}.`,"A smaller unit requires more units for the same quantity. The physical quantity and its sign stay unchanged."]),rows:[["Original number",value],["Conversion factor","10^"+factor],["Converted number",result],["In unprefixed units",base],["Reverse conversion",convertPrefix(result,to,from)]],caption:"One quantity in three unit sizes"};
}
export function conversionInvestigation(value:string,from:number,to:number,power:number):MeasurementModel{
 const result=convertPrefix(value,from,to,power),factor=(from-to)*power;
 return{question:q("conversion",`A length unit has source prefix exponent ${from} and target exponent ${to}. Convert ${value} source units raised to power ${power}. Predict the result and the full factor exponent.`,[field("value","Predicted converted value",result),field("factor","Predicted full factor exponent",String(factor))],[`The whole factor is (10^(${from-to}))^${power}=10^${factor}; the result is ${result}.`,"The power applies to both the number and unit. An inverse unit reverses the conversion exponent."]),rows:[["Unit power",power],["Single-length factor exponent",from-to],["Full factor exponent",factor],["Converted number",result],["Reverse conversion",convertPrefix(result,to,from,power)]],caption:"Raise the complete unit conversion factor"};
}
export function dimensionInvestigation(p:number,t:number,coefficient:number):MeasurementModel{
 if(!Number.isInteger(p)||!Number.isInteger(t)||!Number.isFinite(coefficient))throw Error("Use integer powers and a finite dimensionless coefficient.");
 const length=p,time=t-p,valid=length===1&&time===0;
 return{question:q("dimensions",`A candidate displacement formula is x=${coefficient} v^${p} t^${t}, where v is velocity and the coefficient is dimensionless. Predict its length and time exponents, then check whether it has displacement dimensions.`,[field("length","Predicted length exponent",String(length)),field("time","Predicted time exponent",String(time)),choice("valid","Does it have displacement dimensions?",valid?"yes":"no",[["yes","Yes, but dimensions alone do not prove the model"],["no","No, the dimensional exponents disagree"]])],[`The dimensions are L^${length} T^${time}; the displacement check ${valid?"passes":"fails"}.`,"Changing a dimensionless coefficient cannot be detected by this test. A consistent formula still needs physical justification."]),rows:[["Velocity contribution to L",p],["Velocity contribution to T",-p],["Time-factor contribution to T",t],["Resulting L exponent",length],["Resulting T exponent",time]],caption:"Add exponents when multiplying dimensions"};
}
export function roundingInvestigation(literal:string,mode:"places"|"figures",digits:number):MeasurementModel{
 const info=significantInfo(literal),round=mode==="places"?roundAt(info.value,-digits):roundSignificant(info.value,digits),finer=mode==="places"?roundAt(info.value,-digits-1):roundSignificant(info.value,digits+1);
 return{question:q("rounding",`Round ${literal} to ${digits} ${mode==="places"?"decimal places":"significant figures"}, using nearest with exact ties away from zero. Predict the numerical value and select the complete written report.`,[field("value","Predicted rounded numerical value",round.value),choice("report","Predicted written report","right",[["right",round.display],["finer",finer.display],["original","Keep the original text "+literal]])],[`The requested report is ${round.display}.`,"Numerically equal strings can report different precision. Keep guard digits during a calculation and round the final report under a stated convention."]),rows:[["Exact input",info.value],["Original significant digits",info.count??"Not determined by this notation"],["Rounding grid place",round.place],["Reported value",round.display]],caption:"Value and written precision are separate"};
}
export function measurementInvestigation(value:string,resolution:string,additional:string,reference:string):MeasurementModel{
 if(decimalNumber(resolution)<=0||decimalNumber(additional)<0)throw Error("Resolution must be positive and the additional bound nonnegative.");
 const total=canonical(`(${resolution})/2+(${additional})`),bounds=symmetricBounds(value,total),compatible=withinBounds(reference,bounds);
 return{question:q("measurement",`A simulated display reads ${value} V with resolution ${resolution} V. Assume ideal nearest-step rounding plus an independent stated worst-case bound of ±${additional} V. Add these bound contributions conservatively. Predict the complete closed interval and check reference ${reference} V. No statistical confidence level is supplied.`,[boundsField("interval","Predicted conservative output bounds",bounds,"V"),choice("compatible","Predicted reference compatibility",compatible?"yes":"no",[["yes","Within the stated closed interval"],["no","Outside the stated closed interval"]])],[`The combined half-width is ${total} V and the interval is [${bounds.lower}, ${bounds.upper}] V.`,"Adding these stated worst-case bounds is conservative under the supplied model. This is not a claim that display resolution determines total uncertainty."]),rows:[["Rounding contribution",canonical(`(${resolution})/2`)+" V"],["Additional stated bound",additional+" V"],["Combined bound",total+" V"],["Lower endpoint",bounds.lower+" V"],["Upper endpoint",bounds.upper+" V"],["Reference",reference+" V"]],caption:"Conservative bounds under explicit assumptions",scale:{center:decimalNumber(value),lower:decimalNumber(bounds.lower),upper:decimalNumber(bounds.upper),reference:decimalNumber(reference)}};
}
