import { questionSchema,type Question } from "../contracts";
import { ve,vr,vc,vectorFields,vectorText } from "../families/f07-fields";
import { dot,normSquared,projection,vectorAdd,vectorScale,vectorSubtract,type Vector } from "./vectors";
import { trigValue } from "./trig";
import { approximateExact,parseExact } from "../exact-number";
export type VectorMode="components"|"addition"|"dot"|"cross"|"coordinates";
export type VectorArrow={from:Vector;to:Vector;label:string;dashed?:boolean};
export type VectorModel={question:Question;arrows:VectorArrow[];rows:(string|number)[][];caption:string};
const origin=[0,0];
const question=(mode:string,prompt:string,fields:unknown[],explanation:string[]):Question=>questionSchema.parse({id:"vector-lab-"+mode,familyId:"guided-vector-"+mode,familyVersion:1,courseId:"f07",objectiveId:"investigation",category:"application",critical:false,prompt,fields,hints:["Predict from the stated vector operation before revealing the diagram.","Keep the coordinate frame, component signs, and operation order explicit.","Compare the revealed components with your prediction, then change one control and explain the result."],explanation,answerSummary:explanation.join(" ")});
export function componentInvestigation(p:Vector,q:Vector):VectorModel{
 const d=vectorSubtract(q,p),square=normSquared(d);
 return{question:question("components",`Predict the displacement from P=${vectorText(p)} m to Q=${vectorText(q)} m and its magnitude.`,[...vectorFields(d,"m"),ve("magnitude","Displacement magnitude",`sqrt(${square})`,"m")],[`Q-P=${vectorText(d)} m; magnitude sqrt(${square}) m.`,"Translating both endpoints by the same vector preserves their difference."]),arrows:[{from:p,to:q,label:"P to Q"},{from:origin,to:d,label:"same displacement",dashed:true}],rows:[["Initial P",vectorText(p)],["Terminal Q",vectorText(q)],["Displacement",vectorText(d)],["Squared magnitude",square]],caption:"Endpoint difference and equivalent arrow"};
}
export function additionInvestigation(u:Vector,v:Vector,k:number):VectorModel{
 const scaled=vectorScale(u,k),result=vectorAdd(scaled,v),square=normSquared(result);
 return{question:question("addition",`For u=${vectorText(u)} and v=${vectorText(v)} in metres, predict ${k}u+v and its magnitude.`,[...vectorFields(result,"m"),ve("magnitude","Result magnitude",`sqrt(${square})`,"m")],[`The result is ${vectorText(result)} m with magnitude sqrt(${square}) m.`,"Signed scaling acts on every component. Tip-to-tail addition connects the original start to the final endpoint."]),arrows:[{from:origin,to:scaled,label:"k u"},{from:scaled,to:result,label:"v"},{from:origin,to:result,label:"result",dashed:true}],rows:[["Scaled first vector",vectorText(scaled)],["Second vector",vectorText(v)],["Result",vectorText(result)],["Squared result magnitude",square]],caption:"Tip-to-tail component addition"};
}
export function dotInvestigation(u:Vector,v:Vector):VectorModel{
 const proj=projection(u,v),product=dot(u,v),square=normSquared(v),exact=v.map(x=>`${product*x}/${square}`),remainder=vectorSubtract(u,proj);
 return{question:question("dot",`For dimensionless u=${vectorText(u)} and v=${vectorText(v)}, predict u dot v and the vector projection of u onto v.`,[vr("dot","Predicted dot product",String(product)),...exact.map((x,i)=>vr(["x","y"][i],`Predicted projection ${["x","y"][i]} component`,x))],[`The dot product is ${product}; projection coefficient ${product}/${square}.`,"The remainder from the projection tip to u is perpendicular to v. A negative coefficient puts the projection opposite v."]),arrows:[{from:origin,to:u,label:"u"},{from:origin,to:v,label:"v"},{from:origin,to:proj,label:"projection",dashed:true},{from:proj,to:u,label:"remainder",dashed:true}],rows:[["Dot product",product],["Projection",vectorText(exact)],["Remainder",vectorText(remainder.map(x=>x.toFixed(4)))],["Remainder dot target","0"]],caption:"Projection and perpendicular remainder"};
}
export function crossInvestigation(u:Vector,v:Vector,reverse:boolean):VectorModel{
 const first=reverse?v:u,second=reverse?u:v,z=first[0]*second[1]-first[1]*second[0],tip=vectorAdd(first,second);
 return{question:question("cross",`Embed u=${vectorText(u)} m and v=${vectorText(v)} m in the xy plane with zero z components. Predict the z component of ${reverse?"v cross u":"u cross v"} and the triangle area. The axes form a right-handed frame.`,[vr("normal","Signed normal z component",String(z),"m^2"),vr("area","Triangle area",`${Math.abs(z)}/2`,"m^2")],[`The ordered normal is (0,0,${z}) m²; triangle area is ${Math.abs(z)}/2 m².`,"Reversing the edge order reverses the normal and preserves area. Parallel edges enclose zero area."]),arrows:[{from:origin,to:first,label:"first"},{from:origin,to:second,label:"second"},{from:first,to:tip,label:"",dashed:true},{from:second,to:tip,label:"",dashed:true}],rows:[["Ordered cross product",`(0, 0, ${z}) m²`],["Normal orientation",z>0?"+z (out of xy plane)":z<0?"-z (into xy plane)":"Zero; no unique normal"],["Parallelogram area",Math.abs(z)+" m²"],["Triangle area",Math.abs(z)/2+" m²"]],caption:"Planar edges, signed normal, and nonnegative area"};
}
export function coordinateInvestigation(radius:number,angle:number,height:number):VectorModel{
 if(radius<0||!Number.isFinite(radius)||!Number.isFinite(height))throw Error("Use a nonnegative radius and finite height.");
 const exact=[`${radius}*(${trigValue("cos",angle)})`,`${radius}*(${trigValue("sin",angle)})`,String(height)],point=exact.map(x=>approximateExact(parseExact(x)).real);
 return{question:question("coordinates",`Cylindrical point: radius ${radius} m, azimuth ${angle} degrees from +x toward +y, height ${height} m. Predict Cartesian coordinates and whether this point has a unique azimuth in [0,360).`,[...exact.map((x,i)=>ve(["x","y","z"][i],`Cartesian ${["x","y","z"][i]} coordinate`,x,"m")),vc("azimuth","Unique azimuth for this point?",radius===0?"no":"yes",[["yes","Yes within the chosen one-turn interval","A nonzero horizontal projection selects one azimuth in [0,360)."],["no","No, every azimuth gives this axial point","At radius zero there is no horizontal direction to measure."]])],[`Cartesian coordinates are ${vectorText(exact)} m.`,"The plot shows only the xy projection; the table records height separately. Azimuth is not unique at radius zero."]),arrows:[{from:origin,to:point.slice(0,2),label:"xy projection"}],rows:[["x coordinate",exact[0]+" m"],["y coordinate",exact[1]+" m"],["Height z",height+" m"],["Horizontal radius",radius+" m"]],caption:"Top-down projection with separate height"};
}
