"use client";

import Link from "next/link";
import { courses, courseById, resources } from "@/lib/catalog";
import { weekSummary } from "@/lib/progress";
import { useStudy } from "@/lib/study-store";
import { EmptyState, Icon, PageHeading } from "./ui";
import "./dashboard.css";

function PathSketch() {
  return <div className="path-sketch" aria-hidden="true"><span className="sketch-label">A connected way to learn</span><svg viewBox="0 0 260 160" fill="none"><path d="M32 109H75V48H165V109H227" stroke="#bdcab4" strokeWidth="1.4" /><path d="M75 48V129H165V48" stroke="#d9dfcd" strokeWidth="1.3" strokeDasharray="4 4" /><circle cx="32" cy="109" r="16" fill="#edf2e3" stroke="#b1c0a6" /><circle cx="75" cy="48" r="22" fill="#fcfbef" stroke="#aabd99" /><circle cx="165" cy="109" r="26" fill="#476d50" /><circle cx="227" cy="109" r="10" fill="#fcfbef" stroke="#b1c0a6" /><path d="M25 109h14M32 102v14M66 48l6 6 12-12M154 109l7 7 15-15" stroke="#517650" strokeWidth="2" /><path d="M154 109l7 7 15-15" stroke="#eff4dc" strokeWidth="2" /><path d="M98 48h15l5-7 8 14 5-7h13" stroke="#bb7e52" strokeWidth="1.5" /></svg><div className="sketch-steps"><span>Reconnect</span><span>Understand</span><span>Apply</span></div></div>;
}

export function Dashboard() {
  const { data, ready } = useStudy();
  const week = weekSummary(data.sessions);
  const percent = Math.min(100, Math.round(week.minutes / (data.profile.weeklyHours * 60) * 100));
  const next = data.plan.length ? courseById(data.plan[0])! : null;
  const saved = resources.filter(resource => data.bookmarks.includes(resource.id)).slice(0,3);
  return <>
    <PageHeading eyebrow="Your next chapter" title={data.profile.displayName ? `Welcome back, ${data.profile.displayName}.` : "Welcome to your learning space."}>You don&apos;t need to remember everything. You just need a place to begin.</PageHeading>
    <section className="welcome-card"><div className="welcome-copy"><span className="eyebrow">Curiosity is a good starting point</span><h2>A strong foundation.<br />A path of your own.</h2><p>Reconnect with what you know, make room for what&apos;s new, and work toward a deeper understanding of engineering.</p><div className="form-actions"><Link className="button" href="/curriculum">Explore the curriculum <Icon name="arrow" size={16} /></Link><Link className="button quiet" href="/curriculum?group=refresher">Start with a refresher</Link></div></div><PathSketch /></section>
    <div className="overview-stats"><Link href="/curriculum"><span className="stat-icon"><Icon name="book" /></span><div><strong>32 <small>courses mapped</small></strong><span>Your electrical & computer engineering path</span></div><Icon name="arrow" size={15} /></Link><Link href="/curriculum?group=refresher"><span className="stat-icon warm"><Icon name="spark" /></span><div><strong>12 <small>refresher outlines</small></strong><span>Return to the basics when you need them</span></div><Icon name="arrow" size={15} /></Link><Link href="/resources"><span className="stat-icon blue"><Icon name="bookmark" /></span><div><strong>46 <small>resources to explore</small></strong><span>Books, courses, references, and tools</span></div><Icon name="arrow" size={15} /></Link></div>
    <div className="two-columns"><div className="stack">
      <section className="panel"><div className="panel-heading"><h2>Your next step</h2><Link href="/plan">My study plan <Icon name="arrow" size={15} /></Link></div>{!ready ? <p className="loading">Loading your workspace...</p> : next ? <div className="next-course"><div className="next-course-top"><span className="course-code">{next.code}</span><span className="pill neutral">Awaiting course planning</span></div><h3>{next.title}</h3><p>{next.summary}</p><Link href={`/courses/${next.id}`} className="button secondary">Open course outline <Icon name="arrow" size={16} /></Link></div> : <EmptyState icon="list" title="Make your first small plan" action={<Link className="button secondary" href="/curriculum">Choose a course <Icon name="plus" size={15} /></Link>}>Save a course or refresher to give your next study session a direction.</EmptyState>}</section>
      <section className="panel"><div className="panel-heading"><h2>Find your footing</h2><Link href="/curriculum?group=refresher">All refreshers <Icon name="arrow" size={15} /></Link></div><p className="muted section-intro">A little review can make the next idea click. Pick the area that feels most useful.</p><div className="refresher-links">{["f02","f04","f08","f10"].map(id => { const course = courseById(id)!; return <Link href={`/courses/${id}`} key={id}><span className="refresher-number">{course.code.slice(1)}</span><span>{course.title}<small>Optional refresher · outline</small></span><Icon name="arrow" size={14} /></Link>; })}</div></section>
    </div><div className="stack">
      <section className="panel week-panel"><div className="panel-heading"><h2>A little, often.</h2><Icon name="clock" size={18} /></div><div className="week-progress"><div className="goal-ring" role="img" aria-label={`${percent}% of your weekly study goal recorded`} style={{ background: `conic-gradient(var(--green) ${percent}%, #e9eee5 0)` }}><span>{percent}<small>%</small></span></div><div><strong>{(week.minutes / 60).toFixed(1)} <small>/ {data.profile.weeklyHours} hrs</small></strong><p>recorded this week</p></div></div><div className="week-bars" role="group" aria-label="Study time by day">{week.days.map(day => <div key={day.label} role="img" aria-label={`${day.label}: ${day.minutes} minutes`}><div className="bar-track"><span style={{ height: day.minutes ? `${Math.max(8, day.minutes / Math.max(...week.days.map(item=>item.minutes),60) * 100)}%` : "0" }} /></div><small>{day.label.slice(0,1)}</small></div>)}</div><Link href="/plan" className="button secondary full-width">Record a study session</Link></section>
      <section className="panel"><div className="panel-heading"><h2>On your shelf</h2><Icon name="bookmark" size={17} /></div>{saved.length ? saved.map(resource => <a href={resource.url} target="_blank" rel="noreferrer" key={resource.id} className="compact-link"><div><strong>{resource.title}</strong><small>{resource.kind}</small></div><Icon name="external" size={14} /></a>) : <p className="muted section-intro">Save helpful resources as you explore. They&apos;ll be right here when you come back.</p>}<Link className="button quiet" href={saved.length ? "/resources?saved=1" : "/resources"}>{saved.length ? "View saved resources" : "Explore the library"} <Icon name="arrow" size={15} /></Link></section>
    </div></div>
    <section className="coverage-note"><span className="coverage-icon"><Icon name="lab" size={21} /></span><div><strong>Depth before speed. One course at a time.</strong><p>The workspace is ready. Individual courses will move through planning, building, and review before lessons are released.</p></div><span className="pill neutral">{courses.filter(course => course.modules.length > 0).length} learning packs released</span></section>
  </>;
}
