import pack from "@/content/learning-packs/phs-231.json";
import measurement from "@/content/lessons/phs-231/m01-l01.json";
import vectors from "@/content/lessons/phs-231/m01-l02.json";
import motion from "@/content/lessons/phs-231/m02-l01.json";
import frames from "@/content/lessons/phs-231/m02-l02.json";
import projectiles from "@/content/lessons/phs-231/m02-l03.json";
import forces from "@/content/lessons/phs-231/m03-l01.json";
import friction from "@/content/lessons/phs-231/m03-l02.json";
import drag from "@/content/lessons/phs-231/m03-l03.json";
import circular from "@/content/lessons/phs-231/m04-l01.json";
import gravity from "@/content/lessons/phs-231/m04-l02.json";
import work from "@/content/lessons/phs-231/m05-l01.json";
import energy from "@/content/lessons/phs-231/m05-l02.json";
import impulse from "@/content/lessons/phs-231/m06-l01.json";
import materials from "@/content/lessons/phs-231/m08-l03.json";
import elasticity from "@/content/lessons/phs-231/m08-l02.json";
import statics from "@/content/lessons/phs-231/m08-l01.json";
import rolling from "@/content/lessons/phs-231/m07-l03.json";
import angular from "@/content/lessons/phs-231/m07-l02.json";
import rotation from "@/content/lessons/phs-231/m07-l01.json";
import collision from "@/content/lessons/phs-231/m06-l02.json";
import { lessonSchema, packSchema } from "../contracts";

export const phs231Pack = packSchema.parse(pack);
export const phs231Lessons = [lessonSchema.parse(measurement), lessonSchema.parse(vectors), lessonSchema.parse(motion), lessonSchema.parse(frames), lessonSchema.parse(projectiles), lessonSchema.parse(forces), lessonSchema.parse(friction), lessonSchema.parse(drag), lessonSchema.parse(circular), lessonSchema.parse(gravity), lessonSchema.parse(work), lessonSchema.parse(energy), lessonSchema.parse(impulse), lessonSchema.parse(collision), lessonSchema.parse(rotation), lessonSchema.parse(angular), lessonSchema.parse(rolling), lessonSchema.parse(statics), lessonSchema.parse(elasticity), lessonSchema.parse(materials)];
